### ISSUE TITLE
Not all tags shown (website)

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#10]
Reported on [lp#914498](https://bugs.launchpad.net/turnkeylinux/+bug/914498) by @JedMeister on 2012-01-11
#### Description

When browsing forum tags (when in forums, click on 'more tags' in left hand pane, takes you to: http://www.turnkeylinux.org/tagadelic/chunk/9) not all the tags are shown. To me it seems like heaps of them are missing.
##

**Comment by qq7** [comment]
@JedMeister is this still relevant? It doesn't seem like the forum is using tags anymore

**Comment by JedMeister** [comment]
Thanks for the bump on this one @qq7. TBH, I'm not 100% sure, but as you point out, the URL is a 404. IIRC when the site was upgraded from drupal6 to drupal7, we dropped the usage of the "tagadelic"  module (and are now just using the default/built-in tagging stuff).

So I say, let's close this for now and if need be a new issue could be opened with current info...
