### ISSUE TITLE
Piwik is now Matomo

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1003]
As per subject, Piwik have changed their name to Matomo. We'll need to update that for v15.0

**Comment by JedMeister** [comment]
@OnGle has done most of the work and has issued a PR: https://github.com/turnkeylinux-apps/piwik/pull/15

Unfortunately it appears that the upstream debian repo has not yet been updated with the new version. I have contacted one of the devs via email but am yet to hear back.

I also just noticed that there is an issue on Matomo's GitHub account: https://github.com/matomo-org/matomo/issues/12522

As noted on the pull request (https://github.com/turnkeylinux-apps/piwik/pull/15#issuecomment-365448034) we'll wait to hear back on this one before we proceed.

**Comment by JedMeister** [comment]
Heard from upstream devs that the (third party) debian repo package should be available within about 2 weeks.

**Comment by JedMeister** [comment]
The issue to follow regarding the progress of this is here:
https://github.com/matomo-org/matomo-package/issues/62

**Comment by JedMeister** [comment]
latest upstream update (posted yesterday):

> I'm hoping to have version 3.3.0 out in the next 10 days or so. Maybe less but I can't guarantee due to work commitments (I'm presenting at the AWS Sydney Summit). But definitely keep an eye on this issue as I'll update it as soon as it's available.

So hopefully within the next couple of weeks! :smile:

**Comment by JedMeister** [comment]
Still awaiting on Matomo to provide a Debian package. Although, as noted in the PR (https://github.com/turnkeylinux-apps/piwik/pull/15#issuecomment-365448034) we could switch to a zipball install relatively easily. So we shouldn't let that block release.

**Comment by JedMeister** [comment]
@OnGle - it looks like the Matomo package should be good to go now?! Please see towards the end of the thread noted in my [previous comment](https://github.com/turnkeylinux/tracker/issues/1003#issuecomment-378097040)

**Comment by OnGle** [comment]
As far as I can tell this is done, closing.
