### ISSUE TITLE
Revision Control Appliance shall allow modifications of commit message

### ISSUE THREAD

**Issue by mkarg** [turnkeylinux/tracker#101]
It would be great if the SVN installation of the Revision Control Appliance would allow modifications of commit messages, as described in this article: http://subversion.apache.org/faq.html#change-log-msg
##

**Comment by JedMeister** [comment]
This didn't make it into v15.0 unfortunately, so moving to v15.1.

**Comment by JedMeister** [comment]
Looking at this again, I'm not completely sure that there is a lot of value in me researching, implementing and testing this addition. Whilst I get that SVM still exists and some SVN users may find this feature useful. However, the SVN user base is constantly shrinking and I have never actually used it in the real world.

So whilst I'm still open to including this, TurnKey is not going to investigate and research it, nor do the implementation and testing required.

However, if a TurnKey user could at the very least explicitly document what needs to be done, then we would be willing to look at implementation and testing it as a feature.

For now I'm going to downgrade this to a "wishlist' item. I may well close it at a later date if there is no further progress.

**Comment by JedMeister** [comment]
Moving this to v17.0 milestone.

Pull requests are welcome. If you're not sure how it all works, then I'm more than happy to provide coaching as needed (just ask). If you can use bash, you can tweak appliances! :smile:

**Comment by JedMeister** [comment]
Actually I'm going to close this one for now...
