### ISSUE TITLE
Double check and if need be adjust default opcache settings

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1013]
I recently pushed an [update](https://github.com/turnkeylinux/common/commit/2349a9fd39f9187be6fb217ba19fc79309d8bb77) to `stretch-dev` beranch of common which adjusts the default PHP settings in `php.ini`. 

As part of that process, I noticed that even though opcache is not explicitly enabled in the `php.ini` that it is actually enabled and running by default. I discovered that that was via `opcache.ini` (found at `/etc/php/X.Y/mods-available/opcache.ini` - where `X.Y` is the version, e.g. `5.6`/`7.0`).

After making the changes to common, whilst I checked that LAMP still built and ran correctly, I didn't 100% check that the opcache settings were updated. Furthermore, I just [read](https://github.com/nextcloud/server/issues/5917#issuecomment-318595602) that for opcache settings to be honoured, they actually need to be in the `opcache.ini` file.

I haven't yet confirmed that, but either way, we need to double check that the settings are being applied. If not, my code needs to be updated to write the settings to the `opcache.ini` file rather than `php.ini`.

PS I've labelled this as a bug even though it's more a "todo". That's to ensure it doesn't get forgotten.

**Comment by spaghettimaster** [comment]
The  settings are being applied in both 5.6 and 7.0.

There is no need to update your code.

**Comment by JedMeister** [comment]
Awesome, thanks for checking @spaghettimaster! You rock! :smile: 

We could probably just close this then.

Although, if you'd like to do some additional research and see if there is any (other/better) improvements we could make to default opcache settings, that'd be cool. I don't know tons about it but did a bit of googling and set defaults that I thought might be a good start.

**Comment by JedMeister** [comment]
I'm going to close this. If any specific appliances need tweaks, we can open issues for them.
