### ISSUE TITLE
PostgreSQL 14.2 on AWS: Security Group created by 1-Click launch misses inbound rule for Adminer

### ISSUE THREAD

**Issue by pschneider1968** [turnkeylinux/tracker#1014]
PostgreSQL 14.2 on AWS: 1-Click launch after subscribing from AWS Marketplace does not create an inbound rule for port 12322, so Adminer access initially does not work. Manually adding such a rule to the security group in EC2 console fixes the problem.

Version:
turnkey-postgresql-14.2-jessie-amd64

**Comment by JedMeister** [comment]
Thanks for the heads up. 

Although that is a bit weird as we declare all the ports in the appliance Makefile and you can see that it's clearly there in the [build code](https://github.com/turnkeylinux-apps/postgresql/blob/master/Makefile#L1).

I did consider the possibility that we'd neglected to update the ports at some point recently, but according to GitHub, port 12322 was added [3 years ago](https://github.com/turnkeylinux-apps/postgresql/blame/master/Makefile#L1)!

Whilst, I'm certainly not suggesting that you are wrong, it does surprise me that this hasn't been noted sooner! I haven't checked the AWS stats lately, but I'm sure you're not the only one to launch that appliance in the last 3 years!

I'll have a look into it some time soon. Thanks again for reporting.

**Comment by JedMeister** [comment]
TBH, I don't recall changing anything to do with this, but it no longer appears to be an issue.

FWIW I just checked the default "seller recommended settings" via AWS Marketplace and port 12322 is definitely open by default. There is a possibility that the AWS "1-click" setting may default to a more restrictive default? If that's the case, then unfortunately, there isn't anything we can do about it.
