### ISSUE TITLE
Use php-fpm by default for LAMP/LAPP instead of mod_php

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1015]
As mentioned/discussed in #886 we should move to using php-fpm for LAMP based apps in v15.0.

It's packaged in Debian and should be fairly straight forward.

@spaghettimaster - interested? If so, please self assign. 

Ideally most of it should go in common (as a component of LAMP/LAPP). Although, I'm thinking, that perhaps we need to create a new `mk/turnkey/apache.mk` (or perhaps that should be an `apache-php.mk`?) because there are some appliances that don't include the `lamp.mk` file and it would make it much easier to add this functionality to them (although I haven't double checked so perhaps I'm wrong). 

Regardless, having an `apache.mk` would at least mean less duplication between 'lamp.mk` and `lapp.mk`.

Another thought, (not sure if it's a good one) perhaps we should also consider an `apache-php` plan? (Which the `lamp` and `lapp` plans include). This is perhaps overkill, but maybe we should also consider adding some other plans too, e.g. `php`? And move some of the common php packages into that (and out of appliances)? I know it's more work for no obvious gain, but it might make things a little easier in the longer term...?

Either way, if you take this one, I strongly suggest that you do a bit of an audit of appliances and see what makes the most sense. Open to counter suggestions though. Or we can always just take the path of least resistance and only do this for `lamp.mk`/`lapp.mk` for now?!

**Comment by JedMeister** [comment]
As this will need a fair bit of testing, I'm moving this issue to v15.1. I think we need to push ahead with the v15.0 release and get it done ASAP.

@spaghettimaster if you're interested, please feel free to grab this one?! Although please don't put any time and energy into it until you've run out of all v15.0 related work.

**Comment by JedMeister** [comment]
@spaghettimaster - if you run out of things to do, you could start work on this, although I suggest that to avoid risk of breaking things for the v15.0 release, that I create a new v15.1 branch which you can do PRs against. Or perhaps you could just keep the v15.1 updates separate until v15.0 is finalised?

**Comment by spaghettimaster** [comment]
If we want to use php-fpm we will have to update every appliance that edits `php.ini` file.
And some of appliances, maybe, would not work with php-fpm.

Therefore, I propose to create a separate `mk` for `php-fpm` that we can include to appliance`s Makefiles.

Here is a simple example. 
I created `php-fpm.mk`:
https://github.com/spaghettimaster/common/commit/bdaf0a8ab15e7264787d2af869e16ddec2a9c858 
And used it in the `wordpress` applience:
https://github.com/spaghettimaster/wordpress/commit/7fa7e9ba14c9a2ea90365ca1e8b41a8a30a6b4ac

Are you OK with this realization?
If so I'll open PR.
If not, then let's find another way. :)

**Comment by JedMeister** [comment]
> I propose to create a separate `mk` for `php-fpm` that we can include to appliance`s Makefiles.

Excellent suggestion IMO! :smile:

> Here is a simple example.
> I created php-fpm.mk:
> [...]

Looks good to me mate. Great solution. :+1:

**Comment by JedMeister** [comment]
FWIW, some recent reading I've done suggests that when using Apache in Debian Stretch (what v15.0 is based on) `mod_php` is actually more efficient?! 

I haven't done extensive research, nor have I done any testing myself, so I'm not at all sure, but thought it was worth mentioning.

**Comment by JedMeister** [comment]
I'm going to close this one for now, as I'm not sure that we still want to proceed down this path...
