### ISSUE TITLE
95secupdates

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1018]
firstboot.d/95secupdates determines if a reboot is needed after applying security updates by checking if any files in /lib/modules or /boot have changed. In recent versions of Debian, the /lib/modules directory is no longer used.  The result is that the appliances no longer reboot when needed. The script should be changed to check /var/run/reboot-required.

**Comment by JedMeister** [comment]
Are you sure about that John? 

My research suggests something different. A v15.0 (based on Stretch) Core server I currently have running has files in `/lib/modules`:
```
root@core ~# ls -la /lib/modules /boot
/boot:
total 52824
drwxr-xr-x  3 root root     4096 Feb 23 19:33 .
drwxr-xr-x 23 root root     4096 Feb 23 19:33 ..
-rw-r--r--  1 root root  3185098 Jan  4 22:12 System.map-4.9.0-5-amd64
-rw-r--r--  1 root root  3189623 Feb 22 02:29 System.map-4.9.0-6-amd64
-rw-r--r--  1 root root   186473 Jan  4 22:12 config-4.9.0-5-amd64
-rw-r--r--  1 root root   186567 Feb 22 02:29 config-4.9.0-6-amd64
drwxr-xr-x  5 root root     4096 Feb 23 19:33 grub
-rw-r--r--  1 root root 19133729 Feb 15 11:26 initrd.img-4.9.0-5-amd64
-rw-r--r--  1 root root 19744358 Feb 23 19:33 initrd.img-4.9.0-6-amd64
-rw-r--r--  1 root root  4216608 Jan  4 22:12 vmlinuz-4.9.0-5-amd64
-rw-r--r--  1 root root  4220704 Feb 22 02:29 vmlinuz-4.9.0-6-amd64

/lib/modules:
total 16
drwxr-xr-x  4 root root 4096 Feb 23 19:33 .
drwxr-xr-x 16 root root 4096 Feb 15 11:21 ..
drwxr-xr-x  3 root root 4096 Feb 15 11:12 4.9.0-5-amd64
drwxr-xr-x  3 root root 4096 Feb 23 19:33 4.9.0-6-amd64
```
So even if `/lib/modules` wasn't being used (which it clearly appears to be) then there'd still be new files in `/boot`. So we'd still get a different checksum for the `ls -la /lib/modules /boot | md5sum` that `firstboot.d/95secupdates` uses to check.

Also FWIW, I've never come across the file `/var/run/reboot-required`. A quick google suggests that whilst it does seem to be quite common (at least in Ubuntu) it will only ever get created if one of the following packages is installed:

 - update-notifier-common (deprecated in Jessie, no longer in Stretch)
 - reboot-notifier (new to Stretch)
 - unattended-upgrades

None of those packages are installed by default in Debian AFAIK, although possibly are in Ubuntu. Also we aren't currently installing any of them either (although obviously we could if there was a solid reason).

**Comment by Dude4Linux** [comment]
@JedMeister  Ahh! It's because I'm running in containers.  The containers have the kernel removed so there is no /lib/modules and also no need to reboot (restart) the container.  I just ran turnkey-install-security-updates with the following results:
```
root@lxc-test ~# turnkey-install-security-updates 
+ SEC_UPDATES=FORCE
+ /usr/lib/inithooks/firstboot.d/95secupdates
ls: cannot access /lib/modules: No such file or directory
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://httpredir.debian.org jessie-backports InRelease [166 kB]
Ign http://httpredir.debian.org jessie InRelease
Ign http://archive.turnkeylinux.org jessie-security InRelease
Ign http://archive.turnkeylinux.org jessie InRelease
Hit http://httpredir.debian.org jessie Release.gpg
Hit http://archive.turnkeylinux.org jessie-security Release.gpg
Hit http://archive.turnkeylinux.org jessie Release.gpg
Hit http://httpredir.debian.org jessie Release
Hit http://archive.turnkeylinux.org jessie-security Release
Hit http://archive.turnkeylinux.org jessie Release
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [506 kB]
Get:4 http://httpredir.debian.org jessie-backports/main amd64 Packages/DiffIndex [27.8 kB]
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Get:5 http://httpredir.debian.org jessie-backports/main Translation-en/DiffIndex [27.8 kB]
Hit http://httpredir.debian.org jessie/main amd64 Packages
Hit http://httpredir.debian.org jessie/contrib amd64 Packages
Hit http://httpredir.debian.org jessie/contrib Translation-en
Hit http://httpredir.debian.org jessie/main Translation-en
Hit http://archive.turnkeylinux.org jessie-security/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://archive.turnkeylinux.org jessie/main amd64 Packages
Ign http://archive.turnkeylinux.org jessie-security/main Translation-en
Ign http://archive.turnkeylinux.org jessie/main Translation-en
Fetched 790 kB in 33s (23.8 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ls: cannot access /lib/modules: No such file or directory
```
It doesn't appear to block the installation of the security updates. I was just following up on all the errors I'm seeing in the logs.  Perhaps the test can be written to skip the checksum if /lib/modules doesn't exist.

**Comment by Dude4Linux** [comment]
It occurs to me that if /lib/modules is missing in a container after the kernel is removed, I can just create an empty directory /lib/modules, and then the updater is happy.  I'll do that and close this issue.

**Comment by JedMeister** [comment]
Ok great one, thanks John.
