### ISSUE TITLE
Consider removing Webshell (aka Shellinabox) - use Webmin's builtin shell instead

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1019]
We had a report that Webshell wasn't working well on iOS devices (see #956). Out of interest, I just tested it myself on Android (as noted: https://github.com/turnkeylinux/tracker/issues/956#issuecomment-370267433) and it was sub-par experience.

I then tried Webmin's shell (as part of the [freshly adopted Authentic theme](https://github.com/turnkeylinux/tracker/issues/781)) and it worked a treat! 

So I'm going to look at removing Webshell (and Stunnel) for v15.0.

PS the only thing it doesn't seem to do is colorize the text.

![screenshot from 2018-03-05 08-38-22](https://user-images.githubusercontent.com/818633/36951064-14626698-2053-11e8-8a44-8fb85245a8c0.png)
![screenshot from 2018-03-05 08-38-31](https://user-images.githubusercontent.com/818633/36951065-16ef6870-2053-11e8-81bb-6c01c052668d.png)
![screenshot from 2018-03-05 08-39-05](https://user-images.githubusercontent.com/818633/36951067-195aa9a8-2053-11e8-9362-d19e18a29971.png)

**Comment by JedMeister** [comment]
Whilst I'm still keen for this, I am at least temporarily putting this on hold. I noticed that the shell doesn't pick up the default colorization. 

I reported it upstream (https://github.com/qooob/authentic-theme/issues/1037) in the hope that it could be adjusted. But it turns out that may not be so easy. And actually, it's a pseudo-shell, not actually a proper shell. So until Webmin update their Shellinabox integration (last commit 2009) then I don't think this is going to be much good for us...

**Comment by JedMeister** [comment]
The upstream devs are on he job and hopefully we will have a proper shell available within Webmin at some future point. As such, I'm going to move this to the v15.1 milestone.

**Comment by datavectors** [comment]
This topic seems to covered in different threads.
I added some notes here .. on colourisation work around ..

https://github.com/qooob/authentic-theme/issues/1037

Note that colour themes can be used in butterfly.

**Comment by JedMeister** [comment]
Putting "on ice" for now as it really depends on Webmin support for a "proper" interactive terminal client (see https://github.com/turnkeylinux/tracker/issues/1019#issuecomment-379824593 above).

**Comment by OnGle** [comment]
closed by https://github.com/turnkeylinux/common/pull/255
