### ISSUE TITLE
Consider bundling OpenVPN user creation script

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1020]
I just accidentally came across a [user creation script](https://gist.github.com/gdarko/a9ae4b0745c36b72a0296db61d69a0fb) for our OpenVPN appliance.

I haven't looked at it closely, but from a glance it looks like it might be worth consideration for inclusion of a future release?!

**Comment by OnGle** [comment]
We already bundle a script which creates users and have done so since 2013 (introduced here https://github.com/turnkeylinux-apps/openvpn/commit/f647911ef4953b460bf66323331d4fbafc335ec1#diff-92f5a664d6131e0032b9c4291e4741d5c83b9764cc8f1e544f300d5e6a9ca10f )

**Comment by JedMeister** [comment]
Hmm, not sure what was going on in my head that day...
