### ISSUE TITLE
Investigate updating turnkey-make-ssl-cert?

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1023]
Stuart noted in a [comment](https://www.turnkeylinux.org/comment/28567#comment-28567) that the `turnkey-make-ssl-cert` tool isn't making a proper `.crt` file, it's actually generating a certificate, which his CA is not accepting.

I'm not very familiar with SSL but that doesn't seem right to me. 

Any ideas @Dude4Linux?

**Comment by Dude4Linux** [comment]
@JedMeister The turnkey-make-ssl-cert followed StartCom's instructions for preparing a request and it was the only cert supplier that I tested against.  My guess is that Stuart is correct and it's not making a proper .crt file.  It would take some research, but it could be fixed for 15.0.

**Comment by l-arnold** [comment]
My experience is that the CRT is not actually sent to the SSL provider.  The CSR is sent to them, against which they generate the CRT.

Where would a Turnkey Generated CRT be sent to an SSL provider?

**Comment by Dude4Linux** [comment]
@JedMeister @l-arnold is correct. turnkey-make-ssl-cert with the --csr option produces three files, a .csr certificate request, a .crt temporary certificate used while waiting, and a .key key file used to sign the other two files.  I've asked Stuart to look for the .csr file and try submitting that.  If he confirms that the .csr was accepted, then we can close this as works as designed.

**Comment by JedMeister** [comment]
Thanks @Dude4Linux & @l-arnold 

My mistake! You are both correct. It was actually the CSR we needed! 

The script still doesn't work quite the way I think it ideally should, but I'm not going to even look at that at this point. I image that most users these days would be using Let's Encrypt.

This particular scenario is on an intranet, with a local CA, which I imagine is a bit of a corner case these days.

**Comment by JedMeister** [comment]
I've just changed this to  feature request, as well as updating the subject. I could probably do better still, and I'm not even sure that we'll bother (now that we have Let's Encrypt) but I figured we may as well leave the issue here, for now at least.

Bottom line is, if we plan to keep it and keep using it, it should perhaps be a little more intuitive. I don't mean that as a complaint against you John. You've done a great job with it and it's served us quite well over the years. But it could probably do with some tweaking.

**Comment by Dude4Linux** [comment]
When I wrote turnkey-make-ssl-cert, I had two goals in mind
1. The default certs at that time were failing the security tests (too short)
2. I was manually preparing CSR's for my proposed business, linuxgeeks.biz
For the second, I wanted an easy to use method that didn't require installing and running a CA certificate authority.
No project is ever complete, but I can think of two areas that could be improved.  In the current program, certs/keys are generated and installed in /etc/ssl/.. Only the default cert.pem is installed in the applications e.g. apache, nginx, etc.  The script could be improved to handle installing non-default certs into the applications, but that would take a significant effort.  The second area is documentation.  I looked and couldn't find anything other than the built in help.  When I get home (about a month) I'd be happy to take a look at writing some usage documentation along with examples of how to use the script.

**Comment by JedMeister** [comment]
> When I get home (about a month) I'd be happy to take a look at writing some usage documentation along with examples of how to use the script.

If you feel like it John. But as I said above, I'm not sure how much it will get used these days, now that Let's Encrypt is a thing. I think it was just coincidental that 2 users recently wanted to use third party certs so this came up. As I've noted elsewhere, it was probably more my lack of understanding than a bug that caused the main issue I was having...

**Comment by JedMeister** [comment]
FWIW for v16.0, I've tweaked `turnkey-make-ssl-cert` to also (re)generate the `dhparams.pem` file too. 

Considering that `turnkey-make-ssl-cert` is still serving it's purpose perfectly well, and most users are probably using Let's Encrypt certs these day anyway, I'm going to just close this.
