### ISSUE TITLE
Download locations appear to be broken

### ISSUE THREAD

**Issue by skammerdiener** [turnkeylinux/tracker#1025]
I tried to download several Turnkey applications, but the OVA link sent me to a jump page that redirected to Soourceforge and that had a message that the files were no longer hosted there. I was trying to get Mayan-EDMS, but it happened with Joomla, Worpress and others as well when I tried some more common ones.

Takes you to https://sourceforge.net/projects/turnkeylinux/files/

**Comment by JedMeister** [comment]
Thanks for the report! That's a major issue!

I've just emailed the web development company that did the deployment of the refreshed site (today) to look into and resolve it.

In the meantime, you can download images directly from the mirror. You'll find the OVAs here:
http://mirror.turnkeylinux.org/turnkeylinux/images/ova/

**Comment by JedMeister** [comment]
Should be fixed now. Closing.
