### ISSUE TITLE
Observium Appliance cannot ping new devices 

### ISSUE THREAD

**Issue by twister5800** [turnkeylinux/tracker#1026]
Hi,

You will get an error when adding new devices in observium, this can be fixed with:
chmod +s /usr/bin/fping

Regards
martin

**Comment by JedMeister** [comment]
Hi @twister5800 - please see #488

**Comment by twister5800** [comment]
Sorry about that, when will you update and implement?

**Comment by JedMeister** [comment]
No need to apologise! :smile: 

We won't be changing this because of the security implications. As noted in the issue we linked to, we do need to find a better way to bring that to user's attention, but we won't be implementing that by default. As noted in one comment:

> Was just about to implement this fix however I found on the Observium docs it advises against using the web interface to add devices anyway. Please see http://www.observium.org/docs/add_device/

**Comment by twister5800** [comment]
Ahh makes sense, well my observium is only living on the lan, so I’m not that worried 😊

Thanks.

Fra: Jeremy Davis [mailto:notifications@github.com]
Sendt: 15. marts 2018 22:15
Til: turnkeylinux/tracker <tracker@noreply.github.com>
Cc: Martin Lindemann Frederiksen <martin@mlf.dk>; Mention <mention@noreply.github.com>
Emne: Re: [turnkeylinux/tracker] Observium Appliance cannot ping new devices (#1026)


No need to apologise! 😄

We won't be changing this because of the security implications. As noted in the issue we linked to, we do need to find a better way to bring that to user's attention, but we won't be implementing that by default. As noted in one comment:

Was just about to implement this fix however I found on the Observium docs it advises against using the web interface to add devices anyway. Please see http://www.observium.org/docs/add_device/
