### ISSUE TITLE
Drupal8 trusted host patterns are not being generated in containers 

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1029]
https://github.com/turnkeylinux-apps/drupal8/pull/7 was the last attempt to fix the 'trusted host issue'.  Rather than try to guess the possible host names that might be used, especially in a container which may be named pretty much anything by the user, I think a different strategy is in order.  We have two choices,
1) comment out the three lines in settings.php that enable trusted host patterns
```
#$settings['trusted_host_patterns'] = array(
#     '^www\.example\.com$',
#);
```
or 
2) derive the hostname and domain on the fly
```
# host $(host $(hostname) | awk '{ print $4 }')
195.85.76.10.in-addr.arpa domain name pointer drupal8-test.lxd.
```
From this the actual host.domain name can be derived and put in settings.php in place of the www.example.com shown above.  This has to be done after the IP address has been assigned by dhcp and assumes that the dhcp request includes the hostname in /etc/network/interfaces.

**Comment by JedMeister** [comment]
This should be already resolved via the [inithook](https://github.com/turnkeylinux-apps/drupal8/blob/master/overlay/usr/lib/inithooks/bin/drupal8.py#L89) shouldn't it?!

It certainly worked fine for me when I tested a v14.2 LXC container last release (IIRC I was testing setting it to www.example.net and with a entry in my local hosts file).

**Comment by JedMeister** [comment]
Although actually, now I think about it, depending on how you have LXC setup, (e.g. NATed connection) it may be a bit problematic? Still, so long as you have the DNS setup to point to the correct IP, it should "just work" IMO.

**Comment by JedMeister** [comment]
Whilst this may still potentially be an issue, I'm going to close this for now. Once we have an LXC appliance again (hopefully in v17.0) then we may need to revisit this...
