### ISSUE TITLE
Stop website top-level navigation wrapping

### ISSUE THREAD

**Issue by lamby** [turnkeylinux/tracker#1030]
![](https://i.imgur.com/F7acW7Y.jpg)

ie. The "TURNKEY HUB" is on the next line. This is on 1366x768, so hardly narrow.

**Comment by JedMeister** [comment]
Thanks mate, yes it would be better if they were compacted a little so that it didn't wrap (at least at a "normal" screen resolution.

**Comment by spaghettimaster** [comment]
Looks like this issue can be closed.

**Comment by JedMeister** [comment]
It's still doing it for me @spaghettimaster ?! If I make the browser window a bit narrower, it stops doing it:

![screenshot from 2018-05-19 09-43-27](https://user-images.githubusercontent.com/818633/40262219-2760b0fc-5b49-11e8-8a69-b8580e7a7653.png)

But as soon as I make the window broader, the search bar gets wider too and then it wraps again:

![screenshot from 2018-05-19 09-43-34](https://user-images.githubusercontent.com/818633/40262229-34f2258e-5b49-11e8-9a48-96b61f77b35a.png)

**Comment by JedMeister** [comment]
Fix applied to main site. Thanks @spaghettimaster
