### ISSUE TITLE
ERROR: Cannot open TUN/TAP dev....: No such file or directory (errno=2)

### ISSUE THREAD

**Issue by naveronex** [turnkeylinux/tracker#1032]
Fresh appliance install in a proxmox container and 1 client created.  Couldn't connect, got down to checking that OpenVPN was actually running so i tried this and you can see my result:

root@openvpn ~# openvpn --config /etc/openvpn/server.conf
(....lots of stuff...)
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Exiting due to fatal error

I haven't done anything other than the initial guided configuration and running one other command:
root@openvpn ~# openvpn-addclient client1 notmyreal@email.com

Not sure if I did something wrong.  I set the server up for "server" mode, not "gateway" or "client" and out of the box it seems to not run.

**Comment by JedMeister** [comment]
Please see #1011

**Comment by JedMeister** [comment]
FWIW the fix will be included in the upcoming v15.0 release.

**Comment by naveronex** [comment]
Oh fantastic!  I will likely switch to a turnkey appliance with that
release in my home lab! Thank you for letting me know, you rock!
