### ISSUE TITLE
Fix Apt/GPG for third party repos

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1033]
At the moment when we install third-party apt repos we put their key in `/etc/apt/trusted.gpg.d/` whereas we should be putting their key in `/usr/share/keyrings` and adding a `[signed-by=<path/to/gpg/key>]` part to each source line in the corrosponding sources file.

See https://wiki.debian.org/DebianRepository/UseThirdParty for more information

Some packages which use third party apt repos (non-exhaustive)
 - [ ] <s>ansible ??? - if #1048 is implemented</s> (#1048 not implemented)
 - [x] asp-net-apache
 - [x] matomo (piwik)
 - [x] GitLab (as of v15.2)
 - [x] odoo 
 - [x] php5.6 (in common)
 - [x] jenkins
 - [x] <s>mediaserver (Emby)</s> (Emby no longer installed via repo)
 - [x] canvas (yarn)
 - [x] bt-docker (tkldev/buildtasks)
<s>(Note Odoo does not of this writing use a third-party repo but likely will before this issue is closed).</s>

**Comment by JedMeister** [comment]
Just updated the OP to include `php5.6` and `jenkins`. As well as added the relevant tags (except php5.6 as that doesn't have a specific tag and I'm not sure I should create one at this point).

**Comment by JedMeister** [comment]
Also, we should double check that the new keyrings dir is included in the default TKLBAM backup!

**Comment by JedMeister** [comment]
Just did a grep through app source code to make sure I hadn't missed any. Found a couple and added them above.

**Comment by JedMeister** [comment]
FWIW, see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851774#31

**Comment by JedMeister** [comment]
Just added the mediaserver tag (it was already on the list). I've (re)assigned to you @OnGle. So if you could please take care of that ASAP. Cheers.

**Comment by JedMeister** [comment]
closing now as all relevant appliances are done.
