### ISSUE TITLE
Installation from ISO failing ("partman-auto/init automatically partition doesn't exist")

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1042]
We're currently building di-live from https://github.com/turnkeylinux/di-live/ master branch. I.e. this commit: https://github.com/turnkeylinux/di-live/commit/f7ab328cb2a2213884a4b355f41574e6957804bc

Unfortunately, that doesn't work :cry: and results in a broken ISO which won't install.
When booted with this version of di-live, you get this:

![screenshot2018-04-1022_51_04](https://user-images.githubusercontent.com/818633/38601035-a31da488-3da9-11e8-9d7d-d4cbd4387af1.png)

Selecting any of those options just takes you around in circles...

Slowing down a screen capture, just before that screen, is the following:

![screenshot from 2018-04-12 14-57-47](https://user-images.githubusercontent.com/818633/38657438-906994b8-3e63-11e8-92c1-69b5616ff628.png)

(Apologies that I don't have that simply as text - from a serial console, but I couldn't get a serial connection working with KVM on Proxmox...)

I actually discovered the bug (although not these specifics) ages ago, but as we were considering replacing di-live, I put it aside and promptly forgot about it. Now that Alon has built packages in preparation for a v15.0rc1 release (and we haven't dropped di-live), it's reappeared...

Following my gut, I took a punt on it being something to do with the `di-live.install` file in this commit: https://github.com/turnkeylinux/di-live/commit/754e873e949c302757b7e6198ea653cae56bb810#diff-d9bfab070307ddc8fbc491bcfde56b4b 

I pulled the original ([`install`](https://github.com/turnkeylinux/di-live/blob/a32c8d09dfc8bdef518f29df9be29cb7c73ed4b1/debian/install)) file out of the git history, and renamed it `di-live.install`. See here: https://github.com/JedMeister/di-live/commit/6f61633a4af1ee96af4e25f048c246dfdf92ffe1

The installation from inside a live environment still doesn't work (see #1041) but the "normal" ISO installer now seems to work ok?!:

![screenshot from 2018-04-12 15-03-19](https://user-images.githubusercontent.com/818633/38657842-b20b35c0-3e65-11e8-8b2b-b35bd71c6fee.png)

@lamby - some questions:

 - Does that make any sense to you?
 - Is there any reason why we shouldn't just revert the contents of `di-live.install` (as per my commit) seeing as it appears to "just work"?
 - Or is there an important reason why you reordered it that I'm missing?

Also:
 - Does it seem like a legit "fix"?
 - Or does it seem purely coincidental and that I should do much more testing before I jump to the conclusion that this is the "fix"? (FWIW I have done a fair bit of testing and it seems consistent, but I may be missing something... - I've been wrong before :wink: )

**Comment by lamby** [comment]
Great work narrowing this down.
https://github.com/turnkeylinux/di-live/commit/754e873e949c302757b7e6198ea653cae56bb810#diff-d9bfab070307ddc8fbc491bcfde56b4b doesn't look like a simple namespacing of the filename (ie. rename) but rather modifies the file at the same time. I believe this is actually done by the `wrap-and-sort` utility. It's not immediately unclear why this would break it, however, as the ordering should not be meaningful unless files overwrite each other.

However, I think this is a bit of distraction as #1041 is likely to be the root cause of all these issues.

**Comment by JedMeister** [comment]
To clarify, this issue is related to trying to install direct from ISO. I would call that a "non-live" or probably just an "ISO-install", but again our terminology may differ?

For completeness, I'm moving the relevant part from #1041 over here. I think my inclusion of it over there may raised some confusion for you? From what I can see, the output below (when trying to install from a live running OS using di-live) is the same as installing from ISO (as per OP):

```
root@core ~# apt-cache policy di-live | grep Installed
  Installed: 0.9.5+25+gf7ab328
root@core ~# di-live -d
Traceback (most recent call last):
  File "/usr/lib/di-live.d/42partman-base", line 67, in <module>
    main()
  File "/usr/lib/di-live.d/42partman-base", line 61, in main
    preset_debconf(resets=templates, preseeds=preseeds, seen=seen)
  File "/usr/lib/di-live.d/common.py", line 129, in preset_debconf
    db.reset(template)
  File "/usr/lib/python2.7/dist-packages/debconf.py", line 62, in <lambda>
    lambda *args, **kw: self.command(command, *args, **kw))
  File "/usr/lib/python2.7/dist-packages/debconf.py", line 98, in command
    raise DebconfError(status, data)
debconf.DebconfError: (10, "partman-auto/init_automatically_partition doesn't exist")
Debian Installer Live
---------------------

  1. Partman-base  2. Live-installer  3. Grub-installer  4. Finalize
Debian Installer Live Menu 
```

@lamby - in an attempt to clarify further; the changes I made to `debian/di-live.install`; i.e. https://github.com/JedMeister/di-live/commit/6f61633a4af1ee96af4e25f048c246dfdf92ffe1 resolve this issue! 

I just need to know if that's acceptable? Or if I'm missing something...

**Comment by lamby** [comment]
> in an attempt to clarify further; the changes I made to debian/di-live.install; i.e. JedMeister/di-live@6f61633 resolve this issue!

@JedMeister As in, you just reverted the *ordering* changes? (re. my "the ordering should not be meaningful unless files overwrite each other.")

**Comment by lamby** [comment]
> Yes! Despite your suggestion that the ordering shouldn't be meaningful, that's what "fixes" this issue...

To clarify what I meant there, "should not" in the sense that one shouldn't write a `dh_install` input file that has meaningful ordering. Clearly, if the "files overwrite each other" (the bit you snip from my quote..) then the ordering does start to matter, as was aptly demonstrated here.

> commit that and move on?

Well, I would add a massive comment to say that that the ordering of this file matters to prevent someone naïvely running `wrap-and-sort`, linking to this issue, et cetera. et cetera.

**Comment by JedMeister** [comment]
Ah! Now I get you! Sorry I misunderstood the context of what you meant...

Thanks so much!

> Well, I would add a massive comment to say that that the ordering of this file matters to prevent someone naïvely running wrap-and-sort, linking to this issue, et cetera. et cetera.

Yes good call! Thanks again, you rock! :smile:

**Comment by lamby** [comment]
> > Well, I would add a massive comment to say that that the ordering of this file matters to prevent someone naïvely running wrap-and-sort, linking to this issue, et cetera. et cetera.
>
> Yes good call!

It's a great habit to always adopt.. If someone can break something once, the chances of that exact thing being broken again is really rather high! Plus, this avoids having to remember anything whatsoever, freeing up brain cells for more interesting tasks, reducing the "bus number" of the project,etc.

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux/di-live/commit/b070db05685df9dea0e885f74e54abdb968cc977

Thanks again for your invaluable feedback @lamby

FWIW I added this to the top of `debian/di-live.install`:
```
root@tkldev public/di-live# head -4 debian/di-live.install 
### !IMPORTANT! DO NOT change the order of this file!    ###
### =================================================    ###
### the layout and order of this file is important - see ###
### https://github.com/turnkeylinux/tracker/issues/1042  ###
```

That should do the trick I reckon! :smile: Although open to any further feedback.

**Comment by lamby** [comment]
Hahaha, love it. I guess the only other bit of feedback is that it's a shame our packages don't have real `debian/changelog` files. (Indeed that would make them much more like regular Debian packages and smooth out differences in bus factor and knowledge there too...)

**Comment by JedMeister** [comment]
Well this is embarrassing... :anguished:

Turns out I was totally mistaken. :frowning:

The issue appears to be not in the sorting of that file at all. I was initially on the right track (it was the commit I thought it was) but due to the way I was testing, I was getting false passes. Rather than being the sort order of the `debian/di-live.install` file, it was because of the renaming of the `debian/templates` file (to `debian/di-live.templates`), without the `debian/rules` file also being updated... 

FWIW, [line 13](https://github.com/turnkeylinux/di-live/blob/f7ab328cb2a2213884a4b355f41574e6957804bc/debian/rules#L13):
```
	cat d-i/templates >> debian/templates
```
Needs to be:
```
	cat d-i/templates >> debian/di-live.templates
```
That'll teach me for getting over-excited, jumping to conclusions, cutting corners and not doing a proper final test from scratch...!

So I'll reopen this for now, but will have a closing commit tomorrow... (I've run out of time today).

**Comment by JedMeister** [comment]
Confirmed that I'm now fixed it! :smile: Properly resolved by:

 - https://github.com/turnkeylinux/di-live/commit/ecb6dada91b50529e52398d9fbf67a27f90374fd (revert previous "fix")
 - https://github.com/turnkeylinux/di-live/commit/3fa70dca5216f4cd203e751deb5c8f0ab4f11c69 (proper fix; update `debian/rules`)
