### ISSUE TITLE
Permissions adjustments for Prestashop v15.0

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1043]
**[updated]** Permissions are currently not ideal for Prestashop (taken from comment below):

>All files are: 666 (-rw-rw-rw-)
>All Directories are: 775 (drwxrwxr-x)
>
>For normal setup, Prestashop should be set to:
>Files: 644 (-rw-r--r--)
>Directory: 755 (drwxr-xr-x)
>
>I normally run the commands as root under /var/www/prestashop:
>```
>find . -type d -exec chmod 755 {} ";"
>find . -type f -exec chmod 644 {} ";"
>```

----

On the v15.0 update commit for Prestashop (https://github.com/turnkeylinux-apps/prestashop/commit/0433e858c5448c231b2362eadb9a75e19b27c151#commitcomment-28501493) @JorgeValente writes:

> I wonder if you could add also the following to the file after # cleanup, which seems to be needed:
chown -R www-data:www-data app/logs/
>
> Not sure if user is supposed to be able to upgrade Prestashop on their own as that would require some extra permissions (so I assume not).
>
> Is there a way to start testing the v15 version for the permissions (if I pull Master seems to get 14.2)? As the v14.2 (or was it in 14.1) made Prestashop world writable, it may have introduced extra security risks into default installations.

**Comment by JedMeister** [comment]
@JorgeValente - apologies its taken me all day to get back to this... Better late than never I hope! :smile: 

> I wonder if you could add also the following to the file after # cleanup, which seems to be needed:
chown -R www-data:www-data app/logs/

That sounds fine. Please feel free to open a new pull request adding that change.

Otherwise, either @spaghettimaster or one of the other @turnkeylinux/ninjas could make this adjustment...

Also perhaps we ideally want to change more?! Let's discuss below!? :smile: 

> Not sure if user is supposed to be able to upgrade Prestashop on their own as that would require some extra permissions (so I assume not).

Not specific to Prestashop, but yes the user is supposed to upgrade third party installed software themselves. 

Generally (and historically), the anticipation is that they would be doing that via a root SSH session, so by default everything would remain owned by root and the final permissions would then need to be adjusted back to default release (or updated as required).

However, perhaps I'm missing something...?! 

TBH, I'm not particularly familiar with Prestashop itself. If it has the ability to update from within the web UI, then perhaps we should adjust permissions so they are able to? Please share your thoughts.

The way we have permissions set up by default (i.e. everything owned by root, except specific areas that `www-data` needs to write to) arguably makes it more secure (i.e. reducing the damage that could be done by a hacker, even if they break in). However, if the system can be updated from within the UI, it could also be argued that making it easier for the user to update, makes it more secure! 

FWIW in our WordPress appliance, we've relaxed the permissions to support web UI upgrades for that exact reason! So if Prestashop now has the same facility, then perhaps we should consider adjusting it in a similar way?

> Is there a way to start testing the v15 version for the permissions (if I pull Master seems to get 14.2)?

Yes, you should be able to. However, until I also merge our v15.0 [common](https://github.com/turnkeylinux/common) updates (currently in `stretch-dev` branch) into master, then you'll also need to make sure that you check out the `stretch-dev` branch.

ON a v14.2 TKLDev, this should do the trick:
```
cd common
git fetch origin
git checkout stretch-dev
```
Before you build, you'll also need to set the `RELEASE` environment variable. The `di-live` pacakge curently has a showstopper bug too, so until probably early next week (when we upload a fixed build to the proper/official TurnKey repo, you'll also need to enable my personal dev repo. You can do both of those, like this:
```
export RELEASE=debian/stretch
export DEV_TEST=y
```
Whatever you do, please **DO NOT** use the ISO you build in production! My dev-test repo is for development and testing only! It may become unstable without notice and pacakges may contain bugs and security issues which likely won't be fixed any time soon!

> As the v14.2 (or was it in 14.1) made Prestashop world writable, it may have introduced extra security risks into default installations.

I'm not 100% clear what you mean here?

From my viewing of the history of the Prestashop `conf.d/main` script whilst it was only "locked down" for v14.2, prior to that, there were still plenty of directories which weren't writable by `www-data` and by my reading, it's never been "world writable"; only ever writable by `root` and/or `www-data`. Although, perhaps I'm missing something?

**Comment by JorgeValente** [comment]
Hello @JedMeister , 

Thank you for the detailed reply and no worries I won't run the Dev stuff under production.

I spent the weekend testing this out, seems there is a problem really with the 14.2 (and probably 14.1). Not sure if we should still file bugs to that or not. In the coming week probably will test on 15 eventually.

We take security very seriously and everything we run on production will have a second vetting for penetration and risk assessment, hence the issue mentioned got detected and corrected. I only noticed this problem when testing Development at home. Probably should think of better ways to report problems back to upstream...

Here are the findings: 
> As the v14.2 (or was it in 14.1) made Prestashop world writable, it may have introduced extra security risks into default installations.

Turnkeylinux 14.2 issue:

Setup: 
1) Turnkeylinux 14.2 VM downloaded from Turnkeylinux site
https://www.turnkeylinux.org/download?file=turnkey-prestashop-14.2-jessie-amd64.ova
2) Open in Virtual Box (or VMWare), all default settings.

SSH into VM, cd to /var/www# 
Current default permissions settings are:
All files are: 666 (-rw-rw-rw-)
All Directories are: 775 (drwxrwxr-x)

For normal setup, Prestashop should be set to:
Files: 644 (-rw-r--r--)
Directory: 755 (drwxr-xr-x)

I normally run the commands as root under /var/www/prestashop:
``find . -type d -exec chmod 755 {} ";"``
``find . -type f -exec chmod 644 {} ";"``

(Plus all the other permissions related commands you already have setup in the new v15 changes)

To note, this only happens to the files that are already under the /var/www# folder. I suspect a script that ran the unzip or something related to the unpacking of those files was messed up. 

On the many suggestions you made above, sure I will spend some time to look into the permissions on the v15.

Last but not least, I would like to say a big Thank You to you and the TurnkeyLinux team! We run many of your images, specially useful and quick for Prototyping! And once it proofs useful, we just port it to Production. 

We also run your backup Utility TKLBam and just let it do all the back up for us, it is great! I particularly enjoy having all Backups managed on one simple interface and easy to restore. Many thanks.

Regards,
Jorge

**Comment by JedMeister** [comment]
Hey @JorgeValente thanks tons for this, it's invaluable! :smile: 

> I spent the weekend testing this out, seems there is a problem really with the 14.2 (and probably 14.1). Not sure if we should still file bugs to that or not. In the coming week probably will test on 15 eventually.

Until we do our next release (v15.0 in this case), unless it's already been noted and/or fixed; yes we'd love any bug reports! Essentially v15.0 will be based off the build code from v14.2 (and v15.1 from v15.0, and so on). So unless fixed, any bugs in v14.2 will propagate into v15.0 (etc, etc)!

> We take security very seriously and everything we run on production will have a second vetting for penetration and risk assessment, hence the issue mentioned got detected and corrected. I only noticed this problem when testing Development at home. Probably should think of better ways to report problems back to upstream...

We also take security very seriously. Although as you would well be aware, security can generally be considered on a continuum, rather than being a binary on/off; yes/no. We also need to balance the needs of our "average user" and as many of our user base are Linux and/or headless server "newbs", there is often a need to juggle "ease of use" vs tightening down the security screws.

Whenever there is something we could be doing better though, we'd love to hear! Please don't ever hesitate to post info here on our "issue tracker"! It's specifically for bug reports, feature requests and targeted dev pain/improvement discussions! We also have a [forum](https://www.turnkeylinux.org/forum) which is the preferred location for support and more general discussion.

> Turnkeylinux 14.2 issue:
> [...]

I've updated the top of the OP to include the specifics you suggest for (re)setting perms for Prestashop. Thanks for that.

> On the many suggestions you made above, sure I will spend some time to look into the permissions on the v15.

Please note that if my current schedule goes according to plan, I'll be merging the `stretch-dev` branch of common into `master` this week, and all the stretch packages should be on the official TurnKey apt repo. I'll then build an RC (release candidate) of Core (as ISO only). From that point on, any ISO you built from official TurnKey sources, should be fine to use in production (i.e. from the master branch of common, using only TurnKey official repos). 

>Last but not least, I would like to say a big Thank You to you and the TurnkeyLinux team! We run many of your images, specially useful and quick for Prototyping! And once it proofs useful, we just port it to Production.
>
>We also run your backup Utility TKLBam and just let it do all the back up for us, it is great! I particularly enjoy having all Backups managed on one simple interface and easy to restore. Many thanks.

Awesome. Thanks for your kind words and lovely feedback! :smile: 

Regards,
Jeremy

**Comment by JedMeister** [comment]
@spaghettimaster - could you please double check that the Prestashop appliance has appropriate permissions (as noted by @JorgeValente) ready for the upcoming v15.0 release.

**Comment by spaghettimaster** [comment]
@JedMeister here's [PR](https://github.com/turnkeylinux-apps/prestashop/pull/16)

Thank you for your excellent suggestions, @JorgeValente!

**Comment by JedMeister** [comment]
Thanks @spaghettimaster - merged. :smile:

**Comment by JorgeValente** [comment]
Many thanks @spaghettimaster  & @JedMeister !
Will definitely do some further testing on v15 (dev) in the coming weeks.
