### ISSUE TITLE
Mediaserver

### ISSUE THREAD

**Issue by herohamp** [turnkeylinux/tracker#1046]
I am running the Mediaserver in a VM. I expanded the VM internal disk but it has not noticed. How can I expand the disk.

**Comment by JedMeister** [comment]
Hi @herohamp 

Does your VM use LVM? If so, did you extend that too? Did you also extend the filesystem?

Please see this blog post: https://www.turnkeylinux.org/blog/extending-lvm that should cover it.

It's quite dated, but should still be relevant (FWIW I actually used it last week as a refresher and it seemed to work fine...)

Also FWIW, support questions such as this are generally best asked on our [forums](https://www.turnkeylinux.org/forum/support). This is our "issue tracker" for tracking bugs and feature requests, as well as development discussions. So I'll close this for now, although you can post back if you wish and I'll still see any replies.
