### ISSUE TITLE
Consider installing Ansible from PPA?!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1048]
As noted by @Dude4Linux in a [comment on a pull request](https://github.com/turnkeylinux-apps/ansible/pull/17#issuecomment-378694858); Ansible recommend Debian install using the Ubuntu PPA (see [here](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html?#latest-releases-via-apt-debian)).

As I noted (later in the conversation), whist generally installing on Debian via Ubuntu PPA is frowned on (due to binary incompatibility between Debian and Ubuntu) in the case of a Python package, it shouldn't matter...

So this may be a good option for installation of Ansible?! I think that it's (at least marginally) more secure than using pip and will provide a more up to date version of Ansible than we could currently get from backports. Either way, we're not going to get auto sec updates, so the PPA seems like probably the best option.

Please note that if we do go that way (i.e. install via apt from PPA), then we'll need to add the PPA repo as per third party repo "best practice" - see #1033. We'd also need to configure pinning so that only the packages required for Ansible could ever be installed from that repo (as we do for other 3rd party apt installs).

Any feedback welcome but unless anyone has any serious concerns, I'm inclined to go the PPA route!

**Comment by JedMeister** [comment]
Can you please have a look at this one too @OnGle?

**Comment by Dude4Linux** [comment]
@JedMeister - FYI I did take a look at this earlier, but I guess I failed to update the thread. When I checked into using the Ubuntu PPA for Ansible, I found that it would not be supported by automatic security updates. For me, that would be the primary reason for using a Debian repo versus a `pip` install.  I concluded that for v15.0, we should just continue using the `pip` install method.

I have noted that there have been a couple of bug fix updates to Ansible since the v15.0rc1 release.

**Comment by JedMeister** [comment]
Hey @Dude4Linux 

We don't include 3rd party repos in auto-security updates. The main reason for that is that usually upstream repos don't provide backported security updates, only updated versions. As APIs can change between versions, to avoid users getting nasty surprises, it's generally best not to automatically force version updates.

Having said that, if you wanted to, you could configure your own Ansible server to auto update by adding the PPA to the apt security list or creating a separate cron job to update ansible. We wouldn't want to do that for the default TurnKey appliance though.

TBH, I still think that there is a marginal security advantage of installing from a GPG signed PPA repo (assuming that they provide the same version). Unless you have a firm preference, I'm inclined to do it that way.

OTOH, at this late stage of the release, having one less thing to take care of is certainly appealing! :smile: Although if we are to change to the PPA, doing it now for the `.0` release is preferable (to in a later update release). 

Input welcome.

**Comment by Dude4Linux** [comment]
I just issued a PR for some changes I don't want to get lost if the conversion to PPA repo takes place.
See https://github.com/Dude4Linux/ansible/pull/3

**Comment by JedMeister** [comment]
Lert's just stick with the default Debian package for now...

We could perhaps document how to install the latest via pip or perhaps even do a Confconsole plugin if we wanted to

Regardless, I'm going to close this issue for now...

**Comment by JedMeister** [comment]
Oops forgot to close...
