### ISSUE TITLE
Gitea - New appliance

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1049]
Whilst I think that we should still build a minimalist `revision-control` appliance for v15.0, it's quite clear that Bazar/bzr is pretty much dead, as is Mercurial/hg also SVN is not really used for any new projects these days (from what I hear, academia and other large orgs are really the only ones using it). 

So most new users are likely to just want git. It is after all it is the most popular version control system these days!

GitLab is awesome, but is also quite hefty and contains all the bells and whistle, so for many users it may be more than they want/need.

As a middle ground option, let's have a Gitea appliance!:

https://gitea.io/en-US/

**Comment by qrntz** [comment]
Oops, didn't realize it would close the issue outright. @JedMeister I'd love if you could take a look first :-)

**Comment by JedMeister** [comment]
@qrntz from a glance, looks brilliant mate. From a quick glance, the only thing that jumped out at me was that `inithooks/firstboot.d/40gitea` looks a bit [unfinished](https://github.com/qrntz/gitea/blob/master/overlay/usr/lib/inithooks/firstboot.d/40gitea#L9-L12).

That's cool though, I've forked it to the turnkey-apps repo and I'll do a local build. Assuming that tidying that up is all that's required, I'm happy to take care of it. Cheers mate. :smile:

**Comment by qrntz** [comment]
You're right, fixed that. It didn't influence the functioning of the appliance so I haven't noticed it in time.

**Comment by JedMeister** [comment]
I ended up fixing it myself (late last week) but thanks anyway. 

FWIW I had to make a couple of other tweaks [here](https://github.com/turnkeylinux-apps/gitea/commit/e6faabee9299447b6e8d1a523ed0fbab2221f2c2) and [here](https://github.com/turnkeylinux-apps/gitea/commit/73faea9f9d88753209721c3bfcdbedc7812a1094). Although on reflection, [this one](https://github.com/turnkeylinux-apps/gitea/commit/73faea9f9d88753209721c3bfcdbedc7812a1094#diff-c324caadbb046271fc6f35b3272bdec5R84) should probably have been something more like this:

```
system('sed -i "\|FROM|s|=.*|= admin@%s|" %s' % (domain, config))
```

So the from email address is from "admin" at the server, rather than the first user configured, but anyway...

**Comment by JedMeister** [comment]
Closing as this is now released:

https://www.turnkeylinux.org/gitea
