### ISSUE TITLE
Update mysqltuner script in common (included in all MySQL apps, inc LAMP apps)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1051]
I just noticed that there is a really old (v1.2.0 added Jan 2012; current version is v1.7.9 - April 2018) version of mysqltuner script bundled as part of the [mysql-overlay](https://github.com/turnkeylinux/common/tree/master/overlays/mysql) (in common). I.e. all appliances that include the [mysql.mk](https://github.com/turnkeylinux/common/blob/master/mk/turnkey/mysql.mk) (inc [lamp.mk](https://github.com/turnkeylinux/common/blob/master/mk/turnkey/lamp.mk#L7)) - see https://github.com/turnkeylinux/common/blob/master/overlays/mysql/usr/local/bin/mysqltuner

We should at the very least be installing a newer version. Although actually, we would be better off downloading it at build time IMO! Then it will get updated on rebuild.

So what needs to happen is remove the file from the mysql overlay and edit the [mysql conf](https://github.com/turnkeylinux/common/blob/master/conf/mysql) to include this (or similar):
```
wget http://mysqltuner.pl -O /usr/local/bin/mysqltuner
chmod +x /usr/local/bin/mysqltuner
```
We should possibly at least include a link to the [docs](https://github.com/major/MySQLTuner-perl/blob/master/INTERNALS.md) for it somewhere, although perhaps we should include that file in the build too?

**Comment by JedMeister** [comment]
@spaghettimaster - another little job when you get to it mate.

**Comment by spaghettimaster** [comment]
Done!
https://github.com/turnkeylinux/common/pull/120
