### ISSUE TITLE
Deck (experimental, overlayfs) files never removed

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1053]
This issue refers to the deck bash replacement. 

Files deleted in the current merged directory (mountpoint) of an overlayfs mount do not persist when the merged directory is remounted as a lower layer.

At this point I am unsure whether this is an upstream bug or not.

example:
```bash
# Create base directory
mkdir base
touch base/example

deck base layer1
rm layer1/example
ls layer1/ # shows no file

deck layer1 layer2
ls layer2/ # shows file again
```

It appears this occures because when files that were created in a lower deck, get deleted in an upper deck. The deletion is stored as a special character device in the upper directory of the top layer. When this deck is decked again, or if it has already been decked again the "whiteout" files do not propagate between layers. This is perhaps seen easier when using overlayfs directly

```bash
# Create base directory
mkdir base
touch base/example

# Create merge, upper and work directories for 2 layers
mkdir layer1 layer1.upper layer1.work
mkdir layer2 layer2.upper layer2.work

# Mount layer1 as the merged directory using layer1.upper as the true upper layer, with base as a lower layer and layer1.work as the necessary work directory
mount -t overlay overlay -o lowerdir=$(pwd)/base,upperdir=$(pwd)/layer1.upper,workdir=$(pwd)/layer1.work layer1
ls layer1 # should show example as expected
ls layer1.upper # shows no file (this is expected behaviour, it should only show files written on layer1)
rm layer1/example
ls layer1 # should show no files
ls layer1.upper # should show a special character device called "example", this is the "whiteout" file

# unmount, and remount with layer2 being the new upper layer and using layer1.upper directory as the top level lower layer.
umount layer1
mount -t overlay overlay -o lowerdir=$(pwd)/base:$(pwd)/layer1.upper,upperdir=$(pwd)/layer2.upper,workdir=$(pwd)/layer2.work layer2
ls layer2 # now shows example again as if it was never deleted
```

**Comment by JedMeister** [comment]
Hmm... Ok, well that sort of sucks then! 

I wonder if OverlayFS just doesn't support the usage that auFS provides (and `deck` relies on)? Or whether this is an OverlayFS bug?

Working on the assumption that Docker (etc) would (possibly?) also require this functionality (that `deck` relies on), I just spent a ton of time searching. I found some very similar issues, but nothing exactly the same. TBH, that strikes me as weird, although I can definitely recreate this on my Stretch desktop!

So my guess is that it's a known limitation (which Docker etc work around some other way). But I'm not sure whether that's a reasonable guess or not?

Later on, I'll try testing this on a newer kernel to see if it's also reproducible there. That will at least provide some additional info...

@lamby - I'm assuming that you don't have expertise in this area specifically; but do you think we should consider making a bug report with Debian? And/or somewhere else? Any other suggestions on who we could get confrimation whether this is a bug or a limitation?

FWIW I have posted a Q on [Unix Stack Exchange](https://unix.stackexchange.com/questions/438872/overlayfs-files-deleted-in-current-merged-dir-mountpoint-dont-persist-when)

**Comment by lamby** [comment]
@JedMeister I would file a bug in Debian, yes. Indeed, I'm curious why you're at all hesitant to do that. :)

**Comment by lamby** [comment]
> I was hesitant as I don't want to file a bug if it's not a bug

I cannot recommend or underline enough that you shift your mindset on this :)

**Comment by JedMeister** [comment]
Ok bug filed (about 30 mins ago). Hopefully it will appear soon... Once I have the ID, I'll post a link to it here.

**Comment by lamby** [comment]
:+

**Comment by OnGle** [comment]
This issue was actually caused by an assumption I made that lower layers are stacked left to right, bottom to top. It is infact documented here https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/overlayfs.txt#n253 that this is not the case.
