### ISSUE TITLE
v15.0 Django appliance should probably be using Python3!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1054]
As prompted by a comment on [another issue](https://github.com/turnkeylinux/tracker/issues/830#issuecomment-383283124) we should probably rebase the TurnKey Django appliance on Python3. 

Whilst python2 is still a thing, all new development these days is moving to python3, so it makes sense that most users who wish to launch a new Django appliance would want python3.

Perhaps we still want to provide a python2 Django appliance too though? I'm not sure... Any thoughts @OnGle? @spaghettimaster?

There is a python3-django package in Stretch: https://packages.debian.org/stretch/python3-django

**Comment by spaghettimaster** [comment]
Django 2 [supports only Python 3.x](https://docs.djangoproject.com/en/dev/releases/2.0/#python-compatibility).
And the version of Django from `python-django` isn`t the latest stable.

So I think we should change the way how we install Django and use the latest version of Django and Python 3.

**Comment by JedMeister** [comment]
Hmmm, ok. Thanks for the info @spaghettimaster 

I see that the Debian Stretch package is Django 1.10.7 (available as either as a ptyhon2 or python3 based package; we're using the python2 one currently). 

Upstream will only be supporting Django 1.11 (but Debian security team will backport security patches to v1.10.x, as they do). 

However, you raise a good point. 

I think we should move our v15.0 Django appliance to `python3-django` (as suggested earlier in this issue). As an additional consideration, perhaps we should also provide a Django2 appliance as well?! 

I suggest an additional appliance (rather than a replacement) as the one using Debian package will have the auto security updates, whereas one installed from upstream won't! And although on face value, calling it "Django2" makes sense now, it may cause confusion once Debian release a Django2 build. So perhaps we need to name it something different? Perhaps 'Django-upstream' or something like that?
