### ISSUE TITLE
Deck no longer supports --get-level

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1057]
deck no longer supports `--get-level` which is used when building ISOs that contain `root.sandbox`.

**Comment by JedMeister** [comment]
@OnGle - Is this actually an issue (i.e. do we need `--get-level`)? If not, let's just close this...

**Comment by OnGle** [comment]
@JedMeister  I don't remember the exact details, and they've possibly been patched since. But as far as I remember there was a situation where building an iso with a modified root.sandbox would fail because fab internally used `--get-level`. I'm going to tag this "needs more information", if you feel it should just be closed feel free too, otherwise depending on if we can confirm it it should be closed/moved to 17.0 imo.

**Comment by JedMeister** [comment]
I'll just bump to v17.0 for now. We can readjust as need be...

**Comment by JedMeister** [comment]
This may well still be an issue, but from what I can gather, we're not actually using `--get-level` anywhere currently? As such I'm going to close this for now. It can be reopened if we want to look at re-implementing  `--get-level`.
