### ISSUE TITLE
Build error (appflower): download issue

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#106]
````
Dload  Upload   Total   Spent    Left  Speed
:--     0  0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 504
make: *** [build/stamps/root.patched] Error 22
````

**Comment by JedMeister** [comment]
It looks like appflower is now abandonware so closing this issue

**Comment by abidrcastaneda** [comment]
I think the sfcoreautoload.class.php is missing from the lib/vendor/symfony/ .... in fact, the folders only go all the way up to ../lib/vendor/symfony/  and that's it, there are missing files .....................
