### ISSUE TITLE
Filemanager in WebMin and future of Java Support

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1069]
Not sure if FileManager is going away, but if it stays we need to be aware that Oracle is changing their Java SE support system starting in 2019.  Basically charging for any sort of business usage.

Some detail here:
https://www.java.com/en/download/release_notice.jsp

**Comment by JedMeister** [comment]
Hey Landis, thanks for the heads up mate.

I don't recall which TurnKey version it was introduced in, but sometime within v14.x there was a new Webmin module called "webmin-filemin" which is an html5/javascript filemanager module. it should be installed by default, look for "filemin" in the menu. It isn't quite as full featured as the old java based one, but doesn't require java and should do everything you need. 

FWIW the java filemanager Webmin module has been [removed](https://github.com/turnkeylinux-apps/core/blob/master/changelog#L56) from TurnKey altogether in v15.0.

I'll close this issue for now, but I intend to note this fact when we do the v15.0 final release blog post.
