### ISSUE TITLE
Game Re-Stream (New Appliance)

### ISSUE THREAD

**Issue by ghost** [turnkeylinux/tracker#1070]
If interested I can add an appliance for re-streaming gaming sessions. Essentially it is nginx installed from source with rtmp module and initscripts to setup twitch, youtube live, facebook live, mixer.......

Essentially an easy to deploy appliance that allows one to stream to twitch, youtube, facebook, mixer and any other service that supports rtmp simultaneously.

Why? Outbound bandwidth is limited for most residential internet connections so pushing multiple rtmp streams can rapidly reach your max outbound bandwidth. Solution deploy this appliance to a ec2 instance push one stream and have it pushed to all streaming services from the VPS. Obviously you could run it locally as well but you need a connection that has sufficient outbound bandwidth.

**Comment by JedMeister** [comment]
Apologies on delayed response @MPTMG (I've been trying to keep focused on getting a stable v15.0 Core ready for release). 

This sounds like it could be a really good thing. My only suggestion would be to test the [Debian nginx-rmtp package](https://packages.debian.org/stretch-backports/libnginx-mod-rtmp) before you install from source. Unfortunately, it's only available in `stretch-backports`, but that's still possibly better for end users than installing from source (assuming that it works ok)?! I'm open to the possiblity of a source install though if there is good reason. 

If it does install from source though, perhaps it would be worth providing an install/update script? The initial install could leverage that, and users could then use it to update later too if need be (e.g. security update). Food for thought.

**Comment by MPTMG** [comment]
I am going to roll this into a conf console plugin for the YouPHPTube appliance instead of a stand alone appliance. Essentially just adding some scripts in confconsole to enable record and push stream in nginx.conf. (Can be integrated in later release of YouPHPTube)

It makes more sense this way as securing the streaming side without YouPHPTube would require me to write a custom php authentication mechanism in order to sufficiently secure the live stream/push function. A couple authentication mechanisms exist that could be used, but they are not as granular in control compared to YouPHPTube.

**Comment by OnGle** [comment]
Oops I missed this, :+1: on the appliance idea and making it a conf console plugin sounds like a smart idea

**Comment by JedMeister** [comment]
@MPTMG sounds like a great idea. The current YouPHPTube should be published within the next 24-48 hours (fingers crossed) but as I've said elsewhere, I really hope to start having a quicker/shorter update/release cycle in v15.x. So a YouPHPTube applaince with an optional Gamestreamer confconsole plugin sounds like an awesome idea! :+1: 

@OnGle - thanks for your vote of cinfidence too! :smile:

**Comment by MPTMG** [comment]
Since It seems fine to move this to a confconsole plugin feel free to close this and I will open a new thread later when work is complete. I have already begun work integrated the encoder and just need to add a few confconsole menus.

**Comment by JedMeister** [comment]
Finally following up on most recent comment and closing this one now.
