### ISSUE TITLE
TKLDev LXC build requires priveledged container

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1074]
As [noted](https://github.com/turnkeylinux/tracker/issues/1066#issuecomment-386093584)  by @Dude4Linux, TKLDev v15.0(rc1) still requires a privileged container. Hopefully we can resolve that at some point...

**Comment by JedMeister** [comment]
You probably have more experience with this sort of thing under LXC/LXD than me, but in my recent travels online I came across a SystemD doc that may be relevant when troubleshooting this?:

[SystemD ContainerInterface](https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/)

**Comment by Dude4Linux** [comment]
@JedMeister - Thanks! I only got a chance to preview the document but it looks excellent.  Will give it a full read soon (next rainy day :) ).

**Comment by JedMeister** [comment]
Hey @Dude4Linux - I'm going to close this as a duplicate of #855 (pity I didn't notice that this was a dup sooner...). Just wanted to give you a heads up, as I'm almost certain that this would also be an issue on vanilla LXC/LXD. The note re [4.18 kernel](https://github.com/turnkeylinux/tracker/issues/855#issuecomment-451361217) is an interesting one too. I suspect that it won't be long until we can test that (perhaps your Ubuntu already uses a 4.18+ kernel?).
