### ISSUE TITLE
Registering on the Website not possible

### ISSUE THREAD

**Issue by zevenom** [turnkeylinux/tracker#1076]
Hey there, 

I'm waiting since last week to register myself to the forums, but:

The spam filter installed on this site is currently unavailable. Per site policy, we are unable to accept new submissions until that problem is resolved. Please try resubmitting the form in a couple of minutes.
![unbenannt](https://user-images.githubusercontent.com/19954958/39572688-7aa9b4dc-4ed0-11e8-89fc-71e743954cb3.PNG)

Please don't get me stoned because i post that here, but the contact info on your homepage suggested me to do this.

Best Regards

**Comment by JedMeister** [comment]
Hi @zevenom - thanks for reporting your issue. We'll need to look into that and see what the issue is.

In the meantime, please email me jeremy@turnkeylinux.org and I can manually create a user account for you.

**Comment by JedMeister** [comment]
This should now be resolved. Any further issues, please don't hesitate to ping me direct via email, or post to this thread.
