### ISSUE TITLE
V15.0 - LXC lxc-turnkey template is still creating /etc/inittab for Stretch

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1077]
@JedMeister - After fixing the `/etc/inittab` in `lxd-make-image`, I realized that the `lxc-turnkey` template in the LXC appliance is still creating the `inittab`.  I'll have a look at fixing this as well.

**Comment by JedMeister** [comment]
Great thanks @Dude4Linux I doubt it's a major issue, but always nice to clean up! :smile:

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/lxc/pull/14
