### ISSUE TITLE
hubclient install error: "touch: cannot touch '/var/lib/hubclient/server.conf': No such file or directory"

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1081]
Error encountered when installing [hubclient](https://github.com/turnkeylinux/hubclient) (when building AMI on TKLDev via `buildtasks/bt-ec2`):
```
Setting up hubclient (0.1+30+g49e3511) ...
touch: cannot touch '/var/lib/hubclient/server.conf': No such file or directory
dpkg: error processing package hubclient (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 hubclient
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by JedMeister** [comment]
this should do the trick: https://github.com/JedMeister/hubclient/commit/2c5128c3a14c2c29f8f7eeedfd12334c8b8aa9a5

**Comment by JedMeister** [comment]
@ lamby - while I was at it, I figured I may as well address your comment in the postinstall script:
```
	# Should use dpkg-statoverride?
```

I think you are right, so have implemented it here: https://github.com/JedMeister/hubclient/commit/8d7e8461338120265f5e23d87e1a29da2b5b17d5

To save you a click, here's the diff:
```
diff --git a/debian/hubclient.postinst b/debian/hubclient.postinst
index 89de7fc..b5e057f 100755
--- a/debian/hubclient.postinst
+++ b/debian/hubclient.postinst
@@ -6,13 +6,12 @@ HUBSERVER_CONF=/var/lib/hubclient/server.conf
 
 if [ ! -f $HUBSERVER_CONF ]
 then
-       # Should use dpkg-statoverride?
        mkdir -p $(dirname $HUBSERVER_CONF)
        touch $HUBSERVER_CONF
-       chown root:root $HUBSERVER_CONF
-       chmod 600 $HUBSERVER_CONF
 fi
 
+dpkg-statoverride --update --add root root 600 $HUBSERVER_CONF
+
 #DEBHELPER#
 
 exit 0
```

It seems to work fine, but curious if that looks good to you (never used it before, but looks like a cool utility)?

PS I also noticed that you've replaced the spaces with tabs. Is there a reason for that? Is it a Debian packaging convention of some sort? Or are you just a "tabs guy"? :smile:

**Comment by JedMeister** [comment]
Awesome, thanks @lamby

**Comment by JedMeister** [comment]
@lamby - I have a couple of questions. Please excuse me if these are obvious or silly questions covered somewhere (please feel free to provide hints of where to find current and relevant info).

1. Your suggested change for `postinst` won't update the permissions if the file exists and the user has changed it. That is consistent with the previous behaviour so good call on that. However, I thought that it would be preferable to force the change (it's owned by root and only readable by root for a reason). Or is it bad practice to force changes like that, that the user may have made? (I guess it could be argued that if the user changed it, they did that for a reason and we shouldn't be adjusting it?!)

2. There wasn't a `postrm` script at all, so I've added as per your suggestion. Although shouldn't the `postrm` also completely remove `$HUBSERVER_CONF` if called with `purge`?! E.g. something like this:
```
#!/bin/sh

set -eu

HUBSERVER_CONF=/var/lib/hubclient/server.conf

if [ "$1" = "purge" ]
then
	dpkg-statoverride --remove $HUBSERVER_CONF || test $? -eq 2
        rm $HUBSERVER_CONF
fi

#DEBHELPER#

exit 0
```

**Comment by lamby** [comment]
> Your suggested change for postinst won't update the permissions if
> the file exists and the user has changed it. That is consistent with
> the previous behaviour so good call on that.

Right, and otherwise calls to dpkg-statoverride on the command line
would be magically overridden if the postinst is run again - don't
forget these scripts are meant to be idempotent.

> However, I thought that it would be preferable to force the change
> (it's owned by root and only readable by root for a reason).

Why? Don't follow this.

> There wasn't a postrm script at all, so I've added as per your
> suggestion. Although shouldn't the postrm also completely remove
> $HUBSERVER_CONF if called with purge?! E.g. something like this:

Yep. I think I  assumed there was already a postinst to do this bit
and I was only concerning ourselves with the statoverride bits :)

**Comment by JedMeister** [comment]
> Why? Don't follow this.

No worries. I'll just leave it be. That's probably best...

> Yep. I think I assumed there was already a postinst to do this bit
and I was only concerning ourselves with the statoverride bits :)

Cool, I'll add that too then! Cheers! Thanks again @lamby :+1:

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux/hubclient/commit/b71ad1df5cca954b01752e456a35c7bc48273ce2

**Comment by lamby** [comment]
:+1:
