### ISSUE TITLE
Please remove libreoffice from owncloud & nextcloud

### ISSUE THREAD

**Issue by requiredtruth** [turnkeylinux/tracker#1082]
Need i say more?

**Comment by requiredtruth** [comment]
ok. 
its possibly needless
its big and its other useless friends
clogs bandwidth (for updates) 
and space 
ETC ETC

Please sirs, remove the junk.
Thank You.

**Comment by requiredtruth** [comment]
PS your apps are EPIC

**Comment by vondrt4** [comment]
Libreoffice had its use in Owncloud at the time there was the Documents app. It was superseded by the LibreOffice Online integration, so it's probably safe to remove LibreOffice from the build.

**Comment by JedMeister** [comment]
Thanks for your feedback @requiredtruth and thanks for your additional info @vondrt4.

Following this feedback, I'll tag this as a "feature request" and pin it to the v15.0 milestone. I don't see why we couldn't achieve this for the upcoming v15.0 release. Speaking of v15.0, we creeping ever closer to the stable release. Hopefully we'll have at least a few appliances released within a matter of weeks (hopefully sooner).

**Comment by JedMeister** [comment]
Just assigned this to you @qq7 - it should be pretty straight forward. Let me know if you hit any issues...

**Comment by JedMeister** [comment]
[LibreOffice writer](https://github.com/turnkeylinux-apps/nextcloud/blob/master/plan/main#L22) is also included in the Nextcloud appliance, so figured it's relevant here too?!

**Comment by vondrt4** [comment]
No, but it's obsolete there, too.

**Comment by JedMeister** [comment]
Closing as turnkeylinux-apps/nextcloud#7 & turnkeylinux-apps/owncloud#16 have been merged.
