### ISSUE TITLE
SSH sessions too persistent in v15.0

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1092]
I've noticed that in v15.0rc1 SSH sessions I leave open survive my laptop going to sleep! 

Whilst it is sort of handy during development, IMO they shouldn't be that persistent! They weren't that persistent in v14.x (connection would be lost). I'm not sure if it's changes in defaults, or if it's something we're tweaking.

**Comment by l-arnold** [comment]
Yes, but...  If you use Putty, though the session does not "survive" going into hibernate mode, you can usually "restart" a session from the same black box.  User name and password is required of course, but not a new call to the shell.

**Comment by JedMeister** [comment]
Yeah, that's the behaviour with v14.x. 

However, on v15.0(rc1) the sessions are still open (no need for username and password again). Whilst it's not implicitly a security risk (i.e. a hacker couldn't easily intercept the half-open connection) IMO it's still something of a risk. It relies on the user having their PC setup securely, e.g. requiring password on wake up.

**Comment by JedMeister** [comment]
@qrntz - do you want to have a look at this one mate?

My guess is that a quick adjustment of the config in common will revert it to the behaviour (or close to) in v14.x.
