### ISSUE TITLE
[website] partner page logos should be better

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1095]
I just noticed that the logos of our partners on the [partners page](https://www.turnkeylinux.org/partners) of the website are really small. It'd be nice if they were a bit bigger.

**Comment by qrntz** [comment]
Disabling `max-width: 100%` on `img` makes it look better.

![screenshot](https://i.imgur.com/FVFo8m4.png)

**Comment by JedMeister** [comment]
Thanks @qrntz - it certainly does! :smile: Add to your backlog @spaghettimaster

**Comment by JedMeister** [comment]
Thanks @spaghettimaster - worked a treat! :+1:
