### ISSUE TITLE
SugarCRM Community Edition EOL

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1098]
Early last month SugarCRM [announced on their blog](https://community.sugarcrm.com/community/news/blog/2018/04/06/sugar-community-edition-open-source-project-ends) that the Community Edition of SugarCRM was End of Life.

As such, we will deprecate our appliance and not be producing any future releases.

Whilst not technically correct, I've noted this as a "bug" to ensure it's significance is not lost.

**Comment by OnGle** [comment]
Closing because SugarCRM was not released as part of 15.0 and will not be released in the future.
