### ISSUE TITLE
Magento 1.9 - Flexible Shopping Store eCommerce by TurnKey Linux (HVM)-14.2 wrong image

### ISSUE THREAD

**Issue by gdfSheldon** [turnkeylinux/tracker#1101]
I launched this VM to our AWS cloud and instead of installing M1.9, it actually would up installing M.2.1.7.

**Comment by JedMeister** [comment]
Hi @gdfSheldon - Thanks so much for reporting. You are indeed correct.

Deep apologies on that. Unfortunately, that was/is a mis-labelling issue on our behalf. As you note, our v14.2 Magento appliance [includes Magento 2.1.7](https://github.com/turnkeylinux-apps/magento/blob/14.2/conf.d/main#L3). The labelling of the appliance should have been updated for v14.2 to explicitly note that but unfortunately it got overlooked.

FWIW our v14.1 appliance DOES have Magento v1.9. Although I'm not clear how you might get access to that via the AWS Marketplace? If you'd like me to chase up with AWS MP regarding that, please let me know.

**Comment by JedMeister** [comment]
I've just updated the [appliance](https://github.com/turnkeylinux-apps/magento) readme to note that the next release will be v2.2. We hope to be releasing very soon and the Marketplace will be updated then, so I'm closing this for now. Apologies again on the inconvenience you experienced.
