### ISSUE TITLE
when building packages, ensure .buildinfo is pulled from buildroot prior to destruction

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1104]
When Debian packages are built, there should be a `.buildinfo` file produced (TBH, I haven't double checked but it should be). 

Ideally they should be retrieved from the buildroot prior to destruction. It should probably be saved in `pools/CODENAME/.pools/buildinfo` (or similar).

**Comment by OnGle** [comment]
The 2 above pull requests should allow .buildinfo files to be retained; before the destruction of the buildroot the buildinfo files will be placed in `${POOL_PATH}/.pool/build/buildinfo`

**Comment by OnGle** [comment]
It should also be noted that if you already have pool installed you must delete, recreate and re-initialize your pool directory before usage.
