### ISSUE TITLE
website appliance navigation drill-down issue

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#111]
Reported via email by `Roumen Asenov`:

If I click on the links "Content management" or "Web development", I get the first page of the corresponding selection. If I want to navigate and click on any number at the bottom of the listed systems, "next" or "last", I get a rotating circle (probably representing clock), that stays there forever.

However If I chose "All", then I can navigate through the pages of applications.

Tried on Google Chrome, IE and Android with the same results.
##

**Comment by JedMeister** [comment]
Closing this as it now appears to be working properly. "CONTENT MANAGEMENT" is the only one which has multiple pages and the second page loads fine.
