### ISSUE TITLE
Nginix failing to start (LXC build) - needs to wait for dnsmasq ('nss-lookup.target')

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1110]
Steps to reproduce:
1. Create a v15.0 LXC appliance in a VM or container.
2. Login to the appliance and create a `natbr0` core container
     `root@lxc ~# lxc-create -n core-natbr0 -f /etc/lxc/natbridge.conf -t turnkey -- core`
3. Start the container
     `root@lxc ~# lxc-start -d -n core-natbr0`
4. Create an `nginx-proxy` for the container
     `root@lxc ~# nginx-proxy -d core-natbr0.proxy.lxc -n core-natbr0`
5. Reboot the appliance
6. Login again and check the status of nginx
```
# service nginx status
* nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-06-09 02:25:02 UTC; 28s ago
     Docs: man:nginx(8)
  Process: 853 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, stat
      CPU: 37ms

Jun 09 02:25:02 lxc systemd[1]: Starting A high performance web server and a reverse proxy server...
Jun 09 02:25:02 lxc nginx[853]: nginx: [emerg] host not found in upstream "core-natbr0" in /etc/nginx
Jun 09 02:25:02 lxc nginx[853]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 09 02:25:02 lxc systemd[1]: nginx.service: Control process exited, code=exited status=1
Jun 09 02:25:02 lxc systemd[1]: Failed to start A high performance web server and a reverse proxy ser
Jun 09 02:25:02 lxc systemd[1]: nginx.service: Unit entered failed state.
Jun 09 02:25:02 lxc systemd[1]: nginx.service: Failed with result 'exit-code'.
```
7. Check `/var/log/nginx/error.log`
```
2018/06/09 02:25:02 [emerg] 853#853: host not found in upstream "core-natbr0" in /etc/nginx/sites-enabled/core-natbr0.proxy.lxc:7
```
I believe the problem is caused by systemD trying to start `nginx` before `dnsmasq` is started.  `nginx` needs name resolution (handled by `dnsmasq`) to resolve the `nginx-proxy` address.

**Comment by JedMeister** [comment]
Thanks for the report @Dude4Linux.

I suggest that you try forcing the nginx service to not start until after dnsmasq. Assuming that dnsmasq runs as a service with a unit file named `dnsmasq.service`, something like this should do the trick:
```
mkdir -p /etc/systemd/system/nginx.service.d
cat > /etc/systemd/system/nginx.service.d/10-dnsmasq.conf <<EOF
[Unit]
After=dnsmasq.service
EOF
```

Let me know how that goes...

**Comment by Dude4Linux** [comment]
@JedMeister - I tried your suggestion and it was effective, but I think the problem will affect all appliances running nginx.
From NGINX the /lib/systemd/system/nginx.service should look something like this.
```
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/usr/sbin/nginx -s reload
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
Our TurnKey /lib/systemd/system/nginx.service
```
[Unit]
Description=A high performance web server and a reverse proxy server
Documentation=man:nginx(8)
After=network.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t -q -g 'daemon on; master_process on;'
ExecStart=/usr/sbin/nginx -g 'daemon on; master_process on;'
ExecReload=/usr/sbin/nginx -g 'daemon on; master_process on;' -s reload
ExecStop=-/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target
```
From man systemd.special
```
nss-lookup.target
    A target that should be used as synchronization point for all host/network name service lookups. Note that this is
    independent of user/group name lookups for which nss-user-lookup.target should be used. All services for which the
    availability of full host/network name resolution is essential should be ordered after this target, but not pull it in.
    systemd automatically adds dependencies of type After= for this target unit to all SysV init script service units with
    an LSB header referring to the "$named" facility.
```
Something must be preventing systemd from automatically adding this to nginx.service.  Also the other elements from the `After` line are probably also required for logging and access to remote file systems.

**Comment by JedMeister** [comment]
@Dude4Linux 

FWIW the `/lib/systemd/system/nginx.service` file in TurnKey comes from the Debian [`nginx-common`](https://packages.debian.org/stretch/nginx-common) package (i.e. it's not generated, but included as a file - as is). 

There is an open [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898896) against it for missing `remote-fs.target` but  no reports for other stuff. I tried to recreate the issue you noted, testing the nginx-php-fastcgi appliance as both a VM and a Proxmox container. Both worked fine fro me with fairly minimal resources (which I would have expected might be more likely to show the issue). Either there is something unique to your setup that mine doesn't show, or perhaps it only occurs as an LXC (non-Proxmox) guest? Or perhaps it's purely related to the TurnKey LXC host?

Seeing as expect it's unlikely to cause any issues and assuming that it fixes your bug; I'm open to adding an updated version using your additional info as a common overlay, i.e. something like this in `common/overlays/nginx/etc/systemd/system/nginx.service.d/nginx.conf`:
```
[Unit]
After=syslog.target remote-fs.target nss-lookup.target
```
Note that `network.target` doesn't need to be included again as the `conf` file adds to the existing config (a `/etc/systemd/system/nginx.service` file would overwrite it).

Or perhaps to err on the side of caution we could just include it as part of the `buildtasks/patches/container/conf`? I.e. something like this:
```
if [ -f /lib/systemd/system/nginx.service ]; then
    mkdir -p /etc/systemd/system/nginx.service.d
    cat > /etc/systemd/system/nginx.service.d/10-dnsmasq.conf <<EOF
[Unit]
After=syslog.target remote-fs.target nss-lookup.target
EOF
fi
```

**Comment by JedMeister** [comment]
FWIW it looks like the convention is to call the file `override.conf`, e.g. for Nginx it should be: `/etc/systemd/system/nginx.service.d/override.conf`.

The advantage of using the convention file is that if a user then uses the `systemctl edit nginx.service` command, it will open the existing `override.conf` file for that service (instead of creating a new one).

**Comment by Dude4Linux** [comment]
@JedMeister - Thanks for the tips on SystemD.  Since you weren't able to reproduce the problem, maybe it's a side-effect of my development environment.  I'm still running TKLDev in an LXD container on my laptop.  It started at v14.2, was upgraded to stretch and converted from SysV to SystemD.  Has all the latest for `core`, `common`, `bootstraps`, `buildtasks`, etc.  Since it seemed to be working pretty well, I didn't bother to download `turnkey-tkldev-15.0rc1-stretch-amd64.iso` and setup a new VM on ProxMox. Doing that now to see if it helps.

**Comment by Dude4Linux** [comment]
> I wouldn't expect it to make any significant difference, but who knows?! Fundamentally everything should be similar.

It didn't make any difference.  I still see the behavior where `nginx` refuses to start if there is a proxy defined for a `natbr0` container.

> No problem! It's been a big learning curve for me, so happy to share the gems I've discovered!

I think it has been a big learning curve for the Debian folks too.  I recommend adding an override in `/etc/systemd/system/nginx.service.d/override.conf` in `common`, but I think it should also be reported upstream to Debian so it can be fixed at the source.  As you said, the lack of `remote-fs.target` has already been reported.  `syslog.target` for logging and `nss-lookup.target` for host name service may not always be required, but I'm sure others will eventually find edge cases where they are needed.

> Although, in case you haven't already noticed, deck works quite differently in v15.0. 

I did notice, and had to make some changes to accommodate the new behavior in `lxd-make-image`.

I'm currently working on getting apt-cacher-ng locked down so only containers can access it.  I'll let you know with a pull request when the latest changes are ready for review.

**Comment by JedMeister** [comment]
@Dude4Linux 

Workaround now applied to common: https://github.com/turnkeylinux/common/commit/17976cf63ae5facc73c2332efbc19813975b691e

I've only done preliminary testing, but from your comments, I figure we should be good.

I've also added a note (via email) to the existing Debian bug (figured it was somewhat related): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898896

Closing this issue now, but please reopen if I'm missing something...

**Comment by Dude4Linux** [comment]
@JedMeister - Just wanted to let you know that I tested with the latest changes and it is indeed fixed. Thanks again.

**Comment by JedMeister** [comment]
Awesome @Dude4Linux - thanks for the confirmation. :+1:

**Comment by JedMeister** [comment]
FYI - The Debian `nginx.service` dependency on `nss-lookup.target` is now default. So this will be removed as of v17.0.
