### ISSUE TITLE
TurnKey Core ISO "make" Error

### ISSUE THREAD

**Issue by lightswarm124** [turnkeylinux/tracker#1113]
During "make" for TurnKey Core, the installer ran the following before exiting on an error message. Process could not progress post error message:

fab-chroot build/root.patched --script conf.d/main
+ echo do nothing - core requires no post-package configuration commands
do nothing - core requires no post-package configuration commands
+ dpkg -i /root/inithooks_0.9+*.deb
dpkg: error: cannot access archive '/root/inithooks_0.9+*.deb': No such file or directory
/usr/share/fab/product.mk:535: recipe for target 'build/stamp/root.patched' failed:
make: *** [build/stamps/root.patched] Error 2
root@tkldev products/core#

**Comment by JedMeister** [comment]
Oops! My bad! That line should never have been included/pushed to GH. I included that for testing of new inithooks package and should never have been included in the public repo (the inithooks package will be provided by our repo). FWIW so long as you are happy with an ISO, the current inithooks package (as installed from the turnkey apt repo) should work fine.

Thanks tons for the bug report @lightswarm124! I'll fix it now so it doesn't get forgotten and push it back to GH. I'll post back when I've done that with instructions on how you can fix it~

**Comment by JedMeister** [comment]
Ok I've now removed the errant line from the `conf.d/main` script and pushed the fix back to GH. To update your core repo:
```
cd core
git pull origin master
```
