### ISSUE TITLE
Kliqqi EOL

### ISSUE THREAD

**Issue by spaghettimaster** [turnkeylinux/tracker#1119]
The official site is dead: https://www.kliqqi.com
Repo with the latest version is empty: https://github.com/Kliqqi-CMS/Kliqqi-3-5-2
The old version is here (but it's too old): https://github.com/Kliqqi-CMS/Kliqqi-CMS 

So Kliqqi is probably dead.

**Comment by JedMeister** [comment]
Thanks @spaghettimaster

**Comment by JedMeister** [comment]
@wulungnet - Thanks for that! Nice find and thanks for the additional info! :+1:

**Comment by OnGle** [comment]
Closing as 15.0 is released and Kliqqi was not released.
