### ISSUE TITLE
Standalone MySQL appliance not listening for remote connections

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1121]
During testing I noticed that the MySQL appliance is no longer listening to remote connections (only local ones via the socket). 

I'm happy to leave all the other apps as they are (better security), but the standalone MySQL appliance is likely to be used as a remote DB server, so needs to be pre-configured to be listening remotely. I probably should have noticed when I merged your update https://github.com/turnkeylinux-apps/mysql/pull/12 and said something then. Anyway...

Probably the easiest way to go, is to enable the Adminer user to also be used for remote connections. What do you think?

I've updated the readme to note that the `adminer` account needs to be used for remote connections and have tweaked and updated the changelog (hope you're ok with that). See https://github.com/turnkeylinux-apps/mysql/commit/3ce43f9d73e23066dbe08418ed9fc2e933ffd560

So it just needs to listen for remote connections and it'll be good to go.

**Comment by spaghettimaster** [comment]
Done.
https://github.com/turnkeylinux-apps/mysql/pull/13/
