### ISSUE TITLE
Remove mibew dependency on phpsh

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1122]
For v15.0 we're removing `phpsh` as it's no longer maintained.

It's already been removed from all the other appliances, however, the [mibew](https://github.com/turnkeylinux-apps/mibew) [inithook](https://github.com/turnkeylinux-apps/mibew/blob/master/overlay/usr/lib/inithooks/bin/mibew.py) still depends on it. If we can rework that (perhaps use `php-cli` instead?) then we can remove it altogether.

**Comment by spaghettimaster** [comment]
Done. https://github.com/turnkeylinux-apps/mibew/pull/11
