### ISSUE TITLE
TKLDev-generated .iso and installed/live appliance have different versions of the same file (??)

### ISSUE THREAD

**Issue by qrntz** [turnkeylinux/tracker#1124]
While working on the revision-control appliance a few times something seemed really weird. When I chose to pay attention to it, it occurred to me that e. g. the `/etc/confconsole/services.txt` file doesn't actually seem to change despite me editing it and rebuilding the appliance. However the modification date changes to reflect when I built the appliance. Thought I was going loopy for a bit.

![screenshot](https://user-images.githubusercontent.com/802109/41822461-2d3f10a4-77f0-11e8-999e-a6e83e00c7b0.png)

I have tried a lot of different ways to ensure that the .iso fed to QEMU on the host is the same exact file that is produced by TKLDev and have tried 2 different hosts and a fresh TKLDev installation as well as running the .iso on bare metal via LiveUSB, both installing and running the appliance live. It consistently produces the same result for me: the services.txt of the appliance is different to what is expected. `/etc/confconsole/services.txt` inside the actual appliance running on QEMU or bare metal does not reflect the `/etc/confconsole/services.txt` in the squashfs-compressed rootfs in the .iso which is derived from the overlay, showing what seems to be an older version! I have not actually found a way to modify it which is bizarre.
I still can't say for sure what this is. I would speculate that overlayfs as used by deck produces some leftover filesystem layers that are conditionally visible on the resulting image by TKL booted from the .iso and not the host machine or TKLDev but even that is very much a stretch.

Is anyone else able to reproduce this building from revision-control-fix branch of [my revision-control](https://github.com/qrntz/revision-control) appliance?

**Comment by JedMeister** [comment]
Thanks @qrntz - that seems bizarre and if reproducible is a critical bug! I'll test it myself ASAP and get back to you.

**Comment by JedMeister** [comment]
Ok worked it out! :tada: 

It's an edge case bug in `turnkey-sudoadmin`! It has an overly aggressive [sed line](https://github.com/turnkeylinux/inithooks/blob/4ed432fcdda352437d6f0c1f33b47da60ddce8f7/turnkey-sudoadmin#L114) which when run is adjusting anything with an `@` to be `root@` (or `admin@` - depending on whether it's been turned `on` or `off`).

I've [adjusted `turnkey-sudoadmin`](https://github.com/turnkeylinux/inithooks/commit/179b423942a95d9ec41bf952740382a4c82e51b2) to be more careful and confirmed that it works:
```
root@revision-control ~# diff -u /etc/confconsole/services.txt /etc/confconsole/services-from-overlay.txt 
root@revision-control ~# 
```

:smile:

**Comment by JedMeister** [comment]
Closing as of https://github.com/turnkeylinux/inithooks/commit/179b423942a95d9ec41bf952740382a4c82e51b2

**Comment by JedMeister** [comment]
FWIW Alon has rebuilt inithooks (last night my time) so this should be included in new builds.
