### ISSUE TITLE
Docker Hub TKL images are versioned correctly but in an odd notation

### ISSUE THREAD

**Issue by qrntz** [turnkeylinux/tracker#1133]
The [TKL Docker Hub repo](https://hub.docker.com/u/turnkeylinux/) contains some appliance-version combination images. They are named as `turnkeylinux/(appliance-name)-(appliance version):latest` while the widely accepted format is to version using Docker tags so it would be `turnkeylinux/(appliance-name):(appliance-version)` instead which should be more intuitive to Docker users. So, the tag has to contain the version and the latest tag has to point to the latest version tag of the image ideally.

**Comment by JedMeister** [comment]
Brilliant work on this mate! Unfortunately due to a TKLBAM bug, I'm going to need to rebuild all the Docker and LXC builds. But this worked a treat.
