### ISSUE TITLE
Mediaserver HTTPS not working

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1142]
As per subject, HTTPS link (port 8920) isn't working for Emby (only HTTP working).

I also noticed that according to the UI, there is a new version but it's not available from the repo. Looks like we might need to install an alternative way?!

As an addendum, it appears that the new version of Emby uses `/var/lib/emby` to store it's data, so the tklbam profile will also need adjustment (the legacy version of Emby uses `/var/lib/emby-server`).

**Comment by spaghettimaster** [comment]
https://github.com/turnkeylinux-apps/mediaserver/pull/13

**Comment by spaghettimaster** [comment]
https://github.com/turnkeylinux-apps/mediaserver/pull/14

**Comment by JedMeister** [comment]
Thanks @spaghettimaster . I'll get onto this ASAP...
