### ISSUE TITLE
repository invalid signature

### ISSUE THREAD

**Issue by mr-flibble** [turnkeylinux/tracker#1149]
Hello, if I run apt-update on my **TurnKey Linux 13.0 / Debian 9.4 Stretch** I get error about invalid signature for repository, mabye because gpg key is expired...
```
Hit:13 http://archive.turnkeylinux.org/debian wheezy Release
Err:15 http://archive.turnkeylinux.org/debian wheezy-security Release.gpg
  The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
Err:16 http://archive.turnkeylinux.org/debian wheezy Release.gpg
  The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.turnkeylinux.org/debian wheezy-security Release: The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.turnkeylinux.org/debian wheezy Release: The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/wheezy-security/Release.gpg  The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/wheezy/Release.gpg  The following signatures were invalid: 694CFF26795A29BAE07B4EB585C25E95A16EB94D
W: Some index files failed to download. They have been ignored, or old ones used instead.

```
If I run:  apt-key list | grep expired
I get:
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
pub   rsa4096 2010-08-27 [SC] [expired: 2018-03-05]
uid           [ expired] Debian Archive Automatic Signing Key (6.0/squeeze) <ftpmaster@debian.org>
pub   rsa4096 2010-08-07 [SC] [expired: 2017-08-05]
uid           [ expired] Squeeze Stable Release Key <debian-release@lists.debian.org>
```

What can I do to fix it please?

PS: I posted this on turnkey forum (here https://www.turnkeylinux.org/forum/support/sat-20180707-0949/repository-invalid-signature ) but somebody deleted it without any explanation
Thank you

**Comment by JedMeister** [comment]
Thanks for posting. 

I'm really sorry for accidentally deleting your forum post! :cry: 

By way of explanation, the forums have been hit with a lot of spam lately and I've also been laser focused on getting our long-overdue upcoming release (based on Debian 9 / Stretch) finished. So I didn't even realise that I'd done that. I actually may have accidentally deleted your website user account too (I hope not, but I'm pretty sure I didn't explicitly delete your forum post, so it's possible).

Anyway, I've (manually) reposted your question on the [forums](https://www.turnkeylinux.org/forum/support/wed-20180711-0726/repository-invalid-signature) and [answered](https://www.turnkeylinux.org/forum/support/wed-20180711-0726/repository-invalid-signature#comment-29765) it there too.

Apologies again on my hasty actions... I'll try to be much more careful when cleaning up spam in the future.

**Comment by mr-flibble** [comment]
Thank you for reply a no problem :-)
Have a nice day!
