### ISSUE TITLE
Consider not installing postgresql-x.x-postgis-y.y package in standalone Postgres appliance

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1154]
I'm not 100% sure that this will still be relevant in v16.0, but I've renamed it and pinned it to the v16.0 milestone...

----

I just noticed that the v15.0 standalone [PostgreSQL](https://www.turnkeylinux.org/postgresql) appliance is over 100MB bigger than [LAPP](https://www.turnkeylinux.org/lapp) (Linux-Apache-PostgreSQL-PHP/Python/Perl) appliance!

After a bit of investigation, it appears that the culprit is [`postgresql-9.6-postgis-2.3`](https://packages.debian.org/stretch/postgresql-9.6-postgis-2.3).

Whilst [PostGIS](https://postgis.net/) looks like a very cool library to have included (a requirement if you plan to use spatial and geographic objects), if you follow it's dependency tree it has a whopping 246 dependencies (i.e. if you count dependencies of dependencies etc). Once installed that accounts for an additional 342 MB of installed disk space!

So whilst it may be a very cool library, considering the space it takes up (inc full dependency tree), it seems a little excessive to include something that is clearly quite a specialist library.

I vote we remove it for v15.1. On the other hand, it's been included in the appliance (at least) since [v12.0](https://github.com/turnkeylinux-apps/postgresql/blob/12.0/plan/main#L5) so perhaps users expect it? Still, I think it's excessive when it's easily installed via apt.

FWIW, here's all the dependencies it wants to install:
```
  fontconfig fontconfig-config fonts-dejavu-core libaec0 libarmadillo7 libarpack2 libasound2 libasound2-data libass5 libasyncns0 libatomic1 libaudio2 libavahi-client3
  libavahi-common-data libavahi-common3 libavc1394-0 libavcodec57 libavdevice57 libavfilter6 libavformat57 libavresample3 libavutil55 libblas-common libblas3 libbluray1
  libboost-chrono1.62.0 libboost-date-time1.62.0 libboost-filesystem1.62.0 libboost-program-options1.62.0 libboost-serialization1.62.0 libboost-system1.62.0 libboost-test1.62.0
  libboost-thread1.62.0 libboost-timer1.62.0 libbs2b0 libcaca0 libcairo2 libcdio-cdda1 libcdio-paranoia1 libcdio13 libcgal12 libchromaprint1 libcoin80v5 libcroco3 libcrystalhd3
  libcups2 libdap23 libdapclient6v5 libdapserver7v5 libdatrie1 libdbus-1-3 libdc1394-22 libdrm2 libebur128-1 libegl1-mesa libepsilon1 libfaad2 libfftw3-double3 libflac8 libflite1
  libfontconfig1 libfreexl1 libgbm1 libgdal20 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgeos-3.5.1 libgeos-c1v5 libgeotiff2 libgfortran3 libgif7 libgl1-mesa-glx libglapi-mesa
  libglib2.0-0 libgme0 libgomp1 libgraphicsmagick-q16-3 libgraphite2-3 libgsm1 libharfbuzz0b libhdf4-0-alt libhdf5-100 libice6 libiec61883-0 libiso9660-8 libjack-jackd2-0 libjbig0
  libjpeg62-turbo libjson-c3 libkmlbase1 libkmlconvenience1 libkmldom1 libkmlengine1 libkmlregionator1 libkmlxsd1 liblapack3 liblcms2-2 libldb1 libltdl7 liblwgeom-2.3-0 libmad0
  libmariadbclient18 libminizip1 libmng1 libmodplug1 libmp3lame0 libmpcdec6 libmpfr4 libmpg123-0 libnetcdf11 libnspr4 libnss3 libnuma1 libodbc1 libogdi3.2 libogg0 libopenal-data
  libopenal1 libopencv-core2.4v5 libopencv-imgproc2.4v5 libopenjp2-7 libopenmpt0 libopenscenegraph100v5 libopenthreads20 libopus0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
  libpgm-5.2-0 libpixman-1-0 libpoppler-glib8 libpoppler64 libpostproc54 libproj12 libpulse0 libpython2.7 libqhull7 libqt4-opengl libqtcore4 libqtgui4 libquadmath0 libraw1394-11
  librsvg2-2 librubberband2 libsamplerate0 libsdl2-2.0-0 libsfcgal1 libshine3 libsm6 libsmbclient libsnappy1v5 libsndfile1 libsndio6.1 libsodium18 libsoxr0 libspatialite7 libspeex1
  libssh-gcrypt-4 libsuperlu5 libswresample2 libswscale4 libsz2 libtalloc2 libtbb2 libtdb1 libtevent0 libthai-data libthai0 libtheora0 libtiff5 libtwolame0 liburiparser1 libusb-1.0-0
  libv4l-0 libv4lconvert0 libva-drm1 libva-x11-1 libva1 libvcdinfo0 libvdpau1 libvorbis0a libvorbisenc2 libvorbisfile3 libvpx4 libwavpack1 libwayland-client0 libwayland-cursor0
  libwayland-egl1-mesa libwayland-server0 libwbclient0 libwebp6 libwebpmux2 libwmf0.2-7 libx11-6 libx11-data libx11-xcb1 libx264-148 libx265-95 libxau6 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb1 libxcursor1 libxdamage1 libxdmcp6 libxerces-c3.1 libxext6 libxfixes3 libxi6
  libxine2 libxine2-bin libxine2-ffmpeg libxine2-misc-plugins libxine2-plugins libxinerama1 libxkbcommon0 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6 libxtst6 libxv1
  libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common libzvbi0 mysql-common odbcinst odbcinst1debian2 postgresql-9.6-postgis-2.3 proj-data python-talloc qtcore4-l10n samba-libs
  shared-mime-info x11-common xkb-data
```

**Comment by wulungnet** [comment]
What if putting it on optional ?
Can it be scripted on install dialog ? Add offline mode, so, if needed, pull it from repo with simple command after connected to internet.

Sorry my language. Quick reply mode.

**Comment by JedMeister** [comment]
Hi @wulungnet - so loing as you have internet access, it can easily be installed:
```
apt-get update
apt-get install postgresql-9.6-postgis-2.3
```

**Comment by qrntz** [comment]
I think this is a good candidate for inclusion into inithooks/confconsole rather than the base image.

**Comment by JedMeister** [comment]
This doesn't appear to be an issue in v16.0 (Buster based). The v16.0 PostgreSQL appliance is ~10MB smaller than the LAPP appliance which is closer to what I would have expected...
