### ISSUE TITLE
Does Zoneminder really need port 444 open?!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1156]
On final review of Zoneminder, I've noted that Zoneminder `Makefile` is setting port `444` (added [here](https://github.com/turnkeylinux-apps/zoneminder/commit/0ce8b8cc53f58ec329a74f0eb86abb31ec1c12fe) when the ports were initially added).

I've just checked within a running Zoneminder instance and it doesn't appear to be being used?!:
```
root@ZONEMINDER-AUTO ~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:12321           0.0.0.0:*               LISTEN      2492/stunnel4       
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      483/mysqld          
tcp        0      0 127.0.0.1:10000         0.0.0.0:*               LISTEN      763/perl            
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3457/sshd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      592/master          
tcp        0      0 127.0.0.1:12319         0.0.0.0:*               LISTEN      296/shellinaboxd    
tcp        0      0 0.0.0.0:12320           0.0.0.0:*               LISTEN      2492/stunnel4       
tcp6       0      0 :::12322                :::*                    LISTEN      5586/apache2        
tcp6       0      0 :::80                   :::*                    LISTEN      5586/apache2        
tcp6       0      0 :::22                   :::*                    LISTEN      3457/sshd           
tcp6       0      0 :::443                  :::*                    LISTEN      5586/apache2        
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           763/perl  
```
I've also done a fair bit of googling and can't find any mention of port 444 in relation to Zoneminder - although it's possible I'm missing something.

@MPTMG - do you have any idea?

**Comment by JedMeister** [comment]
I just discovered that port 444 is the default port for [SNPP](https://en.wikipedia.org/wiki/Simple_Network_Paging_Protocol), perhaps Zoneminder can or does user that? Again though, I can't find anything about it on Zoneminder site or forums.

**Comment by MPTMG** [comment]
No it is not needed. It can be removed.

**Comment by JedMeister** [comment]
Thanks for the confirmation man. Yeah when I was doing final test before building it for real, I did a quick google for common issues and that came up. So thought I better fix it! :)

**Comment by JedMeister** [comment]
Have removed port 444 from the firewall ports (in the Makefile). Closing...
