### ISSUE TITLE
TKLDev v15.0 not working as documented

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1157]
Amorminio posted in the [forums](https://www.turnkeylinux.org/forum/support/fri-20180720-1657/sandbox-make-error) re an issue when trying to follow the TKLDev docs. As I noted there, the issue appears to be `deck` missing support for a switch which `fab` expects.

We need to do one (or more) of the following:
- update deck to support `--get-level`; and/or
- update fab so it works around the missing switch; and/or
- update the TKLDev docs so that they "just work"

**Comment by OnGle** [comment]
This is somewhat a duplicate of https://github.com/turnkeylinux/tracker/issues/1057

**Comment by JedMeister** [comment]
Closing this...
