### ISSUE TITLE
Magento - instructions to access admin area not correct

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1167]
As noted by Mateusz in the [forums](https://www.turnkeylinux.org/forum/support/wed-20180801-1202/magento-1501), the Magento app page notes access admin area via "domain/admin", but actually it is via 'domain/admin_XXXXX' (where "XXXXX" is a random string).

I'm not sure of the best way to document that, but it should be noted.

**Comment by JedMeister** [comment]
FWIW this commandline script will give you the admin_XXXXX value:

```
grep -r \'admin_ /var/www/magento/app/etc/env.php | sed "s|^.*admin|admin|; s|'.*||"
```
E.g.:
```
admin@magento ~$ grep -r \'admin_ /var/www/magento/app/etc/env.php | sed "s|^.*admin|admin|; s|'.*||"
admin_1a01yb
admin@magento ~$ 
```

**Comment by l-arnold** [comment]
You can also find the Admin Location off of the Magento (non-admin) default page by copying the Link that is referenced from "login to Admin".

Where the system is not correct is that ConfConsole is not reflecting that link.  That would be helpful.

**Comment by JedMeister** [comment]
@OnGle has provided a fix for this via https://github.com/turnkeylinux-apps/magento/pull/23 That will set the URL as noted in Confconsole to provide the correct one. I intend to merge that code and include it in the next update (i.e. when we next rebuild Magento).

@l-arnold - AFAIK the exact URL is generated at Magento install time. As we pre-install Magento, it should be different for each and every TurnKey release. Although it's probably worth noting that by default that also means that all users of a particular TurnKey release will have the same relative Admin URL. In a perfect world, the relative Admin URL would be (re)generated on firstboot (so each individual instance is unique). We'd like to implement that, although it'd possibly be a good idea for all appliances (not just Magento), so we'll probably leave that for another day...
