### ISSUE TITLE
Magento and other apps - document usage of composer

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1168]
As noted by Mateusz in the [forums](https://www.turnkeylinux.org/forum/support/wed-20180801-1202/magento-1501), the Magento app includes composer, however by default a user would likely use root. That could cause some permissions issues and also has potential [security concerns](https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md) (due to commands that could potentially be run as the user running composer).

At the very least we should document how to use composer with the existing `www-data` user. I.e.:

```
# bash shell:
su - www-data -s /bin/bash

# or sh shell:
su - www-data -s /bin/sh

# and/or to run a single command - works with either bash or sh, can use single (') or
# double (") quotes around command:
su - www-data -s /bin/sh -c "ls /var/www/magento"
```

Alternatively we could create a new specific user (as suggested by Mateusz). That would probably require a little more thought to avoid the potential pitfalls. Although perhaps simply making it a member of the `www-data` group would be sufficient?

Regardless, this should probably be documented for all applainces that use composer (not just magento).

**Comment by JedMeister** [comment]
As of v16.1, a convenience `turnkey-composer` script is included which provides a wrapper around `composer` run as `www-data`.

So instead of:
```
su - www-data -s /bin/sh -c "composer --SWITCH SOME_COMMAND"
```
You can instead run:
```
turnkey-composer --SWITCH SOME_COMMAND
```
This still requires documenting, but the functionality should be good.

**Comment by OnGle** [comment]
Closing due to significant overlap with the above reference issue which has had more attention.
