### ISSUE TITLE
Consider pre-installing the Prestashop 1-Click Upgrade module

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1171]
I just discovered that there is a [1-Click Upgrade module](http://doc.prestashop.com/display/PS16/Automatic+update) for Prestashop. We should be pre-installing this IMO.

**Comment by JedMeister** [comment]
FWIW, this may be possible via commandline?! See [docs](https://devdocs.prestashop.com/1.7/modules/concepts/commands/) and [this thread](https://www.prestashop.com/forums/topic/441297-install-modules-via-php-cli/) (more recent comments towards the end).

**Comment by JedMeister** [comment]
Oops, this missed v16.1... Moving to v16.2 (if it happens... otherwise, it'll go to v17.0).

**Comment by OnGle** [comment]
Currently not possible due to upstream bug: https://github.com/PrestaShop/PrestaShop/issues/23370

Once upstream bug is fixed this should be as easy as:

```bash
cd /var/www/prestashop
php ./bin/console prestashop:module install autoupgrade
```
