### ISSUE TITLE
Consider using MySQL to back Mumble

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1172]
Currently the TurnKey Mumble server uses SQLite as it's DB backend.

Whilst Mumble/murmur recommend SQLite as their default and most tested DB backend, SQLite has some limitations. Particularly lack of support for concurrent connections. It also isn't suitable for scaling and/or failover - e.g. via multiple remote instances.

As such it may be better to include MySQL as the default DB backend on our appliance?

**Comment by qrntz** [comment]
I think SQLite is going to be OK for most users. Since the database is offline it necessarily has its limitations (no scaling/failover) but also its advantages (smaller attack surface, less complexity).

I would be in favor of leaving the default option to be SQLite but including an inithook that would set Mumble up with MySQL. This way whoever needs a more complex solution will have a seamless way to set it up and we don't need to get rid of what already works.

**Comment by MPTMG** [comment]
I can do this in the next couple days if you would like. I recommend using mysql as a default.

My reasoning is: 

1) Those that don't need MySQL will be blissfully unaware that it is using MySQL.
2) Those that need MySQL will have nothing extra to do in confconsole.
3) Change is very simple: Add LAMP to plan/main, create db, dbuser in conf.d/main, (20)inithook to reset dbuser and dbpass (edit murmur.ini with the new values) all transparent to the end user.
4) Any existing user upgrading would still just have simple import/export of existing sqlite database to upgrade. And a nice web based interface for importing their existing data.

Any objections? Only use case I see this being a bit more complex that would warrant a confconsole plugin would be where the configuration needs to be specified for a database not local to the host. I think in that case though it would be simple enough for that user to just edit mumble config directly as it is essentially only 4 lines of editing (database URL/IP, user, pass, db). Those users could would be able to write their own script to run after setup to handle that easily also.

**Comment by JedMeister** [comment]
Hey @MPTMG 

If you're happy to do it, I'm fine with it being done.

I'm not sure when we'll next release it, but I'm really hoping to get a regular (perhaps monthly?) update release cycle going (i.e. every month, any appliances with new commits get rebuilt with a version bump).

So if you could also add a new changelog entry noting what you've done as part of the pull request, that'd be great.

**Comment by MPTMG** [comment]
Knocked this out this evening. Merged back into my fork (master). Everything is transitioned to MySQL/MariaDB. Only thing left to do is add Adminer to confconsole/tkl-wcp and update changelog.

Obviously no rush on integrating changes it can be done down the road, just closing the loop that this feature is essentially complete for when time permits it to be integrated. Also great work on v15.0 and thanks for the mention in the blog post.

**Comment by MPTMG** [comment]
@JedMeister since this is still sitting with the MySQL integration not merged is there an interest in adding rocket.chat to the appliance. Presently a lot of people are moving to Discord due to the integrated persistent chat features. Adding rocket.chat to this appliance would provide the same functionality while affording users greater security by owning their data.

**Comment by JedMeister** [comment]
Hey @MPTMG - apologies things stalled with this. I had intended to get back to it, but got sompletely sidetracked with other stuff (which always seems to happen...). I guess the "squeaky wheel gets the oil"! And you're not anywhere near "squeaky" enough! :wink: 

I really like the idea of adding rocket chat so that there is both voice and text chat in the one appliance. Please feel free to do that. Hit me up if you need any advice or guidance.

Also please feel free to bump me when you're ready - and again (and again, etc) if I don't respond within a few days to a week. Hopefully I won't be too slow responding, but sometimes I need a nudge.

**Comment by JedMeister** [comment]
Moving to v17.0 - although I note it is only wishlist.

**Comment by JedMeister** [comment]
Unfortunately mtpg has closed his account so we lost the PR he had prepared... :cry: 

Whilst I still think the rationale of including MySQL is reasonable, I'm going to close this issue for now. If there is further interest, it can be reopened (or a new equivalent issue opened). Adding the `won't fix` label for now, although I'm happy to consider including this...
