### ISSUE TITLE
v15.x Hub appliances - "applications settings" box missing

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1177]
We've just had a bug report that when trying to launch v15.x appliances from the Hub, the "Applications settings" box (where the `APP_PASS` etc are set) is missing. E.g. here's is what the Joomla appliance should display (as seen when launching v14.x app):

![hub-bug-joomla-example](https://user-images.githubusercontent.com/818633/44181391-e369a600-a144-11e8-9756-9e6ebe29bff7.png)

That section is missing from the v15.x launch page.

I've asked Alon to make resolving this a priority.

**Comment by alonswartz** [comment]
Thanks for the report! I just deployed a fix, please re-open if there are still issues.
