### ISSUE TITLE
OrangeHRM forces user to change admin password on initial log in

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1181]
In testing the v15.0 OrangeHRM server, I noticed that it forced me to change my admin user login on first login:

![screenshot from 2018-08-21 14-43-17](https://user-images.githubusercontent.com/818633/44380782-bb1ce580-a550-11e8-9522-6fd1d7d91791.png)

It notes that my password is "weak" (it's a 8 character password with an upper case, lowercase and a number). Perhaps it's just triggering that because of the way we're setting the initial password? Although when I did reset my password, it required me to also add a "special character".

Ideally user shouldn't need reset their password on first login. But OTOH, it's not a showstopper, so I'll add it here as a feature request.

**Comment by adrianjcalvert** [comment]
This seems to "disable" the user account if the user presses cancel as well. Absolute PITA.

**Comment by JedMeister** [comment]
Moved to 16.0 and upgraded to a bug.

**Comment by OnGle** [comment]
Identified the issue, as far as I can tell this issue is resolved by increasing the minimum complexity in the orangehrm password inithook. As the password reset page is only shown when the password set at firstboot does not meet the minimum complexity requirements of orangehrm

**Comment by JedMeister** [comment]
Assume work @OnGle - I just double checked and this issue is definitely resolved in v16.0 - fingers crossed, will be published early next week.
