### ISSUE TITLE
Mambo - Error code 500

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#1185]
/mos/Contact_Us/Itemid,3/ path returns error code 500 

Apache logs show [
`Wed Aug 29 14:29:25.588392 2018] [:error] [pid 930] [] PHP Fatal error:  Cannot redeclare quoted_printable_encode() in /var/www/mambo/includes/vcard.class.php on line 67`

**Comment by JedMeister** [comment]
Thanks for reporting @qq7 

As Mambo is quite old and requires PHP5.x (and is currently unmaintained), I think that we should probably deprecate the appliance once [PHP5.6 reaches EOL](https://secure.php.net/supported-versions.php) (end of 2018).
