### ISSUE TITLE
"Bugzilla needs a legitimate login and password to continue"

### ISSUE THREAD

**Issue by martijintro** [turnkeylinux/tracker#1191]
...occurs when i try to log in with my admin user.

Why?

Regards,
Jan

**Comment by JedMeister** [comment]
Hi Jan,

FWIW, this is our "issue tracker" for bugs and feature requests. Generally support is best handled via our [forums](https://www.turnkeylinux.org/forum). But seeing as we're here... (and perhaps you've found a bug?)

TBH, I have no idea. I haven't struck that issue. Could you please provide a bit more info about where you're running Bugzilla and/or how you installed it, what appliance version you're using etc. Ideally if you can provide enough info that I can recreate the problem, then perhaps you've found a bug?

**Comment by martijintro** [comment]
Ok thx

 

Von: Jeremy Davis <notifications@github.com> 
Gesendet: Donnerstag, 6. September 2018 09:13
An: turnkeylinux/tracker <tracker@noreply.github.com>
Cc: martijintro <dev@intro.ch>; Author <author@noreply.github.com>
Betreff: Re: [turnkeylinux/tracker] "Bugzilla needs a legitimate login and password to continue" (#1191)

 

Hi Jan,

FWIW, this is our "issue tracker" for bugs and feature requests. Generally support is best handled via our forums <https://www.turnkeylinux.org/forum> . But seeing as we're here... (and perhaps you've found a bug?)

TBH, I have no idea. I haven't struck that issue. Could you please provide a bit more info about where you're running Bugzilla and/or how you installed it, what appliance version you're using etc. Ideally if you can provide enough info that I can recreate the problem, then perhaps you've found a bug?

**Comment by martijintro** [comment]
now i have an account on https://www.turnkeylinux.org, but so it seems i can't do a forum post:

cant see any "new post" option here: 
![image](https://user-images.githubusercontent.com/42765391/45289017-65eb4880-b4ec-11e8-8e98-08454604debb.png)

**Comment by JedMeister** [comment]
Sorry that it's not as obvious as it probably should be... I'll get our web dev guy to have a look at that ASAP.

It's the "Add new forum topic" towards the top left (just below the TurnKey logo). See doctored screenshot:
![forums](https://user-images.githubusercontent.com/818633/45340421-d91eb880-b5d9-11e8-8512-d0e75d011ae6.png)

**Comment by martijintro** [comment]
thx!!
