### ISSUE TITLE
Website - link to add new forum post should be more obvious

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1193]
The add new forum post link isn't very obvious. It should stand out much more IMO, and perhaps should be directly above the forums area (rather than up in that corner).

![forums](https://user-images.githubusercontent.com/818633/45340421-d91eb880-b5d9-11e8-8512-d0e75d011ae6.png)

**Comment by JedMeister** [comment]
FWIW here's what we're thinking, something like this:

![new-forum-thread-button](https://user-images.githubusercontent.com/818633/47131625-719c0d00-d2eb-11e8-806a-ba3cb6cabef7.png)

Although TBH, I'd prefer it in the middle, directly above the threads. We'll see if that's easy enough. Even what's in this pic is a vast improvement on the current situation! If you have any further feedback, I'd love to hear your thoughts (especially as someone bitten by this...)

**Comment by maphew** [comment]
I'd first expect it to be underneath the nav hierarchy - _Home  / Forums / {section}_  - and above the list of threads, left aligned with [Topic] column heading or right aligned above [Last Reply]. If the template requires placement under the banner, aligning it right or center would be an improvement.

At the bottom of the thread list table would work too, but not down in the footer.

**Comment by JedMeister** [comment]
Thanks for the feedback.

I was thinking essentially just centring it. However, now you mention it; this:

> underneath the nav hierarchy - Home / Forums / {section} - and above the list of threads, left aligned with [Topic] column heading

:+1:

**Comment by JedMeister** [comment]
Ok this has (finally) been address. Now if you are logged in you'll see this:

![forum-turnkey-gnu-linux-logged-in](https://user-images.githubusercontent.com/818633/47695475-579ceb80-dc56-11e8-8a44-568c87291670.png)

----
And if you aren't logged in, you'll see this:

![forum-turnkey-gnu-linux-not-logged-in](https://user-images.githubusercontent.com/818633/47695492-61265380-dc56-11e8-9490-5ff93272899f.png)
