### ISSUE TITLE
EasyRSA doesn't provide an openssl.cnf file for OpenSSL 1.1.0f

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1200]
As the title suggests easy rsa does not provide an openssl.cnf file for OpenSSL 1.1.0f (or actually any 1.1.x versions).

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851059
And corresponding bug on the easy-rsa tracker: https://github.com/OpenVPN/easy-rsa/issues/159

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/openvpn/pull/22/commits/7937629a188e3db50f1be640df8ed79d3c728a92#diff-29ac556b17810d3f96aef099659745dbR33

Also see further comment https://github.com/turnkeylinux-apps/openvpn/pull/22/commits/7937629a188e3db50f1be640df8ed79d3c728a92#r221468138
