### ISSUE TITLE
Confconsole - Let's Encrypt plugin - support for dns-01 challenge

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1204]
As requested by Dilshan in a [comment](https://www.turnkeylinux.org/comment/29449#comment-29449) on our docs.

Currently Confconsole leverages the Debian package of Dehydrated (in Stretch that's version [0.3.1](https://packages.debian.org/stretch/dehydrated)). That version of Dehydrated only supports the http-01 challenge and the Confconsole Let's Encrypt plugin was explicitly designed to only support that challenge type.

However, newer versions of Dehydrated ([0.6.2](https://packages.debian.org/stretch-backports/dehydrated) is currently in Stretch backports) also support dns-01 (and tls-alpn-01). It'd be great to at least support dns-01 challenges, which would make it easy for non-publicly available servers to get valid certificates.

**Comment by NitrogenUA** [comment]
@JedMeister Hi! I am attempting an [implementation for this](https://github.com/turnkeylinux/confconsole/pull/63). The idea is to leverage lexicon for DNS manipulation. There is a number of challenges, however, stemming from base OS version disparity between various builds of turnkey as well as general age of packages in the Debian repository.

Present implementation is intermediary and only concerns dehydrated-wrapper. If this is found acceptable, we can then discuss the implementation of GUI component.

Looking forward to your feedback!

**Comment by JedMeister** [comment]
Thanks for having a crack at this @NitrogenUA. I'll reserve specific discussion for the pull request, but your work looks pretty good to me. Looks like you fixed a couple of bugs/oversights as well! :smile: 

As for your suggestion of "the implementation of GUI component". Are you referring to Webmin? If so, then I've actually been considering how we might be able to integrate Confconsole functionality into Webmin. So perhaps we could look at that a bit closer and kill 2 birds with one stone? (FWIW Webmin is written in Perl and whilst I'm not very proficent with Perl, it's not too bad).

Slava Ukraini!

**Comment by NitrogenUA** [comment]
@JedMeister Guess, I should've been more specific :blush: I meant the confconsole TUI rather! But now that I know you're onboard with the initial implementation - UI part should be fairly trivial, hopefully.

Thanks for the support :muscle:

**Comment by JedMeister** [comment]
> @JedMeister Guess, I should've been more specific  I meant the confconsole TUI rather! But now that I know you're onboard with the initial implementation - UI part should be fairly trivial, hopefully.

Ah of course... Sorry, I should have been able to work that out myself! The fact that your Confconsole PR didn't include any changes to the actual Confconsole (python) code should have been a giveaway! :blush: 

> Thanks for the support

You guys deserve all the support you can get! We've got a complete gun Ukrainian dev on the team and we've worked with a few Ukrainians over the years. So Ukraine is pretty close to my heart. Once you guys kick out the Russian invaders, I'm pretty keen to come for a visit and hopefully give a bit of a hand with cleanup etc while I'm there! :smile: 

Thanks for your contribution too! :smile:

**Comment by JedMeister** [comment]
This will be a part of v18.0! :smile: Thanks again @NitrogenUA - deep apologies on how long it's taken to get this included in a default TurnKey release...
