### ISSUE TITLE
TKLBAM - /etc/cron.daily/tklbam-backup file does not exist by default

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1209]
It has been [pointed out](https://github.com/turnkeylinux/tklbam/commit/34ed78c5a50a3c3a0ba1083bee375244fcad107c#commitcomment-30790187) that the `/etc/cron.daily/tklbam-backup` does not exist by default in v15.0!

The file should exist, but be non-executable by default. Until then the documented way to enable the cron job (i.e. `chmod +x /etc/cron.daily/tklbam-backup`) doesn't work!

(Another) gross oversight on my behalf.

This is fairly high priority issue IMO!

**Comment by cboulanger** [comment]
Hi, since the fix is not yet in the currently published template, how can I fix this in a recently created container?

**Comment by JedMeister** [comment]
Hi @cboulanger - it has been fixed, just not all the appliances include the fixed package by default. This should do the trick:
```
apt update
apt install tklbam
```

**Comment by cboulanger** [comment]
That worked, thank you!
