### ISSUE TITLE
UrBackup (New Appliance and maybe confconsole plugin)

### ISSUE THREAD

**Issue by MPTMG** [turnkeylinux/tracker#1216]
If interested I could build a UrBackup server appliance.

https://www.urbackup.org
Debian packages:
https://hndl.urbackup.org/Server/2.2.11/debian/stretch/

Also a confconsole plugin could be created to setup the client version as an alternative for those that don't use turnkey backup and migration. Haven't used the linux client for backups, but the windows and osx clients are solid. I will play with the linux backup client to see if it is suitable for use.

If there is interest let me know.

**Comment by MPTMG** [comment]
If TKLBAM is keeping the lights on forget about it and close the issue.

No reason to do additional work building an appliance and offering it up when that time could be spent improving TKLBAM.

**Comment by JedMeister** [comment]
Ok thanks for your understanding @MPTMG. I'll close for now then. (Although in fairness, not sure when we'll get to TKLBAM; but it really needs some love...)
