### ISSUE TITLE
Hub / AWSMP - support for new AWS instance sizes (e.g. T3, M5, C5, R5, etc)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1225]
The current TurnKey AMIs are not compatible with the new AWS instance types (e.g. T3, M5, C5, R5, etc).

From my reading to date, the primary requirement is to support for AWS [Enhanced Network Adaptor (ENA)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html). I'm not 100% sure, but I think the main thing that is needed for that is a driver. It appears that the driver (`ena.ko` from my reading of the [source repo](https://github.com/amzn/amzn-drivers/tree/master/kernel/linux/ena)) is already in the Debian kernel, e.g. [Stretch's 4.9.0](https://packages.debian.org/stretch/amd64/linux-image-4.9.0-7-amd64/filelist) has this listed:
```
/lib/modules/4.9.0-7-amd64/kernel/drivers/net/ethernet/amazon/ena/ena.ko
```

However, having the drivers is not enough. When creating the AMI, the option `--ena-support` also needs to be passed (so that AWS is aware that the AMI is compatible). I assume that [`bt-ec2`]() will need a minor adjustment to support that, and/or [`ebs.py`](https://github.com/turnkeylinux/buildtasks/blob/master/bin/ec2/ebs.py) and [friends](https://github.com/turnkeylinux/buildtasks/tree/master/bin/ec2). FWIW, there is an AWS "troubleshooting ENA" doc [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).

Another potential issue is that apparently the latest gen instance types use NVMe drives, so that the drive devices are labelled differently. So instead of Xen defaults of `/dev/xvdXY` (e.g. partition 1 of first device: `/dev/xvda1`) they are `/dev/nvmeXn1pY` (IIUC partition 1 of first device: `/dev/nvme0n1p1` - somewhat similar to SSD cards, apparently the `n1` is just a "NVMe namespace"?!).

Possibly the best workaround for supporting all instance types/sizes with a single AMI would be to use UUIDs in the `/etc/fstab`, then it shouldn't matter whether which generation of instance type is used and which type of drive they are.

**Comment by OnGle** [comment]
From my testing it appears xvd entries in fstab still loads nvme drives, oddly enough adding ena_support seems to be enough to make these new instances work fine.

**Comment by JedMeister** [comment]
This seems to be working awesome! :+1:

**Comment by JedMeister** [comment]
Removing Hub label and opening a new/separate feature request for that.
