### ISSUE TITLE
New Appliance Suggestion: Plikli

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1234]
Reference of https://github.com/turnkeylinux/tracker/issues/1119#issuecomment-419554922 by wulungnet.
Project based off Pligg and Kliqqi 

[Plikli Website](https://www.plikli.com/)
[Plikli Github](https://github.com/Plikli-CMS/Plikli-CMS)

**Comment by JedMeister** [comment]
Plikli appears to be dead (both GitHub and website 404).
