### ISSUE TITLE
wordpress 15.1 database conenction error on latest vmware

### ISSUE THREAD

**Issue by Rimplestilhskin** [turnkeylinux/tracker#1250]
In live cd mode using the latest wordpress turnkey ISO 15.1 woardpress works perfectly.
turnkey-wordpress-15.1-stretch-amd64.iso

The moment you install and then boot into this with 100% same settings, the database error happens with same passwords, same password spelling etc...

Error establishing a database connection

1st noticed this on the VMDK and database error.

Deleted and extracted 12x with same results and changing vmware network settings to try to find the error.
Downloaded clean copies of the vmdk / iso / ova to test and same results except for live cd mode "demo mode"

Livecd  / demo mode does not do the updates, could a online update break the systems ?

**Comment by qq7** [comment]
Hi @Rimplestilhskin, thank you for reporting the issue! It is already known, and there is a workaround. Please refer to https://github.com/turnkeylinux/tracker/issues/1246 for a fix.
