### ISSUE TITLE
Update OpenVPN profiles to current standards

### ISSUE THREAD

**Issue by AlejandroBOFH** [turnkeylinux/tracker#1264]
OpenVPN appliance (turnkey-openvpn-15.0-stretch-amd64) includes a script to generate .ovpn profiles for clients to connect.
That script sits in /usr/local/bin/openvpn-addclient.
It generates a <profilename>.ovpn file which can be sent to the client to connect.
Current versions of OpenVPN client report two warnings with current default configuration:

> OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
...
WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
...
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

The needed changes to the openvpn-addclient script are as follows:

Line 74:
Change:
`ns-cert-type server`
to
`remote-cert-tls server`

Line 75:
Add:
`auth-nocache`

**Comment by qrntz** [comment]
Note that `auth-nocache` makes OpenVPN forget the password as soon as it is used to successfully connect to the remote which means that on a subsequent reconnection which could be due to network connectivity issues the credentials are unknown to the OpenVPN client and it will ask for them on stdin. This could break someone's current assumptions.

**Comment by JedMeister** [comment]
@qrntz - good point mate.

I was going to rebuild with this included, but I'm going to refactor the script to it isn't included by default, but can be added via a switch.

**Comment by JedMeister** [comment]
Finalised by https://github.com/turnkeylinux-apps/openvpn/commit/7e5474f9afdd79c9ae248c9b0fa1fab314a5b514

I'm going to close this now, but please feel free to share any further thoughts.

**Comment by AlejandroBOFH** [comment]
I just want to point out that my proposed changes have already been merged to master:
https://github.com/turnkeylinux-apps/openvpn/pull/24
