### ISSUE TITLE
[website] links to docker builds are broken

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1265]
I just realised that the v15.x Docker build links (on each appliance page) are broken.

This is because we changed the naming convention for v15.x. Previous releases were named `APP_NAME-VERSION` and had no tag other than 'latest'. As of v15.0 they are now simply `APP_NAME` and tagged with the version (as well as the latest version being tagged 'latest').

**Comment by jeff-dagenais** [comment]
ping! ;)

**Comment by JedMeister** [comment]
Ok, finally had a closer look at this and it's now fixed (finally ...). Pity I didn't get to it sooner, but better late than never I guess... :smile:
