### ISSUE TITLE
Add Drupal Console to drupal8 build.

### ISSUE THREAD

**Issue by bormanst** [turnkeylinux/tracker#1268]
Drupal Console is replacing most of Drush's functionality (but not all.) It executes much faster than Drush and works quite well with the drupal-composer/drupal-project:8.x-dev route that you've selected.  The console is already included in the project but the drupal.phar needs to be downloaded and configured to use the console anywhere. Also of note, is that Drush is now [included](https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json) in drupal-project:8.x-dev so no need to get it separately; just need to create some symlinks and configs.

I've got the goods already working in my [build script](https://github.com/bormanst/formavid/blob/master/applications/drupal8/drupal8) if that helps any. Please be aware that some of the composer commands are being executed on [overlayed composer.json/lock](https://github.com/bormanst/formavid/tree/master/applications/drupal8/overlay/var/www/drupal8) files. The actual drupal sites are created in another script so...

FWIW

**Comment by JedMeister** [comment]
Thanks @bormanst :smile:

**Comment by JedMeister** [comment]
This was implemented as part of the [Drupal8 v16.0 release](https://github.com/turnkeylinux-apps/drupal8/pull/20).

FWIW we also plan to release a Drupal9 appliance, although unfortunately Drupal console is not compatible with that yet. See the [Drupal9 "new appliance" issue](https://github.com/turnkeylinux/tracker/issues/1511) for more info.
