### ISSUE TITLE
turnkey-pylib debinfo & ar issues

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1272]
In buster onwards debian packages may have control files with .gz or .xz extensions. Pool relies on debinfo which uses the builtin tarfile library to open control.tar.gz files.

The problem: python2.7's tarfile library does not understand .xz files.

The proposed solution: update everything (at least all the development tools) to python3.

**Comment by OnGle** [comment]
Relates to https://github.com/turnkeylinux/tracker/issues/1271

**Comment by JedMeister** [comment]
This should really be addressed sooner rather than later. However, I don't want it to block v16.0 so repinning to v16.1.

**Comment by JedMeister** [comment]
I'm moving this to 17.0 milestone...
