### ISSUE TITLE
Turnkey NextCloud OpenStack Image doesn't exist

### ISSUE THREAD

**Issue by Otterian** [turnkeylinux/tracker#1292]
https://www.turnkeylinux.org/download?file=turnkey-nextcloud-15.1-stretch-amd64-openstack.qcow2

Returns illegal filename. Is it because this particular image doesn't support OpenStack and isn't built anymore, or does it redirect to the wrong file?

Thanks in advance

**Comment by Otterian** [comment]
The images can be found in the following FTP, which I believe the website redirects to:
http://ftp.acc.umu.se/mirror/turnkeylinux/images/openstack/

Closing this issue

**Comment by JedMeister** [comment]
Glad you found them. FWIW it's a website bug. Please see #1239

I have investigated, and by my rudimentary knowledge of PHP, the adjustments that I have made should make it work. Clearly it still doesn't though... We have a great PHP developer that we contract to do a bit of work with us but he's currently working on other projects.

**Comment by JedMeister** [comment]
I've finally worked this out so the website links now work... :smile:
