### ISSUE TITLE
ProjectPier - Can't change theme & icons missing from default theme

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#13]
Reported on [lp#1065326](https://bugs.launchpad.net/turnkeylinux/+bug/1065326) by @JedMeister on 2012-10-11

#### Description

When browsing to the 'Contacts' page (/index.php?c=dashboard&a=contacts&1349914528) of ProjectPier using the default theme (kampPro2) there are 2 icons which don't display. The server is looking for them at /public/assets/themes/kampPro2/images/icons/excerpt_on.png and /public/assets/themes/kampPro2/images/icons/list_off.png

These files do not seem to exist in /var/www/projectpier/public/assets/themes/kampPro2/images/icons/ (where you would expect them to be).

They appear to exist for the alternative theme (marine ie in /var/www/projectpier/public/assets/themes/marine/images/icons/) but the login option to change themes seems to be ignored. I tried setting it at login but it appears to ignore that setting and logs in with the default theme. If changed within the setting once logged in it applies ok (and the icons are there).

My inclination would be to change the default theme in the TKL appliance.

I would also like to see the ProjectPier appliance allow configuration of user, email and password on firstboot or Hub UI rather than on first usage.

**Comment by JedMeister** [comment]
not sure if this is still relevant but probably should test prior to v14.0 release...

**Comment by JedMeister** [comment]
The new version needs to be checked to see if this is still an issue.

https://github.com/turnkeylinux-apps/projectpier

**Comment by qrntz** [comment]
@JedMeister, it is. I'll work on it.
