### ISSUE TITLE
V 15 TKL Magento does not build in Linode,  may

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1302]
Originally had commented regarding Odoo subject, but this came in relative to a different comment thread so I am removing the Odoo comment and leaving Magento subjects below.  (will place the Odoo comment elsewhere)

**Comment by l-arnold** [comment]
It seems to attach to my last comment..  I see now.

I need to also "join" the Git Orgs properly perhaps.

**Comment by l-arnold** [comment]
On my second round, I saw this in the Console Output as Magento 15 (2.2) was installing:  Note the FAILED line and the "Reached the Target Network is Online" being close together.

> [  OK  ] Reached target Local File Systems.
         Starting Raise network interfaces...
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Reached target System Time Synchronized.
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[FAILED] Failed to start Raise network interfaces.
See 'systemctl status networking.service' for details.
[  OK  ] Reached target Network.
[  OK  ] Reached target Network is Online."

**Comment by l-arnold** [comment]
So the subject of this Thread shows as a comment to another thread I made (though I was making the comment relative to my sitting simply on top of the Tracker repository). and I somehow made this into its own thread.  I need to find the original comment to bring context here...  sorry for the embroider work.

**Comment by l-arnold** [comment]
Original Comment which started this Issue without intending to:
versus TKLDEV Magento Issue Parallel here:

> I am going to jump in here.  
> 
> I started the day yesterday attempting to build Magento 15 (2.2) from TKL XEN build on Linode (Linode.com).  Strangely, the Networking interface did not pass through.  I tried a few times.
> 
> I decided I needed to backtrack my steps and went and built, quite meticulously, TKL 14 builds of Magento, Joomla and Odoo.  All went well with V14 TKL in the end (w/ XEN).
> 
> I finished the day again, very carefully building a TKL 15 Magento Linode.  Again, the Networking Interface did not pass through.  (Color also dropped off of ConfConsole as it had in the morning).
> 
> Now I need to try Odoo and Joomla in TKL 15 to see if I can move to Linode.
> I realize that Linode is not AWS, but I do feel that it is well worth our efforts to have a way to install TKL.  I have had tremendously good experience with v 14 on Linode.  I will test Odoo and Joomla (for now) on Linode.  I did come up with a way to build TKL Images on linode...  thogh depending upon the TKL package size they can either be built wholy or just in compressed form.
> 
> I did find in the repositories, there seem to be more flavors of builds available than I recall (VirtualBox etc).  I brushed on the possibility of VMDK working but as yet I have not found how to plant it properly into Linode.  I will look at the other options, I hope today.

I was able to get through Magento FirstBoot Init Hooks (15) except that I could not leave as Networking did not ever hook  (even though I was working in SSH on Linode).

all for now.

**Comment by JedMeister** [comment]
I responded to your thread on the [forums](https://www.turnkeylinux.org/comment/31671#comment-31671). Hopefully that may provide some ideas?

Also re:
> [FAILED] Failed to start Raise network interfaces.
See 'systemctl status networking.service' for details.

IIRC that is "normal" on TurnKey. It's the systemd networking service failing, but networking should still work ok. I'll try to check on a working system ASAP to 100% confirm that for you.

Regardless, you could try running the command noted (i.e. `systemctl status networking.service`) to see why the service failed. Despite my above comments, perhaps this is an issue?

**Comment by l-arnold** [comment]
Add the same experience with Django.
I cannot get Django TKL 15 XEN to build in Linode.  I can get Django TKL 14.1 XEN to build in Linode.

The issue is that Inithooks are not taking Linodes Network situation in TKL 15 while TKL 14 is.

**Comment by l-arnold** [comment]
I can't seem to run anything in FirstBoot Inithooks myself.  Perhaps I could access a backdoor SSH session to do so.

One thing of note:  Firstboot Inithooks resets the Root Password in its process.  I normally have to go in and reset the Root Password in Linode backend in order to complete the install.  I know that is wierd, but I can't get passed Linode's Root Login requirement otherwise in LISH.  (perhaps also GLISH).

**Comment by l-arnold** [comment]
Should, perhaps, be a separate subject as this is DJANGO parallel test (TKL 14.1)

So into the Shell and Webmin on Django 14.1 from XEN.  Not finding my way actually into Django there though for some reason.  I have not used the app before so perhaps I am missing something.  Getting "Bad Request" when I go to the default web page in either http or https.

Apache is aiming for  DocumentRoot /var/www/turnkey_project/static but this time anyway, I am not finding even a WWW folder.

Guessing that I did not have a big enough container defined when I unzipped the XEN build.  All I can think just now

**Comment by JedMeister** [comment]
As I posted in the [forums](https://www.turnkeylinux.org/comment/31689#comment-31689) I suspect that your experience will be common to all v15.x appliances until you can work out what the issue is.

As I noted there if you have some way of getting terminal access (never used Linode, so not sure if that is an option) then hopefully you can troubleshoot the issue. If not, then the only way to do it, would be to configure some/all of the commands I noted to automatically run (e.g. create your own inithook script to run them).

SSH not working is completely expected behaviour if you don't have any networking working on your server. Until your server can accept incoming network connections SSH won't work (it connects via port 22 via the public IP address).

Re the inithooks auto-running (and setting a random root password) that is expected behaviour too. All of our headless builds do that unless you preseed the inithook values as per https://www.turnkeylinux.org/docs/inithooks

**Comment by l-arnold** [comment]
So:  TKL Xen 14.2  fully builds in Linode
confirmed with Joomla,  Django, LAPP.
I assume the others.  (Usually needs to reset the root password via reboot before firstboot inithooks finishes)

TKL Xex 15.x does not build for now in Linode.

**Comment by l-arnold** [comment]
Per your not Jeremy, SSH does work, just TKL does not find any networking in 15.  I am working on solutions.  I need to do so as pretty much all of the TKL 14.1 systems have Python 2.7 and other expiring subsystems.  
Excited to get to the root of this.  Diving back into TKLDEV now.

**Comment by l-arnold** [comment]
Coming back around to this.  It does seem that the changes to the XEN builds for version 15x are causing this error.  I tried to enable eth0 and eth1 in /etc/network/interfaces but it seems the whole of Networking is also not coming up  (I also do not see those interfaces in confconsole even when placed...

> > 
> 
> root@magento ~# systemctl status networking.service
> * networking.service - Raise network interfaces
>    Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor prese
>    Active: failed (Result: exit-code) since Tue 2019-06-11 20:09:12 UTC; 4min 57
>      Docs: man:interfaces(5)
>   Process: 742 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1
>   Process: 737 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [
>  Main PID: 742 (code=exited, status=1/FAILURE)
> 
> Jun 11 20:09:11 magento systemd[1]: Starting Raise network interfaces...
> Jun 11 20:09:12 magento ifup[742]: udhcpc: SIOCGIFINDEX: No such device
> Jun 11 20:09:12 magento ifup[742]: ifup: failed to bring up eth1
> Jun 11 20:09:12 magento ifup[742]: udhcpc: SIOCGIFINDEX: No such device
> Jun 11 20:09:12 magento ifup[742]: ifup: failed to bring up eth0
> Jun 11 20:09:12 magento systemd[1]: networking.service: Main process exited, cod
> Jun 11 20:09:12 magento systemd[1]: Failed to start Raise network interfaces.
> Jun 11 20:09:12 magento systemd[1]: networking.service: Unit entered failed stat
> Jun 11 20:09:12 magento systemd[1]: networking.service: Failed with result 'exit
> lines 1-17/17 (END)

> 

Version 14.2 XEN does install.
I am going to work on a BT Fork for Linode.  The main reason I have been using XEN is that it is easy to load onto a Linode Drive and boot from it.   (yes some more changes to do but boots and runs).
It is extremely easy (and fast) to do it with OpenNode but that appears on hold for now.

**Comment by l-arnold** [comment]
I have installed (and likely noted) v.15 to Linode from ISO now and converted to Linode scalable ext4 drive.  First build will be to a RAW file which needs to be converted w/ dd command.

**Comment by l-arnold** [comment]
Lets Close this one.
