### ISSUE TITLE
Odoo 11 / TKL 15.0 Build

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1311]
Just got an Odoo 11 (TKL 15.0) App from ISO installed.
The "as should work" system on Database creation and/or reflection of Databases is not working.

Normally one needs to Generate a Database from
https://hostname//web/database/manager

When I first got there, however, there was a preinstalled Database "Odoo" there.  I chose to create a new database with a new name.  After some time the database manager came back, again showing "odoo" as the database name.  I could log in (using the non-obvious "admin" email address and the supposed "database manager" password.

Log out again, return to:
https://hostname//web/database/manager
again, only Odoo.
I went to install a new database again, using the same name I did before, and I got 
Error:  Database (newname) has already been installed.

First of all, the new database should show if it has been created.  Second of all, it is quite dangerous, in my opinion, to install a Odoo Database using that name (using a different name is a good way to keep security).

This is also a very different series of interactions than what was happening in V 14 Odoo.

Hopefully at least, the new database will be on a dropdown list.  Perhaps the Odoo Config paramaters is programmed to only look for database Odoo.  If that is the case though, it would be best to NOT have the Database Manager module be there at all, and it is there right in the login screen.

I will reboot now to see if the new database shows up but I doubt that it will.
starting to work through some of these subjects.

**Comment by l-arnold** [comment]
Well,  reboot and same.  
Database Manger gave me the opportunity to "delete" the Database (Odoo). I did so and got an immediate Internal Server Error.
The system should be able to run with no Database installed.  

https://hostname(my ip address)/
https://hostname(my ip address)/web/database/
https://hostname(my ip address)/web/database/selector  

Pretty much need to reinstall it appears.

**Comment by JedMeister** [comment]
@l-arnold - please see #1289
