### ISSUE TITLE
Appliance Mayan EDMS - OCR errors with simple text file on tklapp.com

### ISSUE THREAD

**Issue by zoranpolic** [turnkeylinux/tracker#1313]
Problem
When a simple text file is uploaded to Mayan EDMS at tklapp.com, it can not be previewed as OCR error occurs.  This is not happening on local Virtual Box created with virtual disk image with Mayan EDMS installed on it.

Error Message
[Errno 13] Permission denied: u'/opt/mayan-edms/media/document_cache/document-version-40b831ce-698a-4cc3-ad32-0828dabac35f-7'
as shown at System/Tools/OCR errors

**Comment by JedMeister** [comment]
Hi Zoran,

Thanks for reporting this issue. On face value that appears to be a permissions issue. I'm not sure, but I suspect that it may have been inadvertently introduced by something you have done along the way. (Although perhaps not...)

The Mayan-EDMS system runs under the user account `mayan` and my guess is that that particular directory (and/or perhaps higher up the directory tree?) is owned by someone/something else (possibly `root` if you've made changes from the commandline without doing them as the `mayan` user or ensuring `mayan` user ownership afterwards).

To check, could you please give me the output of:

```
ls -la /opt/mayan-edms/media/document_cache/
```

Regardless, you should be able to resolve that like this:

```
chown -R mayan:mayan /opt/mayan-edms
```

Alternatively, I may be on the wrong track and perhaps the OCR stuff runs under an alternate account? TBH, I don't recall much about Mayan-EDMS OCR. Is that built-in or is it something you added/configured yourself?

**Comment by zoranpolic** [comment]
ls -la /opt/mayan-edms/media/document_cache/
Yes, I did make some changes as root so that might be it.
Executing chown -R mayan:mayan /opt/mayan-edms did fix it.
Mayan-EDMS OCR is built in.

**Comment by JedMeister** [comment]
Great news! :smile: 

FWIW if you wish to do stuff as the `mayan` user, it's worth noting that you can do that using `su`. I.e. something like this:

```
su - mayan -c "YOUR COMMAND GOES HERE"
```

If you use Mayan's commandline tool, then there is also a convenience file `/etc/mayan/env` for setting the appropriate environment vars. Please note that if you make changes to Mayan's env, then those changes **won't** automatically be included, so you may also wish to update the env file.

Usage of the env file is noted on the [Mayan appliance page](https://www.turnkeylinux.org/mayan-edms). To quote from it:

```
ENV=/etc/mayan/env
BIN=/opt/mayan-edms/bin
su - mayan -c ". $ENV && $BIN/mayan-edms.py help"
```

Having said all that, perhaps we should consider including `sudo` in the Mayan appliance in future? It's not a huge application and may make usage of Mayan (at least from the commandline) a little easier? I'd be interested in your thoughts.
