### ISSUE TITLE
WordPress - cron job broken

### ISSUE THREAD

**Issue by uok** [turnkeylinux/tracker#1322]
Thanks for this great TurnkeyLinux!

I noticed that the cronjob for WordPress is broken (file `wordpress-cron` in `/etc/cron.d`), because it is missing user context, e.g. `www-data` (see https://github.com/turnkeylinux-apps/espocrm/pull/9 for comparison)

Also I would recommend `*/5` for faster background processing

**Comment by JedMeister** [comment]
Thanks for the report. We'll fix it and re-release ASAP.

**Comment by OnGle** [comment]
@uok, I've seperated this issue and the interval to ask for more information, if you can share your rational it would be very appreciated, please see this feature request https://github.com/turnkeylinux/tracker/issues/1323
