### ISSUE TITLE
Decrease Wordpress Cronjob Interval

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1323]
This feature request is to discuss decreasing the wordpress cronjob interval suggested by @uok.

Currently this interval is set at 15 minutes, uok suggested 5 minutes for fast background processing, which seems reasonable however looking around I can't find any upstream recommendations regarding ideal intervals so for the time being I'm opening this issue.

**Comment by uok** [comment]
Thanks! I have also not been able to find any good tips on the time interval - e.g. WooCommerce relies on regular scheduled actions during database updates, so if there are 10 tasks queued they will take 10 x 15 minutes, not because of the sql command itself but because of the cron interval

**Comment by JedMeister** [comment]
Let's implement the 5 minute interval for the next v16.1 release of the WordPress appliance.
