### ISSUE TITLE
Remove unrequired "python3-pyfits" package in Ansible app

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1325]
As noted in #1324 there is a bug in the Debian Stretch Python3 library which causes issues in Ansible when run under Python3. The workaround I discovered is to include the `python3-pyfits` package (as it contains a fixed/working `weakref.py` file).

Hopefully Debian will fix [bug #918716](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918716) sometime soon and we can remove the (technically) unrequired python module.

This bug is to track the fact that progress, so it doesn't get forgotten.

**Comment by JedMeister** [comment]
Note that the 15.2 tag is nominal. If it's not fixed when we release 15.2, we'll need to bump this bug to 15.3, etc...

**Comment by Dude4Linux** [comment]
@JedMeister - Hi Jeremy, I see that you just released the 16.0-buster version of TKLDev.  I decided to fire up a copy and fetch the latest version of Ansible.  Guess what was the first bug I hit :).  I assume that I should remove the python3-pyfits from the plan.  I see that a reasonably recent version of Ansible is now available in Debian Buster, so I propose to remove the PiP installation and just use the Debian upstream packages.  Let me know if you don't agree.

**Comment by JedMeister** [comment]
Hi @Dude4Linux - Fantastic to hear from you mate! :smile: 

From what I understand, the issue was resolved in newer versions of Python (than what is provided by Stretch). Buster has a significantly newer version (3.7) so I reckon we're good to remove it now.

As for the Ansible appliance more broadly:
- I have no real issue installing from the Debian package instead and I'm not a Ansbile user, I can't really comment on how useful that may or may not be (seeing as you've done the heavy lifting, I'm happy to be guided by you).
- Having said that, I note that the version in Buster is [2.7.7](https://packages.debian.org/buster/ansible) and latest upstream is currently [2.9.9](https://pypi.org/project/ansible/) so it's already 2 major versions behind. As I note above, I have no issue in installing from Debian, but I'm not sure about switching to Debian repo install now, then back to a pip install for a future update. Although, I do note that it's in backports (currently has [2.9.6](https://packages.debian.org/buster-backports/ansible)) - so that might be a future upgrade pathway if we need/want a newer Ansbile version?
- Completely tangentially, there have been a few questions/requests for including [AWX](https://github.com/ansible/awx). On face value I'm completely onboard with that as it's an open source Ansible (web based) UI (basically the open source upstream of Ansible Tower). But after doing a bit more research, it seems to be fairly heavy, quite messy to install and whilst they do have "releases" I have read that essentially, it's the development branch of Ansbile Tower, so I'm not really sure if that's a good idea to include? If you have any thoughts, I'd be happy to hear.

Take care and stay safe! :smile:

**Comment by JedMeister** [comment]
The core of this issue (i.e. not the discussion since in my comment above) was resolved for the v16.0 release [here](https://github.com/turnkeylinux-apps/ansible/pull/21/files#diff-f8e817e783e619c69860e1abc2cdcc018cfb1aba541469294e7faf407949ca45) so I'm going to close this.
