### ISSUE TITLE
Wheezy and Jessie Backports have been moved to Debian Archive

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#1327]
As noted in https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html, all Wheezy and Jessie repos except for LTS have been removed from the Debian mirrors and moved to the Debian Archive.
Since then, I've been getting errors when I try to update my 14.2 appliances.
```
Err http://httpredir.debian.org jessie-backports/main amd64 Packages
  404  Not Found
Fetched 44.9 kB in 15s (2909 B/s)
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Changing backports.sources.list
```
 sed -i 's/httpredir/archive/g' /etc/apt/sources.list.d/backports.sources.list 
```
results in a different error message
```
E: Release file for http://archive.debian.org/debian/dists/jessie-backports/InRelease is expired (invalid since 80d 20h 0min 41s). Updates for this repository will not be applied.
```
I found that I also had to disable validity checks
```
echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/100disable-validity-checks
```
I'm not sure if there is a fix for this, but maybe a heads-up on the forums would be appropriate.

**Comment by JedMeister** [comment]
Thanks for reporting this John. I actually have a few Jessie servers still running and hadn't noticed that, so it's definitely worth a blog post!

Seeing as backports have been archived, there will be no further updates, so disabling the backports repo altogether is probably as good a plan as any. You won't be able to install new software from backports, but I'm assuming that on an older server you probably don't want to install anything new anyway?! If you do, then upgrading (either via Debian "in place" upgrade, or via data migration to a newer version) are probably the best path forward anyway.

If you aren't ready to upgrade and simply wish to stop the errors (and are ok with not installing anything further from backports) then you can disable the backports repo pretty easily. I'm sure that you are likely aware, but just in case; plus for the benefit of anyone else you comes across this thread, there are 2 ways to disable backports. Either rename the `backports.sources.list` file to something like `backports.sources.list.disabled` (so long as it doesn't have the `.list` file extension on the end) or prefix a `#` to the start of each line that includes the backports repo (unless another entry has been added somewhere else; by default TurnKey uses a separate list file for backports).

**Comment by JedMeister** [comment]
Thanks again John. I've finally got around to posting a blog post on this:

https://www.turnkeylinux.org/blog/debian-7-wheezy-8-jessie-backports-repos-archived
