### ISSUE TITLE
Odoo master DB password does not work if it includes '\' &/or '/' characters

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1336]
As per subject, a Hub user has reported that logging into Odoo with the master DB and password does not work if the password contains '\\' and/or '/' characters.

I've had a quick look through the [Odoo inithook code](https://github.com/turnkeylinux-apps/odoo/tree/master/overlay/usr/lib/inithooks) and nothing jumped out at me. However, I've not yet investigated any further so am not sure if this is limited to the Hub, or affects all Odoo builds (and/or Oddo when initialised via non-interactivly/pre-seeded iinithooks).

**Comment by JedMeister** [comment]
Workaround is to not use either backslash or foward slash in the password.

**Comment by l-arnold** [comment]
I will work on some 15.1x Odoo commentary if you don't mind.

**Comment by l-arnold** [comment]
I just built Odoo 15.2 and have logged in via Linode
Since version 14.0/14.1 the Database Management system has gotten quite Crossed Over with the User Login system.  They are separate subjects in ODOO.
I will explore this some more, but at the very least ConfConsole needs better explanation of this.
Also - while I am at it,  the Appearnce of CONFCONSOLE for ODOO (tkl 15.2) sucks in comparison to JOOMLA's (15.5).  I got through it but cannot almost see what I am typing in.

**Comment by JedMeister** [comment]
Yes Odoo has changed a lot since the v14.x releases! The same as the previous releases though, we just set the "master admin" password. Although IIRC it comes with an "example" app now too. The "admin" user for that has the same password an the "master admin". That way the user can create a new Odoo database, and/or poke around in the example one using the same password. 

But if you have some specific suggestions on how we can make it better, I'd be happy to hear.

> [...] Appearnce of CONFCONSOLE for ODOO (tkl 15.2) sucks in comparison to JOOMLA's (15.5). [...]

FWIW the file that controls what confconsole displays is [here](https://github.com/turnkeylinux-apps/odoo/blob/master/overlay/etc/confconsole/services.txt) if you want to tweak it.

> [...] I got through it but cannot almost see what I am typing in.

Or do you mean the inithooks? I.e. the firstboot scripts? I'm not really sure what you mean. Perhaps you could share a screenshot to help me understand? FWIW the only difference between Odoo and Joomla should be the [Odoo specific question](https://github.com/turnkeylinux-apps/odoo/blob/master/overlay/usr/lib/inithooks/bin/odoo.py#L47-L49).

**Comment by JedMeister** [comment]
I'm moving this issue to v16.1. Inithooks now supports excluding explicit characters from the password via a [list of blacklisted characters](https://github.com/turnkeylinux/inithooks/blob/master/bin/dialog_wrapper.py#L132-L133). As `\` is the escape character, we'll probably need to blacklist `['\\', '/']`
