### ISSUE TITLE
13.0rc3 (phpnuke): 500 internal error

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#134]
```
PHP Warning: ob_start(): second array member is not a valid method in /var/www/phpnuke/mainfile.php on line 81
PHP Notice: ob_start(): failed to create buffer in /var/www/phpnuke/mainfile.php on line 81
```

Found [this](http://www.ravenphpscripts.com/postp158318.html) in reference. Through trial and error seems commenting out the following resolves the issue:

```
@import_request_variables('GPC', '');
```

**Comment by thewolf9** [comment]
how do i fix that i have the same prob

**Comment by JedMeister** [comment]
Hey @thewolf9 - apologies on slow response. We never did discover a proper solution. During development of our v14.0 release, we ended up hitting some other showstopper issues, so dropped PHPNuke from our [library of appliances](https://www.turnkeylinux.org/all) in that release. So unfortunately, we can't offer any advice or solution. :cry:
