### ISSUE TITLE
Moodle cron job error

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#1344]
in `/etc/cron.hourly/moodle` `su www-data -c "/usr/bin/php /var/www/moodle/admin/cli/cron.php > /dev/null 2>&1"` gives 'This account is currently not available' Adding `-s /bin/sh` to the `su` command seems to fix the issue

**Comment by JedMeister** [comment]
Workaround (for existing users):

```
FILE=etc/cron.hourly/moodle
URL=https://raw.githubusercontent.com/turnkeylinux-apps/moodle/master/overlay/$FILE
wget -O /$FILE $URL
```
