### ISSUE TITLE
PHP update in 15.3 stable

### ISSUE THREAD

**Issue by WWE-Corey** [turnkeylinux/tracker#1348]
turnkey-wordpress-15.3-stetch-amd64

Current version of PHP is 7.0 and I need at least 7.1 for certain plug-ins. How can this be updated?

Current plug-in I am trying to install is Weather Station.

**Comment by JedMeister** [comment]
Best bet is to install from [deb.sury.org](https://deb.sury.org/).

You could just follow the instructions from the [readme](https://packages.sury.org/php/README.txt), but in an effort to make it a bit easier on you, try copy/pasting the below into a terminal of your appliance.

Please note that it's untested, so **I recommend that you test on a development server first**! If you have any issues or questions, please ask before you run this on a production server! Having said that, it should be ok as the basis of the below is all pulled from the TurnKey build code (with some minor modifications). FWIW some apps are already using this method to install newer version of PHP. The bulk of this comes from this particular [build script](https://github.com/turnkeylinux/common/blob/master/conf/turnkey.d/apt).

Note that this includes package pinning for additional (best practice) security and does not add the third party key to your default apt keyring (again best practice security).

As the first line suggests, this will install PHP7.2.

```
PHP_VERSION=7.2

PKGS="apt-transport-https lsb-release ca-certificates"
apt update
DEBIAN_FRONTEND=noninteractive apt install -y $PKGS

FILE=usr/share/keyrings/php-sury.org.gpg
URL=https://github.com/turnkeylinux/common/raw/master/overlays/php-sury

wget $URL/$FILE -O $FILE

SOURCES_LIST=/etc/apt/sources.list.d
PREFS_LIST=/etc/apt/preferences.d

cat > $SOURCES_LIST/php.list <<EOF
# DEB.SURY.ORG repo for php
deb [signed-by=/usr/share/keyrings/php-sury.org.gpg] https://packages.sury.org/php/ stretch main
EOF

cat > $PREFS_LIST/php-sury.pref <<EOF
Package: *
Pin: origin packages.sury.org
Pin-Priority: 10
Package: php${PHP_VERSION}-*
Pin: origin packages.sury.org
Pin-Priority: 550
Package: php-common
Pin: origin packages.sury.org
Pin-Priority: 550
Package: php-pear
Pin: origin packages.sury.org
Pin-Priority: 550
Package: php-imagick
Pin: origin packages.sury.org
Pin-Priority: 550
Package: php-redis
Pin: origin packages.sury.org
Pin-Priority: 550
Package: php-igbinary
Pin: origin packages.sury.org
Pin-Priority: 550
Package: libapache2-mod-php${PHP_VERSION}
Pin: origin packages.sury.org
Pin-Priority: 550
EOF
```
Now you'll need to install the PHP packages (you may wish to have additional ones, but this should be a good start).
```
PKGS="php7.2-mysql libapache2-mod-php7.2 php7.2-gd php7.2-cli php7.2-curl php7.2-xml php7.2-mbstring php7.2-zip php-pear php-imagick"
apt update
DEBIAN_FRONTEND=noninteractive apt install -y $PKGS
```
To make PHP7.2 Apache integration the new default, disable the current default Apache-PHP module and restart Apache:
```
DEFAULT=7.0
NEW=7.2
a2dismod php${DEFAULT}
a2enmod php${NEW}
service apache2 restart
```
Finally, to make PHP 7.2 the default PHP when running `php` from the commandline:
```
VER=7.2
update-alternatives --set php /usr/bin/php${VER}
update-alternatives --set php-config /usr/bin/php-config${VER}
update-alternatives --set phpdbg /usr/bin/phpdbg${VER}
update-alternatives --set phpize /usr/bin/phpize${VER}
```
Note that you may need to make adjustments to the new `php.ini` (IIRC the Apache and CLI configs should be found at the following respective locations: `/etc/php7.2/apache/php.ini` & `/etc/php7.2/cli/php.ini`).

If you get any errors about missing PHP modules, then you can install like this:
```
apt update
apt-install php7.2-<module_name>
service apache2 restart
```

For further info, please see the [deb.sury.org GitHub wiki](https://github.com/oerdnj/deb.sury.org/wiki).

**Comment by WWE-Corey** [comment]
Thank you so much for the detailed instructions. I did not see any instructions when I searched. I am having an issue though with this section:

```
PKGS="php7.2-mysql libapache2-mod-php7.2 php7.2-gd php7.2-cli php7.2-curl php7.2-xml php7.2-mbstring php7.2-zip php-pear php-imagick"
apt update
DEBIAN_FRONTEND=noninteractive apt install -y $PKGS
```
I keep getting an error:

```
Err:8 https://packages.sury.org/php stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
Hit:11 http://security.debian.org stretch/updates InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
27 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.sury.org/php stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Failed to fetch https://packages.sury.org/php/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B188E2B695BD4743
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
I tried a different way of getting the key but I still got the error:
apt-get install apt-transport-https lsb-release ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

Any thoughts?

**Comment by JedMeister** [comment]
Hmm, it should be picking up the key from `/usr/share/keyrings/php-sury.org.gpg`. Perhaps double check these:
```
ls /usr/share/keyrings/php-sury.org.gpg
```
(Should just return the filename - if it errors then the key is in the wrong place).
And double check that `/etc/apt/sources.list.d/php.list` looks like this (i.e. run `cat /etc/apt/sources.list.d/php.list`):
```
# DEB.SURY.ORG repo for php
deb [signed-by=/usr/share/keyrings/php-sury.org.gpg] https://packages.sury.org/php/ stretch main
```

Alternatively, if you aren't super concerned about following "best practice" re 3rd party repos (Onjre  is a trustworthy guy IMO - so in this instance the risk probably isn't huge) you could remove the bit in square brackets from the php.list sources file. I.e. so it looks like this:
```
# DEB.SURY.ORG repo for php
deb https://packages.sury.org/php/ stretch main
```

**Comment by WWE-Corey** [comment]
Ok, I think I go through the hard part:

```
# php --version
PHP 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf (cli) (built: Aug  7 2019 19:49:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.21-1+0~20190807.25+debian9~1.gbp935ebf, Copyright (c) 1999-2018, by Zend Technologies
```
I did not see anything to edit in the /etc/php/7.2/apache2/php.ini & /etc/php/7.2/cli/php.ini files and I am guessing I should have because WordPress is still reporting php7.0?

![image](https://user-images.githubusercontent.com/24246957/62842613-dd83a380-bc78-11e9-93be-b40c05be8a70.png)

**Comment by WWE-Corey** [comment]
Disregard.. must be a glitch or something?? 

I can see it in two other places.

1 in wordpress under an optimization plug-in:
![image](https://user-images.githubusercontent.com/24246957/62843258-22f69f80-bc7e-11e9-9a4e-a2569278ec42.png)

2 in the Webmin panel (/apache/?xnavigation=1):
![image](https://user-images.githubusercontent.com/24246957/62843276-50dbe400-bc7e-11e9-9f40-7ed2771d67a7.png)

**Comment by JedMeister** [comment]
Ok great. Looks like you are all good now.

Re the lack of links for configuring PHP7.2 ini files in Webmin, I'm pretty sure if you click the little cog, you can configure it to point to the PHP7.2 version (you'll need to add the full path the the 7.2 ini files).

I'll close this now. If you need more support, best to sign up to the [website](https://www.turnkeylinux.org/user/register) and post in the [forums](https://www.turnkeylinux.org/forum). (You need to be logged in to open a new thread).
