### ISSUE TITLE
Redmine 15.2 SVN Repository

### ISSUE THREAD

**Issue by speedy32129** [turnkeylinux/tracker#1351]
There still seems to be a problem with the cron job creating the repositories (svn or git) automatically.

**Comment by speedy32129** [comment]
First issue is path not found for $WEBROOT.  I've change that and hard code the paths in.  Now it executes but the results are "No output generated".  No repo created.

**Comment by JedMeister** [comment]
Hi there,

I assume you are referring to [this cron job](https://github.com/turnkeylinux-apps/redmine/blob/master/overlay/etc/cron.d/redmine)?

It's weird that the cron script would be having issues with `$WEBROOT` as it's explicitly set at the top of the cron script.

Also, it looks look like it should be logging to `/var/log/reposman.log`, so perhaps you could share what's in there?

**Comment by speedy32129** [comment]
Yes that the correct cron job and it matches.  Left it as is.  I cloned it and been tring to fix/play with the clone to resolve the issue.  reposman.log is empty.

**Comment by JedMeister** [comment]
@speedy32129 - Ok thanks for the heads up. That all sounds a bit broken...

I wonder if it's an issue with something missing from the environment when run as a cron job? FWIW we have a [doc/wiki page on testing cron jobs](https://github.com/turnkeylinux/tracker/wiki/How-to-test-a-cron-job). 

Ideally, I'd jump on this myself ASAP, but I'm currently pretty snowed under with v16.0 dev (really hope to have at least a Core RC iso available really soon...). I'll delegate it to another developer, but I'm not sure when we'll be able to get to it. If you discover anything further in the meantime, please share.

**Comment by speedy32129** [comment]
Any update?  I'm now on Amazon thru the Turnkeyhub and the issue is still there?  I haven't been able to figure it out.

**Comment by JedMeister** [comment]
Hi @speedy32129 - I'll have to have a look for you. It certainly should "just work". Unfortunately it's usually the squeaky wheels that get the oiling... I'll try to have a look at this ASAP. Probably the best place to discuss this would be on our [forums]() or now you're on the Hub, you can hit us up via support (blue icon in the bottom right, or "support link in the top bar).

**Comment by JedMeister** [comment]
Ok, I've had a quick look and on face value it looks like it should "just work". But when I created a new git repo called `test` in `/srv/repos/git` it doesn't seem to see it (so doesn't do anything). So I suspect that there is something I'm missing on how the tool is meant to work and it's requirements... I'm also not super familiar with Redmine either so perhaps my workflow is completely wrong?

So I'll do a little research and find out a bit more about `reposman.rb`. In the meantime, you could see what it's actually doing (perhaps you're hitting the same thing I am?). Run this from the commandline:
```
ruby /var/www/redmine/extra/svn/reposman.rb --redmine localhost --svn-dir /srv/repos/svn --owner www-data --url file:///srv/repos/svn --key-file /var/www/redmine/api_key --verbose --test
```

**Comment by JedMeister** [comment]
Hang on, I misunderstood how it's meant to work. After I created a new Redmine project (`test-001`), it worked for me...

```
root@redmine ~# ruby /var/www/redmine/extra/svn/reposman.rb --redmine localhost --svn-dir /srv/repos/svn --owner www-data --url file:///srv/repos/svn --key-file /var/www/redmine/api_key --verbose --test
running in test mode
querying Redmine for active projects with repository module enabled...
retrieved 3 projects
processing project git-helloworld (git-helloworld)
	repository for project git-helloworld already exists in Redmine
processing project svn-helloworld (svn-helloworld)
	repository for project svn-helloworld already exists in Redmine
processing project test-001 (test-001)
	repository /srv/repos/svn/test-001 created
	repository /srv/repos/svn/test-001 registered in Redmine with url file:///srv/repos/svn/test-001
```

To actually create the new SVN repo, you need to omit the `--test` switch, but I'm only testing so I updated the cron job to also use the `--verbose` and `--test` switches; plus changed the time to 1 minute (it's 10 minutes by default). And here's what happened:

```
.root@redmine ~# cat /etc/cron.d/redmine 
WEBROOT=/var/www/redmine

* * * * * root /usr/local/rbenv/shims/ruby $WEBROOT/extra/svn/reposman.rb --redmine localhost --svn-dir /srv/repos/svn --owner www-data --url file:///srv/repos/svn --key-file $WEBROOT/api_key --verbose 2>&1 >> /var/log/reposman.log
```
I waited until it ran, then checked the log file:
```
root@redmine ~# cat /var/log/reposman.log 
running in test mode
querying Redmine for active projects with repository module enabled...
retrieved 3 projects
processing project git-helloworld (git-helloworld)
	repository for project git-helloworld already exists in Redmine
processing project svn-helloworld (svn-helloworld)
	repository for project svn-helloworld already exists in Redmine
processing project test-001 (test-001)
	repository /srv/repos/svn/test-001 created
	repository /srv/repos/svn/test-001 registered in Redmine with url file:///srv/repos/svn/test-001
```
So it appears to be working as it should...?! Next up, I removed the `--test` switch. And waited until it ran again. here's the relevant log entry:
```
querying Redmine for active projects with repository module enabled...
retrieved 3 projects
processing project git-helloworld (git-helloworld)
	repository for project git-helloworld already exists in Redmine
processing project svn-helloworld (svn-helloworld)
	repository for project svn-helloworld already exists in Redmine
processing project test-001 (test-001)
	repository /srv/repos/svn/test-001 created
	repository /srv/repos/svn/test-001 registered in Redmine with url file:///srv/repos/svn/test-001
```
The subsequent entries all looks like this:
```
querying Redmine for active projects with repository module enabled...
retrieved 3 projects
processing project git-helloworld (git-helloworld)
	repository for project git-helloworld already exists in Redmine
processing project svn-helloworld (svn-helloworld)
	repository for project svn-helloworld already exists in Redmine
processing project test-001 (test-001)
```
And if I look in `/srv/repos/new-test01/`, then there appears to be an SVN repo there:
```
root@redmine ~# ls -la /srv/repos/new-test01/
total 32
drwxrwxr-x 6 www-data root 4096 Nov 23 01:43 .
drwxr-xr-x 6 vcs      vcs  4096 Nov 23 01:43 ..
-rwxrwxr-x 1 www-data root  246 Nov 23 01:43 README.txt
drwxrwxr-x 2 www-data root 4096 Nov 23 01:43 conf
drwxrwxr-x 6 www-data root 4096 Nov 23 01:43 db
-rwxrwxr-x 1 www-data root    2 Nov 23 01:43 format
drwxrwxr-x 2 www-data root 4096 Nov 23 01:43 hooks
drwxrwxr-x 2 www-data root 4096 Nov 23 01:43 locks
```

**Comment by speedy32129** [comment]
So this is all my bad.  

Not sure when Redmine changed it to automatically creating the repositories.  Not how I'd like it. So now I'll only enable the repository when it's actually needed.  I've tested for that and yes it does only create the repository if the repository module is enabled. But when the job does run the cron job is creating the repositories.  

Thanks for looking into this and sorry for wasting and taking up your time!

**Comment by JedMeister** [comment]
All good mate. Glad that we got to the bottom of it.
