### ISSUE TITLE
Add qemu-guest-agent to TKL

### ISSUE THREAD

**Issue by renne** [turnkeylinux/tracker#1356]
[Linux KVM](https://www.linux-kvm.org/page/Main_Page) uses [QEMU](https://www.qemu.org/) to virtualize hardware. [Qemu-guest-agent](https://wiki.qemu.org/Features/GuestAgent) for [Linux KVM](https://www.linux-kvm.org/page/Main_Page) is like the Guest Addons for  VirtualBox.

On Debian it can be installed with `apt install qemu-guest-agent`. It detects automagically if KVM is used.

Please add it to TKL core by default.

**Comment by JedMeister** [comment]
Hi @renne - Thanks for the request. 

I've tagged it with "iso", but I just wanted to clarify that you were suggesting that we include it with all builds? Or were you just recommending it for our OpenStack builds (which are qcow2 format images)? Or something else?

**Comment by renne** [comment]
@JedMeister 
I suggest to include it in the generic ISOs as e.g. Linux Kernel Virtual Machine does not provide all OpenStack tools.
