### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by Lukas-Batema** [turnkeylinux/tracker#1358]
It says this when typing in link...

**Comment by Lukas-Batema** [comment]
Can you add issue label, bug?

**Comment by Lukas-Batema** [comment]
Also, it affects many users!

**Comment by JedMeister** [comment]
Hi there,

I'm sorry to hear of your troubles, but I'm not at all clear what the issue you are hitting is related to.

Could you please elaborate on where/when this issue occurs? Is it on the website? If so, please share which page and what you did to arrive at that point? Or is it on a TurnKey server you have running somewhere? Or something else entirely?

If it's within a TurnKey server, please let me know which one (e.g. WordPress, LAMP, etc), which version (e.g. v15.2, etc) and where you have it running (AWS EC2 launched from the Hub, local VMware VM, etc).

**Comment by Lukas-Batema** [comment]
It is working now, it was on the noodle website, sorry for any troubles. Thanks for helping though, it must’ve been the school filters though. Again, sorry and have a nice day. 

          -Lukas Batema

**Comment by Lukas-Batema** [comment]
*moodle

          -Lukas Batema

**Comment by JedMeister** [comment]
Ok great. I'll close this then. If you have questions or need guidance, please open a new thread on the forums.
