### ISSUE TITLE
Testing of Drupal7 RC3

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#136]
When I went to SourceForge to get the RC3 release of Drupal7 for testing, I found that the final release was posted, which I assume is the same as RC3.  Although this may be too late, I thought I would point out a few things I observed while kicking the tires.  

1) In phpMyAdmin, there is an empty database, 'test', apparently left behind by the build process.
2) Also in phpMyAdmin, user 'root'@'fab-dev' is granted all permissions.  I think leaving this entry is a security risk.
3) In Webmin, a module update is available "Running Processes 	1.632 	Fixes total and free memory display on OpenVZ systems"

Otherwise, the installation when smoothly and I haven't seen any issues with Drupal 7.  I'm sorry I haven't had the time to be more involved in the development phase.  Will try to do more now that winter is approaching.

**Comment by JedMeister** [comment]
I just pointed this to the v14.0 milestone but a quick read suggests that it's actually all done and can be closed... Is that right @Dude4Linux ?

**Comment by Dude4Linux** [comment]
It's my understanding that the fix for 1) and 2) has been merged upstream.  I don't recall if I removed the local fix and tested upstream or not.  3) was to be resolved by #247 but I haven't seen any actual changes upstream.

**Comment by JedMeister** [comment]
Thanks John (@Dude4Linux). I might close this then... 3) is still outstanding (in issue #247) but it has it's own issue so that should be ok... Please reopen or create a new issue if you disagree.
