### ISSUE TITLE
Include python3 build of web2py

### ISSUE THREAD

**Issue by seefor** [turnkeylinux/tracker#1371]
Wondering if I should upgrade to 15.1

**Comment by JedMeister** [comment]
FWIW, generally we prefer it if the "issue tracker" is limited to bug reports or feature requests. For general questions and support, our [forums](https://www.turnkeylinux.org/forum) is the ideal place. :smile: 

Having said that, seeing as you're here, I don't actually think it does!

So I might repurpose your question into a "feature request to ensure that we do update it to use Python3 in the next release (which will almost certainly be v16.0).

It's also further worth noting, that if you weren't already aware, conversion of your app from python2 to python3 will likely require some manual intervention. I'm not sure on the exact web2py specifics, but I've found the `2to3` (python2 to python3 conversion tool) really handy for porting code. Some additional manual work is sometimes still required, but it does a good job of much of it.

**Comment by seefor** [comment]
Thanks!

**Comment by seefor** [comment]
How can I find out when 16.0 will be release?

**Comment by JedMeister** [comment]
Hi @seefor 

Hopefully we'll at least have a RC of Core ready real soon. Apologies on the hold up. We've been a bit waylaid making improvements to our backend infrastructure. The timing is poor, but it will make things better in the long run...

When we release, we'll post on our [website](https://www.turnkeylinux.org/). If you [register](https://www.turnkeylinux.org/user/register) and don't uncheck the "Security and News Announcements" checkbox (it's ticked by default) then you should get an email notification when we post a release note.

**Comment by seefor** [comment]
Take your time guys, I 100% appreciate everything you do, I just wish I was smart enough to figure out how to modify any of these to help you guys out.  I used about 4 or 5 projects from your team!

I will subscribe to get the email notifications

**Comment by JedMeister** [comment]
@seefor - sorry for the delay but we've finally got the v16.0 Web2py appliance released. As per all v16.x appliances, it is based on Debian 10/Buster and it can be used with either python2 or python3 (defaults to python3).

Any problems/questions please feel free to ask on the forums.
