### ISSUE TITLE
Webmin doesn't install on Buster

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1378]
webmin builds but fails to install on buster tkldev.

The following error occured while attempting to build v16 core on v16 tkldev:

```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-l4sy93/000-webmin_1.930-turnkey+20+g2919206_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
  File "/usr/lib/fab/wrapper.py", line 34, in <module>
    CliWrapper.main()
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 388, in main
    commands.run(name, args)
  File "/usr/lib/python2.7/dist-packages/pyproject.py", line 261, in run
    command.module.main()
  File "/usr/lib/fab/pylib/cmd_install.py", line 129, in main
    installer.install(packages, ignore_errors)
  File "/usr/lib/fab/pylib/installer.py", line 251, in install
    self._install(packages, ignore_errors, ['--allow-unauthenticated'])
  File "/usr/lib/fab/pylib/installer.py", line 137, in _install
    self.chroot.system("apt-get", *(args + packages))
  File "/usr/lib/python2.7/dist-packages/chroot.py", line 80, in system
    executil.system(*self._prepare_command(*command))
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
```

package built from turnkey master using pool.

**Comment by JedMeister** [comment]
Hmm, looks like the package install is failing with a non-zero exit code.

I did do a fair bit of work on that in preparation for Buster and I thought that I had tested pretty well. But I guess we're moving into new territory now, so I guess that's bound to happen.

FWIW one of the things I did was added `-e` to all the post/pre install/rm webmin package scripts. So my guess is that something I changed is causing an error under some specific circumstance. The proper fix is to find the specific issue and fix it. The dirty hack workaround would be to remove the `-e`s again...

**Comment by OnGle** [comment]
More information:

copied built package directly into failing core build, chrooted in and attempted to install, here's the log:

```
root@tkldev ~# dpkg -i webmin_1.930-turnkey+20+g2919206_all.deb 
Selecting previously unselected package webmin.
(Reading database ... 28414 files and directories currently installed.)
Preparing to unpack webmin_1.930-turnkey+20+g2919206_all.deb ...
dpkg: error processing archive webmin_1.930-turnkey+20+g2919206_all.deb (--install):
 new webmin package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 webmin_1.930-turnkey+20+g2919206_all.deb
```
issue appears to be very likely in the pre-installation script

**Comment by JedMeister** [comment]
Looking a little closer at this, the only change I made to the pre/post install/remove scripts, was to set `-e` (see [here](https://github.com/turnkeylinux/webmin/commit/d42f570f77934c43a4120474303325a71d9226ab#diff-ba7d25b9a47f21f5eacf5a8db78bdcca)).

The dirty way would be to just revert that commit. Although I think it'd be worth a bit of investigation first to see if we can fix it. What do you think?

**Comment by OnGle** [comment]
Agreed, lets dig in a little before we try and silence it.

Out of interest, more information (rebuild with -x)

```
Selecting previously unselected package webmin.
(Reading database ... 28414 files and directories currently installed.)
Preparing to unpack webmin_1.930-turnkey+21+gc63fe67_all.deb ...
+ perl
+ [ install != upgrade ]
+ set 10000
+ perl -e use Socket; socket(FOO, PF_INET, SOCK_STREAM, getprotobyname("tcp")); setsockopt(FOO, SOL_SOCKET, SO_REUSEADDR, pack("l", 1)); bind(FOO, pack_sockaddr_in($ARGV[0], INADDR_ANY)) || exit(1); exit(0); 10000
dpkg: error processing archive webmin_1.930-turnkey+21+gc63fe67_all.deb (--install):
 new webmin package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 webmin_1.930-turnkey+21+gc63fe67_all.deb
```

Now I don't know perl but it looks to me as if it's attempting to bind a socket and explicitly erroring if it can't. Going to do some looking into perl and see if I can confirm this.

**Comment by OnGle** [comment]
Ok Issue was as follows:

1. -e was added to install scripts
2. preinst uses perl to check if webmin port is in use. Decides how to act based on perl exit code
3. perl exit's 1 because webmin is running (on host tkldev)
4. rather than printing appropriate error message the script exits immediately because of "-e"

Fix:

1. Revert addition of "-e"
2. Ensure tkldev webmin is not running when building packages

**Comment by JedMeister** [comment]
Awesome, thanks @OnGle 

After having a look at the scripts a little myself, I think that they still really require some work. 

However, seeing as that isn't really a priority, I've reverted that previous commit, so as per https://github.com/turnkeylinux/webmin/commit/338d41818ba537957ed85abbbea089088feaf5ae I'm closing this issue.
