### ISSUE TITLE
Install ZoneMinder from 3rd party repo for v16.x

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1383]
When following up on a [support request in the forums](https://www.turnkeylinux.org/forum/support/sun-20191117-0125/zoneminder), I discovered that the ZoneMinder package has been removed from the Debian packages. However, there is a [third party package repo](https://zmrepo.zoneminder.com/debian/master/buster/) available which will likely be a good option?! There is an [install tutorial](https://wiki.zoneminder.com/Debian_10_Buster_with_Zoneminder_1.33.x_from_ZM_Repro_Master) on their wiki. Docs for install on Stretch (using the same repo) are included in the [official docs](https://zoneminder.readthedocs.io/en/latest/installationguide/debian.html#easy-way-debian-stretch) so it appears to be encouraged by the devs although I don't know how much vetting they do?!

As per usual with 3rd party repos, the package will need pinning and we should also store the key in `/usr/share/keyring` (or whatever it is - sorry I didn't double check...).

**Comment by MPTMG** [comment]
I'll take this on if someone isn't already on it. I can commit to a timeline of before January 14th if there are no objections.

**Comment by JedMeister** [comment]
Hey @MPTMG - Lovely to hear from you again! :smile: I hope you are well.

Please feel free to take this one on! :smile: 

However, there are a few notes. Apologies if I'm telling you stuff you already know...

Firstly, we'll need to secure the third party repo (as hinted in my post). We use a combo of package pinning and separate gpg keys. There are a few examples I can point to, but Jenkins is one (see [here](https://github.com/turnkeylinux-apps/jenkins/blob/master/conf.d/10install) - it could instead be done as an overlay; but conf script is ok too).

Secondly, unfortunately, things are a little choked up with the v16.0 release and we currently don't have all our software published in our repo for v16.x. So there will be a little holdup on that. Hopefully it'll be up soon, but I can't give an ETA. If we don't have it done by early next week, I may look at some alternate path to unblock things...

So there is no pressure to meet your stated/suggested timeline.

please note that the next release of the TUrnKey appliance will be v16.0 (so based on Debian 10/Buster) and unfortunately, the pieces aren't yet in place for end users to build v16.0 appliances just yet.

**Comment by MPTMG** [comment]
I'm doing well thanks for asking. I was hoping to be more active, but competing priorities always seem to crop up. I will see what else in/on the tracker I have neglected to finish, or that I may be of use on, and complete it this holiday season.  

Thanks for the notes on package pinning and separate gpg keys. I ran into that particular need on a previous appliance and it is just a lesson in refreshing my memory now. Pointing me to the example will make the "refresh" that much faster.

As always thanks to you and the TurnKey team for providing such an awesome platform. Keep up the great work guys. I will stay tuned for the v16 stuff when it happens.

**Comment by OnGle** [comment]
G'day @MPTMG was just going through the appliance list for 16.0 updates and noticed this one. No rush, just pinging too see how you're going with this one, and feel free too let me know if you need a hand with anything :)

(If you want to get hold of me pinging JedMeister is probably the best way as I tend to lose track notifications rather quickly)

**Comment by JedMeister** [comment]
This was closed by https://github.com/turnkeylinux-apps/zoneminder/pull/8
