### ISSUE TITLE
Pool can't install python3-bcrypt on buster

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1388]
When got by pool/chanko python-bcrypt can't find requirement https://packages.debian.org/buster/python-cffi-backend
Under python-bcrypt (https://packages.debian.org/buster/python-bcrypt) you see 2 unmet requirements "python-cffi-backend-api-min" and "python-cffi-backend-api-max" (both I believe should be met by python-cffi-backend) are listed as "package not available". 

---

Edit:
-----

So it appears what's going on here is `python(3)-cffi-backend` can support multiple api versions, and so in addition to `python(3)-cffi-backend` having it's own version, it also provides `python(3)-cffi-backend-api-min` and `python(3)-cffi-backend-api-max` to specify the min & max supported api versions, and packages can depend on it using the same syntax. I'm not entirely sure exactly how this works but I am sure that pool and/or chanko is **NOT** equipped to handle this.

Traditionally we work around this with virtual packages by providing a package which provides the virtual package. However in this case, for some reason or another this is **NOT** handled correctly.

Fix:
----

The official fix would require changes to chanko, probably pool and possibly also the plan resolving part of fab. This will probably not be fixed until they are updated to python3.

Workaround:
-----------------

While this somewhat defeats the purpose of the plan for the time being, this is guaranteed to work.

1. Comment out the offending package within the plan, along with a note including the word "workaround" and url to this issue.
2. Install package via conf.d script

**Comment by JedMeister** [comment]
Thanks for posting this @OnGle - considering that you noted that it installs ok with apt, just not when using pool; it certainly sounds like a pool bug...

Hopefully we can put some decent work around in place before the v16.0 release? Although perhaps it will install ok when doing a "normal" build (i.e. after the packages are published to the repo)?! Regardless we should keep this in mind as a potentially useful test case for when/if we upgrade pool to py3.

**Comment by JedMeister** [comment]
Moved this issue to v16.1 as it's nto currently an issue but will need to be addressed.

**Comment by JedMeister** [comment]
I'm going to close this as the changes that we've introduced in v18.0 work around this issue by allowing use of both Debian repos and a local `pool`.
