### ISSUE TITLE
fail2ban rules too aggressive

### ISSUE THREAD

**Issue by deutrino** [turnkeylinux/tracker#1398]
The default fail2ban rules in 15.x are problematic in some cases, e.g. when users have an ```id_ed25519``` and an ```id_rsa_fallback``` key in their ssh folder but no ssh keys are set up on the TKL appliance for whatever reason, fail2ban kicks in and kills the connection before the user can even attempt to enter a password, because the user's two keys each count as an auth failure!

Then to add insult to injury, fail2ban may block the user's IP for a while, even if that IP is on the same subnet as the TKL box itself - for example, if it's a copy of TKLDev running in VMware with bridged networking - leading to the result that I'm banned from a VM running on my own machine.

I'd suggest raising the number of failed login attempts by one or two, or finding a way not to count failed ssh keys as login attempts, and maybe also relaxing restrictions on devices from the same subnet as the TKL appliance.

**Comment by JedMeister** [comment]
Have you confirmed that it's fail2ban causing you problems? The SSH config in v15.x is a little too strict and allows 2 attempts before severing the connection. We have already tweaked that slightly for v16.x - see #1130 

I'm open to further discussion though...

**Comment by deutrino** [comment]
I'm not sure I got locked out every time, but it did happen. Between your response though and searching the forums, maybe 16.x has eased up enough?

**Comment by JedMeister** [comment]
I'm going to close this following the tweak included in v16.0. If need be we can reopen and discuss further.
