### ISSUE TITLE
TKLDEV failure with Drupal8

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1399]
Was just running a basic install having added more memory.
Thought I had made it through but got this error perhaps towards the end:

> > DrupalProject\composer\ScriptHandler::createRequiredFiles
+ drush en -y ctools field_group google_analytics honeypot pathauto
The following module(s) will be enabled: ctools, field_group, google_analytics,                    honeypot, pathauto, token

 // Do you want to continue?: yes.

 [success] Successfully enabled: ctools, field_group, google_analytics, honeypot                   , pathauto, token
+ drush entity-updates -y

In UpdateDBCommands.php line 109:

  Drupal removed its automatic entity-updates API in 8.7. See https://www.drupal.org/node/3034742.

entity:updates [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|                   --quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-inte                   raction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-us                   er REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--defi                   ne DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command>

/usr/share/fab/product.mk:535: recipe for target 'build/stamps/root.patched' fai                   led
make: *** [build/stamps/root.patched] Error 1

This is running from TKLDEV 15.x on Turnkey Hub.

**Comment by l-arnold** [comment]
Better Focus:
This was the Error that I could see in Shell

> Drupal removed its automatic entity-updates API in 8.7. See https://www.dru
pal.org/node/3034742.

**Comment by JedMeister** [comment]
Hey @l-arnold - Funny you should mention that! I just read your bug report and at the same time, got a note from @OnGle who is working on updating the build code for v16.0.

We haven't done extensive testing (and I haven't even read the associated documentation), but it seems highly likely that simply removing that particular line from the buildcode (i.e. [this line](https://github.com/turnkeylinux-apps/drupal8/blob/master/conf.d/main#L69)) will fix the issue.

**Comment by OnGle** [comment]
Apologies for slow reply here but I believe, based off my reading of the aforementioned upstream drupal post that the fix for end users is to simply remove the line `drush entity-updates -y` and it's module developers' responsibility to handle the fallout from this.

So with that in mind, I'm going to close this with my next PR to drupal, if anybody disagrees feel free to reopen :)

**Comment by JedMeister** [comment]
Closing this issue as it was resolved by the [v16.0 update](https://github.com/turnkeylinux-apps/drupal8/pull/20).
