### ISSUE TITLE
Non-US keyboard causes login problems

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#14]
Reported on [lp#920939](https://bugs.launchpad.net/turnkeylinux/+bug/920939) by @JedMeister on 2012-01-24
#### Description

As reported by hjo1620 and confirmed by Wolfii in this thread (http://www.turnkeylinux.org/forum/support/20110606/where-can-i-find-correct-root-password-webmin-and-shellinabox) when installing TKL with a non-US keyboard the key mapping for some characters is incorrect (no real surprises there).

The end result is that access via Webmin or Webshell is problematic as the keys are interpreted correctly by the web browser (thus the passwords don't work).
##

**Comment by JedMeister** [comment]
Repegged to v14.1 as #38 is now dependent on #369

**Comment by JedMeister** [comment]
This functionality is now provided via a confconsole plugin as of v1.0.0+. This will be released within days...

**Comment by JedMeister** [comment]
As per https://github.com/turnkeylinux/tracker/issues/38#issuecomment-289963394 this functionality will be supported via a confconsole plugin as of v1.0.0+ (to be released any day).
