### ISSUE TITLE
Joomla Console for Joomla3

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1405]
JoomlaTools Console (cli utility for Joomla) appears like it might be a useful tool to include in our Joomla3 appliance. If you'd like to see it included (or not) please share your thoughts on this issue.

Links:

- Website https://www.joomlatools.com/developer/tools/console
- Github https://github.com/joomlatools/joomlatools-console

**Comment by l-arnold** [comment]
Interesting whether part of TKL or not.  What woukd be the advantage, do you think, of building this in to a TKL Joomla base appliance?

Semi related, is it worth building a Joomla4 (Alpha/Beta/RC) appliance.  It appears to be imminent and they are tagging extensions as Joomla capable.

**Comment by JedMeister** [comment]
Hey @l-arnold - Yeah we're considering it, but only if it's worth the effort. The initial install effort doesn't appear to be that high, but we don't really want to include something that won't get used...

Essentially it's a commandline tool for Joomla. Check out the links that Stefan added in the top post here for more info.

**Comment by l-arnold** [comment]
Yes, I saw and read most of the links. (Thank you for posting Stefan) It would seem if we were packaging a Component or Package with Joomla it would make sense.  There are a few things I generally woukd load but I'm not clear about what (other than the footer which may be a Moduke or at least should be) TKL woukd want to package. The TKL Module.  Perhaps a TKL API component, say to kick TKLBAM or set up some user syncronization.  I'm certsinly seeing some things I could do with it.

I am interested in some of their other tools there as well
