### ISSUE TITLE
Allowing T3 (and other new instance sizes) instances on all current TurnKey solutions that allow T2

### ISSUE THREAD

**Issue by G-Thompson-Ops** [turnkeylinux/tracker#1406]
Currently, most if not all TurnKey solutions on the AWS Marketplace allow T2 but not T3 instances.

This needs to be reviewed.

An example is the Ansible image.

**Comment by JedMeister** [comment]
Thanks for the suggestion.

It's a good call.

FWIW I did start looking at this ages ago and IIRC our images should work ok on t3 instances, but I didn't do enough testing and got pulled off onto other things and never circled back.

We're currently squirrelling away on our next major release; v16.0 so I'll try to revisit this once we have v16.0 AMIs built.

**Comment by G-Thompson-Ops** [comment]
Thanks @JedMeister - I feel as though T3 has been around long enough at this point to just 'bump up', so to speak. I'd also suggest reviewing other instance types while your at it to see if there are newer generations that are been excluded (M5 for example).

**Comment by JedMeister** [comment]
Thanks @G-Thompson-Ops - will do.

**Comment by OnGle** [comment]
Moving to 17.0. Rational: 16.0 is over and done with, 16.2 is wrapping up and bullseye is being released very soon.

**Comment by JedMeister** [comment]
TKL apps on the AWS Marketplace support t3 and other newer instance types. The Hub still doesn't support launching them (or other newer instance sizes) but that's being tracked in #1269
