### ISSUE TITLE
https://releases.turnkeylinux.org/pve/ is down

### ISSUE THREAD

**Issue by ftpman** [turnkeylinux/tracker#1408]
I can't update turnkey templates on proxmox because update links is down:

https://releases.turnkeylinux.org/pve/aplinfo.dat
https://releases.turnkeylinux.org/pve/aplinfo.dat.asc
https://releases.turnkeylinux.org/pve/aplinfo.dat.gz

Cloudflare respond with a 521 error.

#987

**Comment by JedMeister** [comment]
Sorry about that. I strongly suspect that it's related to #1407

**Comment by JedMeister** [comment]
Please see https://github.com/turnkeylinux/tracker/issues/1407#issuecomment-579148820

**Comment by JedMeister** [comment]
Closing now. It's backup and we're pretty sure that we've addressed the cause of the issue.
