### ISSUE TITLE
Inithooks should use proper MySQL connectors & Add MySQL common plan

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1414]
Inithooks for 16.0 will get updated to use proper mysql connectors rather than using the current adhoc connector built into mysqlconf.py. For this we'll be using `python3-pymysql` below is a checklist of appliances which've been updated to correctly use the new connector.

In addition we should create a common mysql plan which includes this connector & the mysql server rather than manually including per appliance.

Gotchas
===

Variable substitution are NOT bound variables
---

`m.execute("%s" % some_value)` != `m.execute("%s", (some_value,))`
The former is not safe as it doesn't get escaped

The later offloads escaping to pymysql. Note when using bound variables, always use `%s` no other `%-codes` will work (i.e. `%d`)

Don't quote bound variables in SQL
---
replace
`... SET someKey="%s" ...` 
with
`... SET someKey=%s ...`

You can't make multiple seperate queries in a single string
---
Using `;` to seperate queries in a single call no longer works

Status on updating for new mysql connector
===

(I'll update this issue with details after the first inithook has been updated)
ones with PRs pending will be added, with a link in square brackets after the name

 - [x] asp-net-core (not yet added as appliance) [Nothing needed]
 - [ ] asp-net-apache
 - [x] b2evolution [PR: turnkeylinux-apps/b2evolution/pull/16]
 - [x] bugzilla [PR: turnkeylinux-apps/bugzilla/pull/13]
 - [x] cakephp
 - [x] codeigniter [PR: turnkeylinux-apps/codeigniter/pull/16]
 - [ ] collabora
 - [x] collabtive [PR: turnkeylinux-apps/collabtive/pull/15]
 - [x] concrete5 [PR: turnkeylinux-apps/concrete5/pull/16]
 - [x] django [PR: turnkeylinux-apps/django/pull/16]
 - [ ] drupal7
 - [x] drupal8 [PR: turnkeylinux-apps/drupal8/pull/20]
 - [x] e107 [PR: turnkeylinux-apps/e107/pull/14]
 - [x] elgg [PR: turnkeylinux-apps/elgg/pull/18]
 - [x] espocrm [PR: turnkeylinux-apps/espocrm/pull/15]
 - [ ] etherpad
 - [x] ezplatform
 - [x] gallery [PR: turnkeylinux-apps/gallery/pull/18]
 - [x] ghost [PR: turnkeylinux-apps/ghost/pull/9]
 - [x] gitea [PR: turnkeylinux-apps/gitea/pull/1]
 - [x] gnusocial
 - [ ] icescrum
 - [x] joomla3 [PR: turnkeylinux-apps/joomla3/pull/11]
 - [x] lamp **no inithook**
 - [x] laravel **no inithook**
 - [x] lighttpd-php-fastcgi **no inithook**
 - [x] limesurvey [PR: turnkeylinux-apps/limesurvey/pull/24]
 - [x] magento
 - [ ] mambo
 - [x] mantis [PR: turnkeylinux-apps/mantis/pull/10]
 - [ ] mariadb
 - [x] matomo [PR: turnkeylinux-apps/matomo/pull/18]
 - [x] mediawiki [PR: turnkeylinux-apps/mediawiki/pull/15]
 - [x] mibew [PR: turnkeylinux-apps/mibew/pull/14]
 - [x] moodle [PR: turnkeylinux-apps/moodle/pull/17]
 - [ ] mysql
 - [x] nextcloud **not required**
 - [x] nginx-php-fastcgi
 - [x] observium [PR: turnkeylinux-apps/observium/pull/15]
 - [x] omeka [PR: turnkeylinux-apps/omeka/pull/17]
 - [x] opencart [PR: turnkeylinux-apps/opencart/pull/3]
 - [x] orangehrm [PR: turnkeylinux-apps/orangehrm/pull/15]
 - [x] oscommerce [PR: turnkeylinux-apps/oscommerce/pull/16]
 - [x] otrs
 - [x] owncloud [PR: turnkeylinux-apps/owncloud/pull/21]
 - [x] phpbb [PR: turnkeylinux-apps/phpbb/pull/12]
 - [ ] php-fpm
 - [x] phplist [PR: turnkeylinux-apps/phplist/pull/15]
 - [x] prestashop [PR: turnkeylinux-apps/prestashop/pull/20]
 - [x] processmaker [PR: turnkeylinux-apps/processmaker/pull/13]
 - [ ] punbb
 - [x] roundup [PR: turnkeylinux-apps/roundup/pull/11]
 - [x] silverstripe [PR: turnkeylinux-apps/silverstripe/pull/14]
 - [ ] simpleinvoices [PR: turnkeylinux-apps/simpleinvoices/pull/11]
 - [x] simplemachines [PR: turnkeylinux-apps/simplemachines/pull/15]
 - [ ] sitracker
 - [x] suitecrm [PR: turnkeylinux-apps/suitecrm/pull/10]
 - [x] symfony
 - [x] tomcat (not req'd - inithook doesn't run any SQL)
 - [x] tomcat-apache (not req'd - inithook doesn't run any SQL)
 - [x] typo3 [PR: turnkeylinux-apps/typo3/pull/22]
 - [ ] ushahidi
 - [x] vanilla [PR: turnkeylinux-apps/vanilla/pull/15]
 - [ ] vtiger
 - [x] wordpress
 - [x] xoops [PR: turnkeylinux-apps/xoops/pull/15]
 - [ ] yiiframework
 - [x] youphptube [PR: turnkeylinux-apps/youphptube/pull/5]
 - [x] zencart
 - [x] zoneminder
 - [ ] zurmo

and rails apps I forgot also include mysql

- [x] foodsoft
- [x] rails
- [x] redmine
- [x] tracks

**Comment by JedMeister** [comment]
I'm pretty sure that we've now nailed this one (outstanding apps are either deprecated or irrelevant).
