### ISSUE TITLE
Transition pathway for v15.x users using Debian style "in place" upgrade

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1419]
We are making some quite major changes behind the scenes in v16.x. Mostly they are porting our custom software (from python2) to python3 - which should essentially be transparent to most users. Some of the other changes are moving (back?) to default Debian packages/tools. E.g. from casper to debian-live.

Whilst we'll continue to recommend TKLBAM for migrating data (and I hope to improve it for migrating between major versions in the future), I'd also like to (continue) to support Debian-style "in-place" upgrades (i.e. adjusting sources list entries and running `apt dist-upgrade`).

At this point, the only thing that occurs to me that will want some tweaking is `busybox-initramfs` (it's not in Debian and as of v16.0 we no longer package it ourselves). I suspect adding a transitional package that depends on `busybox` will be all that's required. But it needs testing to confirm my suspicions.

[update] Actually, `di-live` [depends on `live-boot-initramfs-tools`](https://github.com/turnkeylinux/di-live/blob/master/debian/control#L29), which [in turn, depends on  `busybox`](https://packages.debian.org/buster/live-boot-initramfs-tools). So `busybox` should already be installed?! However I'm not completely sure what might happen with both installed?!

[update#2] Actually I just checked a local TKLDev v15.0 that I have running, and that has both installed already?!:

```
busybox:
  Installed: 1:1.22.0-19+b3
  Candidate: 1:1.22.0-19+b3
  Version table:
 *** 1:1.22.0-19+b3 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
busybox-initramfs:
  Installed: 1.22.0-19ubuntu2+turnkey+1+g33eb5c0
  Candidate: 1.22.0-19ubuntu2+turnkey+1+g33eb5c0
  Version table:
 *** 1.22.0-19ubuntu2+turnkey+1+g33eb5c0 999
        999 http://archive.turnkeylinux.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

It may be just how it is?! Or it may be because it was the same host that I've been mucking around with when doing di-live updates? Or it may have some other irrelevant cause? Regardless, my host (re)boots fine, so it seems unlikely that it will cause issues...

**Comment by OnGle** [comment]
@JedMeister status on this?

**Comment by JedMeister** [comment]
Let's just close it?! It doesn't appear to have been as big an issue as I thought it might have been. Some may still hit this (or otehr related issues) but we can cross that bridge if/when we get to it.
