### ISSUE TITLE
redmine openstack image link broken

### ISSUE THREAD

**Issue by felfert** [turnkeylinux/tracker#1426]
If I visit https://www.turnkeylinux.org/redmine and click on OpenStack, the following page at https://www.turnkeylinux.org/download?file=turnkey-redmine-15.2-stretch-amd64-openstack.qcow2 says:

Error: not a legal filename 'turnkey-redmine-15.2-stretch-amd64-openstack.qcow2'

**Comment by JedMeister** [comment]
Unfortunately this is a known issue... :cry: Please see #1239. FWIW the workaround is to download the qcow2 image files directly from the [mirror](http://mirror.turnkeylinux.org/turnkeylinux/images/openstack/).

As I've noted elsewhere, I have had a few stabs at it, but my PHP knowledge is pretty rudimentary and I've been unable to fix it. We need to get an expert on the job...

**Comment by JedMeister** [comment]
I've finally worked this out... :smile:
