### ISSUE TITLE
Consider installing WordPress with wp-cli

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1437]
I'm not completely sure whether this is a good idea or not, but on reviewing the [wp-cli handbook (aka docs)](https://make.wordpress.org/cli/handbook/) I note that they give an example of [downloading and installing WordPress](https://make.wordpress.org/cli/handbook/quick-start/#practical-examples) and I thought that it might be a good way to go?

**Comment by JedMeister** [comment]
It turns out that `wp core install` requires that a URL be set. So we'll leverage it for downloading and generating the config file, but we'll still continue to use our custom install script for the final install phase (`wp core install` requires that a URL be set).

**Comment by aaronsql2019** [comment]
Hey guys, I just ran into this topic and I am TINKERING around with a BUNCH of WP CLI topics right now. 
Can you guys tell me WHERE this needs to be configured? I'm still learning, it's early in the process. THANKS

**Comment by JedMeister** [comment]
@aaronsql2019

wp-cli is preinstalled in our WordPress appliance. It can be called directly as `wp`. We also provide a wrapper script, `turnkey-wp` which runs `wp` commands as `www-data` (so doesn't mess up permissions for web UI updates, etc). The wrapper is fairly basic and not extensively tested, but should work fine for most usage. If you hit any issues with it, please share.
