### ISSUE TITLE
Plugins not shown Etherpad plugin manager

### ISSUE THREAD

**Issue by nilsws** [turnkeylinux/tracker#144]
When accessing the Etherpad plugin manager through the admin interface, no plugins are shown as available, and manually installed plugins do not show up and aren't working. This problem existed for me in Turnkey Linus version 12.1 and 13. Installing plugins like ep_headings causes an Nginx error.

**Comment by JedMeister** [comment]
This should be resolved as of v14.0. Please reopen (or open a new one) if it is still an issue (in v14.x)
