### ISSUE TITLE
Add 'jellyfin' to 'video' user group

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1442]
In a recent [forum post](https://www.turnkeylinux.org/forum/support/sun-20200405-2332/how-run-turnkey-appliances-lxd-converting-proxmox-lxd-containers#comment-48024) Dave aka LinuxGeek28, has noted the steps required to get Hardware Acceleration working with Jellyfin.

Dave further [suggested](https://www.turnkeylinux.org/forum/support/sun-20200405-2332/how-run-turnkey-appliances-lxd-converting-proxmox-lxd-containers#comment-48032) that we at least add the `jellyfin` user to the `video` group and provide some info via the README as well as a link to the relevant Jellyfin doc page:

https://www.turnkeylinux.org/forum/support/sun-20200405-2332/how-run-turnkey-appliances-lxd-converting-proxmox-lxd-containers#comment-48032

**Comment by qq7** [comment]
closed in https://github.com/turnkeylinux-apps/mediaserver/commit/d8e7fd27c020dd166aff9b5e31f98e0aa83ff2a9

**Comment by qq7** [comment]
@JedMeister

**Comment by JedMeister** [comment]
Closed (ages ago) by https://github.com/turnkeylinux-apps/mediaserver/commit/d8e7fd27c020dd166aff9b5e31f98e0aa83ff2a9
