### ISSUE TITLE
Release Files removed from buster and buster-security at archive.turnkeylinux.org

### ISSUE THREAD

**Issue by Hartwin2342** [turnkeylinux/tracker#1443]
E: The repository 'http://archive.turnkeylinux.org/debian buster-security Release' no longer has a Release file.

E: The repository 'http://archive.turnkeylinux.org/debian buster Release' no longer has a Release file.

N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by JedMeister** [comment]
Thanks for reporting this.

I assume that it must have been related to the archive going down about a week ago. I have fixed `buster` but I'll need to get Alon to fix `buster-security`.

**Comment by JedMeister** [comment]
Mean to close this sooner. Should be all good now.

Please post/reopen if you have any further issues (fingers crossed we should be good for now...).
