### ISSUE TITLE
Building bootstrap on TKLDEV v16.0 fail

### ISSUE THREAD

**Issue by heneault** [turnkeylinux/tracker#1450]
It appears debootstrap is not installed by default in tkldev v16 :

root@tkldev /turnkey/buildtasks# ./bt-bootstrap 
INFO [bt-bootstrap]: RELEASE not set, determining from system.
WARNING [bt-bootstrap]: --publish was not specified
Already up to date.
rm -rf build/bootstrap build/bootstrap.tar.gz
mkdir -p build
debootstrap --arch=amd64 --variant=minbase --include=gpg,gpg-agent buster build/bootstrap http://deb.debian.org/debian
make: debootstrap: Command not found
make: *** [Makefile:67: build/bootstrap] Error 127
total 0
FATAL [bt-bootstrap]: Build failed...

**Comment by JedMeister** [comment]
Thanks for the report and apologies on my delayed response...

I'm not 100% sure of the best resolution here. Options that occur to me OTTOMH are:
- just document it
- auto install it when discovered missing; when you run the bootstrap build `make`
- pre-install it in TKLDev

**Comment by heneault** [comment]
I was thinking  the best would be to pre-install it in tkldev. This is the easiest thing for the end-user as it work out of the box and it was like this in the previous version.

**Comment by JedMeister** [comment]
Finally got around to this one...
