### ISSUE TITLE
VMware - Set static IP in Confconsole causes crash & stacktrace

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1457]
As reported by [Brian in the forums](https://www.turnkeylinux.org/forum/support/fri-20200221-0845/wordpress-php-73#comment-48179) when he sets a static IP within Confconfconsole (installed from ISo onto a VMware ESXi/vSphere v6.0 VM), he gets a crash and a stacktrace (rather than a static IP as expected). Here's a screenshot of the stack trace:

![](https://www.turnkeylinux.org/files/u/43044/Temp.jpg)

I have been unable to recreate the issue (tested in a KVM VM, a VirtualBox VM and a VMWare Player v15.5 VM). My investigations of the code were fruitless.

Could you please have a look @OnGle ?

**Comment by OnGle** [comment]
Yep no worries I'll have a geez now

**Comment by OnGle** [comment]
From the stacktrace I see a couple places where an invalid `None` could popup. Possibly caused by getting `net.addr`, `net.netmask` or `net.gateway` in https://github.com/turnkeylinux/confconsole/blob/05a1c6e34e37662e2dc7ff7825e93d26de7e4e92/ifutil.py#L245

Essentially from my looking I believe:

If it's `net.gateway` then it's caused by a `CalledProcessError` occuring when calling `route -n` (https://github.com/turnkeylinux/turnkey-netinfo/blob/69bac1c2f07d9a969cf32560b29f669ab5067c4a/netinfo/__init__.py#L120)
If it's `net.addr` or `net.netmask` then it's caused by an `IOError` occuring from a `fcntl.ioctl(...)` call. (https://github.com/turnkeylinux/turnkey-netinfo/blob/69bac1c2f07d9a969cf32560b29f669ab5067c4a/netinfo/__init__.py#L97)

Eitherway both cases should probably be handled better by the time they get to confconsole.

I'll do some testing and see if I can reproduce the issue.

**Comment by OnGle** [comment]
I was able to reproduce the issue by removing the default routing rules on a regular core iso:

`route del default`

Then opening confconsole and navigating too `Advanced -> Networking -> Static IP`

---

I believe it was `net.gateway` which triggered it but not by returning an error but by providing no routing rule for `0.0.0.0`

---

I'm unsure specifically how we want to deal with this issue, but once we've decided on a solution I'd be happy to implement it.

**Comment by JedMeister** [comment]
Thanks for this awesome write up of your investigations.

So essentially there are 2 things we need to do here:
- make confconsole more robust in managing these possibilities (i.e. give some useful error message rather than crash with a stacktrace); and
- work out why the underlaying issue occurs and how to fix it.

To reiterate what we discussed elsewhere, IMO resolving (or even attempting to resolve) the underlying issue is outside the scope of Confconsole IMO.

So if you want to have a look at improving Confconsole's robustness and provide some more useful error message(s), I'll have a lcoser look at how this situation may have arisen, and what a user might do to resolve it...

**Comment by OnGle** [comment]
Increasing confconsole's "robustness"; pending additional testing

- https://github.com/OnGle/turnkey-netinfo/tree/add-optional-errors
- https://github.com/OnGle/confconsole/tree/add-more-verbose-erroring

**Comment by JedMeister** [comment]
Ok, So I'm not sure if this was the exact same scenario as the OP experienced, but I've managed to reproduce the issue in VMware Player (v15.5) by setting the network adaptor to "host only" (in my tests, both "NAT" and "Bridged" worked as expected).

Note that in my tests, I started with a v16.0 WordPress VM (installed from ISO). Then:
- with "Bridged" networking:
  - got a DHCP IP by default [worked[
  - set a static IP [worked]
  - reset back to DHCP [worked]
- Shut down VM, set networking to "NAT" and restarted
  - got new DHCP address [worked]
  - set static IP [worked]
  - reset back to DHCP [worked]
- Shut down VM, set networking to "Host only" (see fig 1 below) and restarted
  - initially displayed old DHCP network info (from "NAT" config?)
  - selected "Networking" from Confconsole "Advanced" menu - got first error - see fig 2 below
  - clicked 'ok' and got dropped back to selection screen asking 'DHCP' or 'Static' (no networking info shown)
  - selecting 'DHCP' returns to above noted error - see fig 2 below
  - selecting 'Static' returns the OP's stacktrace! - See fig 3 below.
  - note that there is no `route` - see fig 4 below

fig 1 - *VMware network config that causes issue:**
![network_config](https://user-images.githubusercontent.com/818633/82167160-39611400-98fe-11ea-9b94-10391b7b9c7a.png)

fig 2 - **Initial Confconsole networking error with "Host only" networking:**
![confconsole-dhcp-error-msg](https://user-images.githubusercontent.com/818633/82168610-74654680-9902-11ea-9af5-1692298973df.png)

fig 3 - **Trying to set a static IP (same stacktrace as OP):**
![confconsole-static-ip-stacktrace](https://user-images.githubusercontent.com/818633/82168654-9a8ae680-9902-11ea-96bb-527d809ab0bc.png)

fig 4 - **No `route`s listed:**
![route-output](https://user-images.githubusercontent.com/818633/82168668-a5457b80-9902-11ea-87a2-884112ef6288.png)

**Comment by JedMeister** [comment]
Thanks for these updates @OnGle - on face value they work great! :smile: 

However, it looks like there may actually be a deeper issue at play here... I say that because my initial testing of the updated packages found no errors, even when testing "host only" networking. I.e.:

![Screenshot from 2020-05-18 13-01-38](https://user-images.githubusercontent.com/818633/82172007-484ec300-990c-11ea-8c1a-13637273bf94.png)

It seemed weird to me that the changes you made could actually resolve this issue, so I kept retrying to get a DHCP address, and eventually it failed:

![Screenshot from 2020-05-18 13-21-50](https://user-images.githubusercontent.com/818633/82172044-6b797280-990c-11ea-9837-d1e8bf64f04e.png)

So it seems like there may actually be some race condition causing the underlying issue! And whilst I recreated it easily with the "host only" networking, it makes me wonder if that was just coincidental?! The changes that you've made do appear to make the process more robust, but after I managed to recreate the issue, it seems to sometimes be easy to reproduce (I reproduced it continually 3 times in a row at one point).

FWIW, when the issue occurs, it has no IP nor routing info (as you'd expect):

![Screenshot from 2020-05-18 13-23-33](https://user-images.githubusercontent.com/818633/82172188-d7f47180-990c-11ea-8e72-8574ab40e675.png)

If I try to set a static IP after the DHCP has failed, I now get a much more useful error message:

![Screenshot from 2020-05-18 13-41-26](https://user-images.githubusercontent.com/818633/82172411-6a951080-990d-11ea-96d0-e3fd9e79445b.png)

So it seems that the primary issue may actually rest with the underlying Debian network tools. IMO most likely the DHCP client explicitly (`udhpc`).

Initially, I thought it may be related to [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927413) but it's not...

Still it seems likely to me that it is some sort of race condition with the route setup via `udhcpd`...

**Comment by OnGle** [comment]
My testing indicated that using DHCP, changed the routing in a way that makes it not necessarily cause the same effects on the system each run. Before I would consider this tests significant I think we should check the routing after each run, and note exactly what's occured between each run. 

---

Also I believe the issues in DHCP should be treated differently to the ones in Static IP config as they do not occur under the same conditions. DHCP working may fix routing for Static IP config or broken DHCP may break it further, in my opinion this is an entirely different and unrelated issue.

**Comment by JedMeister** [comment]
This issue is closed by:
https://github.com/turnkeylinux/turnkey-netinfo/pull/1 & https://github.com/turnkeylinux/confconsole/pull/45
