### ISSUE TITLE
YouPHPTube has been rebranded upstream, we need to rename

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1460]
YouPHPTube has rebranded as [AVideo](https://platform.avideo.com/) as noted in their [new readme](https://github.com/WWBN/AVideo#about-the-project-re-brand). It's primarily being marketed as a SaaS/Enterprise platform but still maintains an [open source edition](https://platform.avideo.com/AVideo_OpenSource) ([GitHub repo](https://github.com/WWBN/AVideo)).

As such we should follow their lead and rename the appliance, with updated readme, logo, etc. Mentions of `youphptube` within our buildcode should probably be changed to `avideo` too.

- [x] Update buildcode
- [x] Update Readme, logo and screenshots
- [x] Update git repo name
- [x] Update website content (readme, logo & screenshots)
- [x] Update web URL
- [x] Update Hub (name)
- [x] Update AWSMP (name, readme & logo)

**Comment by JedMeister** [comment]
Much of the work for this has been completed (see https://github.com/turnkeylinux-apps/youphptube/pull/5) and the updated v16.0 release of AVideo (formerly YouPHPTube) is in the build queue.

However, we still need to update the logo, screenshots and info on the website, as well as rename the GH repo, the website url and info etc.

**Comment by OnGle** [comment]
https://github.com/turnkeylinux-apps/youphptube/pull/6

**Comment by OnGle** [comment]
ping @JedMeister has this been done yet on AWSMP?

**Comment by JedMeister** [comment]
@OnGle - nope, I still need to do that. I was going to do it via the new API, but I haven't had a look at that yet. So I should probably just do it via the AWSMP portal (it's a bit sucky but not that bad...).

**Comment by OnGle** [comment]
JedMeister handled this yesterday
