### ISSUE TITLE
Odoo appliance - (firstboot?) script to change Odoo version?!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1462]
It would be cool if Odoo appliance users could easily install an alternate version of Odoo.

Rather than providing separate appliances, instead we could provide a script to allow easy Odoo version down/upgrade?!

Ideally it should probably be asked at first boot (part of the Odoo inithook? only asked if running interactively!). But initially it might be best to just provide it as a separate script.

Then we could make it clear it is relatively "experimental" and get some user feedback on how well it works (and ages over time).

Perhaps we can get some community support to develop this script?

----

Full rationale

Currently we only provide a single Odoo appliance. But Odoo upstream generally supports 3 versions concurrently. That means that we need to choose which version we should be providing.

As the development of the open source plugins usually seems to lag a bit, the "middle" version (i.e. not the latest or the oldest) is generally a better bet for most new users and what we have generally tended to do in the past.

However, that is not always going to be suitable for everyone. Some may have existing Odoo installs/data and wish to migrate to TurnKey (and/or a newer TurnKey) so the old version may suit them better.

OTOH new users may wish to check what the latest version is like. So the latest would suit them best.

One resolution would be to provide 3 (or 2) separate Odoo appliances, but that's a fair bit of work for us and possibly quite confusing for users.

IIRC we're installing Odoo from the upstream apt repo though. So at least in theory it should be possible to install an alternate version relatively easily?!

**Comment by JedMeister** [comment]
I just changed my mind and have decided to move this to v16.1. That will allow us to get the v16.0 appliance out sooner!

**Comment by l-arnold** [comment]
Get it done for 16 but backtrack to view 8 and allow to step all the way forward.

It would also be good to use the original Database setup from version 14.0/ Odom 8.  It is not good style to combine the database Master user and the Admin user with a default "Odoo" named database and password.

The changes on that front in V 15 really mad upgrades complicated and feel like to be a security risk to me.  Also the "language" of what is happening I  Appliance setup is not really clear as to what is being setup.

Back to the original subject,  Yea, absolutely have people be able to choose their Odoo version.  Very good idea.

Great applications.  Thank you for the huge efforts.

Landis

**Comment by marcos-mendez** [comment]
I know how gave you this idea

**Comment by JedMeister** [comment]
I'm going to defer this for now.

If anyone wants to push this forward, please feel free to start work on it. IMO it could (perhaps should?) be a 3 step proces:
- document what we'd need to change depending on version - this documentation would hold value to anyone wanting to use a different Odoo version.
- Use the documentation to create a script to make the required changes.
- Create a inithook and/or confconsole plugin (that leverages the script). 

Also, it's also worth considering this in context of Odoo14 being in Debian official repos in v17.x - see #1590.

**Comment by l-arnold** [comment]
Bump on this one.  How far back wouild those Debian repos go?  Git pulls are nearly infinite.

**Comment by marcos-mendez** [comment]
In odoo the problem is not the pulls but the pip packages inside the python
requirements of odoo.

I nearly do this daily. Perhaps if some one would helpme buid the
confconsole and the script i can contribute on this.

Ive been trying with turnkey linux core but im not so senior developer is i
would like.

If there is any contribution i would love to help

Em sex, 29 de out de 2021 19:00, L. Arnold ***@***.***>
escreveu:

**Comment by JedMeister** [comment]
Now we're using the Debian package, I'm not sure if this issue is still relevant? So I'm going to close it.

Although as something of an aside, I note that it looks like Odoo didn't make it into [Debian Bookworm](https://packages.debian.org/search?suite=bookworm&section=all&arch=any&searchon=names&keywords=odoo)... :cry: (Bullseye had [Odoo14](https://packages.debian.org/bullseye/odoo-14) and Trixie/testing has [Odoo16](https://packages.debian.org/trixie/odoo-16)). Hopefully the Odoo-16 package will be backported to Bookworm!?
