### ISSUE TITLE
Confconsole - "usage" should also include option to "shutdown"

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1463]
As suggested in the forums (initially [hinted by Ian](https://www.turnkeylinux.org/blog/v16.0-1#comment-48154), then [explicitly suggested by Carlos](https://www.turnkeylinux.org/blog/v16.0-1#comment-48268)) it would be good to provide a "shutdown" option on the Confconsole "usage" screen.

The way it is now, a user needs to log in to shutdown which seems pretty dumb in retrospect!

**Comment by OnGle** [comment]
This is a non-issue in my opinion. Shutting down is the ultimate DOS, in addition to the fact that adding stuff to the usage screen is a little difficult, in my mind we should tag this as wont-fix. Unless there's a sufficiently convincing argument beyond mild inconvenience.

**Comment by JedMeister** [comment]
Hmm, you do raise a good point @OnGle...

What about we use the full Confconsole and if not alrady logged in, authenticate the user?! I just noticed that in Buster there is a Python3 PAM module - see [`python3-pampy`](https://packages.debian.org/buster/python3-pampy).

**Comment by JedMeister** [comment]
Closing in favour of new issue: #1562
