### ISSUE TITLE
Would be better if dbus-user-session were installed by default

### ISSUE THREAD

**Issue by paulharris** [turnkeylinux/tracker#1467]
I set up borgmatic with systemd for daily backups,
the suggested service file has this line in it:
ExecStart=systemd-inhibit --who="borgmatic" --why="Prevent interrupting scheduled backup" /root/.local/bin/borgmatic --syslog-verbosity 1

https://projects.torsion.org/witten/borgmatic/raw/branch/master/sample/systemd/borgmatic.service

Without dbus-user-session installed, the job fails with the cryptic error message
May 21 23:06:26 reviewers systemd-inhibit[11421]: Failed to connect to bus: No such file or directory

The fix:
apt install dbus-user-session 

Note that just installing dbus is not enough.

It seems to be the default for the debian-buster image, it should probably be the default on the TKL appliance templates too?
eg this was the problem with 
    turnkey-nginx-php-fastcgi-16.0-buster-amd64

Thanks!
Paul

**Comment by OnGle** [comment]
I am strongly against install dbus at all if avoidable as we don't currently use it for anything (afaik). But `systemd-inhibit` is one of the few systemd components I would potentially consider installing it for...

@JedMeister thoughts?

**Comment by JedMeister** [comment]
> I am strongly against install dbus at all if avoidable as we don't currently use it for anything (afaik).

I tend to agree. But will discuss specifics over on #1635.

As you note, `systemd-inhibit` is possibly the only case where it is specifically needed and possibly the only real place where it is required currently (that I'm aware of; other requirements that I've hit have alternate commands/pathways to achieve the same ends)

FWIW I note that the [borgmatic systemd service](https://projects.torsion.org/borgmatic-collective/borgmatic/raw/branch/master/sample/systemd/borgmatic.service) now notes:
```
# Delay start to prevent backups running during boot. Note that systemd-inhibit requires dbus and
# dbus-user-session to be installed.
```

**Comment by JedMeister** [comment]
Whilst there are still scenarios where `dbus-user-session` is required, it is no longer required for dbus to function in most common use cases that I have tested. I'm unsure about `systemd-inhibit` itself (and haven't tested) but many of the other systemd related commands work with dbus, without installing `dbus-user-session`. This still won't resolve your specific use case, but with the warning in the [borgmatic systemd service](https://projects.torsion.org/borgmatic-collective/borgmatic/raw/branch/master/sample/systemd/borgmatic.service) I think your specific circumstance is covered.

As such I'm going to close this for now.

Having said that, I do note that `dbus-user-session` package is pretty small, so if there is a solid rationale for including it, I'm open to reconsidering it.
