### ISSUE TITLE
Catch socket.gaierror in Mail Relaying

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#1472]
Currently, when an address for Mail Relaying is entered incorrectly, confconsole returns a stack trace from smtplib, which might be confusing when encountered. (e. g. when user types smtp.google.com instead of smtp.gmail.com)

**Comment by qq7** [comment]
![2020-06-03-021821_1366x768_scrot](https://user-images.githubusercontent.com/21182031/83580834-c1256000-a545-11ea-93da-1da473faacbc.png)
![2020-06-03-021811_1366x768_scrot](https://user-images.githubusercontent.com/21182031/83580835-c1bdf680-a545-11ea-9bf6-fd491e70502c.png)
![2020-06-03-021800_1366x768_scrot](https://user-images.githubusercontent.com/21182031/83580836-c2568d00-a545-11ea-9005-c58f0c54a8f7.png)

**Comment by JedMeister** [comment]
Fixed in https://github.com/turnkeylinux/confconsole/pull/47/commits/b1e50e742f5e80418e7b5cf12e94871b6ed22e11
