### ISSUE TITLE
Support setting 'max_input_vars' for PHP (php.ini)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1476]
Currently there is support in [common](https://github.com/turnkeylinux/common/) for setting some PHP config via the individual appliance Makefile, namely [`PHP_MEMORY_LIMIT`, `PHP_POST_MAX_SIZE` & `PHP_UPLOAD_MAX_FILESIZE`](https://github.com/turnkeylinux/common/blob/master/conf/php#L23-L25).

It would be great if this were extended to other values too. E.g. `max_input_vars`.

**Comment by l-arnold** [comment]
That is quite important on many builds.   Usually it can be adjusted in Webmin....

We tried something similar on the original Odoo build, giving Memory Guidance in the build.  Realistically those variables should be modified per appliance, but often also based upon the Server Memory available.  Some Autmated tweaking would be recomended along with an easy to follow "logging" of any changes.

**Comment by l-arnold** [comment]
bump on "memory variable" context adjustability by App scale.  (ie more variables to a Small hub install than a Micro hub install).

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux/common/pull/281
