### ISSUE TITLE
Really weird ISO issue; directories named 'target' not copied on install?!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1479]
Following my investigations into an issue in the [Moodle appliance](https://github.com/turnkeylinux/tracker/issues/1454) I discovered a weird issue within [`di-live`](https://github.com/turnkeylinux/di-live) - I'm pretty sure within [`live-installer`](https://github.com/turnkeylinux/di-live/tree/master/d-i/source/live-installer) to be precise.

The issue is that directories named `target` do not get copied across at install.

**Comment by JedMeister** [comment]
So it seems that I may be on the right track? I'm not yet 100% sure, but browsing through the code, my guess is that the offending line may be [`live-installer` - line #59](https://github.com/turnkeylinux/di-live/blob/master/d-i/source/live-installer/live-installer#L59):
```
chroot . tar c --exclude=target . | \
```

We'll see I guess ...

**Comment by JedMeister** [comment]
So, testing reveals that my suspicion was on the money...

This issue has been closed by https://github.com/turnkeylinux/di-live/commit/3a214d99d99aab8461e1076c509b3c7feaf5e1f8

**Comment by l-arnold** [comment]
Nice work Jeremy!  It is funny sometimes how literally computer code is sometimes interpreted.
