### ISSUE TITLE
webmin service unreliable (especially in LXC, but likely elsewhere too)

### ISSUE THREAD

**Issue by thing4711** [turnkeylinux/tracker#1480]
Note from @JedMeister - This issue is confirmed and a workaround is noted [below](https://github.com/turnkeylinux/tracker/issues/1480#issuecomment-653979218).

Once this has been tested a bit more, the Webmin package will be rebuilt to include the fix.

If you test this and confirm that it works for you (regardless of whether you were having issues before or not) please comment below and note the build you are using (e.g. LXC or Proxmox, ISO, OVA, etc.).

----

Hello all,

I installed my new proxmox lab server last week and deployed some turnkey core containers on it. Up to yesterday, everything worked like a charm. Today I wanted to do some optimizations on one container and suddenly webmin stopped working.

After some unsuccessful debugging, I decided to re-install a fresh core container but also in this competely fresh installation, webmin is not listening anymore.

Either I broke something really big on the host (but on other containers webmin is still running) or there is something wrong with the turnkey configuration. Unfortunately I am stuck.

Steps I did:

1. Configured new lxc container on proxmox:
```
root@pmx:~# cat /etc/pve/lxc/103.conf 
arch: amd64
cores: 1
hostname: webmintest
memory: 512
net0: name=eth0,bridge=vmbr1,firewall=1,hwaddr=62:8C:08:2D:87:58,ip=dhcp,type=veth
ostype: debian
rootfs: vmfs:subvol-103-disk-0,size=8G
swap: 512
unprivileged: 1
```

2. I used **debian-10-turnkey-core_16.0-1_amd64.tar.gz** for installation:
```
extracting archive '/var/lib/vz/template/cache/debian-10-turnkey-core_16.0-1_amd64.tar.gz'
Total bytes read: 506183680 (483MiB, 99MiB/s)
Detected container architecture: amd64
Creating SSH host key 'ssh_host_ecdsa_key' - this may take some time ...
done: SHA256:z7AvCRLL63b9aFXuXxeM9ymAqH6BXFhy9hNu/PH/ClY root@webmintest
Creating SSH host key 'ssh_host_ed25519_key' - this may take some time ...
done: SHA256:o7Ymo+LM75iBc9dfIyLLqRvDPn04kHaEoIOPAAA+Lo4 root@webmintest
Creating SSH host key 'ssh_host_dsa_key' - this may take some time ...
done: SHA256:1DphEPN6yuZr8eyDC2xVBPId2uuE7E8vL6KtEEg03OU root@webmintest
Creating SSH host key 'ssh_host_rsa_key' - this may take some time ...
done: SHA256:ITu+RgrIdFPvwRvTmv1SiG2BzAQVSxpLTSGji1BaFDM root@webmintest
TASK OK
```

3. On first login I skipped the first two dialogues (hub services, system notifications)
4. I installed the security updates (also tried without which made no difference)
5. In advanced menu I did the region config to incorporate my timezone Europe/Berlin (not changing this had no effect either)
6. I quit the advanced menu

7. Directly afterwards webmin/stunnel is listening:
```
root@webmintest ~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:10000         0.0.0.0:*               LISTEN      2642/perl
tcp        0      0 0.0.0.0:12321           0.0.0.0:*               LISTEN      1394/stunnel4
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           2642/perl
[...]
```

8. I did a reboot and afterwards webmin is not listening anymore:
```
root@webmintest ~# reboot
[...]
Linux webmintest 5.4.44-1-pve #1 SMP PVE 5.4.44-1 (Fri, 12 Jun 2020 08:18:46 +0200) x86_64
Last login: Wed Jul  1 12:05:08 2020 from 192.168.253.176
root@webmintest ~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:12321           0.0.0.0:*               LISTEN      196/stunnel4
[...]
```

In the log I only see the following 4 lines repeating every 2-3 seconds:
```
root@webmintest ~# journalctl -f | grep webmin
Jul 01 12:11:32 webmintest webmin[582]: Webmin starting
Jul 01 12:11:32 webmintest systemd[1]: webmin.service: Succeeded.
Jul 01 12:11:33 webmintest systemd[1]: webmin.service: Service RestartSec=1s expired, scheduling restart.
Jul 01 12:11:33 webmintest systemd[1]: webmin.service: Scheduled restart job, restart counter is at 80.
Jul 01 12:11:33 webmintest perl[584]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
```

systemd status is showing one of the two following outputs depending on if the service is currently running...
```
root@webmintest ~# systemctl status webmin.service
* webmin.service - Webmin Web based Admin UI
   Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/webmin.service.d
           `-override.conf
   Active: active (running) since Wed 2020-07-01 12:13:15 CEST; 2s ago
 Main PID: 668 (miniserv.pl)
    Tasks: 1 (limit: 4915)
   Memory: 9.0M
   CGroup: /system.slice/webmin.service
           `-668 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

Jul 01 12:13:15 webmintest systemd[1]: webmin.service: Scheduled restart job, restart counter is at 110.
Jul 01 12:13:15 webmintest systemd[1]: Stopped Webmin Web based Admin UI.
Jul 01 12:13:15 webmintest systemd[1]: Starting Webmin Web based Admin UI...
Jul 01 12:13:15 webmintest systemd[1]: Started Webmin Web based Admin UI.
Jul 01 12:13:15 webmintest perl[668]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
```

...or being restarted:
```
root@webmintest ~# systemctl status webmin.service
* webmin.service - Webmin Web based Admin UI
   Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/webmin.service.d
           `-override.conf
   Active: activating (auto-restart) since Wed 2020-07-01 12:13:18 CEST; 462ms ago
  Process: 668 ExecStart=/usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
 Main PID: 668 (code=exited, status=0/SUCCESS)

Jul 01 12:13:18 webmintest systemd[1]: webmin.service: Succeeded.
```

The webmin logs do not provide useful information:
```
root@webmintest ~# tail /var/log/webmin/*
==> /var/log/webmin/miniserv.error <==
[01/Jul/2020:10:05:10 +0000] miniserv.pl started
[01/Jul/2020:10:05:10 +0000] Using MD5 module Digest::MD5
[01/Jul/2020:10:05:10 +0000] Using SHA512 module Crypt::SHA
[01/Jul/2020:10:05:10 +0000] PAM authentication enabled

tail: cannot open '/var/log/webmin/miniserv.log' for reading: No such file or directory

==> /var/log/webmin/webmin.log <==
1588162806.17811.0 [29/Apr/2020 12:20:06] - - - webmin install-module.pl "install" "-" "net" desc='Network Configuration'
1588162806.17842.0 [29/Apr/2020 12:20:06] - - - webmin install-module.pl "install" "-" "custom" desc='Custom Commands'
1588162807.17873.0 [29/Apr/2020 12:20:07] - - - webmin install-module.pl "install" "-" "shell" desc='Command Shell'
1588162807.17904.0 [29/Apr/2020 12:20:07] - - - webmin install-module.pl "install" "-" "firewall" desc='Linux Firewall'
1588162807.17935.0 [29/Apr/2020 12:20:07] - - - webmin install-module.pl "install" "-" "filemin" desc='File Manager'
1588162809.18084.0 [29/Apr/2020 12:20:09] - - - webmin install-module.pl "install" "-" "passwd" desc='Change Passwords'
1588162843.28525.0 [29/Apr/2020 12:20:43] - - - webmin install-module.pl "install" "-" "fdisk" desc='Partitions on Local Disks'
1588162843.28573.0 [29/Apr/2020 12:20:43] - - - webmin install-module.pl "install" "-" "raid" desc='Linux RAID'
1588162867.3336.0 [29/Apr/2020 12:21:07] - - - webmin install-module.pl "install" "-" "raid" desc='Linux RAID'
1588162867.3366.0 [29/Apr/2020 12:21:07] - - - webmin install-module.pl "install" "-" "lvm" desc='Logical Volume Management'
```

In the end, this is my situation right now. I have no idea where to look at as my webmin knowledge is quite limited and I have no idea why it first run and after reboot didn't anymore.

I also deployed a different container (ID, name, storage, ...) but the result is identical.

I hope for some ideas to debug more.

Siebo

**Comment by thing4711** [comment]
Suddenly without any interaction by me, webmin kept running...
```
root@webmintest ~# journalctl | grep webmin
[...]
Jul 01 13:03:59 webmintest systemd[1]: webmin.service: Succeeded.
Jul 01 13:04:00 webmintest systemd[1]: webmin.service: Service RestartSec=1s expired, scheduling restart.
Jul 01 13:04:00 webmintest systemd[1]: webmin.service: Scheduled restart job, restart counter is at 1026.
Jul 01 13:04:00 webmintest perl[2741]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 01 13:04:02 webmintest webmin[2741]: Webmin starting
```

and is now listening on the desired ports:
```
root@webmintest ~# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.1:10000         0.0.0.0:*               LISTEN      0          7238761    2742/perl
tcp        0      0 0.0.0.0:12321           0.0.0.0:*               LISTEN      0          6407816    196/stunnel4
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           0          7238762    2742/perl
[...]
```

At the same time I can see the CPU and memory usage going down in proxmox GUI:
![20200701 134654 webmintest CPU usage](https://user-images.githubusercontent.com/67686190/86240583-c2c46100-bba1-11ea-8cdb-5b9d28b00c56.png)
![20200701 134703 webmintest memory usage](https://user-images.githubusercontent.com/67686190/86240586-c35cf780-bba1-11ea-8697-e92b783fabf8.png)

However, while this would be great to be persistent, after a reboot, the issue started again with webmin not coming up...

**Comment by JedMeister** [comment]
Hi @thing4711,

Apologies on my slow response...

And also apologies on not posting an issue regarding this when it was first bought to my attention (on the [forums](https://www.turnkeylinux.org/forum/support/fri-20200612-1401/tkl-16x-webmin-not-working-lxc-containers) - a few weeks ago). Gross oversight on my behalf...

Anyway, as per that thread, it turns out that the `webmin.service` file that I developed isn't quite right... :cry: 

I have a [fixed one in my personal Webmin repo](https://github.com/JedMeister/webmin/blob/webmin-service-improvements/debian/webmin.service) but I really need to do some more testing before I merge it. Regardless, I've just opened a [pull request](https://github.com/turnkeylinux/webmin/pull/5).

So to just download the new service file, please try this:

```
URL=https://raw.githubusercontent.com/JedMeister/webmin/webmin-service-improvements/debian
wget -O /lib/systemd/system/webmin.service $URL//webmin.service
systemctl daemon-reload
systemctl restart webmin.service
```

And now Webmin should "just work". Please let me know if not.

**Comment by thing4711** [comment]
Hi @JedMeister,

thank you for your answer, explanation and resolution. You maybe missed to open the issue but apparently I missed to search the forums well enough ;-). However, your solution is fine for me as well and now webmin indeed "just works". For me you can consider this topic as resolved.

**Comment by JedMeister** [comment]
Hey @thing4711 - FWIW I finally got around to including this Webmin service file fix in the package; as well as updating Webmin to the (current latest) v1.955. They're all packaged up and [published to the TurnKey buster-testing repo](https://www.turnkeylinux.org/blog/webmin-1.955). If you get a chance and feel like testing it out, I'd love some feedback! :)
