### ISSUE TITLE
Prestashop permissions not quite right in v16.0 

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1481]
As reported in the [forums](https://www.turnkeylinux.org/forum/support/thu-20200702-1727/turnkey-prestashop-v16) it appears that the permissions for the v16.0 Prestashop appliance aren't quite right. 

We are [adjusting permissions](https://github.com/turnkeylinux-apps/prestashop/blob/master/conf.d/main#L54-L72) but they don't appear to quite match what Prestashop recommend (full info in their [install docs](http://doc.prestashop.com/display/PS17/Installing+PrestaShop)):

According to the docs, for 1.7 they should be; recursive write permission on:
```
cache/ 
config/
download/
img/
log/
mails/
modules/
override/
sitemap.xml
themes/default/cache/
themes/default/lang/
themes/default/pdf/lang/
translations/
upload/
```

**Comment by JedMeister** [comment]
Oops, this missed v16.1... Moving to v16.2 (if it happens... otherwise, it'll go to v17.0).

**Comment by OnGle** [comment]
This issue was already solved in this commit (and possibly before) https://github.com/turnkeylinux-apps/prestashop/commit/a942eae145568747ad311e07706188fa38f11673
