### ISSUE TITLE
Provide MongoDB web UI

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1489]
Since we deprecated RockMongo in v15.0 (due to lack of support for PHP7) our MongoDB appliance does not provide a UI. It'd be nice if we provided one. Currently there are 2 contenders which seem worth a look:
- [MongoDB Admin](https://github.com/hatamiarash7/MongoDB_Admin)
- [adminMongo](https://github.com/mrvautin/adminMongo)

Both are Node apps and both appear to be maintained.

Including this and an icon/link on the webcp page would also resolve #1484 :smile:

**Comment by OnGle** [comment]
Deferring until 17.0 as this feels like to big a change for a point release.
