### ISSUE TITLE
Duplicate backup ID's in hub

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#15]
Reported on [lp#979376](https://bugs.launchpad.net/turnkeylinux/+bug/979376) by ``S Conners`` on 2012-04-12

#### Description

In the hub, somehow my backups have been given duplicate id's. Any attempt to delete them via the hub gives an error.

**Comment by JedMeister** [comment]
Considering the age of this bug report and the lack of further comment I am closing. As per always reopen if you disagree.
