### ISSUE TITLE
Services.txt $ipaddr choosing wrong interface

### ISSUE THREAD

**Issue by CUCraigT** [turnkeylinux/tracker#1509]
I have an appliance set up and it has multiple interfaces because I am running Docker.

In my `services.txt` file, I am using `$ipaddr` as core does. However, this almost always chooses the `docker0` interface instead of `eth0`. Any way to specify or fix this, so that it points to `eth0`?

**Comment by JedMeister** [comment]
You should be able to set the default interface in the Confconsole config file; `/etc/confconsole/confconsole.conf`.

It's set to `eth0` in the conf, but commented out so as you note, will use whichever interface it finds first by default. If you wanted to force it to use `eth0` at build time, just uncomment it (and change the interface if `eth0`doesn't work).

I'll close this now, but if it doesn't work as expected, please come back and we'll turn this into a bug... :smile:

**Comment by CUCraigT** [comment]
Awesome. Thanks, @JedMeister . Worked perfectly at least just changing the file of a running appliance. Have the file in overlay now and will do a build in a bit. Thanks for the quick response.
