### ISSUE TITLE
Redmine ImageMagick install and rmagick gem not installed

### ISSUE THREAD

**Issue by qtzar** [turnkeylinux/tracker#151]
For Redmine to be able to generate some graphs within the application the ImageMagick application and Rmagick gem should be installed.

ImageMagic can be installed using 'apt-get install libmagicwand-dev' and then the Redmine bundle install command should be adjusted to read 'bundle install --without test development'

These two steps will enable ImageMagic/rmagicK support for Redmine.

**Comment by qrntz** [comment]
![screen](https://cloud.githubusercontent.com/assets/802109/9061782/ae4003f8-3ac6-11e5-9c86-d01410c8ae8e.png)
