### ISSUE TITLE
New Drupal 9 appliance

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1511]
Now that Drupal 9 stable has been released ([June 3, 2020](https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means)) we should create a new Drupal9 appliance.

Unlike previous Drupal major version bumps, Drupal9 has much less significant changes, so the Drupal8 appliance build code probably won't need a ton of adjustment, but there will likely be some tweaks required.

The only thing that is blocking currently is the fact that [drupal console doesn't currently support Drupal 9](https://github.com/hechoendrupal/drupal-console/issues/4220). Although we could disable drupal console for now and push ahead with a new Drupal9 appliance (after all, Drupal 9 has been stable for 3 months and the issue still exists...).

**Comment by JedMeister** [comment]
Unblocking by removing drupal console for now... We can reinstate it once it's compatible with Drupal 9.

**Comment by OnGle** [comment]
Drupal9 is complete https://github.com/turnkeylinux-apps/drupal9
