### ISSUE TITLE
Do you have plans to upgrade roundup to version 2.0.0 (released jul 2020)

### ISSUE THREAD

**Issue by rouilj** [turnkeylinux/tracker#1514]
I was wondering if you have plans to upgrade the appliance to version 2.0.0 of roundup.

**Comment by JedMeister** [comment]
Hi @rouilj - Yes we will use the new v2 release when we next update the appliance and do a new release (v16.1). Hopefully that will be soonish, but I can't give you a clear ETA.

If you'd love to see an updated appliance ASAP and have some basic bash/Linux knowledge (and/or are open to learning) then perhaps you could have a go and [hacking on the the build code](https://github.com/turnkeylinux-apps/roundup)? To do that, you'll need a [TKLDev instance](https://www.turnkeylinux.org/tkldev) (I suggest a VM) and have a look through the [TKLDev docs](https://github.com/turnkeylinux-apps/tkldev/tree/master/docs), particularly the [appliance maintenance docs](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/development/maintenance.rst). I'm happy to answer questions and/or provide a bit of coaching as needed.

Alternatively, if you wish to get going with Roundup v2.0.0 on our appliance before we do a new release, please see the [Roundup upgrade docs](https://www.roundup-tracker.org/docs/upgrading.html). Please note that the appliance we ship uses a MySQL (MariaDB) backend, so the [notes for that](https://www.roundup-tracker.org/docs/upgrading.html#python-2-mysql-users-must-read) will also apply.

I hope that helps. :smile:

**Comment by rouilj** [comment]
Hi Jeremy:

In message <turnkeylinux/tracker/issues/1514/695851230@github.com>,
Jeremy Davis writes:
>Hi @rouilj - Yes we will use the new v2 release when we next update
>the appliance and do a new release (v16.1). Hopefully that will be
>soonish, but I can't give you a clear ETA. 

Fair enough.

>If you'd love to see an updated appliance ASAP and have some basic
>bash/Linux knowledge (and/or are open to learning) then perhaps you
>could have a go and [hacking on the the build
>code](https://github.com/turnkeylinux-apps/roundup)?

Actually I have my hands full hacking on the roundup code (I'm a
roundup release engineer/dev). Currently I am updating infrstructure,
modifying the tracker instance we run, making gui tests using
splinter, testing alternate front ends using the REST interface and
developing my own tracker.

>Alternatively, if you wish to get going with Roundup v2.0.0 on our
>appliance before we do a new release, please see the [Roundup upgrade
>docs](https://www.roundup-tracker.org/docs/upgrading.html). Please
>note that the appliance we ship uses a MySQL (MariaDB) backend, so
>the [notes for
>that](https://www.roundup-tracker.org/docs/upgrading.html#python-2-mysql-users-must-read)
>will also apply.

Yup, that's why I was asking you. The MYSQL directions you reference
are our best guess as to what has to happen. None of the devs run
mysql, we all run postges for production (e.g. bugs.python.org and
issues.rounup-tracker.org).

We tried to create problem databases and test the commands. However we
can see that there is a potential issue, but haven't been able to
definitively prove there is an issue and that our notes solve it.

Does your mysql instance use a utf-8 encoded database?

I was hoping that you or one of your customers might be able to help
with testing that upgrade path.

Have a great week and stay safe.

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by JedMeister** [comment]
Hi there,

> (I'm a roundup release engineer/dev).

Ah ok, so you're a Roundup dev! Apologies that that possibility didn't occur to me... :smile:

> None of the devs run mysql, we all run postges for production

Hmm, ok. Is that recommended? Perhaps we should use that too for our appliance?

FWIW we've been providing the Roundup appliance for a long time, and IIRC back when we first created it, I don't think PostgreSQL was an option?!

It seems that [migrating between DB backends](https://www.roundup-tracker.org/docs/admin_guide.html#migrating-backends) is supported (and essentially also works around the issues that are noted re MySQL too), so assuming that the encoding issue doesn't apply, then perhaps we should just recommend that?!

> Does your mysql instance use a utf-8 encoded database?

As you note, our [Roundup appliance](https://www.turnkeylinux.org/roundup) uses MySQL (MariaDB). The v16.0 release has `utf8mb4` encoding (i.e. "full" UTF-8 with 4 byte character encoding) as is default on Debian 10/Buster (the base of our v16.x appliances).

AFAIK our prior v15.x releases used the prior MySQL (MariaDB) Debian 9/Stretch default of `utf8` (which for some bizarre reason is only a subset of UTF-8 with each character encoded in only 3 bytes).

TBH, I'm not sure what our releases prior to that (i.e. v14.x and earlier) used. I do vaguely recall that once upon a time `latin1` was the default MySQL encoding, but I think that was a long time ago now...

**Comment by rouilj** [comment]
Hi Jeremy:

In message <turnkeylinux/tracker/issues/1514/695863318@github.com>,
Jeremy Davis writes:
>> (I'm a roundup release engineer/dev).
>
>Ah ok, so you're a Roundup dev! Apologies that that possibility didn't
>occur to me... :smile:

No prob.

>> None of the devs run mysql, we all run postges for production
>
>Hmm, ok. Is that recommended? Perhaps we should use that too for
>our appliance?

That's a good question. I think the choice of postgres is because of
the historic issues with mysql. I am a sysadmin by training and have
had issues with mysql, varying backends (innodb vs myisam), getting
consistent backups etc. I also have developers using mysql who have
gotten burned. So postgres is what we use.

Given what you say below about using some variant of utf8 for the last
couple of releases, I don't think a migration is warranted.


>FWIW we've been providing the Roundup appliance for a long time, and
>IIRC back when we first created it, I don't think PostgreSQL was an
>option?!

From the mercurial history, postgres has been around since 2003/2004.

>It seems that [migrating between DB
>backends](https://www.roundup-tracker.org/docs/admin_guide.html#migrating-backends)
>is supported (and essentially also works around the issues that are
>noted re MySQL too), so assuming that the encoding issue doesn't
>apply, then perhaps we should just recommend that?!

If you do that you are going to need to redo some tooling for managing
the database, doing backups, housekeeping tasks etc.

So I stick with my recommendation above.

>> Does your mysql instance use a utf-8 encoded database?
>
>As you note, our [Roundup
>appliance](https://www.turnkeylinux.org/roundup) uses MySQL
>(MariaDB). The v16.0 release has `utf8mb4` encoding (i.e. "full"
>UTF-8 with 4 byte character encoding) as is default on Debian
>10/Buster (the base of our v16.x appliances).
>
>AFAIK our prior v15.x releases used the prior MySQL (MariaDB) Debian
>9/Stretch default of `utf8` (which for some bizarre reason is only a
>subset of UTF-8 with each character encoded in only 3 bytes).

Yup those should be fine.

>TBH, I'm not sure what our releases prior to that (i.e. v14.x and
>earlier) used. I do vaguely recall that once upon a time `latin1` was
>the default MySQL encoding, but I think that was a long time ago
>now...

Correct. IIRC the problem was that roundup writes/reads utf8 and if
the back end db has a latin1 encoding (or other non utf8 perhaps) the
bug fix in 2.0.0 will cause issues with characters that are
representable in utf8, but have a different representation in latin1.

I have to admit that my character encoding knowledge is very
superficial. IIUC trackers running in English won't have an issue as
utf8/latin1 are the same representation for all english characters.
German also got some testing seemingly without issue. We don't have
any asian or middle eastern (e.g. Turkish) users on the roundup lists
that answered our call. Those are the languages I would expect to have
issues.

Do you have any info about the users of your appliances? Are there any
using non-western european languages?

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by JedMeister** [comment]
Thanks John

> Given what you say below about using some variant of utf8 for the last couple of releases, I don't think a migration is warranted.

Ok great. We'll leave it as MySQL then.

> From the mercurial history, postgres has been around since 2003/2004.

Ah ok, well that certainly predates our appliance (IIRC our appliance was first released circa ~2010). I must have been mistaken.

> Correct. IIRC the problem was that roundup writes/reads utf8 and if the back end db has a latin1 encoding (or other non utf8 perhaps) the bug fix in 2.0.0 will cause issues with characters that are representable in utf8, but have a different representation in latin1.

Ok, good to have an understanding of.

> I have to admit that my character encoding knowledge is very superficial. IIUC trackers running in English won't have an issue as utf8/latin1 are the same representation for all english characters. German also got some testing seemingly without issue. We don't have any asian or middle eastern (e.g. Turkish) users on the roundup lists that answered our call. Those are the languages I would expect to have issues.

My knowledge of encoding is limited too (especially being an English speaking monoglot in an English speaking country). Your explanation matches my understanding too.

> Do you have any info about the users of your appliances? Are there any using non-western european languages?

The only user info we know of is the info provided by them (as well as aggregate website data) so I can't be really sure. Having said that, our distro is minimalist and ships with only US English and the vast majority of our website traffic is from English speaking countries. So my assumption is that there aren't many users using non-western European language, and if they are, unless they're legacy users, I suspect that they're using UTF encoding (at least the 3 byte MySQL variant).

Your described workaround seems reasonable, but I'll keep this in mind. If I come across a user that fits this and is having issues, I'll suggest that they reach out to you guys. I assume that the best place for contact is via the [Roundup user mailing list](https://sourceforge.net/projects/roundup/lists/roundup-users)?

**Comment by rouilj** [comment]
Hi Jeremy:

In message <turnkeylinux/tracker/issues/1514/696450894@github.com>,
Jeremy Davis writes:
>Thanks John

Your welcome.

>> Given what you say below about using some variant of utf8 for the last couple of releases, I don't think a migration is warranted.
>
>Ok great. We'll leave it as MySQL then.
> [...]
>My knowledge of encoding is limited too (especially being an English
> speaking monoglot in an English speaking country). Your explanation
> matches my understanding too.

I'm in the same boat here.

>Your described workaround seems reasonable, but I'll keep this in
>mind. If I come across a user that fits this and is having issues,
>I'll suggest that they reach out to you guys. I assume that the best
>place for contact is via the
> [Roundup user mailing list](https://sourceforge.net/projects/roundup/lists/roundup-users)?

Correct. Have a great week.

--
				-- rouilj
John Rouillard
===========================================================================
My employers don't acknowledge my existence much less my opinions.

**Comment by JedMeister** [comment]
Thanks @rouilj You have a great week too! :smile:
