### ISSUE TITLE
Prestshop permissions should be more permissive.

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1519]
As noted in the [forums](https://www.turnkeylinux.org/forum/support/tue-20201013-0703/turnkey-prestashop-proxmox-unable-upgrade-or-install-themes) the current Prestashop appliance permissions are too tight to allow "one-click upgrade". Joe also reports that theme install doesn't work either, although if uploaded as root user that may not be related...

**Comment by OnGle** [comment]
This is a permissions issue. It appears that (by looking at the "one-click upgrade" log, that it needs write access to most (if not all) prestashop files.

I initially had issues with module updates but it appears this was related too not being updated. Doh!
