### ISSUE TITLE
Redmine Git Repositories not served up over git protocol

### ISSUE THREAD

**Issue by qtzar** [turnkeylinux/tracker#152]
Redmine is configured to put the repositories in /srv/repos/git but the git-deamon is looking to /var/cache/git

the /etc/defaults/git-deamon file should be changed to have the following lines in it

GIT_DAEMON_ENABLE=true
GIT_DAEMON_USER=www-data
GIT_DAEMON_DIRECTORY=/srv/repos/git
GIT_DAEMON_OPTIONS="--export-all --enable=receive-pack"

To provide full GIT support in Redmine

**Comment by JedMeister** [comment]
So @alonswartz are you suggesting that we reconfigure Redmine to serve /var/cache/git instead? And/or symlink /srv/repos/git -> /var/cache/git !?

**Comment by qrntz** [comment]
I feel like this is obsolete.

**root@tkldev#** cat /etc/default/git-daemon
```bash
# Defaults for git-daemon initscript
# sourced by /etc/init.d/git-daemon
# installed at /etc/default/git-daemon by the maintainer scripts

#
# This is a POSIX shell fragment
#

GIT_DAEMON_ENABLE=true
GIT_DAEMON_USER=gitdaemon
GIT_DAEMON_BASE_PATH=/var/lib
GIT_DAEMON_DIRECTORY=/var/lib/git

# Additional options that are passed to the Daemon.
GIT_DAEMON_OPTIONS=""

# fix Debian git-daemon silliness
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740154

HOME=/nonexistent
```
**root@tkldev#** ls -l /var/lib/git/
```
total 0
lrwxrwxrwx 1 root root 30 Aug  4 11:39 helloworld.git -> /srv/repos/git/helloworld/.git
```
**qrntz@khaydarin /tmp $** git clone git://example.com/git/helloworld.git
```
Cloning into 'helloworld'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (7/7), done.
Checking connectivity... done.
```

**Comment by JedMeister** [comment]
@qrntz - Looking at your post I'd agree. Closing... 

@qtzar (or anyone else) if you disagree (after testing v14.0) then please reopen...
