### ISSUE TITLE
Include 'webmin-exports' package in File Server plan

### ISSUE THREAD

**Issue by maichai** [turnkeylinux/tracker#1521]
The File Server is also useful as NFS server, but the NFS functionality cannot be configured on the Webmin UI, although there are appropriate Webmin modules, e.g. `NFS Exports`. Unfortunately thoe are not available on TKL File Server, which is very puzzling to me.

For example in /etc/exports all internal IP address ranges are allowed to access the server, but if you wanted to tighten these controls you would have to edit the file, although you could use the Webmin module NFS Exports, if it would be available on TKL File Server.

I suggest to integrate the NFS related Webmin modules into TKL File Server.

**Comment by JedMeister** [comment]
FWIW, it should be install-able like this:

```
apt update
apt install webmin-exports
```

Please give that a go and let me know how it goes for you.

**Comment by maichai** [comment]
Thanks that works. I suggest to enclose this with the standard config already.

**Comment by JedMeister** [comment]
Thanks for confirming! I'll rename this issue.
