### ISSUE TITLE
Increase default Ghost upload file size

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1531]
[Key Turner suggested in the forums](https://www.turnkeylinux.org/forum/general/tue-20201103-1411/ghost-shooting-its-own-foot-upload-limit) that we increase the default Ghost file upload size 2MB (in Nginx conf). Sounds like a good plan to me! :smile: 

FWIW, we just need this line in the Nginx config:
```
client_max_body_size 2m;
```
The [source blog](https://www.santoshsrinivas.com/solving-the-maximum-file-size-error-on-ghost-nginx/) suggests adding it to the `http` section of `/etc/nginx/nginx.conf` (the main Nginx conf file). Keyturner confirms that works, however the [Nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) note that it can go in the `http`, `server` or `location` blocks, so it might be best to add it to the [`ghost` site config file (provided via an overlay)](https://github.com/turnkeylinux-apps/ghost/blob/master/overlay/etc/nginx/sites-available/ghost)?

**Comment by OnGle** [comment]
Sounds like the best way to handle it to me :+1: to in ghost site config file.
