### ISSUE TITLE
Ensure that turnkey-install-sec-updates NEVER uninstalls applications.

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1536]
The way that TurnKey currently installs automatic updates (aka `turnkey-install-security-updates`) is potentially dangerous.

In an edge case scenario, an application security update may require a new dependency from another repository (i.e. not included in `security` repos). However, as we enforce "security only" updates, the new dependency can not be fulfilled. We use `dist-upgrade`; so that new packages (such as new security related kernel packages) can be installed. But use of `dist-upgrade` also means that packages can be removed. This means that a security update without a fulfillable dependency will be removed instead of updated!

So the TL;DR is that under some edge case condition, a security update may actually uninstall software. Whilst allowing potentially insecure software to continue running is not ideal, uninstalling it completely is worse IMO!

FWIW - this is not a theoretical issue! It has occurred at least once previously - see #1246!

**Comment by OnGle** [comment]
I would argue that in some cases uninstalling could theoretically be better than using the currently installed version without security apps.

In my mind if it mitigates a DOS, then uninstalling is equivalent to the DOS, or maybe worse depending on the severity of the DOS being mitigated. However if we're talking about having user data stolen, losing admin access, being RATed or having local DB socket accessed. Consider if the security bug being fixed was a arbitrary code execution, say daisy chained with privilege escalation then it's almost certainly better that you have a denial of service, not matter how inconvenient.

BUT that's not to say we should continue as usual, perhaps we should make it configurable?

**Comment by JedMeister** [comment]
@OnGle - sorry for crazy slow response. You raise a good point. Ok then, let's leave it as is by default.

I was going to suggest that we update [`95secupdates`](https://github.com/turnkeylinux/inithooks/blob/master/firstboot.d/95secupdates) but the more I looked at it, the more I didn't like it because I don't think tying config into that is a good idea.

Instead, I think that we should just leave it as is by default and include a confconsole plugin to change it if desired.
