### ISSUE TITLE
Redis - add support for setting custom bind-ip

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1537]
As noted by @OnGle on a [recent PR](https://github.com/turnkeylinux-apps/redis/pull/3#pullrequestreview-533091988):

>  I'd like to note that the bind-ip will probably want more options eventually. There is at least 1 more option that may be wanted for it beyond localhost and internet wide: local-ip (of your local subnet ip) for locally, but not internet wide serving on a server connected TO the wider internet. Also a user may want a specific local ip for a specific interface if they're connected to multiple subnets.

Note that I've made it a "wishlist" item and also not pinned it to a milestone yet.

**Comment by qq7** [comment]
Would this have to be a third option which would lead to prompting to enter a custom IP range or should it be something different?

**Comment by JedMeister** [comment]
Oops, this was done in v17.x.
