### ISSUE TITLE
Don't use composer as root

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1539]
Currently in most (all?) of our lamp + composer installs we run composer as root. We shouldn't do this because of https://getcomposer.org/root 

I propose a common solution, use a new user. Called ``composer`` for example, which can't be logged into, then provide wrapper scripts in ``/usr/local/bin`` which run composer in the correct environment.

**Comment by JedMeister** [comment]
Looking at this one for inclusion in the upcoming v16.1 release. But I'm wondering if we should create a separate `composer` user as per your suggestion @OnGle, or whether we should just run as `www-data`? I'm just thinking that the latter might make things a bit more simple?!

**Comment by OnGle** [comment]
I'll need to think about this, back in november when we spoke about this originally, I was pretty sure there was a good rational for having a seperate user, however it's escaped me since and I apparently didn't have the forethought to note it here.

**Comment by JedMeister** [comment]
I've now added all apps that include the 'composer' keyword within the `conf.d` directory of their relevant buildcode.

**Comment by JedMeister** [comment]
Removed suitecrm - turns out that it wasn't actually using composer (it was in the conf script but commented out): https://github.com/turnkeylinux-apps/suitecrm/pull/11/commits/c41228e5b89a543386894df77dd313db04f4d611

**Comment by OnGle** [comment]
OK so here's the current status of this issue as far as I can tell:

- [x] lamp
- [x] lapp
- [x] bagisto
- [x] drupal7
- [x] drupal8
- [x] drupal9
- [ ] ezplatform
- [ ] laravel
- [ ] magento
- [ ] moodle
- [ ] silverstripe
- [ ] suitecrm
- [x] typo3

Moving to 17.0, let me know if you think that's not appropriate @JedMeister

**Comment by OnGle** [comment]
Also as noted in this issue I'm about to close this should be documented properly somewhere if it isn't already: https://github.com/turnkeylinux/tracker/issues/1168

**Comment by JedMeister** [comment]
Closing as per @OnGle's comment from years ago...
