### ISSUE TITLE
Octohub needs some love and care!

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#1540]
Octohub currently has 3 outstanding PRs:

https://github.com/turnkeylinux/octohub/pull/6
https://github.com/turnkeylinux/octohub/pull/5
https://github.com/turnkeylinux/octohub/pull/1

As well as both @JedMeister and I have local modifications we've been threatening to open PRs for, for a while.

Unfortunately all of this will probably not work together so I suggest I manually merge these, and then tidy things up a little bit afterwoulds. I have other priorities currently however I'll assign this to myself wwith the intention of handling this ideally before 16.1, feel free to ping me if this gets left hanging (as octohub is in sore need of some love and care).

**Comment by JedMeister** [comment]
Note I've just opened a new PR with all my changes: https://github.com/turnkeylinux/octohub/pull/8

I have been testing/using this particular version for a while and it seems pretty solid. It's also packaged in `buster-testing` and can be installed pretty easy on TurnKey via apt.

**Comment by OnGle** [comment]
I've done a review, "ideally" we would be able to include all users changes but unfortunately we waited way to long and it's become difficult. So let's just make a start rather than holding off longer.
