### ISSUE TITLE
lighttpd : (server.c.1493) WARNING: unknown config-key: setenv.add-response-header (ignored)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1546]
Checklist (see below for details):
- [x] ansible: fix `lighttpd.conf` overlay
- [x] domain-controller: fix `lighttpd.conf` overlay
- [x] openvpn: fix `lighttpd.conf` overlay
- [x] wireguard: fix `lighttpd.conf` overlay
- [x] common: (`conf/adminer-lighttpd`) - remove redundant code
- [x] common: (`conf/lighttpd-fastcgi`) - <s>test and confirm it's actually doing what is required... (perhaps should check that `mod_setenv` isn't already added/enabled?).</s> It's doing what is required, but we should double check that `mod_setenv` isn't already included before we add it.

----

This is an old issue which was previously resolved in common (see #994). However, I've just noticed that it still occurs on a few appliances which use Lighty, but have a `lighttpd.conf` overlay (i.e. doesn't inherit from common)... Because of the overlay, the previous fix doesn't propagate to those particular servers.

The fix is easy... Just need to load the `set_env` module. I.e. add it into this list:
```
server.modules = (
    "mod_access",
    "mod_alias",
    "mod_compress",
    "mod_redirect",
    "mod_accesslog",
    "mod_openssl"
)
```
So it looks like this:
```
server.modules = (
    "mod_access",
    "mod_alias",
    "mod_compress",
    "mod_redirect",
    "mod_accesslog",
    "mod_openssl",
    "mod_setenv"
)
```

Also while we fix this in these particular servers, we should probably also tidy up common:

As noted at the top, the code in `conf/adminer-lighttpd` appears to be redundant.

Also, whilst the relevant line in `conf/lighttpd-fastcgi` does what it should, we should be double checking that the `set_env` module isn't already listed.

**Comment by JedMeister** [comment]
Oops, I just came across this issue. As it was not pinned to a milestone, it appears that it's been overlooked... Pinning to v16.1 for now and will adjust as needed.

Of note is that the issue is resolved in Domain Controller (fixed previously) and Ansible (Lighty replace with Nginx) so I'll remove those tags.

**Comment by JedMeister** [comment]
FWIW I haven't investigated the common conf scripts further, but they seem ok.

**Comment by OnGle** [comment]
Adding to my list of "easy todos", will try to wrap this up tonight.

**Comment by OnGle** [comment]
With those 2 PRs merged, this issue should've been handled
