### ISSUE TITLE
I cant connect through proxy

### ISSUE THREAD

**Issue by ejgutierrez74** [turnkeylinux/tracker#1548]
Hi, im a teacher in a post obligatory studies. The past course we used turnkey wordpress to work with Wordpress. But dont know why in this latest version 16.0, when we connect from browser, appears the login window, for example wordpress. We put the username and password, and says error login failed invalid user or password. Both user and password were correct.

The proof is that if we open one virtual machine, and turnkey ( both virutal machines), and we connect from one to the turnkey...it works...with same user and password. So for some reason, with the proxy enabled tunkey doesnt recoginze username and password, in whatever way, adminer, webmin, wordpress... But if we connect from one virtual mahcine to turnkey it works...

Just a clue, with turnkey v15 it worked ok from computer to turnkey.
Any help would be apreciated.
Happy new year.

**Comment by JedMeister** [comment]
Hi there,

This is our issue tracker, generally reserved for reporting bugs and feature requests. Your issue sounds more like a support request which are generally best handled via our [forums](https://www.turnkeylinux.org/forum).

Anyway, seeing as we're already here...

Where/how are you running TurnKey? (E.g. VirtualBox VM, bare metal install, KVM, Proxmox LXC contianer, etc).

Which specific login interface are you referring to? (E.g. Webmin, Webshell, SSH, WordPress itself, Adminer, etc). I'm assuming you mean the WordPress admin login? You mention email address, but IIRC the pre-created WordPress just logs in using the username "admin". So have you tried logging in via the built-in "admin" account?

Are you using a US-International keyboard?

Were/are there any "special characters" in your password?

**Comment by ejgutierrez74** [comment]
Well i thought is a bug. Most of my students can connect without problems. But few of them, dont know why they cant connect.
We have spanish keyboard, and they use $ or € as special characters.
The problem is that they cant enter because login failure password or username not valid.
The thing is that username and password, are correct, because if they enter in the login screen of turnkey, they put the root and password and login without problems.
But if they go to https://192.168.2.54:12321 ( for example), appears the login window of webmin, but they put  username and password, and get the login error message.
We have a pc (host machine) with ubuntu 18.04, and the virtual machine using virtualbox 6.1
The virtual machines are in bridge mode.
Friday id try to change computers, and enter in adminer or webshell. The students with problems we are focused in entering webmin.
The students withoud problems, can login in whatever way, adminer, webshell, webmin, wordpres...

I think i have give all the information, if you need more, let me know....

Thanks for your help.

**Comment by ejgutierrez74** [comment]
@JedMeister , the problem is solved, some students need to reinstall the ova file 3 or 4 times. The same problem. Some decided to change the password, but others with same password, after 2 or 3 reinstallations, the vm worked fine. Id notice if in the future they can get login error again. So perhaps is a issue, bug with turnkey Wordpress.

Another little question, i cant get the Advanced settings menu, i only get the ips addresses and the quit button, not advanced settings. 

Thanks for your help

**Comment by JedMeister** [comment]
To get the advanced menu, you need to log in (as root). The first time it will auto start, but after that, you need to manually start it:

```
confconsole
```

I'll close this for now then...
