### ISSUE TITLE
Remove couchapp and python-couchdb from couchdb appliance

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1550]
I have noted this as a bug in an effort to ensure that it doesn't get forgotten/lost in the v17.0 release.

The [`python-couchdb` Debian package](https://packages.debian.org/buster/python-couchdb) will not be in Bullseye (only supports python2) and the third party [`couchapp`](https://github.com/couchapp/couchapp) development appears to have stalled (last "release" way back in 2016, last commit 2018).

There is an alternate python library; [cloudant]() (primarily aimed at IBM Cloudant; but also compatible with self hosted CouchDB) however, without CouchApp, I'm not convinced that there is much value pre-installing it...

**Comment by qq7** [comment]
@JedMeister it is recommended in the CouchDB docs to not use it as a web app server, so I think the best decision would be to provide a usual webcp?

**Comment by JedMeister** [comment]
@qq7 - yep sounds good!

**Comment by JedMeister** [comment]
This should have been shut ages ago...
