### ISSUE TITLE
OpenVPN image with lxc container on proxmox openvpn@server service failed

### ISSUE THREAD

**Issue by mate1213** [turnkeylinux/tracker#1551]
[edit by JedMeister] Document workaround info as noted in https://github.com/turnkeylinux/tracker/issues/1551#issuecomment-763839551

----

I just installed the ver 16.0 openvpn image, configured, and after reboot it seems to the server is up and runnig. 
![image](https://user-images.githubusercontent.com/36986834/105087447-c31f3d80-5a9a-11eb-9b91-e948aad8a27f.png)

But when I try to connect with my phone to the server, it's refusing my connection.
![Screenshot_20210119-210626_OpenVPN for Android](https://user-images.githubusercontent.com/36986834/105087590-fe217100-5a9a-11eb-993f-bc9e1062d5e4.jpg)

When I stop the service and start the server in "manual mode" with [openvpn /etc/openvpn/seerver.conf] **It's works just fine!**
I can connect to the server. Any suggestion?

### Update
just checked the openvpn@server services status
![image](https://user-images.githubusercontent.com/36986834/105088528-4beaa900-5a9c-11eb-9b31-30e2d796d9e1.png)

After that I tried to launch the server with the services command, which was **successful**. 
_Is there any explanation, why  failed the service start?_

**Comment by mate1213** [comment]
I figured out. I needed to add to the container definition the following lines:
lxc.apparmor.profile = unconfined
lxc.apparmor.allow_nesting = 1
lxc.apparmor.allow_incomplete = 1

Source: https://www.mail-archive.com/debian-user@lists.debian.org/msg745354.html

Could you add this to the read.me?

**Comment by marcos-mendez** [comment]
Actually i think there is a better way. If you trully want a VPN you can virtualize a machine with something like PFSense and provide a better security Core Architecture to the application if you are using proxmox. 

Also, is valuable notice that https://www.cloudhosting.lv/eng/faq/How-to-enable-tun-tap-inside-LXC Maybe you need to configure the correct rights here.

Another tip is to keep openvpn as a service and don-t run it manually is being a server you ganrantee H&A service providing. So
service openvpn (status/restart/stop/start are native commands)

tail -f /var/log/openvpn/server.log show the SERVER logging

openvpn-addclient user user@email.ctl creates a user

openvpn --help shows all posibilities

Hope i have helped

**Comment by JedMeister** [comment]
@marcos-mendez Thanks for the feedback.

FWIW our appliance already includes a [`openvpn-tun.service`](https://github.com/turnkeylinux-apps/openvpn/blob/master/overlay/etc/systemd/system/openvpn-tun.service) so that when running under LXC (with the appropriate host configuration - as noted above) should generate a tun device on every boot. So if you set up the LXC instance appropriately, it should "just work"...

**Comment by OnGle** [comment]
Closing: As far as I can tell this isn't an issue we can `fix`, please reopen if this isn't correct.
