### ISSUE TITLE
Tunkey Wordpress doesnt log to file

### ISSUE THREAD

**Issue by ejgutierrez74** [turnkeylinux/tracker#1552]
Hello,. im using latest Turnkey Wordpress 16.0.

I want to have a log file with information, to debug possible problems and monitoring VM.

As wordpress documentation i write in wp-config:

// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );
//define( 'WP_DEBUG_LOG', 'wp-errors.log' );

// Disable display of errors and warnings
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );

// Use dev versions of core JS and CSS files (only needed if you are modifying these core files)
define( 'SCRIPT_DEBUG', true );

 

This should create and log to default file debug.log.

But i had to create manually the file, and always is empty. So no logging.

I have also changed permissions of wordpress folder to www-data:www-data.

Any help would be apreciated.

**Comment by JedMeister** [comment]
Similar to my response to the other issue you opened:

I've responded to your cross [post on our forums](https://www.turnkeylinux.org/forum/support/thu-20210121-1137/turnkey-wordpress-doesnt-log-information) so I'm going to close this one.

FWIW, it does appear to work, but despite the name, it appears that it won't create a log until there are actually errors.

As I also noted previously (more for others benefit than yours) for future reference, our issue tracker is for tracking specific bugs or feature requests. The forums are the best place for more general and/or support questions such as this.

**Comment by ejgutierrez74** [comment]
Sorry i thought it was probably a bug.

**Comment by JedMeister** [comment]
No problem. :smile:
