### ISSUE TITLE
Apt update/upgrade vs secure updates

### ISSUE THREAD

**Issue by ejgutierrez74** [turnkeylinux/tracker#1553]
I want to ask if its recommended to update/upgrade a Tunkey virtual machine ( Wordpress). Or should i avoid these upgrades and in Advanced Menu go to Security Updates, and then only update/upgrade security packagees and be more stable.

Im afraid if i upgrade i can upgrade some root packages like mysql, php or so on...
The main reason to make security updates, is stability and not upgrading new versions of software.

Thanks

**Comment by JedMeister** [comment]
(I forgot to click the button the other day when I wrote this...)

I've responded to your cross [post on our forums](https://www.turnkeylinux.org/forum/support/sat-20210123-2015/updateupgrade-vs-security-updates) so I'm going to close this one.

For future reference, our issue tracker is for tracking specific bugs or feature requests. The forums are the best place for more general and/or support questions such as this.
