### ISSUE TITLE
Couldn't connect Open Ldap over TLS

### ISSUE THREAD

**Issue by sibiarunachalam** [turnkeylinux/tracker#1557]
We developed Java web app using Spring to integrate LDAP users.
I set up TurnKey open ldap VM for testing.
LDAP server IP address is mapped with hostname "openldap" in /etc/hosts.
I could able to connect it successfully using url ldap://openldap:389
But I couldn't connect the LDAP server over TLS using url ldaps://openldap:636

I used same TurnKey certificates from /etc/ssl/private in my Tomcat where the webapp is deployed
Did I miss any configuration in both sides?

Exception:
`Caused by: org.springframework.ldap.CommunicationException: simple bind failed: openldap:636; nested exception is javax.naming.CommunicationException: simple bind failed: openldap:636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching openldap found]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:108)
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:355)`

**Comment by JedMeister** [comment]
I'll fire one up and have a look ASAP.

However, IIRC OpenLDAP with TLS can be configured in 2 different ways. One is via StartTLS, using the same default port and protocol. It will attempt TLS encryption initially, but will fall back to unencrypted traffic if that fails. I.e. only `ldap://openldap:389` is used for both encrypted and unencrypted traffic. The other config uses an alternate port and only supports encrypted traffic. I.e. `ldaps://openldap:636`.

Obviously you are attempting to use the latter and IIRC the TurnKey appliance is pre-configured for the former.

Regardless, what you are seeking should be possible.

Re your error message, that appears to be a certificate issue (i.e. not related to OpenLDAP at all). The certificate which you are using appears to not include the FQDN of `openldap` that you are using to connect to your server. See this snippet (from your error message:
```
No name matching openldap found
```

**Comment by sibiarunachalam** [comment]
Thank you for your reply. 
This is root certificate issue. I imported wrong CA certificate into cacerts. Root cause is we looked wrong location for certificate configuration in TurnKey open ldap. The certificates found in /etc/ldap/tls, but we looked wrongly at /etc/ssl/private
It works after importing ca_cert.pem from /etc/ldap/tls into cacerts at client side.

**Comment by JedMeister** [comment]
Ah ok great! Thanks for posting back.

For what it's worth, I did learn a fair bit about OpenLDAP during my testing... And part of that was to create a new helper script that will be included in new releases that allows regeneration of the cert/key pair if you wish to use IP address or an alternate hostname.

I'll also add a note to the readme (the appliance page is generated from the readme).
