### ISSUE TITLE
TKLDev - replace polipo with a better build download proxy (squid?)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1560]
As recommended by @OnGle - this issue is essentially a consolidation of #353 & #467.

In summary, `polpo` (the caching software we've been using in TKLDev since forever) is great at caching vanilla HTTP, but can't cache HTTPS. As such, in 2021 the only thing it's really caching is Debian packages, from Debian and TurnKey repos. `polipo` is no longer in development so we're probably best off switching to an alternate caching software. I suspect that `squid` will be the best option...

We can then leverage it to download packages from either HTTP or HTTPS. Not only will that support all apt and direct downloads, but should also allow us to cache third party package manager downloads (e.g. `pip`, `gem`, `npm`, etc.).

**Comment by JedMeister** [comment]
Check out this cool looking proxy tool that I found: https://mitmproxy.org/

I'm not necessarily recommending that we use that to do our proxying in TKLDev, but we probably could! Regardless it looks really cool if you ask me and I wanted to share...! :smile:

**Comment by JedMeister** [comment]
I've made this a 'bug' as polipo has been removed from Bullseye, so this needs to be done! :smile:

**Comment by JedMeister** [comment]
Out of interest, `mitproxy` is [packaged in Debian](https://packages.debian.org/bullseye/mitmproxy) so could actually be an option?!

As an aside (not really relevant to this issue; but cool non-the-less) it looks like it allows you to make scripted changes to HTTP traffic (using Python)! :smile:

**Comment by vondrt4** [comment]
Hi!
If I can chime in, mitmproxy doesn't have caching, neither does tinyproxy and ffproxy.
How about apt-cacher-ng? Is that enough? If there are other repositories than just apt to cache, I'd go for
"squid-deb-proxy: Squid proxy configuration to optimize package downloads" and extend the configuration a bit.

**Comment by JedMeister** [comment]
Hi @vondrt4 

> If I can chime in

Please do! :smile: 

>mitmproxy doesn't have caching, neither does tinyproxy and ffproxy.

Oops. Right you are. Ok, that's a gross oversight on my behalf...!

> How about apt-cacher-ng? Is that enough?

That's great for apt packages, but no good for other stuff (like git clones, pip installs, gem installs, etc).'

>If there are other repositories than just apt to cache, I'd go for
"squid-deb-proxy: Squid proxy configuration to optimize package downloads" and extend the configuration a bit.

Yes, I think you're right. I think that's the go! :+1:

**Comment by JedMeister** [comment]
FWIW, we've gone for Squid. We're using the `squid-openssl` Debian package (which is compiled with SSL/TLS support). We're configuring it with a self-signed local CA so that it can cache HTTPS URLs as well as HTTP.
