### ISSUE TITLE
Only include composer in apps that use it

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1563]
As a streamlining/minimisation measure, we should only include composer in apps that use it. Although LAMP and LAPP should probably be exceptions to the rule.

To do that, we should remove the `composer.mk` from the common `lamp.mk` & `lapp.mk` and just manually add it to the `Makefile` of LAMP, LAPP and any appliance that uses it.

The apps that will need the changes (i.e. ones that use composer, or we decide to include it) have been noted below and tagged in this issue.

- [x] Remove from `lamp.mk` & `lapp.mk` common makefiles

Add to appliance Makefiles
- [x] lamp
- [x] lapp
- [x] bagisto
- [x] cakephp [note: buildcode doesn't yet use it (see #1591) - but would be useful for users, so included now]
- [x] drupal7
- [x] drupal8
- [x] drupal9
- [ ] ezplatform
- [ ] laravel
- [ ] magento
- [ ] moodle
- [ ] silverstripe
- [x] snipe-it
- [x] typo3

**Comment by JedMeister** [comment]
Removed suitecrm - turns out that it wasn't actually using composer (it was in the conf script but commented out): https://github.com/turnkeylinux-apps/suitecrm/pull/11/commits/c41228e5b89a543386894df77dd313db04f4d611

**Comment by OnGle** [comment]
ping @JedMeister

**Comment by JedMeister** [comment]
@OnGle - this is another one that we'll need to double check with repos that it's been done (or not). I have update the checklist with the merged PRs noted here, but there are still some outstanding (they may have been done, but I can't confirm right now).

**Comment by JedMeister** [comment]
Removed snipe-it - it uses composer now anyway...

**Comment by JedMeister** [comment]
Actually, I've just made an executive decision to close this issue....
