### ISSUE TITLE
Invoice Ninja v5.x released as stable - be great to include it ASAP

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1572]
As noted by [OZ in the forums](https://www.turnkeylinux.org/comment/49431#comment-49431) Invoice Ninja v5.x has just been released as stable. I.e.:

- https://www.reddit.com/r/invoiceninja/comments/lxi55n/big_news_invoice_ninja_v5_stable_release/
- https://forum.invoiceninja.com/t/the-v5-stable-release-is-now-available/6120

Due to their versioning it's actually v5.1.14 which IMO seems like a super unintuitive version to be the first stable release of the v5.x, but anyway... Regardless, it's a major rewrite and looks super awesome! :smile: 

It'd be great to update our appliance to use v5.x ASAP.

Install instructions: https://invoiceninja.github.io/docs/self-host-installation/

Having said that, unfortunately, we've just built our v16.1 release (which includes [v4.5.33](https://github.com/turnkeylinux-apps/invoice-ninja/blob/master/changelog#L3)). So without any glaring "showstopper" bugs, I'm a bit loathe to rebuild it again so soon (we're about 1/3 through updating the library and to start redoing the 1/3 we've already done wouldn't be ideal).

So we'll have to see how we go...

**Comment by DocCyblade** [comment]
I had a quick go at building 5.0 and there are many changes so it will not be a quick build. However I take up the challenge.

**Comment by telepath** [comment]
It's been a year, has there been any progress? 
v4 is working fine for me so far, but it would be nice to update at some point.

**Comment by JedMeister** [comment]
@telepath - AFAIK all the v5 Invoice Ninja issues are resolved and it's ready for production. The holdup on an updated TurnKey appliance is that we're currently working on v17.0; a new major version release. As always seems to be the case, it takes much longer than it was going to in my head...

**Comment by seanmahrt** [comment]
Any progress?  I'm currently using another "packager" type software for invoice-ninja, and all though it works well, I still somewhat like "standalone" containers for simplicity and robustness.

**Comment by JedMeister** [comment]
@seanmahrt - Unfortunately not.

There have been quite a few hiccups to the v17.x release. Currently it has completely stalled because I'm sidetracked on some stuff that needs urgent attention.

Whilst the upgrade to Invoice Ninja v5 is a major upgrade, from my browsing of the Invoice Ninja docs, it seems that the blocking issue has been resolved. So it should just be a case of just updating the build code (to install v5 and any specific tweaks that need changing).

Regardless, I'm loath to actually give a specific timeframe. I'm usually overly optimistic and make a fool of myself! :smile:

**Comment by JedMeister** [comment]
I'm closing this now as we have released v17.1 of our Invoice Ninja appliance which includes v5.x. See here: https://www.turnkeylinux.org/invoice-ninja

Please note that unfortunately there is a fairly serious bug (thankfully with an easy fix) in the current release. See #1772 for details.
