### ISSUE TITLE
Move to Nginx as web server for Invoice Ninja 5.x?

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#1577]
With all the docs showing using Nginx as the web front end for Invoice Ninja 5.x maybe we should follow? 5.x will be a big update to build code anyway.

**Comment by JedMeister** [comment]
As I've already commented privately:

>Initially I was inclined to agree with you [on moving to Nginx] but after having a closer look, the detailed install guides (which is where the Nginx conf comes from) is provided by a community member (not the core dev team). And the community member who wrote the guides explicitly states:
>> You might prefer to use apache2, but I am only supporting one web server conf file, and am already using nginx.

So I don't think that the fact there is only Nginx config is a specific recommendation, rather just the preferences of the particular community member who wrote those particular docs.

As such, I think that sticking with the default webserver is a reasonable plan.

Having said that, whether or not we continue to use Apache as our "default webserver" is certainly open for further discussion!

I started writing about that here, but I have decided to open a fresh issue for that. I'll come back and update this post with the link...
