### ISSUE TITLE
Move Nginx & LigHTTPd apps from FastCGI to PHP-FPM

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1589]
TurnKey Nginx & LigHTTPd appliances currently use FastCGI. Whilst that is definitely an improvement over CGI, FastCGI is still pretty generic and PHP provide PHP-FPM (essentially FastCGI developed by PHP for PHP). As such, we should look to move to PHP-FPM IMO.

There is a Debian [`php-fpm` package](https://packages.debian.org/buster/php-fpm). The current (7.3) package [includes a systemd service](https://packages.debian.org/buster/amd64/php7.3-fpm/filelist), so will actually simplify TurnKey's set up...

**Comment by pucilpet** [comment]
It would also be helpful if inithooks/confconsole offered an option to change the ssh port - I think many people end up changing the port manually after the initial install.
