### ISSUE TITLE
Looks like Odoo14 will be in Debian repos!? We should consider using that!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1590]
[It looks like Odoo14 will make it into the official Bullseye Debian repos](https://packages.debian.org/bullseye/odoo-14) (which will be the basis for TurnKey v17.x). IMO we should seriously consider using that rather than upstream.

As additional info, IIRC upstream's repo is called "nightly" (not sure if it actually is or not) which suggests that it's not stable. As we know, using the Debian package will mean both stability and security updates.

**Comment by marcos-mendez** [comment]
@JedMeister count on me if i can help, altought i've been trying to play with tkl core and dev for the last 6 months im not able to build anything, maybe is my dumb head, but any ways. I don't understand what the v17 means to Odoo as it runs most of the time on the nightly builds. If you can explain i'll appreciate. 

Thnaks for the work buddy

**Comment by JedMeister** [comment]
@marcos-mendez - so you can't even build core? How far can you get with [this](https://www.turnkeylinux.org/docs/howto-build-isos-with-tkldev)? If you tell me what goes wrong, perhaps I can help out?

**Comment by l-arnold** [comment]
Strangely, for version 16.0, the Turnkeylinux App page says the Repo is already being used.
See just below "Stable Version 16.0" then a Line
----------
 "Odoo v12 installed from official Odoo Debian repo."

**Comment by JedMeister** [comment]
Thanks @l-arnold - good catch. It should probably read something like "Official Odoo 3rd party apt repo".

In Debian 11/Bulleye, it will be in the actual Debian repos (as opposed to the separate Odoo repo we currently use).

There are pros and cons to use an official Debian package.

One pro is that there will be auto security updates (that shouldn't break things).

One con is that if there are bugs, they may not get a timely fix.
Another con (for some at least) is that it will be Odoo 14 for the life of TurnKey v17.x.

**Comment by JedMeister** [comment]
@l-arnold - hopefully this clarifies things:

> Odoo v12 installed from 3rd party (official) Odoo apt repo.

**Comment by JedMeister** [comment]
Should have been closed last year...
