### ISSUE TITLE
Nextcloud MariaDB not using utf8mb4

### ISSUE THREAD

**Issue by p3k** [turnkeylinux/tracker#1602]
Yesterday I installed the `debian-10-turnkey-nextcloud_16.1-1_amd64.tar.gz` template in a Proxmox LXC container and stumbled over https://github.com/nextcloud/server/issues/20883.

https://github.com/nextcloud/server/issues/20883#issuecomment-702833402 provides the solution, setting `init-connect='SET NAMES utf8mb4'` somewhere in the MariaDB config.

Searching for the right spot I found the file `/etc/mysql/conf.d/force_utf8.cnf` and changed the setting there:

```config
# Force Unicode/UTF8
[mysqld]
init_connect='SET collation_connection = utf8_general_ci'
init_connect='SET collation_database = utf8_general_ci'
# ➖ Disabled the following line
#init_connect='SET NAMES utf8'
# ➕ Added the following line
init_connect='SET NAMES utf8mb4'
character-set-server=utf8
collation-server=utf8_general_ci
skip-character-set-client-handshake
```

After restarting MariaDB the error was gone. However, I am not sure whether this is the proper solution. Maybe the file needs even more tweaking, maybe it should be replaced altogether…?

Feedback appreciated.

**Comment by JedMeister** [comment]
Thanks for reporting. What you've done looks fine.

I think that we should update this for all appliances that include MySQL/MariaDB.

**Comment by JedMeister** [comment]
Ok. So if what you've done is sufficient for your needs, then that should be fine. Having said that, moving forward, we'll force `utf8mb4` encoding as per the [pull request I just opened](https://github.com/turnkeylinux/common/pull/190). Thanks again for reporting.

**Comment by p3k** [comment]
thanks for the quick reply @JedMeister.

i patched the file with your changes in turnkeylinux/common#190 and did not experience any side effects – ran `occ mail:account:sync` without issues.
