### ISSUE TITLE
GitLab: LDAP integration not working

### ISSUE THREAD

**Issue by AltairWolfe** [turnkeylinux/tracker#1604]
Below is the text of the LDAP section of my gitlab.rb file (minus identifying information).  Despite having this all configured, LDAP as an authentication method will not enable.  It does not show up as enabled in the admin console and when I perform a 

> sudo gitlab-rake gitlab:ldap:check 

it returns 

> LDAP: ... LDAP is disabled in config/gitlab.yml

a file that does not exist as my understanding of the TurnKey is that it's an Omnibus installation, not a source.

> gitlab_rails['ldap_enabled'] = true
> gitlab_rails['prevent_ldap_sign_in'] = false
> 
> ###! **remember to close this block with 'EOS' below**
> gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
>   main: # 'main' is the GitLab 'provider ID' of this LDAP server
>     label: 'LDAP'
>     host: 'tf-dc1.placeholder.local'
>     port: 389
>     uid: 'sAMAccountName'
>     bind_dn: 'CN=LDAPAuth,OU=IT,OU=placeholder,DC=placeholder,DC=local'
>     password: 'placeholder'
>     encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
>     verify_certificates: true
>     smartcard_auth: false
>     active_directory: true
>     allow_username_or_email_login: false
>     lowercase_usernames: false
>     block_auto_created_users: false
>     base: 'DC=placeholder,DC=local'
> EOS

Also attempted with a more traditional YAML formatting (spaces disappeared from this post somehow):

> gitlab_rails['ldap_enabled'] = true
> gitlab_rails['prevent_ldap_sign_in'] = false
> gitlab_rails['ldap_servers'] = {
> 'main' => {
>   'label' => 'LDAP',
>   'host' =>  'tf-dc1.placeholder.local',
>   'port' => 389,
>   'uid' => 'sAMAccountName',
>   'encryption' => 'simple_tls',
>   'verify_certificates' => true,
>   'bind_dn' => 'CN=LDAPAuth,OU=IT,OU=placeholder,DC=placeholder,DC=local',
>   'password' => 'placeholder',
>   'encryption' => 'plain',
>   'verify_certificates' => true,
>   'tls_options' => {
>     'ca_file' => '',
>     'ssl_version' => '',
>     'ciphers' => '',
>     'cert' => '',
>     'key' => ''
>   },
>   'timeout' => 10,
>   'active_directory' => true,
>   'allow_username_or_email_login' => false,
>   'block_auto_created_users' => false,
>   'base' => 'dc=placeholder,dc=local',
>   'user_filter' => '',
>   'attributes' => {
>     'username' => ['uid', 'userid', 'sAMAccountName'],
>     'email' => ['mail', 'email', 'userPrincipalName'],
>     'name' => 'cn',
>     'first_name' => 'givenName',
>     'last_name' => 'sn'
>   },
>   'lowercase_usernames' => false,
> 
>   # EE Only
>   'group_base' => '',
>   'admin_group' => '',
>   'external_groups' => [],
>   'sync_ssh_keys' => false
>   }
> }
>

**Comment by JedMeister** [comment]
As noted on the [forums](https://www.turnkeylinux.org/forum/support/wed-20210428-1336/gitlab-appliance-ldap#comment-49724), it appears that updating GitLab should solve this issue. I.e.:

```
apt update
apt install gitlab-ce
```

**Comment by OnGle** [comment]
Closing: refers to a bug which is fixed upstream and is tagged to an old release. If this is NOT fixed please re-open and move to 17.0
