### ISSUE TITLE
Forbidden access for live stream (ZoneMinder)

### ISSUE THREAD

**Issue by edurenye** [turnkeylinux/tracker#1607]
Live stream uses a path starting with `/zm/cgi-bin/nph-zms` and anything under this path returns an 'HTTP 403 ERROR' Forbidden access error.
The path for live stream is `/zm/?view=watch&mid=1` but the path of the rendered image is `/zm/cgi-bin/nph-zms?...`.

Tested with V 16.1 OVA image in VirtualBox.

**Comment by edurenye** [comment]
I've found here: https://forums.zoneminder.com/viewtopic.php?t=28951
That using `auth_relay = none` fixes the issue, but that is a big through-back in security, so would be nice to fix this issue.My guess is that has something to do with Apache configuration.

**Comment by JedMeister** [comment]
Apologies on my delayed response. Hmm, TBH, I'm not 100% sure.

Looking at the default [Apache config](https://github.com/turnkeylinux-apps/zoneminder/blob/master/overlay/etc/apache2/sites-available/zoneminder.conf) it appears that the `/zm/cgi-bin` path is a script alias for `/usr/lib/zoneminder/cgi-bin` and further down you should see that you should have permission to access all paths. But for v16.0 we moved to a (Zoneminder supplied) 3rd party package, so perhaps the path is wrong now? Actually, I just checked and that doesn't appear to be the issue...

Although it might be worth double-checking the permissions of the directory `/usr/lib/zoneminder/cgi-bin/`. I imagine that it will be owned by root (as it's package managed) but the webserver user (`www-data`) should have read access.

Also, I've noticed that there is a script alias in the [`000-default`](https://github.com/turnkeylinux-apps/zoneminder/blob/master/overlay/etc/apache2/sites-available/000-default.conf#L14) Apache site too?! I suggest commenting that out too.

The only other thing that occurs to me is that possibly there is a bug within Zoneminder itself. So perhaps double check for updates? I.e.:

```
apt update
apt install zoneminder
```

**Comment by JedMeister** [comment]
PS also you'll need to restart Apache to apply any config changes. Do that like this:

```
systemctl restart apache2
```

Also if the issue persists, please have a look at the Apache error log (`/var/log/apache2/error.log`) and see if there is anything more explicit in there.

**Comment by JedMeister** [comment]
I'm pretty sure that this should also hopefully be fixed by #1623

**Comment by edurenye** [comment]
Yes, #1623 fixes the problem.

**Comment by JedMeister** [comment]
Thanks for confirming.
