### ISSUE TITLE
Consider handling `dialog.DialogError` in Confconsole

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1609]
Currently, there are situations where if the terminal is resized to dimensions smaller than the pre-set size of the text, a `dialog.DialogError` will occur (e.g. see [this forum post](https://www.turnkeylinux.org/forum/support/tue-20210518-0647/something-little-weird-ghost-161).

It might be nice to handle this exception, rather than spew out a stacktrace?!

**Comment by OnGle** [comment]
Moving to 17.1, if we get time I might come back to this...
