### ISSUE TITLE
Nextcloud Disable SSL / HTTPS redirect

### ISSUE THREAD

**Issue by ectoplasmosis** [turnkeylinux/tracker#1620]
I'm trying to set up a Turnkey Nextcloud container to be used with Cloudflare's SSL proxy, so need to disable SSL/HTTPS redirection.

How can I do this?
Many thanks.

**Comment by JedMeister** [comment]
Hi sorry for slow response. Firstly, this is for posting confirmed bugs or feature requests, support is handled in our [forums](https://www.turnkeylinux.org/forum/support).

While you're here though, here's how to remove a redirect. Locate the Apache config file - /etc/apache2/sites-available/nextcloud.conf (the default files should [look like this]https://github.com/turnkeylinux-apps/nextcloud/blob/master/overlay/etc/apache2/sites-available/nextcloud.conf()) and find the `<VirtualHost *:80>` section. It should look something like this:

```
<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin webmaster@localhost

    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>
```

Change it so it looks like this instead:
```
<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin webmaster@localhost

    DocumentRoot /var/www/nextcloud/
    #RewriteEngine On
    #RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>
```
(I.e. comment out the rewrite parts and add in the `DocumentRoot`).

Then restart Apache:
```
systemctl restart apache2
```
```
