### ISSUE TITLE
Zoneminder has wrong apache2 config (API not working)

### ISSUE THREAD

**Issue by MatijaTerzic** [turnkeylinux/tracker#1623]
The default apache2 zondeminder.conf (in /etc/apache2/sites-enabled/) is wrong and the API is not working.

In attachment the right file that works

[zoneminder.conf.txt](https://github.com/turnkeylinux/tracker/files/6653631/zoneminder.conf.txt)

```
# Remember to enable cgi mod (i.e. "a2enmod cgi").
ScriptAlias /zm/cgi-bin "/usr/lib/zoneminder/cgi-bin"
<Directory "/usr/lib/zoneminder/cgi-bin">
    Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
    AllowOverride All
    Require all granted
</Directory>


# Order matters. This alias must come first.
Alias /zm/cache /var/cache/zoneminder/cache
<Directory /var/cache/zoneminder/cache>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all granted
    </IfModule>
</Directory>

Alias /zm /usr/share/zoneminder/www
<Directory /usr/share/zoneminder/www>
  Options -Indexes +FollowSymLinks
  <IfModule mod_dir.c>
    DirectoryIndex index.php
  </IfModule>
</Directory>

# For better visibility, the following directives have been migrated from the
# default .htaccess files included with the CakePHP project.
# Parameters not set here are inherited from the parent directive above.
<Directory "/usr/share/zoneminder/www/api">
   RewriteEngine on
   RewriteRule ^$ app/webroot/ [L]
   RewriteRule (.*) app/webroot/$1 [L]
   RewriteBase /zm/api
</Directory>

<Directory "/usr/share/zoneminder/www/api/app">
   RewriteEngine on
   RewriteRule ^$ webroot/ [L]
   RewriteRule (.*) webroot/$1 [L]
   RewriteBase /zm/api
</Directory>

<Directory "/usr/share/zoneminder/www/api/app/webroot">
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
    RewriteBase /zm/api
</Directory>
```

**Comment by JedMeister** [comment]
Thanks for reporting this and bonus points for posting a fix! You rock! :smile:

**Comment by JedMeister** [comment]
Argh! I just realised that this one got overlooked for v17.0/17.1!

**Comment by criadoperez** [comment]
The folder you are referring to I think is `/etc/apache2/conf-enabled/`  instead of in `/etc/apache2/sites-enabled/` (just in case anybody out there is searching for the zoneminder.conf file)

**Comment by JedMeister** [comment]
Hi @criadoperez - Thanks for your post.

Although on the [TurnKey Zoneminder](https:///www.turnkeylinux.org/zoneminder) appliance, the file we provide is `/etc/apache2/sites-available/zoneminder.conf` (when enabled, there is a symlink to it from `/etc/apache2/sites-enabled/zoneminder.conf`).

Although it's awesome that you posted as I did not realise that the (3rd party) Zoneminder deb package that we use includes `/etc/apache2/conf-available/zoneminder.conf` file (similarly, when enabled there is a symlink to it from `/etc/apache2/conf-enabled/zoneminder.conf`). After having a bit of a poke around, I also noticed that the package also provides an example apache.conf (`/usr/share/doc/zoneminder/examples/apache.conf`).

I'll have to have a closer look at them all side-by-side (including the example one in the OP) and decide exactly how I'll address this. I suspect that I'll consolidate everything into a single `/etc/apache2/sites-available/zoneminder.conf`, but I'm not sure yet.

Regardless, I'll be aiming to address this issue and re-release the appliance (in the next v17.x release batch) with this fixed (and a newer version of Zoneminder pre-installed - to address https://github.com/turnkeylinux/tracker/issues/1791).

**Comment by ubeaut** [comment]
If I use the zoneminder.conf above the api works but the web page only displays text and if I use the zoneminder.conf that came with the .deb the webpages display but the api doesn't work.

I am using version 1.36.33 and debian 12 and followed install instructions from here:

https://wiki.zoneminder.com/Debian_12_Bookworm_with_Zoneminder_1.36.33

If I want to review any recordings I have to swap back to the original zoneminder.conf then swap back again to the zoneminder.conf above so I can use the api.

Is anyone else seeing this?
I have tried different web browsers but all do the same thing.

**Comment by JedMeister** [comment]
Hi @ubeaut - apologies about delayed response.

Before I say too much, it sounds like you aren't using TurnKey. Whilst we try to remain consistent with upstream recommendations (where we think they make sense), we do not develop the ZoneMinder software. We produce a Debian based [ZoneMinder software appliance](https://www.turnkeylinux.org/zoneminder) - we have no official or formal affiliation with the ZoneMinder team (although we do have open dialog with them).

So if you continue to have struggles, then I suggest contacting the ZoneMinder team directly.

Having said that, please read on...:
https://raw.githubusercontent.com/turnkeylinux-apps/zoneminder/master/overlay/etc/apache2/sites-available/zoneminder.conf



> If I use the zoneminder.conf above the api works but the web page only displays text and if I use the zoneminder.conf that came with the .deb the webpages display but the api doesn't work.

It sounds like the config above resolves your API issues, but is not allowing the CSS/Javascript to be read as well (that's my guess anyway - to check open the web browser "dev tools" and look for assets giving a 404). And the default conf doesn't properly support the API.

Could you please try the {Apache config that we provide by default](https://raw.githubusercontent.com/turnkeylinux-apps/zoneminder/master/overlay/etc/apache2/sites-available/zoneminder.conf) and let me know how that goes? Note that that will server ZoneMinder via a subdirectory - i.e. https://YOUR_SERVER/zm.

To make it a bit easier for you, here's a code snippet to download and replace the current apace conf (assumes your apache conf is `/etc/apache2/sites-available/zoneminder.conf` - backs up the existing conf as `/etc/apache2/sites-available/zoneminder.conf.bak`:

```
URL=https://raw.githubusercontent.com/turnkeylinux-apps/zoneminder/master/overlay
LOCAL_PATH=etc/apache2/sites-available/zoneminder.conf
mv /$LOCAL_PATH /$LOCAL_PATH.bak 2>/dev/null || true
wget -O /$LOCAL_PATH $URL/$LOCAL_PATH
systemctl restart apache2
```

**Comment by ubeaut** [comment]
Hi,
The instructions that I followed have been corrected and everything now works.
There were quotes in the wrong position.
All good now.
And yes I am not using turnkey.
I didn't notice that this was in the turnkey/zoneminder support.

Thanks
