### ISSUE TITLE
Adminer not installed

### ISSUE THREAD

**Issue by noppel** [turnkeylinux/tracker#1624]
The documentation mentions adminer running on port 12322. However there is no icon on the main page and adminer ist not installed.
(Using proxmox, privileged container, nested=1)

**Comment by JedMeister** [comment]
Please note that this is our consolidated issue tracker. In future, for support please use our [forums](https://www.turnkeylinux.org/forum/support).

Which appliance is this? We have over 100, some have Adminer, others don't... It may be a bug in the documentation?

Given the info you've provided (privileged container with nesting enabled), assuming that it actually does contain Adminer, then it should work fine. You could test by launching an unprivileged container, in that use case, everything should "just work".

**Comment by JedMeister** [comment]
Any further info @noppel ?

**Comment by noppel** [comment]
I am sorry, I did not login for a long time. It is the samba or samba active directory. I think I managed without it.
