### ISSUE TITLE
Include dbus in core v18.0+

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1635]
We don't install `dbus` by default. The rationale behind that is that is (was) that `dbus` is a desktop messaging system and we provide servers.

However as systemd can use it (and does in some circumstance; e.g. services of type 'notify' and commands such as `hostnamectl`) and it becomes completely ubiquitous, we probably should reconsider that. It hasn't been a serious issue yet, but IMO it's probably only a matter of time...

As an additional info nugget; currently installing `dbus` isn't sufficent! There is a 'recommended' dependency that is needed in some circumstance but as we don't install 'recommends' by default, it needs to be manually installed. Unfortunately the name of that dep escapes me right now... 

(this issue started as a comment on another: https://github.com/turnkeylinux/tracker/issues/1361#issuecomment-892257110)

Also, I tagged it as a bug (as well as a feature) to ensure that it is considered at a fairly high priority...

**Comment by OnGle** [comment]
Why is this high priority? I'm removing the bug label and defering this to 17.1 (maybe later). 

Rational: Until we need dbus, we shouldn't install dbus.

If somebody feels differently you are welcome to post your rational here.

**Comment by JedMeister** [comment]
As I noted previously, it is becoming more ubiquitous and beyond `systemd-inhibit` there are a few other commands I've hit up against that don't work without it. `hostnamectl` is one we've discussed already (included below for completeness), but there are others (TBH, I'm not 100% sure that they are all dbus related - but they appear to be):

```
root@tkldev ~# hostnamectl
Failed to connect to bus: No such file or directory
root@tkldev ~# resolvectl status
sd_bus_open_system: No such file or directory
root@tkldev ~# wdctl       
wdctl: No default device is available.: No such file or directory
root@tkldev ~# loginctl
Failed to connect to bus: No such file or directory
root@tkldev ~# localectl
Failed to connect to bus: No such file or directory
root@tkldev ~# timedatectl
Failed to connect to bus: No such file or directory
root@tkldev ~# busctl
Failed to connect to bus: No such file or directory
```
Having said that, there does seem to be some sort of fallback (i.e. alternate command/workaround) for many (if not all) of those. As noted on #1467 `systemd-inhibit` is perhaps the only one that I'm not aware of a work around for...

Also I have read that services with `Type=notify` rely on dbus (although I can't find any info/confirmation right now?!).

**Comment by JedMeister** [comment]
Repinned this to v18.0 and it will definitely be included...

**Comment by JedMeister** [comment]
Closing as `dbus` is now being installed on v18.x.
