### ISSUE TITLE
Odoo TKL-Hub Unclear which version is installing

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1638]
Turnkeylinux.org indicates that TKL v16.1 is Odoo 14, while TKL v16.0 is Odoo 12. 
However in Hub.Turnkeylinux.org the Install choices are only 16.x and 15.x..

After an install it looks to be 16.0 (Odoo 12) but I don't know.

I think it would be far better to have a Matrix approach whereby
a:  TKL Version can be chosen  
and
b:  Odoo Version can be chosen

Minimally without that there should be a choice of TKL 16.0 vs 16.1 etc.
Personally I think it is a mistake to upgrade the Odoo Version to 14 with TKL 16.1.  Version 17 would be a more logical time to do so.

Finally, the Hub Install should also allow TKL 14.x to install.  Many people, including me, are running that version still.

Lots of "issues" here on the note.  Sorry about that.

**Comment by l-arnold** [comment]
Confirming that Hub version today installed 16.1 (with Odoo 14).  Had to compare to a Linode Install I just did with ISO from 16.0.

**Comment by JedMeister** [comment]
Yeah, you're right. It would be great if you could easily see exactly which TurnKey version is being launched. In fact it would be nice if you could choose which TurnKey version you launched (default to latest).

Or do you mean the version of Odoo? If so, that info (and the latest TurnKey version too) can be found on the website.
I.e. in this case, you can see the latest TurnKey version via the [Odoo appliance page](https://www.turnkeylinux.org/odoo). Note that says "v16.1" in the download links, plus further down it says "Stable version: 16.1". The version noted there should always match what is available in the Hub (other than when a new release is built; there is a very brief lag between when Alon loads the new builds to the Hub and I update the website).

Re the Odoo version included, if you then click the "[changelog](https://www.turnkeylinux.org/updates/odoo)" text link (next to where it says "Stable version: 16.1") you can see that v16.0 includes Odoo v12.x (~v12.0.20200604) and v16.1 includes Odoo v14.x (~v14.0.20210408). Having that info directly displayed within the Hub is probably unlikely, but we could have a link to the changelog on the website (to make it easier to get that info).

**Comment by l-arnold** [comment]
Just meant 16.x is unclear and wierd that you would change a 2x Odoo generations with a TKL change from 16.0 to 16.x.

Took a bit of time comparison but it is Odoo 14 which is currently installed on the hub.  No way to install Odoo 12 on the hub now, only Odoo 11 (TKL 15.x) or Odoo 14 (TKL 16.1).

Looking for some time to work on all of this.

Landis

Sent from Nine
________________________________

**Comment by JedMeister** [comment]
The Hub should always have the latest v16 release when launched from the Hub as '16.x'. In the case of Odoo then you get v16.1. Some appliances are up to v16.2 (hence our use of 16.x).

As for why we jumped from Odoo v12 to v14, I don't recall the exact rationale, but we did have a ton of requests for Odoo v14. Perhaps we need to work out some way of deciding which version you have at boot time somehow? Or even just have a separate appliance for each supported version? I'm not really sure what the best option is...

> [...] No way to install Odoo 12 on the hub now, only Odoo 11 (TKL 15.x) or Odoo 14 (TKL 16.1).

There is but it requires a bit of a commandline hack (you'll need shell access to a TurnKey appliance with internet access). I won't post it publicly, but get in touch if you want to try that. 

Alternatively, it's not very TurnKey, but you could re-install v12 if you wanted. Then you should be able to restore a TKLBAM backup of a v16.0 appliance to it.

**Comment by l-arnold** [comment]
Honestly the whole situation is impossible to navigate.  In an appliance like this app versioning (Odoo) needs its own stepping stone system.  Ideally a script that would allow movement from one level to another.

Meanwhile there have been a series of changes in the TKL system making it difficult to install in different ways as about half if the build tasks have been abandoned in new versions.

Everything seems focused on how easy it is to get a new generation turned out rather than how to move forward with your business data.

All that and the ethical part where I simply do not like working with Amazon.

**Comment by JedMeister** [comment]
Hi @l-arnold

>Honestly the whole situation is impossible to navigate. In an appliance like this app versioning (Odoo) needs its own stepping stone system. Ideally a script that would allow movement from one level to another.

I'm not sure that I understand. What you want should be possible but there isn't an easy way to automate it from our end that I'm aware of. You would need to do it yourself on your server via an SSH session.

Or do you mean as per a script to be able to change Odoo version?

>Meanwhile there have been a series of changes in the TKL system making it difficult to install in different ways as about half if the build tasks have been abandoned in new versions.

I'm not quite sure what you mean? We've been installing straight from the Odoo apt repository for quite a few years now. Any major changes would be related to the different Odoo versions themselves (which we have limited control over).

>Everything seems focused on how easy it is to get a new generation turned out rather than how to move forward with your business data.

Yes from what I can gather that does seem to be the way Odoo does things. Migration between versions is possible, but it's quite involved. There isn't an easy way to do that that I can see.

That whole situation causes an issue for us. It's not a super popular appliance, but existing users such as you often want to use older versions, whereas new users almost always want the latest version.

>All that and the ethical part where I simply do not like working with Amazon.

Yes, I'd love it if the Hub supported other cloud providers. Unfortunately I'm flat out just trying to provide support and keep up with Debian... Hopefully it might happen one day, but I have no idea when that might be.

**Comment by l-arnold** [comment]
Jeremy,
Sorry that I wrote in a "frustrated" mode.  There was no need for that.  I've fired up my TKLDEV environment. Perhaps I can get you and @DocCyblade  or others to jump in on a Odoo update.  Likely need help in putting a TKLDEV v17 in place a bit early.
I'd love to also get my Linode builds working again.  They stopped when Zen buildtaks were not updated.  Thinking can via a few tracks.  Just like you, time is a difficult commodity for sure.

**Comment by l-arnold** [comment]
We can close this.
Hub is giving a choice on the top bar of which version.  When an app is not available in a version, then it will not show, though that is not always noticable.  IE if you are looking at a V18 App, then you change to another App that is not available in V18, you can assume it is V18, but it is V17 that is selected.

You can always See once installed what version was installed in the instance information.
