### ISSUE TITLE
Odoo 14 - TKL 16.1 Database Error in Webmin

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1643]
Presently on a hub.turnkeylinux Server.
Just logged in to Webmin, clicked on PostgreSQL, then clicked on Turnkeylinux Example

I get the following error:  

> SQL select a.attname FROM pg_class c, pg_attribute a, pg_type t WHERE c.relname = 'pg_tables' and a.attnum > 0 and a.attrelid = c.oid and a.atttypid = t.oid and a.attname = 'schemaname' order by attnum failed : database "Turnkeylinux" does not exist

I do note that the link says "Turnkeylinux Example" while the Database error says "Turnkeylinux"

I expect this is the Odoo Test Database and is made to be either deleted or not used.
Likely one of the latest commits that I saw changing the name of the Example Database.

note for now.

**Comment by JedMeister** [comment]
Hi @l-arnold - apologies on slow response. We're currently trying to keep our heads down working on v17.0.

I have tagged this as an odoo bug and I'll double check when we do the v17.0 Odoo appliance.

**Comment by l-arnold** [comment]
Recent experience (a week or so now) is that after the 16.1 Install the Odoo system needs to be restarted in order to come up.  Perhaps could just restart the Odoo Service but a restart gets it going on a Hub Odoo 16.1 install.

**Comment by JedMeister** [comment]
I'm going to close this for now as it's quite an old issue and AFAIK it's not relevant to the v17.x appliances (please correct me if I'm wrong and it can be reopened).
