### ISSUE TITLE
There is a plan to implement servicedesk

### ISSUE THREAD

**Issue by charsit** [turnkeylinux/tracker#1649]
Hi, good day,
There is any plan to implement servicedesk [https://github.com/ladybirdweb/faveo-servicedesk-community](url) instead of helpdesk?

Thanks a lot in advance for your time.

Best regards

**Comment by JedMeister** [comment]
Hi @charsit,

It looks like it's no longer in development?! The repo is "archived" and the last release was nearly 3 years ago! So I doubt that we would include it in an appliance sorry.
