### ISSUE TITLE
New appliance: Bookstack

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1659]
Bookstack is a PHP wiki. I have built code: https://github.com/JedMeister/bookstack It is unfinished (IIRC it still needs inithooks) but is pretty close...

**Comment by OnGle** [comment]
I've got a few issues with the `validate_url` function in the inithooks of this new appliance:

link: https://github.com/JedMeister/bookstack/blob/3b60ae4cc13b4cf57e3dd5ec8f8bee0503a6f07f/overlay/usr/lib/inithooks/bin/bookstack.py#L30

```python3
def validate_url(url, interactive=True):
    try:
        schema, dom = url.split('//') #[1] [2]
    except ValueError:
        if interactive:
            return (False, "Must include schema and domain separated by '//'.")
        else:
            schema = 'https:'
            dom = url
    if schema != "https:" and schema != "http:": #[3]
        if interactive:
            return (False, "Schema must be 'https:' or 'http:'.")
        else:
            schema = 'https:'
    return ('//'.join([schema, dom.rstrip('/')]), None)
```

1. `//` isn't a the separator between scheme and host, `:` is. `//` is valid as part of the path at least as of rfc3986 (see https://datatracker.ietf.org/doc/html/rfc3986#section-3), technically `:` can appear in multiple places, and the `//` following the scheme isn't necessarily required for a valid url. All of this said, for our purposes checking for a single `://` is sufficient as it will match all valid urls with a scheme and host component.
2. regardless of separator you should only split once, as you are only unpacking 2 values, currently if the separator appears twice it will still produce a value error, but incorrectly assume the separator wasn't present at all. Try `url.split('//', 1)` instead to force it to only split once.
3. could be simplified to `if schema not in ('https:', 'http:'):`

I'd probably go with:

```python3
def validate_url(url, interactive=True):
    try:
        schema, dom = url.split('://', 1)
    except ValueError:
        if interactive:
            return (False, "Must include schema and domain separated by '//'.")
        else:
            schema = 'https'
            dom = url
    if schema not in ("https", "http"):
        if interactive:
            return (False, "Schema must be 'https' or 'http'.")
        else:
            schema = 'https'
    return (f'{schema}://{dom.rstrip("/")}', None)
```

**Comment by JedMeister** [comment]
Awesome, thanks @OnGle !

Here's the diff: https://github.com/JedMeister/bookstack/commit/fb314a18e603872dda89f690156c9015e1af047b

Or the complete file: https://github.com/JedMeister/bookstack/blob/master/overlay/usr/lib/inithooks/bin/bookstack.py
