### ISSUE TITLE
releases.turnkeylinux.org is down

### ISSUE THREAD

**Issue by benricok** [turnkeylinux/tracker#1665]
Hi, my proxmox host is trying to access https://releases.turnkeylinux.org/pve/aplinfo.dat.asc but I get a cloudflare error 521 response.

Is this site under maintenance or does it still exist?
(PS I recently updated my proxmox host so this link should still be relevant)

**Comment by Nibir** [comment]
archive.turnkeylinux.org:80 also down!

**Comment by JedMeister** [comment]
Thanks for the heads up! Apologies on the slow response. It's fixed (or at least is for me) now.

If you continue to have issues, please let me know.
