### ISSUE TITLE
Silence git warning about default 'master' branch.

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1673]
In v17.0 (Debian Bullseye) it seems that git still defaults to using 'master' but now gives a warning about it:
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
```

I suggest that we simply apply this setting (i.e. make `master` the default branch name) thus silencing this somewhat annoying warning.

**Comment by OnGle** [comment]
I disagree, this is none of our concern as developers.

We have a git policy and it makes absolutely no mention of the requirements of contributors git branch name scheme. If anybody feels strongly enough about this you are welcome to re-open, but note if you do so without providing a draft policy amendment for tkldev and tracker docs on gitflow, I will likely re-close.

**Comment by JedMeister** [comment]
@OnGle 

IMO this is just noise that pollutes the UI; at least it will be irrelevant to most users (many won't even know what git is), at worst confusing and concerning users for no good reason.

My personal opinion is that we should adopt previous default and document how to change it if desired.

Having said that, I don't feel strongly enough to push back against your decision this late in our 17.0RC dev cycle. However, I reserve the right to reopen it if we get many support requests regarding this.

**Comment by OnGle** [comment]
I'm re-opening this issue as I was missing a crucial bit of context: `git` is a dependency of `etckeeper` which is included in all appliances, meaning this is no longer a matter of setting defaults for developers, but also for all users. Most users either wont be using git on their server, don't even know what git is, or will expect the previous default behavior unless explicitly configured otherwise.

As a result of this additional information I'm inclined to agree with @JedMeister 

> My personal opinion is that we should adopt previous default and document how to change it if desired.

**Comment by OnGle** [comment]
I actually thought this was a different issue, referring to default conflict resolution behavior on `git pull` (`ff` vs `rebase`, etc.) But imo the reasoning is the same, and the resolution is the same for both issues.

**Comment by JedMeister** [comment]
@OnGle - good point. I actually though this issue was regarding default conflict resolution behaviour too! But I agree! :smile:
