### ISSUE TITLE
Odoo (TKL 16.1.1 ver) not booting from Hub

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1675]
Just tried to launch an instance from hub.turnkeylinux.

I noted that Odoo Admin and Odoo Database Master passwords were allowed to be different so I tried that.

Would not ever spin up though the hub thought it was running.

Just launched a second one keeping the passwords the same and it also did not launch at first.  After a reboot (and reassigning the tklapp.com host to it again, it did come up).

Thought you should know.  Worth another test to be sure.

**Comment by JedMeister** [comment]
Thanks Landis.

Could you please share which region you are launching into and what size server it was/is and I'll see if I can reproduce.

**Comment by l-arnold** [comment]
Hi Jeremy,
Recollection is Oregon.  Small size.

My second one was Oregon and I did need to reboot via the hub to get odoo to start.  That one had coordinated passwords.

**Comment by l-arnold** [comment]
Should be another Issue, but I will not here that I am also having difficulty with TKLBAM.  Just tried to move my data to a server in a different Hub Zone (from California to Oregon) and though TKLBAM thinks it restored well, I have no data other than the demo startup Odoo data in the new server post restore.

**Comment by l-arnold** [comment]
will report that separately.

**Comment by l-arnold** [comment]
From Webshell I ran turnkey-init again and was able to login to Odoo.
Was funny as It did not ask for a Odoo Admin User/   Just asked for Odoo Database Password.

Anyway,  seems they are connected for now.

**Comment by l-arnold** [comment]
Original issue.  Basically Odoo takes a Reboot and then approximately 1-2 minute wait for it to come up via Mapped IP.  TKLAPP.com setup at New Server Built coupled with Elastic IP is not working.
External Mapping is working.
I will watch to see that elastic IP stays mapped.  I believe it will.

**Comment by l-arnold** [comment]
Booting now.  Closing the issue.  Will reopen if issue reappears.
