### ISSUE TITLE
Flag TKL Support for OpenNebula Marketplace

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#168]
OpenNebula now supports TurnKey LXC builds via their Marketplace - website needs to be updated to note this.
----
It'd be great if TKL images could be available via the [OpenNebula Marketplace](http://marketplace.c12g.com/appliance).

TBH I haven't played with [OpenNebula](http://opennebula.org/) and/or their [marketplace](http://marketplace.c12g.com/appliance) so I am not completely clear on what the best course of action to achieve that ends would be and/or how much work it would require. Ideally it'd be great if TKL images were available in the 3 main formats supported by OpenNebula (currently KVM, Xen and VMware - OVZ support is also in development).

I'm not sure on the best approach to doing that - I guess it'd be best if TKL didn't need to host additional images just for the purpose of OpenNebula but I'm not clear on how or even if that is technically possible.

Some relevant references:
http://archives.opennebula.org/documentation:rel4.4:vm4market
https://support.opennebula.pro/entries/455869-Image-Contextualization
https://wiki.debian.org/OpenNebula/PreparingDebianVmImage

Note: I have tagged both Core and TKLDev as even if formal support for OpenNebula Marketplace was not done, a script/plugin/tklpatch (as per #161) on the creation of OpenNebula ready images in TKLDev could also be a very useful thing...
##

**Comment by JedMeister** [comment]
Current OpenNebula Docs:
http://docs.opennebula.org/5.0/operation/vm_setup/context_overview.html

**Comment by dann1** [comment]
There is a [recent integration](http://docs.opennebula.pro/5.8/marketplaces/turnkeylinux_marketplace.html) with OpenNebula. It is not including turnkey in the marketplace but making turnkey another available marketplace.

**Comment by JedMeister** [comment]
I've re-purposed this issue to now be about updating the website as OpenNebula now include TurnKey LXC builds in the Marketplace. 

As an issue hopefully this won't get forgotten amongst my overflowing todo list...

**Comment by dann1** [comment]
Hi there @JedMeister have you been able to check up on this ?

**Comment by JedMeister** [comment]
Hey @dann1 thanks for your patience and persistence. I'm still flat out with a mile long todo list (sort of my default position). But I just decided that this was one of those jobs that shouldn't really take too long and might be a good candidate to quickly clear an item from my list. So I just bit the bullet and spent half hour updating the TurnKey "[build types](https://www.turnkeylinux.org/docs/builds)" doc page. It's still not perfect, but at least it's documented now.

The only other thing that occurred to me is that the OpenNebula docs don't seem to support "latest" as a version (or perhaps I just missed how to do that). That means that the links I have included to your docs will always point to the OpenNebula v5.8 docs. It'd be nice if there were a way to always link to the latest version of the docs. As a workaround, I also added a link to the page source (on GitHub).

**Comment by dann1** [comment]
Thanks a lot for the effort on adding the links to OpenNebula. 

> the OpenNebula docs don't seem to support "latest" as a version

You can replace **5.8** for **stable** and it will point to the latest stable version of opennebula.

Please, let me know when you'll add the logo to [the Turnkey home page](https://www.turnkeylinux.org/)

![image](https://user-images.githubusercontent.com/16429804/65849697-3c78a700-e311-11e9-9e2f-44e49e58f5a3.png)

**Comment by JedMeister** [comment]
> You can replace 5.8 for stable and it will point to the latest stable version of opennebula.

Awesome, thanks. I've just updated the links to use that instead.

> Please, let me know when you add the logo to the Turnkey home page

Done. To make it consistent with the others, I made it black and shrunk it a bit. If you're unhappy with that, please feel free to provide an alternate similar sized logo (PNG with transparent background and logo in black (or black & white, grayscale is an option too although black/b&w is preferable).

I'll close this now that it's been added, but we can reopen if more is required.
