### ISSUE TITLE
Ghost cannot update

### ISSUE THREAD

**Issue by make-believe-agency** [turnkeylinux/tracker#1687]
Ghost cannot update following instructions provided, permissions errors are given.

**Comment by JedMeister** [comment]
Do you mean the instruction on the [Ghost appliance page](https://www.turnkeylinux.org/ghost)?

If so, that's not great! I did update them relatively recently following detailed discussion on our [forums](https://www.turnkeylinux.org/forum/support/mon-20211206-2038/updating-ghost-not-working). Perhaps I missed something or made a mistake?! Could you please have a look at those instructions / that forum thread and let me know how you go?

I'm going to close this for now, but if you continue to have issues, please feel free to respond on that forum thread; or start your own. You could also respond herer if you prefer, but I monitor the forums most closely.
