### ISSUE TITLE
Unable to fetch from archive.turnkeylinux.org

### ISSUE THREAD

**Issue by RyanStav1994** [turnkeylinux/tracker#1688]
Hello, with any turnkey template i try to install the installer never triggers the actual install and get this error instead. 
![image](https://user-images.githubusercontent.com/48797919/147563207-a0d875d0-7d6a-4bf5-adad-c1d3cb1206ec.png)

Is the archive down at the moment?

**Comment by JedMeister** [comment]
Looks like your server isn't getting an internet connection?! If you're sure that it should have a connection, then my guess is that you're installing to hardware and your NIC requires a non-free driver!?

Can you share a bit more info about where you are installing and how. If it's hardware as I suspect, can you please share as much info as you can about the hardware (e.g. motherboard/PC/server/laptop brand and model). If I'm wrong and you're installing to a VM, perhaps try a different virtual NIC.

Regardless, the resolution is to complete the install and then install the required driver. Once that's done, you should get internet and can run the updates as noted.

Armed with more info about the hardware (or VM platform) I can assist you with more specifics.

As this seems likely to be more of a support item, than a bug (this is our bug/feature request tracker) then I'm going to close this. Ideally please open a thread on our [support forums](https://www.turnkeylinux.org/forum/support) (starting a new thread requires free website user account). Feel free to share a link to this so you don't need to repeat yourself, just supply the additional info. You can just reply here if you prefer, but I monitor the forums more closely, so you'll likely get a quicker response over there.
