### ISSUE TITLE
Nextcloud Update Wrapper

### ISSUE THREAD

**Issue by BadCo-NZ** [turnkeylinux/tracker#1691]
As discussed with Jeremy in this thread (https://www.turnkeylinux.org/comment/50698#comment-50698) I have opened this issue to request an update wrapper for the Nextcloud TKL.

Currently my command to update (after much faffing around to find it) is:
`su - -s /bin/bash  www-data -c 'php /var/www/nextcloud/updater/updater.phar'`

Something similar to the OCC wrapper would be super handy:
`turnkey-php updater.phar`

Thanks for the work you guys do, and looking forward to v17!

**Comment by JedMeister** [comment]
We've implemented the [`turnkey-php`](https://github.com/turnkeylinux/common/blob/18.x/overlays/php/usr/local/bin/turnkey-php) helper/wrapper script. It will be included in all v18.0 apps that include PHP by default.

It's not quite what you asked for, but hopefully it's close enough. By default it runs in `/var/www` so the Nextcloud Update command will be:
```
turnkey-php nextcloud/updater/updater.phar
```
I'm going to close this now, but after testing in v18.0 (once we release it) if you want more, please feel free to reopen or open a new issue.

**Comment by BadCo-NZ** [comment]
Nice work @JedMeister, it is certainly an improvement on my original command
