### ISSUE TITLE
General question about login

### ISSUE THREAD

**Issue by user-funky** [turnkeylinux/tracker#1697]
Hi there! 
I tried to login quickly to your TurnKey WordPress, but I failed... Well, when I turned on the machine, Debian asked me for "wordpress login: " - I tried many different names to login, but  I can't (e.g. admin) - can you help me with that? THX.
Stay in touch

**Comment by JedMeister** [comment]
Hi @user-funky,

First up, this is our issue tracker, for verified bugs and feature requests. For support issues, please use the [TurnKey forums](https://www.turnkeylinux.org/forum/support).

When you do post, please be a bit more explicit about the problem you are having and how you got to where you are. Knowing where your TurnKey server is running and/or how you installed it is often valuable info for those trying to assist. As a general rule, you can never really provide too much info when seeking support. If you provide "too much" info, those knowledgeable will know what is irrelevant and can be glossed over. But it's impossible to glean info that you haven't provided!

In the case of your question, I'm not completely clear, but it sounds like you might be trying to log into a local terminal? If so, then as noted on the [WordPress appliance page](https://www.turnkeylinux.org/wordpress) the username is `root` and uses the root password set at firstboot.
