### ISSUE TITLE
Hostname not correct for all URLs

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#17]
Reported on [lp#1158017](https://bugs.launchpad.net/turnkeylinux/+bug/1158017) by ``John Peterson`` on 2013-03-21

#### Description

Here is the process:

Restore from Backup

* Navigate to TurnKey Hub Login.
* Enter login information.
* Under the TurnKey Cloud Servers group select the Servers Dashboard link.
* Click on the website which you want to copy. This will expand out all of the options for that website.
* To the right there will be a row called Backups. Click on the On link next to Backups.
* The backup options and info will now be listed. Select the link, Restore this backup to a new cloud server.
* This will launch the Launch to Amazon EC2 dialog. Make sure the values are as follows:
    * TurnKey Appliance: WordPress
    * Region: Virginia East (USA)
    * Size: Micro
    * Type: This option is not valid for Micro instances
    * Backup to restore: Leave the default value.
    * Hostname: Either "staging", "development", or "testing" using the same domain name as before. For example, if you copied www.develare.com then select the develare.com domain.

Configure Copied Server

* Copy the wp-config.php file used on the production server. This will be the wp-config.php file that you use for the copied server. * Feel free to move to a directory that makes sense for you.
* Open the copied wp-config.php file. Make sure the WP_HOME and WP_SITEURL options defined in the file point to the hostname used when configuring the Amazon EC2 instance. Common values are similar to: http://staging.develare.com or http://development.develare.com.
* Upload the file to the appropriate folder on the copied server.
* Upload a robots.txt file to the copied server that blocks all bots from crawling the site. This will prevent the copied server from being indexed by Google and other search engines.
* Login via SSH to the copied server.
* Run the commands following commands via SSH:

```
chown -R www-data:www-data /var/www/wordpress/
# Remove TurnKey Linux Footer CSS
mv /etc/apache2/mods-enabled/substitute.conf /etc/apache2/mods-enabled/substitute.original
touch /etc/apache2/mods-enabled/substitute.conf
/etc/init.d/apache2 restart

# Get packages for...
apt-get -y install zip unzip # BackupBuddy
apt-get -y install php5-curl # Google Analyticator
/etc/init.d/apache2 restart

# Setup TurnKey Linux backup and daily backup task
chmod +x /etc/cron.daily/tklbam-backup
tklbam-backup
```

After this procedure is formed there is a copy of the production server. This is very handy for creating quick staging servers. However, the problem is not all of the URLs are changed from "www.hammondiles.com" to "staging.hammondiles.com". This can be seen if you look at the source code for the website. It seems like the URLs that are generated by WordPress are fine, but those for CSS and HTML are not. I looked in the hostname file, and poked around on the server, but I'm not sure why this is occurring.

**Comment by JedMeister** [comment]
This bug is so old and we have not had any further comment on it so I am closing this now.

If anyone disagrees please feel free to reopen although further and more up to date info would be really appreciated. Thanks
