### ISSUE TITLE
New Joomla 4x appliance - plus keep Joomla 3x

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1704]
Joomla 4 is now very much up and running.

TKL Applicances, since I recall, 2.5 have been tagged to specific build generations:
1 x
2.5 x
3 x

Likely want to add a 4 x one now to the TKL Library
4 x
https://www.joomla.org/4/

Not sure if there is an easy upgrade path.

**Comment by JedMeister** [comment]
Great thanks @l-arnold. I was aware that v4.0 was getting close but good to hear that it's been released.

My plan is to add a new `joomla4` TurnKey appliance but also continue to provide a `joomla3` appliance (while Joomla 3 is supported). That way any new users can start with Joomla4, bu existing users (who haven't yet updated) will be able to get going quickly.

**Comment by JedMeister** [comment]
This was handled in v17.0: https://www.turnkeylinux.org/joomla4
