### ISSUE TITLE
TKLDev 17rc1  to Core product.iso and subsequent install

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1708]
I thought my TKL Odoo generated a good ISO, but was not able to mount it subseuently in Linode.
Decided to try Core that is in TKLDev 17rc1.

Mounted the ISO to a new Drive Image and booted.
Issues were as follows:

Partition using the Whole Disk (had a 5.2gb disk to write to) was swapping Primary and Swap recomended sizes.   So was suggesting partitions of 4.2gb for swap/swap and 1 gb for primary.  With some difficulty I was able to swap the intended usage of each disc in the partitioner but do not want to do that again.  Quite difficult to navigate.

first Root Password entry box is overwritten by some "Ok" button.  Was able to type in - shot input text to the right and then do the confirm,, so got through that, but is not happening in TKL 16 installs.

The Partitioning subject outlined above is the "Big Deal".  Somehow the logic is swapped in the Automatic Partitioning suggestion and it is not easy to simply over write the sizes...  though I am going to explore manual partitioning some more having worked through that.

Odoo cloned from [TKLApps](https://github.com/turnkeylinux-apps/odoo) did generate an ISO no problem but I was unable to ever mount that ISO as I did with Core outlined here.  Likely some old code in the chain pointing to TKL 16.1 build method even though was built with TKLDev 17rc1.

**Comment by l-arnold** [comment]
Following up.  Worked more on the Odoo install generated from TKLDEV 17rc1.  Several strange things, but twice now when it really should boot post install I am getting 

XZ - compressed data is corrupt
Has happened on 2 different installs.  It seemed to be loading Swap and Primary partitions correctly prior (unlike on Core 17rc1 referenced above)...  but does not complete.

I can try a TKLDEV build next as that (may) be cloneable in TKL 17rc1.  Not sure about that though.

**Comment by JedMeister** [comment]
@l-arnold - I have rolled back the changes that I made to support UEFI boot (which I suspect may be your issue). To ensure that you have the correct code on your TKLDev, install the lastest fab and pull the latest cdroots code. I.e.:
```
# update fab to the latest version
apt update
apt install -y fab

# update cdroots to the latest code
cd cdroots
# assuming that the git repo is in default state
git pull origin master
```

**Comment by l-arnold** [comment]
Ok.  Thank you Jeremy.  Will dive back in again soon.
