### ISSUE TITLE
"fab --version" not implemented

### ISSUE THREAD

**Issue by heneault** [turnkeylinux/tracker#1715]
The option --version for fab CLI seems to have been lost. This is something used at least by the generate-buildenv buildtask.

**Comment by JedMeister** [comment]
Good find. I'll fix that ASAP!

In the meantime, IIRC the version check was because there was a specific feature that was needed from a newer version of fab (but it shouldn't matter anymore).

**Comment by JedMeister** [comment]
I have added support for `-v`|`--version` to (plus some other general tidy up of) `fab`. I'm not sure when I'll rebuild it (soon hopefully) but in the meantime, you can download the updated `fab` executable like this:

```
wget -O /usr/bin/fab https://raw.githubusercontent.com/JedMeister/fab/support-version/fab
```

**Comment by heneault** [comment]
Thank you!
