### ISSUE TITLE
Github Issue  (Odoo does not show in Search)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#1728]
Very strangly, when one is on Github under turnkeylinux-apps
then search "odoo"  it does not show up.
https://github.com/search?q=org%3Aturnkeylinux-apps+odoo&type=Repositories&ref=advsearch&l=&l=

The link from the TKL website does land you where you need to go:
https://github.com/turnkeylinux-apps/odoo

Might be some other apps not searchable as well.

**Comment by JedMeister** [comment]
Looks like a GitHub bug (good luck reporting it, let alone getting it fixed).

FWIW it works if you first browse to the `turnkeylinux-apps` [repository page](https://github.com/orgs/turnkeylinux-apps/repositories) (to get there, first go to the `turnkeylinux-apps` ["organisation" page](https://github.com/turnkeylinux-apps) then click the 'repositories' tab). Then type 'odoo' in the search box there. For me, it's the only result. Or your workaround (i.e. following the link from our website) is another valid workaround.
