### ISSUE TITLE
WordPress doesn't allow internal update/install (including themes and plugins)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#173]
It has commonly reported in the forums that there are issues with installing updates, plugins and themes in the TKL WordPress appliance.

This may well be keep security tight, however the common workaround is to simply give the webserver (www-data) ownership of the whole /var/www/wordpress directory tree which IMO defeats any advantage that may be obtained by the initial config.

So to balance OOTB user experience with security I propose that we give the webserver ownership of the /var/www/wordpress/wp-content/ folder tree thus allowing (minor) updates and installation of WP itself, plugins and themes. I intend to create a patch and pull request, but in the meantime (until a new appliance is released) here is the workaround:

````
chown -R www-data:www-data /var/www/wordpress/wp-content
````

Also you need to add an entry to the `wp-config.php` file:
````
define('FS_METHOD', 'direct');
````

Note: ensure that it goes <strong>above</strong> the line:
````
/* That's all, stop editing! Happy blogging. */
````

Also, I'm not sure if it's required, but I like to restart Apache to be sure:
````
service apache2 restart
````

I guess it could be argued that this is a feature request, however I have decided to mark it as a bug (considering the amount of times this comes up as an issue...)

**Comment by JedMeister** [comment]
@extremelabs - For sure - unfortunately security isn't a yes/no; on/off type problem... It involves compromises and choices that are made have consequences. If you want maximum security for your server, then remove any networking and encase it in concrete... Totally secure, but also totally useless...! 

What are your thoughts on the suggests approaches? Which would work best for you?

**Comment by jeroenpeters1986** [comment]
Well, there might be a solution. The WP Codex at http://codex.wordpress.org/Editing_wp-config.php (Find FS_METHOD) say that http://wordpress.org/extend/plugins/ssh-sftp-updater-support/ might provide a solution. I'm going to explore that in my TKLDev for WP

**Comment by jeroenpeters1986** [comment]
I think I fixed it in my TKLDev for WP. I have to upload the code in my fork of turnkeylinux-apps/wordpress. 
@JedMeister  How do we proceed? I bet you would want to check out my code and test it for yourself?

**Comment by JedMeister** [comment]
@jeroenpeters1986 - That may be the best way forward. Then we have the convenience of in browser updates and the security of most of the directory tree not being owned by Apache. 

My only concern is that if there is a security breach and Apache gets hacked; does the attacker then have root shell access (via credentials saved via this WP plugin)?

**Comment by jeroenpeters1986** [comment]
@JedMeister - I was hoping you could assess that last point for me. I am not completely sure I can do that on my own. 

At this moment I am building the latest version of the appliance with my repository-fork just to check if everything is allright. 

The base/core indicates apache2-mpm-prefork as installed webserver, together with a new directive in the `wp-config.php` that seems to have done the trick. I'll let you know when I've tested the appliance

**Comment by jeroenpeters1986** [comment]
On my TKL-wordpress machine at my hostingprovider I also had issues uploading new media. That's resolved in my new iso-image too. Tested installing some plugins and themes from the wordpress repo. Works like a charm. One thing left to do, install an old version and let it update.

**Comment by jeroenpeters1986** [comment]
Works like a charm 

```Downloading update from https://downloads.wordpress.org/plugin/wordfence.5.3.6.zip…
Unpacking the update…
Installing the latest version…
Removing the old version of the plugin…
Plugin updated successfully.
```

I will be making a pull-request

**Comment by jeroenpeters1986** [comment]
@JedMeister the pullrequest was created

**Comment by JedMeister** [comment]
Great work - Thanks @jeroenpeters1986

@alonswartz should be processing pull requests within the next week or 2.

**Comment by jeroenpeters1986** [comment]
Thank you for the clarification @JedMeister  :) I'll be waiting

**Comment by JedMeister** [comment]
Closing now to to merged code from @jeroenpeters1986 :smile:

**Comment by jeroenpeters1986** [comment]
@JedMeister is there anything I can do for you guys to get this out as a release for TKL? That way, my hostingprovider can update the ISO as well and the new VPSes will be all userfriendly :)

**Comment by JedMeister** [comment]
Hey @jeroenpeters1986. Sorry about the hold up.

Actually there is a lot you could potentially do... I've had a thought - could you please email me : jeremy AT turnkeylinux.org

**Comment by jeroenpeters1986** [comment]
Thanks @JedMeister, you have mail :)

**Comment by JedMeister** [comment]
@jeroenpeters1986 :+1: Read & replied! :smile:
