### ISSUE TITLE
LFS Problem

### ISSUE THREAD

**Issue by 3th3r** [turnkeylinux/tracker#1738]
Can't push anything, LFS do not work. Due to a badly setup reverse proxy. 
Impossible to find any ressource on how to increase the body size....

**Comment by JedMeister** [comment]
What does not work on what? Where? What reverse proxy are you referring to? What body size do you want to increase? With 10 years of producing "software appliances" and over 100 different appliances currently available, I have no idea where to even start providing some sort of useful reply...

FWIW for support queries, ideally we prefer use of our [forums](https://www.turnkeylinux.org/forum) (and reserve "GitHub issues" for confirmed bugs and/or feature requests).

I'm closing for now, but if you can provide some details so I have some idea of what you're talking about,
