### ISSUE TITLE
Cant enter with user

### ISSUE THREAD

**Issue by mandycuba** [turnkeylinux/tracker#1740]
Hi, After install the media server in Ubuntu Container  i cant login in webui... i dont know the user..  i try with root, but not.. can helpme?

**Comment by JedMeister** [comment]
Please note that this is our issue tracker; for tracking bugs and feature requests. Support is best handled on our [forums](https://www.turnkeylinux.org/forum). So I'll close this issue for now.

Regardless, are you referring to our [Media server appliance](https://www.turnkeylinux.org/mediaserver)? If so, then the usernames for the various interfaces are as noted.

If I've misunderstood and not answered your question, please provide some more details.
