### ISSUE TITLE
snipe-it lxc proxmox pptp problem

### ISSUE THREAD

**Issue by PAOK1926** [turnkeylinux/tracker#1741]
hello, 

i just installed snipe-it as lxc on my proxmox server.
everything seems to work fine, except, i cannot add a pptp tunel to my vpn server.
when i try to initiate the pptp connection, i get this message:
```
Couldn't open the /dev/ppp device: Permission denied
/usr/sbin/pppd: Sorry - this system lacks PPP kernel support

```

is this true ? this system lacks PPP kernel support ?

**Comment by JedMeister** [comment]
Hi there,

This is a limitation of running in an unprivileged LXC container.

To work around it, you have 3 options:
- run the container as privileged (and deal with all the bugs and issues that will bring)
- download the ISO instead (from the [Snipe-IT page](https://www.turnkeylinux.org/snipe-it) on our website and install to a "proper" VM; or
- (probably the most relevant option) explicitly set up the required resources/permissions.

Assuming that you are using Proxmox, here is a thread that seems related to the 3rd option I noted:
https://forum.proxmox.com/threads/ppp-on-multiple-containers-not-working.54714/

If you're not using Proxmox and/or you want more general LXC info, please have a look at these:
https://discuss.linuxcontainers.org/t/lxc-allow-openfortivpn-client-to-create-a-ppp0-interface/3048/2
https://discuss.linuxcontainers.org/t/dev-ppp-in-lxc-permission-denied/8326

If you work it out, please post back as I'm sure it will help others.

**Comment by JedMeister** [comment]
I'm closing this now as there's not really anything we can do about it.

If you worked it out @PAOK1926 - please still free to post back with instructions.
