### ISSUE TITLE
www.turnkeylinux.org loads slow or even can't load

### ISSUE THREAD

**Issue by MrCatEsq** [turnkeylinux/tracker#1742]
Very often the Turnkeylinux website and forum are unreacheable. I can see error 524 and some else. The rest of the time the site loads very very slowly. 

The website fails Yellow Labs [check](https://yellowlab.tools/queue/gb6s3evmwm).

Google Page Speed Insights [tool](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.turnkeylinux.org%2F) even can't load the website to start analyse.

**Comment by nazgulsenpai** [comment]
Same here, and same for the 2-3 friends I've had try too from non-US ISPs. I noticed the issue initially 2 days ago.

**Comment by JedMeister** [comment]
As you note the TurnKey site is experiencing issues. I've basically run out of ideas (I've made tons of tweaks and many of them appeared to improve things, but performance keeps degrading). I suspect that there is actually an underlying hardware issue.

I am currently working on migrating the site to a new server. Hopefully it should be back up within the next day or so.

Apologies on the inconvenience and thanks for your patience.

In the meantime you can access the content (docs, forum posts, etc) via [archive.org](https://web.archive.org/web/20220626013717/https://www.turnkeylinux.org/) (note you won't be able to sign in or post new content).

**Comment by Stoidis** [comment]
@JedMeister found this post incidentally as I was preparing to reply in the partnership e-mail. Let me check what we can do in MassiveGRID about hosting. Maybe we can host and support turnkeylinux for free.

**Comment by JedMeister** [comment]
@MrCatEsq @nazgulsenpai - In case you haven't noticed, the website is back up and (mostly) working as well, if not better than it did before. There are still a few issues that I'm working on (mostly PHP warnings for the newer PHP version) but hopefully will have all them done shortly.

@Stoidis - Thanks for your kind offer. Let's touch base via email and perhaps look to organise a voice chat sometime soon? I'm pretty under the pump at the moment, but should be able to fit a brief voice chat sometime soon.

**Comment by JedMeister** [comment]
I
