### ISSUE TITLE
login, registration, unable to download anything

### ISSUE THREAD

**Issue by ttwsyf-dev** [turnkeylinux/tracker#1744]
Hi I have been unable to login to my account. When I request a new password it never arrives in my registered email address. If I try to re-register the site tells me that email address is already in use. I have also been unable to download any isos, vmdk files or anything like that. Also I went through the process of _trying_ to register with AWS and set up a turnkeyhub profile, etc. It took an extremely long time and I don't think I ever got it right. I do realise that AWS has a habit of changing everything without warning but the TurnkeyLinux docs to tell you how to do it were very very far from the way AWS is currently set up. Why do you have to regtister with AWS anyway? I would really have preferred not to. I also realise that Turnkey has recently rebuilt their website and was offline for at least a week or so that I know of. I realise that the registration screen at Turnkey says something at the bottom like "in short be nice". I'm trying my best. However, I would be being very dishonest if I did not point out that _I am_ extremely frustrated. I would prefer Turnkey to have my email address to respond to this but I can't see how to do that here without broadcasting it to the world. I'm sure I'm missing something. However, I will periodically check back. Thanks very much in advance for any possible resolution. Best regards, Mike

**Comment by thelynx77** [comment]
I also cant register or downloadf anything... the email its says has further details never arrives

**Comment by JedMeister** [comment]
Thanks for reporting the issue(s).

I was already aware of the email problem. If you both check your spam folders, you might find them there? FYI, I tested with a gmail account and the registration confirmation email was in spam. Some mail providers will just silently block it though. I hope to have that resolved soon but can't give an ETA.

In the meantime, I can manually approve accounts - shoot me an email.

Regarding the broken download links, I wasn't aware of that! So thanks tons for reporting. :+1: I've just confirmed it myself. We've been having some website issues lately and after migrating to a new server, I've done some PHP tweaks to quieten down the logs. Obviously, I've introduced a bug that slipped passed my ad hoc testing!

I'll look at that ASAP. FYI, it looks like its not including the app name in the download URL. E.g. the LAMP link should be `https://www.turnkeylinux.org/download?file=turnkey-lamp-17.1-bullseye-amd64.iso` (but the `lamp` is missing).

Until I resolve the issue, you can either manually tweak the download url to include the appliance name or browse the [mirror directly](http://mirror.turnkeylinux.org/turnkeylinux/images/iso/).

**Comment by JedMeister** [comment]
I'm pretty sure that I've fixed the download links now. Please let me know if you continue to have issues downloading.

The emailing issue is still outstanding. I'll get onto that ASAP but I'm currently blocked as i don't currently have access to our mailserver.

**Comment by JedMeister** [comment]
Download links are confirmed fixed.

I'll also note that posting in the forums is still problematic. And emailing still isn't working properly. I have access to the mailserver now but still can't get it working. I might get someone else to have a look at that, because I can't work it out...

**Comment by paulforbing** [comment]
Is this an ongoing issue? I've attempted to register with two separate emails and haven't received any confirmation/instructions emails.

**Comment by paulforbing** [comment]
I'm unable to register on the website. (https://www.turnkeylinux.org/) Is that what this issue is highlighting? I've attempted with two different emails and just don't receive a follow-up. If there is another place I should be reporting this please let me know.

**Comment by JedMeister** [comment]
@paulforbing - yes it is. Apologies that it's taking so long. I have recently received some additional info which hopefully will allow me to resolve this by week's end. Fingers crossed, it will be working again really soon. Although unfortunately, I can't 100% guarantee that. I'll try to post back explicitly either way.

In the meantime, please feel free to email me (check my profile) and I can manually enable your account.

**Comment by paulforbing** [comment]
Thank you @JedMeister . I will email you today. I appreciate it.

**Comment by JedMeister** [comment]
Apologies on my slow response. I've just enabled your account @paulforbing (assuming that you're the same Paul who's email I just replied to).

We have a PHP/Drupal expert on the job trying to fix up the website and have already identified a problematic (anti-spam related) module (that was causing timeouts when creating new posts). That is now disabled, so posting should work ok now. I'm hoping that we may be able to fix the module and continue using it. Although we may need to rethink things and one possible option is implementing "CAPTCHA" for new and unauthenticated (i.e. not logged in) user posts.

Unfortunately, the mailserver still isn't working as it should... I'm hoping that further discussions with my colleague (in our meeting scheduled for later today) might bring something to light that I've overlooked, or perhaps a work around I haven't considered. I'll try to keep this thread up to date as new info comes to light.

Hopefully we can get things back to "normal" so I can get back to the v17.x release!

**Comment by JedMeister** [comment]
I'm going to shut this issue now. Whilst the website is still far from perfect, it's working as well as it has for a while now. Behind the scenes we are looking at options for a major rebuild/refresh of our website (whether or not we change the appearance yet or not remains to be seen, but the background technologies will be changed - probably radically).
