### ISSUE TITLE
Update Gitea's nginx config to support large git pushes

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1747]
A user recently reported on support that our Gitea appliance currentl;y doesn't support large pushes. To resolve that:

>update gitea's nginx config to have `ngx_http_core_module 50m;` to support large git pushes.

We should do that for the next release.

**Comment by SamSirry** [comment]
Yes, in deed. I found that adding `client_max_body_size 0;` (or some other large value in place of `0`) in `/etc/nginx/sites-enabled/gitea` achieves this.

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/gitea/pull/7
