### ISSUE TITLE
NFS Server does not work (Fileserver LXC on Proxmox)

### ISSUE THREAD

**Issue by DerDoubleD** [turnkeylinux/tracker#1750]
Hello,

Can someone help me please?!
Installed under proxmox 7.2 lxc

Webmin
`rpc.nfsd: no process found
Stopping nfs-kernel-server (via systemctl): nfs-kernel-server.service.
Starting nfs-kernel-server (via systemctl): nfs-kernel-server.serviceA dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
 failed!`

Shell
`root@TurnkeyFS ~# systemctl start nfs-server.service
A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.`

Shell
`root@TurnkeyFS ~# journalctl -xe
Aug 19 20:02:25 TurnkeyFS stunnel[230]: LOG5[584]: Connection closed: 648 byte(s) sent to TLS, 635 byte(s) sent to socket
Aug 19 20:02:28 TurnkeyFS stunnel[230]: LOG5[585]: Service [webmin] accepted connection from 192.168.0.118:6466
Aug 19 20:02:28 TurnkeyFS stunnel[230]: LOG5[585]: s_connect: connected 127.0.0.1:10000
Aug 19 20:02:28 TurnkeyFS stunnel[230]: LOG5[585]: Service [webmin] connected remote server from 127.0.0.1:48338
Aug 19 20:02:29 TurnkeyFS stunnel[230]: LOG3[585]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing`

**Comment by JedMeister** [comment]
Do you have the NFS package (`nfs-kernel-server`) installed on your Proxmox host? If not, then you'll need to do that. Hopefully it should "just work" once you've done that.

FYI LXC containers leverage the host's kernel - so for any service which requires a kernel module (such as NFS), the host must have the required module installed and enabled. In the case of NFS, simply installing the `nfs-kernel-server` package should be sufficient.

**Comment by DerDoubleD** [comment]
> Do you have the NFS package (`nfs-kernel-server`) installed on your Proxmox host? If not, then you'll need to do that. Hopefully it should "just work" once you've done that.
> 
> FYI LXC containers leverage the host's kernel - so for any service which requires a kernel module (such as NFS), the host must have the required module installed and enabled. In the case of NFS, simply installing the `nfs-kernel-server` package should be sufficient.

Thnaks for you Answer.
Unfortunately it still doesn't work

in proxmox host the NFS package is installed an running.
`root@proxmox:~# systemctl status nfs-server.service
● nfs-server.service - NFS server and services
     Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
     Active: active (exited) since Tue 2022-08-23 07:14:11 CEST; 3min 3s ago
    Process: 189527 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
    Process: 189528 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
   Main PID: 189528 (code=exited, status=0/SUCCESS)
        CPU: 4ms

Aug 23 07:14:10 proxmox systemd[1]: Starting NFS server and services...
Aug 23 07:14:11 proxmox systemd[1]: Finished NFS server and services.`

in lxc FileServer
`systemctl status nfs-kernel-server.service 
* nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Aug 23 07:15:21 TurnkeyFS systemd[1]: Dependency failed for NFS server and services.
Aug 23 07:15:21 TurnkeyFS systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.`

`root@TurnkeyFS ~# journalctl -xe
Aug 23 07:22:35 TurnkeyFS systemd[1]: Dependency failed for RPC security service for NFS server.
-- Subject: A start job for unit rpc-svcgssd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit rpc-svcgssd.service has finished with a failure.
-- 
-- The job identifier is 462 and the job result is dependency.
Aug 23 07:22:35 TurnkeyFS systemd[1]: rpc-svcgssd.service: Job rpc-svcgssd.service/start failed with result 'dependency'.
Aug 23 07:22:35 TurnkeyFS systemd[1]: Dependency failed for RPC security service for NFS client and server.
-- Subject: A start job for unit rpc-gssd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit rpc-gssd.service has finished with a failure.
-- 
-- The job identifier is 466 and the job result is dependency.`

**Comment by JedMeister** [comment]
Hmmm, I've just done some searching and it appears that it may be harder to get an NFS server running as a LXC container than I assumed. I didn't realise, but it appears that NFS is particularly tricky to do within modern LXC.

I can't confirm it works, but I did find a relatively recently published [blog post](https://virtualizeeverything.com/2022/06/14/nfs-server-in-proxmox-ct-lxc-container/) that claims to explain how it can be done.

Please post back if you try that and let me know how you go. Good luck!

**Comment by marcos-mendez** [comment]
> Hmmm, I've just done some searching and it appears that it may be harder to get an NFS server running as a LXC container than I assumed. I didn't realise, but it appears that NFS is particularly tricky to do within modern LXC.
> 
> I can't confirm it works, but I did find a relatively recently published [blog post](https://virtualizeeverything.com/2022/06/14/nfs-server-in-proxmox-ct-lxc-container/) that claims to explain how it can be done.
> 
> Please post back if you try that and let me know how you go. Good luck!

@JedMeister this is smelling like a unprivileged container problem, NFS must be done the other way. Have the FileServer working just fine here, latest version. 

Maybe @DerDoubleD try to boot the fileserver.iso image from here in a VM instead of an LXC it would be much more saffer and you wont loose much performance as is just object storage. Really recommend CephServer SSDs for the job as the best practices recommend

**Comment by JedMeister** [comment]
Thanks for your input @marcos-mendez.

I'm going to close this then. We never heard back from @DerDoubleD and the doc I linked to above suggests it' possible, confirmed by your experience.

**Comment by DerDoubleD** [comment]
The tip with the entry in /etc/pve/lxc/xxx.conf helped.
lxc.apparmor.profile: unconfined 
Thanks very much!!!

**Comment by JedMeister** [comment]
Fantastic news @DerDoubleD - thanks for posting back to confirm.

**Comment by 100730088** [comment]
now,2023-08-04,debian-11-turnkey-fileserver_17.1-1_amd64.tar.gz.
NFS exports
Errot
rpc.nfsd: no process found
Stopping nfs-kernel-server (via systemctl): nfs-kernel-server.service.
Starting nfs-kernel-server (via systemctl): nfs-kernel-server.serviceA dependency job for nfs-server.service failed. See 'journalctl -xe' for details.
failed!

**Comment by marcos-mendez** [comment]
What is the output of journalcto -xe?


Em sex., 4 de ago. de 2023 03:47, lyuchen ***@***.***>
escreveu:

**Comment by Yur-ok** [comment]
> now,2023-08-04,debian-11-turnkey-fileserver_17.1-1_amd64.tar.gz. NFS exports Errot rpc.nfsd: no process found Stopping nfs-kernel-server (via systemctl): nfs-kernel-server.service. Starting nfs-kernel-server (via systemctl): nfs-kernel-server.serviceA dependency job for nfs-server.service failed. See 'journalctl -xe' for details. failed!

I have the same issue!

this is my output from journalctl -xe
`

- May 04 10:19:34 torr stunnel[238]: LOG5[44]: Service [webmin] accepted connection from 192.168.0.31:52500
- May 04 10:19:34 torr stunnel[238]: LOG3[44]: SSL_accept: ../ssl/record/rec_layer_s3.c:1562: error:14094416:SSL routines:ssl3_read_by>
- May 04 10:19:34 torr stunnel[238]: LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
- May 04 10:19:34 torr stunnel[238]: LOG5[45]: Service [webmin] accepted connection from 192.168.0.31:52504
- May 04 10:19:34 torr stunnel[238]: LOG5[45]: s_connect: connected 127.0.0.1:10000
- May 04 10:19:34 torr stunnel[238]: LOG5[45]: Service [webmin] connected remote server from 127.0.0.1:51260
- May 04 10:19:34 torr stunnel[238]: LOG3[43]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
- May 04 10:19:34 torr stunnel[238]: LOG5[43]: Connection closed: 4175 byte(s) sent to TLS, 967 byte(s) sent to socket
- May 04 10:19:36 torr stunnel[238]: LOG3[45]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
- May 04 10:19:36 torr stunnel[238]: LOG5[45]: Connection closed: 660 byte(s) sent to TLS, 796 byte(s) sent to socket
- May 04 10:19:37 torr stunnel[238]: LOG5[46]: Service [webmin] accepted connection from 192.168.0.31:48218
- May 04 10:19:37 torr stunnel[238]: LOG3[46]: SSL_accept: ../ssl/record/rec_layer_s3.c:1562: error:14094416:SSL routines:ssl3_read_by>
- May 04 10:19:37 torr stunnel[238]: LOG5[46]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
- May 04 10:19:37 torr stunnel[238]: LOG5[47]: Service [webmin] accepted connection from 192.168.0.31:48220
- May 04 10:19:37 torr stunnel[238]: LOG5[47]: s_connect: connected 127.0.0.1:10000
- May 04 10:19:37 torr stunnel[238]: LOG5[47]: Service [webmin] connected remote server from 127.0.0.1:51268
- May 04 10:19:38 torr stunnel[238]: LOG3[47]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
- May 04 10:19:38 torr stunnel[238]: LOG5[47]: Connection closed: 663 byte(s) sent to TLS, 814 byte(s) sent to socket
- May 04 10:19:39 torr stunnel[238]: LOG5[48]: Service [webmin] accepted connection from 192.168.0.31:48230
- May 04 10:19:39 torr stunnel[238]: LOG3[48]: SSL_accept: ../ssl/record/rec_layer_s3.c:1562: error:14094416:SSL routines:ssl3_read_by>
- May 04 10:19:39 torr stunnel[238]: LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
- May 04 10:19:39 torr stunnel[238]: LOG5[49]: Service [webmin] accepted connection from 192.168.0.31:48244
- May 04 10:19:39 torr stunnel[238]: LOG5[49]: s_connect: connected 127.0.0.1:10000
- May 04 10:19:39 torr stunnel[238]: LOG5[49]: Service [webmin] connected remote server from 127.0.0.1:37940
- May 04 10:19:41 torr stunnel[238]: LOG3[49]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
- May 04 10:19:41 torr stunnel[238]: LOG5[49]: Connection closed: 660 byte(s) sent to TLS, 814 byte(s) sent to socket

`

**Comment by JedMeister** [comment]
Hi @Yur-ok - thanks for the report and info.

Looking at your log, I'm not seeing anything related to NFS!?

Can you confirm that you've running this on LXC (e.g. on Proxmox)? And that you have the required `nfs-kernel-server` package on the host? And made the other LXC container conf (on the host) required to (previously) make NFS work?

**Comment by Yur-ok** [comment]
@JedMeister thanks for trying to help, but I find out another solution for my task.

**Comment by UncleVic** [comment]
I repeated this and can confirm.

1. `nfs-kernel-server` on the host
2. the privileged container
3. `lxc.apparmor.profile: unconfined`
4. open NFS ports in the Turnkey firewall

And everything works as expected.

**Comment by JedMeister** [comment]
FYI I have added relevant documentation to the FIleserver doc page on the website: https://www.turnkeylinux.org/docs/fileserver
