### ISSUE TITLE
Problem with passing through Intel Quick Sync drivers - Mediaserver 16.1

### ISSUE THREAD

**Issue by fdfytr** [turnkeylinux/tracker#1751]
Followed [official instructions](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#va-api-and-qsv-hardware-acceleration-on-lxc-on-proxmox) from Jellyfin
```
# cat /etc/pve/lxc/102.conf
arch: amd64
cores: 2
features: nesting=1
hostname: mediaserver-ct
memory: 2032
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=9E:C7:79:9D:AD:A7,type=veth
ostype: debian
rootfs: local-lvm:vm-102-disk-0,size=8G
swap: 512
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
```

and received this error

```
# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Privileged container
I wonder can that be due to host has i965-va-driver (Debian bullseye) but LXC mediaserver intel-media-va-driver (buster)
Would appreciate tips on resolving this

**Comment by JedMeister** [comment]
Hmm, you could be right (and it may be the OS mismatch between host and guest? Out of interest, does `/usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so` exist on the guest? Or the host? AFAIK it should be installed on the host (which it sounds like you have?). If not, you should be able to install like this (on the PVE host):

```
apt install -y i965-va-driver
```

That should provide the /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so` file.

A google suggests that there are a few other things that can go wrong. One is the ownership of the `/dev/dri/renderD128` "device" path and whether (or not) that correlates with the appropriate group. You can check that with the following command:
```
ls -l /dev/dri/renderD128
```
That will output a result something like this:
```
crw-rw----+ 1 root render 226, 128 mar 28 14:19 /dev/dri/renderD128
```

That should show the user (probably `root` - as per my example above) and the group which controls that "device" (probably `render` - again as per my example above). You then need to ensure that the `jellyfin` user is a member of this group. You can check what groups the `jellyfin` user is a member of with the `group` command:
```
group jellyfin
```

If you need to add the `jellyfin` user to a specific group, please do that like this:
```
usermod -a -G GROUP_NAME jellyfin
```

Where `GROUP_NAME` is the group that you wish to add `jellyfin` user to. You may have already done that as per the Jellyfin docs (they suggest joining the "`jellyfin` user to the groups `video`, `render` and/or `input`"), but good to double check.

If you continue to have issues, please confirm that the above is as stated and I'll see if I can get it working myself.

**Comment by fdfytr** [comment]
> apt install -y i965-va-driver

on the guest fixed that. thank you!
