### ISSUE TITLE
default password mysql 

### ISSUE THREAD

**Issue by ammarjmhor10** [turnkeylinux/tracker#1759]
Hi, I download an OpenStack image and uploaded it to the cloud provider. there is a default password and I do not know it so please what is the default password? thanks

**Comment by JedMeister** [comment]
There are no default passwords, you need to log in via SSH as `root` to set all passwords. If not preset in the image (which you can do by mounting it and adding a [preseed](https://www.turnkeylinux.org/docs/inithooks) file). On firstboot, the root (and all other) password(s) is(/are) first set to a random string. The random root password should be visible in the log.

The OpenStack builds are getting pretty dated. We don't have any OpenStack infrastructure running, so if you'd like to help us improve them, that's be awesome.
