### ISSUE TITLE
ansible-semaphore fails to create the home directory for semaphore user

### ISSUE THREAD

**Issue by MarcMocker** [turnkeylinux/tracker#1764]
Heyy all, 

I just tried to run the turnkey-ansible image (in version 16.1-1 amd64) and found some bugs:
by creating a simple test-task I got 
```
10:47:19 PM Could not create directory '/home/semaphore/.ssh'.
10:47:19 PM Failed to add the host to the list of known hosts (/home/semaphore/.ssh/known_hosts).
```
on executing it. 

My fix so far has been to simply create the home dir for the semaphore user manually
(mkdir /home/semaphore && chown semaphore:semaphore /home/semaphore)

**Comment by MarcMocker** [comment]
as a consequence of this bug the ssh authentication for remote repositories doesn't seem to work, but public http-repos are still usable

**Comment by JedMeister** [comment]
Thanks for reporting the issue.

I'll have to have a look but AFAIK the way it's meant to work is that it's meant to use the 'ansible' user - which does have a log in etc. Also, there should be a newer v17.x build too. Does that have the same issue? (I assume it would, but just to be sure).

**Comment by MarcMocker** [comment]
Heyy, Thank you for your response. 

I just tested it with the version 17, and the error was gone, so I assume it's my fault for using an old version of the image.
Well, I guess there is no bug anymore, so I'll close this issue now.
Thanks to all of you! You are doing a great job :heart_eyes:

**Comment by JedMeister** [comment]
Ok great news! :smile: And thanks too for your kind words... :heart:
