### ISSUE TITLE
Observium - poller-wrapper.py uses `python` shebang, so cron job fails

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1771]
As noted by [Eduardo in the forums](https://www.turnkeylinux.org/forum/support/fri-20221104-0128/observium-poller) the current Observium appliance does not have `python` (only `python2` or `python3`) so the cron job fails.

As I noted, the shebang could be changed, but updating Observium, would probably break it again.

A better fix is to explicitly call the script using python3 (in the cron job).

I.e. change the line below in `/etc/cron.d/observium` from:
```
*/5  *  * * * root /opt/observium/poller-wrapper.py 1 >> /dev/null 2>&1
```
to
```
*/5  *  * * * root /usr/bin/python3 /opt/observium/poller-wrapper.py 1 >> /dev/null 2>&1
```

**Comment by dijikul** [comment]
This issue just popped up for me in the turnkey-observium image version 17.1-1 pulled from within Proxmox; thankfully, the documentation here confirmed my digging and the fix, but as it led me here, thought to mention that this bug is still being deployed by users new to the turnkey images and observium as a whole.

None the less, thanks for your efforts!  Great software!

**Comment by JedMeister** [comment]
Hi @dijikul - Thanks for dropping in. The issue is closed here because the fix has been merged into the build code, but the reason why you hit it is that we haven't done a rebuild yet (to include the fix).

I am hoping to rebuild really soon, but we've had some other reports of issues displaying graphs. Have you hit that? If so, could you please share any further info you might have about that? Any assistance you may be able to provide would be appreciated.

**Comment by dijikul** [comment]
HI @JedMeister, thanks for the prompt response!

Looks like I may be seeing some of that, though I'm not entirely sure what to be expecting.

The majority of my empty graphs look to be in the netstats section; do we know what needs to be enabled / switched on, for that to start working?  I'd expect ICMP Stats for example, but I'm not seeing any:

![image](https://user-images.githubusercontent.com/2670528/217601733-73f7c2eb-0122-4fea-9af8-ae7770f4b9d6.png)


Turnkey Version: `turnkey-observium-17.1-bullseye-amd64`

**Comment by JedMeister** [comment]
Thanks for the follow up @dijikul. FYI that's not at all what I was expecting! It seems like it's not getting (or perhaps collecting) the data?! I was expecting something wrong with the rendering, but it appears that the graphs are drawing ok, just that there is no data.

I'll try to have a closer look now that I have a clearer idea of the actual problem.

**Comment by Christie018** [comment]
@dijikul Could you walk me through your observium snmp client so I can try and recreate the issue? More specifically, what is the ./add_device.php script syntax you are using to connect the server to the client.

**Comment by dijikul** [comment]
Hi @Christie018,

> what is the ./add_device.php script syntax you are using to connect the server to the client

I've provided the IP of the managed switch, the SNMP Community name, and the version, like so:

`/opt/observium/add_device.php 192.168.1.50 private v2c`

**Comment by Christie018** [comment]
Okay, I changed my snmp configuration to match yours and was able to connect :) @dijikul 
I did come upon this documentation about the graphs and I do seem to be getting some of those to populate,. 

I also checked back in on my observium server and seem to have my graphs populated?! I did leave the snmp client pinging for a bit, so maybe you need to "make some noise" on your snmp client and see if the graphs populate over time?
https://docs.observium.org/faq/#my-graphs-dont-work
