### ISSUE TITLE
GitLab v16.1 - Invalid Repository Signature

### ISSUE THREAD

**Issue by MarcelOnGit** [turnkeylinux/tracker#1777]
I created a new container and the first thing I did was run `apt-get update`. I got the following error:

Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org buster/updates InRelease           
Ign:3 http://archive.turnkeylinux.org/debian buster-security InRelease
Ign:5 http://archive.turnkeylinux.org/debian buster InRelease
Hit:6 http://archive.turnkeylinux.org/debian buster-security Release
Hit:8 http://archive.turnkeylinux.org/debian buster Release                     
Get:4 https://packages.gitlab.com/gitlab/gitlab-ce/debian buster InRelease [23.3 kB]
Err:4 https://packages.gitlab.com/gitlab/gitlab-ce/debian buster InRelease
  The following signatures were invalid: EXPKEYSIG 3F01618A51312F3F GitLab B.V. (package repository signing key) <packages@gitlab.com>
Reading package lists... Done
W: GPG error: https://packages.gitlab.com/gitlab/gitlab-ce/debian buster InRelease: The following signatures were invalid: EXPKEYSIG 3F01618A51312F3F GitLab B.V. (package repository signing key) <packages@gitlab.com>
E: The repository 'https://packages.gitlab.com/gitlab/gitlab-ce/debian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by MarcelOnGit** [comment]
As a solution I have found the following: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6701#note_861905099
`curl -s https://packages.gitlab.com/gpg.key | gpg --dearmor > /usr/share/keyrings/gitlab-ce.gpg`

**Comment by JedMeister** [comment]
Hi @MarcelOnGit - thanks for your report and bonus points for sharing your work around.

As you've likely noticed, our GitLab appliance is a bit dated and hasn't been updated particularly recently. It's been a really labour intensive appliance to maintain and as such has been on the backburner a bit. We are currently in the process of updating it and hopefully when we have that complete, the v17.x release will be much better.

FYI as something of an aside, personally, I use our [Gitea appliance](https://www.turnkeylinux.org/gitea) for my personal projects. It's much lighter weight than GitLab, more responsive and easier to maintain. On the flip side, that is at least in part because Gitea doesn't have all the bells and whistles that GitLab has (and in part that Gitea is written in Go; GitLab has a Ruby core but is a mish-mash of Ruby, Go and other stuff).

**Comment by MarcelOnGit** [comment]
Hi @JedMeister thanks for the tip with Gitea. I have had a look at it and it is definitely much slimmer. However, I've noticed a problem where I don't know right now if it's me or if it's a bug. How can I add images to the wiki? Does that work for you?

**Comment by JedMeister** [comment]
I've never tried adding images to a Gitea wiki, so I wasn't sure. But as I had an instance handy, I had a go and it appears to "just work" for me!?

Before I go any further, please note that my personal Gitea server isn't public so I haven't had a need to keep it up to date - hence it's likely much older than yours and behaviour may not exactly match yours.

Regardless, it works ok for me:
![Screenshot from 2022-12-09 15-04-37](https://user-images.githubusercontent.com/818633/206622483-5e5566a6-f037-48ff-9533-28b6d7dae6cb.png)

It looks like it only supports including images hosted elsewhere though. This is the content of the wiki page:
![Screenshot from 2022-12-09 15-04-58](https://user-images.githubusercontent.com/818633/206622626-a3ecaea7-4c4b-45df-a8a2-bf41a5a1dc6e.png)

To work around that, I just committed the picture to the git repo and let gitea serve it. :smile:
![Screenshot from 2022-12-09 15-15-45](https://user-images.githubusercontent.com/818633/206622793-a391e774-44d3-4fe4-af38-e6c063092cd9.png)

If that doesn't resolve your issue, please open a new issue. Please describe the issue with as much detail as possible, ideally including step by step instructions to recreate it and a screenshot of both the rendered wiki page with broken/missing image and the wiki page content (screenshot or copy/paste into a code block).

**Comment by JedMeister** [comment]
Also, FWIW if you don't want to put them in the git repo, then you could alternatively upload them to (perhaps an `images` subdirectory of) `/home/git/custom/public`. I haven't tested it, but from my reading of the nginx config, that directory should be served by Nginx (from web root) by default. I.e. `/home/git/custom/public/images/my_pic.jpg` should be accessible via `http://your_domain.com/images/my_pic.jpg` (or `https` obviously).

**Comment by JedMeister** [comment]
Closed by the v17.0/v17.1 release.
