### ISSUE TITLE
Invoice Ninja - tweaks needed

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1778]
[Lee has reported on the forums](https://www.turnkeylinux.org/forum/support/sun-20221120-1932/invoice-ninja-v5-issues) that he has had a really frustrating time trying to get the new v17.1 Invoice Ninja app working.

The issues - so far:
- It looks like lots of it's functionality depends on API callbacks, so it won't work without a domain set and a proper SSL cert. At the very least this should be documented.
- Email config should probably be set at firstboot, or at least documented.
- Provision of a `turnkey-php` or perhaps `turnkey-artisan` helper script(s).
- Default permissions seem not quite right? (See below for fix)
- PHP memory too low (needs 512M min).
- Queue not enabled - we should look at enabling that!
- PDF generation not set up for local use (still relies on 3rd party service - see below for fix).

----

##Some fixes

Fix for permissions:
```
chown -R www-data:www-data /var/www/invoiceninja
find /var/www/invoiceninja -type d -exec chmod 755 {} \;
```

Install local PDF renderer:
```
runuser -l -s /bin/bash -c "cd /var/www/invoiceninja && vendor/bin/snappdf download"
sed -i "\|^PDF_GENERATOR|s|=.*|=snappdf|" /var/www/invoiceninja/.env
runuser -l www-data -s /bin/bash -c "php /var/www/invoiceninja/artisan optimize"
```

**Comment by Christie018** [comment]
The issues in this tracker post are resolved in the most recent PR to update the appliance.
