### ISSUE TITLE
Observium - graphs not showing

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1798]
Please see https://www.turnkeylinux.org/forum/support/thu-20221201-0716/observium-draw-errors

I'm sure if I could recreate it I can fix it, but I'm snowed under and completely unfamiliar with Observium.

Perhaps @Christie018 if you get a chance you could have a look. Even if you can't work out the issue, if you could document how to recreate it that would be awesome.

**Comment by Christie018** [comment]
### How to recreate the observium graphing issue:

1. Build observium server from turnkey github repository or download iso from website and apply the cron jobs fix.
2. Build or find a snmp client. I used a core server VM and installed and configured the server with snmp pointing to my observium server:
![image](https://user-images.githubusercontent.com/107725799/219959604-dff39c7e-6b02-4ab9-a845-d267a6f7679d.png)
3. Restart snmpd on the core server to make sure the configuration takes, then switch back over to your observium server to add the device via CLI script.
4. The script /opt/observium/add_device.php is used to connect to the core snmp client: 
![image](https://user-images.githubusercontent.com/107725799/219959782-63812f0e-be92-43e9-bed6-602dcc01ada0.png)
5. Browse to your observium server IP on the internet and log in as admin. Navigate to "All devices --> Core IP --> Graphs --> Netstats. 
![image](https://user-images.githubusercontent.com/107725799/219959890-234c8c9e-ac30-48c7-ad7e-90ae52598d8d.png)
6. This should show you the blank graphs at first. After leaving my core pinging the observium IP for a while, the graphs seemed to populate by themselves.

**Comment by JedMeister** [comment]
Thanks Mattie. Your experience suggests that with the current build code (which hasn't yet been released) the issue is resolved (if it ever existed). I'll note that the next release closes this bug. My guess is that the issue is on the client side rather than the Observium host.

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/observium/pull/20 (and note added to changelog here: https://github.com/turnkeylinux-apps/observium/commit/03e74d1434330c5f508e76ab166d61cfa37fc4e9
