### ISSUE TITLE
mattermost is not listening IPv6

### ISSUE THREAD

**Issue by lo48576** [turnkeylinux/tracker#1800]
## Description
mattermost (and also Web shell, Webmin, and Adminer) don't listen to IPv6.

## How to reproduce
1. Install `turnkey-mattermost-17.1-bullseye-amd64` LXC template on Proxmox VE.
2. Run initial set up with static IPv4 address and SLAAC IPv6 address.
3. Once the set up is done, try to access to the IPv6 address through https, http :12320, http :12321, and http :12322. None of them accepts the connection.
    * `ping` succeeds to the IPv6 address.
    * They all can be connected through local IPv4 address.
    * In contrast, SSH can be connected through IPv6 address.

## Output of `turnkey-version`
`turnkey-mattermost-17.1-bullseye-amd64`

## Expected result
They, or at least mattermost itself, listen IPv6 address on port 443 (and maybe 80?).

## Why this is required
At my home, IP address accessible from WAN is only (semi-dynamic) IPv6 address, so I need to set up DDNS client and make mattermost accessible through domain that resolves only to IPv6 address.

## Any other relevant information
`/etc/nginx/sites-available/{tkl-,}default` have `listen [::]:80 default_server;` and `listen [::]:443 ssl default_server;`, but `mattermost` at the same directory (which is symlink pointee of `/etc/nginx/sites-enabled/mattermost`) have neither of them (it only has `listen 80;` and `listen 443 ssl;`).
Also `adminer` at the same directory have `listen 12322 ssl;` but not `[::]:12322`.

**Comment by JedMeister** [comment]
Thanks for your report.

It looks like Mattermost (and Adminer) not being configured for ipv6 is a bug. Both of them should have `listen [::]:80` & `listen [::]:443 ssl` respectively.

However, it seems your issue runs deeper than that?! AFAIK Webmin and Webshell should be listening on IPv6 OOTB?

**Comment by lo48576** [comment]
I tried on my instance to add `listen [::]:{80,443 ssl};` and confirmed mattermost became accessible through IPv6.
(<https://github.com/turnkeylinux/confconsole/pull/65> was necessary to use LetsEncrypt, but it's already merged and will be released someday, so no problem.)

> However, it seems your issue runs deeper than that?! AFAIK Webmin and Webshell should be listening on IPv6 OOTB?

I didn't know this (unsupported IPv6) is intentional or not, so reported them at the same time. However, I personally don't need them to listen on IPv6, so feel free to ignore reports on them here. Primary thing I'd like to report is only IPv6 support for mattermost.

**Comment by JedMeister** [comment]
I really appreciate the report and the info you've provided. Thanks for taking the time to do that.

I'm glad to hear that you have Mattermost working on IPv6 now.

Webmin and Webshell should work via IPv6 too, but if that's not an issue for you, I won't bother digging into that right now.

FWIW I've opened a PR to close this issue too. Thanks again.

**Comment by JedMeister** [comment]
FWIW I just checked Webmin and Webshell too. On mine, Webshell was already listening on IPv6, but not Webmin. Note that to enable IPv6 for Webmin, you need to tweak `/etc/stunnel/webmin.conf`. The last 4 lines (with IPv6 enabled) should look like this:
```
[webmin]
accept  = :::12321
connect = 127.0.0.1:10000
TIMEOUTclose = 0
```

Weird thing is that the source of that file was changed at the same time as the Webshell config?!:

https://github.com/turnkeylinux/common/commit/99b683619646fb9ddf17e032765fe9ddde971298

So why it's the way it is a mystery...
