### ISSUE TITLE
Apache2 VirtualHost (question)

### ISSUE THREAD

**Issue by DerDoubleD** [turnkeylinux/tracker#1806]
I want to enable a VirtualHost for 8080.
I have created the following file for this.
/etc/apache2/sites-available/daniel.conf
`
<VirtualHost *:8080>
     DocumentRoot /var/www/daniel
     <Directory "/var/www/daniel">
         OptionsNone
         Require all granted
     </Directory>
</VirtualHost>
`

I allowed 8080 in the firewall configuration.
Unfortunately it does not work.
Can someone help me?

**Comment by DerDoubleD** [comment]
You have to go into the file /etc/apache2/ports.conf and enter 
`Listen 8080` 
as well

**Comment by JedMeister** [comment]
Glad to hear you worked it out. :smile:
