### ISSUE TITLE
Wireguard LXC/Proxmox build missing `wireguard-tools` package

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1824]
As reported and confirmed on the [forums](https://www.turnkeylinux.org/forum/support/tue-20210921-1353/wireguard-setup#comment-54657), the `wireguard-tools` package is missing from the v17.1 TurnKey WireGuard appliance. My suspicion is that it gets removed when we remove the kernel (for the LXC build).

We should add `wireguard-tools` as an explicit dependency (in the `plan/main`) and that should ensure that it remains after removing the kernel.

To workaround the issue, install `wireguard-tools` like this:
```
apt update
apt install -y wireguard-tools
```

**Comment by brantleyforrest** [comment]
I am one of the people who reported the symptoms of this issue on the forum after getting a certain error message when trying to add a user to the VPN. I have now discovered that I also get a similar error message when trying to generate an SSL cert through LetsEncrypt. I don't know enough about LetsEncrypt or about the error message to know if this is a related issue or not, but this isn't an error I've gotten from any other Turnkey container. Feel free to tell me if this comment belongs somewhere else.

For reference, the certbot package isn't included in my install and isn't auto-installed after running apt upgrade (but, like I said, I don't know enough about it to know if it should even be included at all). If there are any other packages I should check the status of that would affect the function of the SSL tool in confconsole then I would be glad to check for them.

EDIT: Installing the certbot package fixed the issue. It seems like there is a broader dependency issue that needs to be addressed.

**Comment by JedMeister** [comment]
I'd be interested to understand how you were trying to get Let's Encrypt certs?

Your mention of Confconsole, makes me think that it was via our built-in [Let's Encrypt integration](https://www.turnkeylinux.org/docs/confconsole/letsencrypt)?

But you say that installing certbot fixed it?! That doesn't make much sense to me as our Let's Encrypt integration doesn't use certbot, ours uses [Dehydrated](https://dehydrated.io/) (i.e. not including certbot by default is intentional).

The fact that installing certbot fixed it, does suggest that there may have been a missing dependency (that installation of certbot pulled in) but I'm completely unclear on what that might be? I'll need to do some more testing when I get a chance, but any additional info you can provide (e.g. explicit error messages you got) would be useful.

**Comment by brantleyforrest** [comment]
Yes, I was using the Let's Encrypt integration in confconsole.

I tried uninstalling certbot and running apt autoremove afterwards to see if it would re-break it, but everything still worked fine. I'm kicking myself now for not copying or screenshotting the error while I had the chance. I can't remember much in particular about what the error was. It definitely wasn't a short error message though. When I said that it was a "similar error message" to the wireguard-tools issue, I only paid close enough attention to see that they were both a very large wall of text that filled up the confconsole window, and they both showed errors with python scripts. 

I don't have much time to try to replicate it today, but I can spend some time with it later in the week if not this weekend.

**Comment by JedMeister** [comment]
Thanks @bafben10 - No problem, I completely get it, I often don't think to copy/paste or screenshot error messages lots of the time either! :smile: 

Regardless, if you do manage to reproduce it, that'd be awesome. I'm certain that if I know the steps to reproduce the issue, that I'll be able to fix it.

**Comment by erdoukki** [comment]
Same problem missing the package wireguard with turnkey-wireguard installed in proxmox from the CT template>

Just installing the wiregard deb like mentionned in the first topic by @JedMeister to fix the missing tool.

PS: My apologize if bad nammed or mispelled. I just discover this all project and I am still in the impress sense...
ThX

**Comment by JedMeister** [comment]
Thanks @erdoukki - Hopefully we'll have an updated Wireguard appliance (which doesn't include this bug) available soon. Unfortunately though, I can't give an ETA.

**Comment by manu144x** [comment]
I didn't have anything installed, neither wireguard nor the wireguard-tools package.

Just nothing. I ended up doing it myself.

**Comment by JedMeister** [comment]
@manu144x - thanks for posting but only the `wireguard-tools` package is required when running under LXC!

The `wireguard` package is not required or desired in an LXC container. It's just a meta-package (i.e. it doesn't actually include anything - just depends on other packages):
```
root@jed-test-wg ~# apt show wireguard
Package: wireguard
Version: 1.0.20210223-1
Priority: optional
Section: net
Maintainer: Daniel Kahn Gillmor <dkg@fifthhorseman.net>
Installed-Size: 17.4 kB
Depends: wireguard-modules (>= 0.0.20191219) | wireguard-dkms (>= 0.0.20200121-2), wireguard-tools (>= 1.0.20210223-1)
Homepage: https://www.wireguard.com
Download-Size: 8164 B
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: fast, modern, secure kernel VPN tunnel (metapackage)
 WireGuard is a novel VPN that runs inside the Linux Kernel and uses
 state-of-the-art cryptography (the "Noise" protocol). It aims to be
 faster, simpler, leaner, and more useful than IPSec, while avoiding
 the massive headache. It intends to be considerably more performant
 than OpenVPN. WireGuard is designed as a general purpose VPN for
 running on embedded interfaces and super computers alike, fit for
 many different circumstances. It runs over UDP.
 .
 This metapackage explicitly depends on both the kernel module and the
 userspace tooling.
```
`wireguard-modules` or `wireguard-dkms` provide the kernel modules, `wireguard-tools` is the "userspace tooling".

As LXC leverages the host's kernel, so long as you have the required kernel loaded on the host (which you should - and if it works, that confirms it), then you don't need (or want) the kernel and modules installed in your LXC guest - just the "userspace tooling" (i.e. just `wireguard-tools`). FYI if the host doesn't have the required Wireguard kernel module loaded, then even installing `wireguard` in your LXC guest won't make it work...

So I'd recommend running this in your container to remove the additional cruft you've unintentionally installed (i.e the kernel and modules - should free up ~320MB in your container):
```
apt remove wireguard --autoremove
apt install -y wireguard-tools
```

Regardless, I really appreciate you posting as it's helped me understand how this issue specifically occurred in the first place! I suspected that it was something like that, but wasn't 100% sure. FYI we remove the kernel when building our LXC templates - I can now see exactly how that had the cascading effect of also removing `wireguard-tools`.

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/wireguard/pull/10
