### ISSUE TITLE
Cron jobs do not start because of wrong path

### ISSUE THREAD

**Issue by sepo** [turnkeylinux/tracker#1825]
In `/etc/cron.d/nextcloud` the path should be `/var/www/nextcloud/cron.php` and not `/var/www/nextcloud/occ`.

**Comment by JedMeister** [comment]
Thanks @sepo. I just had a look and you are absolutely right. I'm not even sure why it was changed? (It was changed to it's current form for v17.0?!).

As something of an aside It's probably also worth reducing the time to every 5 mins (it's 15 now and Nextcloud will give warning if the cron job hasn't run for 10 or more minutes).
