### ISSUE TITLE
LDAP PHP extension missing ?

### ISSUE THREAD

**Issue by cloverenergy** [turnkeylinux/tracker#1826]
Would seem the php-ldap extension is missing from the VM. 
But even adding it I get "LDAP PHP extension not installed" error

**Comment by JedMeister** [comment]
Hi @cloverenergy - could you please share which particular appliance you are referring to? If you're not 100% sure, please just share the output of this command:

```
turnkey-version
```

FYI we have about 70 appliances that ship with PHP and AFAIK only one comes with the PHP LDAP extension pre-installed, so not having it pre-installed is expected.

If you can please share which appliance you are running and what steps you took to install the PHP LDAP extension I'm sure I can assist.

Having said that, I have a couple of guesses as to why it isn't working for you.
- my first guess is that you didn't restart Apache after installing the new module. Restart Apache like this: `systemctl restart apache2`
- My next guess is that you are using one of the v17.x appliances that includes newer PHP (Debian 11/Bullseye ships with PHP 7.4 - but many apps these days require 8.0+). Newer PHP versions (should be PHP8.1 on v17.x apps) are provided by the sury.org PHP repo. With the sury.org PHP repo enabled, installing the `php-ldap` package will install the LDAP PHP module for the latest version of PHP currently supported (currently v8.2). Unless your system is configured to use this same (latest) version of PHP, then that won't work. The workaround is to install the PHP version specific module, in this case: `php8.1-ldap` (and then restart apache to apply - `systemctl restart apache2`).

I hope that helps, but please provide the additional info.

**Comment by cloverenergy** [comment]
Hello

I am using turnkey-bookstack-17.2-bullseye-amd64

The extension is installed

***@***.*** ~# apt-get install php-ldap
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php-ldap is already the newest version (2:7.4+76).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

***@***.*** ~# dpkg-query -L php-ldap
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php-ldap
/usr/share/doc/php-ldap/changelog.gz
/usr/share/doc/php-ldap/copyright

Searching for php.ini:

./var/www/bookstack/vendor/aws/aws-crt-php/php.ini
./etc/php/8.1/cli/php.ini
./etc/php/8.1/apache2/php.ini

So I have edited last 2 php.ini with the uncommented extension=ldap and, 
then, also with extension=php_ldap.so.

None of this works.

(the first ini file is most likely not relavant here)

Obviously restarted apache in each instance

Thanks for any further help you might provide.

**Comment by cloverenergy** [comment]
Solved - one has to install php8.1-ldap !!
might still be nice to have it "out of the box" as connecting to an LDAP server seems fairly reasonable use case.

**Comment by JedMeister** [comment]
> Solved - one has to install php8.1-ldap !!

Glad to hear you got it working.
