### ISSUE TITLE
Confconsole stacktrace if interface not found

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1846]
On v18.x/Bookworm Confconsole will crash with a stacktrace (but not crash back to CLI) if an interface can't be bought up at boot.

I have only noticed it if/when I don't define an interface at all, although it has been reported that it can occur occasionally even when an interface is correctly set up.

So it seems that there are 2 (somewhat related) issues:
1. crash when interface not found
2. race condition(?) at start up when confconsole may start before the interface is up(/)

**Comment by JedMeister** [comment]
FWIW it appears that the issue is occurring because of our implementation of typing. Specifically the `assert`s in Confconsole's [`ifutil.py`](https://github.com/turnkeylinux/confconsole/blob/master/ifutil.py#L307-L308) file.

**Comment by JedMeister** [comment]
@a3s7p - any news on this mate?

**Comment by a3s7p** [comment]
@JedMeister https://github.com/turnkeylinux/confconsole/pull/80, should be closed now :slightly_smiling_face:

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux/confconsole/pull/80
