### ISSUE TITLE
TKLDev - Squid proxy cache configuration conservative, causing a lot of cache misses

### ISSUE THREAD

**Issue by derMart** [turnkeylinux/tracker#1855]
Hi,

I am currently again in the process of developing `bitkey-ng` :-) Though, I noticed, that a lot of apt downloads where not coming from the squid cache, `/var/log/squid/access.log` is showing a lot of cache misses.

This boils down to the configuration of the squid proxy in https://github.com/turnkeylinux-apps/tkldev/blob/7f427df9cc43dd076f67a6d2ed86cde49fa53ea3/overlay/etc/squid/squid.conf
As per [squid  documentation](http://www.squid-cache.org/Doc/config/cache_dir/)
```
cache_dir ufs /var/spool/squid 200 16 256
```
results in only a maximum of 200MB cache size on disk.  
Second issue is, that there is also a maximum object size in each cache, which defaults to 4MB only, see: http://www.squid-cache.org/Doc/config/maximum_object_size/
That means every file larger than 4MB does not get cached and will always be redownloaded.

According to the docs it should be possible to increase that per cache directive using the `max_size=[size]` option, but I wasn't able to get that working. However, increasing `maximum_object_size` directly had an effect. My configuration now looks like this:
```
maximum_object_size 1024 MB
cache_dir ufs /var/spool/squid 2048 16 256
```
So resulting in a max of 2Gig cache storage, with a max of 1Gig per object. This works nicely now. If I am building a second time, no apt download is happening via the network. For (the current version of) `bitkey-ng`, the used cache size is around 650MB. One can view this size via `du -sh /var/spool/squid/`.

So I wondered: Is there a reason for this very conservative cache configuration? Would you be open to increase the numbers?

best
derMart

**Comment by JedMeister** [comment]
Awesome work @derMart! Thanks for looking into that. TBH, I don't recall my rationale for setting the on disk cache so low. FWIW it did initially seem to work really well for me (back in v17.x). However, while working on v18.x I too have noticed that it doesn't seem to work as well as it used to. I think part of it was probably that caching had been broken for a while (we were still using polipo which only supported vanilla http and wasn't working that well) so any improvement was immediately noticeable.

Regardless, it hasn't felt like a huge priority, and I haven't had the spare cycles to investigate...

Let's bump the settings to your suggestion and see how we go. We can always change it again later and/or users can adjust it themselves.

Having said that, perhaps the "right answer" is to set on disk cache dynamically at firstboot? Say 10% or 2GB - whichever is the smaller? And adjust the `maximum_object_size` to 50% of disk cache? I'm not going to do that now, but it's an idea for the future...

**Comment by derMart** [comment]
Thank you very much, also for the super fast response and integration :-) It is always a pleasure to get feedback from you!
Yep, the dynamic approach sounds good to me too, but I would also not implement this right now and move on to the `bitkey-ng` work.

In any case, I think it would be good to get the current behaviour documented for tkldev users, such that they know how large they should set their VM disk size? Good place for this documentation might be even here: https://www.turnkeylinux.org/tkldev under "Usage details" ? Well for this, one might probably also need to know how large tkldev root file system will be ... ...

**Comment by OnGle** [comment]
Maybe an inithook? Query the user with sane defaults determined based on current rootfs size?

**Comment by JedMeister** [comment]
> Thank you very much, also for the super fast response and integration :-)

Just luck of the draw... :grin: Ask any of the poor souls that have contributed and get nothing but crickets for weeks (sometimes months)... But thanks for your appreciation anyway. Nice feedback is always nice.

> Yep, the dynamic approach sounds good to me too, but I would also not implement this right now [...]

I've opened a new issue so we don't forget: https://github.com/turnkeylinux/tracker/issues/1856

> I think it would be good to get the current behaviour documented for tkldev users, such that they know how large they should set their VM disk size? Good place for this documentation might be even here: https://www.turnkeylinux.org/tkldev under "Usage details" ?

Good call. Please feel free to update the [TKDev readme](https://github.com/turnkeylinux-apps/tkldev/blob/master/README.rst) (the appliance pages are generated from the appliance readme). I suggest a new section below the main body, above the "Example build sources" section. And/or perhaps in the TKLDev docs dir?
