### ISSUE TITLE
Unable to use turnkey ISO in Proxmox (KVM) - graphics initialization failed - Error setting up gfxboot

### ISSUE THREAD

**Issue by merkys7** [turnkeylinux/tracker#1869]
Hello,
I have been trying to use Turnkey ISO in Proxmox for a while now but I cannot succeed.

Here is how do I do it:
1. I download ISO
```
wget 'http://mirror.turnkeylinux.org/turnkeylinux/images/iso/turnkey-bagisto-18.0-bookworm-amd64.iso'
```
2. I create new VM
```
qm create 364532 --name test.com --memory 32768 --cores 8 --cpu cputype=host --nameserver '8.8.4.4 8.8.8.8' --searchdomain localhost --net0 virtio,bridge=vmbr0 --hotplug 'network,disk,usb' --agent 1 --onboot 1
```
3.
I import the template
```
qm importdisk 364532 turnkey-bagisto-18.0-bookworm-amd64.iso local-lvm
```
4. Set boot options
```
qm set 364532 --scsihw virtio-scsi-single --scsi0 local-lvm:vm-364532-disk-0,discard=on,ssd=1,size=400000M
qm set 364532 --ide2 local-lvm:cloudinit
qm set 364532 --boot c --bootdisk scsi0
qm set 364532 --serial0 socket --vga serial0
```
5. Start the VM and enter terminal
```
qm start 364532
qm terminal 364532
```

and I always end up with the error:
```
graphics initialization failed
Error setting up gfxboot
boot:
```

By any chance, do you know what I am doing wrong? Is it not possible to use Turnkey ISOs in Proxmox?
I have tried multiple different templates. Any help is highly appreciated.

**Comment by JedMeister** [comment]
Thanks for the report.

I've had a look and can reproduce your issue (albeit with slightly different settings; as I don't have 32GB RAM free nor 8 CPUs).

I'm not completely sure, but I reckon there are 2 issues:

First is that the initial ISO installer dialog (i.e. syslinux) provides a graphical interface. My guess is that that is why this is failing with the message that it is.

The second is that TurnKey doesn't (yet) support cloudinit. FWIW we developed [inithooks](https://github.com/turnkeylinux/inithooks) (our own init system) in the early days of cloudinit development - long before it became the defacto standard. We've been wanting to support cloudinit for a few years now, but we're a small team with minimal spare cycles (with a todo list a mile long) so we've just never quite got there. If we didn't already have initihooks (which we rely on in our SaaS platform - which is our main source of revenue) then we would have likely done it long ago. But as we either need to integrate cloudinit with inithooks or work out how to re-implement inithooks functionality/requirements via cloudinit, it's a non-trival thing to do.

I do have 3 workaround ideas though.

----

1. If you can access the PVE UI, then you could do a similar setup - but without the cloudinit stuff (and probable less the serial stuff too?) and then just use the UI (e.g. NoVNC window) to do the install step. After install you should be able to either just use SSH or perhaps configure the serial then?

----

2. If that's not an option, then you could do the install manually. This would be a bit of an undertakin and would probably be non-trival. I did start having a look at how that might work but I soon realised it was a bit of a rabbithole, so bailed. I'd be more than happy to share more details if you wanted to pursue that path.

In essence it would probably go something like this:
- create the VM root volume (`pvesm alloc STORAGE VM_ID '' SIZE` - e.g. `pvesm alloc local-lvm 127 '' 32G`)
- partition and format it as desired (e..g using `fdisk` and `mkfs`)
- mount the ISO and unpack the squashfs to the VM filesystem
- chroot into the root volume and install grub
- [optional] add a inithooks.conf file (to set passwords etc)
- unmount everything and launch the VM - it should be good to go

----

3. If an LXC template is an option, you could use the relevant template instead? In case you aren't aware, we provide LXC templates via Proxmox but the new v18.0 builds aren't yet available. However, we have just built the first few, we just haven't updated the PVE index yet (very soon). But in the meantime, you could download the template (and hash file) via these URLs:
```
http://mirror.turnkeylinux.org/turnkeylinux/images/proxmox/debian-12-turnkey-bagisto_18.0-1_amd64.tar.gz
http://mirror.turnkeylinux.org/turnkeylinux/images/proxmox/debian-12-turnkey-bagisto_18.0-1_amd64.tar.gz.hash
```
----

To provide better hardware support, we intend to rebase on the default Debian installer as some point (possibly v19.0). Hopefully that should fix the initial graphics issue. As I noted, we also hope to support cloudinit, but no idea on that one.

**Comment by JedMeister** [comment]
> If an LXC template is an option, you could use the relevant template instead? In case you aren't aware, we provide LXC templates via Proxmox but the new v18.0 builds aren't yet available. However, we have just built the first few, we just haven't updated the PVE index yet (very soon). But in the meantime, you could download the template (and hash file) via these URLs:

**Update:** The v18.0 LXC releases should now be available direct via PVE UI or CLI. E.g.:

```
pveam update
pveam available --section turnkeylinux
# pveam download <STORAGE> <TEMPLATE> # e.g.:
pveam download local-lvm debian-12-turnkey-bagisto_18.0-1_amd64.tar.gz
```

**Comment by merkys7** [comment]
**Thank you so much for the support.** 

For any proxmox users who will be having this issue
```
graphics initialization failed
Error setting up gfxboot
boot:
```

 - change the display settings from serial to vga in VM settings (facepalm)

**Comment by JedMeister** [comment]
Glad to hear that you worked it out and it was so simple. Thanks too for posting back. Good luck with it all.

Also FWIW we generally do support via our [forums](https://www.turnkeylinux.org/forum/support). Unfortunately due to spammers, we've had to disable auto account approval. So if you want a (free) website user account (so you can create new threads on the forums) please [sign up](https://www.turnkeylinux.org/user/register) and either do a guest post on [this thread](https://www.turnkeylinux.org/forum/general/tue-20230418-1616/post-thread-if-you-are-awaiting-account-approval) (be sure to add the same email address to the guest post as you registered with - it will remain unpublished until I approve it). Alternatively, shoot me an email (via support AT turnkeylinux.org) from the same email as you registered.
