### ISSUE TITLE
TKLBAM migrations losing ConfConsole

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#188]
I have had 2 TKLBAM migratins where I lost confconsole in the start of the new system (actually after restore and restart).  I get dropped into a Shell session inside the Console, need to log in (which ConfConsole does not require).  I found in the last one that I could type ConfConsole and get it back.

I had another series, using TKLBAM on Magento BareMetal machine moving to Magento OVF image in VMWARE that the IP configuration was garbled and I was not able to "get it back".   Ended up doing a series of TKLBAMS on Folders and Databases excluding packages and all but the Magento Folder to get a generally workable system.  Took about 3 Restore Cycles.  Definitely a long process.

**Comment by JedMeister** [comment]
We've had no further reports of this not had it confirmed by any other users. If you are still experiencing this or experience it again please feel free to reopen it.
