### ISSUE TITLE
Apply better fixclock hook fix for containers

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1885]
As per #1170, by default TKLBAM will fail on LXC (and Docker and I imagine any other containerisation) - bare metal and "proper" VMs are fine (assuming they can update their own clock - and if not an error is appropriate).

The workaround implemented previously (in buildtasks) simply made the fixclock hook script non-executable at build time. However, it has come to my attention that it can become executable again post initial setup. I assume that happened via updated TKLBAM package.

So a better fix is needed. Use of `systemd-detect-virt` seems like the best approach (i.e. detect containerisation at runtime).

**Comment by JedMeister** [comment]
Proposed fix: https://github.com/turnkeylinux/tklbam/pull/18

Also required: https://github.com/turnkeylinux/buildtasks/pull/78

**Comment by Christie018** [comment]
I've reviewed and approved the suggested code changes to close this tracker issue.
