### ISSUE TITLE
'Perfect' Forward Secrecy or PFS in all TurnKey appliances that use OpenSSL

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#189]
`John Carver` suggests in a [comment](http://www.turnkeylinux.org/blog/heartbleed#comment-19837) on the [TKL Heartbleed blog announcement](http://www.turnkeylinux.org/blog/heartbleed) that it might be a good idea to implement 'Perfect' Forward Secrecy or PFS in all TurnKey appliances that use OpenSSL.

See his comment for details.

**Comment by qrntz** [comment]
@JedMeister, I believe this was dealt with as a part of the hardening effort.

**Comment by JedMeister** [comment]
:+1:
