### ISSUE TITLE
Leantime Maintainer Here: Can you all sync up with us on image updates? 

### ISSUE THREAD

**Issue by marcelfolaron** [turnkeylinux/tracker#1897]
Hi Team,

I am the maintainer of Leantime (https://github.com/leantime/leantime) and we have received an influx of support request from users using the Turnkey Linux Image of Leantime. Unfortunately you are way behind  on versions which is causing frustrations on the user side who think that this is a Leantime issue. 

Any process to get on a better update cadence?

**Comment by JedMeister** [comment]
Hi @marcelfolaron. I'm sorry to hear that our Leantime appliance is causing both you and our mutual users frustration.

FWIW we're working through a major version update for all our appliances (i.e. rebasing on Debian 12/Bookworm) in batches. We're (finally) implementing automated smoke tests at build time in an effort to speed up our release cycle. Unfortunately that has involved more friction that we had anticipated and somewhat ironically is making this major release slower than usual...

Regardless, I will ensure that we prioritize Leantime for the next batch of updated appliances.

In the meantime, is there anything else we could do to assist and reduce friction?

**Comment by marcelfolaron** [comment]
Thanks, appreciate the insight. I think getting turnkey to our latest version 3.0.x will help a lot. Even on our end since we can then help users through our plugin marketplace and other means of updates. We are working on a leantime updater as well as system check that would help as well but that is still a little bit away. 

Keep me in the loop. Thanks. Will close this for now.

**Comment by JedMeister** [comment]
Thanks for your understanding.

Also, I just realised that I didn't give any indication of ETA. FYI assuming that we don't hit any issues, my goal is to release the updated Leantime appliance by early next week.
