### ISSUE TITLE
[TKLBAM Webmin module] hide backups that apply to other servers

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#190]
It has been suggested by `Charles` in [the forums](http://www.turnkeylinux.org/forum/support/20140410/hub-question-about-backups) that it would be useful if by default the TKLBAM Webmin module only showed the backup that relates to that particular server. I still think that it would also be useful if the other backups could be shown...
##

**Comment by lirazsiri** [comment]
I agree that reducing the number of backups the users can see by default would improve the user experience a bit. By default you shouldn't necessarily see backups you can't restore, because they don't match your sever's profile, unless you ask for that explicitly.

I'd welcome other ideas.

**Comment by JedMeister** [comment]
I think that your solution would be fine. Perhaps show just backups that relate the that particular server (backup ID); but with option to show all backups (or ideally backups that match the profile and all backups as separate options). That's my 2c anyway...

**Comment by JedMeister** [comment]
It has recently been noted on the forums that it can sometimes be confusing when you have multiple backups that relate to individual instances of the same appliance. Perhaps 3 layers of filtering? E.g. All, All of this type of appliance, only this particular server.
