### ISSUE TITLE
New appliance: Laravel

### ISSUE THREAD

**Issue by kefniark** [turnkeylinux/tracker#191]
Hello,

During the last few days, I worked on a new appliance.
This appliance's goal is to provide an installation of laravel based on tkldev.

During this development, I found some people who are looking for the same kind of project : http://www.turnkeylinux.org/forum/general/20131017/laravel-4-php-framework-appliance

I already posted about it on the candidates whiteboard.
But I read in the documentation that I should also create a new ticket here. (https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/development/new.rst)

### Laravel 4.1 : PHP Framework
* Supporter : @kefniark
* http://laravel.com/
* https://github.com/kefniark/turnkey-laravel

Best Regards

**Comment by JedMeister** [comment]
@kefniark Sorry it has taken us so long so far... TBH it is embarrassing :frowning: And I imagine that having to wait this long to see code you wrote actually make it to a release must be frustrating! I imagine that it certainly wouldn't be very motivating...

Anyway, we are (finally) working on a new release (v14.0) that we won't be getting sidetracked from! (I promise!)

I was just going to get someone else to update your code for the v14.0 release (with the latest version of Laravel) but thought perhaps I should check with you first. Are you at all interested in updating your appliance or would you like me to get someone else to do it?

**Comment by JedMeister** [comment]
@kefniark Laravel will be a great appliance to add to TurnKey. As I said, sorry that we have taken so long to look at including it. Unfortunately though the build is now out of date (obviously not your fault). I was hoping that you might be able to help us update it so we can include it in the v14.0 release.

If you (or someone else) can't help out updating real soon, then I will need to re-peg to v14.1

**Comment by JedMeister** [comment]
merged to tkl library: https://github.com/turnkeylinux-apps/laravel
