### ISSUE TITLE
TKLBAM: fixclock hook bug

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1910]
This issue is fixed - see: https://github.com/turnkeylinux/tracker/issues/1910#issuecomment-1996433044

----

Jonathan has reported a bug in the [TKLBAM fixclock-hook script](https://github.com/turnkeylinux/tklbam/blob/master/contrib/fixclock-hook) via the [forums](https://www.turnkeylinux.org/forum/support/wed-20240306-1129/tklbam-backup-failing-due-fixclock-problem).

As he notes, the fix is to add:
```
from typing import Optional
```

**Comment by hodgiers** [comment]
Can confirm this fixes the issue when the import statement is added to "/etc/tklbam/hooks.d/fixclock"

**Comment by JedMeister** [comment]
I've just pushed an update that fixes this (and some other tidying). I'll get a colleague to do a code review. Once that's done, I'll rebuild and push to the apt repo ASAP.

**Comment by JedMeister** [comment]
I've just pushed a fixed version of tklbam to our apt repo. To install it:
```
apt update
apt install tklbam
```
