### ISSUE TITLE
dpkg-vendor --query Vendor returns Debian - should return TurnKey Linux

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#196]
`dpkg-vendor --query Vendor` According to Debian if this prints 'Debian' then you need to patch base-files in your distribution to add a new file in /etc/dpkg/origins/example containing information about your distribution...
##

**Comment by JedMeister** [comment]
Hey @lamby - do you have any advice on this?

I was pretty keen to update this ages ago, but we were concerned about what might break if we did this. As noted in https://github.com/turnkeylinux/common/pull/12, sometime ago there were reports of some packages breaking after this was done. I recall reading someone suggesting that we should do it anyway, then issue bugs against any packages that break, but we'd rather not have those sort of issues if we can avoid it, so would rather wait until that concern is eliminated (or at least reduced).

Do you have any insight/suggestions/etc?

**Comment by lamby** [comment]
[adding assign so I don't lose it]

**Comment by lamby** [comment]
@JedMeister 

First up, why do you want this? :)  It's hardly really exposed to the user - the ``dpkg-vendor`` system is quite obscure, even for a DD.

Secondly, where is your existing origin file? I can see the symlink foo, but I can't find the file you were inserting. Did it contain ``Parent: Debian`` ooi?

> someone on the mailing list (a guy from Tails perhaps?) said that it broke some package installs so they changed it back

Thirdly, I think getting more details here is the next step. What broke..? What was the impact..? It might be fixable elsewhere.

**Comment by JedMeister** [comment]
@lamby 

----

>First up, why do you want this? :) It's hardly really exposed to the user - the dpkg-vendor system is quite obscure, even for a DD.

Because Paul Wise (pabs) asked us to, back when we first joined the Debian Derivatives Census in 2014:
> The page is missing a dpkg vendor field. It is important that
> Debian derivatives set this properly on installed systems and
> mention the value of the field in the derivatives census.

It seems to be a pretty common request of freshly signed up Debian Derivatives; as per:
https://wiki.debian.org/Derivatives/CensusQA#dpkg_vendor_issues

----

>Secondly, where is your existing origin file? I can see the symlink foo, but I can't find the file you were inserting. Did it contain Parent: Debian ooi?

The pull request I originally issued is [here](https://github.com/turnkeylinux/common/pull/12/files)
But yes it does contain `Parent: Debian` (see [here](https://github.com/JedMeister/common/blob/14b2331259fa0ce4c539e38b64e82a604dd3f10a/overlays/turnkey.d/dpkg-vendor/etc/dpkg/origins/TurnKey#L4))

----

>>someone on the mailing list (a guy from Tails perhaps?) said that it broke some package installs so they changed it back
>Thirdly, I think getting more details here is the next step. What broke..? What was the impact..? It might be fixable elsewhere.

Fair and reasonable point. In retrospect, I probably should have chased the original conversation up and posted that at... Also as context, Paul suggested that if anything breaks, then those particular packages should have bugs issued against them. 

FWIW, it was hLinux (not Tails) that reported issues. The full thread (inc my 2c) [starts here](https://lists.debian.org/debian-derivatives/2015/05/msg00001.html), but the specific bit that raised my concerns was posted by Josh of hLinux:

>We originally modified /etc/dpkg/origins/default to point at our own 
file that stated: "Vendor = hlinux" In doing so we discovered that 
this modified lsb_release and caused some applications to fail to
install as they were unable to determine the underlying distribution.
The prime example is OpenStack's diskimage-builder was expecting
either Debian or Ubuntu and failed with other values. Is there a
better method? Or should we instead be working with the software
vendors to not hard code specific actions based off this value?

And Patrick from Whonix (where my erroneous memory of Tails probably comes from):

>"apt-get source package" will show "dpkg-source: warning: failed to
verify signature"
>
>https://www.whonix.org/wiki/Download#.22apt-get_source_package.22_will_show_.22dpkg-source:_warning:_failed_to_verify_signature.22

**Comment by lamby** [comment]
@JedMeister 

Thank you so much for the prompt, detailed and well-researched reply. :)

I think we should simply apply this change and fix any breakage. Whilst it might break some random third-party installer, we cannot work around all the problems in those especially as they cause so many other (bigger) problems such as installing to weird paths outside of the package management system.

> "apt-get source package" will show "dpkg-source: warning: failed to
verify signature"

Sounds like a different problem. (and your link doesn't seem to link to that quote?)

**Comment by JedMeister** [comment]
>>"apt-get source package" will show "dpkg-source: warning: failed to
verify signature"
>
>Sounds like a different problem. (and your link doesn't seem to link to that quote?)

Sorry the link was part of Patrick's message, I didn't link to the post where he said that; FWIW, [here it is](https://lists.debian.org/debian-derivatives/2015/05/msg00004.html).

Ok awesome, let's just do that then!

**Comment by JedMeister** [comment]
https://github.com/turnkeylinux/common/pull/12 has been merged. Closing this.

**Comment by JedMeister** [comment]
For full reference (may not be 100% relevant, but posting it anyway...):
