### ISSUE TITLE
Invoici Ninja 5.9 ---> Php 8.2

### ISSUE THREAD

**Issue by Adefx** [turnkeylinux/tracker#1961]
Hi , this is a warning for everyone, Invoice ninja 5.9.x use now php 8.2 
Many installation are stuck with the message  "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". "

Is there a step by step procedure to update the Turnkey machine, 
either upgrading the PhP version to 8.2 ? 

Thanks a lot

**Comment by JedMeister** [comment]
Hi there,

Sorry there isn't a quick easy answer - especially with the limited info you've provided. I don't really have time to give a full/proper answer, but I can't help myself! :)

I assume that you aren't running TurnKey Invoice Ninja v18.0? FYI that's currently the latest Invoice Ninja version - all v18.x TKL apps are based on Debian 12/Bookworm - which ships with PHP v8.2.

If you are running  a version older that v17.0, then I highly recommend some sort of data migration/OS upgrade (either of the first 2 options noted below).

If running v17.x, then you'll still need to do that at some point, but leaving that for now is legit. The underlying Debian OS will be supported by the Sec team for another few months, then after that by [the LTS team until August 2026](https://wiki.debian.org/LTS). So  just updating PHP on v17.x is an option.

The options for getting PHP 8.2 when running v17.x are (in no particular order):
- Use [TKLBAM](https://www.turnkeylinux.org/docs/tklbam) (our built in encrypted data backup and migration tool) to migrate and restore your Invoice Ninja data to v18.x. As noted on the doc page, that might require some manual tweaks. Worst case, it can make transferring and restoring just your Invoice Ninja date easier. I.e. the `/var/www/invoice-ninja` directory and `invoice-ninja` DB.
  - I offer support with that - see details below.
- Manually migrate the `/var/www/invoice-ninja` directory and `invoice-ninja` DB to a new v18.x instance.
  - I can offer "best effort" support via our forums - more details below; and/or
    - There are a number of threads regarding that on the invoice ninja forums. E.g. [here](https://forum.invoiceninja.com/t/migrating-to-another-server/10243), [here](https://forum.invoiceninja.com/t/data-migration-to-another-server/13130/10) and [here](https://forum.invoiceninja.com/t/invoice-ninja-selfhost-migration-to-new-server-host/2275) - again in no particular order.
    - They may also be able to assist with the migration via their forums.
    - There are likely many other tutorials/guides online.
- Upgrade the Debian base to 12/Bookworm - using the general Debian "in-place" [upgrade procedure](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-upgrading.en.html).
  - Again, I'll offer "best effort" support via our forums - see below.
  - IIRC there are some instructions/guidance already on our forums (try googling something like "turnkey linux upgrade OS" - or similar; and/or
  - There are lots of tutorials/guides re Debian upgrade online. OTTOMH, the only TurnKey specific step is updating the TurnKey apt signing key. Let me know if you need that.
- Update PHP using https://deb.sury.org/ - keeping your current OS base.
  - I recommend you download and run the (community provided) PHP upgrade/version change helper script, notes below; and/or
  - Access "best effort" support via our forums - again see below.

---
TKLBAM/Hub Support

The TurnKey Hub is our main source of revenue. It keeps the lights on, the servers chugging and provides some (well below market rate) financial compensation for our dedicated part-time contract developers. Financial support is warmly welcomed, although no obligation.

Free one-on-one support is included with paid Hub plans - with some limitations.

Primarily we support TKLBAM, but support will be extended regardless of upgrade path.

Ask any Hub related questions via Hub "in app" support - accessible once the sign up process is started. Expected response time is within one work day, usually less.

Free Hub plans get same "best effort" support as noted below - except for Hub specific questions (via Hub support).

----

PHP upgrade script, Manual data migration and Debian upgrade support:

As noted free "best effort" support via our [forums](https://www.turnkeylinux.org/forum/support) is available. As noted above, some available via paid Hub plan support.

The PHP upgrade via our script (see below - should work on v16.0+) will probably receive quicker support - as that is helping us with testing and quality control. Other upgrade/migrations will get "best effort" support regardless.

Forum access requires signup and manual account approval. There is a thread to guest post for account approval (linked in automated welcome email). Although when I'm under the pump, it can take a little while (up to a week or so) before I get to do approvals. I'm currently working on getting someone to help me out with that, but not sure if/when that will be. If you note you're the same person from this thread will likely make it a bit quicker.

---

To download and run the PHP upgrade script - assumes root:

```
# download and make executable
wget -O /usr/local/bin/tkl-upgrade-php https://raw.githubusercontent.com/turnkeylinux/common/18.x/overlays/php/usr/local/bin/tkl-upgrade-php
chmod +x /usr/local/bin/tkl-upgrade-php

# run interactive script
tkl-upgrade-php
```

**Comment by JedMeister** [comment]
Due to lack of response, I'm closing this now. If you have anything further to add, please post back and it can be reopened.
