### ISSUE TITLE
outdated Nextcloud 

### ISSUE THREAD

**Issue by icf20** [turnkeylinux/tracker#1964]
> The version you are running is not maintained anymore.

who is doing the maintenance for Nextcloud if upstream is not followed?

**Comment by JedMeister** [comment]
Thanks for your feedback.

I know it's far from ideal, but we plan to push an updated Nextcloud appliance ASAP - should be within the next week or so.

In the meantime, you should be able to update Nextcloud itself as per their docs. If you run into any issues, please let me know.

FYI we have a large library of appliances to maintain and a small dev team. We've been doing this for quite a while (~15+ years) and have accumulated a lot of technical debt over the years and many of our processes still require manual intervention. We're currently focussed on trying to clean up the accumulated debt and automating as much as we can to allow for more regular releases. We're still not there yet...

**Comment by JedMeister** [comment]
Oops, meant to post back last month when we released an updated Nextcloud appliance. Includes newer v29.x
