### ISSUE TITLE
Help me configuring Let's Encypt SSL/TLS certificates.

### ISSUE THREAD

**Issue by orlipr84** [turnkeylinux/tracker#1989]
Hi friends,

I downloaded the AVideo app from TurnKey and I want to configure the Let's Encrypt certificate to be able to access the site via HTTPS. But, in my particular case, I already have the Let's Encrypt certificate generated and I just need to configure it manually. I have tried all possible ways and it doesn't work. Any help or suggestions?

Thanks.

**Comment by JedMeister** [comment]
Hi Orlando. I hope you are well my friend. :grin:

I've already approved your account on the website and replied there, but seeing as you've given me a bit more info here I'll reply here now. I hope this translates ok, please ask if anything doesn't make sense.

First let me give you some info about our default set up.

On all TurnKey servers, the default SSL/TLS certificate & key files are `cert.pem` and `cert.key` in `/etc/ssl/private`. I.e.:
```
# ls -l /etc/ssl/private/
total 16
-r-------- 1 root root     1704 Oct  7 03:26 cert.key
-r-------- 1 root root     3340 Oct  7 03:26 cert.pem
-r-------- 1 root root      424 Oct  7 03:26 dhparams.pem
-rw-r----- 1 root ssl-cert 1700 Apr 10 23:01 ssl-cert-snakeoil.key
```
The `cert.pem` is the cert, key and dh_parameters all in one file. I.e.:
```
# grep -- '----' /etc/ssl/private/cert.pem
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
-----BEGIN DH PARAMETERS-----
-----END DH PARAMETERS-----
```
The `cert.key` is just the key on it's own.

It may be easiest to just to replace the cert and key files there? FYI that same certificate is also used for Webmin (https on port 12321).

For example if your certificate file and key file are `/root/example.pem` and `/root/example.key`, you could replace the existing `cer.pem` & `cert.key` files like this:
```
cat /root/example.pem > /etc/ssl/private/cert.pem
cat /root/example.key >> /etc/ssl/private/cert.pem
cp /root/example.key  /etc/ssl/private/cert.key
```
Alternatively, if you would rather use your existing keys where they are, another option is to make Apache use them. Do that by adding them to the Avideo Apache virtual host config file; `/etc/apache2/sites-available/avideo.conf`. Adding cert & key locations there will override the default (set in `/etc/apache2/mods-available/ssl.conf`).

Using `/root/example.pem` and `/root/example.key` again as an example; edit `/etc/apache2/mods-available/ssl.conf`. Between the `<VirtualHost *:443>` and `</VirtualHost>` lines, add these 2 new lines:
```
SSLCertificateFile         /root/example.pem
SSLCertificateKeyFile   /root/example.key
```

No matter which way you go, as you probably already know, you'll need to restart Apache to apply the changes:
```
systemctl restart apache2
```

I hope that helps.

**Comment by orlipr84** [comment]
I am so sorry for the delay in responding, I had run out of mobile data package and accessing the internet in my country costs a lot of money.

I am very grateful for the prompt response and especially for the excellent explanation. I was able to configure the Let's Encrypt certificates perfectly. Thank you very much and keep up the good work.

**Comment by JedMeister** [comment]
You are most welcome. I'm glad that helped and thank you for your kind words.

Take care and hopefully speak another day.

I'll close this now.
