### ISSUE TITLE
Turnkey Linux Core confconsole fails to add sasl password with spaces in it

### ISSUE THREAD

**Issue by valankar** [turnkeylinux/tracker#1994]
Gmail app passwords are auto-generated and have spaces in them. Suppose my password is "XXXX YYYY".

When I run confconsole and setup an SMTP relay, I can enter the gmail information and the test actually works fine. However, sending email fails on Postfix.

Looking at `/etc/postfix/sasl_passwd`, it contained:

```
[smtp.gmail.com]:25 my@email.com:XXXX
```

It is missing the rest of the password. When I manually edit the file to fix the password and run postmap, it works.

I am using `turnkey-wireguard-18.1-bookworm-amd64`.

**Comment by OnGle** [comment]
Thanks for the report, as far as I can tell the issue lies here (unquoted ``$@``)

https://github.com/turnkeylinux/confconsole/blob/51da6b3b2c7fd6d3e76256dce0e215e7597c61c5/plugins.d/Mail_Relaying/mail_relay.sh#L75

When I find a moment I'll post a PR that addresses this

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux/confconsole/pull/87

I'll rebuild and push to the TKL apt repo ASAP.

**Comment by JedMeister** [comment]
The updated confconsole package (`v2.1.6+2+ge808780`) which resolves this issue is now available in the `bookworm`  (v18.x) TurnKey apt repo.
