### ISSUE TITLE
Better docs for File server NFS and firewall on LXC

### ISSUE THREAD

**Issue by UncleVic** [turnkeylinux/tracker#1995]
I set up a File Server into the LXC container.
Samba and something else work out of the box. But NFS works just if I open the whole eth0.
I tried opening TCP/UDP ports 111, 2049, 32803, 32769, 875, 892, 662, but it doesn't work.

Which rules do I have to add for NFS?

**Comment by JedMeister** [comment]
I see that you resolved this as per your summary here: https://github.com/turnkeylinux/tracker/issues/1750#issuecomment-2433408816 - thanks for confirming. To repeat it:

>1. `nfs-kernel-server` on the host
>2. the privileged container
>3. `lxc.apparmor.profile: unconfined`
>4. open NFS ports in the Turnkey firewall

I was going to close this but am going to leave it open as a "feature request" to provide better documentation. Any suggestions on where might have made it more obvious for you?

**Comment by JedMeister** [comment]
Closing this and relevant documentation regarding LXC server NFS shares has now been added to the website:

https://www.turnkeylinux.org/docs/fileserver
