### ISSUE TITLE
Turnkey APT Archive appears to be down

### ISSUE THREAD

**Issue by JordanTB** [turnkeylinux/tracker#2005]
While running apt update on my turnkey containers  (Specifically the Nextcloud and Ansible ones), I encountered this error. From reading it appears this occurs when the apt archive is down, so I figured I should report it.

Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Ign:3 http://archive.turnkeylinux.org/debian bookworm-security InRelease                    
Ign:4 http://archive.turnkeylinux.org/debian bookworm InRelease                             
Ign:3 http://archive.turnkeylinux.org/debian bookworm-security InRelease                    
Ign:4 http://archive.turnkeylinux.org/debian bookworm InRelease
Ign:3 http://archive.turnkeylinux.org/debian bookworm-security InRelease
Ign:4 http://archive.turnkeylinux.org/debian bookworm InRelease
Err:3 http://archive.turnkeylinux.org/debian bookworm-security InRelease                                      
  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
Err:4 http://archive.turnkeylinux.org/debian bookworm InRelease                                               
  Unable to connect to archive.turnkeylinux.org:http:
Fetched 48.0 kB in 7s (6789 B/s)                                                                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/bookworm-security/InRelease  Could not connect to archive.turnkeylinux.org:80 (54.83.15.172). - connect (111: Connection refused)
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/bookworm/InRelease  Unable to connect to archive.turnkeylinux.org:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.

Thanks in advance for any input!

**Comment by Am0din** [comment]
I am receiving the same error when updating as well, so it's not just you.  They are most likely down (again).

**Comment by JedMeister** [comment]
Yep - it was :( Should be back up again now.

FWIW the files exist elsewhere (not on that server) and the mount broke for some reason - which had a cascading effect, crashing the webserver.

We made some changes to patch it up sometime ago, and it's certainly made it more reliable - but obviously not enough.

We're slowly working through all our technical debt and designing a better way to host our apt repo is on the list - I'll move it up the priority list.

**Comment by JedMeister** [comment]
Going to close this now, but please post back if you continue to have issues.
