### ISSUE TITLE
Can't login to phpNuke admin user account

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#204]
As per [this forum thread](http://www.turnkeylinux.org/forum/support/20140501/turnkey-phpnuke-install-completes-i-cannot-login-admin-console) I have [tried to set/reset the admin user password](http://www.turnkeylinux.org/forum/support/20140501/turnkey-phpnuke-install-completes-i-cannot-login-admin-console#comment-20091) all to no avail...

**Comment by JedMeister** [comment]
This bug is still occurring in v14.0. It's a showstopper and unfortunately means that we will probably have to retired this product.

**Comment by jeroenpeters1986** [comment]
At this moment, http://www.phpnuke.org/modules/Release/files/phpnuke-release-8.2.4.tar.gz isn't even available. http://www.phpnuke.org seems to be replaced by a generic "app review" site.

**Comment by jeroenpeters1986** [comment]
Ah nice, I found https://www.phpnuke.org/modules.php?name=release, which points to https://bitbucket.org/phpnuke/phpnuke/overview, it even has versions.

Do you guys want me to give it another try?

**Comment by JedMeister** [comment]
It depends?!

If you really love PHPNuke and don't want to see it get retired from the TKL lineup; please be my guest! :smile: 

If you're just looking for something to do then I'm sure I can find you something! :stuck_out_tongue: 

One of our top guys already spent a few hours and he had the same issues (that the v13.0 release had - i.e can't log in with the password set by the inithook) with the latest version. So my feeling is that it isn't worth the effort. But of you really want to got for it. And if you can prove me wroing then I'm totally coolk with that! :+1: I'll even buy you a :beer: next time I'm in your part of the world! :wink:

**Comment by jeroenpeters1986** [comment]
hehe lol, I have some experience with phpNuke (v6), but the product itself really is End Of Life as far as I know (no development since late 2013, and not that active before that)

**Comment by JedMeister** [comment]
phpNuke appliance being deferred due to this still being an issue with the current version of phpNuke. As such this issue is being closed.
