### ISSUE TITLE
Just show me the IP!

### ISSUE THREAD

**Issue by net127** [turnkeylinux/tracker#205]
In Docker builds, rather showing:

    CID=$(docker ps -l -q)
    CIP=$(docker inspect -format='{{.NetworkSettings.IPAddress}}' $CID)

which, when run
a) gives: Warning: '-format' is deprecated, it will be replaced by '--format' soon. See usage.
b) does not give any output
(in Docker version 0.9.1, build 3600720)

how about just showing the output of:
ifconfig | grep "inet addr" | grep -v "127.0.0.1" | cut -d' ' -f 12

**Comment by JedMeister** [comment]
I'm not sure if this will still be relevant for v14.0...
