### ISSUE TITLE
/etc/skel should contain copies of .bashrc, .bashrc.d, .profile etc

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#21]
Registered on [lp#blueprints](https://blueprints.launchpad.net/turnkeylinux/+spec/etc-skel-should-contain-user-env-similar-to-root) by @JedMeister on 2012-01-10

#### Description

Under current setup new users don't automatically get all the cool bash stuff that is set up for the root user by default (such as tab-complete etc). It would be great if these files were copied across to /etc/skel, so all new users also get these. See discussion here: http://www.turnkeylinux.org/forum/support/20120109/shell-works-great-root#comment-11580

**Comment by JedMeister** [comment]
Just read through the forum and looks like this got fixed (or perhaps was never broken) somewhere along the line... Closing this...
