### ISSUE TITLE
Resque-web in control panel

### ISSUE THREAD

**Issue by wvengen** [turnkeylinux/tracker#215]
It would be great to have a [resque](https://github.com/resque/resque) web console in the  control panel when a Rails application uses it.

Resque-web could be run standalone, bound to localhost, and reverse proxied by the control panel.Or the webmin webserver could serve it using passenger, or the main webserver could serve it in a subpath. (I think the first would be the easiest.)

**Comment by JedMeister** [comment]
I'm currently doing a tidy up on the tracker, getting ready to start work on v14.1. 

I'd like to understand a little bit more about this suggestion (as I don't know much about Ruby/Rails stuff).

Are you suggesting that this would be of value to all Rails appliances? Or is it more of a dev tool? I.e. do you suggest that we add it just to the Rails appliance? If not what is the added value for other Rails based appliances?

**Comment by wvengen** [comment]
For sysadmins it is useful to see which background jobs failed and what has been done, that's where resque-web can be a great help.

There could be a redis config in common/conf that appliances could include. E.g. one for redis, which installs it and makes sure it is started at boot, and one for resque, which would depend on redis but also adds resque-web. Or have resque-web explicitely.

Does that give a bit of clarity?

**Comment by JedMeister** [comment]
Yep. Thanks. for taking the time to explain. :smile:

**Comment by qrntz** [comment]
Sounds good. Only makes sense for Redis-including appliances, but should be rather straightforward to set up.

**Comment by JedMeister** [comment]
Let's look at this again for v15.0

**Comment by JedMeister** [comment]
Moving to v15.1...

**Comment by JedMeister** [comment]
I'm going to shut this one for now. I'm still potentially open to including it, but it's not something we've had much request for and unless a community member is keep enough to look at implementing it, I doubt we'll get to it.
