### ISSUE TITLE
Consider adding Adminer and phpSysInfo to TurnKey LAMP

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#218]
Special mentions by High Mobley in the BOSSIE 2013 awards:

1) Adminer is a great alternative to phpMyAdmin. It's a single PHP file
and easy to install. The UI is simpler and more intuitive than
phpMyAdmin. Adminer also has full support for features such as foreign
keys, grouping Select results, sorting results by multiple columns, easy
downloading of blob field contents, and editing fields in multiple rows.
Adminer can work with MySQL, PostgreSQL, SQLite, Microsoft SQL Server,
and Oracle Database, whereas phpMyAdmin supports only MySQL. Adminer
works with older versions of MySQL and PHP as well.

2) phpSysInfo

Sometimes you just want a simple tool to do a simple job. A set of PHP
scripts that pulls data from the /proc file system and lays it out
neatly on a Web page, phpSysInfo shows key information about your
server, such as RAM and CPU utilization, attached drives and USB
devices, available disk space, networking, hard drive SMART (Self
Monitoring Analysis and Reporting Technology) info, and more. For busy
admins on the go, there's even an Android client app for phpSysInfo.

**Comment by JedMeister** [comment]
1) I think that a transition to Adminer is a great idea. We then also get a consistent UI for appliances that utilise MySQL and PostrgerSQL! 

2) phpSysInfo sounds great. But what sort of setup would you recommend? Another specific port? (e.g. like Webmin, Webshell and phpMyAdmin - probably 12323) or something else? Would(/wouldn't) there be value in adding this to other appliances too!?

**Comment by JedMeister** [comment]
Closing this issue. 

phpMyAdmin adn phpPgAdmin are being replaced with Adminer in v14

The question re phpSysInfo is now part of #358
