### ISSUE TITLE
Hasteserver app by Rik Goldman

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#221]
Hasteserver is a node.js pastebin clone. Rik Goldman (AKA ghoulmann) used TKLDev to develop a TurnKey installation:

https://github.com/ghoulmann/hasteserver-with-TKLDEV
##

**Comment by JedMeister** [comment]
I'm guessing this is dead so closing for now. Please feel free to reopen, or open a new issue.
