### ISSUE TITLE
Ghost app by Rik Goldman

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#222]
Ghost is a beautiful blogging platform. Rik Goldman used TKLDev to create a TurnKey Ghost app:

<s>https://github.com/ghoulmann/tkl-ghost</s>
https://github.com/ghoulmann/ghost-tkldev
##

**Comment by JedMeister** [comment]
@ghoulmann - just thought I'd highlight this thread for you :smile: 

Current work in progress: https://github.com/ghoulmann/ghost-tkldev

**Comment by JedMeister** [comment]
Just realised that this issue was still open. We should have closed it when we released the Ghost appliance (quite some time ago now...)
