### ISSUE TITLE
LAN LMS app developed by LanAcademy.org

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#224]
The LAN Server is a Turnkey Linux based MOOC server:

https://github.com/lanacademy/lan-server-tkl

MOOC is a massive open online course:

https://en.wikipedia.org/wiki/Massive_open_online_course

**Comment by JedMeister** [comment]
It looks like this software is not "production ready". I'm closing this issue but please feel free to reopen (or open a new one) if you disagree or things change...
