### ISSUE TITLE
Minecraft/McMyAdmin server by Eric Young

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#228]
Eric Young used TKLDev to create a TurnKey Minecraft/McMyAdmin server:

https://github.com/tssgery/mcapp

Minecraft is a game about breaking and placing blocks. At first, people built structures to protect against nocturnal monsters, but as the game grew players worked together to create wonderful, imaginative things.
##

**Comment by JedMeister** [comment]
I'm guessing this is dead so closing for now. Please feel free to reopen, or open a new issue.
