### ISSUE TITLE
OwnTracks App by OwnTracks upstream

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#229]
OwnTracks upstream devs used TKLDev to develop a TurnKey Owntracks backend:

https://github.com/owntracks/turnkey-owntracks
##

**Comment by JedMeister** [comment]
@jpmens - is this release ready? Or will it be in the next month or 2?

**Comment by jpmens** [comment]
@JedMeister It is currently far from ready, unfortunately, and I don't see this happening soon ...

**Comment by JedMeister** [comment]
That's unfortunate but thanks for the update. If we get a chance we may even be able to tidy it up a bit; but probably unlikely.

**Comment by JedMeister** [comment]
Closing this now as it seems that the effort has been abandoned. That doesn't mean that we will never release an OwnTracks appliance, but it won't be a priority.
