### ISSUE TITLE
Drupal Wetkit app by Dave Samojlenko

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#230]
Dave Samojlenko used TKLDev to develop a TurnKey Drupal Wetkit app:

https://github.com/dsamojlenko/turnkey-wetkit-drupal

WetKit is a Drupal "web experience distribution":

https://www.drupal.org/project/wetkit
##

**Comment by JedMeister** [comment]
I'm guessing this is dead so closing for now. Please feel free to reopen, or open a new issue.
