### ISSUE TITLE
Tomcat on Apache should redirect to control panel using Javascript in index.html

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#233]
A Javascript redirection in index.html would be easier to understand and would prevent users from having to hunt down the RedirectMatch in /etc/tomcat6/mod_jk.conf. They can just drop in a different index.html if they want.
##

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/tomcat-apache/issues/5
