### ISSUE TITLE
Be safe on Rails logs permissions

### ISSUE THREAD

**Issue by wvengen** [turnkeylinux/tracker#235]
In the Rails profile, the `log` directory is `chown`ed to `www-data`, which is needed for running the webapp. In the installation script of a webapp, it is often customary to load an initial database, and perhaps do some other initialization. This may involve output to logfiles. These logfiles don't exist by default, and as the installation script often runs as root, this leaves the logfiles inaccessible to the web-process running rails later.

This is not a problem for the default `railsapp`, since it runs the database initialization in the development environment, which uses a different log. One can see that the development log is owned by root.

Suggestion: as a final step, *after* running the app install script, either
* `chown` the logdirectory and -files to `www-data`, or
* delete all logfiles, or alternatively
* touch the logfiles before `chown`ing (but that leaves non-standard logfiles prone).

**Comment by JedMeister** [comment]
@wvengen is this issue resolved in the new v14.0 version? If it is then let's close this issue. If not please let me know and we'll look to do something about it...

**Comment by wvengen** [comment]
Just checked the rails appliance, it's still a problem:
```sh
# ls -al /var/log/railsapp
total 12
drwxr-xr-x  2 www-data www-data   60 May 14 10:33 .
drwxr-xr-x 14 root     root      380 May 15 13:50 ..
-rw-r--r--  1 www-data www-data    0 May 14 10:23 .keep
-rw-r--r--  1 root     root        0 May 14 10:27 development.log
-rw-r--r--  1 www-data www-data 8553 May 14 10:34 production.log
```

**Comment by JedMeister** [comment]
So we just need to `chown -R www-data:www-data /var/log/railsapp` then right? Was that the final decision? If so it probably should just go near the end of the common/conf/rails...

Actually I just had a look. Shouldn't [this line](https://github.com/turnkeylinux/common/blob/master/conf/rails#L64) already do it!? Looks like it should to me, but obviously it's not quite happening how it should...

**Comment by wvengen** [comment]
Yes. That's because `$LOGSDIR` is a symlink, I'd say. Adding a `/` would help, I think.

**Comment by qrntz** [comment]
That was not the culprit. ```rails generate controller cp``` in the Rails appliance was!

**Comment by wvengen** [comment]
Thanks!

That leaves one question: what to do when a rails-based appliance runs a rake task in the production environment, or runs a script that outputs to a different logfile (I've seen that happen)?
* Leave chowning these files to the appliance script
* Chown the files after running the appliance script (though this would be a problem when the appliance sets up different users with different logfile permissions - haven't seen that yet though)
* Make directory group writable + setgid (unless umask is in the way)

**Comment by qrntz** [comment]
- [x] Leave chowning files to the appliance script

It's a dumb solution but also the most straightforward (= minimal possible complications).

Making good use of Monit is on the TKL roadmap, and while it's restricted to minimal system monitoring at the moment, I hope after v14.0 we'll start using the more advanced features like file permission monitoring. That would solve this issue with style.

**Comment by wvengen** [comment]
Sounds good!
