### ISSUE TITLE
Redmine automatic SVN repo creation and user access?

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#238]
Preston suggests on the forums that TurnKey Redmine should be configured to automatically create SVN repos and allow user access out of the box:

http://www.turnkeylinux.org/forum/support/20140708/redmine-automatic-svn-repo-creation-and-user-access

**Comment by qrntz** [comment]
… should we do the same for Git?

http://www.redmine.org/projects/redmine/wiki/HowTo_configure_Redmine_for_advanced_git_integration

or rather use SCM Creator?
http://www.redmine.org/plugins/redmine_scm

**Comment by JedMeister** [comment]
@qrntz - I assume from your PR that you made a decision and implemented it!? Assuming you did. And I trust your judgement! :smile:

**Comment by qrntz** [comment]
@JedMeister, I implemented management via HTTP for SVN, not yet for Git. That's doable though, as per the links.

So provided you think it's a good idea, I'll go ahead and use whatever of those two works better.

**Comment by JedMeister** [comment]
@qrntz - for sure. TBH I only had a quick glance through those links but I trust your judgement. FWIW we have had at least one request for git to be provided via "smart http"....
