### ISSUE TITLE
MySQL secure installation

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#239]
John Carver suggested reproducing the effects of the mysql_secure_installation script to tighten the screws on the MySQL configuration for the relevant TurnKey integrations:

http://www.turnkeylinux.org/forum/support/20140708/mysql-secure-installation

I'm personally all for tightening the screws... as long as it doesn't break anything or make the system harder to use out of the box.

**Comment by JedMeister** [comment]
I am closing this issue as I assume from the above discussion that the relevant code has been merged. If I've got it wrong and missed something please reopen.
