### ISSUE TITLE
New Appliance: Ansible Orchestration Engine

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#241]
Ansible is a radically simple configuration-management, application deployment, task-execution, and multinode orchestration engine.

Read the documentation and more at http://ansible.com/
The TurnKey Ansible appliance is in development and available for test at https://github.com/Dude4Linux/ansible

**Comment by JedMeister** [comment]
Where is this one up to @Dude4Linux ? Have you had a chance to test building it with the v14.0RC1 TKLDev yet?

Also any further thoughts on making the other TurnKey appliances play nice with it?

**Comment by Dude4Linux** [comment]
I rebuilt the RC4 version using v14.0RC1 TKLDev.  Started testing it this morning. No problems noted so far.  I sent an e-mail to info@ansible.com requesting permission to use their new logo to create a badge for the appliance.  If they don't grant permission, I guess we will have to use the badge I created based on the old logo which wasn't trademarked (to my knowledge).  Hope they will be cooperative.  I will need to make some updates to reflect the move to 14.0 and work on the script I described above to 'gather facts' that are specific to TurnKey appliances.  Basically you want to set a boolean variable e.g. 'turnkey' to yes if the node is a TurnKey appliance and no otherwise.  Then you would set 'turnkey_version' to 13.0, 14.0, etc.  I would also set 'turnkey_app' or 'turnkey_appliance' to the name of the appliance.  I was also thinking it would be helpful to set a variable for the version of the application, e.g. 'turnkey_app_version'.  Got hung up trying to figure out how to keep that up to date for all the different appliances.

**Comment by JedMeister** [comment]
I'm not 100% sure how it would be best leveraged but `turnkey-version` provides all the info I imagine you'd need. It's in the format `turnkey-<appliance-name>-<version-number>-<debian-codename>-<architecture>`. But I have no idea how Ansible would need to get the info...

**Comment by danhuss** [comment]
Hey guys, I went ahead and put together a quick python script to parse the turnkey-version output and should return the ansible facts. I haven't done an ansible module before so it's a bit of a guess as to if it's coming back in 100% the right format, but I didn't have any trouble running it standalone against my inventory of Turnkey and non-Turnkey boxes. 

https://github.com/danhuss/Ansible-TurnkeyLinuxFacts

**Comment by JedMeister** [comment]
Fantastic work @danhuss! :+1: 

Questions though: 
* Where does this code need to go? 
    *In all the appliances? 
    *As part of the Ansible appliance? 
*What (if any) further config needs to be done on the appliances? (if not answered above)

**Comment by danhuss** [comment]
1. it just has to go in the Ansible appliance. The nice thing about Ansible is it does all the management over SSH. other than SSH, I think the only other requirement for managed nodes is Python and a few extra python modules. All the setup should be in Ansible's documentation.
2. There's probably a couple other facts that you'd want to be able to get from managed nodes like TKLBAM status. Then maybe a couple modules to perform some Turnkey specific actions. Nothing crazy hard though.

I wasn't sure how to get it added to the appliance build off the top of my head, so I thought I'd go ahead and setup the repo like that and someone who knew how to get it in the appliance could add it. I do want to emphasize the "quick" part, it's ugly as sin and I haven't worked it into any larger playbooks or other modules yet. So I don't know how if it will end up working with other parts yet.

**Comment by Dude4Linux** [comment]
Thanks @danhuss, I'm not a python programmer (yet anyway) but I'll try to get this added to the Ansible appliance, hopefully before the release of 14.0.

**Comment by JedMeister** [comment]
lloks like this is good to go; merging with turnkey library: https://github.com/turnkeylinux-apps/ansible
