### ISSUE TITLE
ownCloud

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#242]
The latest version of ownCloud, 6.0.4, places new restrictions on the http host headers. Appliance hostnames must now match the ssl certificate and be registered in the ownCloud config.php.

I'm working on a way to automate this for 13.1

**Comment by JedMeister** [comment]
I'm going to close this issue. v14.0 will be released in the not too distant future and should include the latest stable version of ownCloud. As such this should be covered. 

If anyone disagrees please feel free to reopen :smile:
