### ISSUE TITLE
Webmin needs updating for 13.1

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#247]
When I build an appliance using TKLdev which has been updated for 13.1 i.e. common and core, I get the following message when testing webmin.

    The 1 following Webmin module updates are now available ..
    Module 	            Version 	Fixes problem
    Running Processes 	1.632 	Fixes total and free memory display on OpenVZ systems

After I apply the update, I get a new message:

    A new release of Webmin (version 1.690) is now available for download. Future updates will be released only for the latest version.

If this has already been fixed, then I need to know how to properly update my TKLdev install.

**Comment by JedMeister** [comment]
Will be v14.0 now... (looks like we'll skip v13.1)

**Comment by JedMeister** [comment]
I'll ask @alonswartz if he can build and upload latest Webmin for v13.x (Wheezy) when he builds new packages for Jessie.

**Comment by Dude4Linux** [comment]
While experimenting with OpenVAS (fork of Nessus), I found a problem with the version of Webmin currently used by TurnKey.  Webmin fails to set httpOnly on session cookies leading to the possibility of session hijacking.  The fix is in newer versions of Webmin.  See https://github.com/webmin/webmin/pull/199/files

**Comment by JedMeister** [comment]
Thanks John. That will add weight to the newer version being added to v13.x!

**Comment by JedMeister** [comment]
Webmin has been updated for v14.0 - Jessie release but I won't close this bug yes as it hasn't been backported for v13.x
