### ISSUE TITLE
New appliance: MapServer

### ISSUE THREAD

**Issue by mverwijmeren** [turnkeylinux/tracker#248]
MapServer is an Open Source platform for publishing spatial data and interactive mapping applications to the web.
- Repository: https://github.com/mverwijmeren/mapserver
- Tracker: https://github.com/turnkeylinux/tracker/wiki/MapServer
- Upstream: http://www.mapserver.org
- by @mverwijmeren

Since everything in this appliance (so far) is available in the Debian Wheezy repositories, this was not a difficult appliance to develop.
##

**Comment by COLABORATI** [comment]
@mverwijmeren - is there some more information about the personal tile server project?

**Comment by COLABORATI** [comment]
Hi, I now spent some time to understand what TKL exactly is (Google lead me here) and I am willing to spend one or two nights to learn more about the TKL development process - however, it would  be great to have a link to some information here how to get this thing to start up and run. I am willing to dig deeper into the whole TKL infrastructure, but I just want to run this app **right now**. 

I did found some [documentation](http://www.turnkeylinux.org/docs/tkldev-new-appliance) - but unfortunately the most relevant part (for me) - how to build and test an ISO - is left out (topic 16).

@lirazsiri, I found some [other documentation](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/development/new.rst) but it is much to verbose for me, atm I just want to start and test this app! It would be very nice if you would understand this usecase and make it much easier for developers / admins to take a quick dip of TKL and then, when we like it, we still can dig deeper. However, the quick start just is not here (or a link to it).

Actually I just want to know: where do I have to run this make file? In which kind of dev environment / virtual machine? 

Just a few lines of instructions would be enough, or maybe a shell script that does what is needed to get this up. THANK YOU!

**Comment by JedMeister** [comment]
FWIW our [forums](http://www.turnkeylinux.org/forum) are the best place for this sort of discussion.

But while we're here; I suggest that you [install](http://www.turnkeylinux.org/docs/installation-appliances-virtualbox)(quite dated and shows installation of a different appliance but in essence it's still relevant) and [set up](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/setup.rst) TKLDev in a VM ([VirtualBox](https://www.virtualbox.org/) is a popular cross-platform option). 

Then build TKL Core (documented on the set up page [here](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/setup.rst#c-clone-core-from-github-and-run-make).

Any major issues should result in errors and failure to build the core iso. Although if you want to be totally sure that everything worked, then you can copy out the iso that you made and install that (in a new VM - in VirtualBox or whatever you're using).

Once you have confirmed that all is well with TKLDev; then repeat the steps to make core; but with MapServer instead.

I suggest that any general TKLDev issue you post about in the forums (link above) and MapServer specific issues there too (prob start a new thread and post a link here?). Or you could post here. Or if you are sure that it's a MapServer issue (e.g. it builds ok but something is wrong or doesn't work as you expect in the running server) then on @mverwijmeren repo itself may even be the go...

**Comment by COLABORATI** [comment]
Thank you for the shortcut, seems to work! Now I feel like digging deeper into TKL, still an interesting alternative to  other remote config systems!

**Comment by COLABORATI** [comment]
The iso seems to work fine, however think there is not data in it to actually display any maps. I filed an issue here https://github.com/mverwijmeren/mapserver/issues/2 - if it is not finished, maybe I will find some time... but do not hold your breath, may take a very long time.

**Comment by JedMeister** [comment]
@COLABORATI - you are most welcome... 

Glad to hear that you find TKL/TKLDev interesting! :)

That's a pity that it doesn't contain the data to display maps. I know nothing about it so have no idea how to even begin going about that... However if you do find any info please feel free to post here (or on the issue you posted) as even that would save someone else some work! :)

**Comment by JedMeister** [comment]
@alonswartz I think you meant #284

**Comment by alonswartz** [comment]
Sorry about that...

**Comment by JedMeister** [comment]
Hi all, As you possibly know, we are currently working on the v14.0 release (see [announcement](http://www.turnkeylinux.org/14-rc1-aka-we-need-you)).

We'd love to add this appliance to our library for the v14.0 if you guys think that it's ready for prime-time!?

It sounds like currently it doesn't have any map tiles and I think that would be a nice addition (so then it's obviously useful to non-dev types). but I don't know much about all this at all...

What does everyone think?

**Comment by mverwijmeren** [comment]
The next 2 steps to get tiles after this are importing geodata and getting a map style. When I was working on this last year, I ran into the problem that the map styles I wanted required a newer version of Mapserver. Most import tools had dependencies on newer versions of software than available in Debian at that time.

With Jessie everything is newer of course, so I could give it another try. Not now however. Probably in a few weeks.

**Comment by JedMeister** [comment]
That would be super cool @mverwijmeren It'd be great to be able to add it :smile:

**Comment by JedMeister** [comment]
Running out of time for v14.1. Retargeting to v14.2.

**Comment by JedMeister** [comment]
I'm guessing this is dead so closing for now. Please feel free to reopen, or open a new issue.
