### ISSUE TITLE
udhcpc default configuration bug?

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#251]
Peter Lieven from KAMP Netzwerkdienste GmbH brought up an issue (over email) with udhcpc's default configuration and support for /32 IP assignments:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=652573

I'm opening an issue on the tracker so we can track this. The suggested fix is very simple. Replace one line in /etc/udhcpc/default.script. 

Before::

        /sbin/route add default gw $i dev $interface metric $metric

After::

        /sbin/ip route add default via $i dev $interface metric $metric onlink
  
We don't need to patch the package since this is a configuration file in /etc. If it's 100% generic we could drop the fixed configuration into the common overlay so all future builds pick it up. This new default script would go in common/overlays/turnkey.d/udhcpc-fix/etc/udhcpc/default.script.

**Comment by JedMeister** [comment]
I'm 99.99% sure that this bug should have been closed with [this](https://github.com/turnkeylinux/common/commit/b91d83e2f94fa117ba5a6000e7879423fc95d9d1) commit. I.e. addition of this file: https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/udhcpc-fix/etc/udhcpc/default.script
