### ISSUE TITLE
Repoint apt from archive.turnkeylinux.org to mirror.turnkeylinux.org

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#252]
In 13.0 APT points to archive.turnkeylinux.org. In 13.1 it should point to the mirror of archive.turnkeylinux.org at mirror.turnkeylinux.org:

https://github.com/turnkeylinux/common/commit/19f4708c8609a66f3a3f65e395a9fd71f8a3cc8e

**Comment by alonswartz** [comment]
Not sure why this was re-opened after the reverted change. Closing.
