### ISSUE TITLE
ProjectPier bug reported by Lindley Baker

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#253]
Lindley Baker wrote in an email:

"I have found two problems with ProjectPier.  In tasks, you are allowed to schedule a DUE DATE, but when you look in your task list, that due date shows up as a start date.  The other problem is that the calendar is not correct.  It says August 2014, but the days don’t line up with the actual days in this year.  Example August 1 is Friday, but it shows up as a Saturday."

This is probably a ProjectPier software problem which I'm guessing will be fixed in the next upstream version.

**Comment by JedMeister** [comment]
I'm going to close this bug for now... Hopefully it is fixed in the updated TKL appliance. If not then please reopen...
