### ISSUE TITLE
OpenStack build type needs tweaking

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#254]
Previously via email it has been reported that TurnKey OpenStack builds weren't very "user friendly" and ideally require some improvement. Until now as I didn't have anything substantive I didn't lodge it as an issue.

But now Georgios Dimitrak ([here](http://www.turnkeylinux.org/forum/support/20140807/resize-rootfs) on the forums) has some specific issues/feedback.

FWIW all of our alternate builds (inc OpenStack) start life as an ISO; they are then transformed by the relevant [buildtasks](https://github.com/turnkeylinux/buildtasks) script ([bt-openstack](https://github.com/turnkeylinux/buildtasks/blob/master/bt-openstack) in this instance).
##

**Comment by JedMeister** [comment]
FWIW Debian provide an [OpenStack image](http://cdimage.debian.org/cdimage/openstack) and it might be a good idea to pull that apart to compare with what we have... 

As Liraz said:
> It would make sense to use the Debian OpenStack images as a reference for
what the community wants out of an OpenStack image

**Comment by JedMeister** [comment]
Retargetting to v14.2

**Comment by vondrt4** [comment]
Someone wanted to pull apart the official Debian image? I've got something better, the [script](http://anonscm.debian.org/cgit/openstack/openstack-debian-images.git/tree/build-openstack-debian-image) that puts it together :-) and its [manpage](http://manpages.ubuntu.com/manpages/trusty/man1/build-openstack-debian-image.1.html)
Version for the [impatient](https://wiki.debian.org/Cloud/Images_requirements) readers.

**Comment by JedMeister** [comment]
Great work! Thanks :+1:

**Comment by vondrt4** [comment]
I think I'm done here, no help needed, at least with stage 1. See https://github.com/turnkeylinux/buildtasks/pull/22
Any other bugs you can think of? Or the guy you mentioned in #594?

**Comment by JedMeister** [comment]
Great work thanks! 

> Any other bugs you can think of?

Not OpenStack specifically related ones. There are plenty of others though! :grin:  
> Or the guy you mentioned in #594?

I'll email him and get him to test it out. I'll encourage him to come on here to give direct feedback rather than me being the middleman! :smile:

**Comment by vondrt4** [comment]
I'll first give cloud-init at least one go, then we are willing to test it as well. I was working only on core so far, but we'll be deploying about 5 appliances initially on our cloud.

**Comment by JedMeister** [comment]
Closing this. Thanks again @vondrt4
