### ISSUE TITLE
cron.weekly job to garbage collect etckeeper

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#256]
http://www.turnkeylinux.org/forum/support/20111111/etckeeper-has-huge-git-repo-how-remove#comment-20889

Some people have reported that the etckeeper Git repo on /etc/.git can get large. It would probably be a good idea to run a weekly cron job to garbage collect it so that it doesn't get out of hand.

**Comment by JedMeister** [comment]
Not totally sure this is still relevant (see turnkeylinux/common/pull/40); regardless a PR has been issued and whether it is merged or closed this issue can be closed...!
