### ISSUE TITLE
Feature Request - Missing SPDY support in Apache default configuration

### ISSUE THREAD

**Issue by OnePressTech** [turnkeylinux/tracker#262]
To improve performance of the TKLX server it is suggested that SPDY be enabled by default. Caveat: It would need to be verified first that there would be no negative impacts on http-based websites run off the same Apache server. Google is giving SEO priority to SSL-based sites moving forward so it could be reasonably expected that TKLX should support better performance for SSL-based websites out of the box subject to there being no side-effects on http-based websites.

**Comment by JedMeister** [comment]
Hey Tim... Have you seen this:
http://techcrunch.com/2015/02/09/google-starts-fading-out-spdy-support-in-favor-of-http2-standard/

So perhaps HTTP/2 instead of SPDY !? 
I haven't yet had time for any research on HTTP/2 yet but it does seem silly to implement SPDY support when browsers are going to stop supporting it.

Thoughts?

**Comment by OnePressTech** [comment]
Hey Jeremy. Thanks for the  heads up. I hadn’t seen that. http/2 won’t make it into the next TKLX release which I would expect will be based on Jesse so SPDY will be the way to go for now.

 

SPDY3.1 made it into NGINX 1.6 (https://packages.debian.org/jessie/nginx-full ) and subsequently Jessie ( https://packages.debian.org/jessie/nginx-full )

 

Apache2.4 made it into Jessie (https://packages.debian.org/jessie/apache2 ) and Google donated mod_spdy to apache.org to include in apache2.4 (http://thetrendythings.com/read/6340 ). It is possible mod_spdy made it into a core release of apache2.4 (https://svn.apache.org/viewvc/httpd/mod_spdy/ ) but it may not have…in which case it would need to be installed by TKLX as a 3rd-party plug-in if the less technical TKLX users are to benefit out-of-the-box.

 

Just a thought J

**Comment by JedMeister** [comment]
As per usual; great research and fantastic analysis! Thanks! :+1:

**Comment by qrntz** [comment]
mod_spdy is only officially supported for Apache 2.2. For Apache 2.4 an unofficial port [exists](https://github.com/eousphoros/mod-spdy). It is not actively maintained. It does not support SPDY/3.1, which is the only version Google Chrome/Chromium supports. Google are phasing out support for SPDY completely by early 2016 in favor of HTTP/2.

The nginx mod does support v3.1 (and Nginx serves [95%](https://www.nginx.com/blog/how-nginx-plans-to-support-http2/) of all websites that are served via SPDY), but as the bulk of TKL appliances use Apache as the webserver (about 5 use nginx), I doubt this feature is not a dead end.

There is a preliminary alpha [mod_h2](http://icing.github.io/mod_h2/) for Apache. It is not yet production-ready.

The [nginx version](https://www.nginx.com/blog/early-alpha-patch-http2/) of HTTP2 is in alpha, too.

I am convinced the best way to go about this is to leave SPDY alone and wait until major webserver upstreams catch up with the HTTP2 standard towards the end of 2015. If it ain't broke, don't fix it.

**Comment by JedMeister** [comment]
Thanks @qrntz for having a look at this. I am inclined to agree with you so am closing for now. @OnePressTech if you have objections please feel free to update/add-to/reopen/etc this issue! :smile:
