### ISSUE TITLE
[TKLDev] grub related errors within chroot (during build)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#264]
As reported via the [forums](http://www.turnkeylinux.org/forum/general/20140903/turnkey-linux-foreman#comment-21316) installing packages which trigger grub-probe (probably most commonly by update-grub) appear to cause an error when trying to build an image with TKLDev.

**Comment by l-arnold** [comment]
Just trying a Jessie/ Lapp install.   (tkldev Jessie RC1 built/ ISO)
 error reads
Unable to install GRUB in /dev/sda5 ...
This is a fatal error.

will try again.

**Comment by l-arnold** [comment]
Boots and Runs when "Use Whole Disk" is selected.  Will test again with choice #2.

**Comment by qrntz** [comment]
I think this is unavoidable in a chroot. Harmless though.

**Comment by JedMeister** [comment]
Labelled as "won't fix" and closing...
