### ISSUE TITLE
elgg appliance should default to https (and/or allow it to be set to http via inithook)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#268]
As per [this comment](https://github.com/turnkeylinux/tracker/issues/169#issuecomment-59538233) on issue #169 (which I just closed in favour of this one) I suggest that we set https as default on the elgg appliance.

However it is possibly a good idea to allow users to choose http or https via an inithook... Or perhaps it could just be documented?

**Comment by qrntz** [comment]
@JedMeister, to be frank, I don't think letting the user choose is the proper solution here. There is a large bias towards HTTPS for publicly accessible websites (Google ranking priority etc) for good reason, to the point that it became pretty much a standard. Letting the user choose HTTP/HTTPS is placing a burden on them to know the difference and another on ourselves for providing the choice.
And it's not like TKL itself is not geared towards SSL — AFAICS, every single appliance has an SSL service.
Could be documented in the changelog if the original contributor is okay with that.

**Comment by JedMeister** [comment]
@qrntz Agreed...! 

However I could imagine that some (smallish user base; intranet; etc) users may not care about https and rather use http to avoid the self-signed certs "error". I imagine that in the future a free CA will emerge (I have heard plenty of whispers but AFAIK nothing is yet available) and this will become a moot point; but in the meantime...

So I suggest that we make https the default and document how to change it. We coiuld simply just document it in the TKL docs wiki (http://www.turnkeylinux.org/docs - need to log in to edit/create content).

**Comment by qrntz** [comment]
@JedMeister, sounds good.
