### ISSUE TITLE
website search sorting broken

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#277]
Yosi Mor reports on the [forums](http://www.turnkeylinux.org/forum/support/20141125/sorting-search-results-turnkeylinuxorg-website-broken) that sorting search results appears to be broken.
##

**Comment by lirazsiri** [comment]
Workaround: disabled sorting block until we switch to Solr. That way at least users don't expect this to work.

**Comment by JedMeister** [comment]
Closing this as the search appears to be working fine...
