### ISSUE TITLE
User Karma "MORE" button yields "unauthorized" error

### ISSUE THREAD

**Issue by OnePressTech** [turnkeylinux/tracker#278]
There are a number of places on the TKLX website where there is a "MORE" button underneath the list of users that have been active contributors with their Karma total.

If you press the MORE key (which is linked to the following url http://www.turnkeylinux.org/userpoints/list/period ) you get the following error message "You are not authorized to access this page. ".

I guess they're right...Karma's a bitch :-)

**Comment by lirazsiri** [comment]
FWIW, upgrading to the latest version of userpoints doesn't fix this so I'm hiding the link.
