### ISSUE TITLE
Update AWS marketplace AMIs for new instance types

### ISSUE THREAD

**Issue by ahrib** [turnkeylinux/tracker#279]
The current Turnkey AWS AMIs are using the previous generation instance types. 

They should be updated to take advantage of the better hardware and increased performance available to them. Some of these are cheaper to run, or have more resources allocated to them for the same cost.

Current instance types
http://aws.amazon.com/ec2/instance-types/

Upgrade Paths
http://aws.amazon.com/ec2/previous-generation/

**Comment by JedMeister** [comment]
I'm closing this as it has now been implemented in the Hub.

**Comment by JedMeister** [comment]
Oops, just realised that this issue is specifically mentions the AWS MP... Even though they aren't yet available, they are on the way... Hopefully will be live really soon.
