### ISSUE TITLE
Optimized builds for KVM

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#28]
Registered on [lp#blueprints](https://blueprints.launchpad.net/turnkeylinux/+spec/kvm-images) by ``dennyhalim.com`` on 2010-01-10

#### Description

kvm compatible images.
kvm is in mainstream and supported by all distro out of the box

#### Whiteboard

I have been lead to believe that VMware images are compatible with KVM (or at least KVM can easily convert them so they are) so I did a quick and dirty test (using a TKL VM image on my Proxmox server under KVM). It all appeared to go successfully but the machine would not boot. It seemed to get stuck in a loop during bootup. I haven't done enough testing to have a clue what the problem is, and it may be a simple case of me doing something wrong. - JedMeister

**Comment by JedMeister** [comment]
TBH I'm not sure if this is still relevant as KVM now supports VMDK image format OOTB. I have tested it (under ProxmoxVE v3.2) and it works flawlessly. I just used the WebUI to create a KVM VM with a 20GB VMDK. I then deleted the VMDK that was auto created and replaced it with the TurnKey VMDK and booted. 

Someone has kindly documented it more thoroughly on the [TurnKey Wiki](http://www.turnkeylinux.org/docs/kvm).

As such am I going to close this issue.
