### ISSUE TITLE
Add abiword to etherpad-lite

### ISSUE THREAD

**Issue by er2** [turnkeylinux/tracker#285]
Just a matter of installing abiword from the repos and adding its path to the etherpad configuration file.

Instructions here: https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-in-Ubuntu-or-OpenSuse-or-SLES-with-AbiWord
##

**Comment by qrntz** [comment]
* AbiWord has a not-that-large but noticeable footprint (60.8 MB of archives, 225 MB unpacked in Jessie repos)
* More importantly, it pulls in a lot of X/Gnome dependencies that are of no use on a server (Mesa, GTK, icon theme etc) that will have to be updated during subsequent operation and probably never used by anything else.
* It has also been a source of instability previously that lead to the entire app (not just AbiWord) crashing (https://github.com/ether/etherpad-lite/issues/189, https://github.com/ether/etherpad-lite/issues/1083).
* On the other hand, the extra format handling _would_ be sort of nice…

Still, if I were upstream, I'd rather use separate libs/utilities for different formats than pull in a word processor, which no matter how light it is by word processor standards, remains one. I mean, the .deb release of LibreOffice is only about 2 times larger.

My opinion on this would be to either leave as-is, or provide the choice of installing AbiWord to the user on firstboot via inithook at their own discretion and risk.

**Comment by JedMeister** [comment]
Great thanks @qrntz! 
Let's leave it as is for now. I've removed your assignment to this too.

However I like your suggestion of an option to install on firstboot. We'll leave it unassigned, open and pegged to the v14.0 milestone for now. And we'll review it for inclusion later (I guess as a firstboot inithook).

**Comment by qrntz** [comment]
Sounds good.

**Comment by JedMeister** [comment]
I'm going to close this.
