### ISSUE TITLE
turnkey pdc join on linux domain

### ISSUE THREAD

**Issue by suryakiranisbs** [turnkeylinux/tracker#289]
Hi

we have created a turnkey pdc and are able to successfully join up Turnkey PDC with Windows Clients both XP and Windows 7

But when we try to join up with Ubuntu 10 clients we are not doing ok.

The process followed is http://www.clearfoundation.com/docs/howtos/add_linux_workstation_to_the_samba_domain

Up on joining to a Ubuntu PC we are able to login - but there is no roaming profile getting replicated.

- the files are getting saved locally in ubuntu machine and no clue to the server.

Also when the user tries to login through another linux pc then again it rejects

the configuration of PDC is pretty default nothing specific.  Please help us on the same.

**Comment by JedMeister** [comment]
Hi,
This is the TurnKey Linux Issue Tracker and is for bugs and feature requests, not support. We have a [Support Forum](http://www.turnkeylinux.org/forum/support) for that.

Regardless, I'm not particularly familiar with Linux machines joining a Win domain, let alone a Win Domain hosted on a Linux machine! FWIW TurnKey is Debian under the hood and the DC appliance uses Samba3 so google might be of some asistance.

Anyway I'm going to close this Issue. Please open a new topic on the support forums - although I'm not sure how much response you'll get (and I don't know any more than I've already said).
