### ISSUE TITLE
Support applying a TKLPatch to new server during launch via Hub

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#29]
Registered on [lp#blueprints](https://blueprints.launchpad.net/turnkeylinux/+spec/apply-tklpatch-to-ec2-instance) by @JedMeister on 2012-01-07

#### Description

Not sure how technically easy this would be to implement but I reckon it would be friggin awesome if I could apply a patch to an AWS appliance prior to launch. Ideally the patch could be selected from the Hub Server interface - or at least manually uploaded to the Hub, or downloaded to the Hub via a url... Perhaps this option could be available from an 'advanced' drop-down so as not to over complicate things for newbs.

**Comment by JedMeister** [comment]
Now that TKLPatch is not really being used anymore I don't think that this FQ is still relevant. Therefore I'm closing. As always reopen if you disagree! :smile:
