### ISSUE TITLE
nginx rewrite

### ISSUE THREAD

**Issue by stower** [turnkeylinux/tracker#290]
my nginx server is currently working. i want to do a rewrite such that i can stop getting a 404 error because my website has url structure of websitename.com/index.php/compl
kindly assist

**Comment by JedMeister** [comment]
Hi,
This is the TurnKey Linux Issue Tracker and is for bugs and feature requests, not support. We have a [Support Forum](http://www.turnkeylinux.org/forum/support) for that.

Regardless, I'm not actually sure. I would imagine that the Nginx docs probably have the info you are after. And/or google will probably find you a tutorial.

So I'm going to close this Issue. Please open a new topic on the support forums if you want - although I'm not sure how much response you'll get (and I don't know any more than I've already said).
