### ISSUE TITLE
Include wp-cli is WordPress appliance

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#293]
I'm not a big WP user but I think that the Drupal commandline tool Drush is awesome and [wp-cli](http://wp-cli.org/) is essentially the same thing for WP. Therefore I think that it is worthy of inclusion. Also it may be an answer to the issue of how best to set permissions (see Issue #173 ).

What do others think?

**Comment by jeroenpeters1986** [comment]
I'm not sure what to think of it. 
At this moment, I don't see the added value of wp-cli, surely not for TKL.
It requires people to login at SSH, I'm not sure if most of the WordPress people will use it (or know how to SSH maybe?)

**Comment by JedMeister** [comment]
Perhaps you are right @jeroenpeters1986. Probably WP users aren't as tech savy (or as interested in the virtues of the terminal) as Drupal users...

I guess though from my thinking it could then be easily configured to do auto updates (via a cron script), without having a negative impact on security. TBH though I'm not sure whether we'd want to have that pre set; could lead to an embarrassing issue if something breaks...

I also think that so long as it's documented; logging in with SSH is easy (no client even needed in TurnKey - you can use Webshell). Running `wp core update && wp plugin update-all` is hardly rocket science...! Besides IMO it's quicker and easier than clicking around all over the place in the web browser... 

But ultimately I guess that as a commandline loving Linux user I'm probably not like the majority of TurnKey users...! :)

**Comment by jeroenpeters1986** [comment]
@JedMeister - I'm a CLI lover myself. For some users it might be a nifty tool to install along the way. There is no harm in just installing it in the appliance I guess, just as you say: as long as it's documented.

**Comment by JedMeister** [comment]
Closing this issue for now... Following on from above discussion and lack of interest from anyone (other than me - who ironically rarely ever uses wordpress...) it seems like closing it is the way to go...

If anyone feels differently, please feel free to reopen.

**Comment by JedMeister** [comment]
Reopening this as wp-cli seems to be all the rage these days...

**Comment by JedMeister** [comment]
FWIW, this should have been closed already as `wp-cli` is now included in v16.0.
