### ISSUE TITLE
GitLab appliance gives 502 Bad Gateway error after inithooks and reboot

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#295]
As reported in the [forums](http://www.turnkeylinux.org/forum/support/20150114/gitlab-nginx-502-bad-gateway-error) by jruff/John.

**Comment by carlesm** [comment]
Also replied on TKL forums, but I paste here:

Same situation. A vanilla new virtual machine with TKL Gitlab 13.0. And I'm getting the same error.  A web connection to / is redirected to /users/sign_in, where the 502 error is shown. On the  gitlab/logs/*log this is what appears:

==> production.log <==

Started GET "/users/sign_in" for 193.144.12.5 at 2015-01-21 08:31:46 +0000
Processing by Devise::SessionsController#new as HTML
  Rendered devise/sessions/new.html.haml within layouts/devise (30.8ms)

==> unicorn.stderr.log <==
E, [2015-01-21T08:32:16.934330 #2353] ERROR -- : worker=1 PID:29390 timeout (31s > 30s), killing
E, [2015-01-21T08:32:16.963744 #2353] ERROR -- : reaped #<Process::Status: pid 29390 SIGKILL (signal 9)> worker=1
I, [2015-01-21T08:32:16.977034 #29769]  INFO -- : worker=1 ready

**Comment by JedMeister** [comment]
Thanks for the further info.

**Comment by JedMeister** [comment]
Due to recent discussions on the forum thread, it seems that this issue is due to lack of resources (namely RAM). It is suggested that 1GB RAM + 1GB swap is the minimum specs OOTB (with a bit of tweaking it may be possible to get it to run on 512MB RAM + 1.5GB swap but not advised by GitLab devs).

**Comment by JedMeister** [comment]
<p>I can confirm this 'bug' with 512MB RAM (even with 1.5GB of swap - but without any config changes). However I can also confirm that it works as expected (OOTB) with 1GB RAM and 1GB swap...!</p>

<p>So essentially this is not a bug, but relates to minimum spec requirements for GitLab. If you wish to run GitLab with less than 1GB of RAM you will need to play with the config - and even then there are no guarantees...</p>

**Comment by carlesm** [comment]
Well, my results are quite different. On a clean VM with gitlab TKL, with 1GB RAM + 2GB Swap I get the same error. But diving through the logs I see time-outs on 30 secs as described on: https://github.com/gitlabhq/gitlabhq/issues/1527

Using the precompilation trick:
```
cd ~git/gitlab
sudo -u git -H RAILS_ENV=production bundle exec rake assets:precompile
```

It works flawlessly, even with 512 MB RAM.

**Comment by carlesm** [comment]
More on the previous. Attached is the mem usage and cpu usage of a VM running TKL-gitlab. At 9:45 i started testing, as you can see, CPU usage skyrockets, RAM usage also grows, but *never* fills the 1.1Gb alloted. 

So, that reinforces the smell of Ruby/Rails time outs on the alloted time to compile. 

![captura de pantalla 2015-01-24 a las 10 40 01](https://cloud.githubusercontent.com/assets/9011/5886905/aad87a04-a3b5-11e4-94e1-02de0006bfce.png)

**Comment by Nachbar90** [comment]
Hello, I have the same problem after a fresh install. Gitlab has never worked for me. I have 6GB ram and running on debian 7. I have no idea how to get this thing running.

The command sudo -u git -H RAILS_ENV=production bundle exec rake assets:precompile doesn´t work for me, it says "bundle not found". Please help me

**Comment by JedMeister** [comment]
@carlesm Thanks for your research and results. So do you think that it would be a reasonable recommendation that we do the precompile as part of the appliance build process. TBH I don't know much about Ruby so I don't even know if that would work...!? Be interested in your thoughts! At the end of the day if we can make the TurNeky appliance better then that has to be a good thing! :)

@Nachbar90 Are you using TurnKey GitLab appliance or are you just installing GitLab on Debian 7? If it's just on Debian 7 then you are better off talking directly to the GitLab developers and seeing what support they can offer you. If it is a TurnKey appliance then posting on the TurnKey [support forums](http://www.turnkeylinux.org/forum/support/) is your best bet. The 'Issue Tracker' (i.e. here where you have posted) is specifically for bugs and feature requests. General suuport is preferably handled via our forums. Thanks! :)

**Comment by carlesm** [comment]
@JedMeister well, doing the precompile as part of the post-install (on turnkey-init I guess) won't hurt. In fact it will probably solve the day for a lot of people, speed up things for others, and won't hurt anybody. 

IIRC rails will detect any change on source code and re-compile if needed, so, IMHO this won't introduce any issue to anybody.

@Nachbar90 I've been able to install GitLab on CentOS from scratch, it's not an easy task though. I'd recomend a turnkey-linux (I'm using one, although I'm not a debian fan, and turneky is debian-based). The pros of using turnkey-linux outweight, by far, the cons.

**Comment by JedMeister** [comment]
Thanks @carlesm I will add it as a separate (new) 'feature request'.
