### ISSUE TITLE
phabricator image

### ISSUE THREAD

**Issue by igorgatis** [turnkeylinux/tracker#297]
It would be nice to have a Phabricator image easy and ready to use.

**Comment by JedMeister** [comment]
FWIW a [Phabricator appliance candidate already exists](https://github.com/turnkeylinux/tracker/wiki/Candidates#phabricator-a-software-fabricator-code-php) but thanks for the suggestion.

However the harsh reality is that we have so much on our plate that the chances of us releasing any new products anytime soon is quite small... But if you want to push this ahead, then please feel free.

[TKLDev](http://www.turnkeylinux.org/tkldev) (our build infrastructure) is free open source software and if you have a good read through the docs and have a little play you'll see that it's pretty straight forward to produce a new appliance (if you have the time and energy). Browsing through the [build code for existing appliances](https://github.com/turnkeylinux-apps/) is also helpful IMO. If you have questions, then please feel free to post in the [TurnKey forums](http://www.turnkeylinux.org/forum). 

So I'll close this for now. If you do go ahead and start production of a Phabricator appliance then please either reopen it; or create a new issue. Thanks! :)
