### ISSUE TITLE
Provide 32-bit download links on appliance pages

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#303]
This issue relies on #302 
As per discussions in [this thread](http://www.turnkeylinux.org/forum/general/20150208/arguments-against-deprecating-32-bit-tklx-least-mantain-novice-friendly-build) - especially [this post](http://www.turnkeylinux.org/forum/general/20150208/arguments-against-deprecating-32-bit-tklx-least-mantain-novice-friendly-build#comment-22464) it has been suggested that 32 bit links be also provided on each appliance page.

If that is not deemed suitable (too much clutter?) then perhaps there could be a secondary page that includes all links (or a pop-over).

Even just clear mention of the fact that default images are 64 and a link to SourceForge for all other images...

**Comment by lirazsiri** [comment]
I'm closing this as a wontfix. We dropped 32bit support in the latest release.
