### ISSUE TITLE
Explain download build and arch better on appliance pages

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#304]
Somewhat related to #303 
(Among other things) it was suggested in [this thread](http://www.turnkeylinux.org/forum/general/20150208/ovf-import-broken-virtualbox-64bit-fix-and-other-suggestions-easier-tklx-virt) that there be some clearer explanation of downloads; e.g. build types.

**Comment by lirazsiri** [comment]
Now that we support OVA the issues raised in the thread have hopefully been resolved.
