### ISSUE TITLE
ssl issue torrent server  13.0

### ISSUE THREAD

**Issue by blindrain** [turnkeylinux/tracker#305]
the ssl version for the mldonkey control panel is ssl v3 and none of my browsers support v3.
i've tried firefox, chrome and IE 11.

**Comment by JedMeister** [comment]
Hmmm, Initially I thought surely not; but it seems that you are correct. I haven't had much of a dig, but it seems that the MLDonkey WebUI is tunneled through stunnel and that [defaults to SSLv3](https://github.com/turnkeylinux-apps/torrentserver/blob/master/overlay/etc/stunnel/stunnel.conf). I don't know a lot about stunnel but my suggestion would be to adjust that config on your server (to TLS) and restart stunnel and see what happens...

It'd be great if you could report back.

**Comment by blindrain** [comment]
yes that seemed to fix the issue I now can go through the warning options and get to the mldonkey control panel

**Comment by JedMeister** [comment]
Great thanks for reporting back.

**Comment by blindrain** [comment]
i do have another issue though I can't change the password for mldonkey in
the mean time i have iptables blocking incoming traffic to it.resolve the
need fora passwd change.

On Mon, Mar 2, 2015 at 8:55 PM, Jeremy Davis <notifications@github.com>
wrote:

> Great thanks for reporting back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnkeylinux/tracker/issues/305#issuecomment-76871936>
> .
>



-- 
Robert Whitacre
(317)449-9320
The IT Method

**Comment by JedMeister** [comment]
Sorry missed your response. For future reference support questions are best asked on our support forums: http://www.turnkeylinux.org/forum/support
The password should have been set at firstboot. To rerun firstboot scripts: `turnkey-init`

**Comment by JedMeister** [comment]
I'm closing this. The v13.0 appliance still has this bug but the v14.0 appliance is out now with rTorrent/ruTorrent instead.
