### ISSUE TITLE
Need to check if AuFS bug still exists in Jessie

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#309]
We will need to check if this needs a Jessie addition or not:
https://github.com/turnkeylinux/buildroot/blob/master/conf.d/patch-dpkg-gencontrol

**Comment by alonswartz** [comment]
Already implemented: https://github.com/turnkeylinux/buildroot/blob/master/conf.d/patch-dpkg-gencontrol#L65

Or are you referring to something else?

**Comment by JedMeister** [comment]
Thanks @alonswartz that's exactly what I was referring to! I just posted this back when I came across the code and thought that it may have been worth checking... You're all over it though so lets close this.
