### ISSUE TITLE
No https when accessing Web2Py as admin

### ISSUE THREAD

**Issue by icd10doctor** [turnkeylinux/tracker#314]
I am trying to access the Web2Py admin interface by clicking the link that appears as Hostname in the Server view.
I do get the interface but NOT via https (it is deleted with red lines) and thus:
1. The UI is awful (which I could live with) ... but
2. I cannot modify the db.py where the DAL is defined (or any other view or controller)  - so I cannot connect to the MySQL instance (which is up and running)

**Comment by JedMeister** [comment]
Hi,

I haven't attempted to recreate this so I can't confirm it nor offer any sort of workaround. Thanks for reporting though...

**Comment by JedMeister** [comment]
1) sounds like a similar issue to #311

**Comment by icd10doctor** [comment]
1. I did run turnkey-init in the command line. It responded with two long keys: one RSA and one DSA, but there were no prompts to act upon and it didn't solve the issue:
![screen shot 2015-03-23 at 9 56 59 am](https://cloud.githubusercontent.com/assets/11603453/6781358/5f004cc2-d143-11e4-8f06-1ca294fadb14.png)
![screen shot 2015-03-23 at 9 57 11 am](https://cloud.githubusercontent.com/assets/11603453/6781366/6d95291a-d143-11e4-9aa9-8d78a6aaf8de.png)

When I am trying to access Web2Py admin, this is what I get:
![screen shot 2015-03-23 at 9 55 03 am](https://cloud.githubusercontent.com/assets/11603453/6781390/94491526-d143-11e4-837a-437833a3c5b5.png)
which is not the expected Web2Py admin interface...
Question remains - Is there something I have to do in order to access W2P admin interface on https ?

2. There is something you've mentioned which I need more details:
Since I obviously cannot modify any web2py file while it is on TLK (due to the above), I tried to get the connection string in the DAL, set up locally - and then uploaded the W2P app to TLK and check if it works...please see issue #315.

Can you please share a correct / working db connection string I should use in my DAL ?

Many thanks

**Comment by icd10doctor** [comment]
BTW - now I cannot access the Web2Py admin even on http...
And on the same issue - why I could never access Web2Py via the Web shell and thus needed to click on the link in the Server view ?
What is the "right way" to access the W2P admin interface anyway, while on TKL ?
Thanks

**Comment by JedMeister** [comment]
> I did run turnkey-init in the command line ... but there were no prompts to act upon and it didn't solve the issue: 

There is something not quite right... The `turnkey-init` command should have requested a new admin password...

> When I am trying to access Web2Py admin, this is what I get: ... which is not the expected Web2Py admin interface...

Something is up with the CSS on the admin page by the look of it...

I will have to investigate, but sorry I haven't got time ATM...

> Can you please share a correct / working db connection string I should use in my DAL ?

Sorry but I am unfamiliar with web2py so can't help much with DB connection; although the few thoughts I have on that I will post on the other issue. When I check this issue out I will test this too...

> BTW - now I cannot access the Web2Py admin even on http...

AFAIK you should not be able to use http as from what i can see it appears to be disabled. Although perhaps rerunning `turnkey-init` has upset something...

It may be worth starting again? Although TBH I'm not sure that it will achieve much... 

> And on the same issue - why I could never access Web2Py via the Web shell and thus needed to click on the link in the Server view ?

TBH I don't quite understand what you mean?

> What is the "right way" to access the W2P admin interface anyway, while on TKL ?

The right way (AKA the only way) to access the web2py admin page is via a network connected web browser... TKL appliances do not include a desktop etc so browsing from localhost is not an option (unless of course you installed all that extra but IMO for a server it's just bloat you don't need...)

**Comment by icd10doctor** [comment]
Can someone at TLK provide feedback , PLEASE ?

**Comment by seefor** [comment]
Check the locations of the files seems correct, are you using Apache to run Web2PY or using Web2Py itself as a WebServer?

**Comment by icd10doctor** [comment]
Since I installed it from the TLK interface, I'd ASSUME it is running with Rocket Webserver (which is coming with Web2Py) and not Apache

**Comment by seefor** [comment]
icd10doctor, I'm having the same issue :)

**Comment by JedMeister** [comment]
@icd10doctor - I did...! I know it's probably not really ideal; but its the best I've got at the moment... I've got 101 things on my todo list. FWIW I am currently launching a local VM to see if I can at least reproduce it...

Also I suspect that it is using Apache as the webserver (i.e. configured as a production Web2py server rather than a dev one).

**Comment by icd10doctor** [comment]
I could live without the Web2Py admin interface over https, which means an UGLY UI, but I cannot edit any file (controller , view, model, etc) ...
I could still live without this ability too, doing all edits locally and then uploading to Web2Py.
Inconvenient but doable.

And a moment ago I have solved the issue of the database connection string !
It should be in db.py as follows:

db = DAL('mysql://root:pwd2sql@localhost/DBname')

You can find the name of your database by running the SQL command:
select database;

So at least now I can modify my Web2Py locally on my machine and then upload it

**Comment by JedMeister** [comment]
Hmmmmm
We should have done a little searching first... FWIW this issue was first lodged a long time ago. And the reason why it still exists in the current appliance is that our maintenance release (v13.1) is way overdue... (what I am currently trying to work on...)

The cause of the problem is an Apache misconfiguration. I pushed a fix to the appliance code back in May 2014 (hence why I had forgotten about it...)

The fix requires you to replace a line in the Apache site config `/etc/apache2/sites-available/web2py`
Here is the line that needs replacing: https://github.com/turnkeylinux/common/commit/6825e05a62c28bccf8750a60b9631b77bb8eac37

**Comment by JedMeister** [comment]
duplicate of #159 & #311 - but I'm not going to close this issue (for now at least) until I can get confirmation that the fix is working as it should...

**Comment by l-arnold** [comment]
I believe it is working normally.  My 2 cents.

**Comment by seefor** [comment]
@JedMeister - WOOT!  Thanks man that did it, btw love the turnkeylinux.  Please keep up the great work.

**Comment by l-arnold** [comment]
Yes..  Totally helps.  What the heck do these changes do other than effect a whole bunch of paths (line 2 below)

-AliasMatch ^/([^/]+)/static/(.*) /var/www/web2py/applications/$1/static/$2
+AliasMatch ^/([^/]+)/static/(?:_[\d]+.[\d]+.[\d]+/)?(.*) /var/www/web2py/applications/$1/static/$2

**Comment by icd10doctor** [comment]
YES - JedMeister fix works !
Now Web2Py is acting as it should.
Many thanks to all and special thanks to JedMeister.

**Comment by JedMeister** [comment]
@l-arnold the original [regex](https://en.wikipedia.org/wiki/Regular_expression) only matched http urls; the new improved regex also matches https as well!

@icd10doctor great news! :)
