### ISSUE TITLE
DAL connection string for Web2Py to MySQL

### ISSUE THREAD

**Issue by icd10doctor** [turnkeylinux/tracker#315]
According to the Web2Py book, a DAL connection string should be formatted as:
db = mysql://username:password@localhost/test

I have tried to connect a Web2Py app to the MySQL instance (which is up and running) with the following DAL statement (in db.py):

db = DAL('mysql://root:pwd2sql@web2py/dbname', fake_migrate_all=True)

It doesn't work and throws the following ticket:
<type 'exceptions.RuntimeError'> Failure to connect, tried 5 times: Traceback (most recent call last): File "/var/www/web2py/gluon/dal.py", line 7562, in __init__ self._adapter = ADAPTERS[self._dbname](**kwargs) File "/var/www/web2py/gluon/dal.py", line 2572, in __init__ if do_connect: self.reconnect() File "/var/www/web2py/gluon/dal.py", line 606, in reconnect self.connection = f() File "/var/www/web2py/gluon/dal.py", line 2570, in connector return self.driver.connect(**driver_args) File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect return Connection(*args, **kwargs) File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__ super(Connection, self).__init__(*args, **kwargs2) OperationalError: (2003, "Can't connect to MySQL server on 'web2py' (111)")

Does anybody have a connection string sample I can use ?

Thanks

According to the Web2Py book, a DAL connection string should be formatted as:
db = mysql://username:password@localhost/test

I have tried to connect a Web2Py app to the MySQL instance (which is up and running) with the following DAL statement (in db.py):

db = DAL('mysql://root:pwd2sql@web2py/ICD10', fake_migrate_all=True)

It doesn't work and throws the following ticket:
<type 'exceptions.RuntimeError'> Failure to connect, tried 5 times: Traceback (most recent call last): File "/var/www/web2py/gluon/dal.py", line 7562, in __init__ self._adapter = ADAPTERS[self._dbname](**kwargs) File "/var/www/web2py/gluon/dal.py", line 2572, in __init__ if do_connect: self.reconnect() File "/var/www/web2py/gluon/dal.py", line 606, in reconnect self.connection = f() File "/var/www/web2py/gluon/dal.py", line 2570, in connector return self.driver.connect(**driver_args) File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect return Connection(*args, **kwargs) File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__ super(Connection, self).__init__(*args, **kwargs2) OperationalError: (2003, "Can't connect to MySQL server on 'web2py' (111)")

Does anybody have a connection string sample I can use ?

Thanks

**Comment by JedMeister** [comment]
As i mentioned on your other issue thread, I don't know much about web2py so can't directly answer your question... 

However the first thing that I would do would be to try to connect to MySQL using your user and password to make 100% sure that it's not a credential/typo type issue. Something like:
````
mysql --user="$user" --password="$password" --database="$database"
````
And if that works fine then you know it's something up with web2py or your connection string; otherwise you'll need to fix that stuff in MySQL first...

If you are still having issues check this post on StackOverflow; might have some pointers (I don't know just randomly found it with google...) http://stackoverflow.com/questions/7891376/web2py-wont-connect-to-mssql

**Comment by icd10doctor** [comment]
JedMeister,

Much appreciate your feedback.
I have connected successfully to the MySQL instance on TLK.
No problem.
The issues I still have:

1. I cannot access the Web2Py admin interface (issue with https which your hint with tunkey-init or rebooting the server - didn't solve it). 
If there is an issue with SSL certificates missing (?!?)  - I'd expect a company with the term "TURNKEY" in their title to take care of it during the activation / initial setup.
2. I still need a db connection string that someone has already tried and it worked.

TLK people - PLEASE HELP

**Comment by l-arnold** [comment]
Landis here (not a rep),
Out of the box SSL works but is only self signed and not a full cert.  You need to have your browser accept the cert that is not tying out to the domain name if you want to use in box capabilities.

It is quite easy to put a full cert in which I do via WEBMIN.  I apply them to the 443 interface.

I just checked Web2Py.  It runs on both port 80 and port 443.  If you want to force Port 443 it would be worth looking at how this is forced in other aps.  I don't know how to do it but I note that it generally is forced in all the Aps on WebMin and SSH (Webshell).  Normally Database admin is also forced to 443.

I expect there are lots of docs on how to bring this into play on a TKL app.  Web2PY runs an Apache server so should be pretty straight forward in WebMin where you administer the Apache server.

My thoughts anyway.  Hope it is helpful.

**Comment by l-arnold** [comment]
Out of the box Web2P is making a database connection.  All I did is install it and look around a bit.

In fact, when I go to check it, it does go into SSL mode 

Go to your IP address, then on the top you can see the Web2PY pull down and go "This App - Controller".  This will take you into admin.  It goes SSL and requires the Admin Web2Py password as well.  

I don't fully "get what is happening" but I am reading the following about "DB Model"

models
db.py
menu.py
controllers
appadmin.py
default.py
views
__init__.py
appadmin.html
default/index.html
default/user.html
generic.html
generic.ics
generic.json
generic.jsonp
generic.load
generic.map
generic.pdf
generic.rss
generic.xml
layout.html
web2py_ajax.html
modules
__init__.py
private


It does seem like it is losing its formatting for me so someithing might be "off key".

**Comment by icd10doctor** [comment]
Much appreciate your response
I am still not able to go https...
this is what i get:

[image: Inline image 1]

As you can see the https is crossed out...

As of the db connection string, what did you use to connect Web2Py to MySQl
?

Thanks

**Comment by icd10doctor** [comment]
![screen shot 2015-03-24 at 6 00 44 pm](https://cloud.githubusercontent.com/assets/11603453/6813958/74b92c60-d250-11e4-90b0-c5d86ee9383a.png)

**Comment by icd10doctor** [comment]
![screen shot 2015-03-24 at 6 10 28 pm](https://cloud.githubusercontent.com/assets/11603453/6814013/16f1c1cc-d251-11e4-91ea-970dd2345789.png)

**Comment by l-arnold** [comment]
The crossed out https Only means that the Certificate does not match to the domain.  In this situation you would not want to purchase an SSL because you are not tying this to a Domain anyway.    However, you are getting a Secure connection.  When you click on the https (crossed out) you get this information.

![screenclip](https://cloud.githubusercontent.com/assets/5673448/6814248/85e078f8-d242-11e4-8503-688082b8c405.png)

I think you are ok for now.

**Comment by l-arnold** [comment]
This is how to see some of what is going on behind Web2PY.

![screenclip](https://cloud.githubusercontent.com/assets/5673448/6814277/d60e390a-d242-11e4-9497-a41cf8703c86.png)

I was on it the other day and made a small doc and I thought it created a New Database in its own function.  In fact here is a screen shot of what I generated under "new simple application".  From there you are taken to an Admin page for your new project.  One of the choices is Database Administration...  Seems you can keep going from there.

I will note that the Templating seems to go in and out.  Shows good on Database but not so well on the full project interface.

Running the project seems ok.  See below.

![screenclip](https://cloud.githubusercontent.com/assets/5673448/6814337/515e780e-d243-11e4-825e-46902a74de87.png)

**Comment by icd10doctor** [comment]
A moment ago I have solved the issue of the database connection string !
It should be in db.py as follows:

db = DAL('mysql://root:pwd2sql@localhost/DBname')

Since without the https I can use only partially the Web2Py admin interface, I am modifying my app locally on my machine, upload it (at least it allows uploading a new Web2Py app over http) - and with a connection to the MySQL instance - all is good !

Many thanks for your patience !

**Comment by l-arnold** [comment]
Outside observer.  Is the issue that you cannot control these items through Web2PY admin, or is the issue that you cannot control them another way (FTP, WEBMIN etc).

Is your setting overriding a db setting that is in db.py.
I have OVF Web2PY on VMWare ESXI and I am getting SSL.  The formatting (CSS I assume) of part of the interface is not correct, but it seemed that Databases were connecting and generating out of the box.

**Comment by icd10doctor** [comment]
I cannot edit any object in Web2Py admin if it is not on https, BUT I can
upload an app though.

Thus, I am editing locally on my machine the web2py app, upload it (even if
it is not on https - only http) and then everything works

BTW - the db connection string to mysql in db.py is :

*db = DAL('mysql://root:pwd2sql@localhost/dbname')*

I find it strange that the name of the host in a prod environment is
"localhost" (while if you query mysql it says the name of the host is
"web2Py") ... but if it works ....

Thanks

**Comment by JedMeister** [comment]
@icd10doctor - What @l-arnold is saying is on the money. It IS using https; it's just that it is an self-signed cert. If you want a cert that is signed by a third party CA (certificate Authority) so that it isn't red and crossed out then you'll need to purchase one...

Also did you see the fix to the CSS issue that I posted: https://github.com/turnkeylinux/tracker/issues/314#issuecomment-85757430

**Comment by JedMeister** [comment]
And a final comment... Thanks @l-arnold for helping out! :+1:

**Comment by l-arnold** [comment]
No prob JedMeister...  Wierd was that I posted about some of this an hour or more earlier and the posts never showed up.

I had posted pictures of the CERT info which showed it was indeed secure.  There are documents about how to make a "signed cert" on the Forums.  It is relatively easy.  Cost $10 per year or so in my experience.
