### ISSUE TITLE
Instead of OVF TKL should consider releasing an OVA

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#320]
As per [this thread](http://www.turnkeylinux.org/forum/general/20150208/ovf-import-broken-virtualbox-64bit-fix-and-other-suggestions-easier-tklx-virt) it has been suggested that instead of an OVF we should produce an OVA. An OVA is a disk image (often VMDK) bundled with an OVF file and tarred up. According to [Wikipedia](https://en.wikipedia.org/wiki/Open_Virtualization_Format) many virtualisation platforms support OVA OOTB e.g. VMware, VirtualBox, OpenNode, etc. For full details of the OVF standard see [here](http://www.dmtf.org/standards/ovf).

Perhaps it would make sense to discontinue the standalone VMDK build, continue the current OVF build (which could perhaps be relabelled VMDK/OVF (so it could be used either as a vanilla VMDK; or imported via the OVF file) and a OVA (i.e. same thing but tarred and with the VOA extension).

The code that builds the VMDK and OVF builds can be found in [buildtasks](https://github.com/turnkeylinux/buildtasks/); specifically [bt-vm](https://github.com/turnkeylinux/buildtasks/blob/master/bt-vm) and [bin/vm-bundle](https://github.com/turnkeylinux/buildtasks/blob/master/bin/vm-bundle) as well as [patches/vm](https://github.com/turnkeylinux/buildtasks/tree/master/patches/vm)

**Comment by JedMeister** [comment]
At this point I think that this might be best deferred until v14.0 is released although maybe v13.1?

**Comment by chris-redekop** [comment]
+1 for this feature.  OVAs are convenient: no need to unzip after downloading and VMware ESXi, at least, supports deploying an OVA directly from a URL.  In my experience, both VirtualBox and VMware ESXi 4.1+ support the OVA format.

**Comment by lirazsiri** [comment]
If we can get away with doing less formats I'm all for it. I suggest we experiment with a generic Debian OVA image and see where we can get it to work.

**Comment by JedMeister** [comment]
> I suggest we experiment with a generic Debian OVA 

Good idea!

We could even make an inithook that can give users the option of installing VMtools or VBox Additions, etc.!?

TBH I was thinking of converting one of our OVFs to an OVA using VMware's OVFTool and testing it in Virtualbox as a starting point...

**Comment by JedMeister** [comment]
Closing as now OVA is default TurnKey VM build (see [v14.0 OVA container build release](https://www.turnkeylinux.org/blog/14.0-optimized-builds-pt1-vmdk-ova))
