### ISSUE TITLE
Current OVF do not declare machine arch properly

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#321]
As reported many times on the forums (specifically suggested/requested [here](http://www.turnkeylinux.org/forum/general/20150208/ovf-import-broken-virtualbox-64bit-fix-and-other-suggestions-easier-tklx-virt) and most recently [here](http://www.turnkeylinux.org/forum/support/20130828/lamp-doesnt-boot-vmvirtualbox-4216-loading-initial-ramdisk#comment-22810)) the OVF needs to be tweaked to declare the OS arch properly (so 64 bit VMs boot and run properly OOTB).

Specs [here](http://schemas.dmtf.org/wbem/cim-html/2/CIM_OperatingSystem.html); Full OVF standards [here](http://www.dmtf.org/standards/ovf)

Perhaps this could be done as part of #320?

FWIW:
The code that builds the OVF (and VMDK) builds can be found in [buildtasks](https://github.com/turnkeylinux/buildtasks/); specifically [bt-vm](https://github.com/turnkeylinux/buildtasks/blob/master/bt-vm) and [bin/vm-bundle](https://github.com/turnkeylinux/buildtasks/blob/master/bin/vm-bundle) as well as [patches/vm](https://github.com/turnkeylinux/buildtasks/tree/master/patches/vm)

**Comment by chris-redekop** [comment]
Thanks for logging this, Jeremy.

**Comment by l-arnold** [comment]
perhaps my issue with the OVF Wheezy on TKLDEV.

**Comment by JedMeister** [comment]
The fix for this is in progress. 

Also FWIW for v14.0 we will be releasing an OVA build (as per #320) rather than the current zipped OVF.

**Comment by JedMeister** [comment]
This issue should now be resolved as of [v14.0 OVA container build release](https://www.turnkeylinux.org/blog/14.0-optimized-builds-pt1-vmdk-ova)
