### ISSUE TITLE
[Bugailla] New Account emails don't contain proper urls

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#325]
I have had report and confirmed myself that if you try to register for a new account with the Bugzilla appliance the email does not contain proper links. E.g.:

>Bugzilla has received a request to create a user account using your email address (jeremy@turnkeylinux.org).

>To continue creating an account using this email address, visit the following link by April 12, 2015 at 07:10 UTC:

>/token.cgi?t=acbZdmO9BA&a=request_new_account

>If you did not receive this email before April 12, 2015 at 07:10 UTC or
you wish to create an account using a different email address you can begin
again by going to:

>/createaccount.cgi

>PRIVACY NOTICE: Bugzilla is an open bug tracking system. Activity on most
bugs, including email addresses, will be visible to the public. We recommend
using a secondary account or free web email service (such as Gmail, Yahoo,
Hotmail, or similar) to avoid receiving spam at your primary email address.

>If you do not wish to create an account, or if this request was made in
error you can do nothing or visit the following link:

>/token.cgi?t=acbZdmO9BA&a=cancel_new_account

>If the above links do not work, or you have any other issues regarding
your account, please contact administration at admin@example.com.

FWIW if you append the url to the proper domain name they do work, they are just obviously missing something. I am not sure if this is a TurnKey config issue or a Bugzilla Issue.

I propose that we test this on the next build to see if it's still an issue and if so seek to resolve it then...

**Comment by JedMeister** [comment]
The new version needs to b e checked to see if this is till and issue.

https://github.com/turnkeylinux-apps/bugzilla

**Comment by OnGle** [comment]
Issue still exists but can be worked around, (work around for turnkeylinux/tracker/issues/454 required first). Simply edit "urlbase" entry in /var/www/bugzilla/data/params.json to reflect the correct base url (domain or ip address). Seems to require trailing slash. @JedMeister

**Comment by JedMeister** [comment]
:+1:

**Comment by JedMeister** [comment]
this should be fixed by https://github.com/turnkeylinux-apps/bugzilla/pull/6
