### ISSUE TITLE
New Appliance: EspoCRM

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#329]
Oleksiy Avramenko from EspoCRM created an EspoCRM appliance! :smile:

**Comment by JedMeister** [comment]
Forgot to add repo link... He sent me a zip so I've uploaded to my own repo.

https://github.com/JedMeister/espocrm

**Comment by OnGle** [comment]
Builds successfully but couldn't figure out password inithook. Currently uses default password.

**Comment by JedMeister** [comment]
Initihooks now included thanks to https://github.com/JedMeister/espocrm/pull/2

**Comment by JedMeister** [comment]
Just uploaded an upstream provided logo but just noticed that it does not have a transparent background... Will need to be fixed.

**Comment by JedMeister** [comment]
merged into tkl library: https://github.com/turnkeylinux-apps/espocrm
