### ISSUE TITLE
Add compcache to core appliance

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#33]
Registered on [lp#blueprints](https://blueprints.launchpad.net/turnkeylinux/+spec/compcache) by ``dennyhalim.com`` on 2010-01-10

#### Description

With compcache at hypervisor level, we can compress any part of guest
memory transparently - this is true for any type of Guest OS (Linux,
Windows etc.). This should allow running more number of VMs for given
amount of total host memory.

http://code.google.com/p/compcache/

**Comment by JedMeister** [comment]
I'm closing this issue as on the compcache google code site it now says:
>All further development is now being done on the mainline Linux kernel; the code on this site is no longer maintained. Various wiki pages are retained here only for reference.
