### ISSUE TITLE
/etc/default/tomcat6 inconsistency

### ISSUE THREAD

**Issue by SiKing** [turnkeylinux/tracker#330]
I am currently running Tomcat on Apache ver. 13.0.

On the box there is a file /etc/default/tomcat6. Lines 9 through 12 say (note the *leading* comment marks):
```bash
# The home directory of the Java development kit (JDK). You need at least
# JDK version 1.5. If JAVA_HOME is not set, some common directories for
# OpenJDK, the Sun JDK, and various J2SE 1.5 versions are tried.
#JAVA_HOME=/usr/lib/jvm/openjdk-6-jdk      
````
The very last line (line 50) in that file says (note the *lack* of comment marks):
```bash
JAVA_HOME="/usr/lib/jvm/java-6-openjdk-amd64"
```
Please, please, please do **not** do that! Change in only one spot, specifically in the spot where it is documented and therefore expected to be changed.

Standalone Tomcat ver. 13.0 has this same problem, of course.

**Comment by JedMeister** [comment]
This is fixed here:
https://github.com/turnkeylinux/common/commit/5ce6aa48b383d773629de8184fb4c95321432169
