### ISSUE TITLE
Turnkey Linux

### ISSUE THREAD

**Issue by ralph324** [turnkeylinux/tracker#332]
I signed up with AWS for Turnkey Linux and I cancelled with them in January.For the last few months I have not used my website.  I just received a bill (email) from Hub TurnKey Linux. Since I cancelled with AWS and they do not have me using the service, why am I receiving a bill. I asked them for a contact point and AWS could not find one. I am waiting for the bill to come on my credit card so I can dispute it. So, is there a telephone number to call so we can resolve this.

**Comment by JedMeister** [comment]
Hi @ralph324, Sorry to hear about this. We have had a few reports lately about erroneous (and incorrect) emails being sent out. It seems that there is a glitch in the automated email system somewhere. For your piece of mind please feel free tp double check with [Amazon DevPay](http://www.amazon.com/dp-activate). If there is no listing fir TurnKey Linux there you will not receive a bill.  I will close this issue now, but please feel free to reopen, or better still contact me directly if you need anything further (jeremy AT turnkeylinux.org).
