### ISSUE TITLE
Turnkey Bugzilla doesn't work properly with Internet Explorer

### ISSUE THREAD

**Issue by scotty562** [turnkeylinux/tracker#335]
In buglist.cgi
&& $ENV{'HTTP_USER_AGENT'} !~ /WebKit/
needs changed to
&& $ENV{'HTTP_USER_AGENT'} !~ /(?:WebKit|Trident|KHTML)/

If this isn't done, IE is pretty much nonfunctional. They recommend updating to the latest release to fix the issue although the above is a workaround.

**Comment by JedMeister** [comment]
The next release (v14.0) of TurnKey Bugzilla will include a newer version so hopefully that will fix it. Thanks for reporting though! :smile:

**Comment by JedMeister** [comment]
The new version needs to b e checked to see if this is till and issue.

**Comment by OnGle** [comment]
Without knowing the specifics of the issue it's hard to determine if the issue is still present but there doesn't seem to be any noticeable issues with IE 11 (latest stable) and current version of bugzilla in turnkey. Please close @JedMeister

**Comment by JedMeister** [comment]
Thanks @OnGle :+1:
