### ISSUE TITLE
[Webmin] FileManager (java applet) not loading in Chrome

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#337]
I thought it was a Java Generation issue (likely is).  That said, could not get File Manager to load in chrome. Was able to in IE 8.

Chrome is saying "This plug in is not supported"
Perhaps all of Java is being blocked by chrome but certainly could access this in the past.  Ongoing issue when Certs are Unsigned in 12321  (I usually only put signed certs onto outward facing public sites)

**Comment by JedMeister** [comment]
Chrome no longer supports the Netscape Plugin API (NPAPI) OOTB. That is the plugin architecture which Oracle Java uses. I think at the moment you can still nebale it but you need to dig deep into the settings. They intend to stop support altogether very soon.

So once that happens you'll need to use either Firefox or IE for any Java plugins.

**Comment by JedMeister** [comment]
As mentioned in another thread by @l-arnold there is currently a [third party non-official file manager available for Webmin](https://www.virtualmin.com/node/36839). As per that thread it seems that (upstream) Webmin are looking to include it officially although that is yet to happen.

The current development version can be found on the [dev's GitHub](https://github.com/Real-Gecko/filemin). Release tarballs [here](https://github.com/Real-Gecko/filemin)https://github.com/Real-Gecko/filemin/releases. 

I haven't yet tested it but if it is as good as it sounds (and other have reported) then I am tempted to include it in TurnKey v14.0... For now we might wait and see with a final decision to be made around the time of v14.0 release...

**Comment by l-arnold** [comment]
Just got this note from the Webmin world re filemin.,,  

Unattributed just now.  Sorry.
.......

Look in the /install directory in the github for filemin. There are already .wbm and .deb packages for Filemin. You can download either using the raw download option, and use the Webmin Modules module to install it.

We do plan to integrate it into Webmin core going forward, but it's not ready for that yet; it needs some security auditing, accessibility testing, and a few other bits of due diligence before we hand it off to a million users.

—

**Comment by l-arnold** [comment]
Comment from Webmin Space:
The latest development version of Webmin has the new FileManager.

Wonder if we can push this at all?

**Comment by JedMeister** [comment]
Sorry Landis; not going to happen... Once it is released stable via Webmin upstream then we'll integrate it ASAP.

**Comment by l-arnold** [comment]
I understand.

**Comment by JedMeister** [comment]
Having said that maybe we should leave this issue open for now? Until they release 1.770 (i assume it will be in the next release) and we do the upgrade.

**Comment by JedMeister** [comment]
I'm closing this as the html5 file manager is included in v1.770. There is a separate bug for updating TKL to that: #496
