### ISSUE TITLE
ConfConsole sometimes starts before boot finishes (i.e. final stages of boot log pollute Confconsole)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#338]
This leaves the last lines of boot progress over the top of the ConfConsole. It doesn't affect functionality (just hitting enter makes it go to the next screen and all is well) but it looks ugly and makes the initial screen hard to read (and may be a little concerning for TKL newbs).

I assume that this is caused by a systemd thing (synchronous init).

**Comment by JedMeister** [comment]
Same cause as #356

**Comment by DocCyblade** [comment]
I am guessing some systemd dark magic will need to be crafted to make sure the startup hooks happen when they should. I had a quick read of the systemd docs and from what I remeber I think some crafty config could ensure things are run when we want them to. 

Alon, what are you thinking to tackle this beast?

**Comment by JedMeister** [comment]
Yep that's what I assumed too. I know Alon had to do some hacking on systemd already to get things working like they do now. So I was just going to leave it to him when he comes back to v14.0 stuff (probably a little while away).

However if you want to have a crack in the meantime then go for gold! You won't be treading on his toes! In fact I imagine that he'd appreciate it! :smile:

**Comment by JedMeister** [comment]
Limitation of systemd; labelled as "won't fix" and closing for now.

**Comment by JedMeister** [comment]
I'm reopening this issue for v15.0. Once we rebase on Stretch, we should be able to fix this properly!

**Comment by JedMeister** [comment]
TBH, I haven't seen this occur in my Debian Stretch testing, however, I'm not going to guarantee it's fixed. So I'm deferring to v15.1 for now...

**Comment by JedMeister** [comment]
Closing this issue now. It hasn't been such and issue with v15.x (Debian 9/Stretch) and from my testing of (the as yet unreleased) v16.0RC (Debian 10/Buster) this is no longer an issue at all. Regardless, it's likely out of our control anyway...
