### ISSUE TITLE
[Jessie] ISO (di-live) install doesn't reboot properly

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#339]
During di-live install (at the point where it asks you if you are ready to reboot and you answer yes) the system shuts down but does not power off and reboot.

I have only tested this in KVM so far, but it has been replicated in VirtualBox apparently.

Once installed the reboot option in confconsole works fine; as does `reboot` and/or `shutdown -r now` from the commandline. Interestingly `halt` (which I have used to poweroff Ubuntu and Debian since I've been using them) no longer powers the system down (it halts all running processes but then just sits there). Apparently this is intended behvaiour though and is a bug that was never fixed... The desired outcome (i.e. power off) is acheived with `halt -p`.

**Comment by Dude4Linux** [comment]
I believe I experienced this problem while installing the TKLdev jessie appliance.  I'm running in KVM on a Proxmox platform.  I was able to continue the install by stopping and restarting the VM.  Once the install is completed, normal starts, stops, shutdowns, and reboots seem to work flawlessly.

# pveversion -v
proxmox-ve-2.6.32: 3.4-150 (running kernel: 2.6.32-37-pve)
pve-manager: 3.4-3 (running version: 3.4-3/2fc72fee)

**Comment by JedMeister** [comment]
ISOs I've built recently now reboot as they should... Debian must have fixed a bug!?

**Comment by JedMeister** [comment]
Reopening... The ISO I just built did not reboot... Weird...

Is anyone else getting any ISOs that reboot and some that don't? It shouldn't matter but it was Tomcat. Built so it auto rebooted twice in a row, now third time it doesn't!?

**Comment by l-arnold** [comment]
Happening in Jessie with Odoo App and I believe also with LAPP 5-22-15.  Incl Make today.

**Comment by l-arnold** [comment]
Sounds similar.  Seemed they were rebooting 2 days ago but not yesterday or today.

Will try some simple builds again and report.

Landis Arnold

Cell 303.601.0622
Office 303.444.2336

on mobile 
(so typos expected and excusable perhaps)

Sent from Nine

**Comment by l-arnold** [comment]
This is the Text...  One time out of 10 it does reboot but normally needs a shutoff and restart.
Odoo system built from LAPP.  Need to review LAPP to see if updates are not showing in my repo.

ts Blueserve - Remote Desktop
File View VM
H 00 ^ © I B a B\&
[	OK	]	Stopped	target	Swap.
[	OK	]	Stopped	Update	UTMP about SysteM Boot/Shutdown.
Stopping Create Uolatile Files and Directories...
[	OK	1	Stopped	Create	Uolatile Files and Directories.
[	OK	1	Stopped	LSB: Raise network interfaces..
Stopping Load/Save RandoM Seed...
[ OK 1 Stopped target Local File SysteMS.
UnMounting /cow...
UnMounting /rofs...
UnMounting /cdroM...
UnMounting /tMp...
Stopping Monitoring of LUM2 Mirrors, snapshots etc. ...ress polling...
[	OK	1	Failed unMounting	/rofs.
[	OK	1	Failed unMounting	/cdroM.
[	OK	1	UnMounted /cow.
[	OK	1	UnMounted /tMp.
[	OK	1	Reached	target	UnMount fill FilesysteMS.
[	OK	1	Stopped	target	Local File SysteMS (Pre).
Stopping Create Static Device Nodes in /dev...
[	OK	1	Stopped Create Static Device	Nodes in /dev.
[	OK	1	Stopped Load/Save	RandoM Seed.
Stopping ReMount Root and Kernel File SysteMS...
[	OK	1	Stopped	ReMount Root and Kernel File SysteMS.
[	OK	1	Reached	target	Shutdown.

**Comment by JedMeister** [comment]
Yeah doesn't seem to be a rhyme or reason to why this sometimes works but not other times. 

I'll just put up with this issue for now until Alon (or someone) else has time to have a look into it... I don't know enough about di-live and/or systemd to be able to be of any value...

**Comment by l-arnold** [comment]
Well, I just found that if I choose "no" when it is asking me if I want to eject the disk, that the system goes and reboots by itself.

If I choose "yes" it hangs.  Seems a good time to make an OVM that can be customized still choosing "yes" then "shut down" instead of "restart".

**Comment by JedMeister** [comment]
>OVM

?? Did you mean OVF/OVA If so then it doesn't matter. It only applies to the ISO builds. None of the other builds need to reboot...

**Comment by l-arnold** [comment]
I meant OF etc.  If doing your own of image freezing it there by shutting down (instead of rebooting) then pulling an OF etc would mean that inithooks for personalizing would come up on first boot without the first round of installations.not almost seems that it works this way anyway.  If  pulled one that way a week ago but have not tested further.

**Comment by JedMeister** [comment]
You can tell the inithooks to rerun anyway; just set the RUN_FIRSTBOOT flag (in /etc/default/inithooks)... No need to stop at a specific place. Have a look at the inithooks docs: http://www.turnkeylinux.org/docs/inithooks
