### ISSUE TITLE
Add native APR support to tomcat based appliances

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#34]
Registered on [lp#blueprints](https://blueprints.launchpad.net/turnkeylinux/+spec/tomcat-with-native-tomcat-apr) by `Jeremy Davis` on 2012-01-10
#### Description

According to Douglas Borg, Tomcat and Apache Tomcat appliances should come preconfigured with Tomcat Native APR support. 

http://www.turnkeylinux.org/forum/support/20120109/tomcat-and-apache-tomcat-instances-should-come-preconfigured-tomcat-native-ap

http://blog.janjonas.net/2010-07-29/ubuntu-10_04-tomcat_6-improve-preformance-apache-tomcat-native-library
##

**Comment by JedMeister** [comment]
Seems like this is still relevant: http://tomcat.apache.org/native-doc/

**Comment by JedMeister** [comment]
@spaghettimaster - This is a really old issue and may no longer be relevant. Seeing as you worked on the Tomcat appliances, would you mind having a look at this one too?

Either it's still relevant and we should probably include it in v15.0 (unless there is a good reason not to). Or we should close this issue as no longer relevant.

**Comment by spaghettimaster** [comment]
I opened PR with fix: https://github.com/turnkeylinux/common/pull/113
