### ISSUE TITLE
[TKLDev] Some intermittent issues downloading packages when building servers

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#341]
When trying to build some servers in TKLDev I was having some intermittent package download issues. The specific error was `502 Read from server failed: Connection reset by peer`

I'm not sure whether it was something up with my internet or something else... I had a bit of a google and I read that polipo (the caching proxy used in TKLDev) is known to have fairly poor DNS resolver and that a settings tweak improves things; so I added `dnsUseGethostbyname = yes` to `/etc/polipo/config`, restarted polipo (`service polipo restart`) and tried again. 

Perhaps it was coincidence but the packages that had errored now just worked. It seemed quite fast too...

**Comment by l-arnold** [comment]
Similar.  This time in Jessie building a Cone/Mod from LAPP.  New Error.  Will try again.

E: Failed to fetch http://http.debian.net/debian/pool/main/n/ntp/ntp_4.2.6.p5+df
sg-7_amd64.deb  504  Host punk.uchicago.edu lookup failed: Timeout

E: Failed to fetch http://http.debian.net/debian/pool/main/p/php5/php5-cli_5.6.7
+dfsg-1_amd64.deb  504  Host punk.uchicago.edu lookup failed: Timeout

E: Failed to fetch http://http.debian.net/debian/pool/main/p/php5/libapache2-mod
-php5_5.6.7+dfsg-1_amd64.deb  504  Host punk.uchicago.edu lookup failed: Timeout

E: Failed to fetch http://http.debian.net/debian/pool/main/liba/libapache2-mod-p
ython/libapache2-mod-python_3.3.1-11_amd64.deb  504  Host punk.uchicago.edu look
up failed: Timeout

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-mis
sing?

**Comment by JedMeister** [comment]
Did you try my tweak? If so did it help?

**Comment by l-arnold** [comment]
The tweak did get me past where I was.  Thank you for that.THE CONNECTIVITY ISSUES ARE QUITE RANDOM and ongoing.  Normally works on round 2.

Then tweak helped the PGA ADMINISTRATION (sp) errors.
thanks for that.  Very close now with Jessie.  Running fresh test now.

L.Arnold

Sent from Nine

**Comment by l-arnold** [comment]
Connectivity seems to have improved a week later.  Would love to not have Make always pull "git clone" of outside Apps each time I run a Make.  (different subject but related to this one).  Comment last week was, not possible now if in CONF.D  (trying to find the comment).

Related to "connectivity issues" in that Upstream sources do fail of their own accord sometimes.

**Comment by JedMeister** [comment]
Great re connectivity. Perhaps it was because Jessie was still so new? Lots of people trying to download (seems unlikely but possible).

As for always having to run `git clone` - so long as you cloned from the turnkey-apps repo then you can just `git pull` (from inside the repo). That will check GitHub for any new commits and if there are download them and merge with the existing code.

**Comment by l-arnold** [comment]
How about an "error checker" in TKLDEV that will 
1:  try 3 times
2: go back and look for another mirror
3:  fail after 1 and 2.

**Comment by JedMeister** [comment]
I think this still needs some work but I am retargetting to v14.1.

**Comment by JedMeister** [comment]
I am closing this issue now as I have been unable to reproduce recently. I think it was perhaps caused by the Debian repos being flooded soon after the release of Jessie...
