### ISSUE TITLE
TKLDev should not show WebMin or WebShell in confconsole

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#342]
always misleading.
Just show the SSH Port in console.

AWS also shows Icons for both that do not go anywhere.

I understand they cannot be turned on.

**Comment by JedMeister** [comment]
Yes good call! Whilst they are installed and configured they are (intentionally) disabled so the ConfConsole info certainly is misleading!

**Comment by l-arnold** [comment]
Just Add Disabled by default to the window perhaps

L.Arnold

Sent from Nine
