### ISSUE TITLE
(Jessie) Screen Saver in Console

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#343]
For some reason my Console display is going to sleep in TKLDEV Jessie.

When I succeed in waking it it tends to have taken the "Advanced" or "Shutdown" command and is dangerous because one more click and it might be gone.

Not sure, but seems to be doing this.  Installed from RC1 ISO to VMware ESXI 4x

**Comment by JedMeister** [comment]
I too have noticed that; however when it wakes up the display is fine for me...

Probably the best resolution is to disable the screen going to sleep (but document how to make it sleep for those that want that behaviour).

I strongly suspect that it is some default behaviour change in Jessie...

**Comment by l-arnold** [comment]
Agreed.  Just a bit dangerous in that situation.

L.Arnold
Sent from Nine

**Comment by l-arnold** [comment]
Just to note, I just had it "shut down" on me when I was trying to get the screen back.

Also went to "reached target shutdown" as it does in install but had to reset to get it to comeback.

**Comment by JedMeister** [comment]
If you use the spacebar rather than enter then it shouldn't do anything other than wake up the screen. Obviously we still want to 'fix' this though...

**Comment by l-arnold** [comment]
In VMWare (for me) Need to click.
Space Bar wakes and invokes "A" (ie Advanced)... then trouble possible

Click Ctrl Alt often wakes and "disinvokes" the mouse and control (a good thing)

Click Ctrl seems to possibly just wake.

**Comment by JedMeister** [comment]
I've just committed a fix for this, although Alon may think that there's a better way... You can easily implement my fix yourself if you want to...

edit `/etc/default/grub` and change this:
````
GRUB_CMDLINE_LINUX_DEFAULT=""
````
to this:
````
GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0"
````
Then update grub:
````
update-grub
````
You will need to reboot for the changes to take effect.

**Comment by l-arnold** [comment]
Thanks Jeremy,
Will Test tomorrow for sure.
