### ISSUE TITLE
Jessie Migrations - HTML in Apache (TKLDEV and TKLBAM assumed)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#346]
Ran TKLDEV on LAPP.  
Apache wants index.php and other content to reside in the new HTML folder within WWW.

Just moved index.php there but it appears that CSS, Image locators and the like are not referenced.

Should be a programatic moving of this, or resetting of Apache's expectations.

**Comment by JedMeister** [comment]
AFAIK I have fixed this issue in the latest common. Alon has merged my latest commits.

So unless you have made local changes to common yourself which you'd like to keep, try this:
````
cd /turnkey/fab
rm -R common
git clone https://github.com/turnkeylinux/common.git
````
Then go back to your product dir and run `make clean && make` and hopefully this should be all good now... At least it was when I built LAPP

**Comment by JedMeister** [comment]
I'm going to shut this for now. Under Apache2.4 (as installed in Jessie) the new default doc root (for Apache at least) is /var/www/html (the previous default was /var/www).

At this stage we will probably continue to use the old default of /var/www. I set it that way in LAMP and LAPP appliances for now anyway. We may review and change that prior to the v14.0 final release though.

If you have further problems with this, either reopen it or post a new issue. Thanks.
