### ISSUE TITLE
(Jessie) (RC1) TKLBAM Profiles Needed

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#348]
exploring LAPP.

will drop a few restores and see what happens.

Initialized TKLBAM and got the proper error page below  (will work on  formating better here)

-------------

TurnKey Hub Error: Backup profile archive not found: turnkey-lapp-13.0-jessie-amd64

Without a profile TKLBAM can't auto-configure the backup process for your
system. Sorry about that! However even without a profile you can still:

- Restore existing backups
- Backup raw directories with the --raw-upload option

You can use the --force-profile option to fix or workaround a missing profile
in several ways:

- Use an empty profile with --force-profile=empty
- Use a custom profile with --force-profile=path/to/custom/profile/

    tklbam-internal create-profile --help

Also, if TKLBAM is linked to the Hub you can:

- Download a profile for another TurnKey system with --force-profile=codename (e.g., "core")
- Download the all-purpose generic profile with --force-profile=generic

Run "tklbam-init --help" for further details.

Generated backup encryption key:

    For extra security run "tklbam-passphrase" to cryptographically protect it
    with a passphrase, which will be needed later to restore. If you use lose
    the passphrase it will be impossible to restore your backup and you may
    suffer data loss. To safeguard against this you may want to create an
    escrow key with "tklbam-escrow".

Linked TKLBAM to your Hub account.

**Comment by l-arnold** [comment]
Tried to do a restore to LAPP (Jessie) and got:

Error - Perl execution failed

syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 9, near "skip_packages skip_files skip_database limits)"
  (Might be a runaway multi-line () string starting on line 7)
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 12, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 17, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 38, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 41, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 50, near "}"

**Comment by JedMeister** [comment]
Thanks for reporting. TBH I haven't tested TKLBAM with v14 yet but we'll have to look into it.

For now could you try forcing the v13 profile and perhaps using TKLBAM from the commandline instead?

**Comment by alonswartz** [comment]
The TKLBAM profiles are built during the appliance build/release process. So, currently only Core and TKLDev RC1 have profiles.

https://github.com/turnkeylinux/buildtasks/blob/master/bin/iso-release#L77

**Comment by JedMeister** [comment]
Thanks Alon :smile:
