### ISSUE TITLE
Jessie RC1 Webmin (Choosing Document Root in Apache - IE8)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#349]
Got the following error when selecting the "choose button" for document root:

(Occurs in IE8, but not Chrome 42)  Can't solve everything, but can't choose a file in IE8 either.

...........

Warning!
 Webmin has detected that the program https://192.168.1.117:12321/chooser.cgi?add=0&type=1&chroot=/&file=%2Fvar%2Fwww%2Fhtml was linked to from an unknown URL, which appears to be outside the Webmin server. This may be an attempt to trick your server into executing a dangerous command.
Make sure your browser is configured to send referrer information so that it can be verified by Webmin.

Alternately, you can configure Webmin to allow links from unknown referers by :

Login as root, and edit the /etc/webmin/config file.
Find the line referers_none=1 and change it to referers_none=0.
Save the file.

**Comment by JedMeister** [comment]
Hmmm, that seems weird. I have seen this behaviour before but only when I linked to specific parts of Webmin from outside Webmin - e.g. in forum posts. It seems weird that it would give that error when you were within Webmin already. If you can reliably reproduce this issue it may be worth taking up with the Webmin devs?

**Comment by JedMeister** [comment]
I'm closing this for now as it's an upstream issue. Also we no longer support IE8 OOTB sorry (if it works great; if not you'll need to use a workaround such as using Chrome or Firefox instead). Please reopen if it also effects IE11.
