### ISSUE TITLE
TKLBAM restore in Webmin (locked from response)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#350]
Doing a TKLBAM restore from a VM to AWS.  Get the following on the Webmin Console but no way to respond to it that I can find in webmin.  Likely works in SSH.  (All I could seem to do is issue Reboot in another Tab..  perhaps there is a way to splice into WebMin's SSH.  Not sure how)

Configuration file `/etc/vmware-tools/tools.conf' 
==> File on system created by you or by a script. 
==> File also in package provided by package maintainer. 
What would you like to do about it ? Your options are: 
Y or I : install the package maintainer's version 
N or O : keep your currently-installed version 
D : show the differences between the versions 
Z : start a shell to examine the situation 
The default action is to keep your current version.

**Comment by lirazsiri** [comment]
All packages during TKLBAM restore are installed non-interactively. This looks like a bug in the vmware tools package where it doesn't respect that. 

Making the TKLBAM restore process interactive isn't the solution as we rely on non-interactivity in other areas such as restoring backups in the Hub.

**Comment by JedMeister** [comment]
I was almost going to close this as a "won't fix", although I'm not sure if is the right thing to do as this may still potentially be an issue. 

I wonder if a solution might be for TKLBAM to just log a warning and keep the current conf? Thoughts?

**Comment by l-arnold** [comment]
I don't know if this is still a problem but will test again.

**Comment by JedMeister** [comment]
:+1: Thanks Landis

**Comment by JedMeister** [comment]
Clsoing for now. Please reopen if this is still an issue. Thanks.
