### ISSUE TITLE
ruby gems not cached by tkldev's polipo

### ISSUE THREAD

**Issue by wvengen** [turnkeylinux/tracker#353]
The polipo proxy speeds up things quite a lot, but it doesn't seem to be caching ruby gems. The http proxy is set correctly before running `gem install`, and tcpdump shows that traffic is passing through polipo. Still, no new entries appear in /var/cache/polipo , and download speeds are low (indicating no cache is used).

Note that ruby gems are downloaded over https from amazon s3. Polipo [supports https](http://www.pps.univ-paris-diderot.fr/~jch/software/polipo/faq.html#features); no cache headers are present on the http response.

Is anyone else seeing this behaviour?
This is not a serious issue, but it would be useful if ruby gems are cached.
##

**Comment by JedMeister** [comment]
I'm sure I've seen this issue mentioned before (I thought it actually already was an issue but I couldn't find it just then...)

**Comment by wvengen** [comment]
It seems I've suggested this before in #213.
There are several projects out there to do this:
* [rubygems-localproxy](https://github.com/sevos/rubygems-localproxy)
* [panthro](https://github.com/gramos/panthro)
* [rubygems_proxy](https://github.com/akitaonrails/rubygems_proxy)
* [angry-caching-proxy](https://github.com/epeli/angry-caching-proxy) apt+npm+pip+npm caching proxy
* and a [local cache hack](http://www.akitaonrails.com/2011/05/29/rubygems-local-cache-hack)

**Comment by wvengen** [comment]
Though I am wondering why polipo just doesn't do this by default.

**Comment by JedMeister** [comment]
Aha. Nice work finding that. I don't know. I had a quick look aroujd and found nothing of interest re polipo caching gems (although don't take my word for it... Couldn't even find that other issue! :stuck_out_tongue: )

**Comment by JedMeister** [comment]
Related to #467 - I.e. we could leverage Squid to do all sorts of fancy caching...

**Comment by OnGle** [comment]
To be honest I'm almost incline to closes both this and https://github.com/turnkeylinux/tracker/issues/467 in favor of a "replace polipo with a better proxy" feature.

**Comment by JedMeister** [comment]
As per @OnGle's suggestion above (https://github.com/turnkeylinux/tracker/issues/353#issuecomment-774827928) I'm closing this and opening a new consolidated issue; #1560.
