### ISSUE TITLE
[Jessie] Inithooks start before booting finishes

### ISSUE THREAD

**Issue by SiKing** [turnkeylinux/tracker#356]
I grabbed TKLDev 14.0RC1 and went through the tutorial to build the core product.iso. When I launch that in my VM, at the screen that asks to enter a new root password, the prompt gets messed up. See attachment. This happens consistently for other products as well.
![untitled](https://cloud.githubusercontent.com/assets/5496738/7658469/4e314ea2-faef-11e4-8ca2-8a800487da42.png)

**Comment by SiKing** [comment]
Should have mentioned: There is nothing wrong with the _functionality_, the screen correctly accepts the password. This is just a display problem.

**Comment by JedMeister** [comment]
Thanks for reporting. I'm 99% sure that its a systemd thing...

**Comment by JedMeister** [comment]
This is caused by the same issue as #338

**Comment by JedMeister** [comment]
I just renamed this to better reflect what the problem is. Hope you don't mind @SiKing

**Comment by JedMeister** [comment]
Limitation of systemd; labelled as "won't fix" and closing for now.
