### ISSUE TITLE
[Jessie] ConfConsole failing first time it tries to set static IP

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#357]
I am running various v14 test VMs (under KVM on ProxmoxVE) and whenever I set a static IP with ConfConsole the first time it tries to apply seems to consistently fail.

It reports message something like "failed setting IP" but if I retry then it works..

**Comment by qrntz** [comment]
Could not reproduce (yet).

**Comment by JedMeister** [comment]
I can reproduce it fairly reliably (KVM on ProxmoxVE 3.4). Is there additional info I can provide?

**Comment by qrntz** [comment]
OK, could reproduce.

This one is quite weird TBH. Affects changing from DHCP-acquired IP to static config (but not vice versa). Seems like ifupdown does **not** like being called too fast in succession and when that is done, the second command yields no side effect on the network stack (but finishes succesfully). It's probably related to the fact ifupdown is a single executable that can be called either as ifup or ifdown and it gets tangled in its own locks and confused or something (the source code is no good wrt. readability). The same result (no IP set, but interface up) can be reproduced with:

    ifdown eth0; sed -i '/iface eth0/ {s/dhcp/static/; a\
    address 192.168.1.190\
    netmask 255.255.255.0\
    gateway 192.168.1.1
    }' /etc/network/interfaces; ifup eth0

So this is not a confconsole, but an underlying system issue. Could be ifupdown, could be virtio-net. Virtio-net definitely has its part as a culprit as I was not able to reproduce this with an emulated e1000.

In the meantime, ```sleep(0.5)``` between the two calls fixes it. Man, does it feel dirty though.
