### ISSUE TITLE
Joomla ('joomla25') appliance should be renamed to just 'joomla' for next release

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#359]
Appliance to be renamed (and Joomla to be updated to latest upstream stable)

**Comment by l-arnold** [comment]
I would vote for keeping the Versions in the name.  Joomla is notoriously difficult to upgrade and simply moving to the new version may not allow easy upgrades when Debian versions change.

Basically old Joomla 1.5 went to 1.6 OK, but with difficulty for 2.x

Version 2.x Joomla also has difficulty going to 3.x In and of itself.

I know this is taxing on the overhead.  I will test my Joomla 3.2 in Jessie and also look at the Base one.

**Comment by l-arnold** [comment]
I can Clone, but this is the Release needed in Overlay if running today towards Joomla 3.2

VERSION="20021/162256/Joomla_3.4.1-Stable-Full_Package.tar.gz"
URL="http://joomlacode.org/gf/download/frsrelease/$VERSION"

**Comment by l-arnold** [comment]
Should Drop Joomla 1.5  (no longer supported)
Should add Joomla 3.4  (almost built a version)
https://github.com/l-arnold/joomla34/

Got a Build short 3 Welcome Lines at close of Make in conf.d/main
# create welcome post
# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO ${DB_PREFIX}content VALUES ('1', '35', 'Welcome to TurnKey Joomla', 'welcome', '', '<h2>Getting started</h2><p></p><ul><li>Log into the <a href=\"administrator\">administration console</a> as <strong>admin</strong></li> <li>Refer to the <a href=\"http://www.turnkeylinux.org/joomla25\">TurnKey Joomla release notes</a></li><li>Refer to the <a href=\"http://docs.joomla.org\">Joomla documentation</a></li></ul><p></p>', '', '1', '0', '0', '2', '2010-01-01 00:00:00', '42', '', '2010-01-01 00:00:00', '0', '0', '2010-01-01 00:00:00', '2010-01-01 00:00:00', '2020-01-01 00:00:00', '', '', '{\"show_title\":\"\",\"link_titles\":\"\",\"show_intro\":\"\",\"show_category\":\"\",\"link_category\":\"\",\"show_parent_category\":\"\",\"link_parent_category\":\"\",\"show_author\":\"\",\"link_author\":\"\",\"show_create_date\":\"\",\"show_modify_date\":\"\",\"show_publish_date\":\"\",\"show_item_navigation\":\"\",\"show_icons\":\"\",\"show_print_icon\":\"\",\"show_email_icon\":\"\",\"show_vote\":\"\",\"show_hits\":\"\",\"show_noauth\":\"\",\"alternative_readmore\":\"\",\"article_layout\":\"\"}', '1', '0', '1', '', '', '1', '0', '', '1', '*', '');"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO ${DB_PREFIX}content_frontpage VALUES (1,1);"

# $MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO ${DB_PREFIX}assets VALUES ('35', '27', '19', '20', '3', 'com_content.article.1', 'Welcome to TurnKey Joomla', '{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');"

**Comment by l-arnold** [comment]
per above. Joomla34  TKL built ISO and installed normally in console
https://github.com/l-arnold/joomla34/  (based on turnkeylinux-apps/joomla25)


Database not properly setup.
conf.d/main  lines 71,73,75 commented

Return this Error where Joomla should be starting:
"No configuration file found and no installation code available. Exiting..."

**Comment by JedMeister** [comment]
>I would vote for keeping the Versions in the name. Joomla is notoriously difficult to upgrade and simply moving to the new version may not allow easy upgrades when Debian versions change.

problem is though then we need to change the name of the repo each time we update the appliance...

>Basically old Joomla 1.5 went to 1.6 OK, but with difficulty for 2.x
>Version 2.x Joomla also has difficulty going to 3.x In and of itself.

If we just name it 'joomla' then we only need to update the readme and changelog with the version included...

**Comment by JedMeister** [comment]
closed in favour of #443
