### ISSUE TITLE
WebCP page needs update (Adminer)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#363]
Both the LAMP and LAPP appliance webCP pages need to be updated with to point to Adminer now rather than phpMyAdmin/phpPgAdmin.

LAMP:
https://github.com/turnkeylinux-apps/lamp/blob/master/overlay/var/www/index.php#L46-L47)

LAPP:
https://github.com/turnkeylinux-apps/lapp/blob/master/overlay/var/www/index.php#L46-L47

Probably plenty of others too!

**Comment by l-arnold** [comment]
For those wanting phpppgadmin or phpmyadmin, should they not still be available to them?

If App is based on LAPP in Plan seems this will self configure.  Perhaps LAMP builds as well.

Adminer interface appeared rather Spartan at first view. Assume this causes no impact on TKLBAM migrations.  If Php(XYZ) is installed post Jessie likely would move with any backups etc.  Likely reasons not to do this.

**Comment by JedMeister** [comment]
They will be available (in the standard Debian repo) but you'll need to install yourself (apt-get install). It shouldn't affect TKLBAM backups/migrations, although it may drag additional DBs along that aren't needed anymore (Adminer does not require additional DBs to be set up and I suspect that that is part of the reason why it looks so spartan - I could be wrong though).

In fairness I'm not that familiar working with PostgreSQL so can't really compare. WRT phpMyAdmin vs Adminer; from the glance I've had it seems equivalent, if not superior...

**Comment by l-arnold** [comment]
Likely fine.  Something to be said for one system to learn (theoretically).

(off line Navicat is a nice Manager)

**Comment by JedMeister** [comment]
I've removed @OnGle's assingment to this issue as I have him working on some other stuff! :smile:

**Comment by JedMeister** [comment]
Stefan (@OnGle) has created a new Adminer icon modelled off the Adminer logo and the [existing tklcp icons](https://github.com/turnkeylinux/common/tree/master/overlays/tkl-webcp/var/www/images). See here: https://github.com/turnkeylinux/common/pull/37

Now that we are using Adminer, I'm inclined to create a generic index.html file which we just tweak (e.g. with a sed line in the relevant conf or perhaps use some other trickery). Then the default file could be just included in the tklcp overlay and modified or removed per appliance!? I think it best to defer that change for v14.1 though...

**Comment by JedMeister** [comment]
I still think that a generic index.php would be a good idea, however for now I have just updated the file included with the nginx and lighttpd appliances.

**Comment by DocCyblade** [comment]
Just as an FYI, I am making a generic index.php for the mysql and postgres appliances, then editing them with sed to add adminer. We can use this maybe in the future as part of the tklwebcp overlay,

**Comment by DocCyblade** [comment]
Base file I am using, has some comments in so you can use with sed to target the next line and insert 
https://github.com/DocCyblade/postgresql/blob/upgrade-to-adminer/overlay/var/www/index.php

Also adding it here in case my branch is removed down the road

```php
<!-- TKL Control Panel Template - Use sed to edit. Use TKLCPL comment to help insert lines -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="Content-Style-Type" content="text/css">
        <meta http-equiv="Content-Script-Type" content="text/javascript">

        <title>TurnKey APP_NAME_HERE</title>
        
        <link rel="stylesheet" href="css/ui.tabs.css" type="text/css" media="print, projection, screen"/>
        <link rel="stylesheet" href="css/base.css" type="text/css"/>

        <script src="js/jquery-1.2.6.js" type="text/javascript"></script>
        <script src="js/ui.core.js" type="text/javascript"></script>
        <script src="js/ui.tabs.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function() {
                $('#container-1 > ul').tabs({ fx: { opacity: 'toggle'} });
            });
        </script>
    </head>

    <body>
        <h1>TurnKey APP_NAME_HERE</h1>
        
        <div id="container-1">
            <ul>
                <li><a href="#cp"><span>Control Panel</span></a></li>
            </ul>

            <div id="cp">
                <div class="fragment-content">
                    <div>
                        <a href="https://<?php print
                        $_SERVER{'HTTP_HOST'}; ?>:12320"><img
                        src="images/shell.png"/>Web Shell</a>
                    </div>
                    <div>
                        <a href="https://<?php print
                        $_SERVER{'HTTP_HOST'}; ?>:12321"><img
                        src="images/webmin.png"/>Webmin</a>
                    </div>
                    
                    <!-- Use sed to add to area use div tags-->
                    <!-- TKLCPL_CP_AREA -->
                    
                    
                    
                    <h2>Resources and references</h2>
                    <ul>
                        <!-- Use sed to add to area. Use ul tags-->
                        <!-- TKLCPL_REF_AREA -->
                        
                    </ul>

                </div>
            </div>

        </div>
    </body>
</html>
```

**Comment by JedMeister** [comment]
Cool! :+1: 

FWIW the other thought I had was to create the base file and use variables for the bits that might change. Then you just set the vars and `cat` the base file to where you want it/what you want it as.

OTTOMH currently there are:
`index.php` - most common; all LAMP & LAPP appliances, also IIRC Nginx & Lighttpd (inc fileserver etc)
`index.html` - python/Django apps (uses python to find HTTP_HOST rather than php)
`index.cgi` - don't recall which app I saw it in but essentially same as index.php but special use case
`index.aspx` - ASP.NET appliance (uses mono/.NET to find HTTP_HOST rather than php)

**Comment by JedMeister** [comment]
Actually just re-reading / rethinking ..

Now we are using Adminer the index.php files will be almost identical for LAMP/LAPP/MySQL/PostgreSQL appliances. The only thing that will change is the APP_NAME and the reference/doc links...

**Comment by JedMeister** [comment]
I'm going to shut this for now. For v14.0 we have just updated the individual pages in each appliance... It would be good to do something better; but it will do for now...
