### ISSUE TITLE
missing package webmin-shorewall6

### ISSUE THREAD

**Issue by richard-vd** [turnkeylinux/tracker#364]
The package webmin-shorewall6 is missing. This is necessary to set up firewalling on an IPv6 host.

**Comment by JedMeister** [comment]
Ah ok webmin-shorewall**6** (as opposed to webmin-shorewall (with no 6) which **is** in the repos).

TBH I don't recall OTTOMH how it is built but the source that we use to build all the webmin packages (which AFAIK contains all the ['standard modules'](http://www.webmin.com/standard.html) - which I note includes webmin-shorewall6) is [here](https://github.com/turnkeylinux/webmin). Actually a quick scout reveals that indeed the [archive of the shorewall5 module](https://github.com/turnkeylinux/webmin/blob/master/module-archives/shorewall6.wbm.gz) is in there... Just the package wasn't built (and uploaded to the repo)...

An oversight I would assume... Let's call it a bug! :smile: 

Thanks for reporting :+1:

**Comment by alonswartz** [comment]
Good catch! The package is being built, it just wasn't included in the archive spec. I just added it and will appear next time I sync the archive.
