### ISSUE TITLE
upgrade Webmin to 1.750

### ISSUE THREAD

**Issue by markkrueg** [turnkeylinux/tracker#365]
I set up a new VM from turnkey-core-14.0rc1-jessie-amd64.iso. The first thing I wanted to do was set the time on my VM using webmin. The System Time module (time.wbm.gz) requires Webmin 1.750; and the rc of core 14 only contains 1.740. Please update.

**Comment by JedMeister** [comment]
Bugger... We only just built those (v1.740) debs... Thanks for reporting, we'll look at updating  but we'll wait until we're closer to final release though

In the meantime why not just install the 1.740 version...?
 `apt-get update && apt-get install webmin-time`

**Comment by markkrueg** [comment]
Thank you! That worked of course. I had tried doing it from inside webmin: Webmin Configuration -> Webmin Modules -> Standard module from www.webmin.com...and all those give the error that they need Webmin 1.750. I was able to install webmin-time from inside of webmin using System -> Software Packages after first running update at bottom. Thanks for this suggestion as it also fixed the problem for me on an older Turnkey Linux VM I had running without time.

**Comment by l-arnold** [comment]
Ya.  I was just looking at whats all up with Webmin too and noticed that it was updated to 1.75 also.
Was checking to see if there were anyways to get Chrome to work with file manager in Webmin.
https://github.com/webmin/webmin

Not clear there, but they were adjusting their ajax term to work with chrome 43 recently.
I don't see any changes in "file" which appears to be "File Manager".  It has a lot of java going on.

It would be really nice to have the capabilities of File Manager without having to chase Java and Browser Support and UnCertified SSL all the time.

**Comment by l-arnold** [comment]
Other comments (unsolved) regarding File Manager:
https://www.virtualmin.com/node/26236

It seems to me that FileManager is a much bigger issue than replacing the Database Control Managers with Adminer.  (IMHO only)

**Comment by JedMeister** [comment]
@l-arnold  thanks for your comments and links. That's awesome. However Webmin File Manager discussion should probably be in the issue relating to that: #337

**Comment by JedMeister** [comment]
Webmin is now at v1.760 for v14.0/Jessie

Still needs updating for v13.0/Wheezy

**Comment by JedMeister** [comment]
closing this anyway as there is a separate issue (#247) for v13
