### ISSUE TITLE
(Jessie) [TKLdev] (RC1) core not installed during firstboot

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#366]
During both of my attempts to install the 14.0 (jessie) version of TKLdev RC1, core was not installed in /turnkey/fab/products during firstboot.  Running tkldev-setup after logging in successfully installed it.  I was not able to figure out a cause.  The script seems to be running during firstboot and installs the bootstraps, cdroot, and common.

**Comment by JedMeister** [comment]
Thanks for reporting John

**Comment by JedMeister** [comment]
This bug is weird...!? I don't have core either but I have common, bootstrap and cdroot though.

Doesn't make sense to me...

Here's the [tkldev-setup code](https://github.com/turnkeylinux-apps/tkldev/blob/master/overlay/usr/local/sbin/tkldev-setup)

**Comment by l-arnold** [comment]
Same.  Have needed in Tkldev Jessie rc1 to run TKLDEV setup for Core and core is generally required.

Could just issue Git Clone but expect that is in the iso for tkldev itself.  Perhaps not. Or an error.

Landis Arnold

Cell 303.601.0622
Office 303.444.2336

on mobile 
(so typos expected and excusable perhaps)

Sent from Nine
