### ISSUE TITLE
Add additional 'advanced' confconsole options to extend easy firstboot config

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#369]
[update] - Rethinking this; having additional confconsole 'advanced' options is probably a much better way to go...

In discussions elsewhere I thought that perhaps a really good way to add extra config options without making it too complex or making the firstboot inithooks go on forever might be to add an 'advanced' additional option at the end.  

It could allow users to easily tweak settings and install optional software. Some of these "tweak scripts" could be generic scripts (e.g. set language, keyboard, timezone e.g. #38, etc; or install vbox guest addons as per https://github.com/turnkeylinux-apps/tkldev/pull/7...) or could be relevant to specific appliances (perhaps addons that may have some value but are considered adding too much bloat for general appliances - the addition of Abiword to the Etherpad appliance springs to mind #285 ...)?
##

**Comment by l-arnold** [comment]
Good idea!

**Comment by JedMeister** [comment]
That's how the inithooks are already. And those bash scripts call the python scripts in /usr/lib/inithooks/firstboot.d/bin

I am suggesting a page that asks something like "do you want to set further default confg" or something like that. If you select 'yes' then it leads you to a number of other steps (which may be generic and/or specific to the appliance). 

Thinking about this further it may actually be useful to be able to run these after you have installed if you choose (e.g. a command to run them independently of the firstboot inithooks - if you don't want to reset passwords etc). Perhaps it could be `turnkey-extra-init` or something similar?

**Comment by l-arnold** [comment]
That would be an effective way to have a system that started basic, but added options.
In Odoo for instance you could choose from "various external addons" rather than making different Apps with and without them.

One thing that would be great would be a Site Call (forgetting the term) for SSL so that a cert could be pretty easily generated from there.  A really good system could even pull an Authenticated .crt file down during install.

**Comment by DocCyblade** [comment]
This is something too that I need to further config the RT app I am working on. Maybe even a hook into the console screen to allow nice menus.

**Comment by JedMeister** [comment]
@l-arnold 
>One thing that would be great would be a Site Call (forgetting the term) for SSL so that a cert could be pretty easily generated from there. A really good system could even pull an Authenticated .crt file down during install.

Exactly what I was thinking for #382! :smile: 

@DocCyblade 
>Maybe even a hook into the console screen to allow nice menus.

Again pretty much what I was thinking... A firstboot turnkey inithook that asks if you want access to another page that presented the other options. The page that asks would need to support preseeding. And ideally the other options would also support preseeding (with sensible defaults that remain consistent with the way TKL is currently configured.

**Comment by wvengen** [comment]
Would an as-short-as-possible firstboot sequence (to get started easily) with the ability to set advanced options from confconsole solve this as well?

Firstboot would then be run using all files from /usr/lib/inithooks/firstboot.d like now.
Confconsole would look in, for example, /etc/confconsole/confscripts.d. A new confconsole screen would list the files in order, and allow them to be run from there. Titles could be either filename without numerical prefix and underscores turned into spaces, or parsed from a comment-block in the files themselves (just like the `INIT INFO` block in /etc/init.d/* - which would allow for more metadata like putting something into a submenu). Relevant firstboot scripts would be symlinked to the confconsole directory if they can be rerun.

**Comment by JedMeister** [comment]
@wvengen - Yep that sounds like a great way of attacking it. Whether or not this makes it into v14.0 though we are not yet sure. The v14.0 update is already taking us longer than we had hoped so we might have to start pushing some of the additional cool features like this out to v14.1...

**Comment by JedMeister** [comment]
Most of the work for this has been done and the new confconsole package is in our `jessie-testing` repo. Assigning @DocCyblade as lead battle tester! :smile:

**Comment by DocCyblade** [comment]
Since this issue is with "extending" the confconsole for making your own. Thats what I will test. Create a simple extension and a more complex one, and test the integration. I'll post my testing code and methodology here in this issue.

**Comment by JedMeister** [comment]
FWIW the new confconsole package is in turnkey's `jessie-testing` repo. So you can install the new version like this:
````
cat > /etc/apt/sources.list.d/tkl-jessie-testing.list <<EOF
deb http://archive.turnkeylinux.org/debian jessie-testing main
EOF
apt-get update
apt-get install confconsole
````

FWIW to disable that you can just rename the list file (I use a `disabled` suffix but any file extension other than `.list` should do the trick):
````
mv /etc/apt/sources.list.d/tkl-jessie-testing.list /etc/apt/sources.list.d/tkl-jessie-testing.list.disabled
````

**Comment by JedMeister** [comment]
As discussed elsewhere, the new improved confconsole is a bit buggy and is in the process of being tweaked. Once we have an updated version I will let you know.

**Comment by JedMeister** [comment]
Closing as this is now supported in Confconsole v1.0.0+ (not yet released, but should be any day now).
