### ISSUE TITLE
Add ncurses-term to Core

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#370]
It was suggested that we add [ncurses-term](https://packages.debian.org/jessie/ncurses-term) to Core:

>I would consider adding ncurses-term to the core plan. It contains
terminfo definitions for less common terminals; mine is
«rxvt-256color» and without installing ncurses-term ncurses stuff such
as inithooks and even simple commands like «clear»/^L don't work, so I
have to install it every time I'm testing an appliance. I imagine
other users might welcome it as well and it's a pretty tiny package.

**Comment by DocCyblade** [comment]
@JedMeister I am pretty sure https://github.com/turnkeylinux/common/pull/33 closes this if I read this correctly.

**Comment by JedMeister** [comment]
Right you are! Thanks for the heads up! :smile:
