### ISSUE TITLE
rotate logs on redmine appliance

### ISSUE THREAD

**Issue by er2** [turnkeylinux/tracker#373]
I just found a 200mb production.log file in /var/www/redmine/log. Let's rotate that by adding an entry for it in /etc/logrotate.d

**Comment by JedMeister** [comment]
Just posting some links here that might be useful for implementing this:
http://www.redmine.org/boards/2/topics/25236?r=35243#message-35243
http://www.milliondollarserver.com/?p=626
http://keihsler.com/dokuwiki/barn/public/doku.php?id=redmine:bitnami_2_5_2_2#setup_log-rotating
https://forums.freebsd.org/threads/howto-redmine-nginx-passenger-postgresql.41256/
https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Log_Rotation
