### ISSUE TITLE
JESSIE from TKLDEV RC1 TKLBAM in WEBMIN - fails on Restore 

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#378]
It appears I can at least start a Restore Cycle in WebShell   (both LAPP and lapp based Odoo)

Webmin returns prompt Error  (sadly just lost my WebShell when I went to retrieve the text just now)

Lets see if we get a Working Restore in a few minutes.

**Comment by l-arnold** [comment]
Restores seem to be working from Webshell to systems modified in TKLDEV to same.  Restores to barebones LAPP do not work in terms of the "Upfront" components.  It appears however that the rest of the files are restored and put into place.  (but on first tests, can't get Odoo Server to invoke though all the files are there).

**Comment by l-arnold** [comment]
Webmin Error text:

Error - Perl execution failed

syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 9, near "skip_packages skip_files skip_database limits)"
  (Might be a runaway multi-line () string starting on line 7)
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 12, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 17, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 38, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 41, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 50, near "}"

**Comment by l-arnold** [comment]
Mostly a comment.
Odoo TKLBAM Restore in SSH Works Full Database and installed SSL Certs went over in the transfer.

(incl overwriting /plan/main/ which I should have excluded)

**Comment by JedMeister** [comment]
As Alon noted there are no TKLBAM profiles for the v14.0 products yet... And there won't be until v14.0 stable is released. So until the release TKLBAM Jessie related stuff is not a bug, it's just how it is. So I'm going to shut this now.

If you want to do TKLBAM backups of Jessie appliances you'll need to configure that yourself for now. Please feel free to document your progress, experiments and experience, but it's probably better on the forums. That helps keep the noise down on the tracker while we're in dev mode...

**Comment by l-arnold** [comment]
Note however that TKLBAM did work (via SSH, not WEBMIN).  The Issue was with Webmin Call.

I don't know why TKLBAM worked but it did (both backup and restore) in SSH.
