### ISSUE TITLE
[Jessie] Install Grub issues with LVM

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#379]
I chose Option 2 to set up LVM

Fatal Errror, then
Debian Installer Live
options to

Partitition Disks
Install the System
Install the Grub boot loader
finalize

Reboot did not work.  Needs a New VM

**Comment by JedMeister** [comment]
I just updated the title to (IMO) better reflect  the issue.

Also others have reported this (or very similar) issue:
http://www.turnkeylinux.org/14-rc1-aka-we-need-you#comment-23161
http://www.turnkeylinux.org/14-rc1-aka-we-need-you#comment-23257

**Comment by JedMeister** [comment]
And another:
http://www.turnkeylinux.org/14-rc1-aka-we-need-you#comment-23272

**Comment by qrntz** [comment]
As the fix was merged, I believe this is candidate for closing.

**Comment by JedMeister** [comment]
:+1:
