### ISSUE TITLE
Set timezone and keyboard on firstboot (or soon after)

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#38]
Jeremy created a poll asking users what they thought about setting timezone and/or keyboard on firstboot:

http://www.turnkeylinux.org/polls/would-you-be-able-set-time-andor-keyboard-installfirstboot

Majority seems to think this is a good idea. So do I.
##

**Comment by JedMeister** [comment]
Repegged to v14.1 - should be one of the "advanced inithooks" in #369

**Comment by JedMeister** [comment]
This functionality is included in confconsole as of v1.0.0+ (to be released any day now). Whilst it doesn't do it at firstboot, it is pretty straight forward and easy to access. So I'm closing this for now.

Once we resolve #768 then the firstboot aspect will also be sort of covered (albeit only for preseeded installs). Once we implement some way of interactively accessing Confconsole during firstboot, then the original intention of this will be totally covered.
