### ISSUE TITLE
Joomla 3.4 in Jessie

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#380]
(pulled from my Comments re Joomla Ap - not being numbered) 
Updated TurnkeylinuxApp Joomla25

Killed my repository as it was a abandoned Branch

Running TESTS now, (trying 1 change for Repo to make 3.4 now)
Got a Good Build in Jessie of Base Joomla25 Appliance

This is the Release needed in Overlay if running today towards Joomla 3.4

VERSION="20021/162256/Joomla_3.4.1-Stable-Full_Package.tar.gz"
URL="http://joomlacode.org/gf/download/frsrelease/$VERSION"
  
DELETING now the REST of this ISSUE Below pending completion of new MAKE with 1 Change

Don't Do Branches for Tests.  Seems that had happened a year ago when the branch was started.  Never merged etc so lagging.

**Comment by l-arnold** [comment]
Works for 2.5 but not for 3.4..  at least not yet.

This is my error text when I simply change the Version to the Above in Joomla25
(Will try one more time the long way but seems the system wants diff SQL control)

* Bitvise xterm - 192.168.1.123:22
n x
byte-compiling /usr/local/lib/python2-7/dist-packages/phpsh/ansicolor.py to ansi
df: Warning: cannot read table of mounted file systems: No such file or director
[....] Stopping MySQL database server: mysqldERROR 2002 <H¥000>: Can't connect t
fab-apply-removelist /turnkey/fab/common/removelists/turnkey build/root.patched;
+ URL=http://joomlacode.org/gf/download/frsre lease/20021/162256/Joomla_3.4.1-Sta
+ dl http://joomlacode.org/gf/download/frsrelease/20021/162256/Joomla_3.4.1-Stab
+ curl -L -f -0 —proxy http://127.0.0.1:8124 http://joomlacode.org/gf/download/
+ tar -zxf /usr/local/src/Joomla_3.4.1-Stable-Full_Package.tar.gz -C /var/www/jo
df: Warning: cannot read table of mounted file systems: No such file or director
+ mysql —user=root —password= —batch —execute grant all privileges on joomla
.*■ to joomlaGlocalhost identified by	'f5ffbl3d9el88fd202b8c23507447991' ; flush p
+ curl	-c	/tmp/cookie	-b	/tmp/cookie	http://127.0.0.1/installation/index.php —d
ata jform/5Blanguagez5D=en-US&task=setup.set language&5dl242ca779e5bdb4f50d8cc861
Class InstallationControllerSetup.set language not found+ curl -c /tmp/cookie -b
+ curl	-c	/tmp/cookie	-b	/tmp/cookie	http://127.0.0.1/installation/index.php?vie
+ curl	-c	/tmp/cookie	-b	/tmp/cookie	http://127.0.0.1/installation/index.php?vie
+ curl	-c	/tmp/cookie	-b	/tmp/cookie	http://127.0.0.1/installation/index.php —d
ata jformz5Bdb_type/5D=mysqli&jform/5Bdb_hostz5D=localhost&jform/5Bdb_userz5D=jo
omla&jform/5Bdb_passz5D=f5ffbl3d9el88fd202b8c23507447991&jformz5Bdb_namez5D=joom
la&jform/5Bdb_pref ix/5D=jos_&jform/5Bdb_oldz5D=remove&task=setup-database&5dl242
Class InstallationControllerSetup.database not found+ curl -c /tmp/cookie -b /tm
+ curl -c /tmp/cookie -b /tmp/cookie http://127.0.0.1/installation/index.php —d
ata jform/5Bftp_enable/5D=0&jform/5Bftp_user/5D=&jform/5Bftp_pass/5D=&jform/5Bft
p_rootz5D=&jform/5Bftp_hostz5D=127.0.0.1&jformz5Bftp_portz5D=21&jform/5Bftp_save
Class InstallationControllerSetup.filesystem not found+ curl -c /tmp/cookie -b /
tmp/cookie http://127.0.0.1/installation/index.php —data jform/5Bsite_name/5D=T
urnKey+Joomla&jformx5Bsite_metadesc/5D=&jformx5Bsite_metakeysx5D=&jform/5Badmin_
emailx5D=admin(?example .com&jf orm/5Badmin_userx5D=admin8f jf orm/5Badmin_passviord/5D
=turnkey8fjf ormz5Badmin_password2x5D=turnkey&task=setup.saveconf ig8e5dl242ca779e5b
Class InstallationControllerSetup.saveconfig not found+ curl -c /tmp/cookie -b /
+ sed -i s!sef_rewrite = '0'!sef_rewrite = '1'! /var/www/joomla/configuration.ph
+ mysql —user=root —password= —batch —database=joomla —execute INSERT INTO
jos_content UfiLUES <'1', '35', 'Welcome to TurnKey Joomla', 'welcome', '', '<h2>
Getting started</h2Xp></p><ulXli>Log into the <a href=,'administrator,’>administ
ration console</a> as <strong>admin</strongX/li> <li>Refer to the <a href=°http
://www.turnkeylinux.org/joomla25,’>TurnKey Joomla release notes</aX/liXli>Refer
to the <a href ="http://docs.joomla.org'’>Joomla documentation</a></liX/ulXp></
U>', ", '1', '0', '0', '2', '2010-01-01 00:00:00', '42', ", '2010-01-01 00:00:
§0', '0', '0', '2010-01-01 00:00:00', '2010-01-01 00:00:00', '2020-01-01 00:00:0
0' , ", ", ' <,,show_title,p:	"link_t	it les”:	"show_intro":	’’show.category”:"
r, "link^ategory”:	,pshow_parent_category,p:,MP, ,plink_parent_category,p:,p,p, ,pshow_a
uthor,p:,p,p, ,plink_author”:,p,p, ,pshow_create_date,p:,p,p, ,pshow_modif y_date,p:,p,p, ,pshow_pub
lish_date,p:,p,p, ,pshow_item_navigat ion,p:,p,p, ,pshow_icons,p:,p,p, ,pshow_print_icon,p:,MP, ,psh
ow_email_icon,p:,p,p, ,pshow_vote,p:,p,p, ,pshow_Iiits,p:,p,p, ”show_noauth”:,p,p, ,palternat ive_i'e
&dmore,p:,p,p,"article_layout'1', '0', '1', ", ", '1', '0', ", '1', '*',
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' fai
rootPtkldev	tt Error 1
bJ

**Comment by l-arnold** [comment]
Likely my Cleanest Error after FRESH FRESH attempt of modified Joomla25 which did build:

Seems close but something about the Make File needs to be fixed.  I recomend doing a raw joomla install and looking at the starting Datafile:

Here is my error:

* Bitvise xterm - 192.168.1.123:22
_ n
+ sed -i s!sef_rewrite = '0' isef_rewrite = 'l'i /var/www/joomla/configuration.ph
P
+ mysql —user=root —password2 —batch —database=joomla —execute INSERT INTO
jos_content UALUES <'1', '35', 'Welcome to TurnKey Joomla', 'welcome', ", '<h2>
Getting started</h2Xp></pXulXli>Log into the <a href =,padministrator,p>administ
ration console</a> as <strong>admin</strongX/li> <li>Refer to the <a href=,,http
://www.turnkeylinux.org/joomla25,p>TurnKey Joomla release notes</aX/liXli>Refer
to the <a href =,phttp://docs .joomla.org,p>Joomla documentation</a></liX/ulXp></
p>', ", '1', '0', '0', '2', '2010-01-01 00:00:00', '42', ", '2010-01-01 00:00:
00', '0', '0', '2010-01-01 00:00:00', '2010-01-01 00:00:00', '2020-01-01 00:00:0
0' , ", ", ' <"show_title,p: "link_titles": "show_intro": "show.category”: ”
”, ,plink_category,p:,p,p, ,pshow_parent_category”:,p,p, ,plink_parent_category”:,p,p, ,pshow_a
uthor”:,p,p, ,plink_author,p:,p,p, ,pshow_create_date,p:,p,p, ,pshow_modif y_date,p:,p,p, ,pshow_pub
lish_date,p:,MP, ,pshow_item_navigat ion,p:,p,p, ,pshow_icons,p:,p,p, ,pshow_print_icon,p:,MP, ,psh
ow_email_icon,p:,p,p, ,pshow_vote,p:............................ ,pshow_noauth,p:,p,p, ,palternat ive_i'e
admore,p:,p,p, ,part ic le_layout,p: ,p,p>', '1', '0', '1', ", ", '1', '0', ", '1', '*',
ERROR 1146 <42S02> at line 1: Table 'joomla.jos_content' doesn't exist
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' fai
led
make: Ibuild/stamps/root .patched] Error 1
rootOtkldev #

**Comment by l-arnold** [comment]
I went in and ran one of the EMPTY Builds I got yesterday (see early comment re no CONFIG file)  the installation script as done inside TKLDEV for Joomla

It did install.  One issue is that Joomla Wants to use a Random Code for the header (discouraging SQL injection I believe).  Same goes for "naming" the main Database file.

Here are some Pics from Install into the one Joomla3.4 that did build along the way for me (without data)
![joomla 1](https://cloud.githubusercontent.com/assets/5673448/7824348/83f41fe6-03bf-11e5-9d86-8c6171b5bf35.png)
![joomla 2](https://cloud.githubusercontent.com/assets/5673448/7824351/885b3ef2-03bf-11e5-9495-820c7e583a96.png)
![joomla 3](https://cloud.githubusercontent.com/assets/5673448/7824354/8d4fffe2-03bf-11e5-9e6b-530fe75c038d.png)
![joomla 4](https://cloud.githubusercontent.com/assets/5673448/7824359/9205ec18-03bf-11e5-86b3-b8446aa93b70.png)

**Comment by l-arnold** [comment]
Perhaps another approach would be to keep the Installation script in the installed appliance, but modify the script so that the variables and artwork is added.  Might increase security on all this really.

**Comment by l-arnold** [comment]
Working Installer Now.

Git Hub  https://github.com/l-arnold/tkl-joomla34.git
built  ISO now:
              https://sourceforge.net/projects/tkljoomla34/files/

For some reason the Admin Password is getting jumbled at install (both manual build and Tkldev built).
I can get in by changing in Mysql the "jos_user" file in Mysql to any of the hashed passwords on this link page:  :  https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

Almost working..  Nice Looking system but more code to be changed (joomla25 has 2 Changes in my git, both in /conf.d Folder)

**Comment by JedMeister** [comment]
Great thanks! :) That is super handy to have a base building/working system. It sounds like we'll need to update the inithook password creation...

**Comment by l-arnold** [comment]
Also, I expect you need to specify the mysql password when you create the database (seems to write right over the joomla (blank) database which gets created now.

**Comment by JedMeister** [comment]
I'll get a guy to look at this today and he can use what you have already done as a reference! :) Thanks again.
