### ISSUE TITLE
PostgreSQL - Does not build under tkldev14rc1

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#383]
I am testing PostgreSQL, looks like it needs some work. I have forked on my github and will be working on it here https://github.com/DocCyblade/postgresql/tree/jessie-tkldev14rc1 

I'll see if I can get it to build with the latest postgres, let me know if someone else is working on it

**Comment by l-arnold** [comment]
It looks like I got a build.  Go to your Postgresql folder and run 

make clean && make

It is likely that you had some timeouts which have been on going.  That said, not sure why it didn't build for you.  (Landis,  another user is all)

**Comment by l-arnold** [comment]
If you would like to try the ISO I built just loading it now to my upload folder on SourceForge.
I should make a different one for builds like this and Joomla that I was working on.
Should be there shortly  (see Files)

https://sourceforge.net/projects/tklnomadicodoo/

**Comment by DocCyblade** [comment]
Tried again got the same message 
![screen shot 2015-05-29 at 9 22 32 pm](https://cloud.githubusercontent.com/assets/9731860/7895083/f24f2126-0648-11e5-92db-9c98dbe5f4b7.png)

**Comment by DocCyblade** [comment]
I changed the line in the plan file 
postgresql-9.4-postgis 

It now builds

**Comment by l-arnold** [comment]
Nice.  Forgot about that.  Not in my iso.

Landis Arnold
Cell. 303.601.0622
Office. 303.444.2336

Please excuse my mobile phone typos

**Comment by JedMeister** [comment]
Great work. Please issue a pull request from your branch and I can tick it off... :smile:

**Comment by DocCyblade** [comment]
I did this AM (https://github.com/turnkeylinux-apps/postgresql/pull/1)  I'll be testing the ISO and other things soon

**Comment by JedMeister** [comment]
Closing due to https://github.com/turnkeylinux-apps/postgresql/pull/1
