### ISSUE TITLE
MySQL - Does not build, needs work

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#384]
Does not build, still testing on why. Wanted to get a issue open so it's known that is does not build. More info soon

**Comment by DocCyblade** [comment]
Tried another build, looks like everything goes well until this line, the error:

`gzip: /usr/share/doc/phpmyadmin/examples/create_tables.sql.gz: No such file or directory`



![screen shot 2015-05-31 at 7 33 40 am](https://cloud.githubusercontent.com/assets/9731860/7901775/bc9cba3c-0767-11e5-8812-3b2cf48cf668.png)

**Comment by DocCyblade** [comment]
Think I found out why it's not building. Issue with phpmyadmin... running some more builds now

**Comment by DocCyblade** [comment]
Ok, so it looks like I had a dirty mysql build. I must have started to remove phpmysql to replace with adminer A fresh clone resulted in an ok build. I tried the build twice and it works as is. We can close this unless someone else is having a build issue.

I would like to know where below line is being called from as I have removed phpmyadmin from the plan and conf.d. 
`fab-chroot build/root.patched --script /turnkey/fab/common/conf/phpmyadmin`

I will focus my attention then to another issue :-)

**Comment by JedMeister** [comment]
You should be able to just use the Adminer code that's already in common. However if we use LigHTTPd as the server instead (which I think is a good idea) then we'll need to do the config for that...

**Comment by JedMeister** [comment]
Oops sorry didn't answer your question... 

It looks like it's being called in the [makefile](https://github.com/turnkeylinux-apps/mysql/blob/master/Makefile)

**Comment by DocCyblade** [comment]
maybe we should be looking for adminer-lighttpd common config then? We would be able to use it in the postgres and mysql app and did a quick look do we have any of these that admire supports 
( MySQL, PostgreSQL, SQLite, SimpleDB, Elasticsearch, MongoDB) we could use it for them as well. lets keep it DRY

**Comment by JedMeister** [comment]
Great plan. 

I suggest that the way to go would be an adminer-lighttpd overlay and conf; essentially a lighttpd version of the adminer-apache [overlay](https://github.com/turnkeylinux/common/tree/master/overlays/adminer-apache/etc/adminer) and [conf](https://github.com/turnkeylinux/common/blob/master/conf/adminer-apache) (in common).

The Adminer package itself would just go in each of the appliances' (MySQL & PostgreSQL) plans.

**Comment by DocCyblade** [comment]
Sounds like a plan... I just forked common I'll work on that next. I could use adminer in my double db appliance I am working too!

**Comment by l-arnold** [comment]
Briefly want to say..  is there a plug-in for Webmin which would support lighly?  One of the attractions to the common approach is that if you learn how to modify something (like apache) on one app you can use that knowledge on another.  Lightly configuration is daunting from this point as there is nothing familiar about it and even Web resources are not fully helpful. Writing from a user's perspective.  Needs to be some GUI  or simple edit button in Webmin for this IMHO.

**Comment by l-arnold** [comment]
Seems commonbquest.  Search webmin lighttpd support" on google.

Found turnkeylinux lightly server.   The configuration for lightly app if in tKL should also mimicking Postgres and mysql if using lightly in the two dB ones.

Some concern should be there for tKLbam migrations from very 13 to 14.  How much will break?  Ideally none.

**Comment by DocCyblade** [comment]
Should we open another issue for the tkldev common as feature to add adminer-lighttpd and link these with the new issue to show these apps are waiting for a update to common, if so I'll do that and document my work on that issue.

**Comment by JedMeister** [comment]
@l-arnold 
>is there a plug-in for Webmin which would support lighly?

Doesn't look like it

>Lightly configuration is daunting from this point as there is nothing familiar about it and even Web resources are not fully helpful. Writing from a user's perspective. Needs to be some GUI or simple edit button in Webmin for this IMHO.

That is why we generally use Apache as the default webserver on all appliances. Whilst Apache is a bit of a resource hog, it is also very flexible, relatively easy to configure (even from commandline/text editor) and is incredibly well documented. The codebase is very mature too so you rarely have massive changes to config (although in fairlnees there have been a few 2.2 -> 2.4) which makes the finding relevant tutorials and asistance relatively easy. And it has a Webmin module too! :smile: 

>Some concern should be there for tKLbam migrations from version 13 to 14. How much will break? Ideally none.

I agree, but I'm happy to leave that for Liraz to look into (he's the TKLBAM daddy).

@DocCyblade 
>Should we open another issue for the tkldev common as feature to add adminer-lighttpd and link these with the new issue to show these apps are waiting for a update to common

Not a bad idea, because this is essentially 3 separate 'issues'; the 2 appliances will rely on the updated code in common. Having said that though I think that if you focus on one appliance; producing both the common and appliance specific changes, then tweaking the other appliance to use the same common code would be straight forward... So I'm happy to run with whatever you choose. It looks like you've stuck your hand up to do the work anyway...! :smile:

**Comment by JedMeister** [comment]
Now that #387 exists, let's close this...
