### ISSUE TITLE
MySQL - replace phpmyadmin with Adminer

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#385]
Need to implement adminer instead of phpmyadmin. 

TODO: 
~~~1. Remove all trace of phpMyAdmin from build files~~~
~~~2. Add adminer to build files~~~
~~~3. Customize adminer install target PostgreSQL~~~
~~~4. Add Web Basic Web control panel at 80/443~~~
~~~5. Replace documentation verbiage to adminer from phpMyAdmin~~~

Working branch https://github.com/DocCyblade/mysql/tree/upgrade-to-adminer for those who want to track the code process

**Comment by DocCyblade** [comment]
So is the trend to replace phpmyadmin with Adminer? Also asked before about the postgresdb, we should use lighttpd instead of apache ?

**Comment by JedMeister** [comment]
I think that's a good idea! :+1:

**Comment by DocCyblade** [comment]
Work has started, pending pull request 35 on common I am using that as a base 

https://github.com/turnkeylinux/common/pull/35

**Comment by DocCyblade** [comment]
TODO: 
1. Remove all trace of phpMyAdmin from build files
2. Add adminer to build files
3. Replace documentation verbiage to adminer from phpMyAdmin

Working branch https://github.com/DocCyblade/mysql/tree/jessie-mysql-adminer for those who want to track the code process

**Comment by DocCyblade** [comment]
Researching on how to extent adminer found this. Maybe able to use this as an include to customize adminer to our liking.

http://www.adminer.org/en/extension/

**Comment by DocCyblade** [comment]
Working on this now, I should have a pull request by Friday 11pm EDT.

**Comment by JedMeister** [comment]
Awesome mate! :smile: 

FWIW I think that the comments I left on your postgres PR will (mostly) apply here too...

**Comment by DocCyblade** [comment]
Performing final testing now, pull request within the hour as long as everything looks good
