### ISSUE TITLE
TKLDev Common - Add adminer-lighttpd 

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#387]
Add to common overlay and conf a Adminer with lighttpyd to be used by MySQL and Postgres (and any other app that would need it)

**Comment by l-arnold** [comment]
It seems to me if only for 2 apps we should bypass common for now.  If for a number of other database apps then would make sense.  I understand both https://github.com/l-arnold/tkl-nomadic-odoo/tree/master/overlay/var/www mysql and postgresql awaiting this?  What about fileserver and other lightly apps?

I understand Lapp and lamp are using adminer now as I expect are others.  Are they calling a common build?   Can we model Adminer pulls off those merging process with previous data managers for postgresql and mysql?

**Comment by l-arnold** [comment]
As I am wrangling with another subject but while waiting I went to the Common Repository and searched for. 

I think this can be built into POSTGRESQL and MYSQL without a Common Config for now
---------------
Here is why I believe so

Go to:
https://github.com/turnkeylinux/common

Search Repository for "adminer"

There is not too much really going on there.

conf for adminer-apache
overlays for adminer-apache

Then there are for both LAMP and LAPP
plans
overlays
mk

I don't think we want to have the Base Overlays for MySQL and POSTGRESQL also end up in common.  Seems hard to build.

Only Two files then are the APACHE Conf Files
(GET THE WHOLE FILE)
conf/adminer-apache 
#!/bin/sh -e
2	
3	echo Listen 12322 >> /etc/apache2/ports.conf
4	ln -s /etc/adminer/apache.conf /etc/apache2/sites-available/adminer.conf
5	a2ensite adminer
6	
7	# add mcrypt support to apache2 (if not already configured)

and (GET THE WHOLE FILE)
overlays/adminer-apache/etc/adminer/apache.conf 
    SSLCompression off
10	    ServerAdmin webmaster@localhost
11	    DocumentRoot /usr/share/adminer/adminer
12	    Alias /adminer/static /usr/share/adminer/adminer/static
13	    Alias /externals /usr/share/adminer/externals
14	    Alias /editor   /usr/share/adminer/editor

**Comment by DocCyblade** [comment]
I think the idea of not having apache, was memory foot print and the fact if you add apache and php you basically have a LAMP/LAPP server do you not? Personally I don't use the web based phpmyadmin/phppgadmin. I would connect to the server and perform command line or use a GUI utility. 

Maybe the question should be why not use a webmin module only for basic quick changes and just dump  phpmyadmin/phppgadmin

Or another train of thought, base it on the lapp/lamp build, but do some tweaking to the database server config files to make it more useful for a "database server" 

I like this discussion, however I am going to continue working on postgres with aim at a common config just because it will be fun to hack and try it out. I'll let the core devs make the final choice.

**Comment by l-arnold** [comment]
Sounds good.  Just learned something about the certs etc that get built in the .conf file for Adminer (by way of a totally different "copy/paste"...  Will plug a bit at this.

Your idea bout mod Lamp/Lapp is not off the mark.  I think we should simply compare the .conf files for Adminer in Apache and LightTPD and we will understand the differences in set up required.  Trick is to look at the overlay .conf files (likely in Core) and not get distracted by the generated .conf files in a built ap.  (that was my mistake just now.  The crypts of old blocked a new build w/ apache from starting for a bit).  

Super psyched w/ my Odoo ISO about now.  Will add some docs.

**Comment by JedMeister** [comment]
I think that Lighty set up for Adminer for the DB appliances is the go... Whether it goes in common or not is relatively minor in the grand scheme of things... 

However my inclination would be to put it in common, as then if other DB applications (MongoDB?) also want it then it makes it super simple to add (only need to add it to their make file).

**Comment by DocCyblade** [comment]
I am hacking away right now on it. I am using the PostgreSQL appliance as my test bed. I created a "no phppgadmin" Basically no web management other than webmin (https://github.com/DocCyblade/postgresql/tree/no-phppgadmin) it builds but needs tested. That was easy, rip out all phppgadmin stuff from all the files. Did that just for fun, and for myself

Getting close, I hope to have a working build soon

**Comment by JedMeister** [comment]
Nice one! :+1: 

Adding Adminer back in shouldn't be too hard. It's probably the Lighty config will be the worst of it and that shouldn't be too hard... :smile:

**Comment by DocCyblade** [comment]
Just an update, I have a basic build, but still trying to wrangle lighty's config file. Also correct me if I am wrong, but I think we wanted adminer on port https:/:12322 correct?

Getting close. My goal is to have a working build of the postgres application then port the changes to common, test that then test the common config with MySql as well.

**Comment by DocCyblade** [comment]
Another thing, should we create the adminer.conf file from a config script or use an overlay?

What's the going standard for creating conf files use the script in conf.d or use an overlay

**Comment by JedMeister** [comment]
>Just an update, I have a basic build, but still trying to wrangle lighty's config file. 

Great! :+1: 
>Also correct me if I am wrong, but I think we wanted adminer on port https:/:12322 correct?

Yeah that's what I was thinking... Although I think it would be good to have a landing page too (on 80/443)?
>My goal is to have a working build of the postgres application then port the changes to common, test that then test the common config with MySql as well.

:smile:  That's what I'd do...
>Another thing, should we create the adminer.conf file from a config script or use an overlay?
What's the going standard for creating conf files use the script in conf.d or use an overlay

I'd do both... Essentially a 'generic' adminer lighty conf in an overlay, then a conf script to enable it (and tweak if need be) - model it on the existing adminer-apache. I.e. an /etc/adminer/lighttpd.conf (somewhat like the [apache.conf](https://github.com/turnkeylinux/common/tree/master/overlays/adminer-apache/etc/adminer)) then enable it with a adminer-lighttpd script (again like the [apache one](https://github.com/turnkeylinux/common/blob/master/conf/adminer-apache)).

Then on the appliance itself use the tklcp (simple html front page)...? TBH I don't recall what the old appliance did/does...

**Comment by JedMeister** [comment]
I just realised that you could use the LigHTTPd-PHP-FastCGI appliance's PHPMyAdmin conf script as the base of your Adminer one if you wanted? Have a look here: https://github.com/turnkeylinux-apps/lighttpd-php-fastcgi/blob/master/overlay/etc/lighttpd/conf-available/50-phpmyadmin.conf

Unless of course you are already done... In which case we can probably reuse what you've done already in the LigHTTPd-PHP-FastCGI appliance...

**Comment by l-arnold** [comment]
By the way.  I am a bit lost doing a search in 1 Database (not a table) for a string of text.  Was pretty easy with phpostgreadmin (or whatever it is called).

**Comment by DocCyblade** [comment]
I'll take a look at that tonight!

I have some working code I have not yet committed so yeah, if the other code is better I'll use it

**Comment by DocCyblade** [comment]
Success, was able to get adminer built. Thinking we should have the common with no customization (as far as default database type, let us do that with what ever app we are building we can customize the database type with a config file. 

Thinking out loud, should we "brand" the login page with TKL and maybe remove the update checking. Looks like jessie installs 3.3.3 (current version if 4.2)

**Comment by DocCyblade** [comment]
I just committed my work. (https://github.com/DocCyblade/postgresql/tree/adminer) I did use the SSL code from the other app. I also did some reading and tried to do some harding of the SSL for light as well. Link I used is in the code. 

Also another question, since we are https://12322 should we redirect http://:12322 and https://12322 to https://:12322/adminer/ 

I think thats all that needs done

**Comment by JedMeister** [comment]
>Success, was able to get adminer built.

Awesome work! :smile: 
>Thinking we should have the common with no customization (as far as default database type, let us do that with what ever app we are building we can customize the database type with a config file.

Sounds good. Did you come across info on how to do that in your travels? It is/was on my todo list for the appliances with PostgreSQL (it seems to default to MySQL so it's irrelevant for them).
>Thinking out loud, should we "brand" the login page with TKL and maybe remove the update checking. 

Nice idea. I was also thinking that we should find a sexy theme to use as the default one is a little plain I reckon...
>I just committed my work. (https://github.com/DocCyblade/postgresql/tree/adminer) I did use the SSL code from the other app. I also did some reading and tried to do some harding of the SSL for light as well. Link I used is in the code.

Looks awesome! 
>Also another question, since we are https://12322 should we redirect http://:12322 and https://12322 to https://:12322/adminer/

Redirecting from http to https is a cool idea. As for redirecting to /adminer; personally I'd make adminer available on the root (ie https://example.com:12322/). When I set it up for Apache I needed to [set up some aliases](https://github.com/turnkeylinux/common/blob/master/overlays/adminer-apache/etc/adminer/apache.conf#L12-L13) so the css and js worked properly. Also FWIW I made the adminer-editor available at /editor (the line below).

**Comment by DocCyblade** [comment]
Great feedback. I'll move adminer to root and set the alias accordingly. I will do a redirect to https

As far as change the default database type it's on my todo list as well. Also I like the idea of a theme, maybe find a good free one and modify it to be the TKL theme. 

My next time to work on TKL is tonight for about hour or so. I should be able to tweak the config and do some adminer research in that time. Will report back tonight

**Comment by JedMeister** [comment]
Sounds brilliant Ken! :+1:

**Comment by DocCyblade** [comment]
Have a look at adminers website (http://www.adminer.org) at end of the main page they have some css themes let me know your thoughts

**Comment by JedMeister** [comment]
Thanks. I had a quick look. although TBH none of them really jumped out at me. I did't mind the last one.

Seeing as you're doing the work maybe you can leave your mark on it (if you want that is!?)

**Comment by DocCyblade** [comment]
## Adminer Database Selection FYI ##

Just an FYI for adminer, it seems to disable or make a default database type (disable all but the one you want) Just comment out the included database drivers. The below snippet will show only postgres

Below snippet from file
**/usr/share/adminer/adminer/include/bootstrap.inc.php**
```php
include "../adminer/include/lang.inc.php";
include "../adminer/lang/$LANG.inc.php";
// include "../adminer/include/pdo.inc.php";
// include "../adminer/drivers/sqlite.inc.php";
include "../adminer/drivers/pgsql.inc.php";
// include "../adminer/drivers/oracle.inc.php";
// include "../adminer/drivers/mssql.inc.php";
// include "../adminer/drivers/mysql.inc.php"; 
```

**Comment by DocCyblade** [comment]
## Adminer Theme Selection FYI ##

Just an FYI for adminer themes,  it seems all themes are controlled by css file located:
**/usr/share/adminer/adminer/static/default.css**

There are a few others you can download on their web site. I like this brown one. Screen shots below


![screen shot 2015-06-10 at 10 04 29 pm](https://cloud.githubusercontent.com/assets/9731860/8098343/df929162-0fbc-11e5-8e34-f61f7a3a98c5.png)


![screen shot 2015-06-10 at 10 05 04 pm](https://cloud.githubusercontent.com/assets/9731860/8098345/e70db7e6-0fbc-11e5-871f-bddcc6d9c57f.png)



![screen shot 2015-06-10 at 10 05 18 pm](https://cloud.githubusercontent.com/assets/9731860/8098347/ec94f472-0fbc-11e5-8810-cd7e8f6ef4a9.png)

**Comment by DocCyblade** [comment]
Ok, so I updated the doc root and fixed some other broken links dues to css/js files being different places.   Added a better (I think) theme. I did not get to do the http:// to https:// redirect. Ran out of time. Should be able to hack at this some more tomorrow evening. Work was commit adminer branch on a fork of the postgres app. https://github.com/DocCyblade/postgresql/tree/adminer

**Comment by JedMeister** [comment]
>Just an FYI for adminer, it seems to disable or make a default database type (disable all but the one you want) Just comment out the included database drivers. The below snippet will show only postgres

Super awesome! IMO we should do that for all appliances!
>Just an FYI for adminer themes, it seems all themes are controlled by css file located:
/usr/share/adminer/adminer/static/default.css
There are a few others you can download on their web site. I like this brown one. Screen shots below

Looks fine to me. Sounds like it's not too much to change anyway if need be...
>Ok, so I updated the doc root and fixed some other broken links dues to css/js files being different places. Added a better (I think) theme. I did not get to do the http:// to https:// redirect. Ran out of time. Should be able to hack at this some more tomorrow evening. Work was commit adminer branch on a fork of the postgres app. https://github.com/DocCyblade/postgresql/tree/adminer

That's awesome! 

Just wondering though, shouldn't some of it  go in common? Or was putting it all in the PgSQL appliance just temporary?

**Comment by DocCyblade** [comment]
I am using Postgres as steer bed. Wanted to make sure it all worked, once I have it they way we want it, I'll transfer it over to common, and build Postgres with my common fork. I'll then test it with the MySQL app if I can get both to work with my changes in my common form I'll submit a pull request on common

**Comment by JedMeister** [comment]
Cool! :smile: Sounds like a fair and reasonable plan :+1:

**Comment by DocCyblade** [comment]
Still trying to get adminer to redirect from http to https. I am not very good an regexp, but I think after this I'll have a better understanding! 

Also after working on this, since this will be in common, I am thinking I need to make sure I disable port 80 and 443 since an app that uses adminer-lighty may need or use 80/443 for something else. 

Use my new found regexp powers and use sed to do some conf file tweaking? Just thinking out loud.

**Comment by l-arnold** [comment]
Hi Ken,
Agree, not to use 80-443 Overtly for real action.  I think though that it an issue for the App rather than the Adminer Hook.  In the App (postgres, mysql etc), I would recomend that Adminer use 12322 (as it does now).  For 80-443, I think there should be  a  "dummy system" in as a placeholder for whoever wants to modify that as the base of their activities.    If need be the Setting could be modified or trashed, but they could see how to call something to those ports  (maybe A simple Html File or better, a view of some Data Driven page.  I recall this is in some of the builds now.  

My approach has beeen to build a "Console" on Ports 12324/12325 (https/http) which could also go out on 80-443.  The Console could  show the usage of the Database and underlying base. 

In terms of the Adminer Hook for Common though Aim for 12322 and call it good.  Notice that 12323 is left "unused".  I personally would like to have that be a space always for an alternative Admin of whatever database is installed.

Good luck.  I will try to find your activity and browse around a bit.

**Comment by DocCyblade** [comment]
I do like the idea of some sort of status page on 80/443 for the app. Know any scripts?

I am using Postgres as a test bed as I said in an above post. 

Don't think I'll get anything done this weekend. On vacation in Washington DC to the Smithsonian. I did bring my lap top so I might sneak some time in! Only problem is my build VMs are at home. I guess I could VPN to my home network :-)

**Comment by l-arnold** [comment]
Not sure how just yet with lightppd but must be a way to put out php.

**Comment by l-arnold** [comment]
Not sure how just yet with lightppd but must be a way to put out some  php.

**Comment by JedMeister** [comment]
I say enjoy your holiday Ken! :smile: 

My thoughts re 80/443 are either a TurnKey 'control panel' (i.e. tkl-webcp) or simply redirect them to Adminer...

If you want to simply redirect all http to https then that is pretty easy, I stumbled across it in my travels and added it to the TurnKey docs ([here](http://www.turnkeylinux.org/docs/lighttpd)). I tested that IIRC it redirects port 80 to 443. I would assume that if you used a non-standard port (e.g. 12322) that it would just redirect http on that port to https on the same port; but I don't know... Obviously it won't cover redirecting to specific ports though.

**Comment by DocCyblade** [comment]
I was thinking that if this adminer-lighttpd on common, we need to disable 80/443 on lighttpd, since that could cause issues with other apps. 

As far as MySQL and Postgress yes I am thinking of TKL-WebCP for 80/443 

Does the webcp use Apache ?

**Comment by JedMeister** [comment]
>I was thinking that if this adminer-lighttpd on common, we need to disable 80/443 on lighttpd, since that could cause issues with other apps.

True, but relatively easy to work around (if you wanted to) by splitting the config; generic in common and specifics in each appliance. 

Regardless it sounds like that is irrelevant because you're going to webcp direction.
>Does the webcp use Apache ?

It doesn't use any webserver. It doesn't even have any html... It's just the css, js and images. You could rob the html from LAMP (or LAPP, etc).

**Comment by DocCyblade** [comment]
Jumping on some of this before I am gone for a few more days to celebrate 11 years being married to my wonderful wife, I think common code is done. I have added code to remove the generic index page put by lighttpd. 

So here is what I am going to do

1. Create new branch from forked common called, adminer-lighttpd.
2. Create new branch from forked Postgres called, jessie-tkldev14
3. Remove all phpPgAdmin code (Will use no-phpPgAdmin branch)
4. Transfer adminer code to common
5. Update jessie-tkldev to use new common code
6. Test, test, test

If all testing if good, I'll submit a pull request on common, once approved and merged, I'll re-test my postgres code, and if all is well, pull request on postgres. That will knock out two issues and I'll work on MySQL next

**Comment by DocCyblade** [comment]
So I am hacking away and I made changes to

1. plan/main (Adds the adminer, lighttpd, php)
2. conf.d/adminer-lighttpd (Config for adminer)
3. overlays
    3a - overlay/usr/share/adminer/adminer/static/default.css (Better theme)
    3b - overlay/etc/adminer/lighttpd.conf (Lighttpd config file for adminer)

So how much should go in common and what should if any be in the app. I am thinking all of the above would be common. I could create the overlay files in conf scripts but's that looks ugly..

Thoughts?

**Comment by JedMeister** [comment]
Great work and happy anniversary! :tada: 

 >1. plan/main (Adds the adminer, lighttpd, php)

Seeing as it's going to be used by both MySQL & PostgreSQL appliances; and we could probably use it for the LigHTTPd-FastCGI appliance too (the LigHTTPd and the MySQL appliance are now very similar) perhaps a shared plan could go in `common/plans/turnkey` (i.e. in here: https://github.com/turnkeylinux/common/tree/master/plans/turnkey)
>2. conf.d/adminer-lighttpd (Config for adminer)

Again I think that should go in common (`common/conf/`) so long as it's fairly generic any specifics could be overwritten by each appliances own `conf.d/main` 
>3. overlays 3a - overlay/usr/share/adminer/adminer/static/default.css (Better theme)

Maybe all of that and the existing apache.conf could all go together in an "Adminer" overlay in common? (I.e. rename this: https://github.com/turnkeylinux/common/tree/master/overlays/adminer-apache to just adminer). Text files are very small and if desired the irrelevant one could just be removed... 

FWIW there is already a precendent for that sort of thing (although not a TurnKey one). A number of Debian packages now come with `apache.conf`, `lighttpd.conf` and `nginx.conf` files (in `/etc/&lt;package-name&gt;/`) - you then just symlink the one you want into the relevant webserver config directory...

**Comment by DocCyblade** [comment]
I like it! I'll work on this more tonight.

As for the rename of the Apache adminer I think so not to break anything I would just add it. Then we can update appliances to use the new common files, then remove un-needed files from common when we know everything has been moved

**Comment by l-arnold** [comment]
Off subject perhaps.  Wondering about a turnkey scripting environment.  Say someone really likes their old database manager, could there be a two command install and have the configuration files drop into place in addition to the app?  Might be easiest in a Webmin environment to arrange... but more difficult to set up the environment?

**Comment by JedMeister** [comment]
@DocCyblade Great and good thinking...

@l-arnold not quite sure what you mean. If you wanted to install it into the appliance then you could just add additional conf/overlay/etc before you built the ISO. If it was afterwards you could just install it manually. Or did I miss your point?

**Comment by l-arnold** [comment]
Jeremy,
All I meant is that if folks want to install "extra tools"  (not into a base app) that there perhaps be some scripts or documentation on how to do so.  Could be for database utilities or other programs really.

I have not spent any time w/ Adminer really but my impression was I liked the old tools better.  Normally I prefer Navicat for that but the previous MySQL and Postgres tools seemed quite competent and a bit more intuitive based on my little time with Adminer to date.

**Comment by DocCyblade** [comment]
@l-arnold I think I know where you're going with your question. Give the end user a choice of tools (Adminer or PHPPgAdmin)  I agree I do most of my db work with Navicat my self, however having an option to "Turn on" on or the other or turn them both off using a Webmin plug-in or some script magic. Am I right? Your dislike for adminer stands out (I agree it's not as robust at PHPPGAdmin/PHPMyAdmin) 

@JedMeister Tell me again why the move to Adminer and away from PHPMyAdmin/PHPPGAdmin I remember seeing a reason from the core devs I thought.

**Comment by JedMeister** [comment]
@l-arnold Ah ok, I get you... Personally I think either it should probably just be documented (so users could copy paste). Or if you'd rather a more automated solution then a script could be developed that then users could run like this:
````
wget http://github-or-some-other-host/install-script
chmod +x install-script
./install-script
````
@DocCyblade The reason why we moved away from phpMyAdmin is because the Jessie version of phpMyAdmin does not honour the port assignment of 12322. You can make it accessible via 12322 but as soon as you log in it redirects to standard https (i.e. port 443). The only workarounds we could find were to either hardcode a FQDN or IP into it's config (using another inithook; thus requiring all LAMP based appliances to have a static IP or a FQDN). Or to move phpMyAdmin to a sub-dir (i.e. /phpmyadmin).

We decided that that requiring all LAMP appliances to have a static IP or a FQDN was not a good thing. It totally defeats the point of appliances defaulting to DHCP. Also it makes using appliances more of a pain, especially considering that LAMP is our most popular product; followed by other LAMP based appliances. 

Having phpMyAdmin available from a separate port has a couple of reasons. One; it makes it really easy to block/disable access to the DB manager. Two, it won't interfere with (or be interfered with by) other webapp config. Thus we don't need to create a convoluted config to work around different webapp  rewrite rules and/or anticipated end user possibilities (in the case of LAMP) - it just works...

We also had a long standing plan to move to Adminer at some point anyway. This was because it is much lighter weight and provides some degree of consistency between appliances (because it supports multiple DBs). Also as you guys have already said; serious DB work usually is done with other tools anyway...

So once we decided to move away from phpMyAdmin, then the move away from phpPgAdmin seemed like a logical follow on. From what I recall Jessie phpPgAdmin didn't break TurnKey the way phpMyAdmin did but seeing as it also supports PostgreSQL it seemed like a no brainer...

**Comment by DocCyblade** [comment]
@JedMeister Thanks for the refresher!  BTW I am hacking away on the config, looks like I'll be able to sneak some time in the next few evenings while the wife does her reading ;-) I hope to have a pull request to you guys for common by Sunday my time. 

Also, should I do one request for all of changes of common for adminer or split it up in some why. I guess you could cherry pick if you wanted to as well. Just want to know before I submit one

**Comment by JedMeister** [comment]
No worries! :smile: 

I say just put it all in one PR. It's all related to the same thing... 

@alonswartz will do final signoff/merge so if he has any specific issues then we can discuss them within the PR. He is currently back to weekly merging which he normally does on a Thursday (he did it daily for a while but it's more efficient to do it in a batch). If he has any specific issue(s) and you are no longer available by the time that happens then I (or someone else) could fork your work and make any alterations if need be... Considering our discussions I don't imagine that there will be any real issues unless of course there is something that we have both overlooked...

**Comment by l-arnold** [comment]
Good explanation.  Crazy about phpMyAdmin defaulting to 443...  I want to say "say it aint so" but I don't have time to explore just now.  

I will explore that script thing.  That whole piece you wrote also generally should go into "docs".  Good info.  Thanks,

**Comment by DocCyblade** [comment]
Well I have my mobile rig ready. My normal TKLDev VM is on my VM server at home.  I now have a VM on my laptop ready to roll. Plan on sneaking some commits in the evening :-)

**Comment by DocCyblade** [comment]
Quick update on progress, I have been working learning the fine art of regex and sed. I have learned a lot in the last few days.

1. Added overlay files overlays/adminer-lighttpd
2. Added conf script common/conf/adminer-lighttpd that sets up a clean install of lighttpd and adminer.

This will allow other apps to add adminer using lighttpd. 

currently testing this (https://github.com/DocCyblade/common/tree/adminer-lighttpd)

**Comment by DocCyblade** [comment]
Testing with my poastgresql fork (https://github.com/DocCyblade/postgresql/tree/upgrade-to-adminer)

**Comment by l-arnold** [comment]
Nice work Ken.  I will see if I can look at the details next day or so.  I am interested in how you went about it vis a vis Core.

**Comment by DocCyblade** [comment]
Working through some issues with whats posted on github as of now. Issue is something with SSL I am thinking, and the redirect is not working. Out of time for tonight..

**Comment by JedMeister** [comment]
Hi Ken, Looks like great work mate. Sorry I haven't had a chance to have a proper look yet. I will try to real soon!

**Comment by l-arnold** [comment]
From June 17. Missed post.  Good enter prettiness Ken.  All good just wanting t o have the old Postgres tools avail with some ease.  No big but something to consider.  More security than opening ports for Navicat though zip prefer Navicat for functional work.

**Comment by DocCyblade** [comment]
@JedMeister - I think you suggested I move apache.conf and my new one in a "overlay/adminer" overlay? I like the idea, however before we remove the adminer-apache we would need to update the all the apps. Thoughts. I am ready to create a pull request on common

**Comment by DocCyblade** [comment]
Must have hit the comment button too soon...

But I wanted to wait as if we want to combine the two I'll add the apache.conf to mine and make a note in the current that it will be moved. Don't want to change something and break known building apps!

**Comment by DocCyblade** [comment]
I have two branches ready

One with just adminer-lighttpd 
(https://github.com/DocCyblade/common/tree/adminer-lighttpd)

One with adminer combine with the apache config
(https://github.com/DocCyblade/common/tree/adminer-lighttpd-apache)

I am going to go ahead and submit one for the combined.

**Comment by DocCyblade** [comment]
Pull request 35 ( https://github.com/turnkeylinux/common/pull/35) submitted

**Comment by JedMeister** [comment]
Sorry on slow response... 
>I think you suggested I move apache.conf and my new one in a "overlay/adminer" overlay? I like the idea, however before we remove the adminer-apache we would need to update the all the apps. Thoughts. I am ready to create a pull request on common

I did and I totally agree with your decision to do the pull request that includes both (apache & lighty). That way we can transition without breaking anything. TBH though I'll probably batch switch all the apps that need it...

**Comment by DocCyblade** [comment]
Glad to be able to help. Always a good thing when the core devs pumped up :-)

I am going to go ahead and work on Postgres and My SQL working with the common i have. That way I'll be ready for those when the merge is done on common. I may go ahead a submit it when I am done just mark it that it would need to wait until the common one is done.

**Comment by JedMeister** [comment]
Sounds great! :)

**Comment by DocCyblade** [comment]
Since pull request 35 on common was merged this can be closed.  

@JedMeister I can open pull request on Lapp and lamp to update them to use the adminer overlay. Or do you want to do it? Also is that the only two that use adminer

**Comment by JedMeister** [comment]
You did the work so I think that you should do it! :smile: But I'm happy to if you don't want to for some reason...
