### ISSUE TITLE
TKLDEV Tomcat on Apache build fail

### ISSUE THREAD

**Issue by bucklandmedia** [turnkeylinux/tracker#389]
My initial build attempt failed due to missing/outdated openjdk-6 versions so I tried a quick fix of editing plan/main and changing refs to openjdk-7 which are available in jessie repo. Looked like the build would complete next time around but failed again. Pasted below... ooops sorry think I pasted a bit too much

Setting up openjdk-7-jre-headless:amd64 (7u79-2.5.5-1~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up ant (1.9.4-3) ...
Setting up openjdk-7-jre:amd64 (7u79-2.5.5-1~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode
Setting up openjdk-7-jdk:amd64 (7u79-2.5.5-1~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/idlj to provide /usr/bin/idlj (idlj) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/javah to provide /usr/bin/javah (javah) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
Setting up tomcat7-common (7.0.56-3) ...
Setting up tomcat7 (7.0.56-3) ...

Creating config file /etc/default/tomcat7 with new version
Adding system user `tomcat7' (UID 111) ...
Adding new user `tomcat7' (UID 111) with group `tomcat7' ...
Not creating home directory `/usr/share/tomcat7'.

Creating config file /etc/logrotate.d/tomcat7 with new version

Warning: Fake invoke-rc.d called
Setting up tomcat7-admin (7.0.56-3) ...
Setting up tomcat7-docs (7.0.56-3) ...
Processing triggers for systemd (215-17) ...
Processing triggers for libc-bin (2.19-18) ...
Processing triggers for resolvconf (1.76.1) ...
Processing triggers for python-support (1.0.15) ...
update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
fuser -k build/root.build || true
touch build/stamps/root.build
deck build/root.build build/root.patched
# apply the common overlays
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/apt build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/autologin build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/bashrc build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/etckeeper build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/grub build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/interfaces build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/lsof-restart-services build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/ntp build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/profile build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/rcS-sulogin build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/resolvconf build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/ssh-emptypw build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/sslcert build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/stunnel build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/turnkey-init-fence build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/udhcpc-fix build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/turnkey.d/webmin build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/tomcat build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/tomcat-apache build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/tomcat-welcome build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/tkl-webcp build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/apache build/root.patched
fab-apply-overlay /turnkey/fab/common/overlays/mysql build/root.patched
# run the common configuration scripts
$(call run-conf-scripts, /turnkey/fab/common/conf/turnkey.d)
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/apt
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/busybox
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/console-setup
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/cronapt
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/etckeeper
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/hostname
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/locale
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/motd
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/persistent-net
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/roothome
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/rootpass
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/shellinabox
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/sshd
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/sslcert
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/sysctl
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/vim.tiny
update-alternatives: using /usr/bin/vim.tiny to provide /usr/bin/vim (vim) in auto mode
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-cats
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-deftab
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-fw
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-history
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-port
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-ssl
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-theme
fab-chroot build/root.patched --script /turnkey/fab/common/conf/turnkey.d/webmin-updates
fab-chroot build/root.patched --script /turnkey/fab/common/conf/postfix-local
[ ok ] Starting Postfix Mail Transport Agent: postfix.
[ ok ] Stopping Postfix Mail Transport Agent: postfix.
fab-chroot build/root.patched --script /turnkey/fab/common/conf/tomcat
+ [ -e /usr/lib/jvm/java-6-sun ]
+ [ -e /usr/lib/jvm/java-6-oracle ]
+ [ -e /usr/lib/jvm/java-7-oracle ]
+ [ -e /usr/lib/jvm/java-7-openjdk-i386 ]
+ [ -e /usr/lib/jvm/java-7-openjdk-amd64 ]
+ JVM=java-7-openjdk-amd64
+ [ -z java-7-openjdk-amd64 ]
+ cat
+ ls /usr/lib/jvm/.java-1.7.0-openjdk-amd64.jinfo
+ JINFO=/usr/lib/jvm/.java-1.7.0-openjdk-amd64.jinfo
+ JINFO=/usr/lib/jvm/.java-1.7.0-openjdk-amd64
+ JINFO=java-1.7.0-openjdk-amd64
+ update-java-alternatives --jre-headless -s java-1.7.0-openjdk-amd64
+ sed -i s/^#JAVA_HOME.*/JAVA_HOME=\/usr\/lib\/jvm\/java-7-openjdk-amd64/ /etc/default/tomcat7
+ [ -e /etc/apache2/sites-available/jktomcat.conf ]
+ a2dissite 000-default
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
+ a2ensite jktomcat
Enabling site jktomcat.
To activate the new configuration, you need to run:
  service apache2 reload
fab-chroot build/root.patched --script /turnkey/fab/common/conf/tkl-webcp
fab-chroot build/root.patched --script /turnkey/fab/common/conf/apache-vhost
fab-chroot build/root.patched --script /turnkey/fab/common/conf/mysql
df: Warning: cannot read table of mounted file systems: No such file or directory
[ ok ] Starting MySQL database server: mysqld ..
[info] Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..
[....] Stopping MySQL database server: mysqldERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
. ok
# apply the common removelists
fab-apply-removelist /turnkey/fab/common/removelists/turnkey build/root.patched;
warning: entry does not exist: etc/apt/trusted.gpg~
warning: entry does not exist: etc/apt/trusted.gpg.d/debian.gpg~
warning: entry does not exist: etc/apt/trusted.gpg.d/turnkey.gpg~
# apply the product-local root overlay
if [ -d overlay ]; then fab-apply-overlay overlay build/root.patched; fi
# run the product-local configuration scripts
$(call run-conf-scripts, conf.d)
fab-chroot build/root.patched --script conf.d/main
+ WEBAPPS=/var/lib/tomcat6/webapps/
+ WEBROOT=/var/lib/tomcat6/webapps//cp
+ mv /var/lib/tomcat6/webapps//ROOT /var/lib/tomcat6/webapps//cp
mv: cannot stat '/var/lib/tomcat6/webapps//ROOT': No such file or directory
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1
root@tkldev products/tomcat-apache#

**Comment by JedMeister** [comment]
Thanks for your report :+1: 

I'll look at it tomorrow (my time it;s nearly 2am now so I probably should go get some sleep... :smile:). 

The standalone Tomcat appliance should be good to go already and so it shouldn't take too much to tidy this one up...

**Comment by bucklandmedia** [comment]
OK Many Thanks, you get some sleep now.

**Comment by JedMeister** [comment]
Not sure when Alon will merge the code but I have fixed/updated it...

If you want to build/test prior to Alon merging it back into the Turnkey repo then you can add my fix branch and build it now...
````
cd tomcat-apache
git remote add jeremy git@github.com:JedMeister/tomcat.git
git checkout -b "jeremy-jessie-update"
git fetch jeremy jessie-update
git merge jeremy/jessie-update
deck -D build/root.patched
rm build/stamps/root/patched
make
````
