### ISSUE TITLE
[TKLDev] During build sometimes default apache site not being disabled

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#391]
Others have reported this too. It seems that once you have been working in a tkldev for a while the default apache site refuses to be disabled (despite the make log showing that the command `a2dissite 000-default` was successful. I have tried putting it in a second time and the log shows that it says `000-default site already disabled`

I have even tried `rm -rf /etc/apache2/sites-enabled/000-default` and it's still there...

**Comment by JedMeister** [comment]
Actually I just tested in a fresh install of tkldev. This only seems to occur in the `build/root.patched` and `build/root.sandbox` **after** creating the iso!?

I just tested `build/root.patched` while building the turnkey tomcat-apache iso (`build/root.sandbox` doesn't exist until afterwards) `ls build/root.patched/etc/apache2/sites-enabled`:
````
jktomcat.conf
````
But after the iso has finished building: `ls build/root.patched/etc/apache2/sites-enabled/`
````
000-default.conf  jktomcat.conf
````
& same for the sandbox: `ls build/root.sandbox/etc/apache2/sites-enabled/`
````
000-default.conf  jktomcat.conf
````

**Comment by l-arnold** [comment]
I am having really strange results one build to the next in this arena also.  Seems very fickle to get .conf files to propigate into apache sites-enabled (symlinks).

Adminer is the only one that seems to consistently make it and the format is very different from what I am used to.  It seems Apache has new format requirements.  doing yet another make right now.

**Comment by JedMeister** [comment]
>Seems very fickle to get .conf files to propigate into apache sites-enabled (symlinks).

If you put your apache site file(s) in the overlay (`overly/etc/apache2/sites-available/`) and then enable them in your `conf.d/main`. Also you need to make sure that the file has a `.conf` file extension! That is new for Jessie... 

So for example your apache conf site file was called odod; then you'd have your config in the file `overly/etc/apache2/sites-available/odoo.conf` and have this in your `conf.d/main`
````
a2ensite odoo
````
If you have consistent issues then I would `fab-chroot` into your `build/root.patched` and muck around with it. Then copy it out of the chroot into your overlay when you'e done. For reference here are the apache changes: http://httpd.apache.org/docs/2.4/upgrading.html

**Comment by l-arnold** [comment]
Yes.  They must end with .conf
they must work in an apache acceptable manner.
for some reason I can pull them if in my "conf.d"  fiolder structure if it starts with 30, but if I separate out and put  all amen sites in filele ending with 60 they do not go through.

See the end of
 odoo 30_odoo_instalation

At github.com/l-arnold/tkl-nomadic-odoo

Also the 12325.conf there was modeled after the joomla.conf in joomla in my directory and engages two ports.

Just can't put thme all  in a separate file and get it to build.  Also very unhappy with some .conf structures at times.  Is building now as is.

I have not synced common or core with my tkldev for a while I should add.

**Comment by JedMeister** [comment]
It shouldn't matter... Did you maybe just forget to make it executable?

**Comment by l-arnold** [comment]
Good one: 

IE: ? 
#!/bin/sh -ex 



----- Original Message -----

**Comment by JedMeister** [comment]
in tkldev run:
````
ls -l conf.d
````
and it should return something like this:
````
total 4
-rwxr-xr-x 1 root root 1328 Jun  7 03:06 main
````
the xs note that the file is executable i.e. -rw**x**r-**x**r-**x** - see the pic below and/or the [post that I robbed it from](http://linuxcommand.org/lts0070.php)

The easiest way to make a file executable is `chmod +x path/to/file`

![Image of permissions](http://linuxcommand.org/images/permissions_diagram.gif)

**Comment by l-arnold** [comment]
Cool.

Did the my conf.d 's make any sense to you?  On my side, it seems there is an old and a new.  Don't really know the diff but some mix of them is coming through.  They tend to NOT come through on a second "make" command though (experience based not scientific)

**Comment by l-arnold** [comment]
Does the command have to be run in tkldev?  Does it make the resulting files all that as well?  Can that command be applied from GitHub?

**Comment by JedMeister** [comment]
>Did the my conf.d 's make any sense to you? 

yeah looks good; although off topic; I'd install wkhtmltopdf from the repos... The [version in Jessie](https://packages.debian.org/jessie/wkhtmltopdf). Just add it to your `plan/main`
>Does the command have to be run in tkldev?

Do you mean `ls`? If so IMO it's easier to do it in tkldev, but in GitHub you can see if a file is executable; if you browse to the file e.g. [your 10-hostname](https://github.com/l-arnold/tkl-nomadic-odoo/blob/master/conf.d/10_hostname); you can see that it says "Executable File" just above the line numbers. Whereas your old [60-apache-conf](https://github.com/l-arnold/tkl-nomadic-odoo/blob/8a05d27e0e2e8acf79738ef8a722b1de9cab0df4/conf.d/60-Apache-conf) is missing that...

But like I said IMO it's easier to check in tkldev; you can check a whole directory at the same time. Executables have the xs like I said, but also by default tkldev colours them (IIRC green for executables).

Or did you mean `chmod +x`? If so, no I don't think so... You'll need to re make it afterwards..

**Comment by l-arnold** [comment]
Ofdbtopic too.  I tried the wkhtmltopdf.  Something up with the package.  Wouldn't run in Odoo reports.  Went to plan B which took a while.

Same with PIP and magento.  Work around worked.

Will split odoo into with and without connectors.  May even trim the base but not sure how easy it is to pull modules on the fly.  ODOO plays some games That way.  I deal would be a Webmin interface to load and unload modules.  Seems workable but some time required.

**Comment by l-arnold** [comment]
What about Odoo from the repos itself?  You said no on a forum post?  Would love to take the load out of the tkldev builds and perhaps the base build.

**Comment by JedMeister** [comment]
I assume you mean the Odoo repos (as it doesn't seem to be in the Debian repos)?

The main reason why I don't think that is a good idea is because Odoo themselves recommend against it. They say that using GitHub is a better way to go...

**Comment by l-arnold** [comment]
I think we are past this issue now.

**Comment by JedMeister** [comment]
closing in favour of #530
