### ISSUE TITLE
TKLDEV Magento Build Fails

### ISSUE THREAD

**Issue by bucklandmedia** [turnkeylinux/tracker#392]
Build of Magento Appliance failed. Note I updated conf.d/downloads version to 1.9.1.1 (May 1) as this is latest stable. Still failed with error below.

+ php -f /var/www/magento/install.php -- --license_agreement_accepted yes --locale en_US --timezone Europe/London --default_currency USD --db_host localhost --db_name magento --db_user magento --db_pass f7a912b70616fdb658f8201dc0be2b9f --url http://127.0.0.1/ --secure_base_url https://127.0.0.1/ --skip_url_validation yes --use_rewrites yes --use_secure yes --use_secure_admin yes --admin_firstname Store --admin_lastname Admin --admin_username admin --admin_password turnkey1 --admin_email admin@example.com --admin_frontname admin --encryption_key 81579a00167483daf8accdcb600d886b
PHP Fatal error:  Call to undefined function mcrypt_module_open() in /var/www/magento/lib/Varien/Crypt/Mcrypt.php on line 63
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 255
root@tkldev fab/magento#

**Comment by JedMeister** [comment]
Oh no! We updated this one while Alon was in the process of building the v14.0 base and we hadn't tested building it on Jessie yet.

Looking at the error my suspicion is that there may be some compatibility issues with the version of php in Jessie... :frowning:

**Comment by l-arnold** [comment]
I was looking yesterday at PHP and I think it should work w/ Magento if in 1.9

http://magento.com/resources/system-requirements...  however, perhaps I need to correct myself:

PHP requirements for COMMUNITY EDITION 1.9.1
I believe PHP is 5.6.7 in Jessie actually.

PHP 5.4
PHP 5.5

**Comment by JedMeister** [comment]
It has been fixed and a pull request issued. It was a new package requirement for Jessie (php5-mcrypt). Also there was a new security patch which has also been applied...

This issue will be closed when the code is merged...

**Comment by l-arnold** [comment]
Just to tie the thread is all:  Just for reference then:  
For Different Magento Store: There are records in
/etc/apache2/sites-available (folder) and /var/www/magento/.htaccess (file)

# in  /etc/apache2/sites-available (with pointers to in sites-enabled)
# for each "virtual store"  is a record
ie, one each for magento site  (aims at domain1  referenced below in .htaccess)
domain2
domain3
domain4
domain5

VirtualHosts are controlling port 80 and 443 with
DocumentRoot /var/www/magento
hostnames on
ServerAlias domain1.com www.domain1.com
Servername domain1.com
(and associated SSL Pointers for each individual cert)

## .htaccess Added
SetEnvIf Host www\.domain1\.net MAGE_RUN_CODE=magintdom1
SetEnvIf Host www\.domain1\.net MAGE_RUN_TYPE=website
SetEnvIf Host ^domain1\.net MAGE_RUN_CODE=magintdom1
SetEnvIf Host ^domain1\.net MAGE_RUN_TYPE=website

SetEnvIf Host ^myipnumber MAGE_RUN_CODE=magintdom1
SetEnvIf Host ^myipnumber MAGE_RUN_TYPE=website

SetEnvIf Host shop\.domain2\.net MAGE_RUN_CODE=domain2
SetEnvIf Host shop\.domain2\.net MAGE_RUN_TYPE=website
SetEnvIf Host ^domain2\.net MAGE_RUN_CODE=domain2
SetEnvIf Host ^domain2\.net MAGE_RUN_TYPE=website

SetEnvIf Host www\.domain3\.com MAGE_RUN_CODE=magdom3
SetEnvIf Host www\.domain3\.com MAGE_RUN_TYPE=website
SetEnvIf Host ^domain3\.com MAGE_RUN_CODE=magdom3
SetEnvIf Host ^noramkayaks\.com MAGE_RUN_TYPE=website

SetEnvIf Host www\.domain4\.com MAGE_RUN_CODE=magintdom4
SetEnvIf Host www\.domain4\.com MAGE_RUN_TYPE=website
SetEnvIf Host ^domain4\.com MAGE_RUN_CODE=magintdom4
SetEnvIf Host ^domain4\.com MAGE_RUN_TYPE=website

SetEnvIf Host shop\.domain5\.com MAGE_RUN_CODE=magintdom5
SetEnvIf Host shop\.domain5\.com MAGE_RUN_TYPE=website
SetEnvIf Host ^domain5\.com MAGE_RUN_CODE=magintdom5
SetEnvIf Host ^wildnet\.com MAGE_RUN_TYPE=website

**Comment by JedMeister** [comment]
As per @alonswartz comment on https://github.com/turnkeylinux-apps/magento/pull/4#issuecomment-111052349 to complete this fix we probably should adjust the ssl-cert regen inithook to happen later in the process. This should happen in common.

**Comment by JedMeister** [comment]
I'm reopening this as it's not yet fixed. We'll need to wait for the resolution of this PR: https://github.com/turnkeylinux/common/pull/34

**Comment by bucklandmedia** [comment]
Yes build now completes successfully but it does spit out the following messages...

/usr/share/initramfs-tools/scripts/casper-bottom/25autologin: 13: .: Can't open                                          /scripts/casper-functions
/usr/share/initramfs-tools/scripts/casper-bottom/25singleuser_shell: 6: .: Can't                                          open /scripts/casper-functions
/usr/share/initramfs-tools/scripts/casper-bottom/25ssh_emptypw: 6: .: Can't open                                          /scripts/casper-functions

**Comment by JedMeister** [comment]
It fixes the build but the appliance still won't work properly until you create a new SSL cert (or install a CA cert). The browser won't accept the autogenerated SSL cert.

Regarding the errors that you note, I'm not too sure about them, but seeing as they relate to casper they would only be an issue if you intend to run the ISO live...

**Comment by JedMeister** [comment]
Closing this one now as I have opened a new issue (#400) which states the issue that we now have with the Magento appliance.
