### ISSUE TITLE
 i386 architecture gives error on apt-get update with 14 RC1

### ISSUE THREAD

**Issue by HansH111** [turnkeylinux/tracker#393]
architecture i386

I used dkpkg --add-architecture i386 to be able to run also 32bit applications

After that the apt-get update gives the following info

.....

Get:23 http://http.debian.net jessie-backports/main i386 Packages [148 kB]
Fetched 19.0 MB in 6s (3055 kB/s)
W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/jessie-security/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://archive.turnkeylinux.org/debian/dists/jessie/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

Is there someway that I can disable this for the turnkey repositories.

**Comment by JedMeister** [comment]
FWIW the issue tracker is for bugs/feature requests. Questions like this are generally handled better on our [forums](http://www.turnkeylinux.org/forum). But seeing as we're here now:

TurnKey only provides a 64 bit Jessie repo so you'll need to configure your system to allow for that.

I don't recall exactly but you need to adjust your sources.list entires for TKL. You need to add amd64 somewhere/somehow (in square brackets perhaps?) to the deb line(s) to tell it that it's only fro 64 bit. If you google you should find the answer. If you keep in mind that TurnKey is based on Debian you should find plenty of info. Plus for more generic stuff like this Ubuntu info should probably appy too...

Turnkey repo is noted in `/etc/apt/sources.list.d/sources.list` and `/etc/apt/sources.list.d/security.sources.list`.

Be great if you could post back to let uw know what works...

**Comment by l-arnold** [comment]
Likely doable.  I think easiest would be to stick with V12 wheezy.  I am a I 386 fan also but from experience the speed is not even close.

If you just need to support it though for an app or 2 it would seem there could be a way.

Can you run things on Wheezy? V13.

**Comment by HansH111** [comment]
>  TurnKey only provides a 64 bit Jessie repo so you'll need to configure your system to allow for that.

Then it would be logical that the Turnkey entries in the sources.list would be marked like amd64 ....
I will report backup how it should be defined in the sources.list

> I think easiest would be to stick with V13 wheezy. I am a I 386 fan also but from experience the speed is not even close.
No, that is not the reason, I want to use the last version because of systemd.
But sometimes you have old binaries/libraries from external parties you need to run...  and that requires some i386 libs

**Comment by JedMeister** [comment]
Thanks @HansH111
