### ISSUE TITLE
Bamboo Invoice - CSS not displaying over HTTPS

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#398]
It has been reported that when built on the Jessie base, Bamboo Invoice does not display properly over HTTPS. It appears to be a issue with CSS

**Comment by JedMeister** [comment]
Might need to swap this so that it only displays via https and redirect http...

**Comment by qrntz** [comment]
@JedMeister, the website has been down for a few days at least so no upstream download. Moreover, the project is not maintained since Jan 2014 (the author went on to work on a [paid alternative](https://www.pancakeapp.com/)). Looks obsolete to me.

**Comment by qrntz** [comment]
No sign of life yet…

**Comment by JedMeister** [comment]
Thanks for checking @qrntz - doesn't bode well really... Oh well if they don't come back online looks like we'll drop it then...

**Comment by JedMeister** [comment]
Closing this due to the fact that we did not build the bamboo invoice appliance for v14.0.
