### ISSUE TITLE
[TKLDev 14 rc1] tool chain not fully initialized when first boot with no network

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#399]
I started up an  TKLDev14 RC1 VM tonight and I forgot to give it a network connection, so it did not do it's downloading of the bootstrap. I tried tkldev-setup script but looks like that did not fix it. Works perfect when you have a network connection to internet, but when you don't TKLDev not so happy.

Is TKLDev-Setup supposed to download the bootstraps? It seems everything else in order.

**Comment by JedMeister** [comment]
IIRC `tkldev-setup` should download the bootstrap (tar.gz and unpack it) and common (git clone).

You raise a good point though. Without a network TKLDev should fail; but ideally it should probably tell you to run `tkldev-setup` once you have a network connection. Then `tkldev-setup` should fix the issue (once you have network), or at least provide some useful error message explaining why it didn't or couldn't...

**Comment by DocCyblade** [comment]
Just happen to stumble on this one. I am guessing it's one of the first boot scripts.

Thinking out loud, not sure how the setup script works (have not peeked at that one yet) maybe we can create a test product that will check and make sure everything is ready to build, build-check or something that will double check that all the files are there to build and give a nice message? Would that be part of the TKLDev app so that it's ready to use even before any network 

Again just thinking out loud.

**Comment by JedMeister** [comment]
Yeah AFAIK there is an inithook which runs `tkldev-setup` although TBH I haven't checked...

Re your :thought_balloon:  I don't know much about makefiles, but I imagine that you could insert some sort of hook to do that...

**Comment by DocCyblade** [comment]
I'll check out the code for tkldev-setup

**Comment by DocCyblade** [comment]
Where can I find tkldev-setup source on GIT hub?

**Comment by JedMeister** [comment]
Good question... I'll have a look

**Comment by DocCyblade** [comment]
Must have missed your update, I'll take a look at this, see what's going on

**Comment by DocCyblade** [comment]
So I took a look and I think I know what happen. During first boot the inithook calls `/usr/local/sbin/tkldev-setup` The script is pretty simple, checks to see if the directory exists then if it does not creates it and downloads things to it. 

Well on first boot I did not have a internet connection. So it created the directories but failed in downloading the stuff that goes into them. So next time I tried to run the `/usr/local/sbin/tkldev-setup` myself since the directions already existed it did not download anything.

Resolution, do a internet check or check to see if we can connect to the server before downloading each item, or do some checks to make sure the wget command downloaded something.

**Comment by JedMeister** [comment]
Or adjust `tkldev-setup` so it does deeper checks (than just whether the dir exists or not).

**Comment by DocCyblade** [comment]
Maybe make some kind of check/stamp that is written so we know each step is done. Would need to check to make sure each step was competed then write out a check/stamp file. That way all you would need to do is remove the stamps/check files to re initialize your tool chain.

I'll look at this more in depth once we have v14 released. We got more pressing issues out there 

:-)

**Comment by JedMeister** [comment]
Or (for cdroot, common and core at least) if it exists (and there are no uncommitted changes) update it!?

But you're right, we have plenty of other stuff to do!

**Comment by DocCyblade** [comment]
@JedMeister we should tag this then 14.1?

**Comment by JedMeister** [comment]
Done! :+1:

**Comment by alonswartz** [comment]
Just came across this issue. I've since refactored tkldev-setup, so on a rerun it will download and/or update the repos. Though, it might be a good idea to add a connectivity check...
