### ISSUE TITLE
my myserviceteam.tklapp.com is not showing login page

### ISSUE THREAD

**Issue by HerinShah** [turnkeylinux/tracker#406]
Hello,

Can you please check why my "myserviceteam.tklapp.com" url is not showing login page?

Thanks

**Comment by JedMeister** [comment]
Well it's serving something but it looks like your Apache config isn't right... The [TurnKey Linux Issue Tracker](https://github.com/turnkeylinux/tracker#turnkey-dev-tracker) is for bugs and feature requests for TurnKey Linux. For help with configuration issues please use the [TurnKey support forums](http://www.turnkeylinux.org/forum/support/). 

So I'm going to close this for now. If you'd like some help please post further details on the [TurnKey support forums](http://www.turnkeylinux.org/forum/support/). Please clearly state what you are trying to do and what you have done to get to where you are and we'll see what we can do to help you out.

If after some further research and testing it seems that there is a TurnKey bug then please reopen this or open a new issue. We'll need a bit more info though. Thanks.
