### ISSUE TITLE
Revision Control Appliance: Support for Smart HTTP 

### ISSUE THREAD

**Issue by quipsy-karg** [turnkeylinux/tracker#407]
The Revision Control Appliance provides (besides others) support for GIT in the form of unauthentitcated git: native protocol and encrypted ssh: protocol. The first lacks security, and latter discloses the on-disc structure of the server's directory hierachy and makes usage more complex than needed.

GIT has support for Smart HTTP, as described in http://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP. Unfortunately this is not enabled on the Revision Control Appliance.

I want to propose to add support for Smart HTTP, as it solves a lot of problems:
* Customizable mapping of simple URL paths to complex on-disc directory hierarchy.
* No firewall troubles, as it runs on HTTP and HTTPS default ports.
* Authenticated.
* Makes use of Apache, which in turn opens a simple path to LDAP / Active Directory authentication.
* possibly more...

**Comment by JedMeister** [comment]
Thanks for posting. I have tagged it for the v14.0 milestone although TBH the chances of it getting into the v14.0 release will rely on someone other than me doing (at least most of) the work! :smile: 

Ideally if it can be done via a pull request to the [Revsion Control](https://github.com/turnkeylinux-apps/revision-control) appliance that'd be super awesome. Step-by-step instructions (that can basically be copy pasted) might be enough though! :smile:

**Comment by JedMeister** [comment]
@qrntz - as discussed elsewhere...

**Comment by fhw72** [comment]
It looks like smart HTTP access is broken in current revision control appliance (TKL 14.1).
Cloning a repository works but pushing back changes does not work and leads to an error 403
from the server.

**Comment by JedMeister** [comment]
Let's reopen this until we are sure that it's working. I've also retargetted to v14.2

**Comment by qrntz** [comment]
Confirmed broken. Working on it.

**Comment by JedMeister** [comment]
We've fixed it for (the currently unreleased) v14.2 but v14.1 or prior you'll need to manually update your config. If you look at the pull requests from Anton (above) then you should be able to see what you need to do. Please post back if you have issues and I'll try to help you out.
