### ISSUE TITLE
Make sure all appliances have relevant and up to date screenshots (in .art in each repo).

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#408]
New appliances will need screenshots and screenshots for existing appliances need to be double checked to make sure they are still relevant and up date if required. This first list contains *all* current appliances and is a list of **those that have been checked or not**. Those that could benefit from (or need) update are in a list in the next comment.

- [ ] asp-net-apache
- [ ] b2evolution
- [ ] bambooinvoice
- [ ] bugzilla
- [ ] cakephp
- [ ] canvas
- [x] codeigniter
- [x] collabtive
- [x] concrete5
- [x] core
- [x] couchdb
- [x] django
- [x] dokuwiki
- [x] domain-controller
- [x] drupal7
- [x] drupal8 - **new**
- [x] e107
- [ ] ejabberd
- [x] elgg
- [x] espocrm - **new**
- [x] etherpad
- [x] ezpublish
- [x] fileserver
- [x] foodsoft - **new**
- [x] gallery
- [x] gitlab
- [x] icescrum
- [x] jenkins
- [x] joomla25 - **renamed**: joomla
- [x] lamp
- [x] lapp
- [x] lighttpd-php-fastcgi
- [x] limesurvey
- [x] lxc
- [x] magento
- [x] mahara
- [x] mambo
- [x] mediawiki
- [x] mibew
- [x] moinmoin
- [x] mongodb
- [x] moodle
- [x] mysql
- [x] nginx-php-fastcgi
- [x] nodejs
- [x] observium
- [x] omeka
- [x] openldap
- [x] openvpn
- [x] orangehrm
- [x] oscommerce
- [x] otrs
- [x] owncloud
- [x] phpbb
- [x] phplist
- [x] phreedom - **renamed - upstream** *phreebooks*
- [x] piwik
- [x] pligg
- [x] plone
- [x] postgresql
- [x] prestashop
- [x] processmaker
- [x] projectpier
- [x] punbb
- [x] rails
- [x] redmine
- [x] revision-control
- [x] roundup
- [x] sahana-eden
- [x] silverstripe
- [x] simplemachines
- [x] sitracker
- [ ] statusnet  - **renamed - upstream** *gnusocial*
- [ ] sugarcrm
- [ ] suitecrm - **new**
- [ ] symfony
- [ ] tendenci
- [x] tkldev
- [ ] tomatocart
- [ ] tomcat
- [ ] tomcat-apache
- [ ] trac
- [ ] tracks
- [ ] twiki
- [ ] typo3
- [ ] ushahidi
- [ ] vanilla
- [ ] vtiger
- [ ] web2py
- [ ] wordpress
- [ ] xoops
- [ ] yiiframework
- [ ] zencart
- [ ] zurmo

**Comment by JedMeister** [comment]
This is a list of servers which could benefit from screenshot updates; or need screenshot updates. Those that would benefit are in *italics*; those that need updating are in **bold** - these are appended in with square brackets. Once completed they will be ticked off.

- [ ] asp-net-apache [*control_panel.jpg*]
- [ ] b2evolution [*webmin_system_overview.jpg*]
- [ ] bambooinvoice [*webmin_system_overview.jpg*]
- [ ] bugzilla [*?updates for new version?*]
- [ ] canvas
- [ ] collabtive [*?updates for new version?*]
- [ ] concrete5 [*???*]
- [ ] core [*webmin_system_overview.jpg*]
- [ ] django [*webmin_system_overview.jpg*]
- [ ] domain-controller [*samba_file_sharing.jpg*,*turnkey_control_panel.jpg*]
- [ ] drupal7 [*webmin_system_overview.jpg*]
- [ ] drupal8 [**all**]
- [ ] e107 [*webmin_system_overview.jpg*]
- [ ] ejabberd [**???**]
- [ ] elgg [*webmin_system_overview.jpg*]
- [ ] espocrm [**?all?**]
- [ ] fileserver [**all**]
- [ ] foodsoft [**?all?**]
- [ ] gallery [*webmin_system_overview.jpg*]
- [ ] icescrum [*webmin_system_overview.jpg*]
- [ ] joomla25 [*all*]
- [ ] lamp [**phpmyadmin_console.jpg** **turnkey_control_panel.jpg** *webmin_system_overview.jpg*]
- [ ] lapp [**turnkey_control_panel.jpg** *webmin_postgresql_configuration.jpg* *webmin_system_overview.jpg*]
- [ ] lighttpd-php-fastcgi [**control_panel.jpg** *webmin_system_overview.jpg*]
- [ ] magento [*webmin_system_overview.jpg*]
- [ ] mahara [*webmin_system_overview.jpg*]
- [ ] mediawiki [*webmin_apache_lamp_configuration.jpg*]
- [ ] mibew [**control_panel.jpg** 
- [ ] moinmoin [*webmin_system_overview.jpg*]
- [ ] mongodb  [*webmin_system_overview.jpg*]
- [ ] mysql [**phpmyadmin_console.jpg** **phpmyadmin_db_config.jpg** *webmin_configuration.jpg*]
- [ ] nginx-php-fastcgi [**control_panel.jpg**  *webmin_system_overview.jpg*]
- [ ] nodejs [*webmin_system_overview.jpg*]
- [ ] orangehrm [*webmin_system_overview.jpg*]
- [ ] oscommerce [*webmin_system_overview.jpg*]
- [ ] phpbb [*webmin_apache_lamp_configuration.jpg*]
- [ ] phreedom (*phreebooks*) [*webmin_system_overview.jpg*]
- [ ] piwik [*webmin_system_overview.jpg*]
- [ ] pligg [*webmin_system_overview.jpg*]
- [ ] postgresql [**phppgadmin_console.jpg** **phppgadmin_sql_exec.jpg** *webmin_configuration.jpg*]
- [ ] prestashop [*webmin_system_overview.jpg*]
- [ ] punbb [*webmin_system_overview.jpg*]
- [ ] rails [*webmin_mysql_rails.jpg* *webmin_system_overview.jpg*]
- [ ] roundup [*webmin_system_overview.jpg*]
- [ ] silverstripe [*webmin_system_overview.jpg*]
- [ ] simplemachines [*webmin_system_overview.jpg*]
- [ ] simpleinvoices
- [ ] sitracker [*webmin_system_overview.jpg*]
- [ ] statusnet (*gnusocial*) [**all** *[*webmin_system_overview.jpg*]*]
- [ ] suitecrm [**all**]
- [ ] symfony [*webmin_system_overview.jpg*]
- [ ] tendenci [**???**]
- [ ] tracks [*webmin_system_overview.jpg*]
- [ ] typo3 [*webmin_system_overview.jpg*]
- [ ] vanilla 
- [ ] vtiger
- [ ] web2py
- [ ] wordpress
- [ ] xoops
- [ ] yiiframework
- [ ] zencart
- [ ] zurmo

**Comment by l-arnold** [comment]
Anyone working on this, I can get a  InDesign template out which I built today to help process this.  Not a "one click" deal but still easier than everything else I was trying in Photoshop and Illustrator.

Message me, or I may find a place to post it for download.

**Comment by JedMeister** [comment]
Hey. Someone is working on an automation to take screenshots and in the future test the appliances too (which will hopefully make updates quicker and easier).
But it probably won't be ready for v14.0 so if you wanted to update a few in the meantime that'd be cool! :smile:

**Comment by l-arnold** [comment]
No Prob.  I will likely do Joomla and Magento first.

**Comment by JedMeister** [comment]
Awesome thanks! :+1:

**Comment by JedMeister** [comment]
Closing this now in favour of 639. I'm going to put a bounty on it and get it done manually for now. We'll still do the testing framework, but the screenshots are really sad...
