### ISSUE TITLE
Look at whether we can rebase on standard Debian-Installer

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#412]
Currently TKL uses `di-live` - a custom installer that leverages Debian-Installer.

Considering that Debian-Installer (apparently) now supports running Debian live, perhaps we could reconsider this and rebase back on the default installer?

**Comment by vondrt4** [comment]
Bump on this. I don't want to open a new issue, but di-live does not support UEFI. I just spent several hours trying to install TKL LAMP for a customer on a physical HP Proliant gen9 server and failed.
UEFI mode: ISO does not boot at all.
BIOS mode: Installer goes through, installs grub-legacy, but system does not boot. Forced boot from HDD loops back to boot menu.
I solved it by installing Debian Jessie in UEFI mode, which installed grub-efi in a FAT partition with EFI partition type. Then over it I installed TKL and it booted. I selected the same /boot partition so grub config probably got overwritten but I skipped grub-install.

**Comment by JedMeister** [comment]
Hi @vondrt4,

Ah, that sucks! 

FWIW I have had some discussions with a Debian insider and he recommended that if we wish to continue providing the "live" functionality, that we not rebase on the standard Debian installer just yet. Apparently the 'live' stuff in the default `di` is somewhat in a state of flux. He recommends that we wait until that has settled down before we proceed. I haven't double checked any of that though, or got a recent update from him...

Having said that, I'm not sure how much the 'live' functionality is used? OTOH I don't think that many install TurnKey to bare metal either. Unfortunately we don't have any stats for either of those so I'm only guessing...

**Comment by JedMeister** [comment]
We should re-investigate where Debian Live is up to. If we can support the "live CD" functionality with the default Debian installer in v15.0, then IMO we should do it.

**Comment by vondrt4** [comment]
The end of di-live is nigh.
https://lists.debian.org/debian-devel-announce/2017/08/msg00002.html
https://lists.debian.org/debian-live/2017/06/msg00064.html

**Comment by JedMeister** [comment]
Hmmm. Ok I wasn't aware. We should get in touch with them and discuss so we can have some insight into what the state of it is. Although, if it's working ok for stretch, then it may still be an option (and decide what to do when we get to the buster release)?

OTOH if Debian don't think there's enough value in live functionality that they are considering ditching it, then perhaps we should also consider that? I'm not really sure how many users actually use it?! My guess is that new users may use it, but personally (not counting testing) I've only used it a couple of times in my nearly 10 years of using TurnKey!

**Comment by JedMeister** [comment]
FWIW, I've done some more investigation and it would seem that that it's not the Debian live project itself which is in immediate jeopardy, but the inclusion of it in any "offical" Debian isos. Obviously if Debian stopped using it in any "official" capacity, it would get much less testing and wouldn't be ideal for us. 

However, if we include it, then we could assist in it's maintenance and testing. Especially if we start working with Debian testing a bit earlier in the release cycle (which I had hoped to do for Stretch/v15.0, but as per usual, I under anticipated the volume of work required and over anticipated how quickly we could get through it).

I think that I'll open dialog with Debian around this and see where it goes...

**Comment by vondrt4** [comment]
And I have also seen something about UEFI working in the Stretch live CD, but through something else than di-live..

**Comment by JedMeister** [comment]
Yeah, nothing other than TurnKey uses `di-live`... IMO it was quite an elegant solution, but it's showing it's age. AFAIK Debian Stretch live CD uses `live-wrapper`. I'm guessing that that doesn't explicitly provide the UEFI support itself though?! That would be something baked into `debian-installer` wouldn't it? That the live bit would just leverage?!

**Comment by JedMeister** [comment]
Deferring this to v15.0; along with the other related issues...

**Comment by JedMeister** [comment]
`di-live` has been significantly refactored for v16.0 and is now using only Debian components (rather than the hacked-on Ubuntu components we were using formerly). It's somewhat irrelevant to this thread, but it's also been ported to python3.

`di-live` still doesn't support UEFI (or "secure boot"), but hopefully these changes will allow us to support both in future (AFAIK Debian has full support for UEFI and "secure boot" in 10/Buster.

**Comment by JedMeister** [comment]
As the main thrust of this issue is essentially complete, I'm going to close this issue and open a new UEFI specific issue: #1435
