### ISSUE TITLE
Test Adminer access on new MySQL & PostgreSQL appliances

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#416]
As per https://github.com/turnkeylinux-apps/mysql/pull/2#issuecomment-124017478

Need to test/check that access to Adminer (port 12322) is available with IPTables enabled.

**Comment by DocCyblade** [comment]
Did a quick search, looks like LAMP and LAPP specify these directly in the .mk files. Will need to add this to the make files for MySQL and PostgrSQL

Need to add below to the make files 
WEBMIN_FW_TCP_INCOMING += 12322

This sound correct?

**Comment by JedMeister** [comment]
Sounds perfect! :smile:

**Comment by JedMeister** [comment]
closing
