### ISSUE TITLE
Recent Firefox (39+ or older ESR with security updates) blocks SSL access to TKL appliance websites

### ISSUE THREAD

**Issue by qrntz** [turnkeylinux/tracker#439]
As per:

https://stackoverflow.com/questions/31265573/ssl-error-weak-server-cert-key-issue-in-firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1181515
https://bugzilla.mozilla.org/show_bug.cgi?id=1182567

https://blog.mozilla.org/security/2014/09/23/phasing-out-certificates-with-sha-1-based-signature-algorithms/ is probably grounds.

Reproducible on vanilla LAMP appliance accessed over SSL.

Doesn't seem to be reported yet but FF 39 has been out for a month — since 2nd of July.

The FF team broke the status quo, but on the other hand the default TurnKey cert.pem seems to be SHA-1 with 512 bit pubkey length. We legitimately ought to do something about that I think.

**Comment by JedMeister** [comment]
+1 Agreed!

Actually community member John Carver (@Dude4Linux) is currently working on some security hardening measures. See his branch of common here: https://github.com/Dude4Linux/common/tree/security-hardening

**Comment by qrntz** [comment]
@JedMeister, good to know.

Actually, this only applies to the key in the default overlay — the one generated by **15regen-sslcert** on boot is good (SHA-256, 2048b) so not as much of an issue as it might have seemed. Still I wonder why the default one is different.

@alonswartz, OK to replace [cert.pem](https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/sslcert/etc/ssl/certs/cert.pem) with a more up-to-date version? Also, if nothing but Nginx requires splitting the .pem into .crt and .key, that's not really necessary anymore — Nginx has been handling PEMs fine for a while now.

**Comment by Dude4Linux** [comment]
@grntz, if I understood what you are saying, I think it may be due to a problem I recently discovered during testing.  During the initial 'firstboot' several services are started using a default cert.pem that was generated during the build.  Apparently the code that generates this has not been updated.  When 15regen-sslcert runs, it replaces the default cert.pem with a new,  unique key/cert pair, but it does not restart the services which continue to run until the next reboot or a manual restart. 

I think we should do two things:
1) update the code that generates the default cert.pem at build time.
2) add a new script, tkl-ssl-restart, that finds and restarts any service that uses SSL, then call this script from 15regen-sslcert.

**Comment by qrntz** [comment]
@Dude4Linux, actually, I did not know about that. I encountered the issue in question because I was testing a Web appliance with only a chroot (no init → no inithooks running automatically → all the services run with the simple default cert → FF blocks the website since the certificate is primitive). What you say makes the offense worse though — that means the services on firstboot from an actual .iso are non-conformant as well so I am in full support of your proposal.

AFAICS, the default cert.pem is not generated per se. It just gets copied from the common **turnkey.d/sslcert** overlay. It's also been a while since it was last generated — 4 years ago. So as soon as Alon confirms this will not break any assumptions, I intend to replace it with a newly-generated conformant (SHA-256, 2048b) PEM.

**Comment by JedMeister** [comment]
@qrntz & @Dude4Linux - great work guys! That sounds like a plan...

**Comment by Dude4Linux** [comment]
@qrntz, you're right, the default cert.pem is just an overlay ./overlays/turnkey.d/sslcert/etc/ssl/certs/cert.pem

I see you have forked turnkeylinux/common so you can create and submit a replacement cert.pem, but I will do the same in my security-hardening branch so I can continue testing.  Thanks for confirming my suspicions.

**Comment by Dude4Linux** [comment]
I generated a new 2048 bit, SHA256 cert.pem and pushed it to the security-hardening branch.  I made a few changes.
1. Set CN=TurnKey ; a blank CN is no longer accepted.
2. Set CA=False ; I don't think it should have been true.
3. Set Extended Key Usage=TLS Web Server Authentication, TLS Web Client Authentication

```
# openssl x509 -noout -text -in ./overlays/turnkey.d/sslcert/etc/ssl/certs/cert.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 16704488550168457226 (0xe7d243d50b5ef00a)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=TurnKey GNU/Linux, OU=Software appliances, CN=TurnKey
        Validity
            Not Before: Aug  3 15:12:55 2015 GMT
            Not After : Jul 31 15:12:55 2025 GMT
        Subject: O=TurnKey GNU/Linux, OU=Software appliances, CN=TurnKey
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b6:e0:f4:df:c9:93:6a:9d:cf:60:a6:c8:40:a7:
                    f0:66:48:c9:74:ff:9f:b5:4f:49:4d:52:03:16:4a:
                    61:d3:d5:c3:fe:76:46:61:6a:f5:8f:12:97:7e:88:
                    c2:aa:70:b2:fd:fb:d6:e5:f2:8a:a9:4d:84:c3:f1:
                    93:3b:16:46:ab:a3:52:43:0f:d2:69:7d:28:88:8c:
                    00:e3:f9:95:ed:b6:8c:d4:14:28:bd:08:ea:d4:a2:
                    2b:4f:15:25:95:e4:97:76:50:9e:ff:e6:fe:4d:c6:
                    1c:62:c9:56:17:f8:62:82:74:61:b6:92:1a:72:fa:
                    b4:53:7a:ed:27:65:88:f7:d1:0b:19:f6:d7:f0:bc:
                    d3:90:93:63:fe:ab:50:3b:5a:69:36:ee:84:2f:a8:
                    1d:5b:d5:c2:60:3c:1b:85:ad:a2:c1:cd:f2:00:7f:
                    b1:b1:69:8e:22:5f:65:f5:30:71:0d:41:b1:a9:f2:
                    52:cd:d2:1c:9d:2d:ab:e7:dc:c5:f8:8c:dc:bd:f2:
                    2f:57:0d:eb:5c:fd:2e:70:52:f0:43:b9:b4:f9:54:
                    3d:09:e8:92:de:08:a8:a8:d4:89:fd:fb:11:2d:9b:
                    8d:ea:6b:e4:de:15:73:83:d0:05:25:07:b6:1a:67:
                    b6:34:4c:ed:b4:dc:8c:22:89:7b:c1:b8:d1:a4:f4:
                    38:a5
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
    Signature Algorithm: sha256WithRSAEncryption
         56:1f:36:3b:ff:18:f8:2a:5f:68:42:4b:7b:8a:6d:f9:0f:dd:
         75:ab:20:73:3a:28:08:e8:48:44:2d:7e:8b:86:e5:7d:e0:dc:
         d8:4a:29:f7:1c:a7:93:62:a8:a9:9f:0e:9f:9b:b8:31:c0:58:
         41:bc:d2:12:e1:d2:82:6a:86:d0:db:84:05:db:b2:0e:82:e8:
         1e:2d:ee:ab:32:62:90:4b:df:a0:df:15:5a:76:ee:ae:a9:62:
         95:1c:3e:c8:f7:cd:bd:2b:2d:aa:c8:22:82:05:48:0a:5f:aa:
         55:71:57:15:e7:8c:1d:c9:ee:a0:e3:8b:54:7b:7b:59:4b:db:
         ac:7c:ff:15:ee:6b:51:be:a4:ab:55:2a:75:9d:42:f1:94:ce:
         29:64:cc:82:43:f6:c0:d4:66:7e:1e:7f:49:ce:7f:35:8c:9c:
         7d:d2:09:0a:c7:70:d2:18:2d:9d:b1:df:42:a8:7c:06:4b:49:
         7a:4d:1a:29:70:fd:04:a0:6c:fa:e8:48:c7:b2:0a:7b:86:47:
         64:04:d2:1d:23:a4:87:80:70:57:10:48:39:60:3c:0b:f7:39:
         7d:84:cd:67:d8:b0:16:fb:51:6b:f9:d7:69:92:3d:cf:7d:8d:
         4b:7a:e8:ef:08:9d:49:6b:9f:63:5d:2a:f6:48:c1:15:88:06:
         b0:58:55:e1

**Comment by Dude4Linux** [comment]
@qrntz, I haven't had a chance to test this with Firefox 39, so please let me know if this new cert/key pair works in your app.

**Comment by qrntz** [comment]
@Dude4Linux, it does, thanks.
I guess it would make sense if we just took your .pem for inclusion into common.

**Comment by qrntz** [comment]
No longer applicable.
