### ISSUE TITLE
[limesurvey] Error during build

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#446]
Error trying to build during SSL hardening. Not sure if it's related the SSL stuff, looks like maybe upstream issue? Reporting anyway for followup.

Testing Tracking here (https://github.com/turnkeylinux/common/pull/42#issuecomment-132284465)

#### Error Below
```
# apply the common removelists
fab-apply-removelist /turnkey/fab/common/removelists/mysql build/root.patched;  
warning: entry does not exist: var/lib/mysql/ib_logfile*
fab-apply-removelist /turnkey/fab/common/removelists/turnkey build/root.patched; 
warning: entry does not exist: etc/apt/trusted.gpg~
warning: entry does not exist: etc/apt/trusted.gpg.d/debian.gpg~
warning: entry does not exist: etc/apt/trusted.gpg.d/turnkey.gpg~
# apply the product-local root overlay
if [ -d overlay ]; then fab-apply-overlay overlay build/root.patched; fi
# run the product-local configuration scripts
$(call run-conf-scripts, conf.d)
fab-chroot build/root.patched --script conf.d/downloads
+ VERSION=206plus-build150729
+ URL=http://download.limesurvey.org/latest-stable-release/limesurvey206plus-build150729.tar.gz
+ dl http://download.limesurvey.org/latest-stable-release/limesurvey206plus-build150729.tar.gz /usr/local/src
+ '[' http://127.0.0.1:8124 ']'
+ PROXY='--proxy http://127.0.0.1:8124'
+ cd /usr/local/src
+ curl -L -f -o limesurvey-205.tar.gz --proxy http://127.0.0.1:8124 http://download.limesurvey.org/latest-stable-release/limesurvey206plus-build150729.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 500 Internal Server Error
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 22
```

**Comment by DocCyblade** [comment]
I tried again, and it failed again. I tried the link with wget and it failed too. I went to the website and the link is 

https://www.limesurvey.org/en/stable-release?download=1329:limesurvey206plus-build150812targz
this will resolve and redirect to 
http://download.limesurvey.org/latest-stable-release/limesurvey206plus-build150812.tar.gz

I will change this and re-test. If it works I will create a PR off of your SSL branch

**Comment by DocCyblade** [comment]
Just did a successful build. I'll submit a PR once SSL testing is done.

**Comment by DocCyblade** [comment]
PR submitted to @JedMeister repo.

**Comment by JedMeister** [comment]
Great thanks! :smile:

**Comment by DocCyblade** [comment]
This can be closed as long as it is merged back to the main repo

**Comment by DocCyblade** [comment]
@JedMeister You can close this if you want. It does build with the PR and the SSL changes. If you want to wait until your branch is merged that would be good

**Comment by JedMeister** [comment]
Cheers @DocCyblade but I'll leave it open until it's merged back into the main TKL repo.
