### ISSUE TITLE
[symfony] Feature request - Upgrade to LTS 2.7

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#447]
LTS 2.3 has been replaced with 2.7, would be nice to upgrade to this. Assign this @DocCyblade as I use sf a lot in side projects. I'll see if we can't sneak this into v14 or at least v14.1

**Comment by JedMeister** [comment]
Assuming that it all just works with 2.7 then lets do it...

**Comment by DocCyblade** [comment]
Looks like a single line change will install 2.7, however there have been a lot of changes to sf since 2.3. 

The default twig page has changed directories, causing this issue (https://github.com/turnkeylinux/tracker/issues/445). Also the page content has changed, so I am updating the conf script to update the new page. Should have a PR be the end of the weekend.

**Comment by DocCyblade** [comment]
Work is going along well. I have updated the conf file, I manually merged @JedMeister SSL branch just for testing. When ready for PR I will remove his, and note that it depends on his SSL, or however he would like to do it.

@JedMeister if this does work, how should I PR this? Should I PR off of your SSL branch or your master branch and you can do the finally PR to the TKL repo? I am keeping all of my final changes so it would not be an issue to fork your repo and submit a PR from yours, since I kind of need to test off of your SSL branch. It was you SSL branch testing that found this build issue with 2.3. Just let me know

**Comment by JedMeister** [comment]
Thanks @DocCyblade! Have I mentioned that you are a :star: :+1:

**Comment by JedMeister** [comment]
Oops. Sry was replying while you were obviously writing...

It may be easiest to PR against my ["ssl-hardening"](https://github.com/JedMeister/symfony/tree/ssl-hardening) branch; Even though obviously it's more than that...

**Comment by DocCyblade** [comment]
I did a quick build and ISO test and things are looking good! I had to do some manual tweaking, but once I get the sed editing of the app_dev we should be golden.


<img width="1188" alt="screen shot 2015-08-21 at 10 34 22 pm" src="https://cloud.githubusercontent.com/assets/9731860/9422123/0d0cb502-4855-11e5-9fe7-369bc4535dcc.png">

**Comment by JedMeister** [comment]
Awesome :smile:

**Comment by DocCyblade** [comment]
Sounds good, I'll fork your repo and issue a PR when things look good.

**Comment by DocCyblade** [comment]
I am super excited for this, as I have been wanting to build on the new LTS, and TKL will make it much easier. Time for some :beers: huh?

**Comment by JedMeister** [comment]
Cool! Yeah :beers: all round I reckon! :smile:

**Comment by DocCyblade** [comment]
So after doing some reading for 2.7, it seems the conf script was written for 2.0. A lot has change since then, now at 2.7. 

I purpose we follow sf best practice for configuration found here:
https://symfony.com/doc/current/best_practices/configuration.html

It says to store config files in three locations
- 1. Define the **infrastructure-related** configuration options in the **app/config/parameters.yml** file.
- 2. Define all your **application's parameters** in the **app/config/parameters.yml.dist** file.
- 3. Define the **application behavior** related configuration options in the **app/config/config.yml** file.

We would only be worried about **app/config/parameters.yml**

I am going to move forward with this with the 2.7 LTS upgrade

-------
Optional:

It also suggested to move the database creds outside of symfony altogether. See below link:
https://symfony.com/doc/current/cookbook/configuration/external_parameters.html 

According to the write up it reads any environment variables tagged with a prefix of SYMFONY__ in to the server variables. I think that any environment variables made by SetEnv via apache is only accessible to the process that it is running under. Did a quick test and this seems to be the case. However, since these are passed to all scripts, an attacker could craft a phpinfo page and glean the info. I guess if they get access to make a page they could access the app/config/parameters.yml anyway. So maybe not a concern? This can be done pretty easy by moving the database user and password and secret to the apache config. But I see this an optional. I would like to hear anyone else thoughts however.

**Comment by DocCyblade** [comment]
I have pushed my changes to https://github.com/DocCyblade/symfony

This is forked from @JedMeister fork, since he was working on the SSL hardening and I wanted to include that, it is branched off of his SSL branch. 

I also updated the changelog and README files as some of the links and instructions were out dated. @JedMeister already has the change log updated, I just benched off of that so he can pull them in, then submit a PR to the official repo.

I am going to do some in depth testing (build a small application) to make sure it's working all the way. 

Something to think about, since the demo app is no longer part of a new install, do we want to include a "demo site" built in by another apache config?  I think it stands on it's own. we could have it off of /sf-demo/ or something like that. That way it can be disabled using a2 command. Thoughts about this?

It should take a few more days of testing, to get it right, or we could update this in v14.1

Thoughts?

**Comment by DocCyblade** [comment]
In regards to the demo site, I was able to quickly add that using another apache site so it can be disabled quickly, and updated the default welcome screen on how to disable the demo site. I also put a link on the welcome page to the demo site. Doing final testing now

**Comment by DocCyblade** [comment]
Well testing went south, not sure what is going on. Had everything working, went to do a final build and the demo site is failing. I think it may be a sf demo problem. If I can't get it fixed tonight, I will nix the demo site and button up v2.7 LTS upgrade only

**Comment by JedMeister** [comment]
Sorry for radio silence. Sounds like you've done a great job so far.

**Comment by DocCyblade** [comment]
Ok, so one more day of vacation and I want to get this knocked out. So after some testing, I figured an easy way to have the demo site... on a different port. Since sf built in php server uses port 8000 I chose this to run in apache. I am doing the config now, and hope to test the builds tonight

**Comment by DocCyblade** [comment]
Doing another build/test, hopefully I have this sorted out!

**Comment by DocCyblade** [comment]
Not doing to well. I removed the demo code, and some times it works and some times it does not. Going to start from the top. Each time testing three times to ensure it was not a fluke. It must pass all three times. 

I also broke down the editing of the app_dev.php and .htaccess files to make sure my sed commands are doing what I expect them to do without messing with other things. Current code re-creates the two files, where I am instead going to edit the stock files as there is good documentation in those files. 

1. Base install of symphony with no customizations
2. Base install and security modifications
3. Steps 1 and 2, and app_dev.php modifications
4. Steps 1 - 3, and htaccess modifications
5. Steps 1 - 4 and twig modifications
6. Steps 1 - 5 and base demo app
7. Steps 1 - 6 and demo app app_dev.php modifications
8. Steps 1 - 7 and demo app htaccess modifications
9. Steps 1 - 8 and demo app twig modifications
10 - Retest will all in place.

**Comment by DocCyblade** [comment]
FYIW, I uploaded my scripts that I am using to test each part, mostly for my learning of SED in my "sandbox" a git repo that I'll use to keep such script for the enlistment of all :-) 

https://github.com/DocCyblade/sandbox/tree/tkl-symfony-testing

**Comment by DocCyblade** [comment]
Testing seems to be going well doing test 10 now..

**Comment by DocCyblade** [comment]
Ok, again it's not working. I am going to cut my losses a bit but still keep the Demo app. Here is how

I will just install the demo app, and add a reference on how to start the PHP built in server to use it.

**Comment by DocCyblade** [comment]
Submitted PR https://github.com/JedMeister/symfony/pull/1

This should complete this once @JedMeister branch is merged

**Comment by JedMeister** [comment]
https://github.com/turnkeylinux-apps/symfony/commit/80f7346e4fd67d65114f4be4a57d5534e7fde739
