### ISSUE TITLE
SSL changes blocking IExplorer from accessing builds (new Build Today)

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#448]
Prior Builds in Internet Explorer I can access the site by "accepting" the websites security certificate.

However, just did a build today that is not allowing such.  I know there are changes as I had to add my email for security updates.

I can certainly go get a CERT but i simply need to see if things are working and need FileManager to check things.

Thoughts?
(working now on Odoo, which was showing some promise just now)

**Comment by l-arnold** [comment]
Looks like Microsoft did upgrade me to V. 11 Internet Explorer.  However, same browser session is letting me accept the old SSL versions.

**Comment by l-arnold** [comment]
Also, it appears that Webshell is not loading in Chrome either (Chrome is loading Webmin however).  Same site that IE is not loading anything (new build).

**Comment by DocCyblade** [comment]
Is this because the cert is self signed? We have had this issue at work with IE 11, it just won't even allow you to accept the self signed cert, firefox would do the same thing. Forgive me for being ignorant, does webmin and webshell use the same cert?

**Comment by DocCyblade** [comment]
@l-arnold are you testing in a CHROOT or full ISO VM install? I noticed that inside a CHROOT I had the same issue, I had to run the turnkey-init.

**Comment by l-arnold** [comment]
This is a ISO VM install.  I just rebooted the server and IE can now get in (and thus I can get to FileManager).  However, Webshell is still not loading (though it did ask me to "proceed" a moment ago).

**Comment by l-arnold** [comment]
Fix that.  Added https: to Webshell and it came up.  Not sure why it was not there.  More testing to follow.

**Comment by DocCyblade** [comment]
FYI, I ran the testssl script on a bunch of apps. Your PR has all the details. I did not do any other testing but run the script three times, 1 in CHROOT, 2 in CHROOT after running turnkey-init, 3 after ISO install. All the files have been captured and in a github repo

**Comment by l-arnold** [comment]
"Captured and in a Repo".  I will research the PR side of tthings.  Does that mean everything loaded for you?  Seems after my reboot things have been moving.  I am back to my password setup quest.  

I have not had the "IE" or "WebShell" issues for a bit now.  I will close this for now.

**Comment by l-arnold** [comment]
Seems we are moving forward
