### ISSUE TITLE
[FileServer] Enhancement Request: Unified User System

### ISSUE THREAD

**Issue by tomck** [turnkeylinux/tracker#449]
While AjaXplorer supports logging in with Samba accounts, there is a bit of difficulty in creating Samba accounts (it can't be done from AjaXplorer). In Webmin, it seems it is possible to create users, then convert them to Samba accounts, but for ease of use it seems more logical to have some sort of unified system.
##

**Comment by JedMeister** [comment]
The fileserver appliance is pre-configured so if you create a new Linux user (either via commandline or Webmin) then they automatically become a Samba user. As you know Samba users can log in to Ajaxplorer.

Whilst I can see how it might be nice to have it "All-in-one" type config; in my mind the separation between administration and users is a good thing. 

**Upcoming v14.0 File Server appliance**
Ajaxplorer has become Pydio and whilst it's great software, we had difficulties automating it's installation. So we have taken a slightly different approach for the v14.0 fileserver appliance. We have added WebDAV as an access protocol and are using a much more simple WebUI called SambaDAV. It provides a simple access point only. SambaDAV uses Samba/Linux users only and has no administration component. Whilst it doesn't fulfil your request; it does remove all ambiguity.

Perhaps we just need to document the creation of users better?
