### ISSUE TITLE
Add hostname as an advanced network setting in confconsole

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#450]
Something I have been longing for for some time. Add option (maybe even the host name showing) to update the system hostname from the console. Most people may leave it, but it would be nice to give a easy way to set it in the console? Maybe even an init-hook? 

Not at the top of the todo list but thought I would throw that out there see what others thing and the core devs.

Not sure what the confconsole is written in my gut tells me python but to be honest I have not yet looked.
##

**Comment by DocCyblade** [comment]
Just, did a quick search for confconsole and found it is python. Maybe I'll fork the repo and give a go at it. I need to learn another language! Or maybe I should leave it to the professionals!

**Comment by JedMeister** [comment]
Yep python.

AFAIK if you write the code then you should be able to run it as a confconsole module and/or as an inithook. My sense is that there may be value in "advanced" inithooks also being available as confconsole options too!? Not sure on that... 

Actually I need to talk with Alon about what/how these "advanced" inithooks will work...

**Comment by DocCyblade** [comment]
Conf console module eh? This sounds like a class. I don't know Python but I do know a lot of other languages, most are all the same when you get down to it. I'll have to check out the GIT repo and read the code. I do that before bed, helps me sleep! Hah!

If I do attempt anything I'll be sure to post here.

**Comment by JedMeister** [comment]
Sorry probably wrong terminology... IDK python much at all but my son does and he explained some stuff to me...! :smile:

**Comment by JedMeister** [comment]
I'm moving this to v14.2 milestone as I doubt we'll have time/energy to get this done in a timely manner...

**Comment by Dude4Linux** [comment]
There is another open issue for confconsole.  https://github.com/turnkeylinux/tracker/issues/148
I also noticed that it can't manage the network configuration for the lxc appliance.  It would be nice to be able to select static addressing for lxc.

**Comment by JedMeister** [comment]
I have discussed this with Alon and essentially confconsole needs a rewrite. 

As part of that the idea would be to support some sort of "plugin" type system so additional "advanced" options could be really easily developed and added.

It'd also be nice to separate the backend and the UI (so we could even have a web UI for it if we wanted).

**Comment by JedMeister** [comment]
As per https://github.com/turnkeylinux/tracker/issues/369#issuecomment-261474743 I am assigning @DocCyblade as lead battle tester! ￼:smile:

**Comment by DocCyblade** [comment]
Did not realize, I opened this request :-) will be fun to test the feature I requested and see it through to production.

**Comment by DocCyblade** [comment]
As this is part of the confconsole re-write testing, a plug in was created within the new confconole that will do this. Thats what I'll be testing :-)

**Comment by DocCyblade** [comment]
Testing the confconsole version below this works as I asked for. This feature works as asked above. 


```
root@lamp ~# apt-cache policy confconsole
confconsole:
  Installed: 0.9.4+97+gc9897a4
  Candidate: 0.9.4+97+gc9897a4
  Version table:
 *** 0.9.4+97+gc9897a4 0
        900 http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.4+54+g99603c7 0
        850 http://archive.turnkeylinux.org/debian/ jessie/main amd64 Packages
```

**Comment by JedMeister** [comment]
Closing as per above comment from Ken.
