### ISSUE TITLE
Drupal8 'Trusted Host Settings' Warning

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#451]
Just found in testing Drupal8 complains about Trusted Host Settings on config page.

Warning is:

The trusted_host_patterns setting is not configured in settings.php. This can lead to security vulnerabilities. It is **highly recommended** that you configure this. See [Protecting against HTTP HOST Header attacks](https://www.drupal.org/node/1992030) for more information.

**Comment by JedMeister** [comment]
Good find! :+1: Thanks for reporting!

IMO it's not quite a bug; but it's more than a feature request... Regardless I'll label it as a "feature" for now... 

From a (very) brief read it seems like we might want to set the appliance domain in the drupal settings. However as this appliance currently includes beta software (drupal8) lets just leave it for now and I'll target this for v14.1.
