### ISSUE TITLE
Magento Latest Build

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#452]
I just went to the Magento Site.

Latest build they are putting out is
ver 1.9.2.1 - Added Aug 4, 2015  

the Pull version for Current Magento on Turkleylinux-apps is, I believe, 1.9.1.1

Might be worth the update.

**Comment by JedMeister** [comment]
Thanks for the heads up... To do this now will require that the app code be updated and the appliance retested... I'll see what I can do, but no promises...

**Comment by JedMeister** [comment]
Although v14.0 build code initially downloads v1.9.1 (see [here](https://github.com/turnkeylinux-apps/magento/blob/master/conf.d/downloads#L8)) it later uses `mage` (Magento commandline tool) to update to the latest version (see [here](https://github.com/turnkeylinux-apps/magento/blob/master/conf.d/main#L78-L82)). So v14.0 will have Magento v1.9.2.1
