### ISSUE TITLE
[Bugzilla] Doesn't send emails OOTB

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#454]
Bugzilla does not seems to be able to send emails out of the box due to config issues. Can be worked around by editing the entry "mailfrom" in /var/www/bugzilla/data/params.json and setting it too a **valid** email address (doesn't have to be real, just valid form). @JedMeister

**Comment by JedMeister** [comment]
Thanks.for that. Oversight on my behalf that this didn't get checked sooner and v14.0 code already include a fix...

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/bugzilla/pull/6
