### ISSUE TITLE
Check "Reboot" command in Jessie Lapp etc.

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#456]
Twice today I have had Reboot commands not power cycle.

Once from ConfConsole
Once from WebShell (reboot)

Did just get a Reboot from ConfConsole on retry.
Not sure if an issue w/ VMWARE or something else.  Has been ongoing inconsistent behaviour in Jessie.  Last week was not getting the "confirm" dialog floating up at Install Reboot.  It did start floating up this week again however after updating CORE in TKLDEV.

**Comment by JedMeister** [comment]
2 fixes to di-live have been issued in the last couple of weeks so install reboots should now be working consistently with new builds (it does for me at least).

Although I'm not sure about `reboot` not working from ConfConsole or Webshell (TBH I almost never use Webmin are only rarely use confconsole). What about commandline? Any inconsistencies there?

**Comment by l-arnold** [comment]
Yes.  It was Webshell (not webmin) that reboot did not work on (so command line)

Just tried again (system much more fresh) and it did reboot on commandline (webshell)

**Comment by l-arnold** [comment]
I think the main issue is whether Systems Reboot Properly in "Cloud" envirionments where admin's don't have a "reset" command when all else fails.  My VMWare does have that and seems to proceed as planned.

**Comment by l-arnold** [comment]
"Target Shutdown Reached"  after ConfConsole Shutdown console.
Never shut off.
On Odoo/Restored via TKLBAM system.
I did have some sessions (like Adminer) open when command was isued and seemed to "pause" for a while, but eventually passed Postgres and Apache shutdowns.  

Didn't seem the final "get past" was coming any time soon when I powered off.

**Comment by l-arnold** [comment]
This started yesterday "after" a TKLBAM Restore cycle in shell.  
In shell TKLBAM said "complete.  You might want to reboot now".

I typed Reboot, and it hung as described.

Doing a new test now.  Cycle complete.  Instead of "shell"  "reboot" command went to
ConfConsole, chose "Advanced/Reboot"
Rebooted  and it did Power Cycle

That is a good thing.  Will need to test the Shell one again.

**Comment by JedMeister** [comment]
I'm closing this for now; please reopen if need be.
