### ISSUE TITLE
Manual partitioning is broken

### ISSUE THREAD

**Issue by AllanDaemon** [turnkeylinux/tracker#459]
When trying to install from ISO image, if you choose `Manual` in partitioning (instead of Guided), you go to the menu show in the picture above. The first bug is that the format string is shown directly. This is ok though, as you can read all you need. But when you select a existing partition, instead of going to the submenu to edit the partition, it stays in the same screen to choose partition. For creating a new partition table or a new partition it works as expected. I guess the presentation error of format string may be related with this.

I found out it in a third party application built with Turnkey Core (MineOS). I tried with the Turnkey core ISO as well, first in a bare metal machine, as also in Virtualbox,  all them with the same problem.

![turnkey debian install error](https://cloud.githubusercontent.com/assets/607994/9861072/93df9838-5b06-11e5-96b0-cb5e3aa5c541.png)
![turnkey version](https://cloud.githubusercontent.com/assets/607994/9861075/9b99582a-5b06-11e5-9c10-7272540f22a8.png)

**Comment by JedMeister** [comment]
Hi, 
Thanks very much for taking the time to lodge this bug report. This is a known issue and has been fixed for the v14.0 release (very close to release). As the fix has already been committed I will close this issue. Please feel free to reopen it and/or post a new issue if you come across similar behaviour in v14.0. :+1:
