### ISSUE TITLE
Node.js install script in common is broken

### ISSUE THREAD

**Issue by Olliebrown** [turnkeylinux/tracker#461]
It looks like the 'dist' folder over at the node.js server must have changed.  The nodejs-install script in common fails saying it cannot find SHASUMS.txt.  After some investigations I found that the folder 'latest' now contains node.js v4 instead of the previous 0.1x versions that the script was expecting.

All that needs to happen is the URL needs to be updated to point to 'latest-v0.12.x' or 'latest-v0.10.x' depending on which one you guys are expecting (I assume it's the .12 version).  An [image of the] diff patch is attached allthough it's kind of overkill!  Just two little lines need to change and then it's happy again!

![nodejs-install](https://cloud.githubusercontent.com/assets/6719670/9936474/cf17a8c4-5d21-11e5-9270-e292664c3c3a.png)

**Comment by JedMeister** [comment]
Thanks for reporting. :+1: 
We only just finished building appliances for our [v14.0 release](http://www.turnkeylinux.org/blog/turnkey-14-0-release) so it only must have just changed! :smile:

**Comment by JedMeister** [comment]
Closing this in favour of #477
