### ISSUE TITLE
Spelling "TYPO3 CMS" instead of "Typo3"

### ISSUE THREAD

**Issue by sgrossberndt** [turnkeylinux/tracker#463]
Hi there,

http://www.turnkeylinux.org/updates/typo3 uses wrong spelling for the TYPO3 brand:

It should be at least "TYPO3" instead of "Typo3", even better would be "TYPO3 CMS"

https://typo3.org/about/the-brand/style-guide/the-typo3-spelling/

Thanks,
Stephan

**Comment by JedMeister** [comment]
Thanks for the correction. :+1: We'll fix that for you next release!
