### ISSUE TITLE
Upgrade TYPO3 CMS from 7.3.1 to current version

### ISSUE THREAD

**Issue by sgrossberndt** [turnkeylinux/tracker#464]
Hi there,

http://www.turnkeylinux.org/updates/typo3/new-turnkey-typo3-version-140

lists "Upgraded to latest major version of Typo3 (7.3.1)." with a release date of "Tue, 2015/09/15 - 17:00".

On 2015-08-04 TYPO3 CMS 7.4 was released which succeeded 7.3.1
On 2015-09-29 TYPO3 CMS 7.5 will be released succeeding 7.4

http://typo3.org/download/

Thanks,
Stephan

**Comment by JedMeister** [comment]
Hi Stephan,

THanks for taking the time to post.

The appliance release date and the date when the build code were updated are not always the same (in fact they're rarely the same...) Considering that the v14.0 update took us about 5 months, unfortunately some appliances are not going to have the very latest code. FWIW the changelog was signed off on [9th July](https://github.com/turnkeylinux-apps/typo3/blob/master/changelog)

If you'd like to assist in keeping the appliance build code up to date (better than we currently have the resources for) then that would be awesome! You can find it here: https://github.com/turnkeylinux-apps/typo3 If you need a hand setting up [TKLDev](https://www.turnkeylinux.org/tkldev) (our dev/build environment) then let me know and I'll help you out. :smile:

**Comment by JedMeister** [comment]
@sgrossberndt - I notice that TYPO3 is now up to 7.6.1.

It'd be nice to update this for the upcoming v14.1 release but IIRC Stefan had a really quick look at it and it didn't successfully build. I'm guessing that was because the web installer screens have changed a bit (so we can't just automatically recycle the [twill code](https://github.com/turnkeylinux-apps/typo3/blob/master/conf.d/main#L56-L71) that we use for the final part of the install).

Is it possible to install TYPO3 completely via commandline? I.e. like you can install drupal via drush? I had a poke around on the TYPO3 website but couldn't see any mention of anything like that. I also asked on the TYPO3 IRC but I haven't had any response there yet... 

I did come across what appears to be a third party [TYPO3 commandline tool](https://github.com/helhum/typo3_console) which looks promising but not sure if it's what we're after. Out of interest do you know anything about it and/or recommend it (or not)?

If there is a commandline tool/installer then that'd make maintenance of the TYPO3 appliance super easy! :smile:

**Comment by sgrossberndt** [comment]
Hi Jeremy,

indeed there is no official console installer for TYPO3 yet but since 
@helhum providing the typo3_console Extension you mentioned is a core 
member its fine to use it.

IRC is more or less dead, but you're very welcome to join us on Slack: 
https://forger.typo3.org/slack and ask in #typo3-cms or #typo3-composer

I did not use typo3_console yet, but maybe this will help you:

====

https://docs.typo3.org/typo3cms/extensions/typo3_console/Introduction/Index.html

# Non interactive automatic setup of a new TYPO3 instance
./typo3cms install:setup --non-interactive \
         --database-user-name="root" \
         --database-host-name="localhost" \
         --database-port="3306" \
         --database-name="travis_test" \
         --admin-user-name="admin" \
         --admin-password="password" \
         --site-name="Travis Install"

# Populate essential core caches
./typo3cms cache:warmup

# Perform safe database schema updates
./typo3cms database:updateschema "*.add,*.change"

====

Using composer:

1) create a composer file which requires the typo3-base distribution 
typo3_console
2) composer install (to download all the files)
3) create a symlink for typo3_console
4) run typo3_console to create an new database

====

https://gist.github.com/sorenmalling/82769c3dfe838740ff93

====

Regards,
Stephan


Am 17.12.2015 um 08:45 schrieb Jeremy Davis:
> @sgrossberndt <https://github.com/sgrossberndt> - I notice that TYPO3 is
> now up to 7.6.1.
>
> It'd be nice to update this for the upcoming v14.1 release but IIRC
> Stefan had a really quick look at it and it didn't successfully build.
> I'm guessing that was because the web installer screens have changed a
> bit (so we can't just automatically recycle the twill code
> <https://github.com/turnkeylinux-apps/typo3/blob/master/conf.d/main#L56-L71>
> that we use for the final part of the install).
>
> Is it possible to install TYPO3 completely via commandline? I.e. like
> you can install drupal via drush? I had a poke around on the TYPO3
> website but couldn't see any mention of anything like that. I also asked
> on the TYPO3 IRC but I haven't had any response there yet...
>
> I did come across what appears to be a third party TYPO3 commandline
> tool <https://github.com/helhum/typo3_console> which looks promising but
> not sure if it's what we're after. Out of interest do you know anything
> about it and/or recommend it (or not)?
>
> If there is a commandline tool/installer then that'd make maintenance of
> the TYPO3 appliance super easy! :smile:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnkeylinux/tracker/issues/464#issuecomment-165374708>.
>

-- 
side by site GmbH & Co. KG
Geo & Web

Barbarastraße 3-9 (Block 6)
50735 Köln

fon: +49 221 27909-68
fax: +49 221 27909-65
email: s.grossberndt@sidebysite.de
http://www.sidebysite.de

GK2:
2568335.13239 rw / 5648797.09828 hw

WGS84:
50.9703360368 br / 6.97225749493 la

HR A 15202
Amtsgericht Köln

persönlich haftende Gesellschafterin:
side by site Verwaltungs GmbH
Amtsgericht Köln HR B 33600
Geschäftsführer: Michael Schlieper

**Comment by JedMeister** [comment]
Awesome! You rock!

**Comment by qrntz** [comment]
I had no luck with typo3_console last when I was updating this, hence twill.

However, it's likely better now. I will take a look.

**Comment by sgrossberndt** [comment]
You're very welcome to join us on Slack: https://forger.typo3.org/slack and ask in channels #typo3-cms or #typo3-composer

**Comment by JedMeister** [comment]
@qrntz has reported ongoing issues getting the "introduction package" to activate as it should. He mentioned that he has heard (on the slack channel) that the package is corrupted!? 

Anyway this has sucked up a fair bit of time and energy with little result. At this point we'll need to postpone this until v14.2 now... :disappointed:

**Comment by helhum** [comment]
@JedMeister @qrntz What exactly is not working? Which package has been reported to be corrupted?

**Comment by JedMeister** [comment]
@helhum - Thanks for dropping in. Best if you speak with @qrntz directly but he's away at the moment. I'm not sure of exact date when he returns but at least another week AFAIK.

**Comment by helhum** [comment]
@qrntz Please ping me once you are available again

**Comment by qrntz** [comment]
@helhum, hi! Thank you for your assistance.

The «introduction» package has given me a lot of trouble. I have found no way to install it in an automated fashion without some kind of error surfacing or it silently refusing to work.

One of the errors (when trying to install manually, via extExtract.php/cli_dispatch) reads

    No file found for given UID:384

and corrupts the reference index. Fixing it does not lead anywhere. On the Slack channel it [was](https://typo3.slack.com/archives/typo3-cms/p1451480822001148) suggested that the package does not behave properly.

Upon trying to install the extension with Composer, ```./typo3cms install:generatepackagestates``` terminates without output, however there are no pages on the rootlevel and no templates. Moreover, none of the required system extensions are activated by default (css_styled_content, bootstrap, realurl, introduction). After adding them to ```active-packages``` in composer.json, the admin panel artwork suggests that the «bootstrap» package is installed and activated, but not «introduction».

I am quite puzzled on how to proceed… I think I must have tried every possible way of installing it by now.

**Comment by helhum** [comment]
@qrntz: not that complicated

try this: https://gist.github.com/helhum/b96ad43bb382825eb446

It works on my machine :)

**Comment by qrntz** [comment]
@helhum, that works. Many thanks.

1) What does updating schemas actually do? I haven't seen it used before.
2) When should ```install:generatepackagestates``` be used?

**Comment by helhum** [comment]
>  What does updating schemas actually do?

This is only needed, because my typo3 console extension currently has a bug which leads to the situation that some database tables are missing.

This call compares the actual available database tables with the expected ones from configuration and creates the missing tables. If the bug is fixed at some point this call would be a noop.

> When should `install:generatepackagestates` be used

Never! This is an experimental feature useful in deployment scenarios

**Comment by JedMeister** [comment]
@helhum - Thanks heaps for your input :+1: 

@qrntz - looks like this should be fairly straight forward now. Assuming that you can get this implemented and tested by first thing next week we can still squeeze this into v14.1. Retargetting for now so please keep me posted if that's not possible.
