### ISSUE TITLE
deck --isdirty not working as it should

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#473]
deck --isdirty» is not working as it produces a zero status code regardless of whether the deck is dirty or not

**Comment by qrntz** [comment]
@JedMeister, I'll take a look at this.

**Comment by qrntz** [comment]
I've taken a look at this. It doesn't do that anymore. At least not under controlled conditions. And I can't tell why it did.

I suspect this was caused either by some error on my side or general AuFS instability that is normally resolved with a reboot.

**Comment by JedMeister** [comment]
Let's close for now and reopen if/when we need to.
