### ISSUE TITLE
New appliance: FormaVid: Small Business Appliance

### ISSUE THREAD

**Issue by bormanst** [turnkeylinux/tracker#478]
Thank you for your consideration.

Repo: https://github.com/bormanst/formavid
Whiteboard: https://github.com/turnkeylinux/tracker/wiki/FormaVid
Additional Info: http://formavid.org

This is a tkldev v14 (rc3) build. Thanks and kudos to all involved in developing v14, especially with respect to releasing rc3 so quickly after rc2.
##

**Comment by bormanst** [comment]
Added some convenience links (from Candidates wiki):

Repo: https://github.com/bormanst/formavid
Whiteboard: https://github.com/turnkeylinux/tracker/wiki/FormaVid
Additional Info: http://formavid.org

**Comment by bormanst** [comment]
Also of note:

This is a tkldev v14 (rc3) build. Thanks and kudos to all involved in developing v14, especially with respect to releasing rc3 so quickly after rc2.

**Comment by JedMeister** [comment]
Thanks for submitting your appliance code. I'm still finalising the v14.0 release. We have already built (and published) all of the ISOs (with one special case exception) and we just need to finish up the optimised builds (e.g. virtual machine images, etc).

Once all that is complete then I will be in a better position to look over your code properly and we can go from there.

To be clear this won't be included in the current release. It will be in v14.1 at the earliest (no release timetable at this point but I would anticipate 6mths +/-).

**Comment by bormanst** [comment]
Awesome, I look forward to helping make this a viable appliance for your site. I've been using a hacked/hardwired 32 bit version of it since tkldev v12. I was in the process of doing a 64 bit build when I saw v14 being developed so I decided to put in the extra effort to comply with the TurnkeyLinux submission requirements in case you guys deemed it something of value as well. I've greatly appreciated and benefited from all your hard work so I consider it quite an honor to possibly give something back.  The timetable mentioned is not an issue as it's easy to see (been watching the tracker) how busy you guys are and the tremendous amount of work the move to v14 must be. I have others interested in obtaining it sooner than later so I will maintain a local fork with the Turnkey Hub, etc. commented out and host it on my site until the dust settles and (if) you guys wish to host it. While my site contains no direct or implied endorsements from TurnkeyLinux, I will continue to give your site the credit and links it is due with respect to the core components of what I have produced (unless it poses an issue with you guys). Thank you, again, for your consideration.

**Comment by JedMeister** [comment]
No promises, but I hope to look into you code a little more closely and add it to the library for v14.1. I'll keep you posted.

**Comment by JedMeister** [comment]
Sorry running out of time for v14.1. Retargeting to v14.2.

**Comment by bormanst** [comment]
Thanks again for even looking at it, I hope it's worth while.

**Comment by bormanst** [comment]
Didn't mean to close issue. Thanks.

**Comment by bormanst** [comment]
I recently updated my repository and have built/tested it using (the briefly available) v 14.1 of TKLDev:

* Solr search engine was updated to most recent version 5.5.0.

* The Drupal, Roundup, SimpleInvoices conf.d script files were updated to their recent respective appliance versions and customization comments added to simplify maintenance and understanding.

I hope the changes to the script.d files help.  Thanks.

**Comment by JedMeister** [comment]
Thanks for the update and your patience. Apologies on the silence. Alon, Liraz and myself still haven't properly discussed inclusion of your appliance together though we have had some preliminary discussions. 

Considering the work that you have obviously put into it and the potential value of your appliance, I really love to include it. However historically TurnKey has never provided "all-in-one" type appliances (which essentially yours seems to be). I.e. it is an appliance which fulfils a role rather than providing a product if you understand what I mean? Not that that is a bad thing, I actually think it's a good thing.

However I think that Alon & Liraz have some hesitation in including appliances like this as it opens the doors to future requests such as "just like FormaVid but instead with Joomla (instead of Drupal) and/or InvoiceNinja (instead of SimpleInvoices) etc". For the record nobody has, I was just making an example, but they have a great point as I almost guarantee something like that would happen. If it was a single product (which I guess it sort of is - at least when you distribute it) but really tightly integrated e.g. single sign-on for all the components, etc then it might be a little different.

Ideally what we would rather do is provide some better mechanism to allow infinite "remixes", so users could create their own "all-in-one" appliances which include whichever TurnKey appliances they wanted into a single server. We have some ideas on how we might do that, but we are probably some time away from that.

So in the meantime, let's leave this issue open and keep me posted on any further updates, but I honestly do not know when (or even if) we will add your appliance to the library. I'm sorry that I haven't got better news for you.

BTW some of the initial v14.1 apps were buggy so we pulled them. New ones will be up ASAP.

**Comment by l-arnold** [comment]
The approach is interesting.  I like combines and a system to mix and match would be cool.  I will see if I can do an install sometime soon.

I like  the idea of a Joomla Magento mix, and have seen. TKLDev should provide semi easy combos if additional settings can be properly set (like Apache distribution of apps to different locales)

**Comment by bormanst** [comment]
No problem, I've been there myself and completely understand nightmare scenarios; it's been extremely useful for me so I thought it worth while to modify it for submission in case you guys thought so as well. Thanks for the 14.1 update, I will wait for the official 14.1 TKLDev before building/deploying the FormaVid update to my site.

Some notes:
* (You probably already know, but...) Though these types of "remixes" may vary slightly, an appliance composed of web/content management, issue tracking, and invoicing has the base components necessary to support the appliance itself from a small business or contractor standpoint; use it for your business, as your business, or both. Such an appliance has a chance of "chain reaction" ecosystem development while simultaneously expanding the sub-appliance ecosystems. Of course, this is all conjecture and my embarrassingly low volume site would never achieve the "critical mass" for proper validation.
* While I haven't been annoyed without single sign-on (usually only doing one thing on any given day), I'm not opposed to it and would integrate it, if that made any difference.
* I'm also willing to help out with "some better mechanism to allow infinite remixes". Not sure what you guys have in mind but minimally, I could help QA/validate by building/testing a new version of FormaVid. My years of automation/integration development experience made me appreciate and use your appliances as my building blocks in the first place so...

Thank you again for even considering my submission.

**Comment by bormanst** [comment]
I recently updated my repository and have built/tested it using v 14.1 of TKLDev:

- Solr search engine was updated to most recent version 5.5.3.

- Drupal and drush build commands were updated.

- Commented out some single certificate code previously overlooked.

Thanks.

**Comment by JedMeister** [comment]
Thanks @bormanst - great job on maintaining your work. Apologies that we haven't moved any closer. Behind the scenes we're flat out. Hopefully we'll have some time to come up for air soon...

**Comment by l-arnold** [comment]
Is there an ISO built or shouldbit be built through TKLDEV?

**Comment by bormanst** [comment]
You can get the recent 14.1 build iso at: 

[http://formavid.org/sites/formavid.org/files/isos/formavid-14.1.0-amd64.iso](url)

Notes:

- The email security alerts and tklbam screens are not presented during install.

- A tklbam profile is generated during install and is located in /usr/local/formavid/tklbam if needed.

**Comment by bormanst** [comment]
Congratulations on grinding out Core 14.2; your efforts are greatly appreciated!

No need to respond to any of this, at least in a timely fashion, as I know that you are extremely busy and there has been no commitment to my appliance nor do I expect any forthcoming.

That being said, I currently have some bandwidth available through the end of summer and would like to upgrade my appliance to include the awesome new features that you've built into Confconsole; namely the Let's Encrypt and mail relay stuff. I have a couple of questions though:

1) Are you using TKLDev-14.1 to build the new appliances or should I wait for v14.2?  It doesn't appear that the 14.2 updates really impact the dev part, but it's worth asking.  Once again, no "pushy-push" here as I can wait for v14.2 if recommended or required.

2) What's the line on jessie-backports?  I'm assuming the JDK-8 related backports are "stable" and, if allowed, I would be able to upgrade Solr from v5.x to v6.x.  I've already built/tested the backported JDK-8/Solr-6 version but do not want to throw a wrench into the "possible acceptance" of my appliance as the new Solr-6 features are mostly "enterprise-level/multiple-instance" related and not any kind of "support or deal breakers".

Also of note is that I built a TurnKey-LXC "research" version of my appliance with Drupal7/Roundup/SimpleInvoices/Solr in their own containers.  Again, your TurnKey-LXC efforts are greatly appreciated!  I finally had the reason/excuse to learn more about LXC other than just reading about it.  This is not a complaint, a request, or anything other than an observation of an inherent issue with LXC builds using multiple containers: the memory footprint can be bigger regardless of container usage, i.e. in my case, three separate "Apache2/MySQL/Postfix" instances running for Drupal7/Roundup/SimpleInvoices.  While this is usually not an issue for most businesses, I developed the FormaVid appliance primarily for the "mom and pop shop" that might have some older hardware lying around and when the memory footprint surpasses 2 gig, unfortunate upgrading decisions have to be made.

By the way, doing the LXC "research" build included doing a separate Solr build. I don't know if you're interested in a standalone Solr search appliance but I could produce one with a little extra effort, if desired.  I, by no means, want to heap more misery upon your stack but would gladly contribute what I can, if it is deemed worthwhile.

Thanks for all that you do.

**Comment by JedMeister** [comment]
Hi @bormanst 

Thanks for your kind words and your easily accommodated attitude. If only everyone were as kind, polite and patient as you! :smile: 

To explicitly answer your questions:

1. I'm using v14.2 TKLDev to build v14.2, so you'll be fine using that for your purposes. We do plan to do some work on TKLDev for v14.2, which is part of the reason why it hasn't been built yet. Even though you will be fine, we've updated the `deck` package so I would recommend that you at least update that (`apt-get update && apt-get install deck`).

2. Jessie backports is a tricky one. In essence packages installed from there should be relatively stable and usable. However, they won't receive any backported security updates. They will get updated time to time, but usually via a new(er secure) version. So there are no guarantees on timely upgrades to mitigate new security issues and no real guarantee on what version it will get bumped to or when. So automatically installing updates from backports is a bad plan on a production system. Having said that, we already use some packages from backports, so it's not a no-no.

We install dehydrated from backports, as well as the new version of Adminer. We use Adminer from backports as it's stable and generally pretty secure (we've been watching it for a while now). We also have a close relationship with the Debian package maintainer, which means we have additional insight. Dehydrated is a pretty simple BASH script which we didn't really even need to install from Debian, but we chose to to make life a bit easier.

So whilst it would probably be ok, the risk of security bugs being found in Java8 is high, have a look at how often it's been patched so far [here](http://metadata.ftp-master.debian.org/changelogs/main/o/openjdk-8/openjdk-8_8u131-b11-2_changelog). So I'd be a little hesitant to build an appliance using it (it won't get auto secupdates but will no doubt have unpatched vulnerabilities if not manually updated regularly).

It definitely won't be an issue once we get to v15.x as that will be based on Stretch (which has java 8). But I need to get v14.2 finished first! 

I'll try to remember to ask what Alon what he thinks.

**Comment by bormanst** [comment]
I appreciate the informative response; thanks for taking the time to think about it.

I saw the Roundup changelog was recently updated (Drupal7 and SimpleInvoices are already posted as v14.2) so I proceeded to update FormaVid to incorporate the appropriate changes.  No worries if Roundup is not completed yet, I'll keep an eye out for the official v14.2 posting and adjust accordingly.

With respect to the Java8 issue, I couldn't agree more and will not try to include it; security far outweighs any feature enhancements.

The FormaVid v14.2 updates have been committed to the master branch and the FormaVid v14.2 build iso is available at:

http://formavid.org/sites/formavid.org/files/isos/formavid-14.2.0-amd64.iso

Notes:

- The email security alerts and tklbam screens are not presented during install.
- A tklbam profile is generated during install and is located in /usr/local/formavid/tklbam if needed.

Thank you for your consistent professionalism regarding this matter.

**Comment by bormanst** [comment]
I'm closing this issue as I've moved on to a more generic build while upgrading the components. The code is still somewhat compatible (easily made so) with your styles and I could probably whip it up, on short order, after you've completed the 15.0 release *IF* there is any interest such a thing. The repository is the same: https://github.com/bormanst/formavid

Thanks again for all that you do and have done.

**Comment by JedMeister** [comment]
Hi @bormanst - apologies on such a slow response. I've had my head down trying to push v15.0 out. As you may have seen, I've released nearly half the library as ISOs. I've also built the alternate builds and they're on the mirror, but I haven't announced them yet.

**Comment by bormanst** [comment]
Excellent news and congratulations on grinding it out. I'll have to check
it out when I get the chance; you guys do a consistent job of making great
even better - always worth a look-see.

I've been going through the "oh that's been changed too" gotchya's
continuously myself so...

Best wishes with the remaining deployments.
