### ISSUE TITLE
v14 webmin-postgresql is missing in PostgreSQL applience

### ISSUE THREAD

**Issue by xanderdin** [turnkeylinux/tracker#480]
There is a missing end comment mark in plan/main leading to missing webmin-postgresql. I've posted a pull request fixing that issue several days ago but it looks like nobody notices it, so I'm opening this issue here.

**Comment by JedMeister** [comment]
Thanks @xanderdin. THanks for finding the issue and extra thanks for the PR. I did notice, but we tend to process PRs in batches.

I've tagged this appropriately (`inprogress` may seem weird; it just means that a PR to fix it exists but has not been merged).

**Comment by JedMeister** [comment]
Merged
