### ISSUE TITLE
improve AWS marketplace UX by disabling automatic installation of security updates

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#483]
It seems many AWS marketplace complaints seem to originate in lack of awareness of why the appliance is not immediately serviceable after boot (e.g., because it's installing security updates, which can take a few minutes to complete).

I propose we disable automatic installation of security updates post-boot and let the user choose whether or not they want that as part of the initialization process. We already do that but we force install security updates anyway.

**Comment by DocCyblade** [comment]
Would this be on all TKL distributions or just ones modified for AWS install in the cloud. Sorry to speak out of ignorance as I only know the ISO build process and not familiar with the AWS and other builds.

**Comment by lirazsiri** [comment]
I'm suggesting this only for the AWS builds. I still think installing security updates on first boot is a great idea. It's just a problem if it breaks the user experience when it happens in an environment we have less control over (e.g., deployments AWS marketplace). At least with the ISOs we have the console and can tell the user what we're doing.

**Comment by DocCyblade** [comment]
Ahh ok. I have not had any experience with TKL on AWS as I host all mine locally with VMWare or Just recently Proxmox. I should get a small instance to play around with to learn that aspect. 

I agree security updates are important on first boot. Again speaking out of ignorance, being that these are in the cloud security updates are even more important. When I spin up a VM that will be internet facing it is setup and secured way before it is internet facing.  Does an AWS appliance have an Internet IP upon first boot? Again I really should check out the AWS :-)

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux/buildtasks/commit/b561d436129572f85eb0f1b477d49f7aab419058
