### ISSUE TITLE
GitLab inithook uses 'systemctl' calls; should use 'service'

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#510]
This will only be an issue for container builds of GitLab (as they use SysVInit instead of SystemD).

The file that needs fixing is:
gitlab/overlay/usr/lib/inithooks/bin/gitlab.py

Note that both NodeJS and GitLab both use systemctl calls during build but that is not currently an issue as the build process will not work within a container currently anyway...

**Comment by JedMeister** [comment]
I had a bit more of a dig into this and it seems that the current systemd init script are downloaded [here](). We'll need to also include a sysvinit script. There are some [here](https://gitlab.com/gitlab-org/gitlab-recipes/tree/master/init/sysvinit) however I note that the Debian one uses Puma (not Unicorn) so we will need to tweak for our requirements. The CentOS ones would probably be a good guide.

**Comment by qrntz** [comment]
@JedMeister, I thought systemd-shim provided a functional stub for systemctl start/stop?

Regardless, it would probably be a good idea for all service control cases to use ```service X start``` instead of either ```systemctl start X``` or ```/etc/init.d/X start```. That is bound to work portably for the near future.

**Comment by JedMeister** [comment]
TBH I haven't actually checked but AFAIK systemd-shim doesn't provide systemctl but I could be wrong... Also using /etc/init.d/service-name is apparently ok even when using systemd as it is intercepted. Liraz wrote a [blog post about systemd](https://www.turnkeylinux.org/blog/debugging-systemd-sysv-init-compat) the other day that was interesting IMO.

**Comment by qrntz** [comment]
Using /etc/init.d can lead to a bit of confusion because it's associated with SysV init and it calls the respective systemd unit file if it exists (which is often the case) instead of the actual init script that also exists but does not ever get executed. The possibility to call systemd services with that is only there for backwards compatibility and to satisfy LSB specs. ```service``` is transparent in that it doesn't imply a preference for a certain init implementation.

**Comment by JedMeister** [comment]
Good point.
 
Regarding this issue, I just tested and systemctl doesn't work: "-bash: systemctl: command not found"

**Comment by jstruebel** [comment]
I ran into this just today when I tried to bring up a container version of the gitlab appliance. With some searching I found an init script at /home/git/gitlab/lib/support/init.d/gitlab that works when I simply moved it to /etc/init.d

**Comment by JedMeister** [comment]
Thanks @jstruebel - Ah, so it actually includes it already!? Just has to be moved to the right spot... Nice!

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/gitlab/pull/13
