### ISSUE TITLE
bug in 15regen-sllcert

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#512]
[line 26](https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/sslcert/usr/lib/inithooks/firstboot.d/15regen-sslcert#L26)
````
which lighttpd >/dev/null && service nginx restart
````
should be 
````
which lighttpd >/dev/null && service lighttpd restart
````

**Comment by mredig** [comment]
Is this what causes the lets encrypt interface to crash? If not, I will need to open another issue.

**Comment by JedMeister** [comment]
Not related. Please open a new issue and if you can provide as much detail (inc screenshots and/or copy pasted text) and steps to reproduce it. If we can reproduce it, we can fix it! :smile:
