### ISSUE TITLE
Canvas appliance not sending emails

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#516]
As reported by Teddy in the [forums](https://www.turnkeylinux.org/forum/support/20151207/canvas-14-not-sending-email) the v14.0 Canvas appliance is not sending emails as it should. We have confirmed this issue.

**Comment by JedMeister** [comment]
Workaround (as noted in the [forums](https://www.turnkeylinux.org/forum/support/20151207/canvas-14-not-sending-email#comment-24576)):
````
adduser --disabled-password --no-create-home --gecos "Canvas user" canvas
adduser canvas www-data
echo "PassengerDefaultUser canvas" >> /etc/apache2/sites-available/canvas.conf

WEBROOT=/var/www/canvas
USER=canvas:www-data
chown $USER $WEBROOT/config/*.yml
chown $USER $WEBROOT/config/environment.rb
chown -R $USER $WEBROOT/log
chown -R $USER $WEBROOT/tmp
chown -R $USER $WEBROOT/public

service apache2 restart
service service canvas_init start
````

**Comment by JedMeister** [comment]
@qrntz - Seeing as work on this is blocked by #525 I am reassigning this to you. I hope that's ok.

**Comment by JedMeister** [comment]
I'll give this back to Stefan to work on (build a patch for v14.1). I hope that doesn't interfere with where you were up to...

**Comment by qrntz** [comment]
@JedMeister, sure. My changes only pertain to building.
