### ISSUE TITLE
Odoo inithooks password script not working reliably

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#522]
An issue was noted in the [forums](https://www.turnkeylinux.org/forum/support/20151205/odoo-appliance-cant-get-past-create-database-screen) that the master password wasn't working to allow the master admin to create a new DB. I confirmed this but found that rerunning the inithook and restarting Odoo resolved the issue.

**Comment by JedMeister** [comment]
This is the actual issue I was originally testing. I'm not sure if it's also related to the other one or not...

**Comment by l-arnold** [comment]
Could be "misunderstanding" of what the Odoo Master Password,  There was one "self correction" of such on the forums.

The Odoo Master Password is not connected to a USER but is needed to create, drop, backup Databases inside the Odoo Database Manager.

When You create a Database in the Odoo Database Manager you do set a New Password (not in firstboot inithooks) for Admin user for that password.

Odoo puts in "admin" but the Inithook will now allow :"admin" so the actual Password needs to be set in the "dot dot dot" Odoo Master Password field.

**Comment by JedMeister** [comment]
I don't think so. This issue occurs when creating the first Odoo DB/user. The problem is that the "master admin" password isn't being set properly (sometimes) on firstboot.

I suspect that it is caused by a [race condition](https://en.wikipedia.org/wiki/Race_condition) on firstboot. That would explain why it works sometimes (and/or for some people) but works ok other times (for other people). It also explains why re-running the inithook fixes it...

**Comment by JedMeister** [comment]
FWIW as I hinted above the workaround is to rerun the inithook:
````
/usr/lib/inithooks/bin/odoo.py
service openerp-server restart
````
Then it all works as it should.

**Comment by DocCyblade** [comment]
@JedMeister is this only in containers or the ISO as well? I might tackle this one first strictly an ISO test then test it in Proxmox

**Comment by JedMeister** [comment]
I could reproduce it after installing from ISO (to a Proxmox VM). Although Landis couldn't/hasn't and I'm sure that I've tested it previously and never came across this... (hence why I suspect it's some sort of race condition)

**Comment by DocCyblade** [comment]
If I remember correctly we did see this condition in testing. I thought we had fixed it by just doing a restart. But we may have taken that out so that we were using systemV calls. I'll have to browse the code to be sure. I'll have a closer look this weekend

**Comment by JedMeister** [comment]
Ok cool, thanks Ken

**Comment by l-arnold** [comment]
I need to test some system start and stops.  Have not had trouble running system on
Vmwar, Linode and TurnkeyHub but I have not done a lot of service start/stops.

**Comment by JedMeister** [comment]
Closed by https://github.com/turnkeylinux-apps/odoo/issues/5
