### ISSUE TITLE
Use composer to install drush in drupal appliances

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#524]
We already use composer to install drush, but we download drush from git first (clone). Perhaps it would be better to use composer itself; as suggested [here](http://whaaat.com/installing-drush-8-using-composer):

>First install Composer globally.

>`$ curl -sS https://getcomposer.org/installer | php`
`$ mv composer.phar /usr/local/bin/composer`
Now add Composer's directory to your path by editing your .bash_profile or .zshrc

>`$ export PATH="$HOME/.composer/vendor/bin:$PATH"`
Reload your terminal or just re-source the configuration you just added.

>`$ source ~/.bash_profile`
Now that you have Composer working, you can install Drush from the latest HEAD.

>`$ composer global require drush/drush:dev-master`
That's it!

>Some other things you can do...

>Keep Drush (and anything else you have installed with Composer) up to date.

>`$ composer global update`
Roll back to a release version of Drush 7

>`$ composer global require drush/drush:7.*`
Install a specific version of Drush. For example: Drush 6.1.0

>$ composer global require drush/drush:6.1.0`

**Comment by OnGle** [comment]
Did a bit of research, while this is doable, installing drush from composer means drush install is within the composer directory of the root user on turnkey which means it's use outside of the initial install on a real production server is limited, installing drush from composer increases complexity without clear benefit. I believe we should leave this as is.

**Comment by JedMeister** [comment]
Thanks @OnGle, that sounds fair and reasonable. 

In response to your input I'm going to assign you, tag this as "won't fix", unpin it from the v14.2 milestone and close it for now. 

If anyone else disagrees and wants to work on it, please feel free to reopen and/or comment or open a new issue altogether... :smile:
