### ISSUE TITLE
New Appliance: Mediaserver

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#526]
I just noticed that @jstruebel has been working on an awesome looking [mediaserver](https://github.com/jstruebel/mediaserver) appliance.

Maybe it might be ready for the v14.1 release? I'm hoping! :smile:

**Comment by jstruebel** [comment]
It should be ready. I have it building with v14.0 and am now running a server from it. It is based on the fileserver appliance with the [Emby](https://emby.media/) media server added and basic default configurations applied. Testing and feedback from other users would be greatly appreciated.

**Comment by JedMeister** [comment]
Awesome! :+1: I'll give it a bit of a test drive; but I think it'd be a great addition to v14.1!

TBH it's all very auspicious! I'd never heard of Emby until I stumbled across it a week or 2 ago and started playing with a media server type appliance myself (I had a similar vision to you). I found that the install didn't go as smoothly as I'd hoped and had sort of shelved it. 

Then I found that you'd already done it! Yay! :tada: 

Don't ever hesitate to let us know of new appliances that you have built (or even just if you're just playing). The more the merrier I say! :smile:

**Comment by jstruebel** [comment]
What is the best way to let you all know if I'm working on something?

I had actually finally gotten it finished up to the point I would consider it ready for others to work with when you found it. It was a bit of a pain to get the setup part of it scripted, but once I figured it out it went pretty well. I did run into a bug with one of their recent updates where it didn't properly save the path for new libraries right in the middle of testing my scripts. I thought sure I had somehow broken something until I checked the forums. They were pretty quick about fixing it too. Maybe you ran into that when you were trying it out.

**Comment by JedMeister** [comment]
Some others have used their repo's "issues" to track things that need doing and/or bugs. But that's totally optional. Just posting updates here is fine.

You might be right. I never actually investigated my issue. It just seemed to stall during install. After waiting about 20 minutes I killed it with intention to return and troubleshoot. But then I saw yours! :smile:

**Comment by jstruebel** [comment]
Ah, actually that is something different that I ran into as well. It only seemed to happen when I was trying to install from a patch or tkldev. When I installed it manually from the command line or running a script it was ok. I tracked it down to the emby-server was starting at the end of the installation and blocking the apt process from continuing until the emby-server process was killed. I worked around it by forking the apt-get command, waiting until the emby-server process started, and then killing it. A bit of a hack, but it seemed like it was specific to the environment when running under the TKLDev or TKLPatch processes. I was going to post in the forums about it, but hadn't gotten around to it yet since I found a workaround.

**Comment by JedMeister** [comment]
I've done a test build of your repo and it worked awesome for me! :smile:

**Comment by aaronkempf** [comment]
I love y'all software.. I think that WinAmp was the pinnacle of media
players for the past twenty years.. I'm just DISGUSTED that you all ACCEPT
drm from Apple.. And you ACCEPT the ten dollar monthly fee for keeping your
music on icloud.

I'm still CLUELESS why anyone would ever use iTunes. I had better
functionality in what, August 1995 on beta software ?

**Comment by jstruebel** [comment]
FYI, I just pushed a minor update today. I discovered that it wasn't installing the Imagemagick packages automatically and I moved the group assignment in the config files so they don't conflict with the defaults during package upgrades.

**Comment by JedMeister** [comment]
Closing now as this is merged into the TurnKey library: https://github.com/turnkeylinux-apps/mediaserver

Thanks again @jstruebel for your great work! :+1: 

I'll do a PR against your repo once it's released so the repos stay in sync.
