### ISSUE TITLE
Install composer by default on LAMP & LAPP

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#527]
I propose that we install [composer](https://en.wikipedia.org/wiki/Composer_(software)) ([globally](https://getcomposer.org/doc/00-intro.md#globally)) by default on LAMP and LAPP. I think using a common [conf script](https://github.com/turnkeylinux/common/tree/master/conf); called by [lamp.mk](https://github.com/turnkeylinux/common/blob/master/mk/turnkey/lamp.mk) & [lapp.mk](https://github.com/turnkeylinux/common/blob/master/mk/turnkey/lapp.mk) would be the best plan.

Many PHP apps use it these days and it's only 270kb in the ones that don't. I would argue that even though it's really easy to install it's a handy tool to have already there ready to go. Seems like a no brainer to me. But I'd be interested what others think...

@DocCyblade @qrntz @Dude4Linux @dashohoxha

**Comment by dashohoxha** [comment]
Seems reasonable. Related to #524.

**Comment by dashohoxha** [comment]
Also setting a new domain for the appliance (on init hooks) can be implemented on LAMP, or maybe even on TKLCore.

**Comment by qrntz** [comment]
Sounds good.

**Comment by JedMeister** [comment]
Moving this to v14.2 as we'd like to push the v14.1 out soon. The focus for v14.1 is now shifting to bugfixing and maintenance. The code to support this will be added to common, but we will postpone implementation of this (into the appliances) at least until v14.2

**Comment by JedMeister** [comment]
@qrntz has already done common side of this; assigning the appliance side to @OnGle
