### ISSUE TITLE
Include di-live in the jeOS.iso

### ISSUE THREAD

**Issue by JERasmussen** [turnkeylinux/tracker#53]
I realize jeOS is more of a technical exercise and yes, one could do a minimal Debian or TKL core install and just strip away the unwanted code, but why ask users to do this when it's already been done?

Including the Debian installer seems (to me) like a trivial matter and in scanning the forums, I see I'm not the only user to request this.

**Comment by JedMeister** [comment]
A couple of points. Firstly we no longer ship a 'JeOS' version. We do internally still make something similar (we call it 'minimal') but we don't bother distributing it as frankly we have very little interest in our JeOS...

Regardless now that TKLDev exists, it is possible to create your own minimalist TurnKey OS mixed up any way you wish!

As such I'm going to close this for now (even though technically it hasn't been done). If anyone wants to reopen it please feel free.
