### ISSUE TITLE
suitecrm.py needs a facelift: application password fails at upstream version 7.4.3

### ISSUE THREAD

**Issue by LinforPros** [turnkeylinux/tracker#531]
An attempt to bump suiteCRM to the latest version by specifying:
VERSION="v7.4.3.zip"
int the "conf.d/download" file produces build/product.iso which, after installation, renders admin/login inoperable.

Reproduce:
edit conf.d/download
VERSION="v7.4.3.zip"

make

install product.iso in a virtual machine

point browser to "virtual machine ip of suitecrm"

privide login "admin"
password "password chosen on first boot"

**Comment by JedMeister** [comment]
Thanks for reporting, We weren't intending to update SuiteCRM for the v14.1 maintenance release so I'm not sure when we'll get to this but it's good to know.

As a workaround for now you could remove the password setting part of the inithook and set a default password in the conf script (I think - I haven't actually checked it though).

If you work on this then please let us know. If you can resolve it in time for the v14.1 release then we could include an updated version of SuiteCRM for v14.1 (which would be cool).

**Comment by JedMeister** [comment]
I've just had a quick look into this (after I said I wasn't going to do it any time soon) and it's more critical than what I first thought. I'm pretty sure that the issue is that SuiteCRM is not properly installed.

I didn't spend a ton of time on it and I'm not 100% sure but it looks like the (web) installer has changed. We use a curl based install and although it work's fine when it's set up, it's a dumb script and doesn't adapt to changes. So I expect that that will need to be updated. It's not actually that hard but it is a bit of mucking around so no promises.

**Comment by qrntz** [comment]
I'm looking into this.

**Comment by LinforPros** [comment]
Hi qrntz,
I really appreciate if you start working on it. I can offer to run the updated code since little can I do with programming.... I actually have vested interest to use the software which was the primary reason for me to report the bug.
LinforPros

**Comment by JedMeister** [comment]
FWIW SuiteCRM is a fork of SugarCRM so once this is fixed then the same fix should also apply to SugarCRM.

**Comment by qrntz** [comment]
Turns out it can be installed in CLI mode! I'll be porting this over to SugarCRM as well.

**Comment by JedMeister** [comment]
Great work mate! :+1: That's a win for longer term maintenence! :smile:

**Comment by qrntz** [comment]
@JedMeister, since there is no separate issue, I linked my changes to SugarCRM here.

**Comment by JedMeister** [comment]
Good thinking. That's fine, but I might add sugarcrm as a tag to this issue for completeness.

**Comment by JedMeister** [comment]
@LinforPros - We have closed this as the code has now been merged. We still don't have a firm release date for v14.1 but you can build it yourself using TKLDev and it should all work. Please let us know ASAP if you encounter any issues...

**Comment by LinforPros** [comment]
Big thanks for the work done.
LinforPros
