### ISSUE TITLE
Enable auto minor updates for WordPress

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#537]
I think that it may be the default for WordPress but we need to double check (and adjust if neccessary). We want minor updates to auto install; but not major ones...

**Comment by OnePressTech** [comment]
Just an (obvious) observation that this issue is related to issue #489 . The web server needs full control of the WordPress sub-directory to update the WordPress software.

**Comment by JedMeister** [comment]
@OnePressTech - Yep! :smile: See the PR; specifically here: https://github.com/OnGle/wordpress/blob/update-fix/conf.d/main#L130

Although I note that we could tidy up a little and get rid of L125
