### ISSUE TITLE
Fixes/Improvements to Owncloud appliance

### ISSUE THREAD

**Issue by jstruebel** [turnkeylinux/tracker#538]
I needed to use owncloud for a project this weekend and found a bug and an improvement so I added them to the appliance.

The bug is fixed in the last commit, when running it as a container it would have two domains configured because of the preseeded init. The preseeded init value took precedence since it ended up later in the file. The fix deletes any existing domains that were configured by the init before inserting the current one.

The improvement is to install the dependencies required by the external files and user ldap apps. I went to enable them and got a white screen since they were missing. With them installed by default that won't happen. Even though these apps are not enabled by default, as a user I wouldn't expect dependencies of the installed apps to be missing.

See PR: https://github.com/turnkeylinux-apps/owncloud/pull/9

**Comment by JedMeister** [comment]
Great work; thanks Jonathan! :+1:

**Comment by qrntz** [comment]
@jstruebel, if you link to the issue in the description of your PR preceded by something like «solves», «resolves» or «closes», then merging it will [automatically close the issue](https://github.com/blog/1506-closing-issues-via-pull-requests). I use this all the time.

Thanks for the contribution!

**Comment by jstruebel** [comment]
You're welcome! And thank you for the tip

**Comment by JedMeister** [comment]
Clsoing as the code has been merged. Thanks again @jstruebel
