### ISSUE TITLE
Joomla3  configuration.php ownership

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#539]
In order to make basic and needed changes to any Joomla set up the 
configuration.php file needs to be owned by Apache rather than Root.

When one is in Joomla Admin, config changes need to write to this file and cannot.

Easy enough to change but would be best if the last inithook set this (IMHO).

**Comment by JedMeister** [comment]
Re-reading this I think that it's actually a bug, so I've retagged it...

**Comment by qrntz** [comment]
Was a regression accidentally missed in review.

**Comment by JedMeister** [comment]
TBH I haven't actually tested so maybe something else is going on; but I guessed that it was a regression.
