### ISSUE TITLE
Magento (Jessie) Difficulties with any TKLBAM Restores

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#540]
I was able to easily migrate a Joomla Install with TKLBAM.  I have tried about 6 variations of the same with Magento and have not been able to get a good TKLBAM Migration, particularly to a Hub Install.

Typically get:

Server error

500
##

**Comment by JedMeister** [comment]
Have you checked the logs for errors post TKLBAM restore? Given the error I would suggest checking the Apache errors `/var/log/apache2/error.log`. Please feel free to post your logs here if you want a hand debugging.

**Comment by JedMeister** [comment]
@l-arnold - Also it would be useful to know if this was a migration between v14.0 servers; or from v13.0 to v14.0. If the latter then it is probably some Apache config that has changed. There were significant config changes in Apache 2.2 (v13.0) and 2.4 (v14.0). 

Although it doesn't explain why your Joomla migration worked ok though...

**Comment by JedMeister** [comment]
Hey @l-arnold is this still an ongoing issue for you?

Do we need to look into this further or are things all good now?

**Comment by JedMeister** [comment]
I'm going to close this for now. Please reopen if it continues to be an issue.
