### ISSUE TITLE
We should probably show a message on root login attempt to a TKL EC2 instance like Debian does

### ISSUE THREAD

**Issue by qrntz** [turnkeylinux/tracker#541]
From my experience, the Debian AMIs accept your SSH key for root, show a message that the «admin» account is to be used instead and then terminate the connection.

TurnKey does not do that (yet). I think it would make sense to implement that as part of the fence policy for EC2.

**Comment by lirazsiri** [comment]
Sounds like a good idea. I bet lots of people have root hardcoded in their SSH configs and will appreciate this.

**Comment by qrntz** [comment]
Turns out this is a feature of cloud-init: http://serverfault.com/questions/216174/how-ubuntu-cloud-version-enforces-the-no-root-login-over-ssh which makes it related to https://github.com/turnkeylinux/tracker/issues/172

We can replicate it but then including cloud-init is on the roadmap anyway.

**Comment by JedMeister** [comment]
Ok good to know... Certainly adds weight to adding CloudInit to the images.

**Comment by JedMeister** [comment]
Reopening as a separate issue. Cloud-init inclusion won't happen for v14.1, but we may still be able to rob some code from it to add this functionality...

**Comment by JedMeister** [comment]
Closed as per https://github.com/turnkeylinux/inithooks/pull/21 plus additions as per comments
