### ISSUE TITLE
WordPress appliance should disable WP-cron and enable Linux cron

### ISSUE THREAD

**Issue by OnePressTech** [turnkeylinux/tracker#545]
WP-Cron adds a latency delay in most site accesses since it triggers all the scheduled actions from a user access. Switching from wp-cron to cron provides a better result.

**Comment by JedMeister** [comment]
Sounds liek a great idea. I did a similar thing for the Drupal appliance for v14.0. THis might be a good candidate for v14.1 if it's easy enough.

Do you have any links or specific code snippets? Or are you interested in taking this on?

**Comment by OnePressTech** [comment]
Technically it is quite straight-forward.

One line cron job to poll the wp-cron link on the WordPress site

`lynx -source "<mydomain>/wp-cron.php" >/dev/null 2>&1`

and one line in the wp-config.php file to disable the default mechanism.

`/* Disable wp-cron, we run linux cron */`
`define('DISABLE_WP_CRON', true);`

lynx would need to be installed. It has some advantages over wget, and curl since it is a browser that can have a user-agent. The alternate choices to lynx, wget and curl, are [blocked by the Bulletproof security plug-in](https://wordpress.org/support/topic/bps-prevents-backupwordpress-from-accessing-wp-cron).

NOTE: Switching to cron-triggered wp-cron has an additional benefit to users who upgrade their TKLX WordPress appliance to multi-site. There is a WordPress design flaw in the default wp-cron mechanism which does not trigger sub-sites wp-cron events. In the case of a multi-site installation [a WordPress plug-in](https://wordpress.org/plugins/multisite-system-cron/) is also required.

Other References:
[wp-cron access options](https://williamjxj.wordpress.com/2010/12/17/curl-vs-wget-vs-lynx/)
[securing wp-cron access](http://serverfault.com/questions/196069/using-lynx-or-wget-in-cron-to-call-a-php-script)

When is v14.1 submission cut-off date?

**Comment by JedMeister** [comment]
Awesome thanks Tim. :+1: 

Re v14.1 "cut off", I still haven't finalised the timeframe; (I hope to by the end of this week) but we have made significant progress on fixing the bugs. The bigger ticket items (that I just mentioned in another post) might take a little while though. If I were to guess I suggest 3 weeks. Bottom line is though, if I know that you are working on something and have a rough idea of time frame then I'm happy to negotiate. So I guess the question is if you were to take this on; how long would you need? :smile:

**Comment by OnePressTech** [comment]
3 weeks would be tight. I would be doing this as a sideline to client work and I have a full load for the next month. I'm also getting too old for deadlines...too much stress is a killer :-)

**Comment by JedMeister** [comment]
No worries! :smile: TBH 3 weeks is probably tight for me too!

Your info and links is invaluable though. I'm going to target this to v14.1 anyway and we'll see what happens. If you (or anyone) decides to have a crack at this then just post a comment so we don;t have multiple people on the same thing! :smile:

**Comment by JedMeister** [comment]
@OnePressTech - I'll get @qrntz to take this on. We have no ETA on v14.2 but it'd be nice to tidy up some of these in the meantime anyway...
