### ISSUE TITLE
Moodle v3.x is out now; request to update TKL app

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#549]
As requested in the [forums](https://www.turnkeylinux.org/forum/support/20110531/moodle-version#comment-24744)

Updating everything for v14.1 is not likely (nor feasible) but I have added this one as a "low priority" feature request.

It is possible that it may get nudged to v14.2 though...

**Comment by qrntz** [comment]
@JedMeister, is the priority for this and #548 still higher than feature requests? Then I could take this on.

**Comment by qrntz** [comment]
This was pretty trivial so I took the liberty.

**Comment by JedMeister** [comment]
Sry I didn't reply. I recall writing a response, but must have forgotten to hit "post"... Anway, all good! :smile:
