### ISSUE TITLE
Enable SSL on CouchDB appliance

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#551]
In version 14.0 of the CouchDB appliance, ssl is not enabled on port 443.  This was detected during Ansible/LXC testing.  The solution is to modify the file, /etc/nginx/sites-available/couchdb and add 'ssl' to  the listen statement.  It should read:

    listen 0.0.0.0:443 ssl;

**Comment by JedMeister** [comment]
Thanks for reporting John. Ever since you mentioned it, testing the CouchDB appliance has been on my todo list. :+1:
