### ISSUE TITLE
Web Console on database appliances listening on port 8888

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#552]
The default lighttpd.conf on the mysql and postgresql appliances is misconfigured.

     server.document-root        = "/var/www/html"
     server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
     server.errorlog             = "/var/log/lighttpd/error.log"
     server.pid-file             = "/var/run/lighttpd.pid"
     server.username             = "www-data"
     server.groupname            = "www-data"
     server.port                 = 8888

The server.document-root should be changed to "/var/www/" and server.port should be changed to 80.

**Comment by JedMeister** [comment]
Closed as per above merged commits
