### ISSUE TITLE
Plone doesn't have inithook (to set password)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#554]
Henry reported on the [forums](https://www.turnkeylinux.org/forum/support/20160121/potential-security-breach-prior-webserver-password-change) that the Plone appliance uses a default password...

**Comment by JedMeister** [comment]
FWIW I have spent some time looking into this and it appears that whilst it is easy to create a new user with a password; it is currently not possible to reset the password of a current user via the commandline. This means that our current infrastructure would not be able to support this OOTB (we currently require a specific username).

With further/deeper investigation there is probably a way to work around this. However I have just noticed that there is a v5.x Plone available now (current TurnKey appliance uses v4.3.6). So IMO it would make more sense to update Plone in v14.2 and then develop an inithook.

**Comment by qrntz** [comment]
I'll sort this out.
