### ISSUE TITLE
Metal Webmin theme as default

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#56]
TKL User Adrian Luca has created (and supported) a very nice looking Webmin theme (see the thread on the forums here: http://www.turnkeylinux.org/forum/general/20120815/metal-webmin-theme). It is a fantastic looking theme and he has shown his dedication to it by providing support (both by updating it and helping out users with issues). 
Personally I think that it would be really cool if his initiative was repaid by making it the default TKL Webmin theme! (Although perhaps the current default TKL theme could still be there as an option to assist those who wish to keep the current theme? Or at least instructions on easily changing back to it?)
What do others think?
##

**Comment by alonswartz** [comment]
@metal696heart I know it's been a while, but are you still supporting this theme?

**Comment by IntellixWeb** [comment]
I am supporting it if needed.

**Comment by metal696heart** [comment]
i am if still needed. I tought people got bored of it allready as there are some new fancy themes out there. :D

**Comment by JedMeister** [comment]
I'm going to close this one now (7 years later...!) as we're using the Webmin "Authentic" theme now.
