### ISSUE TITLE
Magento TKLBAM

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#561]
[update by @jedmeister]
- Need to check that Magento has suitable garbage collection set up.
- check that exclusion of `/var/www/magento/var/cache` from backup doesn't cause issues; and add to profile if not
- exclude `/var/www/magento/var/session` from backups

----

Totally Blank Site built.  Sat for a Week.

Sessions being Backed up.
Takes forever.

Sessions and CACHE should NOT be backed up on Magento IMHO.
##

**Comment by JedMeister** [comment]
Sorry I haven't commented on this previously. I'd like to help you out with this once I have v14.1 released (shouldn't be too long now...)

**Comment by DocCyblade** [comment]
I think this is related to a blank TKLBAM profile. I have that kind of on the radar over on my repo https://github.com/DocCyblade/tkl-odoo/issues/69 This is one of the things I want to implement first.

**Comment by JedMeister** [comment]
Remember though that blank TKLBAM profiles inherit from [Core](https://github.com/turnkeylinux/tklbam-profiles/blob/master/core) so a blank profile is not a blank profile! :smile:

**Comment by l-arnold** [comment]
Understand..  Still /var/www/magento/var/cache  (and sessions) likely not specified to exclude by Core.\

Magento TKLBAM should be tested on a few fronts for sure.  Have not had time to debug some other problems noted.

**Comment by JedMeister** [comment]
Ok cool. 

You can test by adding 
````
-/var/www/magento/var/cache
````
to `/etc/tklbam/overrides` and do a fresh backup. 

Then confirm it works as it should by restoring your backup to a new/fresh/clean Magento server and double check that everything works as it should...

**Comment by lirazsiri** [comment]
Then we can move that to the magento TKLBAM profile so you don't have to tweak the overrides.

**Comment by l-arnold** [comment]
/var/www/magento/var/session(s) needs critically to be added.  Tklbam neatly breaks the server backing this up.  Need to build a good fast flush too.  Can do in Magento but I normally do manually.  

Need to delete the files but notvthe folder.  (can lose some potential orders I think however)

**Comment by JedMeister** [comment]
Hey @l-arnold have you implemented this and checked that it works? If so, let's add it?!

Also I have had a quick read and it seems that `/var/www/magento/var/session` should certainly be excluded for backup. And actually we should really be configuring garbage collection on that too.

I'm not quite as sure about `/var/www/magento/var/cache` but on face value it seems that it would make sense to not include it. I'd like confirmation that everything still works afterwards.

**Comment by JedMeister** [comment]
Hey @spaghettimaster - I know I've been calling out to you a fair bit today, but this is another one that would be good to look into for v15.0. If you need some pointers on TKLBAM, please hit me up.

**Comment by spaghettimaster** [comment]
Hey @JedMeister, I opened PR: https://github.com/turnkeylinux/tklbam-profiles/pull/10

**Comment by JedMeister** [comment]
Thanks @spaghettimaster! And I just merged it! :smile:
