### ISSUE TITLE
Improve Yii default demo application

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#568]
It would be good to tweak the pre-installed default demo app (yii2-advanced) so that the backend is easily available by default. Perhaps also an inithook to set a default admin password?

Regardless here are some docs which might be relevant:
http://www.yiiframework.com/wiki/799/yii2-app-advanced-on-single-domain-apache-nginx/
http://mickgeek.com/yii-2-advanced-template-on-the-same-domain-2
https://github.com/mickgeek/yii2-advanced-one-domain-config
https://github.com/mickgeek/yii2-advanced-one-domain-config/issues/5
##

**Comment by JedMeister** [comment]
Any thought son this one @spaghettimaster?

**Comment by spaghettimaster** [comment]
Backend is available at /admin.
And Yii2 does`t have user accounts out of the box. It's ok, because developers can choose how to configure role-based access control.

So maybe this issue is no longer relevant?

**Comment by JedMeister** [comment]
Ok cool. Thanks @spaghettimaster - I'll close it then! :smile:
