### ISSUE TITLE
Oracle phasing out browser Java impacts legacy Webmin File Manager

### ISSUE THREAD

**Issue by OnePressTech** [turnkeylinux/tracker#579]
Webmin Java-based file manager will stop working on legacy TKLX VMs once [Oracle drops JAVA browser support](http://www.eweek.com/developer/oracle-dropping-java-browser-plug-in-in-jdk-9.html).

You might want to create a blog post to foreshadow this to your members. Updating to the latest 14.1 TKLX will now get them the latest Webmin that supports a web-based file manager.
##

**Comment by JedMeister** [comment]
:+1:

**Comment by JedMeister** [comment]
I'm closing this. Thanks for the great idea Tim, sorry that it fell through the cracks...
