### ISSUE TITLE
Canvas very slow starting

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#583]
Now that the Canvas "delayed job runner" service is operating as it should (see #516), the Canvas appliance is very slow to start (including completing the inithooks). That may be an unfortunate reality but it would be good if we could try to improve it as much as possible for v14.2.

**Comment by qrntz** [comment]
Alas, Canvas is naturally very slow. The assets are precompiled already so what's left would be webserver tuning. If that doesn't bring much improvement, we could try operating it on top of another stack (e. g. Nginx + Puma). I think that would help if nothing else does.

**Comment by JedMeister** [comment]
Ok, I thought that may be the case, but I wanted to note it.

FWIW when I was testing v14.1 (KVM VM with 2GB RAM) the "delayed job runner" service restarts in the inithooks ([here](https://github.com/turnkeylinux/buildtasks/blob/master/patches/maintenance-releases/14.1-jessie-amd64/canvas/overlay/usr/lib/inithooks/firstboot.d/40canvas#L9)) take literally minutes (IIRC something like 2-3+ minutes - which feels like forever)... I didn't test exhaustively but with 4GB RAM it was still really slow but getting close to reasonable...

Cycling the services during install (see [here](https://github.com/turnkeylinux/buildtasks/blob/master/patches/maintenance-releases/14.1-jessie-amd64/canvas/conf)) seemed to help a little but not a lot.

OTOH perhaps there is some sort of hacky workaround to make things at least appear nicer?

Perhaps just doing something like disabling the "delayed job runner" service by default and enabling it right at the end of firstboot? That would at least mean that the service won't be running initially so it only needs to start once everything has been done. That should at least reduce the initial firstboot time. 

Or seeing as the "delayed job runner" doesn't actually need to be started when the server starts (it hasn't been running at all in all our previous Canvas releases), perhaps always delaying it's startup on boot? 

And/or make the daemon check for the inithooks status (i.e. don't start if RUN_FIRSTBOOT is true)?

**Comment by qrntz** [comment]
Those are all valid suggestions and something I should try when I get to it.

However even without the delayed jobs, Canvas still was fairly slow... For me, the first few requests on a fresh installation would always time out before Rails could send a response (I think I allocated 3GB to the VM). So while obviously we need to eliminate the minutes-long wait in inithooks first thing, some work on the entire stack is warranted.

**Comment by JedMeister** [comment]
I have been doing some Canvas v14.1 testing. 

My tests on a local KVM VM (4vCPUs & 8GB RAM) show that given adequate resources it works flawlessly. However when launched from the Hub it does not start reliably on firstboot (in fact it reliably doesn't start successfully!). Rebooting resolves that, although it can also be worked around by restarting Apache (except t2.small; which also requires that canvas_init be stopped while Apache is restarted). E.g.:

### t2.small
**Initially fails; either reboot or:**
`service canvas_init stop`
`service apache2 restart`
 - refresh login page in browser
 - wait until log in page loads successfully

`service canvas_init start`

#### t2.medium; t2.large; c4.large: 
**Initially fails; either reboot or:**
`service apache2 restart`

I can't comment on long term usage as I was the only connected user and only tested initial ability to log in to Canvas.
