### ISSUE TITLE
reboot (or firstboot secupdates) breaks SSL certificates for nginx

### ISSUE THREAD

**Issue by dominique120** [turnkeylinux/tracker#587]
On Torrent Server(VMDK on VMWare Workstation 12 ), when I go though the initialization, install security updates and reboot as suggested on start up nginx fails to start and gives the following error:
```Mar 14 02:59:14 torrentserver nginx[497]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/ssl/private/cert.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)```
```Mar 14 02:59:14 torrentserver nginx[497]: nginx: configuration file /etc/nginx/nginx.conf test failed```
```Mar 14 02:59:14 torrentserver systemd[1]: nginx.service: control process exited, code=exited status=1```
```Mar 14 02:59:14 torrentserver systemd[1]: Unit nginx.service entered failed state.```

How to reproduce:
1. Go through initialization
2. Install secutiry updates 
3. Reboot
OR
1. Dont install security updates(it will work till we reboot in the next step)
2. Reboot

**Comment by JedMeister** [comment]
Thanks for the heads up. I'll look into it and see what I can see. I'll be back with a workaround when I work it out...

**Comment by JedMeister** [comment]
Looks like this definitely also effects other appliances too: https://www.turnkeylinux.org/forum/support/20160313/lxc-connections

**Comment by dominique120** [comment]
I tried updating manually with ```turnkey-install-security-updates``` and with ```apt-get update && apt-get upgrade``` but the problem persists. As soon as I reboot it breaks. Updating manually might work for lxc but it does not for torrentserver

**Comment by JedMeister** [comment]
I think that this may actually be related to a kernel regression (but I still haven't tested much yet). I say that as I was not able to reproduce this when running in a LXC container. I installed all the secupdates and rebooted numerous times and it just keeps working... Also I know that a kernel update was released just after I built the v14.1 appliances.

I still haven't had a chance to test a VM as my internet is really slow ATM (the main fibre that serves my island home is down for repairs) and I've only just downloaded the ISO to test.

Out of interest though perhaps it's related to the VM builds somehow? You are using the VMDK and others on the forums mentioned the OVA build. I'll soon see I guess (if my ISO install works ok too).

**Comment by dominique120** [comment]
I'll test an ISO of the torrent server and let you know how it goes.

**Comment by JedMeister** [comment]
I have reproduced this installing from ISO and it doesn't look like it's anything to do with the kernel... Even just a simple reboot (no secupdates installed at all) still breaks it. 

I wonder why it doesn't occur with the LXC container though. That is weird.

**Comment by dominique120** [comment]
Yep I just finished installing and testing the iso and it does not work.

**Comment by JedMeister** [comment]
Ok looks like it might be a regression introduced in v14.1 by an update to our self-signed cert generation script. FWIW the update was to reduce the amount of info that our appliances leak via the self signed cert; but it looks like it broke things. 

I'm guessing that we missed it during testing as we must not have done many reboots and obviously none with the infected appliances. FWIW I'm guessing that it also occurs when you install updates as the new kernel forces the firstboot updates to reboot the server.

I'm still working on a workaround...

**Comment by JedMeister** [comment]
Ok here's the workaround:
````
URL=https://raw.githubusercontent.com/turnkeylinux/common/master/overlays/turnkey.d/sslcert
FILE=usr/local/bin/turnkey-make-ssl-cert
wget -O /$FILE $URL/$FILE
turnkey-make-ssl-cert --default --force-overwrite
service nginx restart
````

**Comment by dominique120** [comment]
This works. I tested it with the VMDK and the ISO. Will you find a more permanent solution or will you maybe temporarily put it in one of those inithook scripts?

**Comment by JedMeister** [comment]
Great thanks for confirming the workaround.

I'm not 100% sure what we'll do but I'll let you know ASAP.

**Comment by JedMeister** [comment]
We've temporarily pulled the v14.1 images from the website. I will rebuilding a number of images so when the v14.1 images are back they will be fixed.

**Comment by dominique120** [comment]
Thats great! I will await the new images.

If I can help in any way let me know.

**Comment by kstaniek** [comment]
After applying the workaround there does not help. The nginx starts but the 502 Bad Gateway error is returned.

Steps to reproduce on proxmox 4.1

1. Create CT based on debian-8-turnkey-gitlab_14.1-1_amd64.tar.gz
2. Boot
After booting the nginx does not start.

**Comment by JedMeister** [comment]
The workaround noted here should work; although GitLab is a resource hungry thing and take quite a while to start the first time. #295 might be worth a read? We did add the precompile to v14.1 (as discussed there) though so I'm not sure what is going on...

**Comment by kstaniek** [comment]
I installed fresh CT and allocated 4 cores and 2GB mem.  Booted and applied workaround. Rebooted CT. I was waiting for 10 minutes and still have 502 Bad Gateway from nginx.

**Comment by kstaniek** [comment]
That might be important. Everytime trying to open webpage seeing this in the  /var/log/nginx/gitlab.error.log

2016/03/27 20:01:07 [crit] 1453#0: *69 connect() to unix:/home/git/gitlab/tmp/sockets/gitlab.socket failed (13: Permission denied) while connecting to upstream, client: 192.168.1.133, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/", host: "172.31.0.4"

**Comment by kstaniek** [comment]
root@gitlab-prod1 ~# ls -l /home/git/gitlab/tmp/sockets/
total 0
srwxr-xr-x 1 git git 0 Mar 27 19:49 gitlab.socket

added +w to the socket and it seems to be working. This must be an issue in gitlab upstream.

**Comment by kstaniek** [comment]
just to be precise o+w

**Comment by JedMeister** [comment]
Sorry for slow response...

Thanks for followup and sharing your workaround. I'll need to have a play and we may need to re-re-release the GitLap app (we just completed redoing it to include this particular SSL cert/nginx bug workaround).

**Comment by dominique120** [comment]
When are you planing on releasing the new 14.1 images? and how did you implement the fix?

**Comment by JedMeister** [comment]
@dominique120 The new images should be on the mirror now. The appliances that were affected by this particular bug (i.e. nginx/SSL cert) were actually rebuilt about a week ago; but then we found another bug that required us to rebuild a number of other appliances (the ones that weren't affected weren't rebuilt). So we held off the "official" release a bit longer...

The fix was essentially the same as the workaround: use the latest/fixed version of the self signed SSL generation script. Once rebuilt with the latest script there are no issues (at least not this one). 

Interestingly it actually affected applliances that use Apache and LigHTTPd webservers too; however only Nginx broke so bad that it wouldn't serve content. It could be argued that really the other webservers should have also failed, but they didn't. It suggests that Nginx has scricter requirements which could be a good or bad thing depending on your perspective... It was also interesting that it didn't cause Nginx to fail when running inside a container. I still don't totally understand why and I haven't had any time to investigate...

**Comment by JedMeister** [comment]
This issue has been resolved with the rebuild so is being closed.

@kstaniek - Unfortunately I didn't put any time into looking into your issue sooner (if I did I could have fixed it when I fixed this other one). I have confirmed your issue and your workaround but I have not yet fixed it (as I'm not sure that your workaround is the best way to go). As it is not related to this one (and hasn't yet been fixed) I have opened a new issue specifically for that: #602

**Comment by dominique120** [comment]
Thanks for fixing the bugs and for the information you gave me above!

When will you update the images on the site?

**Comment by JedMeister** [comment]
I was hoping to announce this week, but we've run out of week... So my plan is next week.

In the meantime, the new images are available already on our [mirror](http://mirror.turnkeylinux.org/turnkeylinux/). It should be fairly obvious but the directory structure of the mirror is something like this:
````
mirror.turnkeylinux.org
`-- turnkeylinux
    `-- images
        |-- iso
        |-- openstack
        |-- ova
        |-- proxmox
        |-- vmdk
        `-- xen
````

**Comment by dominique120** [comment]
Ok so I had a few days to test torrent server 14.1 from the mirror but for some reason its still not working. I tested an iso and a vmdk. I also tried some other ones(django and lamp) although since they use apache I dont think they apply here.

The workaround works and secupdates dont break it anymore. But as soon as I restart, nginx fails to start.

**Comment by JedMeister** [comment]
Hmm, ok. Thanks for reporting back. AFAIK you are correct in that none of the appliances that included Apache were affected (although I did rebuild them too).

I have done some preliminary testing and from what I can see this is a whole new issue (not related to the original one at all). I'll do some more testing to try to work out exactly what the problem is but it seems to be something to do with the updated nginix in Debian. I suspect that some configuration options have been tightened up (possibly to resolve a security issue?)

Anyway, I'll digf a bit deeper and probably open a new issue (i'llpost here though so you know where to find it...)

**Comment by JedMeister** [comment]
Argh, it looks lie it may actually be a variation on the original issue... I'm not sure how that happened... I need to really dig in so not only can I fix it properly, but so I can make sure that it doesn't happen again. Reopening this issue until/unless I create a new one...

**Comment by JedMeister** [comment]
New ISO has been built and is in the process of being uploaded to the mirror. I'm 99.999% sure that I fixed it properly this time...! Should be available from the mirror within the next 24 hours. Check the file date on the mirror to make sure you are getting the latest one. 

The other builds (e.g. VMDK etc) will be up within the next 48 hours hopefully...

**Comment by JedMeister** [comment]
PS I will be updating the website (to point to the new builds) and announcing the v14.1 release within the next few days; by mid week hopefully...

Closing this issue now in anticipation that all will be well...

**Comment by JedMeister** [comment]
FWIW the v14.1 release is now live: https://www.turnkeylinux.org/blog/14.1-bugfixes-maintenance-and-more
