### ISSUE TITLE
TurnKey Common/rails 20regen-rails-secrets relies on appname=hostname

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#591]
The firstboot init file, 20regen-rails-secrets, gets the appname from /etc/hostname.  Starting in v14.0, we are now setting the hostname to the actual host's name instead of the appliance name.  Since the configuration should always be found in /var/www/railsapp/config, I think the head of the file should be changed from
```
#!/bin/bash -e
# regenerate rails secret key and mysql password

. /etc/default/inithooks

APPNAME=$(cat /etc/hostname)
[ "$APPNAME" == "rails" ] && APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME
```
to
```
#!/bin/bash -e
# regenerate rails secret key and mysql password

. /etc/default/inithooks

APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME
```
I also had to make changes to the assets.rb file to get the web server to run.
```
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( ui.tabs.css )
Rails.application.config.assets.precompile += %w( base.css )
Rails.application.config.assets.precompile += %w( ui.core.js )
Rails.application.config.assets.precompile += %w( ui.tabs.js )
```
I'm not familiar enough with Rails to know if these are all the changes required to run version 4.2.4, but at least apache starts up without errors.

**Comment by Dude4Linux** [comment]
PS:  The same change needs to be made for common/overlays/rails-pgsql.

**Comment by Dude4Linux** [comment]
The file common/conf/rails also makes the assumption that APPNAME=$HOSTNAME, but I think that is a safe assumption during the build which is a more controlled environment.  Still I wonder why it was thought necessary to make that assumption.  rails and rails-pgsql are the only two apps that seem to use this paradigm.

**Comment by JedMeister** [comment]
As you say, using APPNAME=$HOSTNAME at buildtime is pretty safe. But using that at firsboot is a really bad idea IMO. 

Whilst for many of the builds it will be reliable for firstboot (e.g. ISO, OVA, VMDK). However I am not sure that is true for the other builds. for example launching an LXC container from Proxmox; the hostname is set from Proxmox PRIOR to launch. So in that circumstance it is highly unlikely that the hostname will match. Getting the appliance name from `turnkey-version` (which reads `/etc/turnkey_version`) would be a much more reliable way to go. E.g.:
````
root@tkldev ~# cat /etc/turnkey_version | cut -d- -f2
tkldev
````

**Comment by Dude4Linux** [comment]
@JedMeister I attempted to use /etc/turnkey_version to determine APPNAME during both build and firstboot.  It turns out that /etc/turnkey_version has not been initialized until the end of common/mk/turnkey.mk while HOSTNAME is set at the beginning.  This is probably why HOSTNAME was used to initialize APPNAME in the first place.  FWIW, it derives the HOSTNAME from the base of the directory it is building from, so it shouldn't be a problem unless turnkey.mk is ever changed.

**Comment by JedMeister** [comment]
Ok cool. So APPNAME=$HOSTNAME at build time is safe (for now at least). But we should avoid that post build.

**Comment by JedMeister** [comment]
Your first point (regarding the rails inithook)  relates to all rails based apps (hence why I added them to this issue). It is pending the merge of the PR but will be included in v14.1.

Your second point (about adding assets to be pre-compiled) relates only to the Rails appliance so I split that off into a separate issue - which I have just fixed).

**Comment by JedMeister** [comment]
Unfortunately this didn't make it into v14.1; but will be included in v14.2.

**Comment by l-arnold** [comment]
I don't feel this will work in Setting a SSL Cert, but do note that in getting Apache to work "Flexibly"  I have recollection of using the term "SERVER_NAME"  rather than Host_Name.  This  allows the system to work on two sides of a Firewall, with an IP number and with a DNS HostName.

I believe I used this in making a "responsive" webconsole that allowed navigation to different Port Settings.  Somewhat of a ConfConsole but w/ hot links.

**Comment by JedMeister** [comment]
@l-arnold I think you may have accidentally posted in the wrong place?
