### ISSUE TITLE
appliances ship with a broken version of open-vm-tools (vmdk/ova release only)

### ISSUE THREAD

**Issue by dominique120** [turnkeylinux/tracker#595]
I suppose this is more a problem of Debian "stable" but since we are building custom distros we could include a newer version of the package.

The issue is that the vmghfs driver in the current version of open-vm-tools is broken so shared folders do not work.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800322

To reproduce: Its broken right out of the box with torrent server 14.1 vmdk.

This is a suggestion only if it is not possible or not feasible then just close this issue. The easiest solution would be to install VMWare tools instead of using open vm tools.

**Comment by JedMeister** [comment]
Thanks for the heads up. I'll need to investigate further but appreciate the bug report and we will definitely aim to fix it; although probably not for v14.1 at this late stage (I hope to have the new v14.1 builds finalised this week).

**Comment by dominique120** [comment]
You could just wait for the people from Debian to move the updated package to their stable branch. At the moment its available on sid.

For the moment I've just switched to using VMWare Tools that comes with workstation and the normal iso. 

You could notify users that vmghfs is not working on the vmdk/ova release and recomend that if they need it they should install vmware tools and go through the standard compiling process to get it to work. I know it works because I just finished testing it.

Uninstalling open-vm-tools and installing VMWare tools does not work because the its(the driver) a kernel module or something that I dont really know about.

**Comment by JedMeister** [comment]
I'm not sure if it will get the the stable branch (Jessie), often bug fixes take a long time to get into stable (if ever) and it's generally rare for a new version to make it into the stable main repo. However,  I imagine that as soon as it gets into Stretch (testing) then it will be back ported (to jessie-backports) fairly soon after. 

When it gets to that point we'll look into the best course of action. In the meantime I will make a note of the bug and your proposed workaround when we do the v14.1 release announcement.
