### ISSUE TITLE
GitLab - nginx not serving gitlab

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#602]
As reported by @kstaniek the GitLab appliance is broken.

The result is a "502 bad gateway" error on what should be the gitlab page.

The nginix gitlab site error log includes this:
````
2016/04/01 00:48:05 [crit] 2874#0: *1 connect() to unix:/home/git/gitlab/tmp/sockets/gitlab.socket failed (13: Permission denied) while connecting to upstream, client: 192.168.1.90, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/", host: "192.168.1.106"
````

Giving 'other' write access (i.e. chmod o+w) gives the desired result but is probably not the ideal way of doing it...

**Comment by JedMeister** [comment]
@kstaniek the workaround you posted on the other issue will only work until reboot (and will then need to be redone). We will fix the image ASAP, but in the meantime here is a workaround that should work consitently:
````
sed -i '/gitlab.socket/ s/$/, :umask => 007/' unicorn.rb
usermod -a -G git www-data
service gitlab restart
service nginx restart
````

The you should be all good to go...

**Comment by qrntz** [comment]
The persistent fix would be:

    setfacl -m default:user:www-data:rwx /home/git/gitlab/tmp/sockets
    service gitlab restart

**Comment by JedMeister** [comment]
Awesome! :+1: Thanks @qrntz :smile:
