### ISSUE TITLE
Monit configuration broken

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#603]
We're in the process of evaluating all the features of the TKL images.
In the 14.1 images, there is a default monit config file, which includes all files from directory /etc/monit/conf.d, and the TKL monit config scripts are in /etc/monit/monitrc.d. Hence, monit does nothing.
Also, if I move them, I get an error 
`monit/etc/monit/conf.d/system:4: syntax error 'cpu'`
What is the status of the monit integration?

**Comment by JedMeister** [comment]
Hmmm, thanks for the report. We''l investigate and see what is going on there...

**Comment by JedMeister** [comment]
@qrntz - please add this one to your todo list...

**Comment by qrntz** [comment]
Already did. :+1:

**Comment by qrntz** [comment]
Upstream changed the config format, should be fixed now.

The scope of monitoring is intentionally left basic as we have yet to discuss to which extent Monit will be integrated into v14.2 images.
