### ISSUE TITLE
Django SECRET_KEY set too loosely by firstboot script.

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#604]
Django SECRET_KEY is set to 2 concatenated mcookie outputs which are actually md5 hex digests of /dev/urandom or /dev/random data. Which means SECRET_KEYs as set by firstboot script will always be 64 characters of 16 possible values. Ideally we should be setting these values to a random string of a-zA-Z0-9 and punctuation.
##

**Comment by JedMeister** [comment]
Thanks for reporting this. Whilst it could be argued that this is a feature request; I have labelled it as a bug...

**Comment by JedMeister** [comment]
After a brief (offline) discussion I have decided to downgrade this to a "feature".

**Comment by JedMeister** [comment]
@spaghettimaster - seeing as you worked on the Django app, do you want to have a crack at this one? If not, that's ok, but perhaps let's move it to the v15.1 milestone?!

**Comment by spaghettimaster** [comment]
Hey @JedMeister, 
[PR](https://github.com/turnkeylinux-apps/django/pull/12)
I used A-Za-z0-9 + [Password special characters](https://www.owasp.org/index.php/Password_special_characters)

**Comment by JedMeister** [comment]
Great work, thanks @spaghettimaster - merged :smile:
