### ISSUE TITLE
Use of single quotes in Turnkey Apache credit conflicts with javascript Moodle plugin

### ISSUE THREAD

**Issue by leeand00** [turnkeylinux/tracker#607]
Explicitly conflicts with Configurable Reports 2.3.9

When the footer
`
<div id='turnkey-credit'> <div> <a href='http://www.turnkeylinux.org/moodle'>Moodle Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a> </div>`

is tacked on to the bottom of every page in Turnkey Linux it causes the printDiv function to fail when printing reports from Configurable Reports.

That said it can be fixed in the following manner:

1. In the configurable reports plugin, you can edit configurable_reports/locallib.php
1. Search for the printDiv Javascript function.
1. On the line that reads tmpw.document.write('&lt;/body&gt;&lt;/html&gt;'); change the single quotes to double quotes.

Or you guys could just change your footer, wasn't sure where to note that exactly, but I imagine the footer is in the database somewhere as a grep of the moodle folder didn't yield a result.

[See the issue also posted here](https://tracker.moodle.org/browse/CONTRIB-6237)

**Comment by JedMeister** [comment]
Thanks for the bug report and the workaround.

Out of interest, is the configurable reports plugin included in a default Moodle install (i.e. is it already in the TurnKey appliance) or is it an add-on that you installed? 

I ask as it would be relatively easy for us to patch it when we build the appliance if it's already pre-installed. If not then it's not so easy for us to do anything about I don't think (unless we start including it by default).

We use Apache's mod substitute to provide the TurnKey footer so I'm not sure how easy that would be to tweak' but we can certainly look into it...

**Comment by leeand00** [comment]
I don't believe it's pre-installed, I had to install it myself as a plugin; but if this one is having issues with it, it sort of makes me wonder about other plugins.

Thanks for showing me where that is getting added to the page!  I didn't think of Apache having a mod in there.

Well it looks like that's second reference is just a bash script, [and you can escape the double quote in bash using \"](http://stackoverflow.com/a/3834857/18149) so it shouldn't be too hard to fix, so long as mod_substitute is okay with the result...it too might require some more escaping depending on the regex engine.

**Comment by leeand00** [comment]
Trying to [find out](http://webmasters.stackexchange.com/questions/92466/what-regex-engine-does-mod-substitute-use) before taking further action.

**Comment by JedMeister** [comment]
Yes you are right; the second reference is the bash script which is executed at build time (i.e. when we build the appliances). It configures the mod_substitute credit. As all our build conf scripts are designed to run within a chroot, they should run fine within an appliance (for testing).

From the research that you initiated I'd strongly suspect that if we replaced all of the `'` with `\"` then it would fix this... We'll have to give a test and see...
