### ISSUE TITLE
Appliance pages should have link to relevant GitHub tracker issues

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#609]
Each individual appliance page should have a link to the relevant issues here on the tracker.

As it doesn't seem possible to return issues using an OR operator we'll need to also note that users should check core's issues as well.

As issues are closed as code is committed, the link should be to the **next** milestone (e.g. we just released v14.1 so the link should point to v14.2 milestone) and it should also contain all of the issues (both open and closed).

For an example here is a link to all the issues for TKLDev for the v14.2 milestone:
https://github.com/turnkeylinux/tracker/issues?q=is%3Aissue+label%3Atkldev+milestone%3A14.2

**Comment by lirazsiri** [comment]
I really like this and it's not hard to implement:

1) find the best place for it on the app page
2) tweaking the template to link to github label by codename:

https://github.com/turnkeylinux/tracker/labels/core
https://github.com/turnkeylinux/tracker/labels/mediawiki

That's it.

**Comment by JedMeister** [comment]
closing as it's been implemented.
