### ISSUE TITLE
Mediawiki not sending emails

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#612]
Looks like a bug from way back has slipped through without being properly noted (and therefore fixed) in the Mediawiki appliance and it's ability to send emails...

For starters it appears that there is a missing dependency (php-pear) but it looks like there may be additional issues. See [this](https://www.turnkeylinux.org/forum/support/20140925/mediawiki-appliance-pear-mail-package-not-installed-error) thread; specifically this](https://www.turnkeylinux.org/forum/support/20140925/mediawiki-appliance-pear-mail-package-not-installed-error#comment-25443) comment. It relates to the v13.0 release but I imagine that it

**Comment by OnGle** [comment]
Tested this on 14.1, I didn't test postfix sending email but I had no issue passing the mail to the postfix queue even without php-pear

**Comment by JedMeister** [comment]
Ok thanks @OnGle. It looks like this may have been a v13.x issue that does not exist in v14.x.

My suspicion is that the users were trying to configure a remote SMTP relay (rather than using the built in postfix) and perhaps that's when php-pear is required? As it is preferable to use postfix to send email (so other server components beyond MediWiki can also send emails) I think it is best left as is. Apologies on giving you the run around, but thanks for testing.

I'll close for now. If anyone else is having this issue (in v14.0 or later) please reopen and we'll dig a little deeper.

**Comment by OnGle** [comment]
I just uninstalled postfix from a mediawiki appliance that has not had php-pear installed on it nor any smtp config set. When attempting to send an email it errors that "sendmail" does not exist which seems to demonstrate that while mediawiki requires php-pear net_SMTP for setting up relays it will fall back on sendmail which is configured to work with postfix which can in turn be used to set up relays without explicit smtp config for mediawiki. I believe that maintaining a common way to configure smtp accross all tkl appliances is the best way to do this and although it may be a little confusing for some people, this seems the most appropriate imo.

**Comment by JedMeister** [comment]
Awesome thanks for clarifying that! :+1:
