### ISSUE TITLE
Adminer is very "unresponsive"

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#619]
Using Adminer is painful in comparison to Phpmysql.  It seems to "timeout" without giving any ability to move except for "Page Refresh".

Seems this may have something to do with the SSL cert being "uncertified" though I am not sure.  Basically if the session has been open for a while, at least for me, Chrome wants to reaffirm you want to use an unsecure cert.

That said, there is a basic lack of Navigation intuition in Adminer.  One can navigate "in" to a database.  (particularly if you choose "select data" once you have selected a table you want to browse).  

The only way "out" is to select the "magento" or larger database name in the topline breadcrumb.  If the session is "timed out" however this does not work, nor does it return any feedback.

I would recomend that there be a "one click" install of more dedicated Database Interfaces.  I could see this being built into WebMin or ConfConsole.

All for now.  Mostly an opinion here, but noticed last night and again this AM these issues.

**Comment by l-arnold** [comment]
Version Jessie, Magento Appliance at this particular juncture.

The one advantage to Adminer is that it seems to "put out there" SQL dialect.  

Would be nice to know how to build some "customized views" and attach to Adminer (or other inteface) somehow.  Magento's 445 Tables, for example, is a bit overwhelming.  Doing that right now via ODBC and FileMaker Pro.

**Comment by JedMeister** [comment]
> Using Adminer is painful in comparison to Phpmysql. It seems to "timeout" without giving any ability to move except for "Page Refresh".

Are you using a current version of PHPMyAdmin alongside Adminer? A current version of PHPMyAdmin should do it too! It's a security feature! :wink: It's so if you leave your computer unattended but logged in it won't stay logged in indefinitely. There are also measures to stop cross-site scripting ([XSS](https://en.wikipedia.org/wiki/Cross-site_scripting)) and cross-site request forgery ([CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery)) attacks which might also make use of Adminer a bit of a pain at times; but like most anti-hacker measures the pain is probably a better alternative.

Also something to keep in mind, we are using a really old version of Adminer. I have already taken steps to assist Debian to get a newer version into the repos, but I haven't had time to get back to it. Once we have that sorted updating it should be fairly easy.

Regardless, as you may recall, there was a bug in PHPMyAdmin that meant that we couldn't use it for v14.x. If you'd like to install it yourself you can, but it can only be hosted on port 443.

For the sort of work you are trying to do, perhaps you would be better off using a proper desktop DB manager? The web interface DB managers whilst really handy, IMO they aren't really intended for "serious" DB work. Sounds like you are trying the desktop option with "Filemaker Pro", but I'm sure that there are many of other options if that doesn't work out for you.

**Comment by JedMeister** [comment]
PS, I'm not really sure whether this should be labelled as a bug or a feature? It's not really clear to me. So I'll just leave it as is for now...

**Comment by l-arnold** [comment]
Where I use it normally is to go in and modify something that the main Magento won't allow.  Turning a "simple product" into a "configurable" one or giving a product a different "attribute set" which exposes a different set of table values which the main program wants to track, So small changes.

A paid program, "Navicat" is quite good.  FileMaker is nice in that it allows you to program different input and display views that are repeatable and modifiable.

It all works together in the end once the proper settings are established.  Adminer, etc, are for quick and dirty, forget the settings, do a small review or change right now.

You are correct that starting a new session is likely best after a period of time.  New Browser window even.  This probably belongs in the forums.

**Comment by l-arnold** [comment]
"Feature" rather than a "bug" per say (having a alternative manager that is).  Technically there is Webmin and Adminer as alternative managers right now.  So would be for a third.  

If you know how to navigate Shell, can likely do quite a bit there as well.  I don't do data in the shell though.

**Comment by l-arnold** [comment]
Crazy you couldn't use PHPmysql on any port other than 443.  Makes no sense.  I didn't realize that is what drove the decision.  I thought it was just simplifying the code base.

No matter.

**Comment by JedMeister** [comment]
Thanks for the clarification @l-arnold. Adminer had been suggested/requested (as a lightweight alternative to PHPMySQL) some time ago and when the issue with PHPMySQL was discovered in v14.0 that was the main motivation to implement including that...

**Comment by l-arnold** [comment]
Complicates things bit the concept of easy addons yo app builds is part of this,  whethet a diff data base mamager or a multiple app hosting method, all seem somewhat usable and desieable for some. 

No big right this minute.

**Comment by l-arnold** [comment]
Complicates things bit the concept of easy addons yo app builds is part of this,  whethet a diff data base mamager or a multiple app hosting method, all seem somewhat usable and desieable for some. 

No big right this minute.
