### ISSUE TITLE
Feature Request TKLDev: Add ability to install patches during appliance build 

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#623]
TKLpatch had the ability to apply patches through the tklpatch-apply command.  I was disappointed to find that this capability was not included in TKLDev.  Several times I have wanted to be able to apply a patch (usually an upstream fix) during an appliance build.
##

**Comment by JedMeister** [comment]
Thanks John. FWIW TKLPatch is in the repos and has been updated for use with v14.x. It installs fine on TKLDev and then works as expected.
````
apt-get update
apt-get install tklpatch
````

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux/fab/pull/2
