### ISSUE TITLE
Admin password to login phplist-14.0 on docker

### ISSUE THREAD

**Issue by quangvi282** [turnkeylinux/tracker#625]
how to know username , password to login phplist 14 on docker
does it have default ?

**Comment by JedMeister** [comment]
All the appliances have their own page which details all the relevant info. So in the case of PHPList it's https://www.turnkeylinux.org/phplist

You need to set the password yourself by initializing the appliance. You can either do that interactively; or you can pressed the values. Have a look at the initial blog post announcement: https://www.turnkeylinux.org/blog/14.0-optimized-builds-pt2-proxmox-opennode-docker (dated but still relevant). Or the more recent v14.0 Docker build announcement: https://www.turnkeylinux.org/blog/announcing-docker-builds
