### ISSUE TITLE
Rails & Redmine appliances document use of Ruby Enterprise

### ISSUE THREAD

**Issue by paul-calvelage** [turnkeylinux/tracker#632]
The documentation for the Rails and Redmine appliances claims (wrongly) that Ruby Enterprise is being used:

- **Rails:** "Uses Ruby Enterprise for improved performance and memory utilization."
  - https://www.turnkeylinux.org/rails
  - https://github.com/turnkeylinux-apps/rails/blob/master/README.rst
- **Redmine:** "Uses Ruby Enterprise (performance)."
  - https://www.turnkeylinux.org/redmine
  - https://github.com/turnkeylinux-apps/redmine/blob/master/README.rst

In fact, the switch was made away from Ruby Enterprise to the stock Ruby from Debian in the Oct. 28, 2013 release (TurnKey Rails & Redmine version 13.0).  See https://github.com/turnkeylinux/tracker/issues/102 and https://github.com/turnkeylinux/common/commit/6324f6db5bd946ae8bc1bdf97cbbb4455800045e, which show how `ruby-enterprise` was dropped in favor of `ruby` and `ruby-dev`.

This change was announced with the updates, even though it is not shown in the `README.rst` and website description for the appliances.
- **Updates:** "Replaced ruby-enterprise with stock ruby from Debian [#102]."
  - https://www.turnkeylinux.org/updates/rails/new-turnkey-rails-version-130
  - https://www.turnkeylinux.org/updates/redmine/new-turnkey-redmine-version-130

**Comment by JedMeister** [comment]
Ooops! :blush: Thanks for the heads up Paul! We'll need to fix that!

**Comment by JedMeister** [comment]
Now fixed :smile:
