### ISSUE TITLE
Getting an error message when selecting PNG off the gantt page

### ISSUE THREAD

**Issue by liquiz** [turnkeylinux/tracker#633]
Started GET "/projects/planned-projects/issues/gantt.png?month=5&months=6&year=2016&zoom=3" for 10.30.21.220 at 2016-05-10 12:01:22 +0000
Processing by GanttsController#show as PNG
  Parameters: {"month"=>"5", "months"=>"6", "year"=>"2016", "zoom"=>"3", "project_id"=>"planned-projects"}
  Current user: liquiz (id=1)
Completed 500 Internal Server Error in 360ms (ActiveRecord: 27.9ms)

Magick::ImageMagickError (unable to read font `' @ error/annotate.c/RenderFreetype/1127: `(null)'):
  lib/redmine/helpers/gantt.rb:436:in `draw'
  lib/redmine/helpers/gantt.rb:436:in `to_image'
  app/controllers/gantts_controller.rb:44:in `block (2 levels) in show'
  app/controllers/gantts_controller.rb:42:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

As best as I cant tell some of the solutions for fixing this deal with re-compiling imagemagick and making sure the gs font directly is correctly specified. http://stackoverflow.com/questions/1014506/imagemagickerror-unable-to-read-font-null-null

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  no plugin installed

**Comment by JedMeister** [comment]
I'm guessing that this is our Redmine appliance? If so, which version specifically?
````
turnkey-version
````
If you're not using the TurnKey appliance then you've posted in the wrong place. :smile:

**Comment by liquiz** [comment]
root@redmine ~# turnkey-version 
turnkey-redmine-14.1-jessie-amd64

I was surprised when I actually found the right place to post it to ... My week has just been like that  :)

**Comment by JedMeister** [comment]
Well you found it! :smile: 

Thanks for the bug report and the clarification.

TBH I don't know when we'll get a chance to have a look at this. I haven't yet had time to even have a proper read of you link (although I did give it a quick scan). FWIW we use the Debian Jessie package of ImageMagic. So I'd assume that the best/easiest way to recompile it is to use the Debian source package as a base.

**Comment by liquiz** [comment]
I do computer QA work for a living so chasing odd and unusual is something I enjoy.  I enjoy it even more when I find a solution, which in this case I get to share back to the community.

root@redmine share/fonts# apt-get install ghostscript

Turns out a simple solution was indeed the correct one.  What I dont know is if I used a hammer to fix it or if I could have used a flyswatter.  Its completely possible that you could just download and use the font package as well.  So when you get to duplicating the issue you can fine tune the fix and roll that into an update for the redmine image.

**Comment by JedMeister** [comment]
Nice! Thanks for the workaround! You rock! :smile:

**Comment by qrntz** [comment]
Sorry that took a while. Indeed just the GhostScript fonts package was enough to fix the issue.
