### ISSUE TITLE
Auto generated appliance pages suggest Adminer is installed in some apps, but it's not 

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#634]
...in (at least) Django, Rails, Redmine.

**Comment by JedMeister** [comment]
Thanks for the heads up on this. 

Initially I thought you were mistaken. As if you look at the appliance readmes (e.g. [Django](https://github.com/turnkeylinux-apps/django/blob/master/README.rst)) they do not mention Adminer at all. However when you look at the appliance page (e.g. [Django](https://www.turnkeylinux.org/django)) under the screenshots it clearly does note "Adminer database management " info. FWIW the appliance pages are automagically created from the Appliance Readme so it's a bug in our script that creates the appliance pages.

**Comment by JedMeister** [comment]
I've manually fixed the website pages, but I'll leave this issue open for now as a reminder to fix the appliance page build script.

**Comment by JedMeister** [comment]
I'll investigate this one shortly and close by the time we have completed v14.2.

**Comment by JedMeister** [comment]
Finally fixed these on the website...
