### ISSUE TITLE
Appliances need relevant and up to date screenshots (in .art in each repo)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#639]
All appliances need to be checked to make sure they have at least 3 up to date (<~1yr) screenshots in their `.art` directory. E.g. [mediaserver](https://github.com/turnkeylinux-apps/mediaserver/tree/master/.art). I have only tagged this issue 'core' because I couldn't be bothered tagging every single app!

So far a few are definitely done (I've ticked them below). I expect that most of the rest will need at least one new screenshot, some may need 3.

The screenshots need to be to [spec](https://github.com/turnkeylinux/artwork#appliance-screenshots). You can find a tutorial on how to take good screenshots [here](https://github.com/JedMeister/artwork/blob/update-docs/docs/screenshots.rst)

It doesn't matter if there are more than 3. If you are unsure of what is best to take a screenshot of, feel free to add 5 or 6 even. Please delete old, out of date screenshots. All new screenshots should be `.png` (as per the specs) but if the repo already has up to date `.jpg`s they don't need to be deleted.

I'll try to keep this tick list up to date but best to double check  If you mention this issue (post the url) when you make your pull request then that will make it easier for others which appliances aren't done.
- [x] asp-net-apache
- [x] b2evolution
- [ ] bambooinvoice
- [x] bugzilla
- [x] cakephp
- [x] canvas
- [x] codeigniter
- [x] collabtive
- [ ] concrete5
- [ ] core
- [x] couchdb
- [x] django
- [x] dokuwiki
- [x] domain-controller
- [x] drupal7
- [x] drupal8
- [x] e107
- [ ] ejabberd
- [ ] elgg
- [x] espocrm
- [ ] etherpad
- [x] ezpublish
- [x] fileserver
- [ ] foodsoft
- [ ] gallery
- [x] ghost
- [x] gitlab
- [x] gnusocial
- [x] icescrum
- [x] jenkins
- [x] joomla3
- [x] lamp
- [ ] lapp
- [x] lighttpd-php-fastcgi
- [x] limesurvey
- [ ] lxc
- [x] magento
- [x] mahara
- [x] mambo
- [x] mattermost
- [x] mediawiki
- [x] mediaserver
- [x] mibew
- [x] moinmoin
- [x] mongodb
- [x] moodle
- [x] mysql
- [x] nginx-php-fastcgi
- [x] nodejs
- [ ] observium
- [ ] odoo
- [x] omeka
- [x] openldap
- [x] openvpn
- [x] orangehrm
- [x] oscommerce
- [x] otrs
- [x] owncloud
- [x] phpbb
- [x] phplist
- [ ] phreebooks
- [x] piwik
- [ ] pligg
- [ ] plone
- [ ] postgresql
- [x] prestashop
- [x] processmaker
- [ ] projectpier
- [x] punbb
- [x] rails
- [x] redmine
- [x] revision-control
- [x] roundup
- [x] sahana-eden
- [x] silverstripe
- [x] simplemachines
- [x] sitracker
- [ ] sugarcrm
- [x] suitecrm
- [x] symfony
- [ ] tendenci
- [ ] tkldev
- [ ] tomatocart
- [x] tomcat
- [x] tomcat-apache
- [x] trac
- [x] tracks
- [ ] twiki
- [x] typo3
- [ ] ushahidi
- [x] vanilla
- [ ] vtiger
- [x] web2py
- [x] wordpress
- [x] xoops
- [x] yiiframework
- [x] zencart
- [x] zurmo

**Comment by lirazsiri** [comment]
LAMP Stack still shows PHPMyAdmin screenshot instead of Adminer. There is no Adminer screenshot. As part of this update we need to replace every reference to PHPMyAdmin with Adminer.

**Comment by JedMeister** [comment]
Thanks Liraz, yes you are right...

**Comment by JedMeister** [comment]
This should be pretty much up to date now so closing...
