### ISSUE TITLE
Nodejs init script clash

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#642]
We're having trouble with the NodeJS image. There is an init script `/etc/init.d/pm2-init.sh` and a systemd service `/etc/systemd/system/pm2.service`. Both provide `pm2`. The result is, interestingly, that pm2 is not running after restart and nginx is throwing 502 Bad Gateway.

If you delete one and reboot, or the other and reboot, pm2 starts up.

It comes from `common/conf/nodejs`:
```
pm2 startup ubuntu -u $USER
pm2 startup systemd -u $USER
```

**Comment by qrntz** [comment]
Both certainly should not be activated at the same time. The conf should ensure that it works on both SysV and systemd however there might have been some upstream change in ```pm2 startup``` that leads to both being added to the boot sequence now…

Thanks for reporting. I'll take a look at it.
