### ISSUE TITLE
Mediaserver hangs when booting after changing the root password

### ISSUE THREAD

**Issue by martinjh99** [turnkeylinux/tracker#651]
When installing the TKL Mediaserver appliance from the downloaded OVA file in the latest Virtualbox the appliance boots fine but after asking for the new root password it hangs in the following file:

`firstboot.d/50emby-server`

Nothing happens even after leaving the appliance for a while and increasing the memory of the virtual machine thinking thats the problem but it isn't...

**Comment by martinjh99** [comment]
Also tried installing the ISO file and that hangs at the same place in the same file...

**Comment by qrntz** [comment]
Thank you for reporting. We will take a look at it.

**Comment by qrntz** [comment]
That should fix it, but I could not reproduce the issue consistently — looks like it may depend on the hardware after all.
