### ISSUE TITLE
Mantis configuration file location

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#653]
The docs say it is `/etc/mantis/config_inc.php`, but really it is `/var/www/mantis/config_inc.php`.

**Comment by JedMeister** [comment]
Great catch! FWIW prior to v14.x we used the Debian packaged version (hence the /etc/mantis reference). We should update the docs, but IMO a symlink linking /etc/mantis/config_inc.php to /var/www/mantis/config_inc.php might also be handy. I know /etc is often the first place I look for config files...
