### ISSUE TITLE
Inithooks variables documentation needs updating

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#654]
The page https://www.turnkeylinux.org/docs/inithooks omits e.g. that Prestashop needs the APP_DOMAIN variable and OpenVPN has four special variables.

**Comment by JedMeister** [comment]
Thanks Tomas. FWIW the original doc (which is the source of the page you link to) is the README for the inithooks package: https://github.com/turnkeylinux/inithooks/blob/master/README.rst

**Comment by JedMeister** [comment]
I'm closing this now as the inithooks readme (#744) was updated a week ago. I've just updated the website now too.
