### ISSUE TITLE
Observium – Mail From Address not as Configured

### ISSUE THREAD

**Issue by w3p706** [turnkeylinux/tracker#655]
In standard configuration, mail will always be sent with <root@HOSTNAME>.

If we change the email backend to sendmail/postfix with the following configuration:
```
$config['email']['backend']       = "sendmail";
$config['email']['sendmail_path'] = "/usr/sbin/sendmail -t -i";
```

The from-address will be taken from the following setting (if set)
`$config['email']['from']           = 'Observium <observium@YOURDOMAIN.COM>';`

Is this correct? Could that be included in the configuration for the appliance?

**Comment by JedMeister** [comment]
Just for clarity I'm assuming that you are specifically referring to the [Observium appliance](https://www.turnkeylinux.org/observium)?

**Comment by w3p706** [comment]
Yes, with the turnkey observium appliance email works out of the box, except the above issue that will prevent sending of mail for some picky smtp-servers which rejects from addresses without a dot after the @.

**Comment by JedMeister** [comment]
No problem. Thanks for your report and your suggestion sounds like a nice improvement! :smile:
