### ISSUE TITLE
Redmine 14.1 svn create

### ISSUE THREAD

**Issue by rainer28** [turnkeylinux/tracker#656]
Why to create a svn repo as default?
This is not always the right flow.

Why not move this to repository creation: Create default button, after svn, git, ... is selected and known.

**Comment by JedMeister** [comment]
Sorry I'm not quite clear on what you are suggesting? Also I'm not quite clear on whether you are referring to the Redmine software itself or something that we have pre-configured. To be clear we do not produce or tweak the Redmine software itself, we just install it and pre-configure it. With regard to the repos that the Redmine appliance comes with, these are simply example repos and there is an example for each supported VC.

**Comment by JedMeister** [comment]
I'm closing this due to lack of feedback/response. @rainer28 if you'd like to add more info then we can reopen it if it is relevant to TurnKey...
