### ISSUE TITLE
Wrong IP adr. in Domain-controller example

### ISSUE THREAD

**Issue by rlsson** [turnkeylinux/tracker#661]
At: https://www.turnkeylinux.org/domain-controller

The IP adr. 12.34.56.789 is used as an example.
This is unfortunate because 789 is an invalid number, can only be between 0-255.

and the IP should also be within an RFC-1918 IP adr. space.

/Mats

**Comment by JedMeister** [comment]
The example IP is explicitly given as an invalid IP because it is only an example. You need to substitute the example IP for the IP of your instance. The only other option would be to use `xxx.xxx.xxx.xxx` which is obviously also not valid IP...
