### ISSUE TITLE
Reports that OpenVPN is broken OOTB

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#669]
There have been a couple of recent reports ([here](https://www.turnkeylinux.org/forum/support/20140918/convert-openvpn-udp-tcp#comment-26185) and [here](https://www.turnkeylinux.org/forum/support/20160707/no-dns-turnkey-opendns-image)) that the latest version of OpenVPN is not working. TBH I'm not sure if these 2 issues are related or not. 

We will need to investigate and confirm if that is the case (and obviously fix it if it is broken).

**Comment by qrntz** [comment]
It does not seem like a problem with our OpenVPN appliance. I could replicate neither issue (and the first user is not using v14.1).

**Comment by JedMeister** [comment]
Ok thanks Anton. I'll shut this for now then.
