### ISSUE TITLE
[Request new appliance] Gogs

### ISSUE THREAD

**Issue by Darcidride** [turnkeylinux/tracker#677]
Hi,

First, sorry if I post this on the wrong place, I didn't see anything about a "request" section on your website & forum (https://www.turnkeylinux.org/)

Well, my request is about add a Gogs LXC image.
Gogs is a Lightweight, Open Source Git platform based on the language "Go".
![gogs_logo](http://i.imgur.com/nVLCbtB.png)

This tool is lightness than Gitlab and the user experience is really simple compared to Gitlab. (Gogs seems more like Github if we compare the web GUI)

Finally, the main problem with Gitlab is its memory consuption, really anoying, **up to 2/3/4GB easily** because of unicorn... view this issue, for example => https://github.com/gitlabhq/gitlabhq/issues/903#issuecomment-235827497

Official Gogs website : https://gogs.io/
Demo here : https://try.gogs.io/
Already available on Docker : https://github.com/gogits/gogs/tree/master/docker
Installation from package can be find here : https://gogs.io/docs/installation/install_from_packages.html

Thank you in advance,

**Comment by JedMeister** [comment]
Hi @Darcidride here is just as good a place as anywhere! :smile: 

I've changed the title as all the alternate builds are actually built from the ISO. So once we have an ISO build then we convert that to all the other build formats (including LXC).

Regardless, Gogs looks like a pretty cool thing and it'd be great to add it. Having said that we don't have a ton of spare resources so if you (or anyone else) want to have a go at it; I'm happy to give you as much support and guidance as I can.

**Comment by Darcidride** [comment]
If this links are up-to-date :
- https://www.turnkeylinux.org/docs/howto-build-isos-with-tkldev
- https://www.turnkeylinux.org/docs/tkldev-new-appliance

I think i can do it, i just need to dig more the docs and try it :)

I will ask here if i need help

**Comment by JedMeister** [comment]
PS to clarify; IMO this thread is yours so please feel free to post whatever/whenever here and I will try to respond ASAP. If I don't respond within one working day (I'm in Australia so AEST = UTC+10) feel free to ping me direct via email (jeremy at turnkeylinux.org) to give me a nudge! :smile:

**Comment by JedMeister** [comment]
I'm going to close this, as we have now added Gitea (a fork of Gogs).

For further info and download links, please see the Gitea appliance page:
https://www.turnkeylinux.org/gitea

Also FWIW, the (now closed) issue:
https://github.com/turnkeylinux/tracker/issues/1049

The buildcode:
https://github.com/turnkeylinux-apps/gitea

If you think that the Gitea applaince is missing something important and/or you'd still really like to specifically see a Gogs appliance, then feel free to reopen this issue.
