### ISSUE TITLE
etherpad service is not started at boot time

### ISSUE THREAD

**Issue by oupala** [turnkeylinux/tracker#684]
I'm trying etherpad v14.1, ova version (turnkey-etherpad-14.1-jessie-amd64).

The vm starts well, but etherpad is not started, resulting in a:

> 502 Bad Gateway nginx/1.6.2

etherpad and nodejs are not registered as known services so it is hard to find how to start etherpad.

When starting etherpad manually with the following command:

`/opt/etherpad-lite/bin/run.sh`

etherpad becomes available.

It looks like etherpad and nodejs have not been integrated to the system. Or I may have understood everything wrong...

But I think that etherpad should be automatically started at boot time.

**Comment by JedMeister** [comment]
It should "just work". I'll have to investigate further. Thanks tons for posting.

**Comment by JedMeister** [comment]
This has been investigated and the issue confirmed. It appears to be a problem with PM2. Requires further investiagtion. Perhaps when you have time @qrntz ?

**Comment by oupala** [comment]
Thanks for confirming the bug. Can you tell me what is **PM2**?

I'm astonished to be the first one to report this simple problem. Am I the only one willing to use etherpad turnkey?

**Comment by JedMeister** [comment]
[PM2](http://pm2.keymetrics.io/) is a commonly used NodeJS process manager. I haven't had time to investigate in detail (and NodeJS is not my area of expertise) but as you surmised, what seems to be happening is that the Etherpad process isn't starting as it should. 

Generally in Debian an init (short for initialisation) system starts all the daemons (equivalent to Windows' "services"). We could have written a "normal" initscript for Etherpad, but as we have adopted PM2 for all NodeJS based appliances, we stuck with that.

So what is meant to happen is that the "normal" init system starts the PM2 daemon. PM2 then starts the relevant NodeJS processes (Etherpad in this case).

TBH I'm surprised that no one else has picked this up yet either. It may be a case of no one else has bothered to post an issue (and just ditched the appliance), or it could be that something that has happened more recently has broken something. IIRC I did basic testing using an LXC container so perhaps they work fine on that base?

As a workaround you could try implementing the SystemD (init service for v14.x OVA based appliances) instructions as documented [here](https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service#debian-8-jessie--systemd). Although I'm not sure how that will go as there should already be a relevant user account and PM2 will still probably be running which may possibly cause some issues? I wouldn't use it anywhere mission critical until you have done some solid testing.

**Comment by l-arnold** [comment]
Ibhave not dugested this, but we previously discussed having etherpad install tovthe odoo appliance and perhaps now there woukd be understanding of how to so.
Odioo supports "Colaborative pads" in swveral modules and references etherpad as a prefered mechanism.

**Comment by l-arnold** [comment]
Will "de-thumb" edit last comment when I get to a laptop.

**Comment by oupala** [comment]
When will this fix be available in turnkey etherpad?

**Comment by JedMeister** [comment]
We'll be rebuilding it sometime soon but I'm not 100% sure exactly when. In the meantime you can apply the workaround that we use on the buildcode; directly to your server. Like this:

````
su - node
cd /opt
pm2 start etherpad-lite
pm2 dump
exit
chattr +i /home/node/.pm2/dump.pm2
service pm2-init.sh restart
service nginx restart
````
When you execute these commands it should look something like this:
````
root@etherpad ~# su - node
node@etherpad:~$ cd /opt
node@etherpad:/opt$ pm2 start etherpad-lite
[PM2] Applying action restartProcessId on app [etherpad-lite](ids: 1)
[PM2] [etherpad-lite](1) ✓
[PM2] Process successfully started
┌───────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name      │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├───────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ run           │ 0  │ fork │ 1970 │ online │ 0       │ 23s    │ 95.320 MB   │ disabled │
│ etherpad-lite │ 1  │ fork │ 2612 │ online │ 18      │ 0s     │ 18.422 MB   │ disabled │
└───────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
node@etherpad:/opt$ pm2 dump
[PM2] Saving current process list...
[PM2] Successfully saved in /home/node/.pm2/dump.pm2
node@etherpad:/opt$ exit
logout
root@etherpad ~# chattr +i /home/node/.pm2/dump.pm2
root@etherpad ~# service pm2-init.sh restart
Restarting pm2
[PM2] Applying action deleteProcessId on app [all](ids: 0,1)
[PM2] [run](0) ✓
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
Starting pm2
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Resurrecting
[PM2] Restoring processes located in /home/node/.pm2/dump.pm2
[PM2] Process /opt/etherpad-lite/bin/run.sh restored
[PM2] Process /opt/etherpad-lite restored
┌───────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name      │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├───────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ run           │ 0  │ fork │ 2907 │ online │ 0       │ 0s     │ 2.543 MB    │ disabled │
│ etherpad-lite │ 1  │ fork │ 2922 │ online │ 0       │ 0s     │ 20.367 MB   │ disabled │
└───────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
root@etherpad ~# service nginx restart
[ ok ] Restarting nginx: nginx.
````
Then Ehterpad should be working and should auto start on reboot.

**Comment by JedMeister** [comment]
Also FWIW the bug is in PM2. It appears to be caused by a [race condition](https://en.wikipedia.org/wiki/Race_condition) which means it won't effect everyone, everytime. Although as we've discovered in some configurations (yours and mine) it seems to happen pretty consistently! I assume that is why no one else has complained about it previously. 

The PM2 bug means that sometimes when PM2 shuts down, it overwrites it's process start up info (with nothing). If this happens, when PM2 restarts it doesn't know to start the Etherpad app.

Our workaround adds Etherpad to PM2's start up info, then sets the "immutable" property (`-i`) on the PM2 dump file (`/home/node/.pm2/dump.pm2`). When a file becomes immutable it can not be deleted or overwritten so Etherpad should start every time!.

**Comment by oupala** [comment]
Thanks for all the explanations.

I tested the workaround, and in my case it doesn't work. I still get the **502 Bad Gateway** error.

As far as I understand your release system, I'll have to wait for the 14.2 [release of turnkey etherpad](https://www.turnkeylinux.org/etherpad). Am I right?

**Comment by JedMeister** [comment]
Hmm, that's weird. You are using v14.1 right? Which part didn't work for you? If you compare to the results I posted above, which part of yours looked different and what was the error or difference from your output?

**Comment by oupala** [comment]
I'm using this file in VirtualBox : turnkey-etherpad-14.1-jessie-amd64.ova. So I started from a 14.1 release, but not from the ISO. I used the OVA file that can be directly imported into VirtualBox.

I deleted my previous VM so that I can replay all the commands. Here is the console log:

```bash
root@etherpad ~# su - node
node@etherpad:~$ cd /opt/
node@etherpad:/opt$ pm2 start etherpad-lite
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Starting etherpad-lite in fork_mode (1 instance)
[PM2] Done.
┌───────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name      │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├───────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ etherpad-lite │ 0  │ fork │ 4743 │ online │ 0       │ 0s     │ 19.633 MB   │ disabled │
└───────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
node@etherpad:/opt$ pm2 dump
[PM2] Saving current process list...
[PM2] Successfully saved in /home/node/.pm2/dump.pm2
node@etherpad:/opt$ exit
logout
root@etherpad ~# chattr +i /home/node/.pm2/dump.pm2 
root@etherpad ~# service pm2-init.sh restart
root@etherpad ~# service nginx restart
root@etherpad ~#
```

My console is a lot less verbose than yours. And at the end, I still get the **502 Bad Gateway** error.

**Comment by oupala** [comment]
I also tested to create a new VM from the OVA file, but changing the available RAM from 512 (the default) to 1024. And this time etherpad was started at boot time without problem.

The *race condition* is maybe driven by the amount of RAM of the VM...

**Comment by oupala** [comment]
I answer to myself: setting the amount of RAM to 1024 does not guarantee you that etherpad will be started. I just tried again, with 1024 Mo of RAM, and ehterpad is broken (**502 Bad Gateway** error).

**Comment by qrntz** [comment]
Your Etherpad is being terminated by a SIGINT. That is strange. Could you please also provide the output of:
```
lsattr /home/node/.pm2/dump.pm2
```
```
cat /opt/etherpad/run-out-0.log
```

**Comment by oupala** [comment]
Here are the results:

```bash
root@etherpad ~# lsattr /home/node/.pm2/dump.pm2
-------------e-- /home/node/.pm2/dump.pm2
root@etherpad ~# cat /opt/etherpad/run-out-0.log
cat: /opt/etherpad/run-out-0.log: No such file or directory
```

The file was not found, so I added some more commands:

```bash
root@etherpad ~# cat /opt/etherpad-lite/run-out-0.log
cat: /opt/etherpad-lite/run-out-0.log: No such file or directory

root@etherpad log/pm2-node# cat /var/log/pm2-node/run-out-0.log 
5
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2016-04-08 09:44:03.047] [WARN] pluginfw - /opt/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/has-cors requires global@'https://github.com/component/global/archive/v2.0.1.tar.gz' but will load
/opt/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/global,
which is version 2.0.1 unmet dependency
[2016-04-08 09:44:03.058] [WARN] pluginfw - /opt/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/engine.io-client requires xmlhttprequest@'https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz' but will load
/opt/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/xmlhttprequest,
which is version 1.5.0 unmet dependency
5
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
5
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
```

**Comment by qrntz** [comment]
Seems your dump.pm2 does not have the `immutable` attribute. It has to for the fix to work.

The proper lsattr output should look like
```
----i--------e-- /home/node/.pm2/dump.pm2
```

The `i` here means `immutable`; that's what we need.

So it looks like your call to `chattr` did not succeed without apparent error. I'm not sure why that could happen (I can't reproduce this scenario). Perhaps output from the following would help.

```
# chattr -V +i /home/node/.pm2/dump.pm2
# echo $?
# lsattr /home/node/.pm2/dump.pm2
```

The dependency warnings in the log can be ignored.

**Comment by oupala** [comment]
This time, it worked:

```bash
root@etherpad ~# lsattr /home/node/.pm2/dump.pm2
-------------e-- /home/node/.pm2/dump.pm2
root@etherpad ~# chattr -V +i /home/node/.pm2/dump.pm2
chattr 1.42.12 (29-Aug-2014)
Flags of /home/node/.pm2/dump.pm2 set as ----i--------e--
root@etherpad ~# echo $?
0
root@etherpad ~# lsattr /home/node/.pm2/dump.pm2
----i--------e-- /home/node/.pm2/dump.pm2
```

**Comment by qrntz** [comment]
You probably made the empty dump.pm2 (after pm2 has overwritten it) immutable so it still raises an error. Please try the complete [workaround](https://github.com/turnkeylinux/tracker/issues/684#issuecomment-243284309) again and if that doesn't work, do it from a newly created VM.

**Comment by oupala** [comment]
I restarted the vm this morning and etherpad was started. So the workaround seems to work.

Maybe it was necessary to restart the vm. Or maybe the Firefox cache was still displaying an error page while etherpad was started.

Could you please update this issue when etherpad turnkey is rebuilt?

**Comment by qrntz** [comment]
Might also be the case that you needed to restart nginx for the fix to work (which was done with a reboot). Either way, glad it's resolved for you.

Of course we'll update the issue.
