### ISSUE TITLE
Gitlab workhorse not integrated

### ISSUE THREAD

**Issue by XaviTorello** [turnkeylinux/tracker#686]
It seems that gitlab-workhorse does not exist with the current template. The main startup process throw and error every time it's tried to start (see /home/git/gitlab/log/gitlab-workhorse.log)

Can be very interesting to integrate it, currently there are issues interacting with Gitlab through http, i.e an "git clone" through http will return an empty repo (see https://gitlab.com/gitlab-org/gitlab-ce/issues/2669#note_2176671)

### Current workaround

```
# As root install Go (dependency for building gitlab-workhorse)
su -
apt-get install golang

# As user git
su - git

# Ensure correct pwd for tunned configurations
cd /home/git

# Fetch gitlab-workhorse
git clone https://gitlab.com/gitlab-org/gitlab-workhorse.git

# Enter and compile workhorse
cd gitlab-workhorse
make

# Restart Gitlab
/etc/init.d/gitlab restart

# Extend nginx / override current socket at proxy_pass
## It's prefered to handle it through a new upstream, and point the proxy_pass for the desired location to it, but it's on your hands...

# the workhorse sorcket
grep workhorse_opt /etc/init.d/gitlab
# take care about the -listenAddr definition i.e $socket_path/gitlab-workhorse.socket
# this will be the new socket to define on nginx

# in my case I created a new upstream on nginx/sites-enabled/gitlab
upstream gitlab-workhorse {
    server unix:/home/git/gitlab/tmp/sockets/gitlab-workhorse.socket fail_timeout=0;
}

# and creating a new location (regexing .git GETs) on nginx/include/proxy pointing to this upstream
location ~ [-\/\w\.]+\.git\/ {
    ...
    ...
    ...
    proxy_pass http://gitlab-workhorse;
}
```

**Comment by JedMeister** [comment]
Thanks for your report.

**Comment by qrntz** [comment]
Thank you for reporting this (and providing a PR!)

**Comment by JavaMachine** [comment]
Hello fellow developers ( @qrntz @JedMeister @XaviTorello ),

After completing "Workaround",
I am facing another problem:

`remote: Internal server error
fatal: unable to access 'http://git.paynet.local/java/vas_service.git/': The requested URL returned error: 500
Pushing to http://git.paynet.local/java/vas_service.git
`
from access.log I could see that git is trying to access:

`http://git.paynet.local/java/vas_service.git/info/refs?service=git-receive-pack`

Any suggestions "how I can resolve problem?"

Thanks in advance

**Comment by JavaMachine** [comment]
UPD: Googling above last errors gave me folowing solutions for this ([Here](https://gitlab.com/gitlab-org/gitlab-ce/issues/22484) and [Here](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1595))

But I could not find file '/opt/gitlab/embedded/cookbooks/gitlab/templates/default/sv-gitlab-workhorse-run.erb'

Also no success searching "-proxyHeadersTimeout" in all files :(

**Comment by JedMeister** [comment]
I am no GitLab expert, but my guess is that the path `/opt/gitlab/embedded/cookbooks/gitlab/templates/default/sv-gitlab-workhorse-run.erb` relates to installs done with the "omnibus" installer. The TurnKey appliance uses a "source" install so IIRC instead of `/opt/gitlab` the base installation path is `/home/git/gitlab`. 

Having said that I haven't checked or tested, just working from assumptions/memory...

Also, I'm going to open this as a new issue so it doesn't get missed for our next (v14.2) release.

**Comment by JavaMachine** [comment]
I resolved issue by following below instruction:

[https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/8.2-to-8.3.md](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/8.2-to-8.3.md)

NOTE: there is no update info about updating straight from 8.8 to 8.16

So in the above instruction `treat 8.2 as 8.8` and `treat 8.3 as 8.16`

checkout to:
GitLab:  `8-16-stable`
GitLab-shell:  `v4.1.1`
GitLab-workhorse:  `0.7.2`

**Comment by JedMeister** [comment]
Awesome, thanks for the update! :smile:
