### ISSUE TITLE
Can not send alert mail from observium CE version

### ISSUE THREAD

**Issue by engmostafakotb** [turnkeylinux/tracker#690]
Hi,
I installed observium CE version but couldn't send any alert emails  below is the config.php 
you support is highly appreciated 
![image](https://cloud.githubusercontent.com/assets/21199185/17896206/fce200c0-694f-11e6-9d49-ce66bc297b3d.png)

**Comment by JedMeister** [comment]
AFAIK, email alerts are only supported in the paid version. About 2 years ago the head Observium dev [stated (on our forums)](https://www.turnkeylinux.org/forum/support/20140115/observium-email-setup#comment-19913) that it had been removed but would be back eventually. But it seems it still hasn't yet made it back in. So this is currently a known limitation of Observium CE.

**Comment by engmostafakotb** [comment]
Thanks a lot for your reply

**Comment by JedMeister** [comment]
No problem. Sorry I didn't have better news...
