### ISSUE TITLE
How to remove the silent link to turnkeylinux at the end of drupal pages?

### ISSUE THREAD

**Issue by fibo99** [turnkeylinux/tracker#692]
On my home drupal page, there is at the end the following piece of code
`<div id='turnkey-credit'> <div style='clear: both;'> 
    <a href='https://www.turnkeylinux.org/drupal8'>Drupal 8 Appliance</a> - Powered by 
    <a href='https://www.turnkeylinux.org'>TurnKey Linux</a> 
</div> </div>`

Apparently this piece does not show when the page is read in a web browser, only when reading thru some text explorers.
While I understand the interest of this backlink towards the site, I would like to remove it.
I did not find it in the usual suspectable files: any hint? 
Or is this strictly forbidden by some tiny print I missed?

**Comment by l-arnold** [comment]
Poke around these links.  Should indicate what you need to do

https://github.com/turnkeylinux-apps/drupal8/blob/master/overlay/etc/apache2/mods-available/substitute.conf

Coming out of GitHub it is generating here and likely landing in the folder above.
https://github.com/turnkeylinux-apps/drupal8/blob/master/conf.d/main

**Comment by JedMeister** [comment]
@l-arnold has headed you in the right direction. Perhaps you noticed that the "credit" footer is proceeded by the Apache substitute module? If you do not need the substitute module for anything else (chances are you don't) then the easiest way to disable it is like this:
````
a2dismod substitute
service apache2 restart
````

**Comment by fibo99** [comment]
Thx, both answers pointed me asap to the right solution!
B-) and at the same time I discover a good example of what substitue.conf can do. 
Great!

**Comment by JedMeister** [comment]
:smile:
