### ISSUE TITLE
Rails based images cannot be built

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#696]
..due to the error: "activesupport requires Ruby version >= 2.2.2"
The fix seems to be to specify the version of Rails to be the last one of the 4 series in the jessie specific section of common/conf/rails. It happens to be 4.2.7.1 right now.

The redmine image still does not build after trying this, though.

**Comment by qrntz** [comment]
:arrow_up: and I'll take a closer look at Redmine.

**Comment by qrntz** [comment]
Redmine builds fine for me with the PR.
