### ISSUE TITLE
Template directory is not writable

### ISSUE THREAD

**Issue by lukescammell** [turnkeylinux/tracker#698]
Fresh, default config of Dokuwiki and the templates directory is not writable, so cannot add templates via the extension manager. These should be writable so we don’t have to jump immediately into the command line to change the permissions.

**Comment by qrntz** [comment]
You are right. Thank you for reporting.

**Comment by hvoIIITA** [comment]
I just installed 15.0 looks like this issue has reappeared

Out the box it doesn't look like correct perms are set

**Comment by JedMeister** [comment]
FWIW, we intend to do a new release soon. It will come with the "upgrade" plugin pre-installed and more relaxed permissions.

To relax the permissions in your current install:
```
chown -R www-data:www-data /var/www/dokuwiki
```
That will give full ownership to the dokuwiki webroot to the webserver user. 

If you want to lock down your server after you've done what you wish to do, then please see this doc:
https://github.com/turnkeylinux-apps/dokuwiki/blob/master/docs/locking-down.rst
