### ISSUE TITLE
Nodejs update pm2

### ISSUE THREAD

**Issue by Wernervanrun** [turnkeylinux/tracker#699]
How do i update pm2 to v2.0.0 or any other version for that matter.

Regards Werner

**Comment by qrntz** [comment]
PM2 is installed with `npm` at the time of building the respective TurnKey image. So, it should be updated for all Node.js-based appliances in our next release (v14.2).

In the meantime, you can use this to upgrade it:
```console
npm update -g pm2
```

(run as root)

**Comment by JedMeister** [comment]
As this isn't really a bug or feature request I'm going to close it. FWIW @Wernervanrun general questions like this are often best asked on our [forums](https://www.turnkeylinux.org/forum). Cheers.
