### ISSUE TITLE
Potential issue with ec2-pvmshim grub patches being included in TKLBAM backups?

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#704]
To support both HVM and PV instances on AWS we provided some grub patches.
A user recently reported an incident where a server (was running fine), refused to boot (falling to a grub prompt) after being stopped. We are still not 100% sure of the cause.

However, as we use grub patches to support both PV and HVM instances on AWS, a possibility is that the ec2-pvmshim grub patches (from a PV instance) was included in TKLBAM backup. If that's the case, then restoring a backup from a PV instance to a HVM instance will break the new instance.

We'll need to investigate further. If this is an issue, the ec2-pvmshim grub patches will need to be blacklisted in TKLBAM profiles.

**Comment by lirazsiri** [comment]
It doesn't really make sense for TKLBAM to backup grub configuration so I just patched all TKLBAM profiles to blacklist /etc/grub.d. We still need to test that this resolves the issue.

FWIW, whenever buildtasks patches an ISO in a directory that's monitored by TKLBAM (e.g., /etc) TKLBAM will pick that up as a difference to backup. If a change is only appropriate for a particular build, that may create a problem when we restore that backup to another type of build.

**Comment by JedMeister** [comment]
As per the comment by @lirazsiri - I'm closing this now.
