### ISSUE TITLE
New Appliance: Mayan EDMS

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#714]
Current Status (Beta 2 - Testing)

I have started a build for Mayan EDMS primally because I need one, and this one fit the bill!

[My TKLDev Github Repo](https://github.com/DocCyblade/tkl-mayan-edms)

[Mayan EDMS Web Site](http://www.mayan-edms.com)

[Mayan EDMS Documentation](https://mayan.readthedocs.io/en/latest/)

From Mayan's website

> Mayan EDMS is a Free Open Source Electronic Document Management System, coded in the Python language using the Django web application framework and released under the Apache 2.0 License. It provides an electronic vault or repository for electronic documents.

**Comment by l-arnold** [comment]
I will.look for some beta testing time.  One other biz ap I would also like to test.  Main interest is about system functiion.  Super busy right now but important to chip in.

**Comment by DocCyblade** [comment]
@l-arnold - Would be great to have another tester! If you want to give it a build, use [Beta 2 - v0.2](https://github.com/DocCyblade/tkl-mayan-edms/tree/v0.2) when checking out the code. Be sure to checkout [the submitted bugs](https://github.com/DocCyblade/tkl-mayan-edms/issues?q=is%3Aissue+is%3Aopen+label%3Abug) so you know when you see one. Feel free to go over to [my github page](https://github.com/DocCyblade/tkl-mayan-edms) and post any testing info you may have on my [testing issue](https://github.com/DocCyblade/tkl-mayan-edms/issues/1) or post any new issues. Look forward to working with you again my friend!

**Comment by DocCyblade** [comment]
Published! 
https://www.turnkeylinux.org/mayan-edms
