### ISSUE TITLE
Magento 1.9 Critical security patch required on new build & permissions not right by default

### ISSUE THREAD

**Issue by GotGetGitHub** [turnkeylinux/tracker#716]
**[update by Jeremy]** Essentially, install latest security patch(es) and test to ensure working

----
Out of the box I get the following:
1. Critical security patch required on new build start-up
2. Compilation error on new build:
   Directory "/var/www/magento/includes" must be writeable
   File "/var/www/magento/includes/config.php" must be writeable

Is this "a ready-to-run Magento 1.9 solution that is secure, supported and easy to maintain" product offering?

**Comment by JedMeister** [comment]
The [patch which I assume you refer to](https://magento.com/security/patches/supee-8788) was released 3 days ago! IMO it's a bit harsh to judge us on that! 

Having said that I am aware that v1.9 is quite old now. Unfortunately we have a labour bottleneck and can't ever get everything done which we'd like to... We plan to start working on updates sometime soon.

As for your second point, that sounds like after you did the upgrade, you neglected to properly set the permissions. As you are the root user, you need to make sure that the webserver account has write permissions for the Magento directory (like how we [set it up initially](https://github.com/turnkeylinux-apps/magento/blob/master/conf.d/main#L77)). I.e.:
````
chown -R www-data:www-data /var/www/magento
````

**Comment by GotGetGitHub** [comment]
Thanks for your response JedMeister.

Sorry, my intension was not to judge. My comment on the 'ready to run, supported', etc. was based on you comparing your marketing to the delivery received. 3 days getting to a critical security update could be seen as not meeting the suggestion in your marketing.

On the second point, I'm afraid your assumption was incorrect. I didn't apply the patch, I merely viewed the configuration.

Again, thank you for your response.

**Comment by JedMeister** [comment]
Thanks for your response. We always welcome feedback (or at least try to! :smile:) so apologies if I came across as a bit defensive.

Apologies for my misunderstanding re the file permissions issue. Thanks for reporting that issue and for providing clarification.

The link in my previous post was to the build code for the Magento appliance. The line I highlighted should be adjusting the permissions correctly. It seems that is not the case though. I will need to look into that a bit closer. It seems very strange though...

**Comment by GotGetGitHub** [comment]
Thank you for adding this issue to your backlog. Do you have an expectation to share on the time frame for resolution?

Many thanks.

**Comment by JedMeister** [comment]
TBH I'm not sure. We are currently snowed under and have a massive backlog of issues to resolve. Ideally we should rebuild the appliance ASAP to include the security patch OOTB, unfortunately though we have some other pressing matters which need to take precedence. I'll add the `security` tag though so it sits higher in the list.

Actually, assuming that you manually applied the security patch from the commandline, I suspect that is what caused the issue. It should be easily resolved like this:

````
chown -R www-data:www-data /var/www/magento
````

**Comment by JedMeister** [comment]
Deep apologies on the ridiculous delays. 

Hopefully it shouldn't be too far away now (weeks at worst). I'm closing this issue for now as we also have #759; a request for v2.1 (which will be in the v14.2 release).
