### ISSUE TITLE
New Appliance: Mumble

### ISSUE THREAD

**Issue by MPTMG** [turnkeylinux/tracker#723]
Created a Mumble Appliance need additional testers and code review/comment.

https://github.com/MPTMG/Mumble

**Comment by qrntz** [comment]
Thanks for the effort!

I'll take a look and get back to you.

**Comment by DocCyblade** [comment]
I'll take a look as well. Would you mind if I open issues on your repo? I find that way you have a more precise way of listing the things to do and a nice clear place for dialog! I do this my self on my contributions. I am currently working on [Mayan EDMS](https://github.com/DocCyblade/tkl-mayan-edms) and last year I helped out with [Odoo](https://github.com/DocCyblade/tkl-odoo), feel free to take a look at the code base for use patterns as well.

**Comment by MPTMG** [comment]
Feel free to open issues on the repo. I will do whatever is necessary to ensure that it meets the TKL standards and complies with any best practices you guys may have for this sort of thing. Honest feedback yields the best end result.

**Comment by DocCyblade** [comment]
@MPTMG - I had a quick look at the code, I opened up a few issues. Feel free to start discussion in the issues.

**Comment by MPTMG** [comment]
Latest commit includes suggestions proposed by DocCyblade (thanks again).

**Comment by DocCyblade** [comment]
@MPTMG - I'll have a look when I get home this evening.

**Comment by DocCyblade** [comment]
@MPTMG - I apologize for the delayed response have been sick as of late :-( 

I did a quick build and it seems to build. I am doing a quick review of the build scripts now.

**Comment by JedMeister** [comment]
@MPTMG - as the others have said, thanks again for your contribution! :smile: 

Thanks @qrntz for jumping straight in. 

And extra thanks to (one of our premier community champions) @DocCyblade on taking the lead on helping to create an appliance that confirms to our standards. 

As an aside (and I'm sure I've mentioned previously), I think we probably should provide a simple clear checklist of requirements for new apps. Perhaps it should be a separate doc called `new-checklist.rst` (or similar) and added to https://github.com/turnkeylinux-apps/tkldev/tree/master/docs/development/ ?

**Comment by MPTMG** [comment]
Just let me know what additional things need to be done for you guys to include this. Still working on one last thing from DocCyblade in reference to auto opening ports as additional servers are created. Additional web interface for Mumble (phpMumbleAdmin) will be added soon.

**Comment by DocCyblade** [comment]
@JedMeister - welcome back! I agree with the check list. I can open a new issue and we can discuss this further there if you would like.

**Comment by JedMeister** [comment]
@MPTMG - I have had a really quick glance and it looks like a great app. I will have a closer look and follow @DocCyblade's lead and open issues on your repo for anything I discover.

@DocCyblade - once again, champion effort! :smile:

**Comment by MPTMG** [comment]
Committed code tonight. Changes include additional web interface phpMumbleAdmin, script and daemon for opening firewall ports automatically (checks every 5 minutes), sed statement changes for resiliency to special characters, inithooks for phpMumbleAdmin.

**Comment by qrntz** [comment]
Sorry this took me a while! Please review/comment PR above.

Did anyone else witness 30rootpass not being executed properly (root password remains «turnkey»)? If not, must be something broken in my system.

**Comment by MPTMG** [comment]
No issues for 30rootpass for me. I merged your changes/improvements rebuilt the iso and everything works as expected @qrntz.

**Comment by qrntz** [comment]
Must be something on my side. Thanks for testing & merging.

**Comment by OnGle** [comment]
@MPTMG Sorry for the long wait, I've had a look at the build code, everything looks good to me. We should be building this very soon! Thanks again for your work!

**Comment by MPTMG** [comment]
Excellent. Let me know if you need anything additional. I built a Zoneminder appliance as well, take a look if you guys are interested. I have some free time, so if there are other appliances that you need someone to take a look at I can.

**Comment by JedMeister** [comment]
@MPTMG - Sorry that it's taken such an embarrassing long time to get your first appliance published. But we finally got there in the end. I announced Mumble late last week. Please see the new Mumble server appliance page [here](https://www.turnkeylinux.org/mumble) and the blog post announcement [here](https://www.turnkeylinux.org/blog/v14.2-release-update3-x3-new-x24-isos).

Thanks again for your contribution and sorry that it's taken so long to get it live. Now on to Zoneminder...
