### ISSUE TITLE
CANVAS:  Instructors cannot Upload

### ISSUE THREAD

**Issue by backstageapps** [turnkeylinux/tracker#725]
This Turnkey installation of Canvas seems largely unusable, despite wanting it to work.  The biggest issue is that users cannot upload files.  Anyone see this issue or know how to resolve?

TW

**Comment by DocCyblade** [comment]
@backstageapps - I have not used this app before, but I will spin one up. Can you give me a step by step work flow so I can try an replicate the issue.

**Comment by DocCyblade** [comment]
@backstageapps - First off thanks for pointing this App out. I can see why you want it to work. It looks really nice. However I could not get the same issue you describe. Can you describe your setup, is it on real hardware, virtualized (what kind of hypervisor) and do you have it going through any firewalls etc.

Also if you could step me through like I did below so I can try to replicate the issue.


I tried the following:
   1. Installed ISO (v14.1) to test VM with 2GB vRAM 2 vCPU 20 GB vHDD
   2. Took all the defaults / and updated the system. (`apt-get update && apt-get upgrade`)
   3. Logged in as admin, created new user and assigned as a student
   4. Created a course, and created an assignment, assigned to the created student.
   5. Made sure the assignment was to be uploaded, no restrictions on content type
   6. Logged in as student, accepted the course and uploaded an excel file with out any issue.
   7. Was able to login as admin, see the uploaded file and grade the assignment and post a note with  an Word attachment.
   8. Logged in as student and was able to see grade and comment, with attached word doc. 
   9. As student, added comment to teacher with a PDF upload, no issues
   10. Finally as teacher I can see the comments and the uploaded PDF file from student.

**Comment by DocCyblade** [comment]
@backstageapps I tried few more times and uploading worked for both student login and teacher, again can you provide any more details in your setup?

**Comment by qrntz** [comment]
Could not replicate either.

**Comment by JedMeister** [comment]
@DocCyblade & @qrntz thanks for looking into this. As neither of you can reproduce and @backstageapps hasn't been back to provide further details I am closing for now.

@backstageapps please feel free to provide further info to help us reproduce your issue. If you can, then I'm more than happy for it to be reopened.
