### ISSUE TITLE
Mediawiki package has been removed from Jessie repos

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#726]
It has been noted that the Debian Mediawiki package (which TurnKey uses for it's Mediawiki appliance) is no longer in the main Debian repos. There is a newer version in jessie-backports but due to the lack of backport testing (as opposed to the security testing) it can't reliably be used for auto updates. 

Given the potential for issues and no assurances of the timeliness of future updates to backports (managed by the backports team rather than the security team); it's probably better to just install from upstream for v14.2+. We can then reassess the situation once we get to v15.0.

We also need to document the manual upgrade/migration process for existing v14.x users. Even if we plan to go with the upstream install, it may still be worth documenting backports install as some users may prefer the (potential) ease of that?

**Comment by qrntz** [comment]
@JedMeister https://github.com/turnkeylinux-apps/mediawiki/pull/8 resolved this (?)

**Comment by JedMeister** [comment]
Mostly. We still need to document the migration from the existing appliance to the upstream install. Should be fairly straight forward I imagine?

**Comment by qrntz** [comment]
Yep. I'll do that.

**Comment by JedMeister** [comment]
Awesome :)

**Comment by qrntz** [comment]
@JedMeister, doc published at https://www.turnkeylinux.org/node/19649

**Comment by JedMeister** [comment]
Great work, thanks mate! You rock! :smile: 

BTW I gave it a pretty url alias: https://www.turnkeylinux.org/docs/mediawiki/migrate-to-v14.2
