### ISSUE TITLE
TKL New Appliance Check List

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#728]
Building an TKL appliance can be fun, and hard work too. What would take some of the guess work out of the process would be a nice cut and dry check list for community members like my self to make sure we dot all the "i"s and cross the "t"s, and would take some work off of old @JedMeister :-). Also some maybe and off shoot could be some best practices that are kind of known to the core dev's but maybe not written down all in one place. 

This was discussed [here](https://github.com/DocCyblade/tkl-mayan-edms/issues/1#issuecomment-255506398) and [here](https://github.com/turnkeylinux/tracker/issues/723#issuecomment-260817880) and other conversations we have had in the past year via email.

**Comment by JedMeister** [comment]
As per my recent comment in another thread:

> Perhaps it should be a separate doc called new-checklist.rst (or similar) and added to https://github.com/turnkeylinux-apps/tkldev/tree/master/docs/development/ ?

**Comment by JedMeister** [comment]
Extending discussion from https://github.com/turnkeylinux/tracker/issues/729#issuecomment-260969244:
>>More generally, so long as there is a solid use case and it's under an open source license then IMO it's a legitimate appliance candidate.

>Should add this to the check list #728

@DocCyblade - I agree that it should be clearly documented somewhere. 

I was actually thinking of the checklist being a final double check that everythign has been done and is up to spec. However, your suggestion raises a good point. Perhaps there is stages to the checklist, or probably more like a pre-start checklist and a final checklist?!

**Comment by JedMeister** [comment]
I've actually been thinking that we should provide appliance build code tests. Then users could run that and get a report of areas that may need further tweaks.

**Comment by JedMeister** [comment]
It could possibly do with some more work, but a checklist exists: https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/appliance-checklist.rst

As such I'm going to close this. As per always, if there is value in reopening, I'm happy to run with that...
