### ISSUE TITLE
New appliance: Snipe-IT

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#729]
I am was looking at creating something for my "real job" to track mobile device assets, but like everything else time is NOT on my side, so I started looking at open source options. 

I ran into, and settled on Snipe-IT. You can find more info below links. 

@JedMeister - Let me know if this would qualify, I think it would [from this old post here](https://www.turnkeylinux.org/forum/general/20140509/it-asset-management) And I since this would be for work, it's a high priority for me :-) 

WebSite:
https://snipeitapp.com

Documentation:
https://snipe-it.readme.io/docs
https://snipe-it-manual.readme.io/docs

Snipe-IT GitHub:
https://github.com/snipe/snipe-it

Turnkey Build Code:
https://github.com/DocCyblade/tkl-snipe-it

**Comment by JedMeister** [comment]
I think it looks awesome! I say, go for it...!

More generally, so long as there is a solid use case and it's under an open source license then IMO it's a legitimate appliance candidate. And as time goes on Alon is giving me more and more control of the appliances so he needs less and less convincing! :smile: Regardless IMO Snipe-IT has both boxes ticked so I don't think that any convincing will be required. OTOH, it's still probably not a bad idea to float ideas before 

Specifically in this case, if you are under the pump to do it for work then feel free to just create the basic appliance for you own consumption first. Then come back to it to do any remaining jobs when you have some more time. E.g. inithooks and artwork wouldn't be required for your direct purposes.

FYI as you probably already know, you can use [buildtasks](https://github.com/turnkeylinux/buildtasks) to create whatever format you need (if ISO won't do the trick).

**Comment by DocCyblade** [comment]
> More generally, so long as there is a solid use case and it's under an open source license then IMO it's a legitimate appliance candidate. 

Should add this to the check list #728

**Comment by DocCyblade** [comment]
Added my github repo to the issue

**Comment by DocCyblade** [comment]
@JedMeister - Sounds good. I will do as you said, create a basic version for our use now, and add the TKL bits later.

**Comment by JedMeister** [comment]
> Sounds good. I will do as you said, create a basic version for our use now, and add the TKL bits later.

Totally fair IMO! :smile:

**Comment by JedMeister** [comment]
In an effort to finalise v15.0, I'm moving this to v15.1. If it gets done prior to v15.1, we can always move it back (and release as a late addition to v15.0).

**Comment by JedMeister** [comment]
FWIW, this was developed and released as part of v16.0.

See: 
https://github.com/turnkeylinux-apps/snipe-it
https://www.turnkeylinux.org/snipe-it

**Comment by alkopit** [comment]
How to upgrade Snipe-it after install from TurnKey ISO?

**Comment by JedMeister** [comment]
Hi @alkopit - sorry I missed your post. FWIW support requests are best asked via our [support forums](https://www.turnkeylinux.org/forum/support/).

I've just posted a tutorial on the best upgrade path](https://www.turnkeylinux.org/forum/support/fri-20220107-2255/upgrade-snipe-it). I hope that helps.
