### ISSUE TITLE
To send emails; phpList appliance needs hostname set in postfix config 

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#732]
Luis Flores reported on the [forums](https://www.turnkeylinux.org/forum/general/20141221/server-send-emails%D8%9F#comment-26848) that he `had to correctly configure "myhostname" on /etc/postfix/main.cf`.

As I noted in the thread, this probably deserves better documentation in the short term, but automation for the next release...

I have tagged the phplist appliance explicitly, but also core as it is most likely relevant to all appliances...

**Comment by DocCyblade** [comment]
@JedMeister - You know the one thing I do on EVERY TKL install, that probably should be a first boot init script? Set the hostname and domain name! Setting this in core/common I think is a good idea! If it were set early on during first boot, other more specific apps that need hostname else where could then read `/etc/hostname` and configure it's app specific files.

**Comment by JedMeister** [comment]
Actually we already have plans for supporting easy config of that for v14.2. Most of the work has been done already.

FWIW we've [updated confconsole](https://github.com/turnkeylinux/confconsole/pull/6) to provide a plugin system and added some additional default config options.  It's in our `jessie-testing` repo so if you add that to your sources you could install it and have a play if you want. 

It may need some tweaking and/or rough edges taken off but it should be useful as is...

We decided not to make them firstboot scripts because we want to keep initial install minimal. IMO ideally we should support preseeding of some/all these via non-interactive inithooks as well. I.e. if preseeded they are auto configured, otherwise they can be configured interactively via confconsole (but not interactive firstboot initscript).

**Comment by JedMeister** [comment]
I.e. add a new line to `/etc/apt/sources.list.d/sources.list` (or a new `.list` file to `/etc/apt/sources.list.d/`) that includes this line:

````
deb http://archive.turnkeylinux.org/debian jessie-testing main
````

**Comment by DocCyblade** [comment]
@JedMeister - I know that was something that was talked about last year this time when working on Odoo, to allow further tweaking of packages and such, this to me awesome, I'll be sure to install and break it, I mean test it! So much TurnKey so little time!

**Comment by JedMeister** [comment]
Hehe! :smile: Looking forward to hear how your testing goes!

FWIW it's been designed so that additional appliance specific plugins can be added to the appliance's overlay dir (just like we do with inithooks). Hopefully it's fairly clear how you add your own plugins... See the [example.py](https://github.com/turnkeylinux/confconsole/blob/master/plugins.d/example.py)

**Comment by JedMeister** [comment]
I removed Core yesterday, thinking that this was a phplist specific thing to consider. However, in discussion with @qrntz he raised a really good point: As postfix is installed in all appliances, it probably should be easily adjustable in all appliances. The postfix config should also probably be auto set by the tool we are using for setting the hostname (which qrntz worked on, hence why he's been allocated this issue).

**Comment by l-arnold** [comment]
Good directions guys.  Postfix would be great to thresh out and make functional.

**Comment by JedMeister** [comment]
This should have been included in the confconsole hostname plugin! Doh! The confconsole code has been updated, but I'm not sure when we'll release the new confconsole package.

For now I'm also going to include it in the phplist app as an overlay, but I'll discuss it with Alon and see how we handle this on other appliances.
