### ISSUE TITLE
Replace n with nvm in common nodejs configuration

### ISSUE THREAD

**Issue by lirazsiri** [turnkeylinux/tracker#738]
common/conf/node-install installs the 'n' node version manager from https://github.com/tj/n 

We should be using https://github.com/creationix/nvm instead

**Comment by qrntz** [comment]
@lirazsiri why?

**Comment by JedMeister** [comment]
I'm going to just close this for now. @lirazsiri didn't get back to us, so let's push on as is... Obviously feel free to reopen if desired.
