### ISSUE TITLE
Trac appliance: internal server error

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#743]
As reported by [kipahei170 in our forums](https://www.turnkeylinux.org/forum/support/20161128/trac-invalid-indexhtml), Trac has an invalid `index.html` which causes it to throw and internal server error when first launched.

kipahei170 reports that removing the last 2 lines from the `index html` works around the issue.

**Comment by OnGle** [comment]
I was unable to reproduce this issue in fresh built chroot, on iso or in the current available container build. Without further information I cannot confirm this bug.

**Comment by JedMeister** [comment]
closing for now as we couldn't reproduce this issue. Please comment and/or reopen if new info etc comes to light.
