### ISSUE TITLE
Buildtasks: bt-container throwing error during build

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#748]
As reported by Christian in the [forums](https://www.turnkeylinux.org/forum/support/20161117/drupal-8-announced-not-available-proxmox#comment-27007) when using `bt-container`:

````
./bt-container: line 61: /usr/local/src/pfff/build/config/common.cfg: No such file or directory
````

**Comment by OnGle** [comment]
I'm not 100% sure but if memory serves me correctly, BT_CONFIG needs to be reset after installing pfff and cmake.

**Comment by qrntz** [comment]
I wonder if we even need pfff (and conversely, cmake) anymore… does anything still use the signatures?

**Comment by JedMeister** [comment]
@qrntz - I totally agree. FWIW @OnGle has removed all the OpenNode build stuff as it's a deprecated platform. FWIW OpenNode was/is quite similar to Proxmox, but based on CentOS. They have now moved to a container based model which TKLX will probably integrate with quite nicely once we get there...
