### ISSUE TITLE
AWS security group settings seemingly ignored in Ruby image

### ISSUE THREAD

**Issue by pmryanibm** [turnkeylinux/tracker#761]
I provisioned the Turnkey image for Ruby on Rails into AWS (EC2 m1.medium).  I got the system initialized successfully.  I am able to ssh into the image as well as bring up the webmin interface.  In AWS, I assigned a security group that includes TCP port 3000 in addition to the other ports needed by Turnkey (22,12320, 12321,80,443). As of now, connections are allowed to those ports from anywhere.  The built-in firewall, iptables, is set to accept everything:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   

  I upgraded rails, installed my application, and started the Rails server:

admin@rails ~/sample_app$ rails server
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

   Despite all of that, connections to port 3000 are being refused:

connecting to ec2-54-89-100-93.compute-1.amazonaws.com on port 3000...
ec2-54-89-100-93.compute-1.amazonaws.com: Connection refused

I also added the MySQL port, 3306.  Same effect.

  This is a screen shot from the EC2 mgmt console. It shows the inbound rules for the image.
<img width="523" alt="screen shot 2017-01-27 at 11 39 36 am" src="https://cloud.githubusercontent.com/assets/13138864/22378994/75524a96-e485-11e6-85dc-2df7dadb6bbe.png">

  Some other layer is restricting access to these ports.  I need help figuring out what's going on.

thanks,

pat

**Comment by JedMeister** [comment]
Hi Patrick,

Please note that this is our issue tracker, ideally used to track bugs and feature requests. I can guess that in this instance you weren't sure whether it was a bug or you just needed insight and understanding on what might be going on. 

FWIW I replied to your [forum post](https://www.turnkeylinux.org/forum/support/20170125/image-ignoring-aws-security-group-settings) on this same issue a couple of days ago. Hopefully that helps.

I'm going to close this now, but if you believe that there is actually a bug, then please feel free to reopen it.
