### ISSUE TITLE
Provide improved vim-tiny default config

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#763]
Currently the appliances all include vim-tiny. That's cool, but the default config is pretty painful IMO. THe obvious answer is to upgrade to "proper" vim, but seeing as the size difference is significant, a preferable way to go is to just improve the default config. 

My biggest bugbear is that tabs remain as tabs and expand to a width of 8. IMO tabs should expand to be 4 space characters (except for GNU makefiles).

**Comment by OnGle** [comment]
I think the MVP would look something like

```
set tabstop=4 shiftwidth=4 expandtab softtabstop=0

autocmd FileType make setlocal noexpandtab
```

Essentially, tabs expand to 4 spaces except in makefiles where they're tabs
