### ISSUE TITLE
Include email in Odoo inithook

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#769]
I have been playing with the Odoo appliance and have noticed that it has the default email auto configured to `admin@example.com`. That's fine as a default, but ideally it'd be nice if that was set by the inithook.

@DocCyblade - I hope you don't mind I have assigned you as you're the Odoo man! :smile: Please feel free to unassign yourself.

Note this is just a "wishlist" item, certainly not a priority. Actually it may be better to wait until it has a newer version of Odoo (as discussed elsewhere) as things may be different?

----

Update: 

Actually it looks like it's setting the user default email to just `admin` in some places. The application log in screen (after you have created a database with the master password) asks for "Email", but actually it requires you to log in with just `admin` (not an email address). After logging in, you can change that in the user preferences, but I suspect that may be confusing to users. 

I certainly found it confusing and only worked it out after a bit of trial and error. FWIW I did a quick google and discovered that I had already answered that question for someone else previously. Doh! :)

**Comment by DocCyblade** [comment]
Sounds good :-)

**Comment by l-arnold** [comment]
Hi Guys,
Do we know if the email in Odoo is working "out of the box" with Postfix?  IE, if DNS records are set properly for both the domain and mx, will the Odoo App serve both Odoo as well as all in and outgoing mail?  For me, I have only been able to do this using an external server with an email box set to "catch all" for that domain.  
Seems this would work in Postfix now somehow.
Working a bit on odoo and our work threads here have a lot of good history in them.

**Comment by JedMeister** [comment]
AFAIK it should be for outgoing mail (as per all TKL appliances). Incoming mail should also work, but I can't be 100% sure of that.

As per always though, ISPs often block port 25 (default email port) and many dynamic IPs get blacklisted for sending spam (so emails often get silently dropped).

The most reliable way to configure email is to use an SMTP relay for emails. [Confconsole](https://www.turnkeylinux.org/docs/confconsole) provides a fairly easy way to configure a [mail relay](https://www.turnkeylinux.org/docs/confconsole/mail_relay). Best bet is to log in via SSH to do that (it should probably also work from Webshell, but using a proper SSH client will generally be a much better experience).

**Comment by JedMeister** [comment]
Oops, just noticed that this issue wasn't pinned to a release milestone, so it probably hasn't been included in the v15.0 buildcode. I've just added it to the v15.0 milestone and added it as a "feature request". There is no guarantee it will make it in, but hopefully!

**Comment by JedMeister** [comment]
Whilst it would be nice to include this in v15.0, I'm moving it to v15.1 as we need to get v15.0 done...!

**Comment by JedMeister** [comment]
I had a super quick look at this yesterday. I've actually changed my mind and have decided not to worry about this. My rationale is that the default "odoo" DB is essentially an "example" Odoo site/DB. Users will most likely create their own Odoo site/DB so updating the admin email address for the "example", is probably of limited value...
