### ISSUE TITLE
Confconsole: Region Config -> Keyboard:  Message Bug

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#770]
In Region Config -> Keyboard: When selected strange message pops up and can't read all of it.

When selecting Yes or No does not seem to do anything.

<img width="279" alt="screen shot 2017-02-01 at 10 34 54 pm" src="https://cloud.githubusercontent.com/assets/9731860/22536357/3cc149ea-e8cf-11e6-825e-3e54d0730617.png">

Test was with
```
root@lamp ~# apt-cache policy confconsole
confconsole:
  Installed: 0.9.4+97+gc9897a4
  Candidate: 0.9.4+97+gc9897a4
  Version table:
 *** 0.9.4+97+gc9897a4 0
        900 http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.4+54+g99603c7 0
        850 http://archive.turnkeylinux.org/debian/ jessie/main amd64 Packages
```

**Comment by OnGle** [comment]
This should be fixed here 
https://github.com/OnGle/confconsole/commit/786733885840fb47aa06d9d91fea5ec78ca189fa
(added option to auto size yesno/msgbox dialogs)

**Comment by DocCyblade** [comment]
@OnGle 

Looks like the window is fixed, however it does not do anything. I think I saw it flashed some text messages too quickly for me to see. I can select YES and it just takes me back to the menu

**Comment by OnGle** [comment]
It appears this issue was caused by the package `keyboard-configuration` not being installed by default on turnkey systems. It should (as of https://github.com/OnGle/confconsole/commit/7f385f8e7375c01b12b001472dbc09cc74149750) now give a clean error message rather than silently going back to the menu

**Comment by JedMeister** [comment]
New package `confconsole_0.9.4+102+g7f385f8_all.deb` which should close this bug has been uploaded to dev-test repo.

**Comment by DocCyblade** [comment]
Confirmed bug is fixed
