### ISSUE TITLE
Confconsole: Region Config -> Locals: Message goes too fast 

### ISSUE THREAD

**Issue by DocCyblade** [turnkeylinux/tracker#771]
When selecting Region Config -> Locals a message flashes up so fast I had to do 3-4 screen shots to catch it (Maybe my laptop is way to fast!)  

Clip of the message that flashed up so fast

<img width="235" alt="screen shot 2017-02-01 at 10 38 45 pm" src="https://cloud.githubusercontent.com/assets/9731860/22536480/0a0f57a2-e8d0-11e6-8b15-c9ef19d01d39.png">

Test was with
```
root@lamp ~# apt-cache policy confconsole
confconsole:
  Installed: 0.9.4+97+gc9897a4
  Candidate: 0.9.4+97+gc9897a4
  Version table:
 *** 0.9.4+97+gc9897a4 0
        900 http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.4+54+g99603c7 0
        850 http://archive.turnkeylinux.org/debian/ jessie/main amd64 Packages
```

**Comment by OnGle** [comment]
This also should be fixed here
https://github.com/OnGle/confconsole/commit/786733885840fb47aa06d9d91fea5ec78ca189fa

**Comment by DocCyblade** [comment]
This bug is fixed, works on the latest build 

```
confconsole:
  Installed: 0.9.4+101+gf610e0f
  Candidate: 0.9.4+101+gf610e0f
  Version table:
 *** 0.9.4+101+gf610e0f 0
        900 http://tkl-dev-test.s3-website-us-east-1.amazonaws.com/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.9.4+54+g99603c7 0
        850 http://archive.turnkeylinux.org/debian/ jessie/main amd64 Packages
```

**Comment by JedMeister** [comment]
Awesome thanks @DocCyblade
