### ISSUE TITLE
addclient private subnet problem

### ISSUE THREAD

**Issue by swamilad** [turnkeylinux/tracker#772]
When using "openvpn-addclient client client@client.net 1.2.3.4", the file /etc/openvpn/server.ccd/client is created, but due to the chroot in server.conf, the system actually looks for /etc/openvpn/easy-rsa/keys/crl.jail/etc/openvpn/server.ccd/client

The result is 1.2.3.4 being inaccessible and a nearly impossible to google (to any avail...) "GET INST BY VIRT: 1.2.3.4 [failed]" in the log.

I resolved the issue for myself by making /etc/openvpn/server.ccd a symlink to /etc/openvpn/easy-rsa/keys/crl.jail/etc/openvpn/server.ccd.

**Comment by JedMeister** [comment]
Thanks for your bug report and workaround.
