### ISSUE TITLE
OpenCart appears worthy!

### ISSUE THREAD

**Issue by l-arnold** [turnkeylinux/tracker#776]
Looking at OpenCart just now.  It looks like a worthy addition to the TKL Library.

Not really ready to take this on myself but I can see a few rationale for sure.

https://www.opencart.com/

Something to consider anyway.
Landis

**Comment by JedMeister** [comment]
Hey Landis. Thanks for the suggestion. We're not currently in a position to be creating new appliances, but hopefully at some point in the near future... In hte meantime if yourself or someone else wants to take it on, you're more than welcome.

**Comment by JedMeister** [comment]
Hey @l-arnold, I'm closing this issue now, in favour of #894 - @qq7 has pretty much finished it. We'll release it with v15.0.
