### ISSUE TITLE
confconsole crashes if window is resized to be smaller than it's contents

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#789]
I'm not 100% sure, but I suspect that we'll just have to live with this bug for now.

To recreate it, open confconsole within a terminal session. resize the window so it is smaller than it's contents and you'll see an error.

Workaround: Don't resize windows too dramatically when using confconsole.

**Comment by DocCyblade** [comment]
I tried this on my Mac and tried to resize a few windows with confconsole and it did not crash. Maybe dynamic fonts on your end?

**Comment by JedMeister** [comment]
Good to know. Are you using a terminal window and SSH to connect? When you resize does it scale the text as well?

FWIW I'm using a Debian terminal window and connecting via SSH. When I resize the terminal window it resizes the contents, but the text size remains the same. 

I found that some resizing works ok, but reducing the size of the window beyond a certain point it will crash. But actually doesn't cause too much issue. You just click ok and it drops you back to the advanced menu.

FWIW I've attached some screenshots, it seems to be related to the initial size of the confconsole contents. I.e. happens much easier on the SSL cert screen where you enter domains (big block of content) as opposed to other screens with much less content.

Attached before, during and after screenshots (unfortunately GH scales them so they all look the same size):
![screenshot from 2017-03-07 14 14 49](https://cloud.githubusercontent.com/assets/818633/23640258/a595ed8c-0340-11e7-99ad-39aa098e1786.png)
![screenshot from 2017-03-07 14 14 59](https://cloud.githubusercontent.com/assets/818633/23640257/a595bda8-0340-11e7-9976-45362d3a95fa.png)
![screenshot from 2017-03-07 14 15 13](https://cloud.githubusercontent.com/assets/818633/23640259/a59f172c-0340-11e7-8852-a4a809ba53ce.png)

**Comment by OnGle** [comment]
If this bug persists it is most likely part of dialog and something we can't fix without a new CLI UI backend to entirely replace dialog with.

**Comment by OnGle** [comment]
When a window reduces the number of rows and columns in the terminal this is destructive, that's how terminals work, you can't write to a cell that doesn't exist in a terminal.

**Comment by JedMeister** [comment]
Ok. I'm going to close this issue for now.

As noted by @OnGle, there's nothing we can do about it on our end (without hacking on dialog itself). However, when we get v16.0 released, that will be using a newer version of dialog (direct from the Debian repos...) and the python dialog wrapper (also direct from the Debian repos - although we'll have our own dialog-wrapper wrapper... so everything just works without too much heavy lifting). So either that will fix this, or it will still be outside of our control. Either way there is no value in keeping this issue open...
