### ISSUE TITLE
Add firstboot option so Domain Controller can join existing domain (currently creates new domain)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#790]
It'd be awesome if the Domain Controller appliance supported being added as a member server rather than just creating a new domain.

Taylor has worked out what needs to be done and has documented in on the [forums](https://www.turnkeylinux.org/comment/27425#comment-27425). Big thanks Taylor! :+1:

**Comment by JedMeister** [comment]
If you din't mind mate, this would be good to include for v15.0 I reckon @spaghettimaster (assuming I recall correctly and you were working on this one?!)

**Comment by spaghettimaster** [comment]
@JedMeister, done!  [PR](https://github.com/turnkeylinux-apps/domain-controller/pull/13)

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/domain-controller/pull/13
