### ISSUE TITLE
OpenVPN: Cronjob /etc/cron.hourly/openvpn-profiles-delexpired fails with "This account is currently not available."

### ISSUE THREAD

**Issue by ainkinen** [turnkeylinux/tracker#800]
When trying to manually trigger the deletion of expired download URLs, the script fails and output is `This account is currently not available.`

Reason:
The cron job tries to execute the actual script as the user `www-data`. That user has the shell set to `/usr/sbin/nologin` in `/etc/passwd/` so the `su` command fails.

Fix:
Add `-s /bin/bash` to the `su` command to override the shell.

Issue and fix tested on:
AWS Marketplace OpenVPN AMI (HVM)

**Comment by JedMeister** [comment]
Thanks for your bug report. Bonus points for also publishing the workaround! :+1:

**Comment by JedMeister** [comment]
Thanks for the PR! :smile: 

Closed by https://github.com/turnkeylinux-apps/openvpn/pull/16
