### ISSUE TITLE
Cannot add device in via GUI & terminal 

### ISSUE THREAD

**Issue by navadhino56** [turnkeylinux/tracker#806]
I need help 

Im unable to add device in via GUI & terminal... I'm able to ping the device from server and do " Snmpwalk -c string -v1 x.x.x.x "  its working ..but only cannot add device

**Comment by JedMeister** [comment]
Which appliance? I'm guessing Observium considering your mention of snmpwalk?! If so, you can only add devices via hostname, not IP. So you'll need to set up DNS first...

**Comment by navadhino56** [comment]
Could you advice where should i add the dns ? In Obervium server ?


Thanks and Regards

Navanithan S/O Muniandy

Tel : +60173723745

________________________________

**Comment by JedMeister** [comment]
Do you not have a DNS server in your LAN? If not, then yes you could install a DNS on the Observium server if you'd like. Or so long as all the systems you want to monitor have static IPs, hardcoded entries in your hosts file (/etc/hosts) should probably do the trick?!

**Comment by JedMeister** [comment]
closing this for now
