### ISSUE TITLE
git-lfs does not appear to work with TKL-Gitlab-14.1

### ISSUE THREAD

**Issue by niarbeht** [turnkeylinux/tracker#810]
Really not sure what to test or where to go next with this.  This might be related to #686 and #758, but I'm not sure.  It's quitting time here, so I can't be more verbose today.

```
$ git push
Git LFS: (0 of 1 files) 0 B / 351.83 KB
Fatal error: Server error: http://mygitlabserver/myusername/myreponame.git/gitlab-lfs/objects/70b79e91edc07e09a98c9898f71ea05c1c9b565e1212d234368604adb193fe4e/360269 from HTTP 502
error: failed to push some refs to 'http://mygitlabserver/myusername/myreponame.git'
```

**Comment by JedMeister** [comment]
Thanks for the bug report. 

I'm guessing you have, but can you please confirm that you've double checked the [GItLab git-lfs docs](https://docs.gitlab.com/ee/workflow/lfs/manage_large_binaries_with_git_lfs.html) and have configured everything as they suggest?

Regardless, we hope to be releasing our v14.2 version (which will include the latest GitLab stable release) sometime really soon.

**Comment by niarbeht** [comment]
Yep.  Reading the manual would help.  That's what I get for trying to do stuff late in the day.

**Comment by niarbeht** [comment]
Just popping in to note that following the instructions does not appear to have resulted in a working setup.  I don't have as much time to track the issue down as I'd like, so while I'll be leaving this closed, I'd encourage you guys to take the time to figure out how/why it doesn't seem to be working  I'm sure I'm missing something obvious, but it might make for a good entry into some sort of "Errata" page, e.g. "Don't forget to X or else you won't be able to get git-lfs working."

Back to work for me!

**Comment by JedMeister** [comment]
Hmm, thanks for the feedback.

Considering that you can't get it working, let's reopen this.

**Comment by JedMeister** [comment]
I'm leaving this open until we properly investigate, but we're going to skip it for v14.2. Debian have just released Stretch (aka Debian 9), so we need to get a wriggle on! After v14.2, v15.0 will be the next release and will be based on Debian Stretch.

**Comment by niarbeht** [comment]
That's perfectly fine.  I'll take another stab at it soon at home and see if I can't figure out what all is missing that's needed to do this.
