### ISSUE TITLE
etherpad: admin config somewhat insecure; moving to commandline script (from inithook)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#813]
During testing I couldn't log into the etherpad admin area with the password that I'd set during firstboot.

I also tried to restart etherpad (actually I restarted `pm2`) and that broke it completely?!

Needs a little bit of work...

**Comment by OnGle** [comment]
After having a look at the etherpad appliance it appears that etherpad stores it's passwords in plaintext, updating the inithook to work would mean many users would be storing passwords insecurely without knowing and I believe that too be a serious security issue.

Instead I've written a small commandline utility for disabling/enabling the admin account and setting the password. It also spits out a warning about the lack of security in storing passwords in plaintext.

**Comment by JedMeister** [comment]
Great work, thanks @OnGle. I think the way you've approached this is great. I'm inclined to agree, so I've changed the name of the issue to reflect your position. Once you've got a pull request for this, I'll merge and build for v14.2! :smile:
