### ISSUE TITLE
Build error (sencha): senchacmd install fails on 64bit

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#82]
```
+ unzip -q /usr/local/src/SenchaCmd-3.0.2.288-linux-x64.run.zip -d /usr/local/src
+ /usr/local/src/SenchaCmd-3.0.2.288-linux-x64.run --unattendedmodeui none --mode unattended --prefix /usr/local/share/senchacmd
make: *** [build/stamps/root.patched] Error 1

```

**Comment by JedMeister** [comment]
I have just had a relook at this. FWIW I would like to revisit this for the v13.1 release and as such are adjusting the milestone to be 13.1

At a glance I thought Sencha may have gone propriety freeware only; but they do still have a GPL version buried (see this page: http://www.sencha.com/products/touch/license/)

There does not seem to be a separate version for 32 & 64 bit...

Download link:  http://www.sencha.com/products/touch/download/sencha-touch-2.4.1/3277

**Comment by JedMeister** [comment]
I investigated this a little more and it seems that the open source version of Sencha is 32 bit only... Closing this issue for now as v14.0 will likely be 64 bit only
