### ISSUE TITLE
The LXC template lxc-turnkey needs to be updated

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#820]
The recent change of the MD5 signature file extension from .sig to .hash causes the download of v14.2 containers to fail. A patch or replacement of the lxc-turnkey template will be needed for version 14.0 and 14.1 LXC appliances and the new version needs to be included in LXC v14.2 release.
Error shown below.
`root@lxc ~# /usr/bin/lxc-create --name core-natbr0-container --config /etc/lxc/natbridge.conf --template turnkey --bdev dir --logfile /var/log/lxc/lxc-core-natbr0-container.log --logpriority INFO -- core --version=14.2-jessie
debootstrap is /usr/sbin/debootstrap
INFO [lxc-turnkey]: checking cache download in /var/cache/lxc/turnkey/debian-8-turnkey-core_14.2-1_amd64.tar.gz ... 
INFO [lxc-turnkey]: verifying gpg signature...
gpg: verify signatures failed: eof
FATAL [lxc-turnkey]: debian-8-turnkey-core_14.2-1_amd64.tar.gz.sig gpg verification failed
FATAL [lxc-turnkey]: failed to install turnkey core
lxc-create: container creation template for core-natbr0-container failed
lxc-create: Error creating container core-natbr0-container
`

**Comment by JedMeister** [comment]
Thanks John! :+1:

**Comment by Dude4Linux** [comment]
FYI I'm working on the issue. Just discovered that the change involved more than just the file extension. The method of verifying the checksums also changed from sha1sum to sha256sum or sha512sum. That is a good thing.

**Comment by JedMeister** [comment]
That'd be super cool! :smile: 

Yeah sorry, should have mentioned that... We also need to update the docs.

**Comment by Dude4Linux** [comment]
Just released [Updates for 14.2 release #10]( https://github.com/turnkeylinux-apps/lxc/pull/10) with a new version of lxc-turnkey template that addresses this issue along with a number of other fixes and enhancements.
