### ISSUE TITLE
File Server Appliance: PHP Fatal error:  Call to undefined function SambaDAV\ssh2_connect()

### ISSUE THREAD

**Issue by cboulanger** [turnkeylinux/tracker#822]
Installed the fileserver appliance in a container on a ProxMox virtual host. This is the error I am getting in `/var/log/nginx/error.log`:

2017/05/04 14:45:39 [error] 11477#0: *16 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function SambaDAV\ssh2_connect() in /var/www/sambadav/lib/SambaDAV/Auth.php on line 176" while reading response header from upstream, client: XXXXXX, server: localhost, request: "GET /webfolders HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxx.xxx.de"

**Comment by JedMeister** [comment]
Thanks for reporting @cboulanger 

I just answered [this thread](https://www.turnkeylinux.org/forum/support/thu-20170504-1658/file-server-appliance-php-fatal-error%C2%A0-call-undefined-function) in the forums. I'm guessing that was you?

As I noted there, we're moving to a different web UI for v14.2. Unfortunately though the code was written ages ago and just not merged. But now it doesn't work :cry: ... As soon as we've worked out what the bugs are, we'll be releasing that. So I'm not super keen on spending too much time on this when the new app is just around the corner (assuming we can work out the bugs - which I'm sure we can)...

**Comment by JedMeister** [comment]
I'm closing this now. The new updated code has been merged and the new web UI will be all systems go for the v14.2 fileserver. Apologies on the delays, I can't give a tight ETA but I'd guess it'll be avaialble within the next 2-3 weeks.
