### ISSUE TITLE
composer installs in builds may ask for user input

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#826]
When the maximum number of un-authorized github-api requests is reached by composer it stops and asks for a github token from the user.

**Comment by JedMeister** [comment]
Hmm, I recall hitting this issue previously. I forgot how we managed to work around it.

Perhaps something we could do is configure something in the buildtasks config to allow a GH auth token to be included, then in scenarios such as this, it could use that?!

**Comment by cebe** [comment]
> Perhaps something we could do is configure something in the buildtasks config to allow a GH auth token to be included, then in scenarios such as this, it could use that?!

you can configure composer with an oauth token so that it will not ask for input.
explained here:
- http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/
- https://getcomposer.org/doc/06-config.md#github-oauth

**Comment by DocCyblade** [comment]
We may be able to just set an ENV variable inside your TKLDev box before a build so that composer uses that to authenticate. I'll test this while I am working on the fileserver webdav build

https://getcomposer.org/doc/03-cli.md#composer-auth

**Comment by JedMeister** [comment]
Hi @cebe - thanks for that. I was aware that we could work around it, but we need to ensure that it get's cleaned up after. I did consider creating a "throw-away" token just for the build, but it seemed pretty dirty to ship the image with a cancelled/invalid token. So I'd rather leave it for this release and design and implement a proper way of doing this for composer based installs in the future. I suspect we'll probably include the token in an overlay and then clean up afterwards.

@DocCyblade - That sounds like it could be a good option! I wasn't aware of that possibility. We'll still need to clean up after I suspect, but it's probably a little nicer.

**Comment by JedMeister** [comment]
tagged core so this happens early in the v15.0 dev cycle.

**Comment by JedMeister** [comment]
So much for my previous comment (re "arly in the v15.0 dev cycle")...

@spaghettimaster - do you want to have a look at this one? No rush at this point as I don't think that we have any immediate issues with it, although I do note that there are a few apps we still use upstream source (instead of composer).

I don't recall what appliances it is a problem in OTTOMH, but it would be good to have some reliable way of doing composer installs. We could always leave it until after the v15.0 release? Thoughts?

**Comment by spaghettimaster** [comment]
Hi @JedMeister

I like `Composer` , It's easy to use, and it check all system requirements of package before install (like php modules, php version, etc.).
Therefore, in my opinion, it would be great to update apps to use `Composer`.

I also agree with you and @DocCyblade  that using ENV for build + clean up after  can be a solution  to the github auth problem.

**Comment by JedMeister** [comment]
Hey @spaghettimaster - Awesome stuff mate. Do you want to do some more research and look at how we can implement that? If so, please assign yourself this issue.

We still need to clean up the `/usr/local/bin/service` wrapper after the build anyway, so perhaps what I should do is implement a final clean up as part of the TKLDev build process? There is already support for a `removelist` (both in common and per appliance). However, I think a `removelist` in common, which runs right at the end would probably be ideal.

I guess you don't know quite yet, but if there is a single generic file (i.e. same file no matter what the appliance) to delete, we can easily clear the token from common. Worst case, I guess we could add it to all the appliances which include Composer?!

Let me know your thoughts. Cheers.

**Comment by JedMeister** [comment]
BTW, great work on this @spaghettimaster I have merged your code, but I'd like to do a little more testing myself to be sure that it's going to work exactly how we need it to. I'm sure it'll be good though! :smile:

**Comment by spaghettimaster** [comment]
Hey @JedMeister, a little reminder -  there is another one PR to `fab`:
https://github.com/turnkeylinux/fab/pull/4/

**Comment by JedMeister** [comment]
Thanks tons for the bump @spaghettimaster! I'll review and merge that now! :smile:

**Comment by JedMeister** [comment]
I'm going to close this now. We still need to build the updated package and do some final testing, but I'm going to close this for now.

**Comment by JedMeister** [comment]
Actually, changed my mind... I'll build the package first... Then I'll come back and close this...

**Comment by JedMeister** [comment]
Ok, the updated pacakge (for both jessie and stretch) is in my dev-test repo. Although if you don't already have it installed in your TKLDev (v14.2) then probably the easiest way to install is via wget and dpkg:
```
wget https://s3.amazonaws.com/dev-apt.jeremydavis.org/pool/f/fa/fab_0.6%2B246%2Bgcd4f542_amd64.deb
dpkg -i fab_0.6+246+gcd4f542_amd64.deb
```
