### ISSUE TITLE
Bugzilla aws marketplace instance; faulty bugzilla domain

### ISSUE THREAD

**Issue by gr9** [turnkeylinux/tracker#828]
Steps:

1) install turnkey bugzilla from AWS market place version 14.1 (Linux/Unix, Debian 8 (Jessie) | 64-bit Amazon Machine Image (AMI) | Updated: 8/25/16) (not the other 2 versions that are available)
2) Select to run on t2.micro, with 10gb of hd space
3) SSH into the instance using the admin account and fill out all mandatory fields for the admin passwords etc that are required
4) enter a 'bugzilla domain' when asked; I used bugzilla.tbadigital.com (I then created an A type pointer in my dns to point to the public ip for the aws appliance)
5) complete all other questions from the setup prompt - I tried installing security updates, and not installing security updates
6) Visit the bugzilla website either using the IP address of the aws appliance; e.g. http://111.22.33.44 or by using the domain name setup using first ssh login prompt mentioned in step 4 (e.g. http://bugzilla.tbadigital.com).
7) Try logging into bugzilla using the credentials that were setup in step 3; 

Error; you can't login; you get a 404 error.  Bugzilla appears to be incorrectly handling the domain e.g. if I tried logging in at http://bugzilla.tbadigital.com then the login form tries submitting to: http://bugzilla.tbadigital.com/bugzilla.tbadigital.com/index.cgi and same if accessed via IP address.  If I manually edit the html that is sent to my browser to make the form submit instead to http://bugzilla.tbadigital.com/index.cgi then I can log in; but this is a manual code hack & is not a feasible end user request.  During ssh setup prompt the domain field is mandatory.

**Comment by JedMeister** [comment]
Thanks heaps for the bug report. I'll look into it ASAP.

Actually, your timing is impeccable as I'm currently working on v14.2 and haven't got to the Buzilla appliance yet.

**Comment by JedMeister** [comment]
This should have been resolved ages ago (with the v14.2 update).

If you are still having issues with the new appliance. Please let us know ASAP (and/or reopen this issue).
