### ISSUE TITLE
Django not working

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#830]
Just built Django v14.2 and it's failing with "Bad Request (400)":

![screenshot from 2017-05-11 10 37 05](https://cloud.githubusercontent.com/assets/818633/25926942/cb658ac2-3635-11e7-9152-be08803f74ae.png)

**Comment by JedMeister** [comment]
This was due to a change in Django that requires you to now set a domain to server from. Fixed as of the v14.2 release (when it gets here).

**Comment by pauloalcobia** [comment]
ho do I fix it in my VM?

**Comment by JedMeister** [comment]
Hi @pauloalcobia

If you are using TurnKey v14.2 this issue should already be be fixed. 

You need to set a domain and then configure DNS to point to your server (or add a local hosts file entry if using for development on a LAN or in a local VM). Then everything should "just work".

An alternate approach is to edit `/var/lib/django/allowed_hosts` so that it will allow access via IP address.

**Comment by pauloalcobia** [comment]
Thanks,
Is there a easy way to switch to python3.4 in django?

**Comment by JedMeister** [comment]
Hi @pauloalcobia

Unfortunately not. But thanks for bringing it up. We should certainly create a Django appliance based on Python3 for our next release (which should be fairly soon).
