### ISSUE TITLE
Stunnel causes failures when testing shellinabox and webmin 

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#833]
The 14.1 configuration, /etc/stunnel/stunnel.conf, results in failures when testing the shellinabox and webmin ports using Ansible.  The solution is to set the parameter, TIMEOUTclose, to zero in both sections of stunnel.conf.  The resulting config should look like this.
```
...snip...
[shellinabox]
accept  = 12320
connect = 127.0.0.1:12319
TIMEOUTclose = 0

[webmin]
accept  = 12321
connect = 127.0.0.1:10000
TIMEOUTclose = 0
```
Reference: RedHat Enterprise Linux 7 Security Guide, Section [4.9.2. Configuring stunnel as a TLS Wrapper](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Using_stunnel.html#sec-Configuring_stunnel_wrapper)

**Comment by JedMeister** [comment]
Thanks for providing the link John. 

It sounds like Ansible is acting like MSIE?! :frowning: According to the [stunnel docs](https://www.stunnel.org/static/stunnel.html):
````
TIMEOUTclose = SECONDS
time to wait for close_notify (set to 0 for buggy MSIE)
````
Also, not sure if related or relevant; from the [stunnel FAQ](https://www.stunnel.org/faq.html):
````
It is a well known problem with Internet Explorer and several other products. They do not send close_notify message before TCP FIN packet violating SSLv3 and TLSv1 protocols. It is also a security problem: Microsoft applications are vulnerable to truncation attacks. Is Microsoft able to implement anything properly?
Currently stunnel implements ugly 10-seconds timeout to work with Microsoft... I hate it, but several peple need it.

See RFC 2246 chapter 7.2.1. for details.
````

Anyway, from my reading I didn't see anything that appeared alarming about using that setting, so I've merged it and we'll run with it. I'll make a point of double checking Webmin and Webshell manually on a couple of appliances to make sure it's all good.

Thanks again John.

**Comment by JedMeister** [comment]
As i've merged, I'll close this too...
