### ISSUE TITLE
install concrete5 via composer

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#835]
Concrete5 should be installed via composer but is currently installed from upstream source

blocked by https://github.com/turnkeylinux/tracker/issues/826

**Comment by JedMeister** [comment]
Seeing as the v15.0 app code has already been updated, I'm going to defer this to v15.1.

FWIW, we should have #826 resolved by the v15.0 release, so this should be trivial for v15.1.

**Comment by qq7** [comment]
This was fixed with https://github.com/turnkeylinux-apps/concrete5/pull/17, wasn't it?

**Comment by JedMeister** [comment]
Closing this one now...
