### ISSUE TITLE
ZenCart - can't login

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#840]
It is not possible to log into ZenCart using the email and password set at firstboot. I get a message "Error: Sorry, there is no match for that email address and/or password."

I also tried to use just the username 'admin', but that failed due to not being a proper email addy.

**Comment by OnGle** [comment]
IIRC zencart's admin interface is at /manage and is working, perhaps just not very obvious. This PR makes things a little more obvious https://github.com/turnkeylinux-apps/zencart/pull/13
