### ISSUE TITLE
Prestashop inithooks require tweak

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#841]
It looks like the 20regen-prestashop-secrets needs tweaking.

It tries to edit the config file found at /var/www/prestashop/config/settings.inc.php, however, it appears that's been deprecated. The new location appears to be /var/www/prestashop/config/bootstrap.php

I tested that and it seems to work now. However, I still couldn't log in with the password and email I set, so it looks like that needs some further work...

**Comment by OnGle** [comment]
I set configuration in `/var/www/prestashop/config/parameters.php` but looking now, perhaps if the parameters.yaml file is populated it takes precendence. Which would be cleaner. 

For the time being though, prestashop login works and has been updated.

**Comment by JedMeister** [comment]
Great work. Thanks man.
