### ISSUE TITLE
EspoCRM curl install not working with latest upstream version

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#842]
It seems that the curl install method we use to achieve a non-interactive for tons of appliances, no longer works with the latest version of EspoCRM. 

As we're way behind on version, obviously we've updated the curl strings to match the new installer. But even when we replay the exact communication that we capture (with a web browser doing it manually) it just gives an error message (whereas when done manually in a browser it works).

@AlexAv - do you have ideas or pointers for us? We don't need to do the install via curl, it just needs to be scriptable and non-interactive.

We haven't pushed the updated code that we've been working with (because it doesn't work - at all) but if that would add value, we probably can.

**Comment by qrntz** [comment]
Could be one of two things:
1) The installer uses JS;
2) The installer is picky about something like an actual browser being emulated (if so, we could probably use twill to script it but I did not try that).

**Comment by JedMeister** [comment]
Thanks @qrntz. I was under the impression that even javascript calls would be captured by the web browser (Chrome seems to not catch them all, Firefox appears to capture them, but perhaps not all?). Perhaps we should give twill a try?

Hopefully @AlexAv has some ideas or pointers for us...

**Comment by JedMeister** [comment]
FWIW @ongle worked it out. It required some curl trickery... :smile: See https://github.com/turnkeylinux-apps/espocrm/commit/168a883b2f7708c1db00752046bc3a464c31a10e#diff-29ac556b17810d3f96aef099659745db
