### ISSUE TITLE
Confconsole - Let's Encrypt - can't specify 2 domains on 1 line

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#843]
I tried to use Confconsole to generate a certificate for one site that runs on a .com and a .cz domain and it told me one is not a subdomain of the other. I had to use dehydrated-wrapper manually.

Suggestion - modify the form to allow to specify the lines in dehydrated config directly. Each line is one certificate. The domains need not be related. (Have a look at homeatcloud.com, for example)

**Comment by JedMeister** [comment]
Hey @vondrt4 

Thanks for having a look. You are correct, currently that is a limitation. We decided to keep the initial release simple. FWIW, as it uses dehydarated, you can just add the additional domains to the domains.txt. it's all fairly well [documented](https://www.turnkeylinux.org/docs/confconsole/letsencrypt).

**Comment by JedMeister** [comment]
I was just thinking some more about this one. 

Perhaps what we should do, is change confconsole so that asks for separate domains on new lines, but (space separated) multiple sub-domains could be included on a single line. That would make it consistent with dehydrated's domain conf file.

**Comment by vondrt4** [comment]
The point is that dehudrated creates one certificate for every line in the config. So if I want to do an apache VHOST like
`ServerName xxx.cz
Server Alias xxx.com`
I also need one certificate that has both the domains specified. It works quite well, but not when confconsole checks if one is a subdomain of the other.

**Comment by JedMeister** [comment]
Oh ok. I was under the impression (IIRC I read it in the Dehydrated docs) that each individual domain needs to be on a separate line, but additional sub-domains can be on the same line (as the domain that they are a sub-domain of).

I was under the impression that you couldn't get a single certificate to cover multiple domains (unless they are sub-domains). Although obviously you can combine multiple certs into a single file. Either my understanding of how it works is not quite right, or perhaps my understanding is right, but dehydrated is just smart enough to create separate certs, but just write them to a single file?

We should certainly look at how we can improve this for v15.0 either way!

**Comment by vondrt4** [comment]
Nope. The Letsencrypt servers just validate all the domains that you put on one line and create one cert. The first name will in its CNAME and all of them in Subject Alt Name. Maybe there's a limit on how many you can put on one line, but I have not hit it yet :-).
Try drive.homeatcloud.com and .cz. It is the same cert. And it was created by dehydrated.

**Comment by JedMeister** [comment]
The code to provide this has been pushed to our stretch repo, so will be included in the upcoming (really soon I hope!) v15.0 release...
