### ISSUE TITLE
Confconsole - Mail relaying - can't specify a local mail server without password

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#844]
...yes, I have one that services my whole local network without authentication. I had to edit postfix config manually.

**Comment by JedMeister** [comment]
Hmm ok. We didn't expect that! :smile:

I guess instead of failing if you don't enter a password, it should probably just ask to confirm that there is no password.

**Comment by JedMeister** [comment]
FWIW another user just bumped into this one (reported via the [forums]()). He additionally noted that to do it manually:

> The solution was to add the following line to /etc/postfix/main.cf:
> ```
> relayhost = [10.0.0.50]
> ```
> In other words, just specify the IP address of your internal mail relay that doesn't require authentication.  Using a different port might look like:
> ```
> relayhost = [10.0.0.50]:465
> ```
