### ISSUE TITLE
Confconsole - Hostname - does not set FQDN and hostname at once

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#845]
It should seprate the part before the first dot and put that to /etc/hostname. The whole FQDN and the hostname should go to /etc/hosts

**Comment by JedMeister** [comment]
Hmmm ok. Fair call...

**Comment by JedMeister** [comment]
Argh! This _should_ have been resolved in v15.0! Unfortunately it was missed (because it didn't have an appliance tag...). I've now added core and will move it to v15.1.

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux/confconsole/commit/7183d256cf1d111cb8e8601d09343c6fdeda9b14
