### ISSUE TITLE
Confconsole - Network config should be disabled on cloud builds

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#846]
As per updated subject; all cloud builds should have networking disabled. - @jedmeister

----

In a cloud setting, leaving the user a menu to change the configuration of the first network card is a way to let him make the cloud instance inaccessible. There should probably be at least a warning.

**Comment by JedMeister** [comment]
Yes there is.

Unfortunately the networking component is old baked in code, whereas the other new stuff are all provided as plugins (so extras can be included and the existing ones removed). However, we did anticipate that use case. You can disable it in the config file (IIRC it should be /etc/confconsole/conf or something similar) with `networking false`. Here's what it should look like by default:
````
# default network interface to display in usage
#default_nic eth0

# command to get public ipaddress to display in usage
#publicip_cmd curl -s https://api.ipify.org
#publicip_cmd ec2metadata --public-ipv4
networking true
````

**Comment by JedMeister** [comment]
Maybe we should make that the default on the OpenStack builds then?

[off topic] Speaking of which, I resolved the first issue we had with the OpenStack build, but still haven't had a chance to have a look at the other one. Obviously supporting cloud-init would solve it, but as we have big rewrite plans for a lot of software in the near future, we're pretty loathe to tinker too deeply with code just yet. Alon suggested that we could just add a inithook to read the metadata on the OpenStack builds for now. Would that do the trick for you?

**Comment by vondrt4** [comment]
Ah, thanks. Maybe I should have RTFMed more :-).

I would disable it in the "cloud" module of buildtasks. I think that all it applies both to AWS and OpenStack that the primary interface is configured by DHCP and if you reconfigure it, you will make bad things happen, like desynchronizing the IP address written in the dashboard with reality, breaking instance liveness checks, or outright cutting off access if MAC to IP pinning is in place. (I'm not sure how often that's the case in reality, but OpenStack has pluggable network layers, so it will be there at least in some of them.)

I would not block the release of the OpenStack build because of the hostname setting. I suggest that Alon writes the inithook module and adds it to all cloud builds - when he has the time. The behavior should be the same for all TKL builds.

**Comment by JedMeister** [comment]
All good. Having a manual to read for TurnKey software is probably a shock! :smile: (we probably should add in proper man pages actually...)

Ok, we'll make that the default for all cloud builds going forwards. I'll repurpose this issue if you don't mind.
