### ISSUE TITLE
PostgreSQL with LDAP authentication

### ISSUE THREAD

**Issue by microchipe** [turnkeylinux/tracker#847]
Hi, i tried to use the turnkey postgresql vm, and looks like ldap auth support was not built into that, can you guys include that?
I'm sure there  will be many use cases for that, and ldap is a very common  auth method to be left out.
Thanks in Advance.

**Comment by microchipe** [comment]
Sorry, my bad. Turns out that i've managed to make it work, was some typo on my config that caused the issue. My problem now is just the version , and I'll need pgsql 9.6, and the turnkey version now is 9.4. Thanks.

**Comment by JedMeister** [comment]
Ok cool. I'll close this then. Unless you want to leave it open as a feature request ("add LDAP authentication option to appliances" or something similar)?! TBH, I know of at least one other community member that would potentially agree (and possibly even be interested in implementing it). If so, please feel free to reopen.

WRT to PostrgreSQL version, yes the current version in Debian is [9.4](https://packages.debian.org/jessie/postgresql). The next major release (v15.0 - no ETA yet) will be based on Debian Stretch which includes [9.6](https://packages.debian.org/stretch/postgresql). In the meantime, you could install 9.6 from Jessie backports as that also has [9.6](https://packages.debian.org/jessie-backports/postgresql).

It should be a fairly easy install to configure and install so long as you keep in mind that TKL v14.x is basically Debian Jessie under the hood. Please keep in mind though, that backports (and most third party repos I've come across) **do not** provide security updates in a way that is safe to automate. So please keep in mind that once you move away from, default Debian (or TurnKey) packages, then you **will not** get automated security updates for that software; you'll need to manually track the security status of those packages and manually install updates as required. Debian backports **does not** guarantee timely security fixes (which main does) although in my experience, they usually upload updated packages relatively quickly. Obviously any other third party repos are an unknown quantity WRT to security updates.

The only other thing you will need to keep in mind is, that if you are using TKLBAM for backups, you may encounter some hurdles if you migrate your data to a new machine (i.e. restore your TKLBAM backup to a new machine). By default TKLBAM tracks packages that you install, but on restore, it will only reinstall packages which come from Debian main or TurnKey (not backports or third party repos). You can work around that manually by configuring and installing Postgres 9.6 **prior** to restoring your backup. You could also automate that if you chose in a TKLBAM pre-restore hook.
