### ISSUE TITLE
OpenVPN constant crash/restart

### ISSUE THREAD

**Issue by chariga** [turnkeylinux/tracker#848]
Our AWS Turnkeylinux OpenVPN server restart constantly, few times a day.

Please help.

Best regards,

Chris HARIGA

**Comment by JedMeister** [comment]
Hi Chris,

This is our issue tracker and is just for explicit bug reports or feature requests.So I'm closing this now.

I'll also need to know a lot more info about your server before I could even guess what might be wrong.

For public community support (which will almost certainly still be me) please post on our forums in the [support section](https://www.turnkeylinux.org/forum/support).

As an Amazon MarketPlace and/or TurnKey Hub user, you also have the option of contacting me directly via the support portal within the Hub. Alternatively, emails to support AT turnkeylinux.org also go to the support portal.

Either way, when you post, please provide information about what version of TurnKey it is, which region, instance size, architecture, etc. Also any other info that might help us track down the issue would be good. Info such as how long the server has been running, how long the issue has been occurring, any specific config you are using, anything you may have already tried to diagnose and/or resolve the issue, any log messages that you may have seen or discovered, etc.

Look forward to hearing from you on the forums or via the support portal.

Regards,
Jeremy
