### ISSUE TITLE
TYPO3 not building for v14.2

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#854]
In theory, the TYPO3 appliance should auto build to latest v7 LTS. However, it's currently failing:

Tail end of the build log (first line matches [line 51 of conf.d/main](https://github.com/turnkeylinux-apps/typo3/blob/master/conf.d/main#L51)):

````
+ composer require typo3-ter/introduction
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.0 for typo3-ter/introduction
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for typo3-ter/introduction ^3.0 -> satisfiable by typo3-ter/introduction[3.0.0].
    - typo3-ter/introduction 3.0.0 requires typo3/cms-core >= 8.0.0, <= 8.9.99 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
/usr/share/fab/product.mk:526: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 2
````

A quick google suggests that [`ter` is no longer supported](https://typo3.org/extensions/repository/view/ter)?!

@qrntz - I hope you don't mind, but I've assigned you.. Seeing as you did the initial work to support composer install, you seem like the best person for the job... :smile:

**Comment by qrntz** [comment]
Looks like they obsoleted the Composer installation method, too. This upstream...

**Comment by qrntz** [comment]
The version we are installing is outdated now. The latest stable version of TYPO3 requires PHP 7, which is not in Jessie.

**Comment by JedMeister** [comment]
I see that the v8 branch is the current latest and does require php7. However, according to the [download page](https://typo3.org/download/) (click the "TYPO3 v7 LTS" tab in the middle) the v7 branch will still receive:

>Security-related and important bugfixes until November 2018

The release page for the latest v7 branch can be found here: https://wiki.typo3.org/TYPO3_CMS_7.6.18

**Comment by qrntz** [comment]
That one's not in their Composer repo and it seems none of the 7.x versions are anymore. That's what I meant by "outdated" but should have specified in detail.

Actually I don't know why because the [docs](https://composer.typo3.org/) refer to 6.x and 7.x.

I can change it to use the regular package instead.

**Comment by JedMeister** [comment]
Ah ok. Sorry I misunderstood...

That's a bit of a pity but it sounds like your proposed solution is the WTG for now... We'll go back to composer once we rebase on Stretch (and have PHP7).

**Comment by qrntz** [comment]
OK, sounds good.

**Comment by qrntz** [comment]
Actually I was wrong on this.
