### ISSUE TITLE
WordPress appliance has old v3.x version installed!?

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#858]
Reported via support.

WordPress must have changed how they host their downloads. Currently we are installing the "latest" version via a url (see [here](https://github.com/turnkeylinux-apps/wordpress/blob/master/conf.d/downloads#L10)). However, the current release (v14.2) only has v3.x, latest release is 4.8!

**Comment by qq7** [comment]
Just made a fresh build from repo and downloaded .iso from https://www.turnkeylinux.org/wordpress
They both appear to have 4.8 installed
http://imgur.com/a/jZbUy

**Comment by qq7** [comment]
Just downloaded one from https://www.turnkeylinux.org/wordpress and built one from repo

Published version has 4.7.4 onboard and the built one builds with 4.8
![screenshot2017-06-1517 07 22](https://user-images.githubusercontent.com/21182031/27185407-e91dac06-51ed-11e7-8b5d-bc37469a312c.png)
![Uploading Screenshot2017-06-1516:54:14.png…]()

**Comment by JedMeister** [comment]
Hmmm, that's weird?! A Proxmox user (container build) noted this and I was able to reproduce it (with in a container on Proxmox). I wonder what is going on?

I'll need to investigate further... Thanks for double checking @qq7

**Comment by JedMeister** [comment]
I'm going to close this. I think the user (and I) was (were) mistaken...
