### ISSUE TITLE
Namespace collision when starting a new project

### ISSUE THREAD

**Issue by Dude4Linux** [turnkeylinux/tracker#860]
I'm seeking guidance or suggestions re: naming of new projects.  I've started development of a Mautic appliance for TurnKey GNU/Linux. Mautic provides social media marketing automation and looks like a good fit for TurnKey as it has plugins for Drupal, Wordpress, Joomla, SugarCRM, etc.
To start, I forked the project from https://github.com/mautic/mautic because I want to be able to contribute development work upstream. Now that I've successfully got the project running on a LAMP appliance, I want to convert to a TKLdev build. Normally I would start a new project named mautic and sync it to my TKLdev project directory, however, in this case, the repo mautic already exists. I've not been able to find a way to have github repo's with the same name, and it might be too confusing anyway.

I'm thinking of naming the second repo, tkl-mautic, to clearly indicate that it is the project for TKLdev, but I'm not sure if there will be any downsides later on. Has anyone else faced this dilemma before? Is there a naming convention for new projects?

**Comment by DocCyblade** [comment]
Hey John!

When I start a new TKL project I like to prefix with "tkl-" keeps things tidy and keeps conflicts like you have brought up. When Jermey forks your project to the official repo he can and will rename it. 

Take a look at the [Odoo appliance for an example.](https://github.com/turnkeylinux-apps/odoo)

**Comment by qrntz** [comment]
Also what you could do is rename your forked repo.

**Comment by Dude4Linux** [comment]
Thanks @DocCyblade I think I'll adopt that convention from now on. @qrntz I could rename the original forked project, but what should I call it. mautic-mautic seems odd. I think the 'tkl-' prefix will always let me and Jeremy easily know which repo belongs to TurnKey.
