### ISSUE TITLE
Include Webmin OpenLDAP module (OpenLDAP appliance)

### ISSUE THREAD

**Issue by mredig** [turnkeylinux/tracker#864]
I had to run `apt install libnet-ldap-perl webmin-ldap-server` to get the OpenLDAP webmin module to load. 

PLA is great, but it doesn't appear to have ACLs built in (and I definitely don't want anonymous access to read the personal info I'll be storing)

I apologize as I don't know how to label issues.

**Comment by JedMeister** [comment]
Hi @mredig thanks for reporting. You are right, it would make plenty of sense to ship the appliance with the LDAP Webmin module! Thanks for providing the info on the missing dependency too.
