### ISSUE TITLE
Let's Encrypt not working right (OpenLDAP appliance)

### ISSUE THREAD

**Issue by mredig** [turnkeylinux/tracker#865]
The issue:
1. ![1](https://user-images.githubusercontent.com/6509485/27455175-0a2eacaa-5762-11e7-8a08-3632f589b311.png)
1. ![2](https://user-images.githubusercontent.com/6509485/27455194-1469427a-5762-11e7-8a7f-24d668cf5909.png)
1. ![3](https://user-images.githubusercontent.com/6509485/27455200-186641e8-5762-11e7-8bd2-7b00841f6a0f.png)
1. ![4](https://user-images.githubusercontent.com/6509485/27455208-20fe9288-5762-11e7-9dd0-e8d1a8550882.png)
1. ![5](https://user-images.githubusercontent.com/6509485/27455212-25b55b2c-5762-11e7-914a-5412ac1a7298.png)
1. ![6](https://user-images.githubusercontent.com/6509485/27455215-29717570-5762-11e7-9012-68577f75c31c.png)

I was able to (temporarily? it won't work for auto updates as this is a manual requirement) get it to work by running `service lighttpd stop` before running the letsencrypt menu option. Of course, once it's done, I have to start lighttpd back up again `service lighttpd start`.

The issue appears to arise from the conflict where the default services are running on port 80, but letsencrypt also tries to run on port 80 with its own service instead of utilizing the existing one.

**Comment by JedMeister** [comment]
Hi @mredig thanks for the bug report.

That is very strange as it should be stopping lighty before it runs the dehydrated script (which uses a simple http server we've called `add-water`). I did test it with all the different webservers we use, but something must have slipped through... I'll look into it ASAP and get back to you with a proper fix.

**Comment by JedMeister** [comment]
Hmm, ok. I just had a quick browse of the code and I think I can see what's going on (although still not sure why). It appears that for some reason, instead of getting the name `lighttpd` as the name of the webserver; it's seeing it as `lighttpd\nlighttpd` (i.e `lighttpd` twice separated with a new line)...

Unfortunately I can't clearly see why it would be doing that on the OpenLDAP appliance. FWIW I tested fairly thoroughly on a number of different appliances which had lighttpd installed, but not the OpenLDAP appliance specifically. Looks like I'll need to dig in a bit deeper to work this out...

**Comment by mredig** [comment]
Could it have to do with the entry tool not displaying multi lines and whoever configured it accidentally hit return?

**Comment by mredig** [comment]
* multi lines in text fields

**Comment by JedMeister** [comment]
I don't think so. I'm pretty sure that it's the [`check_80`](https://github.com/turnkeylinux/confconsole/blob/master/plugins.d/Lets_Encrypt/dehydrated-wrapper#L113) function returning multiple lines. When I wrote it, I didn't account for the possibility it may return multiple lines. So if you want to have a hack on it, you could try tweaking it.

If we force it only return the first line of results that should solve it.

So we need to change line 113 from:
````
netstat -ltpn | grep ":80 " | cut -d/ -f2 | sed -e 's|[[:space:]].*$||'
````
to:
````
netstat -ltpn | grep ":80 " | head -1 | cut -d/ -f2 | sed -e 's|[[:space:]].*$||'
````

Here's a sed line to try from the commandline and see if that fixes it:
````
sed -i.bak "/netstat -ltpn | grep/ s/| cut/| head -1 | cut/" /usr/lib/confconsole/plugins.d/Lets_Encrypt/dehydrated-wrapper
````

**Comment by JedMeister** [comment]
I've tested my workaround and it seems to work. I just want to do a little more testing. FWIW, here's an alternate way (to the `sed` line above) to apply my fix:
````
apt-get update && apt-get install patch
cd /usr/lib/confconsole/
wget https://github.com/turnkeylinux/tracker/files/1107224/confconsole-patchfile.txt
patch -b -p1 < confconsole-patchfile.txt
````
[confconsole-patchfile.txt](https://github.com/turnkeylinux/tracker/files/1107224/confconsole-patchfile.txt)

Hopefully, we'll release a new version this week.

**Comment by JedMeister** [comment]
I've merged the code which has closed this issue. Hopefully we'll have a new package out really soon.

**Comment by JedMeister** [comment]
@mredig - there is a new confconsole package in the repos. If you haven't already applied one of the above workarounds, then please install that (or install it anyway if you want! :smile: ).
````
apt-get update && apt-get install confconsole
````

**Comment by mredig** [comment]
Updated and got no error when trying to renew my cert! I haven't checked that that actually worked (and I assume it did nothing cuz the very is recent), but it appears to be an improvement!

**Comment by JedMeister** [comment]
Awesome, thanks for the feedback. 

Please let us know ASAP if you have any further issues with confconsole, or anything to do with TurnKey really. We love feedback, especially when it's constructive criticism. We know we're far from perfect, but we figure that via community feedback we can keep slowing creeping towards it! :smile:
