### ISSUE TITLE
how to uninstall lanmp stack

### ISSUE THREAD

**Issue by xsdhy** [turnkeylinux/tracker#866]
how to uninstall lanmp stack

**Comment by JedMeister** [comment]
Hi @xsdhy 

Firstly, I'm not really quite sure what you mean. We provide software appliances, so if you installed our LAMP stack, then you are probably running it in a VM or a container (or on Amazon etc). So to "uninstall" it, you just remove the VM/container/whatever and then it's gone...

Secondly, this is our issue tracker; for posting bug reports and feature requests. It's not intended for support. For general support, please post on our [support forums](http://www.turnkeylinux.org/forum/support/).

Regards,
Jeremy
