### ISSUE TITLE
HubDNS weirdness...

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#867]
I just launched a new server from the Hub and set a tklapp.com domain name for it.

The instance is up and running and I can contact it via the IP address or the AWS DNS name. However, the tklapp.com domain seemed to be taking a long time to update, it was still pointing to the default tklapp.com page which displays:

>The site you are looking for is currently not available.

````
user@ninjux ~$ dig ldap-test.tklapp.com

; <<>> DiG 9.9.5-9+deb8u11-Debian <<>> ldap-test.tklapp.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35320
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ldap-test.tklapp.com.		IN	A

;; ANSWER SECTION:
ldap-test.tklapp.com.	85436	IN	CNAME	tklapp.com.
tklapp.com.		86399	IN	A	23.21.244.168

;; Query time: 172 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jun 28 09:55:01 AEST 2017
;; MSG SIZE  rcvd: 79
````
So I decided to see if I could speed it up by forcing HubDNS to update. So on the server:
````
root@openldap ~# hubdns-update
Updated ldap-test.tklapp.com. with 54.206.85.130
````
According to dig, that appeared to work almost instantly:
````
user@ninjux ~$ dig ldap-test.tklapp.com

; <<>> DiG 9.9.5-9+deb8u11-Debian <<>> ldap-test.tklapp.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29553
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ldap-test.tklapp.com.		IN	A

;; ANSWER SECTION:
ldap-test.tklapp.com.	9	IN	A	54.206.85.130

;; Query time: 208 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jun 28 09:55:41 AEST 2017
;; MSG SIZE  rcvd: 65
````
But when I tried to browse to the site via my browser, I still get the tklapp default/error page. I thought that may have been just because of browser caching, so I cleared my cache and opened it in an incognito window for good measure. But still getting the same default tklapp page?!

So I double checked dig, and it's changed back again - WTF?!:
````
user@ninjux ~$ dig ldap-test.tklapp.com

; <<>> DiG 9.9.5-9+deb8u11-Debian <<>> ldap-test.tklapp.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58097
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ldap-test.tklapp.com.		IN	A

;; ANSWER SECTION:
ldap-test.tklapp.com.	85367	IN	CNAME	tklapp.com.
tklapp.com.		85367	IN	A	23.21.244.168

;; Query time: 30 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jun 28 09:56:03 AEST 2017
;; MSG SIZE  rcvd: 79
````

I retired again and same result... (`hubdns-update` works almost instantly, but then within a minute (or perhaps less) it switches back to the default tklapp.com IP.

However, I note that in the time it's taken me to write this, it now appears to finally be working properly.  It seems like something on the Hub end is keeping it locked to the default tklapp.com IP until it's ready to let it go?! Perhaps there is some race condition going on?

Perhaps this is the real issue behind #618?

**Comment by qrntz** [comment]
In my experience it might depend on your router's DNS caching. I used to use an actual router and get this all the time (so I'd have to use the IP to connect to the instance) but when I switched to using dnsmasq on a Linux machine configured as a router it went away. I have not investigated the issue in depth.

**Comment by JedMeister** [comment]
Hmmm, thanks for that. Sounds like it's worth investigating. I think I can install dnsmasq on my router... I'll have to check.

**Comment by JedMeister** [comment]
I'm going to close this now as I think (as noted) that it's to do with my local setup.
