### ISSUE TITLE
Redirect Django http access via IP to domain set in firstboot

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#869]
For v14.2 Django requires a domain name to serve from. However, most of our documentation suggests that you can access machines via IP address. So for the next release the Django appliance should auto redirect to the url that was set...

**Comment by JedMeister** [comment]
I've tagged it as a bug to make it clear it will need doing for v15.0

**Comment by JedMeister** [comment]
@spaghettimaster - just trying to tidy up issues and noticed that this one is a part of #958 (assigned to you) and has been ticked off there, but browsing the repo, I'm not 100% clear on whether it's been done or not?

From a glance over the most recent [PR](https://github.com/turnkeylinux-apps/django/pull/11) I can't see it (but perhaps I'm missing something?)

**Comment by spaghettimaster** [comment]
In this  [PR](https://github.com/turnkeylinux-apps/django/pull/11) I added mask to the "'/var/lib/django/allowed_hosts'" so now Django available via domain and also via IP.

Is this a good alternative to redirection?

**Comment by JedMeister** [comment]
@spaghettimaster - ah ha! That's fine, it's just that I missed that detail in my review! Thanks for clarifying! :smile: 

So I'll close this then.
