### ISSUE TITLE
Make packages reproducible

### ISSUE THREAD

**Issue by lamby** [turnkeylinux/tracker#876]
Tools
----  

 - [x] pyproject — Pushed branch
 - [x] autoversion — Pushed branch
 - [x] pool — Pushed branch
  - [x] verseek — Pushed branch
- [x] fab — Pushed branch
 - [x] tklpatch — Pushed branch
 - [x] hubtools — Pushed branch
 - [x] cloudtask — Pushed branch
 - [x] chanko — Pushed branch
 - [x] repo — Pushed branch
 - [ ] <s>deck (skip)</s>
 - [ ] <s>deckdebuild (skip)</s>
 - [ ] <s>useraufs (skip)</s>

Appliance packages
----

 - [x] inithooks — Pushed branch
 - [x] confconsole — Pushed branch
 - [x] pycurl-wrapper — Pushed branch
 - [x] pythondialog — Pushed branch
 - [x] turnkey-pylib — Pushed branch
 - [x] turnkey-sysinfo — Pushed branch
 - [x] turnkey-version — Pushed branch
 - [x] tklbam — Pushed branch
 - [x] tklbam-duplicity — Pushed branch
 - [x] tklbam-python-boto — Pushed branch
 - [x] tklbam-squid — Pushed branch
 - [x] webmin-tklbam — Pushed branch
 - [x] casper — Pushed branch
 - [x] di-live — Pushed branch
 - [x] ebsmount — Pushed branch
 - [x] ec2metadata — Pushed branch
 - [x] hubclient — Pushed branch
 - [x] hubdns — Pushed branch
 - [x] tklamq — Pushed branch
 - [ ] luks (low priority)
 - [ ] theme-zukitwo (low priority)
 - [ ] webmin[-*] (low priority)
 - [ ] <s>shellinabox (low priority)</s> (using Debian package now)

**Comment by lamby** [comment]
Have been working on this although nothing to push just yet.

**Comment by lamby** [comment]
@JedMeister Was just about to push... but can you give me write access to these repos, at least to create branches? :)

**Comment by JedMeister** [comment]
Historically, we've always just got people to push to their own fork and do a pull request via GitHub. However, I can see that from your perspective, that would be a bit of a PITA. So I've just created a new group with push access to all those repos. I've protected the master branch, but you should be able to push a new branch.

PS I noticed that `shellinabox` is in [Debian](https://packages.debian.org/stretch/shellinabox) so perhaps we should switch to that, rather than continuing with our old fork (from before it was abandoned by the original developer). It seems like a no brainer to me...

**Comment by lamby** [comment]
@JedMeister 

> Historically, we've always just got people to push to their own fork and do a pull request via GitHub. However, I can see that from your perspective, that would be a bit of a PITA

Haha, somewhat. :) Thanks for giving me access.

> PS I noticed that `shellinabox` is in [Debian](https://packages.debian.org/stretch/shellinabox) so perhaps we should switch to that

Indeed. I wasn't going to touch it immediately as it was marked low priority.

Thanks again

**Comment by lamby** [comment]
(Been cranking through these, in case edits to the main text are not obvious!)

**Comment by OnGle** [comment]
Oops, I accidently clicked one of the tick boxes, sorry about that. Incidently, awesome work!

**Comment by lamby** [comment]
No problem; ticking the boxes doesn't alert anyone I think.

**Comment by lamby** [comment]
(And more...)

**Comment by lamby** [comment]
Aaaaaand more.

**Comment by lamby** [comment]
Not entirely sure what to do with `tklbam-squid` - the packaging is *so* old and crufty its difficult to update. It doesn't autoreconf too. :/

**Comment by lamby** [comment]
All done :)

**Comment by JedMeister** [comment]
Great work Chris! :smile: I'll shoot you an email shortly.

**Comment by lamby** [comment]
Not closing as not merged into master, but not sure what to do with this issue otherwise.

See also #883 re. travis integration

**Comment by JedMeister** [comment]
Thanks @lamby - We'll just leave them there in the branch you've pushed to for the moment. We'll merge them all once we move everything to Stretch. I'm not sure when that'll be done, but hopefully within the next few weeks.

**Comment by JedMeister** [comment]
Hey @lamby - I've started merging your branches into master. Out of interest, I thought I'd do it via GH pull requests and see how the tests went.

Firstly, [pyproject](https://github.com/turnkeylinux/pyproject) [failed in travis](https://travis-ci.org/turnkeylinux/pyproject/builds/264646359) although the failure looks to me like an apt issue. I haven't investigated further. I merged anyway as now that I've closed #910, I have tested building locally and all appears to be ok.

Also, I assume that I can I delete your branches once they're merged?

**Comment by JedMeister** [comment]
Actually, this is a bit weird. [GitHub shows](https://github.com/turnkeylinux/autoversion/pull/2) that travis "checks" both passed for autoversion, but [travis says otherwise](https://travis-ci.org/turnkeylinux/autoversion)?!

**Comment by lamby** [comment]
@JedMeister Yeah, it's some annoying issue with Travis's apt caching. I've asked them a couple of times what the deal is but yeah...

**Comment by lamby** [comment]
I'll change this in travis.debian.net for now.

**Comment by lamby** [comment]
@JedMeister https://github.com/lamby/travis.debian.net/commit/8e3f06e56c791522250eb1c41a7b14fc0fbfeaa3

**Comment by lamby** [comment]
I've restarted all the failing builds.

**Comment by JedMeister** [comment]
Ok all done merging. 

TBH, I haven't double checked that they are all reproducible (as i imagine that you have and/or will and/or have some infrastructure for testing that?!) but I did do a random test on `turnkey-version` and it passed with flying colours!:
````
root@da-shiz fab/pools# sha256sum A/turnkey-version_0+2017.7.24+16.38.10+e6ad7143_amd64.deb 
9d4d8a40e325c66e55158725327220258c2e39ad83d81204467ca07425301323  A/turnkey-version_0+2017.7.24+16.38.10+e6ad7143_amd64.deb
root@da-shiz fab/pools# sha256sum B/turnkey-version_0+2017.7.24+16.38.10+e6ad7143_amd64.deb 
9d4d8a40e325c66e55158725327220258c2e39ad83d81204467ca07425301323  B/turnkey-version_0+2017.7.24+16.38.10+e6ad7143_amd64.deb
````

I'm almost tempted to close this now?! Although there are still some packages that haven't been done, so perhaps we should leave it open for now? What say you @lamby?

**Comment by lamby** [comment]
Yes, let's close this up for now.

**Comment by JedMeister** [comment]
Hey @lamby - I just tested our [TKLBAM Webmin module](https://github.com/turnkeylinux/webmin-tklbam) and it doesn't seem to be reproducible?! For good measure, I built it 3 times (I know, no good reason and no real advantage...).
```
root@da-shiz pools/stretch# shasum build-1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
95f92d31a8ff43f97e8b71de41bd9503976da100  build-1/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
root@da-shiz pools/stretch# shasum build-2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
6c37463df4b58b8c7ab671149244ba450b3b7357  build-2/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
root@da-shiz pools/stretch# shasum build-3/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb 
756f69a12b665778f57522f55e685b180242bb15  build-3/webmin-tklbam_1.0+26+g7bbf82f_amd64.deb
```
Admittedly I have made [some tweaks](https://github.com/turnkeylinux/webmin-tklbam/commit/7bbf82f563932e75491ba9b80e159c4f1b60cd95) since you worked on it, so maybe it's something I broke? But after having a [look via diffoscope](https://try.diffoscope.org/gtbgaurdctfz.html) I'm pretty sure it's nothing to do with me.

Could you please have a look?

**Comment by lamby** [comment]
@JedMeister What distribution are building under?

**Comment by JedMeister** [comment]
Building on Jessie still. Would that be the cause? 

FWIW, it's the same system that I built `turnkey-version` on previously [which was reproducible](https://github.com/turnkeylinux/tracker/issues/876#issuecomment-322646298).

**Comment by lamby** [comment]
@JedMeister  Moved to #1028

**Comment by JedMeister** [comment]
Cheers @lamby - should have done that initially... :+1:

**Comment by JedMeister** [comment]
Turns out webmin is already reproducible! :smile:

**Comment by lamby** [comment]
Hurrah!
