### ISSUE TITLE
Need to document how to set up OpenVPN appliance as a client

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#880]
reported via support:

>[...] could explain how to setup an OpenVPN instance as a client? Your documentation only explains how to set one up as a gateway or site-to-site. [...]

The OpenVPN appliance can be configured as a server, in either "site-to-site" or "gateway" mode; or as a client (the other site in "site-to-site"). 

The "site-to-site" config actually covers the client side, but I think it would be good to separate them out. So we have 3 doc pages for the 3 different firstboot config options.

**Comment by OnGle** [comment]
I disagree on your appraisal. Site-to-site configuration doesn't make sense without a client-configuration and I believe it highly unlikely someone would install the turnkey-openvpn appliance purely to use openvpn as a client. Closing.

@JedMeister If you still disagree, please re-open and move to 17.0 (or later if relevant)
