### ISSUE TITLE
Add Travis CI builds for Debian packages

### ISSUE THREAD

**Issue by lamby** [turnkeylinux/tracker#883]
When working on #876 I was thinking it would be great if we ran package builds on Travis CI. This is quite trivial with my http://travis.debian.net/ service :)

If you agree, please grant enough access on Github to the repos mentioned in #876 and assign back — am currently seeing https://i.imgur.com/iuZWT5T.jpg.

**Comment by JedMeister** [comment]
Sounds good to me. @alonswartz will be back next week so let's bring it up with him.

**Comment by JedMeister** [comment]
Hmm, I just had a quick look. You already have full "write" access to those repos. The only other permission I can give is "admin" (which allows merges and adding new team members etc). Although I did protect the master branch, perhaps that's the issue? Does it need to push to master?

It doesn't seem right to me that it needs full admin rights just to run test builds? Or is that just to set it up initially?

**Comment by lamby** [comment]
First, I don't understand what buildbot has to do with this? Travis CI is a hosted service that just slurps in stuff from GitHub, no local admin machine, no extra users, no buildbot :)

@JedMeister wrote:

> Will you need the actual credentials (i.e. password) or will you just need an authentication token?

Neither. I just need to be able to add the Travis "integration" to the GitHub repos:

![](https://i.imgur.com/bjeou1H.jpg)

Or perhaps this is something you can do, or I can be an admin for 20 minutes. I can totally understand about not wanting to make me a permanent admin.

**Comment by lamby** [comment]
(Please assign back when done)

**Comment by JedMeister** [comment]
> First, I don't understand what buildbot has to do with this? Travis CI is a hosted service that just slurps in stuff from GitHub, no local admin machine, no extra users, no buildbot :)

Alon was keen to create a separate GH machine account (called tklbuildbot or similar -as per what we currently use with CircleCI) to manage the travis stuff. Rather than using your personal account (which no doubt has write access to tons of stuff). Then it could be a dedicated user purely for the purpose of travis builds (security). 

But regardless, it seems either way, that it needs full admin privileges. As GitHub is our "central" repos, we're not super keen about giving full admin access to you or a machine account (no offence; we're just paranoid). 

Is there another way around this? If not, then perhaps we need to consider setting up something specific ourselves?

**Comment by JedMeister** [comment]
Oops, I missed the last lines!

> Or perhaps this is something you can do, or I can be an admin for 20 minutes. I can totally understand about not wanting to make me a permanent admin.

No worries, if it's easy enough, I can take care of it, let me know what needs doing. I'll also check with Alon about giving you admin for 20, but if I can do it, that's probably preferable.

**Comment by lamby** [comment]
@JedMeister 

I don't see how opening another admin account improves security. (And I wouldn't call it ``buildbot`` as that overlaps with the entirely separate buildbot CI system!)

> Is there another way around this?

Sure. As I mentioned: http://travis.debian.net/#quick-setup ← *Any* admin just needs to follow this for all the repos mentioned in #876. I only need the first two steps doing, I can add the ``.travis.yml`` files.

**Comment by JedMeister** [comment]
> Sure. As I mentioned: http://travis.debian.net/#quick-setup ← Any admin just needs to follow this for all 
> the repos mentioned in #876. I only need the first two steps doing, I can add the .travis.yml files.

Oops, sorry, I missed that... Too many things on the go...

I'll take care of it ASAP (tomorrow I reckon I really need to knock off it's just gone 8pm)

**Comment by JedMeister** [comment]
Hey @lamby - apologies on the previous confusion and my misunderstanding. I've now added all those repos to Travis.org as requested. I was going to add `.travis.yml` to the repos (I actually did one) but then I realised that they should be added to the `git-buildpackage` branch (which we don't currently have), so I thought I might leave that to you if you don't mind?

**Comment by lamby** [comment]
@JedMeister 

Yes, leave the .travis.yml stuff to me — sorry, should have made that clearer :)

**Comment by lamby** [comment]
https://github.com/lamby/travis.debian.net/commit/cf08e803e5d34c445de2b7a2054e4432195b8d33

**Comment by lamby** [comment]
https://github.com/lamby/travis.debian.net/commit/a918d8800a81f79bff9acd03a4c39a9412c74ec0

**Comment by lamby** [comment]
https://github.com/lamby/travis.debian.net/commit/a918d8800a81f79bff9acd03a4c39a9412c74ec0

**Comment by lamby** [comment]
… and we have our first passing build!

https://travis-ci.org/turnkeylinux/pyproject/builds/256944234

**Comment by lamby** [comment]
Have (manually) configured the rest to match. For reference, this is:

 * Enabling "Only build when ``.travis.yml`` is present"
 * Setting ``TRAVIS_DEBIAN_DISTRIBUTION`` to ``stretch``

**Comment by lamby** [comment]
The next issue is to ensure some kind of repo for the common build-depends, specifically pyproject-common.

**Comment by lamby** [comment]
https://github.com/lamby/travis.debian.net/commit/f7af20ec9f6638d926fc87fdad892b455a34b892

**Comment by lamby** [comment]
After some changes, eg:

https://github.com/turnkeylinux/di-live/commit/879fe1ac7d2f2657984872eaf099eac78fd7d147
https://github.com/turnkeylinux/tklbam-duplicity/commit/cb94bea1ccb2a84d46e7ce6850d7c519f5b91014

.. as well as battling travis-ci's web interface (urgh), all of our repos with a lamby/packaging branch are passing :)

**Comment by JedMeister** [comment]
:+1: Nice work @lamby! You rock man!

**Comment by lamby** [comment]
![](https://i.imgur.com/thXPgoT.jpg)

**Comment by JedMeister** [comment]
Looking good! The latest merges I just did all passed too! :smile:

**Comment by lamby** [comment]
@JedMeister Shall we add a slack channel for failures to posted to?

**Comment by JedMeister** [comment]
@lamby - sounds like a mighty fine idea! :+1:

**Comment by lamby** [comment]
Lets close this for now given we've split off #931
