### ISSUE TITLE
Feedback re improvements for WordPress (and all LAMP appliances)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#886]
A user has commented on his Google Pagespeed results; now running from the Hub, vs his previous hosting. And there were a few areas where we could improve things OOTB. I'll list it all here for now, but we may wish to split this up into separate issues?

PageSpeed feedback that our WordPress appliance gave which didn't appear on previous host:
- Prioritize visible content - perhaps via WordPress plugin?
- Reduce server response time - default to Nginx instead of Apache? Easy way to disable unwanted services e.g. webmin, webshell, etc? other ideas?
- Minify HTML - not sure about this one? Perhaps this is a content thing? Or perhaps there's a WordPress plugin?

mod_pagespeed has been suggested and I agree. It looks like Google provide packages for Apache, or source code for Nginx ([here](https://developers.google.com/speed/pagespeed/module/)). I found quite a nice tutorial on building an Nginx package for it on [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-add-ngx_pagespeed-to-nginx-on-debian-8) so perhaps we could even consider packaging that (if we dump Apache as default and go for Nginx)?

PHP7 (default PHP in Stretch) will likely improve some apps straight away too. My reading suggests that WordPress in particular benefits significantly from the newer PHP.

**Comment by vondrt4** [comment]
I don't know about Wordpress plugins, but I'm pretty sure that the transition to Nginx would solve nothing. It is fast in serving static content. Everything in Wordpress goes through PHP.

If you want to accelerate it, you must employ caching to create the static content and ease the load on the CPU. Either as a Wordpress plugin, or the Apache mod_cache, or the Squid or Varnish caching proxy.

Disabling services will only free some memory, but will not speed up response time.

mod_pagespeed is quite controversial. It, for example, reduces the quality of images, which some users might not want.

**Comment by qrntz** [comment]
I believe most of our LAMP appliances don't use php-fpm (they should). But if/when they do, it makes more sense to keep nginx as the front-end webserver since it was _made_ to be a reverse proxy and it does the job better. If after that the performance is not up to par, we should think about optimizing caching.

If mod_pagespeed is controversial, we can make an inithook to toggle it.

**Comment by JedMeister** [comment]
I thought I'd replied to this already, but obviously not...

As per always, thanks tons for your input guys.

@vondrt4 - By my understanding server response time is at least somewhat linked to server resource availability?! So I was under the impression that reducing the server load (and Nginx is significantly lower load than Apache) would also decrease server response time. Am I mistaken in my thinking?

@qrntz - Sounds like a good plan to me. TBH, I wasn't actually aware of the fundamental difference with php-fpm until yesterday! It certainly seems like a much more efficient way to run PHP apps. 

WRT to caching, it occurs to me that prior to v14.0 we used xcache. It had a default config in common, but it was optimized for some appliances. PHP in Debian Jessie comes pre-compiled with (Zend) OPCache enabled. But we're not tweaking it for any of the appliances. There are possibly some performance gains to be made there?

Good idea on mod_pagespeed.

**Comment by vondrt4** [comment]
Yes, response time is linked to server resource availability. For an idle server, all resources are available; there is no load. In that case, the single customer that comes to the system will see a minimal latency that is given by the computational complexity of the application and the power of the hardware. Together, for a concrete system, it is a time constant called Service Demand. When the server is loaded, the background load reduces the perceived power of the hardware by the so called Stretch Factor. But when optimizing, you always target the Service Demand (unless troubleshooting database locks and such problems that only come at higher loads).

When optimizing, you should  always target the most significant source of latency. In the case of Wordpress (and I have benchmarked it last on a several generations old 4-core, 2,6 GHz processor), the latency of Apache is less than 5 ms and PHP about 100 ms.

Therefore, I do not think that changing from Apache from Nginx is a good optimization strategy. On the other hand, you will lose the .htaccess mechanism which some applications use to configure PHP, Wordpress and NextCloud amongst them.

Changing from mod_php to mod_fcgi is, in my experience, good for limiting maximum memory use. With it, you can have more Apache threads buffering requests and return data, and limit the number of PHP workers eating memory to a sensible multiple of CPU count.

Yes, PHP cache is not built in PHP and I do not know much about its tunables. I used to use APC...

What I meant is caching of statical content. With the default Wordpress installation, every request takes minimally 100 ms. Including requests for css and images. If it produces correct cache control headers, using a reverse proxy cache will reduce the resource demand for rendering the whole page significantly.

**Comment by verysiberian** [comment]
Changing the core to the latest version of Debian with PHP 7 would be another way to enhance performance of WordPress.

**Comment by JedMeister** [comment]
@verysiberian - yep, we're working on it...

**Comment by verysiberian** [comment]
The WordPress core team just updated its recommended version of PHP to 7.2 yesterday:

https://wordpress.org/about/requirements/

Just FYI. If there's anything I could do to help out with this, let me know. I don't want to be a nag.

**Comment by JedMeister** [comment]
@verysiberian - Apologies on slow response. We'll almost certainly stick with PHP 7.0 as that is what is packaged in [Debian Stretch](https://packages.debian.org/stretch/php) (the basis of v15.0).

v15.0 is under development, but I'm really hoping that we'll be able to release a v15.0 Core RC sometime really soon. Once we do that, then the official release (and all the other apps) should follow soon(ish) afterwards. At this point, I'm anticipating Core RC early next year (hopefully January) with the other appliances all updated to v15.0 by the end of Q1 2018. It's still not clear if we'll use Nginx for the WrodPress appliance or not, but it should be released soon after the official v15.0 stable release of Core.

Currently, we've got one issue in particular (#970) blocking our RC release of v15.0 Core. Although ideally, I'm also waiting for #942 (which will hopefully result in #412 being addressed). I have managed to get di-live working again, so that won't block an RC, but until we're clear on the path forwards for di-live (inc replacing it), we won't be doing the final release.

**Comment by JedMeister** [comment]
I'm closing this issue for now.

Using `php-fpm` is covered in a separate feature request and has an outstanding PR (at least the WP appliance). 

Having said that, some more recent reading I've done suggests that when using Apache in Debian Stretch (what v15.0 is based on) `mod_php` is actually more efficient?! I haven't done extensive research, nor have I done any testing myself, so I'm not at all sure, but thought it was worth mentioning.  I'll also add that note to the separate issue.

I've added the idea of an easy option to install and enable pagespeed as a separate feature request for v15.1.

So I'm going to close this particular issue now...
