### ISSUE TITLE
Update to Python3

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#887]
From [Should I use Python 2 or Python 3 for my development activity?](https://wiki.python.org/moin/Python2orPython3):
>Short version: Python 2.x is legacy, Python 3.x is the present and future of the language
>
>Python 3.0 was released in 2008. The final 2.x version 2.7 release came out in mid-2010, with a statement of extended support for this end-of-life release. The 2.x branch will see no new major releases after that. 3.x is under active development and has already seen over five years of stable releases, including version 3.3 in 2012, 3.4 in 2014, 3.5 in 2015, and 3.6 in 2016. This means that all recent standard library improvements, for example, are only available by default in Python 3.x.

(added by @jedmeister)

----
Hey all, let's start having the conversation about updating our code to python 3.x.

Against:
 - most of it works, when we update most of it will break
 - we have dependancies that have no direct python-3.x counterpart
 - python2.7 is incredibly stable

For:
 - python2.7 is only getting maintainance updates, all future development is on python3
 - many new projects only work on python3
 - some distros now ship with python3 as default (Arch and Gentoo)
 - the python website even argues against learning 2.7 before learning 3.x now
 - the longer we wait the harder it will be
 - some of our code is embaressingly old (using `__future__` to import with_statements which were at the time backported from 2.6 as I understand it)

Any comments?

**Comment by JedMeister** [comment]
Great discussion starter! And knowing you, I'm sure you could think of some more pros (for)! :smile: 

As a more general note (not python3 specific) I think one big advantage to getting everything more up to date is the non-intuitive probability that it will actually reduce our maintenance overhead. We'll have less idiosyncratic hacks that may not be apparent to outsiders (thus making contribution easier) and less code that we need to maintain ourselves. E.g the really clunky old version of python-dialog we use, which breaks our confconsole and inithooks as soon as any other python app which uses python-dialog is installed.

**Comment by qrntz** [comment]
I have been saying this for a long time.

**Comment by JedMeister** [comment]
Found this quote in my travels:

>Short version: Python 2.x is legacy, Python 3.x is the present and future of the language
>
>Python 3.0 was released in 2008. The final 2.x version 2.7 release came out in mid-2010, with a statement of extended support for this end-of-life release. The 2.x branch will see no new major releases after that. 3.x is under active development and has already seen over five years of stable releases, including version 3.3 in 2012, 3.4 in 2014, 3.5 in 2015, and 3.6 in 2016. This means that all recent standard library improvements, for example, are only available by default in Python 3.x.

source: https://wiki.python.org/moin/Python2orPython3

Actually, I may add that to the top of @OnGle's OP.

I upgraded my laptop to Stretch earlier this week. Whilst python2 remains the default python, I've noticed that at least one app (vim) is compiled against python3. There is a version ([`vim-nox`](https://packages.debian.org/stretch/vim-nox)) still compiled against python2, but I figured I should start learning a bit about python3. Turns out that I actually didn't need any python3 knowledge! I just used the `2to3` tool:
````
2to3 -w /path/to/python-2-file.py
````
General resources:
- https://docs.python.org/3.0/whatsnew/3.0.html
- https://docs.python.org/3/howto/pyporting.html
- http://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html
- https://www.digitalocean.com/community/tutorials/how-to-port-python-2-code-to-python-3

Automated conversion tools:
- https://docs.python.org/2/library/2to3.html
- https://python-modernize.readthedocs.io/en/latest/
- http://python-future.org/automatic_conversion.html

**Comment by OnGle** [comment]
Alright, I've gone through all of the python projects in the turnkeylinux organization and each of their dependencies as best I could. The dependencies are broken down into 3 categories.

- Deprecated standard library: Items which have been deprecated/remove from the python standard library since python 2.7. 
- Third Party: Third party libraries (not these are not discriminated based on whether they are available in python3 or not, I have not yet checked)
- Turnkey Dependencies: Other libraries or software created by turnkey.

With this we can create a plan for how we want to attack this rather large problem.
[turnkey-python-projects-and-dependencies.txt](https://github.com/turnkeylinux/tracker/files/3279217/turnkey-python-projects-and-dependencies.txt)

**Comment by JedMeister** [comment]
Wow that's a big list with lots of stuff we'll need to take care of...! Great work @OnGle ! :smile: :+1:

**Comment by JedMeister** [comment]
This is still in progress - but probably not much more will happen (beyond individual appliance inithook updates) before the release of 16.0 stable. So i'm moving to the v16.1 milestone.

**Comment by JedMeister** [comment]
We're left with TKLDev tools (e.g. Fab, etc) and TKLBAM. So I might close this issue...
