### ISSUE TITLE
Jenkins - automated plugin dependency fulfilment

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#888]
When doing the final QA checks for Jenkins, I noticed that a few of the plugins were broken. So I decided to try to fix that. Unfortunately though, OOTB Jenkins does not currently support automated dependency fulfilment. So each dependency needs to be manually downloaded and Jenkins restarted and check again for plugin errors. For long dependency trees, that can get a little painful...

I suggest that for our next Jenkins build that we consider researching a way to automatically install plugin dependencies. Then we can just list the plugins we want included and the dependencies are auto discovered and downloaded. IMO that would make maintenance easier. 

Surely there's something out there to make this a bit better?!

**Comment by qrntz** [comment]
When I was updating the appliance I found a couple of ways to do it including [REST API](https://gist.github.com/basmussen/8182784) and [web interface](https://stackoverflow.com/questions/9765728/how-to-install-plugins-in-jenkins-with-the-help-of-jenkins-remote-access-api/34863149#34863149). The first one doesn't seem to work with current Jenkins but it should be fixable.

**Comment by JedMeister** [comment]
Sounds good @qrntz - FWIW I just manually added the required deps by hand for now. While I was at it, I tweaked the cli stuff a little too. II doubt my little "helper" tweak will get used much (most devs would probably just it as per Jenkins docs), but may be a nice little extra for those working on the local server.

FYI here's my PR: https://github.com/turnkeylinux-apps/jenkins/pull/12

**Comment by JedMeister** [comment]
Downgraded to wishlist and bumped to future release.
