### ISSUE TITLE
New appliance - OpenCart

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#894]
As suggested in https://github.com/turnkeylinux/tracker/issues/776,

https://www.opencart.com/
https://github.com/qq7/opencart

**Comment by JedMeister** [comment]
Good work on this @qq7 but I'm putting this aside for v14.2 as per https://github.com/turnkeylinux/tracker/issues/904#issue-247338107 I'll also remove you and self assign. I'll reassign you if it see anything that we'll want to change.

**Comment by JedMeister** [comment]
@qq7 - can you pls check that this is (still) good for release as part of v15.0?!

**Comment by JedMeister** [comment]
@qq7 informs me that this should be pretty much ready to go! :smile:

**Comment by qq7** [comment]
@JedMeister closing because the appliance is released

**Comment by JedMeister** [comment]
Oops. Good catch @qq7 ! :smile:

**Comment by JedMeister** [comment]
Also FWIW some links for anyone who stumbles across this:

Appliance page:
https://www.turnkeylinux.org/opencart

Buildcode:
https://github.com/turnkeylinux-apps/opencart
