### ISSUE TITLE
Django appliance - Lamby to review and tweak (and apply improvements and optimisations as required)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#896]
@lamby - Once we have released Core v15.0, it'd be awesome if you could review our Django appliance and tweak it as need be. To clarify, there isn't anything particularly wrong with our current appliance (AFAIK anyway). But the upgrade to a Stretch base may break it. Plus I'm sure that a Django pro would be able to make it better.

The first step would be to build it on TKLDev (on Stretch base) and fix anything that is broken OOTB (so it builds successfully and works OOTB - it may do that straight away; or it may need adjustment).

The next step would be to test it out and review it to see if there is anything that could be improved. I'm not particularly familiar with Django myself, but if there is anything that most Django devs would want and we aren't including it, then add it. On the other hand, if we are including anything that most devs would not want, then we probably should remove that by default.

Once we get to this, if you want some finer grain guidance, then we can discuss it when we're ready to progress. I'll self assign for now as I'm blocking. But once we've got v15.0 Core done, then you can be assigned.

**Comment by lamby** [comment]
@JedMeister ACK :)  Sounds good, looking forward to it…

**Comment by OnGle** [comment]
ping on this, is this still relevant, are we still doing this since we've already built 15.0, are you still blocking @JedMeister

**Comment by JedMeister** [comment]
I'm just going to close this one for now...
