### ISSUE TITLE
Can't stop VM on the hub with IE 8.0.6001.18975

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#9]
Reported on [lp#911226](https://bugs.launchpad.net/turnkeylinux/+bug/911226) by ``Guy Leblanc`` on 2012-01-03

#### Description

Can't stop VM on the hub with IE 8.0.6001.18975

#### Jeremy Davis (jedmeister) wrote on 2012-09-15

Is this bug still current?

If there is no more activity on this bug I will assume that it is resolved and close it (although even if I do the bug can be reactivated should it still apply).

**Comment by JedMeister** [comment]
Not sure why this is still open? As per comment that Alon quoted 0 I am closing...
