### ISSUE TITLE
[mongodb] password doesn't work for admin account for turnkey mongodb

### ISSUE THREAD

**Issue by gissehel** [turnkeylinux/tracker#90]
Contexte
-------------

I'm using OpenVZ official images for version 12.1-1 (both version i386 and amd64).
Images are :
- 6d21334b9f17e7b8f644725d52af446b  debian-6-turnkey-mongodb_12.1-1_amd64.tar.gz
- 4df341d5c8b7d49ee01627ae7fbf00d8  debian-6-turnkey-mongodb_12.1-1_i386.tar.gz

I use thoses files with distribution proxmox3

Steps
--------
- Install a container with turnkey mongodb
- Start the host
- ssh to the host
- write new password (ex: newpass)
- end the init procedure
- ssh to the host
- try "mongo -u admin -p newpass admin"

Expected result
-----------------------
- I'm connected the to mongo server, and I can query the base "admin"

Actual result
------------------
- I get an error "User Exception 12514:login failed"

Analyse
------------
So following the sources, it seems that the install process expect the password to be "turnkey" on the image.

If I remove "turnkey-init-firstlogin" from /root/.profile.d/ before the first connection, and I try in the first connection "mongo -u admin -p turnkey admin", it doesn't work neither.

If I stop mongodb, I delete files "/var/lib/mongodb/admin.*" (3 files, ".0" ".1" and ".ns"), everything works (after restarting mongodb), including adding a user "admin" with a password, and then using that user and that password.

If I then stop mongodb, remove "/var/lib/mongodb/admin.*" and put default "/var/lib/mongodb/admin.*" from .tar.gz image, the probleme is still here (I'm trying the password "turnkey")

And now the strange things
----------------------------------------

If I then stop mongodb, remove "/var/lib/mongodb/admin.*" and put default "/var/lib/mongodb/admin.*" from **the other** .tar.gz image, the command "mongo -u admin -p turnkey admin" works !

By "the other image", I mean if I'm using the amd64 image, I put the admin.* files from the i386 image, or I'm using the i386, I put the admin.* files from the amd64 image.

searched Google for people having the same problem, found nothing. Still don't know if I did something wrong (both in classical usage of the product and in my analysis) or if there is a problem with those images.

**Comment by JedMeister** [comment]
Seeing as MongoDB is installed from package management let's hope that it works OOTB in v14.0...

**Comment by JedMeister** [comment]
The new version needs to be checked to see if this is still an issue.

https://github.com/turnkeylinux-apps/mongodb

**Comment by JedMeister** [comment]
confirmed fixed in v14.0
