### ISSUE TITLE
Backport zoneminder to stretch-backports

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#900]
I'm just about to add [Zoneminder](https://github.com/turnkeylinux-apps/zoneminder) to the library for v14.2. As we're installing it from Jessie-backports, I expected that the migration to v15.0 (Stretch) should be really quick and easy (just install from Stretch main repo instead of backports).

However it appears that [Zoneminder didn't make it into Stretch](https://packages.debian.org/search?suite=stretch&keywords=zoneminder) :cry: 

@lamby - If you get a chance over the next few weeks, could you please have a look into that and see what the status is (relatively low priority ATM). If it's easy enough, perhaps you could help get it into stretch-backports?! If it needs more than a trivial amount of work, let's discuss the options further.

I'll assign you for now, please bounce it back when it needs attention from me. :smile:

**Comment by lamby** [comment]
It possibly didn't migrate due to these outstanding security issues:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854272
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854733

**Comment by lamby** [comment]
@JedMeister 

My plan is as follows:

- [ ] Email the maintainer to ask him the current status and whether he wants to continue (done, 31 July 2017)
- [ ] Wait a 24/48h for a reply, then "NMU" the package to fix the CVEs.
- [ ] 5 days later it should hit "buster", which means that I can upload to stretch-backports.

Then we wait for it to pass NEW processing on stretch.

**Comment by JedMeister** [comment]
Great work @lamby - thanks!

>It possibly didn't migrate due to these outstanding security issues:
>
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854272
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854733

Wow, ok. Well it looks like we should hold off on releasing this for v14.2 then too then. :cry: 

Out of interest, what happens to Jessie backports from here on in? Do the LTS team do "best effort" on those or do they get removed? Or something else?

**Comment by MPTMG** [comment]
Alright. From the bug reports it looks like the Zoneminder team has the ball in their court right now.

**Comment by lamby** [comment]
@MPTMG Actually, no, the developer is unwell so I will be taking over temporarily and will move this forward.

**Comment by lamby** [comment]
Did some work today here https://anonscm.debian.org/git/collab-maint/zoneminder.git/log/

**Comment by lamby** [comment]
Adding the new upstream version seems like the best way of fixing these CVEs over backporting.  More work here anonscm.debian.org/git/collab-maint/zoneminder.git/log

**Comment by JedMeister** [comment]
Thanks @lamby :+1:

**Comment by lamby** [comment]
Added new upstream, just now fixing up some mess, tidying allllll the patches etc.

git log here: https://anonscm.debian.org/git/collab-maint/zoneminder.git/log/

**Comment by lamby** [comment]
Just uploaded zoneminder (1.30.4+dfsg-1) to unstable :)

**Comment by lamby** [comment]
Still some issues with RC bugs which will prevent migration. Closed 2 of them today, but now working on making it build with GCC 7.0 which is now a requirement for it to hit buster...for it to be backportable... :p

**Comment by lamby** [comment]
Updates here:

 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854272
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854733

**Comment by JedMeister** [comment]
As much as a bugger that is, you've got to love the vigilance! :smile:

**Comment by lamby** [comment]
Security issues appear to be addressed. Hopefully will migrate to buster in 24h or so.

**Comment by lamby** [comment]
For some reason these were re-opened without explanation. Investigating.

**Comment by lamby** [comment]
and now we wait … :)

**Comment by lamby** [comment]
I've just uploaded 1.30.4+dfsg-2~bpo9+1 to ``stretch-backports``. It will wait in the backports ``NEW`` queue for a few days now.

**Comment by lamby** [comment]
```
From: Debian FTP Masters <ftpmaster@ftp-master.debian.org>
To: Dmitry Smirnov <onlyjob@debian.org>, Chris Lamb <lamby@debian.org>
Subject: zoneminder_1.30.4+dfsg-2~bpo9+1_amd64.changes is NEW
Date: Monday, 18 September 2017 10:21 AM

binary:zoneminder is NEW.
binary:zoneminder-doc is NEW.
binary:zoneminder-doc is NEW.
binary:zoneminder is NEW.
source:zoneminder is NEW.

Your package has been put into the NEW queue, which requires manual action
from the ftpteam to process. The upload was otherwise valid (it had a good
OpenPGP signature and file hashes are valid), so please be patient.

Packages are routinely processed through to the archive, and do feel
free to browse the NEW queue[1].

If there is an issue with the upload, you will receive an email from a
member of the ftpteam.

If you have any questions, you may reply to this email.

[1]: https://ftp-master.debian.org/new.html
     or https://ftp-master.debian.org/backports-new.html for *-backports
```

**Comment by JedMeister** [comment]
Great thanks @lamby

**Comment by lamby** [comment]
This is still in the NEW queue. (The backports maintainer is AFK for a few days so nothing to worry about!)

**Comment by JedMeister** [comment]
Thanks for the update @lamby - not sure if I mentioned lately, but you rock! :smile:

**Comment by lamby** [comment]
@JedMeister It is now in backports :)

https://tracker.debian.org/news/875696
