### ISSUE TITLE
SuiteCRM can't be updated via WebUI due to permission settings

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#901]
It has been reported in the [forums]() (and unfortunately it got missed for the v14.2 release) that the permissions in our appliance, do not currently support updates via WebUI.

If you just want to be able to use the UI for updates and aren't super paranoid about security, you could just recursively `chown` the web root (`/var/www/suitecrm` or `/var/www/sugarcrm`). I.e.:
````
WEBROOT=/var/www/suitecrm # or /var/www/sugarcrm depending on appliance
chown -R www-data:www-data $WEBROOT
````

If you like the locked down nature of default TurnKey, but wish to use the UI to upgrade, then you can revert to default permissions. Once you have you completed the upgrade revert to the previous permissions like this (this should also work for SugarCRM, except set `WEBROOT=/var/www/sugarcrm` & remove the mention of `suitecrm.log`): 
````
WEBROOT=/var/www/suitecrm
chown -R root:root $WEBROOT
for i in cache custom modules upload config.php sugarcrm.log suitecrm.log install.log config_override.php .htaccess; do
    chown -R www-data:www-data $WEBROOT/$i
done
````

For v15.0, I'd really like to see a confconsole plugin that allows loosening and tightening of filesystem permissions.

**Comment by JedMeister** [comment]
Updated title and removed `sugarcrm` tag as per ￼#1098

**Comment by spaghettimaster** [comment]
I added confconsole plugin for suitecrm.  [pr](https://github.com/turnkeylinux-apps/suitecrm/pull/7/files)
And SugarCRM is dead now, so there is no plugin for it.

**Comment by JedMeister** [comment]
Great work, thanks @spaghettimaster :+1:
