### ISSUE TITLE
New appliance - Redis

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#904]
@qq has produced a redis appliance: https://github.com/qq7/redis

Good work! It's so close, and it'd be really cool to slip this into v14.2 as well. However, v14.2 might take all year to finish if we keep squeezing one more in. So I'm drawing a line in the sand and moving all new appliance candidates to v15.0.

Sorry about that. We'll try to push it out early in the v15.0 release.

I'm assigning this issue to myself for now. I'll note anything that needs tweaking here on this issue and reassign to you @qq7 when I'm done.

**Comment by qq7** [comment]
test

**Comment by JedMeister** [comment]
@qq7 - this one too! :smile:

**Comment by qq7** [comment]
The appliance can be found here: https://github.com/qq7/redis

**Comment by JedMeister** [comment]
This app has now been built, awaiting final publishing (should be within the next week).
