### ISSUE TITLE
New appliance: Foswiki (fork of Twiki) - Twiki appliance to be deprecated

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#906]
@OnGle has forked the [Twiki appliance](https://www.turnkeylinux.org/twiki) to create a [Foswiki](https://foswiki.org/) appliance:
https://github.com/OnGle/foswiki

Twiki is essentially dead; the core Twiki devs forked the code and created Foswiki.

We'll deprecated Twiki for v15.0 and release the Foswiki appliance.

**Comment by JedMeister** [comment]
@ongle - I'm assinging this one to you seeing as you've already done most of the work. I know you're busy ATM but this looks like it's pretty close, just needs a clean up (e.g. readme, credit footer, etc) and should hopefully be good to go...

**Comment by OnGle** [comment]
Foswiki should now be working and up to date https://github.com/OnGle/foswiki

**Comment by JedMeister** [comment]
Forked into library: https://github.com/turnkeylinux-apps/foswiki

Will be added as part of upcoming v15.0 release.
