### ISSUE TITLE
Stretch build still using auFS - should use overlayFS

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#921]
The good news is that I can successfully build a v15.0 Core ISO! Yay! (I'll share how you too can do that really soon). The bad news is that it doesn't boot, neither 'live' nor 'install'.

No great surprise really as auFS is no longer supported in Stretch...

![screenshot from 2017-08-10 18-07-45](https://user-images.githubusercontent.com/818633/29160776-ef508e06-7df6-11e7-9343-38b3e74d2c7d.png)
(please ignore the key errors at the bottom, that was just me taking the screenshot).

This could be patched relatively easily no doubt. However, I imagine that it would also be resolved incidentally if #412 were resolved.

**Comment by vondrt4** [comment]
https://packages.debian.org/stretch/kernel/aufs-dkms ?

**Comment by JedMeister** [comment]
Nice one @vondrt4! You rock! That will probably do the trick. I was thinking that it would be best to transition to OverlayFS (default union FS in Stretch), which we may still do. But in the meantime, that might be enough to get a "beta" build?!

**Comment by JedMeister** [comment]
Thanks @vondrt4 - I added that package and the headers and all is well. 

Before we release, we'll change it so we're using overlayFS instead, but at least we'll be able to release a beta and it won't block people from starting work on upgraded and new appliances for v15.0.

**Comment by JedMeister** [comment]
Pretty much fixed, just need to merge. Note updates casper package is in my dev-test repo.
