### ISSUE TITLE
Nextcloud appliance tklbam profile is missing the nextcloud webroot!!!

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#922]
It has been reported in the [forums]() that the v14.2 Nextcloud tklbam profile is incorrect. It is not including the webroot (`/usr/share/nextcloud`)!!

The immediate fix is to regenerate the TKLBAM profile to include /usr/share/nextcloud. The workaround for users right now is to manually add the location:
````
echo "/usr/share/nextcloud" >> /etc/tklbam/overrides
````

IMO, the "proper" fix for this is to move the nextcloud webroot to the TKL standard location (`/var/www/nextcloud`), then the default profile will "just work" (`/var/www` is always included in backups). I'll open a separate issue on that for v15.0.

**Comment by JedMeister** [comment]
An alternate (and arguably better) workaround, is to manually use the updated profile.

To do that, you'll need to download the profile I've uploaded to your server. [turnkey-nextcloud-14.2-jessie-amd64.tar.gz](https://github.com/turnkeylinux/tracker/files/1216625/turnkey-nextcloud-14.2-jessie-amd64.tar.gz)
````
HUB_API_KEY=replace this text with your Hub API key!
mv /var/lib/tklbam /var/lib/tklbam.backup
cd ~
mkdir tklbam-profile
wget https://github.com/turnkeylinux/tracker/files/1216625/turnkey-nextcloud-14.2-jessie-amd64.tar.gz
tar xf turnkey-nextcloud-14.2-jessie-amd64.tar.gz -C tklbam-profile/
tklbam-init $HUB_API_KEY --force-profile=tklbam-profile/
````
I've just tested it and it gives me a backup size of 17.4 MB (original profile gave me 8.18 MB; adding an override gave me 153 MB). That looks pretty legit to me!?

**Comment by cboulanger** [comment]
Looks good:
```
# tklbam-backup --simulate

[...]

--------------[ Backup Statistics ]--------------
StartTime 1502433812.51 (Fri Aug 11 06:43:32 2017)
EndTime 1502433817.88 (Fri Aug 11 06:43:37 2017)
ElapsedTime 5.37 (5.37 seconds)
SourceFiles 26203
SourceFileSize 14416317304 (13.4 GB)
NewFiles 13476
NewFileSize 14416317304 (13.4 GB)
DeletedFiles 0
ChangedFiles 0
ChangedFileSize 0 (0 bytes)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 13476
RawDeltaSize 0 (0 bytes)
TotalDestinationSizeChange 0 (0 bytes)
Errors 0
-------------------------------------------------
``

**Comment by JedMeister** [comment]
Awesome! :+1:

**Comment by JedMeister** [comment]
Alon has informed me that the new profile (as tested here) has now been uploaded to the Hub. It should be all good now! :smile:
