### ISSUE TITLE
use http://deb.debian.org as url for sources.list

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#927]
I have it on good authority that the preferred main Debian repo url is now http://deb.debian.org

Obviously we still need http://security.debian.org

**Comment by JedMeister** [comment]
This has been addressed in https://github.com/turnkeylinux/common/commit/2cb560f4a12061be871354e6c9468e0f3f0e420d

**Comment by OnGle** [comment]
@JedMeister Should this issue now be closed?

**Comment by JedMeister** [comment]
Yep, let's!

FWIW, I was keeping issues that have been addressed in `stretch-dev` but not yet merged to `master` as open but `in-progress`. However, it's probably better to just close them now as `stretch-dev` will be here for a little longer yet, and we'll just merge that into master anyway.
