### ISSUE TITLE
AWS console IAMs role creation UI has changed - Hub instructions no longer match

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#929]
It seems that AWS console UI has changed since we created our instructions on how to create an ARN/IAMs role for the Hub. Alon is the only one with full and direct Hub access so we'll need to wait for him to update that. 

For now, I'll detail how to manually create the new IAMs role/ARN for the Hub. I hope it's not too confusing, but I will be using my own Hub account to demonstrate. Unfortunately I already have it set up, so it won't exactly match what new users will see, but hopefully it will be apparent what needs to be done.

----

So I am starting with the IAMs details as shown in my Hub account. I am starting from the [Hub's AWS account info page](https://hub.turnkeylinux.org/amazon/account/). To see the policy info and the external and trusted account IDs (which are displayed for new users, but in a slightly different format) click the "?" next to "Role ARN":
![iams01-hub](https://user-images.githubusercontent.com/818633/29301183-bf3ae9da-81bd-11e7-9311-1cfed7c171f9.png)

----

It should open a pop-over that looks like this:
![iams02-hub2](https://user-images.githubusercontent.com/818633/29301274-6c40ef26-81be-11e7-9ef5-7d64287b168c.png)
You can clearly see there my role ARN plus the External ID and Trusted account ID. 

----

Now let's look at the AWS IAMs area. To start with, log into [AWS console](https://console.aws.amazon.com/iam/home?#/policies). If you have multiple AWS accounts, please ensure that you log in using the account that is linked to the Hub. The first thing we'll need to do is create a policy, you should see a page like this:
![iams03-aws-policy1](https://user-images.githubusercontent.com/818633/29301710-8a2c9cd0-81c1-11e7-801e-3d40d823d864.png)
Click the big blue "Create policy" button towards the top left. 

----

That should take you to a page like this:
![iams03-aws-policy2](https://user-images.githubusercontent.com/818633/29301787-062d449c-81c2-11e7-957d-51e088db5071.png)
We'll need to create our own policy, so select the bottom option "Create Your Own Policy" (i.e. click the blue "select" button to the right of it).

----

Then give it a name (I used "turnkey-hub", but "turnkeyhub" is fine). A description is optional (I didn't bother). Copy paste the policy exactly as displayed within the Hub. Your page should look something like this:
![iams03-aws-policy3](https://user-images.githubusercontent.com/818633/29301841-6fa3027c-81c2-11e7-9dc3-0987134518d9.png)
Then click the blue "Create policy" button in the bottom right. 

----

That will take you back the the main policy page, but should have a green notification at the top notifying that it was successful, like mine does:
![iams03-aws-policy4](https://user-images.githubusercontent.com/818633/29301931-2725bb38-81c3-11e7-9228-104cbac8235e.png)

Note the menu on the far left, currently "Policies" should be selected (text in bold with a yellow bar to the left).

----

From the left hand menu (as noted above) select "Roles" (directly above "Policies"). You should see something similar to me:
![iams03-aws-iams1 png](https://user-images.githubusercontent.com/818633/29301383-1f761fc6-81bf-11e7-83b5-f3c888991a9b.png)
If you haven't already tried to set this up, then yours won't already have the 'turnkeyhub' role that mine does. If it does and your Hub account isn't working, delete that and we'll recreate it. Otherwise, please ignore that in my screenshots. I'll create a new one which I will call 'turnkey-hub' (so it won't clash with the current one I'm using) but if you already have a ARN saved in the Hub; you **must** use the same name as already saved in the hub (most likely 'turnkeyhub'). 

Click the big blue "Create New Role" button near the top. 

----

That will open a new page that should look like this:
![iams03-aws-iams2](https://user-images.githubusercontent.com/818633/29301489-d51773c0-81bf-11e7-8f9c-4d43faba3c24.png)

----

From the list displayed, click the heading "Role for cross-account access", the section should roll down to reveal some new options. We'll want to "Provide access between your AWS account and a 3rd party AWS account", so select that option (highlighted in red in the screenshot):
![iams03-aws-iams3](https://user-images.githubusercontent.com/818633/29301549-4db437f0-81c0-11e7-80c3-6842d16f1532.png)

----

That will open a new page where you will need to add the External ID and Trusted Account ID from the Hub. Copy them directly into the relevant places. Note that Trusted account ID will be the same as mine (it's the Hub's AWS account). However, the External ID will be unique to your Hub account, so please copy it directly from your Hub account. E.g.:
![iams03-aws-iams4](https://user-images.githubusercontent.com/818633/29301628-e383aec8-81c0-11e7-9a8b-20d0ea79f32c.png)

Then click the big blue "Next step" button in the bottom right.

----

That will take you to the "Attach Policies" page, where all possible policies will be displayed. We want to attach the policy which we created earlier. 

The easiest way to find the policy we made earlier is to input 'turnkey' into the filter box:
![iams03-aws-policy5](https://user-images.githubusercontent.com/818633/29302465-b8598ffe-81c7-11e7-85d6-6e8f8510d984.png)
Then select the appropriate policy, by clicking in the box on the left. Click the blue "Next step" button in the bottom left.

----

Type the role name into appropriate box (I've typed 'turnkeyhub' which is probably what you should use):
![iams03-aws-policy6](https://user-images.githubusercontent.com/818633/29302559-835d4fec-81c8-11e7-8714-8961cb53fb0e.png)
Click the blue "Create role" button in the bottom left.

----

That will take you back to the main Roles page. 
![iams03-aws-policy7](https://user-images.githubusercontent.com/818633/29302584-bf3249be-81c8-11e7-9837-c6757d187125.png)

----
Click on the role you just created. You should now see the full details of your 'turnkeyhub' IAMs role (I'm showing my proper 'turnkeyhub' role with my ARN highlighted in red).
![iams03-aws-iams6](https://user-images.githubusercontent.com/818633/29302729-0564e8c8-81ca-11e7-8413-9fd9d8e6bb4a.png)

Copy that ARN and paste it back into the Hub into the appropriate place. If you have already saved an ARN in the Hub, then double check that they are the same.

----

Once you've done that, then browse to the [Hub's AWS account page](https://hub.turnkeylinux.org/amazon/account/). 
![iams02-hub3](https://user-images.githubusercontent.com/818633/29302829-df834554-81ca-11e7-9fd1-44925a4f9209.png)

Click the "Help" link to the right of "Amazon service connectivity checks" (highlighted in red). 

----

That should open a pop-over.
![iams02-hub4](https://user-images.githubusercontent.com/818633/29302891-6501b832-81cb-11e7-814c-57c3a6ff6968.png)

Click the "Recheck connectivity" button.

----

Hopefully, you should see 4 green "Passed" next to the relevant AWS services that the Hub interacts with. If not, please click the "Help" text link again and follow through the 3 other suggestions.

**Comment by JedMeister** [comment]
That was weird, I don't recall setting any of those tags?! Anyway, fixed it...

**Comment by JedMeister** [comment]
This should be resolved now. Closing...

**Comment by qrntz** [comment]
This is again the case as the the IAM UI was updated. Maybe we should also consider updating the Hub-IAM interface to:
1. automatically locate the role so the user doesn't have to copypaste
   - if we have the AWS account ID and we know the role has a specific name we can compute the ARN
   - Hub accounts are useless without AWS anyhow so perhaps it makes sense to require the account ID for creating an account
   - if we need to provide a demo of the Hub that can be done separately without requiring registration
2. link to official AWS IAM documentation

**Comment by JedMeister** [comment]
I'm going to close this issue again as we've now got an "automated" AWS CloudFormation way to create the IAMs role, which makes the sign up easier and makes this issue somewhat irrelevant. However, I've moved the most recent comment out into a new issue.
