### ISSUE TITLE
Ansible inithook won't work as expected when launched on AWS MP

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#935]
While working on another matter, I noticed that the Ansible inithook [explicitly copies the generated SSH key to the root user](https://github.com/turnkeylinux-apps/ansible/blob/master/overlay/usr/lib/inithooks/firstboot.d/50ansible-key#L11-L13). 

While that's fine for  most of the builds; AWS Marketplace require the root account to be disabled. So instead we provide an "admin" user account. So the Ansilbe inithook should probably check to see if `/home/admin` exists and if it does, use that instead.

Also it'd probably be a good idea to rename the inithook to be consistent and inline with other appliances. I.e. instead of [`inithooks/bin/setpass_key.py`](https://github.com/turnkeylinux-apps/ansible/blob/master/overlay/usr/lib/inithooks/bin/setpass_key.py), it should really be `inithooks/bin/ansible.py`.

**Comment by JedMeister** [comment]
I've added a workaround to buildtasks for now - see https://github.com/turnkeylinux/buildtasks/commit/a35b6dd3963e6ae10b851a3b45c6bb5ba483e8d3

**Comment by OnGle** [comment]
@JedMeister, I've had a quick look at your fix, could you double check this works as expected on the hub?

**Comment by JedMeister** [comment]
Oh bugger! @OnGle I only just followed up on your request that I double check this on the Hub. And... it doesn't work...!
