### ISSUE TITLE
custom builds and scripts

### ISSUE THREAD

**Issue by xevilstar** [turnkeylinux/tracker#936]
I'd like a core that can load at boot (rc.local style) some custom scripts that will partition the disk prepare the lvm volumes mount those and untar a full centos system tgz .... is that feasible and if yes how ? is there another better way to make a custom centos install iso (considering that kickstart is not an option since I had to build a lot of core stuff old school style) ?

**Comment by xevilstar** [comment]
also I'd like my script to start at boot instead of the turnkey menu

**Comment by JedMeister** [comment]
Please note that this is our "issue tracker" for bugs and feature requests. More general questions such as this, are best asked on our [forums](https://www.turnkeylinux.org/forum/). But seeing as you've posted here already...

Why do this via TurnKey? You know that TurnKey is Debian based, right? 

If what you are after is a CentOS custom installer, why not see what CentOS/RHEL already provide for that purpose?! It sounds like you have had a bit of a go and it didn't work how you'd hoped. Although personally I'd be surprised if there isn't already something that will do what you want.

TBH, it actually sounds like what you want is a modified CentOS installer that operates in a similar fashion to the TurnKey installer (which is basically just a wrapper for the default Debian installer). 

So whilst you could probably create a TurnKey build that would do what you want, it'd be hacky as and is certainly well outside the scope of intended usage. So, I think developing a wrapper for the CentOS installer would be your best bet. And as I've never used CentOS/RHEL, I have no idea how you would go about that.

I'm going to close this for now. If you'd like to ask more about it, please post in the forums.
