### ISSUE TITLE
PhpMumbleAdmin doesn't install correctly - cannot log in

### ISSUE THREAD

**Issue by Enigma0** [turnkeylinux/tracker#938]
PhpMumbleAdmin doesn't install correctly - cannot log in

Tried root & admin for users.

**Comment by JedMeister** [comment]
When in doubt, read the docs! :smile: 

https://github.com/turnkeylinux-apps/mumble#credentials-passwords-set-at-first-boot

**Comment by Enigma0** [comment]
Thanks - could not find that.
