### ISSUE TITLE
TKLBAM S3ResponseError: 417 Expectation failed

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#94]
Mentioned on the [forums](http://www.turnkeylinux.org/forum/support/20130130/tklbam-backup-conn-error-sa-east-how-override-tklbam-datacenter-selection) by ``Paulo Cesar Emerique``, as well as in an email by ``Alexander Kuznetsov``:

````
Uploading s3://
s3-ap-northeast-1.amazonaws.com/tklbam-a5ffv4lzfwds4q4w/duplicity-full.20130619T170707Z.vol1.difftar.gpgto
STANDARD Storage
Upload 's3://
s3-ap-northeast-1.amazonaws.com/tklbam-a5ffv4lzfwds4q4w/duplicity-full.20130619T170707Z.vol1.difftar.gpg'
failed (attempt #1, reason: S3ResponseError: S3ResponseError: 417
Expectation failed
None)
````

**Comment by JedMeister** [comment]
Considering the age of this bug and the lack of activity I am closing it, Please reopen (or open a new bug) if you disagree.
