### ISSUE TITLE
investigate replacing TurnKey live functionality and install (i.e. di-live, casper and friends) with default Debian tools

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#942]
Currently di-live is not working as it should in our Stretch based alpha/beta builds. It did work the very first time I built it; but something since has caused a serious regression. di-live already had a few other things which are needed/desired for Stretch anyway (e.g. #921, #932, #166).

So now seemed like the logical point to properly investigate what would be required to fulfil our needs via default Debian packages (i.e. #412) . Then we can make an informed decision on the best path forward (balancing time and cash resources against best possible outcome).

Here is the task I propose for @lamby (perfect man for the job IMO):

1. spend half hour +/- installing TurnKey v14.2 ISO to VM to get a feel for the current end user experience.

2. spend an hour or 2 looking over the current di-live code and set up so you have an idea of how it works and whether it may be worth updating and including as part of the solution (possibly not as per previous private conversation; but let's see).

3. spend a day +/- on prototyping and give us some more detailed feedback inc an updated estimate on implementation timeframe and cost.

**Comment by vondrt4** [comment]
If you want a modern server or two for testing, I can give you access to a HPE ProLiant gen9 and a recent SuperMicro, both with UEFI and BIOS mode, and with remote console + virtual media.

**Comment by JedMeister** [comment]
Thanks @vondrt4 - that's a very kind offer and we'd love to take you up on it once we get to testing.

**Comment by JedMeister** [comment]
Tidying up the tracker a little and have now moved this issue to 15.1 milestone. We need to push ahead with v15.0 and get it released ASAP so I'm starting to reduce the feature requests we'll include for this release of core. As we've resolved the major blocking issues with di-live we'll stick with that for v15.0. Unfortunately that means that UEFI support is unlikely (although not impossible). I'll post some more info about my findings on the relevant thread (#932).

**Comment by lamby** [comment]
:+1:

**Comment by JedMeister** [comment]
Closing this as `di-live` has had some significant changes in v16.0!

For details, see the note in the [v16.0 Core changelog](https://github.com/turnkeylinux-apps/core/blob/6ecbbbf6fbc24307aadeefed16a58f59281bddd2/changelog#L26-L32) and/or https://github.com/turnkeylinux/di-live/pull/7
