### ISSUE TITLE
Odoo TKLBAM restore v14.1/v14.2 => v14.2; PDF rendering appears broken on restored system

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#943]
A user reported that restoring a v14.1 Odoo TKLBAM backup to a v14.2 Hub server leaves the system a little broken. Mostly it all seems to work ok, but the PDF printing appears to be broken.

> The issue is creating pdf reports. The report I am creating is an invoice. This issue can be re-created by using the demo database . then do a tklbam backup and restore to new system the invoice will no longer have the layout and logoimage

AIso worth noting is that the (broken) system appears to hang for a little while before producing the broken PDF. On a working system, it shows the good PDF much quicker.

Further investigation on the user's part showed that it appears to be an issue with the DB. And it's not limited to v14.1 => v14.2. It can also be recreated simply by backing up a (working) v14.2 and restoring it to another v14.2 instance, same breakage occurs.

If instead a backup of the DB is created via Odoo (i.e. within the webUI) and then manually migrated to the restored server; then manually restored (again via Odoo webUI) then it works again!

So it appears that TKLBAM is mangling something within the DB when backing it up! And/or when it restores it...

**Comment by JedMeister** [comment]
As a workaround, you should be able to manually create a backup with this line:
````
wget --post-data 'master_pwd=ADMIN_PASSWORD&name=DB_NAME&backup_format=zip' -O back_up_filename.zip http://localhost:8069/web/database/backup
````
To fully automate the backup, we'll need to add that as a hook script and ensure that the file ends up somewhere that will be in the backup. 

Then automatically restoring the backup will be the next step we need to work out.

**Comment by JedMeister** [comment]
I'm closing this now as I've been unable to recreate the issue. The user who originally reported it, has not responded.

**Comment by l-arnold** [comment]
I realize closed but this is happening with Odoo 14 (TKL 16.2).
I just used the Odoo Database manager and seem to have worked through.
Had to delete the Restored Database
go to the old Server,  Backup the Database in /web/database/manager
go to the new server and restore the database  (using the OLD Database ADMIN Password)

Takes a few tries, but I am at least getting renderings of CSS etc on the new site.
Effectively moved from AWS to Linode (for test)  (this is also a clone of first Linode)
