### ISSUE TITLE
New appliance -Candidate- beta : SLIMS8

### ISSUE THREAD

**Issue by Ozgurujim** [turnkeylinux/tracker#948]
Senayan Library Information Management System [ Version 8 , code-name Akasia ]. 
A LAMP-based LMS widely used in Indonesia , compliant with international library standards, and with multiple language translations.
This is my beta version of an appliance with some language customisations.
https://github.com/Ozgurujim/slims8

**Comment by JedMeister** [comment]
Great work @Ozgurujim - thanks tons for your contribution. As I noted on the forums, unfortunately, there will be a biot of a holdup before we can add your new appliance, but thanks so much for the contribution. 

Hopefully I'll get a chance to look at it a bit closer sometime soon. Currently I'm still trying to get a public beta of v15.0 out the door. As soon as I have that done (and have unblocked the other devs) then I'll have a bit more time.

Please feel free to bump this is you haven't heard much and are wondering where things are up to...

**Comment by JedMeister** [comment]
Just a bit of an update... We're still working on v15.0 although we're super close to a release candidate. Hopefully within the next week or so!

Soon after that, we'll start building the other appliances. Once that starts, I'll have a much closer look at this.

**Comment by Ozgurujim** [comment]
Really looking forward to v15.0 - it'll re-energise a lot of projects I'm sure!! :)

**Comment by JedMeister** [comment]
Yeah I can't wait for the release! It's been a long time coming!

**Comment by JedMeister** [comment]
Unfortunately, this never got added and I notice that SLIMS is now up to v9. I'm going to close this for now, but may take another closer look if I get a chance (unlikely, but ...).
