### ISSUE TITLE
confconsole: networking - static IP doesn't stick until you select DHCP

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#952]
Relates to (not yet publicly released) v15.0beta1 Core.

After firstboot, I noticed that when setting a static IP within confconsole, it did not appear to apply.

After trying repeatedly, I randomly tried what would happen if I set it back to DHCP. Nothing appeared to happen then either. But when I retired setting a static IP it worked...

**Comment by JedMeister** [comment]
It looks like it's not restarting networking to apply the new IP. The interfaces file has been updated:
````
--- a/network/interfaces
+++ b/network/interfaces
@@ -5,7 +5,11 @@ auto lo
 iface lo inet loopback
 
 auto eth0
-iface eth0 inet dhcp
+iface eth0 inet static
+    address 192.168.1.100
+    netmask 255.255.255.0
+    gateway 192.168.1.1
+    dns-nameservers 192.168.1.1
 
 auto eth1
 iface eth1 inet dhcp
````

**Comment by JedMeister** [comment]
It seems that even running ifdown/ifup on eth0 from the commandline is no longer sufficient to apply the static IP?! I tried that and the IP did not update.

Rebooting applies the updated IP address set in the interfaces file. Or the trick with applying DHCP first. I guess that confconsole must do something when setting DHCP which allows it work later?!

FWIW, once it's worked once, it appears to continue working?! Seems weird...

**Comment by JedMeister** [comment]
Hmmm, looks like something really funky going on with the networking...

````
root@core /etc# service networking status
* networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-10-17 06:54:58 UTC; 3min 16s ago
     Docs: man:interfaces(5)
  Process: 6524 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
  Process: 6521 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude
 Main PID: 6524 (code=exited, status=1/FAILURE)

Oct 17 06:54:58 core systemd[1]: Starting Raise network interfaces...
Oct 17 06:54:58 core ifup[6524]: udhcpc: SIOCGIFINDEX: No such device
Oct 17 06:54:58 core ifup[6524]: ifup: failed to bring up eth1
Oct 17 06:54:58 core systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 06:54:58 core systemd[1]: Failed to start Raise network interfaces.
Oct 17 06:54:58 core systemd[1]: networking.service: Unit entered failed state.
Oct 17 06:54:58 core systemd[1]: networking.service: Failed with result 'exit-code'.
````
But...
````
root@core /etc# ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.98  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::ec83:55ff:fe9a:819a  prefixlen 64  scopeid 0x20<link>
        ether ee:83:55:9a:81:9a  txqueuelen 1000  (Ethernet)
        RX packets 41217  bytes 16281811 (15.5 MiB)
        RX errors 0  dropped 16232  overruns 0  frame 0
        TX packets 13311  bytes 1171063 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1798  bytes 241517 (235.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1798  bytes 241517 (235.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
````
And...
````
root@core /etc# ping -c4 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.586 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=0.325 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=0.386 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=0.310 ms

--- 192.168.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3067ms
rtt min/avg/max/mdev = 0.310/0.401/0.586/0.112 ms
````

Turns out that the networking service was failing because I didn't have an eth1 device, but it was mentioned in the /etc/network/interfaces file. I commented that out and that bit at least works fine now. I'm not 100% convinced that this was the cause, but I'll do a rebuild in the background and retest later.

**Comment by JedMeister** [comment]
fixed by commenting out `eth1` in the default interfaces file. Commit coming soon...

**Comment by vondrt4** [comment]
Please patch it back to two interfaces in the 'cloud' overlay. Otherwise, the users won't be able to use a second interface they attach to the instance. Static IP setting is not used in the cloud.

**Comment by JedMeister** [comment]
Great point! Thanks @vondrt4 :+1:

**Comment by JedMeister** [comment]
@vondrt4 - now I think of it, I imagine that your comment would actually apply to all cloud instances. 

So seeing as we're already disabling confconsole network config for cloud builds, it seems like the way to go is remove eth1 for default builds, but add it back for all cloud builds in buildtasks. E.g: like [this](https://github.com/JedMeister/buildtasks/commit/9cd98db15e94cc0285c61d27d49df297dac5bcd5).

Sound fair?

**Comment by vondrt4** [comment]
Exactly what I had in mind.

**Comment by JedMeister** [comment]
original issue closed by: https://github.com/turnkeylinux/common/commit/445624fb010819c2fef72456255e0bd3db322d2c

cloud build concerns (i.e. `eth1` uncommented) addressed in buildtasks here: https://github.com/turnkeylinux/buildtasks/commit/aa332754cec7e6f7759d1cfa0ffbd12b0e5a9325

**Comment by l-arnold** [comment]
I know this is closed buy I was looking for a solution to getting Networking to show on in TKL 15:  
I am having this issue, so far, with version TKL 15 XEN  installs (Magento and Django so far) in Linode.  

I will try Django TKL 14 Next.

In Django seems I can work past this by starting once with the XEN image Unzipped and in place.  Crashing.  Resetting the Root Password for the Drive.  Restarting and finishing.

nope:  After that I still end up crashing:
turnkey-init-fence.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable turnkey-init-fence
insserv: warning: current start runlevel(s) (empty) of script `turnkey-init-fence' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `turnkey-init-fence' overrides LSB defaults (0 1 6)
.
turnkey-init-fence is down
error: Networking is not yet configured
