### ISSUE TITLE
Ushahidi should have php IMAP module pre-installed

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#961]
A user has just reported:

>I just installed Ushahidi.
>
>I am having an issue with setting up the email. When I test the email settings I get the following error message:
>
>`Error! - IMAP PHP Library is not installed`
>
>How do I fix this?

I'm awaiting confirmation from the user, but it should be as simple as installing the php IMAP module:
````
# v14.x (Jessie)
apt-get update && apt-get install php5-imap

# v15.x (Stretch)
apt-get update && apt-get install php-imap
````

**Comment by spaghettimaster** [comment]
Done!
https://github.com/turnkeylinux-apps/ushahidi/pull/12

**Comment by JedMeister** [comment]
When I merged the PR, this issue got auto closed! :smile:
