### ISSUE TITLE
Elgg should have cron job enabled by default

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#972]
I've just had a look at @ongle's recent v15.0 Elgg appliance update ([turnkeylinux-apps/elgg/pull/12](https://github.com/turnkeylinux-apps/elgg/pull/12)). It all looks good to me, but a quick browse of their docs suggest that a [custom cron job should be set up](http://learn.elgg.org/en/2.3/admin/cron.html). 

From what I can see, we aren't currently doing that, and we probably should....! FWIW, there is a wiki page on [troubleshooting/testing cron jobs](https://github.com/turnkeylinux/tracker/wiki/How-to-test-a-cron-job) which might be handy?

I'll leave the PR unmerged for now, so a new PR won't be needed.

**Comment by OnGle** [comment]
Cheers @JedMeister, I'll have that sorted out ASAP!

**Comment by JedMeister** [comment]
I'm going to shut this now. Even though the code hasn't been merged, it's in progress and you've addressed the issue, so that'll do! :smile:
