### ISSUE TITLE
mattermost - 502 Bad Gateway after reboot

### ISSUE THREAD

**Issue by edurenye** [turnkeylinux/tracker#973]
I'm getting a 502 Bad Gateway error after rebooting the machine with LXC container.
In the nginx error.log I have the following error:

> [error] 1304#0: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.xxx.xxx, server: , request: "GET /api/v3/users/websocket HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v3/users/websocket", host: "xxx.xxx"

**Comment by edurenye** [comment]
The problem was that in the config I activated TLS and this is done by nginx not mattermost so it fails, disabling it in the config solved the problem.

**Comment by JedMeister** [comment]
Great to hear you sorted it out! :smile:
