### ISSUE TITLE
Elgg cronjobs can be started by anybody

### ISSUE THREAD

**Issue by OnGle** [turnkeylinux/tracker#974]
Currently elgg cronjobs are not restricted and can be run from the internet.

It seems that the latest version of elgg supports hardening of `/cron` and `/upgrade.php` but not the stable version.

@spaghettimaster @DocCyblade Any ideas from you guys who know a bit more about php?

**Comment by JedMeister** [comment]
I reckon what you'll want to do is use Apache location directives to block access to all but localhost.

So something like:
```
      <Location /cron>
                Require host localhost
      </Location>
```
Actually, goggling suggests that this is possibly better (assuming it works as expected):
```
      <Location /cron>
                Require local
      </Location>
```

**Comment by OnGle** [comment]
Awesome, really simple and seems to work. Closing
