### ISSUE TITLE
Sahan-Eden should ideally create the initial admin account on firstboot

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#977]
Currently the Sahan-Eden appliance does not have a pre-configured Admin user. The first user to sign up is automatically assigned Admin privileges.

That's fine when you launch it locally, but on a publicly available server, that's not ideal. If someone malicious was in the right place at the right time they could create an account and be admin. It's probably unlikely, but worth protecting against regardless IMO.

**Comment by JedMeister** [comment]
@qq7 - can you please have a look at this one. It'll need a new inithook (to create a default admin account).

**Comment by qq7** [comment]
https://github.com/turnkeylinux-apps/sahana-eden/pull/6

**Comment by JedMeister** [comment]
closed by https://github.com/turnkeylinux-apps/sahana-eden/pull/6
