### ISSUE TITLE
Sahana-Eden broken when launched from AWS

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#978]
I can't believe that I'm still mucking around with v14.2 builds...! :cry: 

Anyway, the latest issue is that the Sahana-Eden appliance is broken on launch. It appears to be related to the MySQL tweak we applied to appease AWS (see [here](https://github.com/turnkeylinux/tracker/issues/934#issuecomment-341590537)). I'm pretty sure, it's a race condition that only occurs on that particular appliance and only on Amazon. Initially I thought that it may be some edge case to do with web2py (what Sahana-Eden is based on) but it turns out that the standalone web2py app works fine.

I have only tested (and confirmed) that it's consistently an issue on a t2.micro & t2.small. There is a chance that a larger server may work better? But I'm not going to explore that further currently.

**Comment by JedMeister** [comment]
Further investigation has confirmed that this is actually an issue on all AWS builds which use MySQL and have appliance names (or more correctly, inithook names) that precede `mysql` alphabetically. In the case of Sahana-Eden (which obviously doesn't appear to match this; `S` comes way after `M`) the inithook is named `20regen-eden-secrets`. I will be rebuilding these appliances today and hopefully they should be up on the Hub by the end of the week (tomorrow hopefully).

FWIW, the full list of affected appliances is:

- b2evolution
- bugzilla
- cakephp
- codeigniter
- collabtive
- concrete5
- django
- drupal7
- drupal8
- e107
- elgg
- espocrm
- etherpad
- ezplatform
- gallery
- gitlab
- gnusocial
- icescrum
- joomla3
- kliqqi
- limesurvey
- magento
- mambo
- mantis
- mediawiki
- mibew
- moodle

**Comment by OnGle** [comment]
What's the current status on this issue?

**Comment by JedMeister** [comment]
Thanks for the bump. Apologies on the slow response. 

We'll need to double check when we get to v15.0, but we should be good to close this for now.
