### ISSUE TITLE
git example doesn't work

### ISSUE THREAD

**Issue by antoneliasson** [turnkeylinux/tracker#980]
turnkey-revision-control-14.2-jessie-amd64

After installation I read the example checkout command lines on the Examples tab. For git this is `git clone git://192.168.1.230/git/helloworld`. I run this command:

```
[5.3.1]anton@miramis:~/tmp> git clone git://192.168.1.230/git/helloworld
Cloning into 'helloworld'...
fatal: remote error: access denied or repository not exported: /git/helloworld
```

I tried some variations which don't work either:

```
[5.3.1]{128}anton@miramis:~/tmp> git clone git://192.168.1.230/git/helloworld.git
Cloning into 'helloworld'...
fatal: remote error: access denied or repository not exported: /git/helloworld.git
[5.3.1]{128}anton@miramis:~/tmp> git clone git://192.168.1.230/helloworld        
Cloning into 'helloworld'...
fatal: remote error: access denied or repository not exported: /helloworld
[5.3.1]{128}anton@miramis:~/tmp> git clone git://192.168.1.230/helloworld.git
Cloning into 'helloworld'...
fatal: remote error: access denied or repository not exported: /helloworld.git
```

Subversion seems to work though:

```
[5.3.1]anton@miramis:~/tmp> svn co svn://192.168.1.230/svn/helloworld
A    helloworld/tags
A    helloworld/trunk
A    helloworld/trunk/helloworld.py
A    helloworld/trunk/README
A    helloworld/branches
Checked out revision 2.
```

**Comment by antoneliasson** [comment]
I would suggest that the example is changed to illustrate git access over SSH instead of the git:// protocol, as that is probably what most people are used to and expect.

**Comment by JedMeister** [comment]
Another good call! Actually, this should have been updated in the docs some time ago! But it quite clearly hasn't been! TBH, I'm not sure why. But I will pin this to the v15.0 milestone so it doesn't get forgotten again! 

Thanks for the bug report.

**Comment by JedMeister** [comment]
Hey @qrntz - while you're working on the revision control app, can you please have a quick look at this.

As I understand it, it's just a doc tweak that is required?!
