### ISSUE TITLE
No add_device.php in Root directory 

### ISSUE THREAD

**Issue by craigthackerx** [turnkeylinux/tracker#981]
Hi,

I have installed turnkey-observium-14.2-jessie-amd64.iso in a VirtualBox VM for a school project. I have had no problems adding Debian VMs & a Raspbian VM to the web interface and encountered my first problem with a Windows Host.

I have tried adding a Windows host to the Observium server via the web interface (on the Windows 10 VM) and receiving the following output:

> Adding host Windows10 community public port 161
> Trying v1 community public...
> No reply on community public using v1.
> Could not reach windows10 with given SNMP parameters using v1.

This error is also occuring for v2c. I find it likely that my Windows 10 configuration is causing issues somewhere along the lines, but I did general googling and have then read via this other GitHub post - https://github.com/turnkeylinux/tracker/issues/488 - that generally adding devices through the web interfaces is not recommended and to use the "add_device.php" located in the root directory of Observium.  The issue now arises that the "add_devices.php" cannot be located on the Observium CLI.

I am unsure on where to look for add_devices.php, and many issues that I have found online haven't solved the problem.  I have even added the Windows host to /etc/hosts file, and they are able to ping each other.

Any way of working around this issue?

Cheers.

EDIT: Problem (somewhat) solved.

Seems I've had a bad install on this VM, reinstalled while waiting on reply and add_device is present there.  No idea where it could have gone? Space magic I guess

**Comment by craigthackerx** [comment]
Forgot to add to this, I got the add device all working using the available documentation after reinstalling

Issue closed

**Comment by JedMeister** [comment]
Hi @craigthackerx - glad to hear you sorted out your issues. Although I have no idea where your original `add_device.php` file went?! Could it perhaps be a simple typo? (I note that you mention both `add_device.php` & `add_devices.php`).

Anyway, I'll close this for now. If you find a bug and/or have a feature request, please feel free to post here on GitHub. General troubleshooting and support stuff is probably best done on our [forums](https://www.turnkeylinux.org/forum)
