### ISSUE TITLE
Hub: misleading error message

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#983]
Trying to launch an appliance in EU West region ends up with error for me:
>Error

>You have reached your instance limit. Request an increase here: http://aws.amazon.com/contact-us/ec2-request/

While changing instance region resolves this

**Comment by JedMeister** [comment]
Another user reported something similar, but I didn't hear back. 

Did you ever hear back from AWS when you tried to increase your limit? Did that resolve it?

If not, please double check what you have in the [EU West region from within your AWS account](https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#). I'm not sure, but I'm wondering if maybe it was security groups or something like that causing the issues? I could be wrong...

**Comment by JedMeister** [comment]
I'm going to shut this now as I haven't had any further reports. @qq7 - please feel free to reopen if you have further info and/or hit this again.
