### ISSUE TITLE
https://releases.turnkeylinux.org/pve/aplinfo.dat.asc not found

### ISSUE THREAD

**Issue by fdellwing** [turnkeylinux/tracker#987]
Since yesterday the file is gone from your servers and proxmox users are unable to use `pveam update`.

Please provide a fix for that.

https://forum.proxmox.com/threads/pveam-update-fails-for-turnkeylinux-templates-on-5-1-41.39045/

**Comment by JedMeister** [comment]
Hi @fdellwing  Thanks for the heads up. 

That's really weird as I updated my PVE server only a few hours ago and it seemed to work fine.

Although I can confirm that it certainly is missing now! I'm not sure, but AFAIK, that's hosted on our mirror. I'll try to get someone onto it ASAP.

Thanks again.

**Comment by billyprice1** [comment]
this is also an issue for me

**Comment by amitjindal** [comment]
Not working for us as well.
Please fix ASAP.

**Comment by dave2492** [comment]
Still broken for me too.  My last successful update was on Jan 2nd.

**Comment by alonswartz** [comment]
I re-uploaded the latest versions. Will take a short while until it's propagated through the mirror network.  

We're investigating the cause of the issue. Based on my initial findings, the master mirror was rebooted (AWS maintenance) and the full directory structure wasn't automatically re-mounted successfully.
