### ISSUE TITLE
SuiteCRM password reset url in email is 127.0.0.1

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#988]
A user has reported that on SuiteCRM, when a user triggers a password reset email, the url to reset the password is given as 127.0.0.1.

My reading suggests that the workaround is to adjust `/var/www/suitecrm/config.php`, namely adjust the line:
```
'site_url' => 'http://127.0.0.1/',
```
to
```
'site_url' => 'http://YOUR_FQDN/',
```
E.g. if your site's domain is `www.example.com` then it would need to be:
```
'site_url' => 'http://www.example.com/',
```

Here's a quick commandline fix (change the first line to be your domain):
```
URL=www.example.com # change this to your domain
sed -i.bak "\|site_url|s|127.0.0.1|$URL|" 
```

AFAIK, that should work straight away, if not, restart Apache:
```
service apache2 restart
```

**Comment by JedMeister** [comment]
@spaghettimaster - assigning this to you seeing as you've worked on at least the SuiteCRM app (which is a fork of SugarCRM). Also being a star PHP guys, I'm sure it's well within your abilites! :smile:

**Comment by JedMeister** [comment]
Updated title and removed `sugarcrm` tag as per ￼#1098

**Comment by spaghettimaster** [comment]
Here is fix for suitecrm: https://github.com/turnkeylinux-apps/suitecrm/pull/7/files

Unfortunately Sugarcrm is dead now :(
