### ISSUE TITLE
rbenv is not being loaded into cron jobs

### ISSUE THREAD

**Issue by qq7** [turnkeylinux/tracker#993]
as reported in https://www.turnkeylinux.org/forum/support/fri-20180112-1025/out-box-redmine-issue

**Comment by JedMeister** [comment]
FWIW there is a doc page in the (`turnkeylinux/tracker`) wiki that covers testing cron jobs:

https://github.com/turnkeylinux/tracker/wiki/How-to-test-a-cron-job
